### ISSUE TITLE
Calling GRPC server from REST client. 

### ISSUE THREAD

**Issue by cpranav** [grpc/grpc-dotnet#1004]
1) Can a REST API call be made to a GRPC server? Call made will be plain HTTP GET call which I think equivalent in GRPC is unary call. We don't want to use GRPC Client but keep using REST API for calling, will it work? Is there a way to make it work, how difficult it would be?

2) If the answer to the above question is Yes, will it be possible to send JSON format back to REST client from a GRPC Server?

3) If we end up using GRPC client after seeing complexities it can involve calling from a REST client, can the GRPC server use dotnet core 3.0 while GRPC client uses .net framework? 

4) Can the GRPC client use grpc.core package as its based on .net framework while GRPC server used grpc-dotnet.

**Comment by JunTaoLuo** [comment]
gRPC and REST are completely different technologies, you cannot have a client using one communicate with a server using another.  That being said, if you are using grpc-dotnet, you can use an experimental package [Microsoft.AspNetCore.Grpc.HttpApi](https://www.nuget.org/packages/Microsoft.AspNetCore.Grpc.HttpApi/0.1.0-alpha.20305.2) to expose an HTTP endpoint for a gRPC service. See the sample at https://github.com/aspnet/AspLabs/tree/master/src/GrpcHttpApi/sample to see how that works. In a nutshell, after implementing the gRPC service, you can configure your server to serve both gRPC and REST requests.

As for interoperability between gRPC servers and clients, both Grpc.Core and grpc-dotnet clients and servers are all interoperable with eachother so scenarios described in 3 and 4 are supported.

**Comment by JamesNK** [comment]
This is answered. Closing
