### ISSUE TITLE
Error on Windows 7:  Bad gRPC response. Response protocol downgraded to HTTP/1.1.

### ISSUE THREAD

**Issue by PeterUherek** [grpc/grpc-dotnet#1006]
### What version of gRPC and what language are you using?

- Google.Protobuf  Version="3.12.4" 
- Grpc.Net.Client Version="2.30.0" 
- Grpc.Tools" Version="2.30.0"

### What operating system (Linux, Windows,...) and version?

- Windows 7, SP1, x64

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)

C:\Users\administrator\dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.302\

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  3.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.W
indowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

### What did you do?

I builded the grpc client on win 10 and I want to use it on win 7. The client works on win10 but does not work on win7 and I get error from grpc: _Bad gRPC response. Response protocol downgraded to HTTP/1.1._ I dont know what can be wrong. So do you have someone any idea what can be a problem? 

```
using Grpc.Net.Client;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Security.Cryptography.X509Certificates;

private GrpcChannel CreateChannel()
{
    var loggerFactory = LoggerFactory.Create(logging =>
    {
        logging.AddNLog(LogManager.Configuration).SetMinimumLevel(Microsoft.Extensions.Logging.LogLevel.Trace);
    });
    var cert = new X509Certificate2(Convert.FromBase64String(m_connectionConfig.PeerCertificatePfx), m_connectionConfig.PeerCertificatePassword);
    var handler = new HttpClientHandler();
    handler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator; 
    handler.ClientCertificates.Add(cert);

    string conntectionString = "https://" + m_connectionConfig.Hostname + ":" + m_connectionConfig.Port.ToString();

    var grpcOption = new GrpcChannelOptions
    {
        HttpHandler = handler,
        LoggerFactory = m_configuration.DebugMode ? loggerFactory : null,
    };

    return GrpcChannel.ForAddress(conntectionString, grpcOption);
}
```

### What did you expect to see?
It should connect without error. 

### What did you see instead?

Error: message: 
```
Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Bad gRPC response. Response protocol downgraded to HTTP/1.1.")
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, 
```

**Comment by JamesNK** [comment]
HTTP/2 is not supported on Windows 7

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1#http2-support

**Comment by PeterUherek** [comment]
Ok.. That explain lot. Is there any solution or possible workaround?

**Comment by JamesNK** [comment]
You need a more modern operating system to run HTTP/2 + TLS.

If you are ok with no using TLS then HTTP/2 (and gRPC) might work without TLS.

**Comment by JamesNK** [comment]
This is answered. Closing

**Comment by Dunge** [comment]
I'm able to have a gRPC Client working on Windows 7 by disabling TLS by:

- Calling `AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);` on the client and connecting via http only in the URL.
- Configuring the server NOT to call `UseHttpsRedirection()` and configuring the HTTP port to use HTTP2 only (`options.Listen(IPAddress.Any, 80, listenOptions => { listenOptions.Protocols = HttpProtocols.Http2; });`)

The HTTPS binding can still work for the gRPC clients on Windows10 and the normal MVC web server.

Unfortunately, disabling HTTPS redirection kinda break the normal MVC web server support if the customer don't manually write https in the URL.

Is there a way in ASP.NET to enable HTTPS redirection only on one endpoint (MVC) and to disable it for the other (gRPC)?

**Comment by JamesNK** [comment]
You could white your own middleware to do that and look at the request content type.

If you want built in support then that’s a question you should ask at the dotnet/aspnetcore repo.

**Comment by Dunge** [comment]
Thanks @JamesNK 

Copying code from https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Middleware/HttpsPolicy/src/HttpsRedirectionMiddleware.cs and adding a 

    if (context.Request.ContentType == "application/grpc")
        return _next(context);

in the Invoke() method would have worked if my previous analysis was true that the redirection was the problem.

Unfortunately no. Forcing the listen option on port 80 to Http2 only seems to break services for web browsers before even handling the middlewares. The web browser act as if it's a file to download, and the web server don't even reach the middleware code.
