### ISSUE TITLE
GRPC server and console applications

### ISSUE THREAD

**Issue by Code-Codex** [grpc/grpc-dotnet#1010]
In 5.0 is there a way to create a grpc server console application without bringing in asp.net? Also are there any other transports supported other than http?

**Comment by davidfowl** [comment]
Nope, grpc-dotnet is built on asp.net core. Multiple transport support will work in .net core 5.0+.

**Comment by davidfowl** [comment]
That said, it'll work fine in a console application. Just add the package and go

**Comment by JamesNK** [comment]
Closing as answered.
