### ISSUE TITLE
How to throw exceptions with details

### ISSUE THREAD

**Issue by kelvinsand** [grpc/grpc-dotnet#1011]
I am new to grpc and I am not sure how to proceed to throw detailed exceptions. Searching I found that there is the Google.Rpc package that provides the status class as well as other helpers for exceptions. But, this status is not the same received by RPCException. I would like to know how to proceed.

**Comment by lamLeX** [comment]
Per this documentation, https://grpc.io/docs/guides/error/, grpc provides a list of error code.
You could consider this grpc status code similar to HTTP status code meant for Restful API.
When an exception is thrown either on client or on server side, the RPCException is raised on the other side with the proper status code. 

If you want to communicate the exception to the other side, I believe you need to handle it and serialize the exception into your message to relay it to the other side. 

I used the [oneof](https://developers.google.com/protocol-buffers/docs/proto3#oneof) to achieve this purpose.
Your message may look like this
```proto
message Response{
	oneof reply{
		string exception = 1;
		ResponseMessage result = 2;
	}
}
```

This is one solution, I have thought of. If anybody had a better idea, I'm looking forward to seeing their solution.

**Comment by JamesNK** [comment]
Two options:

1. What @lamLeX suggested. `exception` could be a string or a complex message with details about the exception
2. In configuration set `EnableDetailedErrors` to true. [Link to docs](https://docs.microsoft.com/en-us/aspnet/core/grpc/configuration?view=aspnetcore-3.1). When true the status message detail has information about the server error.

**Comment by JamesNK** [comment]
Closing as answered.

**Comment by kelvinsand** [comment]
Sorry for the delay in giving feedback. I was really busy and I had to put that aside for a while.

I don't think I was very clear when I asked my question, but even then @lamLeX got really close to what I need.
The treatment I need is about field validations. Whereas exceptions are costly and should only be used for exceptional things and not for flow control and Based on [RFC 7807](https://tools.ietf.org/html/rfc7807) I built this example. I would like to know your opinion.

```
syntax = "proto3";

package user;

service UserService {
  rpc AddUser(User) returns (Reply);
}

message Reply { 
    oneof user_reply {
        User user = 1;
        Error error = 2;
    }
}

message User {
  string name = 1;
  int32 age = 2;
}

message Error {
    string title = 1;
    string detail = 2;
    // The status, which should be an enum value of [google.rpc.Code].
    int32 status = 3;

    message FieldViolation {
      string field = 1;
      repeated string messages = 2;
    }
    // I thought about using the map type here, but it is necessary that for each field a list of messages is returned
    repeated FieldViolation field_violations = 3;
}
```
