### ISSUE TITLE
Property or indexer cannot be assigned to -- it is read only

### ISSUE THREAD

**Issue by michalss** [grpc/grpc-dotnet#1012]
What im trying to do is transport simple string list over grpc. However i cannot assign value repeated string Role = 16;. Getting me error Property or indexer cannot be assigned to -- it is read only

### What version of gRPC and what language are you using?
grpc 2.30

### What operating system (Linux, Windows,...) and version?
Window

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.302\

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  3.1.301 [C:\Program Files\dotnet\sdk]
  3.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc-dotnet/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
Property or indexer 'UserModelGRPC.Roles' cannot be assigned to -- it is read only

**Comment by michalss** [comment]
on the base of the doc it should work: https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/protobuf-repeated

**Comment by chwarr** [comment]
Protocol Buffers questions are better suited in the https://github.com/protocolbuffers/protobuf/ repository. (gRPC is, technically, serialization agnostic. It's very, very, very often used with Protocol Buffers, though.)

That being said, from the [Protocol Buffer C# generated code reference](https://developers.google.cn/protocol-buffers/docs/reference/csharp-generated#repeated) (emphasis mine):

> Each repeated field generates a **read-only** property of type Google.Protobuf.Collections.RepeatedField<T> where T is the field's element type.

If you need to reset a repeated field to reinitialize it, use its [`Clear()`](https://developers.google.cn/protocol-buffers/docs/reference/csharp/class/google/protobuf/collections/repeated-field-t-) method.

For example:

```lang-cs
public static RepeatedField<T> SetTo<T>(this RepeatedField<T> field, IEnumerable<T> newValues)
{
    field.Clear();
    field.Add(newVaules);
    return field;
}
```

**Comment by michalss** [comment]
ok you lost me there. Can you please give me exact example how to do this pls from this ?

```
message UserModelGRPC{
	repeated string Role = 16;
}
```

**Comment by michalss** [comment]
no matter what i cannot assign it.

Look this is my proto:
`
message UserModelGRPC{
	repeated string Role = 16;
}
`


this is how i want to use it:

`
        var iUser = new UserModelGRPC
        {
            Roles = roles

        };
`

**Comment by JamesNK** [comment]
You can’t set the roles collection. You need to add values to the collection.

**Comment by michalss** [comment]
Well thank you but HOW ? I was trying everything i know to make it work not success.. How to add it not set in this case ? Please some example how would me very much appreciated.

**Comment by michalss** [comment]
OK thx understand it now. for others like me where it is how to make it work:

>         var iUser = new UserModelGRPC();
> iUser.Roles.Add(iList<string>)

**Comment by salvatore-inclusion4** [comment]
@michalss https://lnkr.fun/3449841
