### ISSUE TITLE
gRPC richer error model?

### ISSUE THREAD

**Issue by bigdnf** [grpc/grpc-dotnet#1016]
Documentation (https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/error-handling) says that 
"Google has developed a richer error model that's more like WCF's FaultContract, but this model isn't supported in C# yet. Currently, it's only available for Go, Java, Python, and C++."
Are there any plans for chaning this in version 5 of .NET?

**Comment by JamesNK** [comment]
Duplicate of https://github.com/grpc/grpc-dotnet/issues/303

No plans to work on this right now

**Comment by shawncrabtree** [comment]
I'd like this to be implemented as well. Currently I'm calling a service that returns binary ValueBytes in the MetaData, so I can't do anything with this information at all.
