### ISSUE TITLE
Read response headers in Asp.NET Core GRPC client?

### ISSUE THREAD

**Issue by bigdnf** [grpc/grpc-dotnet#1017]
I can see that I can easily read headers on server side, write them in response but on client side I see no option how to read headers that are send by server?

**Comment by JamesNK** [comment]
https://github.com/grpc/grpc-dotnet/blob/e02fd189d1334d3c29ade34e871684c5b2b3376c/test/Grpc.Net.Client.Tests/ResponseHeadersAsyncTests.cs#L59

```cs
var client = new GreeterClient(Channel);
var call = client.SayHelloAsync(request);

var headers = await call.ResponseHeadersAsync;
var reply = await call;
```

**Comment by bigdnf** [comment]
Ok so it looks like headers can be read first. Are there any potential performance problems reading messages in such way?

**Comment by JamesNK** [comment]
Not that I can think of

**Comment by bigdnf** [comment]
Inssue has bee answered

**Comment by yogyogi** [comment]
ResponseHeadersAsync property is missing in .NET 8.0. Any suggestions?
