### ISSUE TITLE
Using an interceptor in Blazor WASM

### ISSUE THREAD

**Issue by ChristianWeyer** [grpc/grpc-dotnet#1019]
While trying to use the Logger sample interceptor in a Blazor WASM application, I got kind of stuck.

Currently, I am trying to do this:
```
builder.Services.AddScoped(services =>
            {
                var baseAddressMessageHandler = services.GetRequiredService<BaseAddressAuthorizationMessageHandler>();
                baseAddressMessageHandler.InnerHandler = new HttpClientHandler();
                var grpcWebHandler = new GrpcWebHandler(GrpcWebMode.GrpcWeb, baseAddressMessageHandler);

                var channel = GrpcChannel.ForAddress(builder.HostEnvironment.BaseAddress, new GrpcChannelOptions { HttpHandler = grpcWebHandler });

                var invoker = channel.Intercept(new ClientLoggerInterceptor());
                // ... what to do with invoker here?
                return channel;
            });
```

How should we return the channel back to DI with the logger 'enabled'?
Thanks.

**Comment by JamesNK** [comment]
Return the invoker and create with it.

**Comment by ChristianWeyer** [comment]
@JamesNK - sorry for my ignorance.
The client code currently using the channel looks like this (it is a service in a Blazor app) - using @mgravell's code-first approach:

```
    public class ConferencesServiceGrpc
    {
        private ConfTool.Shared.Contracts.IConferencesService _client;
        private IConfiguration _config;
        private string _baseUrl;

        public ConferencesServiceGrpc(IConfiguration config, GrpcChannel channel)
        {
            _config = config;
            _baseUrl = _config["BackendUrl"];
            _client = channel.CreateGrpcService<ConfTool.Shared.Contracts.IConferencesService>();
        }

        public async Task<List<ConferenceOverview>> ListConferencesAsync()
        {
            var result = await _client.ListConferencesAsync();

            return result.ToList();
        }
    }
```
How would we use the invoker in such a scenario?
All I can see on the CallInvoker does not seem to match what would be needed.

![image](https://user-images.githubusercontent.com/888718/91613063-17584280-e97f-11ea-93df-9371af215b22.png)

Thanks!

**Comment by ChristianWeyer** [comment]
This would work:

`_client = ProtoBuf.Grpc.Configuration.ClientFactory.Default.CreateClient<ConfTool.Shared.Contracts.IConferencesService>(invoker);
`
Is this the way you would do it @mgravell ?

**Comment by mgravell** [comment]
@ChristianWeyer

```
GrpcClientFactory.CreateGrpcService<TService>(CallInvoker)
```

Not currently an extension method, but it can be with the simple addition of a `this`

**Comment by ChristianWeyer** [comment]
Thanks, gentlemen - @JamesNK and @mgravell !
