### ISSUE TITLE
Other repeated message type not supported?

### ISSUE THREAD

**Issue by saariniemi** [grpc/grpc-dotnet#1020]
With proto3 you should be able to use other repeated message types.
It seems like it's not supported since the code generated is missing a setter.
Am I doing something wrong or is this not supported?

https://developers.google.com/protocol-buffers/docs/proto3#other

Protobuf:

```
message GetWeatherForecastsResponse {
  repeated WeatherForecast forecasts = 1;
}

message WeatherForecast {
  google.protobuf.Timestamp date = 1;
  repeated int32 temperatureC = 2; // REPEATED VALUE WILL BE READONLY CANT BE SET
  string summary = 3;
}
```

Generated temperatureC code:

```
    /// <summary>Field number for the "temperatureC" field.</summary>
    public const int TemperatureCFieldNumber = 2;
    private static readonly pb::FieldCodec<int> _repeated_temperatureC_codec
        = pb::FieldCodec.ForInt32(18);
    private readonly pbc::RepeatedField<int> temperatureC_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> TemperatureC {
      get { return temperatureC_; }
    }

```

**Comment by chwarr** [comment]
Take a look at https://github.com/grpc/grpc-dotnet/issues/1012 and see if that answers your question.

I have a [PR open to improve the gRPC for WCF developers documentation about repeated fields](https://github.com/dotnet/docs/pull/19908) to help address this common question.

**Comment by JamesNK** [comment]
https://docs.microsoft.com/en-us/aspnet/core/grpc/protobuf?view=aspnetcore-3.1#collections
