### ISSUE TITLE
Lack of features for console applications compared to Grpc.Core package.

### ISSUE THREAD

**Issue by Tylertron1998** [grpc/grpc-dotnet#1027]
### Is your feature request related to a problem? Please describe.
With Grpc.Core, you can easily create a server with a simple console application - this does not seem to be the case with Grpc.Net - or, if it is possible, it is most certainly hard to do. It would be nice to be able to do similar to Grpc.Core, where you simply define services, and bind them to a server inside your application, and run said server. Instead, it seems, it is required to use asp.net - which is not great.

### Describe the solution you'd like
An API that is the same as Grpc.Core - you can create services, bind them to a server instance, and run the server yourself.

### Describe alternatives you've considered
Grpc.Core

### Additional context
Right now, the solution is fairly simple -- just use Grpc.Core; however, this isn't ideal; from what I understand it means native dependencies, which are annoying for debugging, and publishing.

**Comment by JamesNK** [comment]
> With Grpc.Core, you can easily create a server with a simple console application - this does not seem to be the case with Grpc.Net

All ASP.NET Core websites are console apps by default. `dotnet new grpc` creates a gRPC service hosted in a console app. What are you finding difficult?

**Comment by Tylertron1998** [comment]
example code with Grpc.Core:
```cs
            var channel = new Channel("localhost:8000", ChannelCredentials.Insecure);
            var server = new Grpc.Core.Server
            {
                Ports = { new ServerPort("localhost", 8080, ServerCredentials.Insecure) },
                Services = { BackendService.BindService(new MonitorServer()) }
            };
            
            server.Start();
            await Task.Delay(-1);
```

from what I can see; there is no such class as "Server" in Grpc.Net - so setting it up as so is not possible within a console application.

**Comment by JamesNK** [comment]
1. Open a console
2. `dotnet new grpc`
3. `dotnet run`

Notice how the website launches in a console app, and writes logging to the console. All ASP.NET Core websites are console apps by default.

**Comment by Tylertron1998** [comment]
The problem here is, that it comes with all the additional code overhead asp.net core does - having to create a IHostBuilder, appSettings.json, etc; the way of creating a server in grpc.core is, in my opinion, much nicer and simpler. Having a similar api exposed is a nice option for developers; those who prefer explicitically creating a server and running it, rather then having it routed behind asp.net, and having to deal with the extra code of asp.net core. It also means there is a http server being spun up in the background - which in most cases, the developer has no use for - and they have to explicitly handle that in code.

**Comment by JamesNK** [comment]
You don't need JSON files. You don't even need Startup.cs. Everything can be simplified down to:

```cs
public class Program
{
    public static void Main(string[] args)
    {
        CreateHostBuilder(args).Build().Run();
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(webBuilder =>
            {
                webBuilder.Configure(app =>
                {
                    app.UseRouting();
                    app.UseEndpoints(endpoints => endpoints.MapGrpcService<GreeterService>());
                });
                webBuilder.ConfigureKestrel(options =>
                    options.ConfigureEndpointDefaults(o => o.Protocols = HttpProtocols.Http2));
            })
            .ConfigureServices(services => services.AddGrpc());
}
```

Grpc.AspNetCore runs in ASP.NET Core. A requirement of that is running in a host, using DI, and using routing.

**Comment by Tylertron1998** [comment]
That's unfortunate - any chance of getting a mirrored, non ASP.NET Core backed version of Grpc.Core - much like Grpc.Net? Or is ASP.NET Core a hard dependency?

**Comment by JamesNK** [comment]
I'm not sure what you're asking for. If you don't want gRPC on ASP.NET Core then use Grpc.Core. It already exists.

**Comment by Tylertron1998** [comment]
From my understanding there are fundamental differences between Grpc.Net and Grpc.Core - right? Such as Grpc.Net being completely managed - which is certainly a desirable trait - it would be nice to be able to reap these benefits with a similar api.

**Comment by JamesNK** [comment]
Making Grpc.AspNetCore not use ASP.NET Core is not possible without a full rewrite. That's outside the scope of this project.

If you have problems with the ASP.NET Core API you could raise them in the ASP.NET Core project.
