### ISSUE TITLE
Grpc.Core.RpcException:“Status(StatusCode="Cancelled", Detail="Cancelled"……

### ISSUE THREAD

**Issue by JACKCHEN96** [grpc/grpc-dotnet#1028]
Hi, I'm getting this error from client side in CallInvoker.BlockingUnaryCall(__Method_SayHello, null, options, request) :
Grpc.Core.RpcException:“Status(StatusCode="Cancelled", Detail="Cancelled", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1598237258.589000000","description":"Error received from peer ipv4:127.0.0.1:50051","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\surface\call.cc","file_line":1055,"grpc_message":"Cancelled","grpc_status":1}")”

#### Description

I'm just testing the connection of client and server on MS unit test and get the RpcException. The simple Greeter service works well on my demo (which is a console program), but get error in unit test. So the problem description can be simplified as following:

Unit test Client & Unit test server CANCELLED;
Demo Client & Demo Server  YES;
Unit test Client & Demo Server YES;
Demo Client & Unit test Server CANCELLED.

#### Environment details

  - OS: Windows
  - .NET version: 4.6.2
  - Package name and version: .NET framework 4.7.2 & Grpc.Core 2.24.0 & protobuf-net 2.3.7.0

#### Steps to reproduce

  1. Simple Greeter service on unit test
  2. Using "protobuf-net" for serialization/deserialization

Thanks!

**Comment by JamesNK** [comment]
Grpc.Core questions should be asked at https://github.com/grpc/grpc. Recreate your issue there.
