### ISSUE TITLE
Streaming Backpressue/Flow Control

### ISSUE THREAD

**Issue by AlgorithmsAreCool** [grpc/grpc-dotnet#104]
Are you folks tracking streaming flow-control/backpressure on your roadmap? Because I think it is a really important aspect of building robust services.

[In the past I've seen GRPC services accept and buffer streaming messages extremely aggressively.](https://github.com/grpc/grpc/issues/13955). This lead to heavy memory usage on the server due to GRPC internal buffering of messages for many seconds until the handlers slowly drained the buffers. It also increases the cost of a server crash since thousands of buffered messages could be lost at once.

I'd love if there was a mechanism to limit buffering and to apply back pressure to fast producers.

**Comment by JamesNK** [comment]
@davidfowl can you comment here. What does Kestrel offer out of the box via pipelines?

**Comment by davidfowl** [comment]
Kestrel implements HTTP/2 flow control and shouldn't be reading ahead too aggressively. The relevant settings are here:

Connection limits:
https://github.com/aspnet/AspNetCore/blob/8f49bdf195efbcf3172eae8b3a8acbf862777b83/src/Servers/Kestrel/Core/src/Http2Limits.cs#L101-L107

Stream limits (this one is more relevant):
https://github.com/aspnet/AspNetCore/blob/8f49bdf195efbcf3172eae8b3a8acbf862777b83/src/Servers/Kestrel/Core/src/Http2Limits.cs#L123-L130

cc @halter73 for more details

**Comment by AlgorithmsAreCool** [comment]
That....is pretty great. Fantastic work folks.
