### ISSUE TITLE
when using AddGrpcClient, Grpc Channel is not reused for clients of the same type?

### ISSUE THREAD

**Issue by NetGH** [grpc/grpc-dotnet#1044]
Why grpc clients of the same type from the same service provider do not share the same channel? It supposes to reuse the same channel for the same address for efficiency right?

`            var services = new ServiceCollection();
            services.AddGrpcClient<AnyNamespace.AnyClient>(options =>
            {
                options.Address = new Uri("http://localhost");
            });
            var serviceProvider = services.BuildServiceProvider();

            var dummyRpcClient = serviceProvider.GetRequiredService<AnyNamespace.AnyClient>();
            var anotherDummyRpcClient = serviceProvider.GetRequiredService<AnyNamespace.AnyClient>();
            Assert.AreNotSame(dummyRpcClient, anotherDummyRpcClient);

            var callInvokerField =
                typeof(ClientBase).GetField("callInvoker", BindingFlags.Instance | BindingFlags.NonPublic);

            var callInvoker = (CallInvoker)callInvokerField.GetValue(dummyRpcClient);
            var anotherCallInvoker = (CallInvoker)callInvokerField.GetValue(anotherDummyRpcClient);

            var invokerField =
                callInvoker.GetType().GetField("invoker", BindingFlags.Instance | BindingFlags.NonPublic);

            var invoker = invokerField.GetValue(callInvoker);
            var anotherInvoker = invokerField.GetValue(anotherCallInvoker);

            var channelProperty = invoker
                .GetType()
                .GetProperty(nameof(Channel), BindingFlags.NonPublic | BindingFlags.Instance);

            var channel = (GrpcChannel) channelProperty.GetValue(invoker);
            var anotherChannel = (GrpcChannel)channelProperty.GetValue(anotherInvoker);

            Assert.AreSame(channel, anotherChannel);`

**Comment by JamesNK** [comment]
At the moment the `HttpClient` is cached but a new `GrpcChannel` is created for each client. This is ok because `HttpClient` is where the heavy state, e.g. the connection, is stored.

Is not reusing the channel a problem?

**Comment by d1820** [comment]
@JamesNK  that seems contradictory to the Best Practice recommendations from Microsoft  [Reuse gRPC channels](https://docs.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-5.0). Am I missing something?

**Comment by JamesNK** [comment]
HttpClient is the important thing to reuse *right now*.

In the future more on GrpcChannel will be important. When that happens the client factory will be updated to reuse the channel.
