### ISSUE TITLE
UDP client/transport for GRPC

### ISSUE THREAD

**Issue by tiwariashish86** [grpc/grpc-dotnet#1049]
Is it possible to use UDP client/transport underneath GRPC? It would be really good for gaming applications.

**Comment by JamesNK** [comment]
It will probably be possible with HTTP/3. HTTP/3 is very new and not well supported yet by clients or servers so I haven't tried it yet.

**Comment by tiwariashish86** [comment]
As per https://grpc.github.io/grpc/core/md_doc_core_transport_explainer.html, it seems you can either use Cronet transport or implement your own transport. Is that true for GRPC C# as well? Basically i am trying to develop a gaming application with GRPC C# on unity. So I am trying to find out if I can use a UDP client underneath and how much effort that would require to implement?

**Comment by JamesNK** [comment]
Yes https://docs.microsoft.com/en-us/aspnet/core/grpc/interprocess?view=aspnetcore-5.0

However `SocketsHttpHandler.ConnectCallback` is probably not support on Unity.

**Comment by tiwariashish86** [comment]
Yeah You are right. One more thing so GRPC must be using some HTTPClient underneath. Is it possible to expose that for some other purposes like normal rest calls to CDN?

**Comment by chwarr** [comment]
You are looking for .NET's [HttpClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netcore-3.1). gRPC for .NET uses this underneath. (It also uses some lower level abstractions too. For more details, you'll want to read the code in this repo.)

**Comment by tiwariashish86** [comment]
I am looking at their code but I dont see reference for HTTPClient in the code. Since my use case is related to unity for gaming, I am using unity version of GRPC lib https://packages.grpc.io/archive/2019/11/6950e15882f28e43685e948a7e5227bfcef398cd-6d642d6c-a6fc-4897-a612-62b0a3c9026b/csharp/grpc_unity_package.2.26.0-dev.zip. I want expose this HTTPClient for other purpose like CDN requests as well to avoid multiple HttpClient maintenance.

**Comment by JamesNK** [comment]
That is Grpc.Core. It is a different gRPC implementation and uses its own HTTP/2 library. Ask questions about it at https://github.com/grpc/grpc. It isn't a general purpose HTTP client.

**Comment by JamesNK** [comment]
Closing as answered.
