### ISSUE TITLE
Performance issue related to Grpc client

### ISSUE THREAD

**Issue by rampratapa** [grpc/grpc-dotnet#1064]
I am trying to load test Grpc ( client and service )using .Net Core 3.1 in AKS,  I have three microservices written ,NET core and deployed to AKS cluster and all are injected using DI during startup

```
 services.AddGrpcClient<Validator.ValidatorClient>(o =>
            {
                AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
                o.Address = new Uri(validatorUrl);
              //  o.ChannelOptionsActions.Add("grpc.keepalive_permit_without_calls", 1);


            }).EnableCallContextPropagation(o => o.SuppressContextNotFoundErrors = true)
             .ConfigurePrimaryHttpMessageHandler(() =>
                    {
                        var handler = new HttpClientHandler();
                        handler.MaxConnectionsPerServer = 300;

                        return handler;
                    });

 services.AddGrpcClient<Translator.TranslatorClient>(o =>
            {
                AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
                o.Address = new Uri(translatorUrl);
                

            }).EnableCallContextPropagation(o => o.SuppressContextNotFoundErrors = true)
             .ConfigurePrimaryHttpMessageHandler(() =>
              {
                  var handler = new HttpClientHandler();
                  handler.MaxConnectionsPerServer = 300;

                  return handler;
              });

services.AddGrpcClient<Connect.ConnectClient>(o =>
            {
                AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
                o.Address = new Uri(connectorUrl);

            }).EnableCallContextPropagation(o => o.SuppressContextNotFoundErrors = true)
             .ConfigurePrimaryHttpMessageHandler(() =>
                    {
                        var handler = new HttpClientHandler();
                        handler.MaxConnectionsPerServer = 300;

                        return handler;
                    });

```

and these are injected into the Business class
   ```
      private readonly ILogger<OrchestratorService> _logger;
        private readonly Validator.ValidatorClient _validator;
        private readonly Translator.TranslatorClient _translator;
```

and being called while executing the code.
 var validatorResponse = await _validator.ValdiateAsync(validatorRequest);

I use Jmeter to send a http post to a RESTful service and that service invoke these microservice using DI.

As these are deployed in Kubernetes as pods,  I have used Service ulrs while injecting these microservices in the proxy.

during the performance testing,  randomly it is taking longer to get the response or execute the grpc methods.  generally it takes 100 to 200ms,  but occasionally it is taking about 20 to 40 seconds.  There is no consistency in the throughput.  I thought this could httpclient socket exhaustion case ( I did not observe any exceptions) and I added   handler.MaxConnectionsPerServer = 300; thinking this will improve but still I am seeing the same issue.   _My question is,  what are the parameters/Properties I can look to improve the performance of Grpc client or service to fine tune._  The business logic in these microservices are very simple.   The AKS is built on Linux OS.

The same functionality written in Go and deployed to the same cluster works well and demonstrate consistent throughput.

Please let me know if you need more information.

Thanks
Ram

**Comment by JamesNK** [comment]
If there is a lot of load on a channel it is possible you have hit the maximum number of concurrent requests allowed on one HTTP/2 connection

Some docs that discuss this with some workarounds - https://docs.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-3.1#connection-concurrency

In .NET 5 a channel will automatically create additional connections if the maximum request limit is hit.

**Comment by rampratapa** [comment]
James,  thank you for quick response,  It is not that big of load,  I started with 60 messages per second and end the average around 30 messages per second after 25minutes, where as the same type of functionality with go Grpc,  I am able to get 120 messages per second consistently .   I am not sure how to manage Channels using dependency injection.  Let me upgrade the project to .net 5 and see if that improves the performance.

Thank you for your help.

**Comment by rampratapa** [comment]
Here is the debugging information related to Grpc calls from .net 3.1 ( I switched back to 3.1 from NET 5)

[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 POST http://orchstrservice:5002/WorkFlow.Orchestrate/Process application/grpc 
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'gRPC - /WorkFlow.Orchestrate/Process'
[40m[37mdbug[39m[22m[49m: Grpc.AspNetCore.Server.ServerCallHandler[10]
      Reading message.
[40m[32minfo[39m[22m[49m: Mdrx.Hub.Eligibility.Orchestrator.OrchestratorService[0]
      Grpc OrchestratorService Called
**_[40m[32minfo[39m[22m[49m: System.Net.Http.HttpClient.ValidatorClient.ClientHandler[101]
      Received HTTP response after 2903.4576ms - OK
[40m[32minfo[39m[22m[49m: System.Net.Http.HttpClient.ValidatorClient.LogicalHandler[101]
      End processing HTTP request after 2903.4931ms - OK_**
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[13]
      Reading message.
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[4]
      Finished gRPC call.
Metrics:Time taken Validatorb7bf71da-d845-43fd-b96e-be6501b4a821: 2916.0351ms
[40m[32minfo[39m[22m[49m: Mdrx.Hub.Eligibility.Orchestrator.OrchestratorService[0]
      Comleted validations
[40m[32minfo[39m[22m[49m: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.1.6 initialized 'EnrollmentContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[1]
      Starting gRPC call. Method type: 'Unary', URI: 'http://validateservice:5003/Validator.Validator/Valdiate'.
[40m[32minfo[39m[22m[49m: System.Net.Http.HttpClient.ValidatorClient.LogicalHandler[100]
      Start processing HTTP request POST http://validateservice:5003/Validator.Validator/Valdiate
[40m[32minfo[39m[22m[49m: System.Net.Http.HttpClient.ValidatorClient.ClientHandler[100]
      Sending HTTP request POST http://validateservice:5003/Validator.Validator/Valdiate
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[18]
      Sending message.
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 POST http://orchstrservice:5002/WorkFlow.Orchestrate/Process application/grpc 
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'gRPC - /WorkFlow.Orchestrate/Process'
[40m[37mdbug[39m[22m[49m: Grpc.AspNetCore.Server.ServerCallHandler[10]
      Reading message.
[40m[32minfo[39m[22m[49m: Mdrx.Hub.Eligibility.Orchestrator.OrchestratorService[0]
      Grpc OrchestratorService Called
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[1]
      Starting gRPC call. Method type: 'Unary', URI: 'http://validateservice:5003/Validator.Validator/Valdiate'.
[40m[32minfo[39m[22m[49m: System.Net.Http.HttpClient.ValidatorClient.LogicalHandler[100]
      Start processing HTTP request POST http://validateservice:5003/Validator.Validator/Valdiate
[40m[32minfo[39m[22m[49m: System.Net.Http.HttpClient.ValidatorClient.ClientHandler[100]
      Sending HTTP request POST http://validateservice:5003/Validator.Validator/Valdiate
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[18]
      Sending message.

I put the debug statement in the method and it is taking less 100ms.  Based on the above log, it took 2903.4931ms  and not sure where is the remining time being spent.  Any idea?

Thanks
Ram

**Comment by rampratapa** [comment]
Hi All,  can any one help on how to fine tune or improve the performance of the grpc client and server.  Or how to profile these two to find the bottleneck.  I did the simple test with one proxy with RESTful API receiving messages and invoke grpc service and return hello world message.  The following are the results.

the following are the steps and methodology used.
•	Create a proxy using kestrel with http Post.
•	Create another grpc component and this will return a simple message ( hello world)
•	Used the grpc client in the porxy and executed the method.
•	The response received from grpc call is returned.
•	There services are containerized and deployed to AKS.
•	Used the jmeter to pump the messages.

![mypick](https://user-images.githubusercontent.com/16505054/94885981-5d4d6e00-0437-11eb-9054-4c8743846c40.jpg)

Though it shows 30 instance, we got only 4 each 

![performance](https://user-images.githubusercontent.com/16505054/94886062-9be32880-0437-11eb-98ec-ead26884883e.jpg)

If you can take a look,  it starts with very low response time and slowly the response times increased which will reflect on decreased throughput.

If you look the one of the samples that took 2.7 seconds it is spent in proxy ( first component) and all it was doing is to call grpc method.

![Specific Event](https://user-images.githubusercontent.com/16505054/94886139-cb923080-0437-11eb-88f6-5f816426909e.jpg)

the following is the kestrel configuration on proxy
"AllowedHosts": "*",
  "Kestrel": {
    "Limits": {
      "MaxConcurrentConnections": 1000,
      "MaxConcurrentUpgradedConnections": 1000
    },


The following is grpc client configuration.

services.AddGrpcClient<Orchestrate.OrchestrateClient>(o =>
                {
                    AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
                    o.Address = new Uri(orchestratorUrl);

                }).EnableCallContextPropagation(o => o.SuppressContextNotFoundErrors = true)
                .ConfigurePrimaryHttpMessageHandler(() =>
                {
                    var handler = new HttpClientHandler();
                    handler.MaxConnectionsPerServer = 300;
                    return handler;
                });



I ran the same test with a fixed number of messages like 6500 message per minute which approximately 100 msg per second and observing the same behavior.

I am using 4 nodes with Standard_DS2_v2

Thank you for your help.

Thanks
Ram

**Comment by JamesNK** [comment]
It is hard to say why you get the reported times. The client logging says it takes 2.7 seconds, but that is the only useful information there. Server logging is needed to see where than 2.7 seconds time is being spent on the server.

You mentioned you're using Kubernetes and multiple instances. Load balancing requires additional work when using HTTP/2 - https://docs.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-3.1#load-balancing

**Comment by rampratapa** [comment]
James,  Good evening,  Thank you for your response.  I looked into the article on grpc load balancing and I felt it may not required as when I observed the traffic on the pods using Azure monitoring,  I am seeing the traffic across all pod with equal percentage.  We are not ready to put mesh technology in AKS as it complicates the management and overhead on the infrastructure.  Is there any other thought to improve the performance. 

Related to response time 2.7 seconds,  as I got only two grpc services,  proxy is client and orchestrator is server.   The server only took 1.9 ms,  the client took about 2.1 seconds and not sure what is 611ms.   I am not sure,  what tool give more details about Grpc client and server to capture more details to understand the issue.  if you have any thought,  please let me know so that I can capture.

Thank you for your help.

thanks
Ram

**Comment by JamesNK** [comment]
The logging that the gRPC client captures doesn't include underlying logging from the HTTP/2 client. Extra tracing is available from the .NET HTTP library, but it is more difficult to capture.

The event source name is `Microsoft-System-Net-Http`.

Discussion about tracing here - https://developers.redhat.com/blog/2019/12/23/tracing-net-core-applications/

Capturing tracing information inside Kubernetes is difficult. One solution is using dotnet-monitor. More information here - https://devblogs.microsoft.com/dotnet/introducing-dotnet-monitor/

**Comment by rampratapa** [comment]
@JamesNK ,  Good evening,  Thank you for the articles.  I will try to spend sometime this week to enable tracking using the dotnet-monitor and see if I can capture it.  Meanwhile,  I changed the microservices as RERSTful ( all grpc microservices are exposed as Rest),  I am seeing consistent results ( though it is about 40% less throughput than go grpc but stable) where as I did not see with .Net core grpc Microservices.  I will continue to research and let you know the results.

Thank you for your help.

Thanks
ram

**Comment by rampratapa** [comment]
James, Good morning,  I am still try to do some performance testing using various ways.   Is there anyway,  I can implement client side load balancing. As I am using

```
 services.AddGrpcClient<.Orchestrator.Orchestrate.OrchestrateClient>(o =>
                {
                    AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
                    o.Address = new Uri("**http://OService:5051"**);
 
                }).EnableCallContextPropagation(o => o.SuppressContextNotFoundErrors = true)
                .ConfigurePrimaryHttpMessageHandler(() =>
                {
                    var handler = new HttpClientHandler();
                    handler.MaxConnectionsPerServer = 300;
                    return handler;
                });

```

Is there anyway we can do client side load balancing without using Istio or Linkerd or do you have any thoughts we can achieve without  using AddGrpcClient or updating some properties of this one.   

I am seeing significant issue with the performance when we use in AKS/Kubernetes.   I reached out Microsoft and they said,  they are not supported ( I am still perusing with them in my case by asking more questions) Grpc and requested to reach out through this forum.

I really appreciate your help.

Thanks
Ram

**Comment by rampratapa** [comment]
@JamesNK ,  Any thought on load balancing on client side for a Grpc service.  I am looking into Dapr to see if it load balances.  Though it is invasive in nature but thinking it may have other uses like Pub-sub.   

Thank you
Ram

**Comment by JamesNK** [comment]
If you want to do client side load balancing today you will need to create and manage `GrpcChannel` instances yourself, and write an abstraction for choosing which one to use. There is no built in support for this in Grpc.Net.Client today.

**Comment by rampratapa** [comment]
@JamesNK ,  so, it means,  we need to use Kubernetes client *https://www.nuget.org/packages/KubernetesClient/* and get endpoints and construct the grpcChannel factory and randomly select the channel/grpc server.   Also,  whenever there is change to pods/endpoints, we need to destroy channel and recreate it.

I am thinking,  it may be too much of code maintenance and hence thinking to  give-up grpc implementation for now and go with RESTful services.  Though we have mesh technologies,  the number of service are not more than 25 or 50,  it may be an overhead to maintain those technological stack.  With the given hardaware,  I am seeing RESTFul is giving better throughput than grpc without client side load balancing ( At this time as I don't have client side load balancing code I am not sure what is the affect on the throughput).  Even with Mesh technologies like Iinkerd, Istio,  I am seeing REST is doing better on throughput and smooth distribution of the load.  Hence I am thinking to go with REST for now but wanted to let you know my observations.  if you feel different,  if you can provide some articles,  I am happy to look/read.

Also,  Microsoft said through support case,  they don't support grpc ( not sure what is their role).

I really appreciate your help.

Thank you
Ram
