### ISSUE TITLE
Why can't I deserialize a 'RepeatedField<string>'?

### ISSUE THREAD

**Issue by kelvinsand** [grpc/grpc-dotnet#1067]
My proto file:

```
message Greet {
   repeated string name = 5;
}
```
My json:

```
{
   "name ": [
      "foo",
      "bar"
   ]
}
```

I'm using System.Text.Json to try this

**Comment by JunTaoLuo** [comment]
Why are you trying to deserialize json? Protobuf messages are binary and deserializing json wouldn't work.

**Comment by kelvinsand** [comment]
I was not trying to deserialize for the protobuf, but the class generated by the protobuf. 
I built a gateway api and it converts my rpc messages to json

<hr></hr>

After some time I discover the problem. The property generated for the `repeated string name = 5` is generated with no setter, then the jsonConverter is unable to deserialize json for the message. 

<hr></hr>

In this [issue](https://github.com/dotnet/runtime/issues/30258) of the donet repository there is a discussion about it and it will probably only go into .NET 6
I solved the problem temporarily based on the solution presented [here](https://github.com/dotnet/runtime/issues/30258#issuecomment-564847072)


Thank you for your help

**Comment by JamesNK** [comment]
You can deserialize JSON into Protobuf objects by using the JSON functionality in Google.Protobuf.

```cs
var m = YourMessageType.Parser.ParseJson(json);
```

**Comment by kelvinsand** [comment]
😮 I hadn't seen that parser. As I am making a generic converter I had not seen this possibility. I had to use reflection to get it.

**Comment by xqotax** [comment]
This is more of a workaround, but when I was configuring massTransit to work with models generated via proto files, I just used NewtonsoftJsonSerializer - repeatedField deserialized fine
