### ISSUE TITLE
Improve discoverability of BindService

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#107]
Right now we use reflection to look up a service's type hierarchy to find `BindService`. This is brittle because other code gen tools could have placed `BindService` in a different location.

What about adding an attribute that is added via code-gen to the service base type that specifies exactly where to find the BindService method.

```cs
public class BindServiceAttribute : Attribute
{
    public BindServiceAttribute(Type type, string methodName)
    {
        // ...
    }
}
```

Code gen service:

```cs
public static class Counter
{
    [BindService(typeof(Counter), nameof(Counter.BindService))]
    public abstract partial class CounterBase
    {
    }

    public static void BindService(grpc::ServiceBinderBase serviceBinder, CounterBase serviceImpl)
    {
        // ...
    }
}
```

Other .NET code generators can then be encouraged to output this attribute so they can be more easily used with Grpc.AspNetCore.

**Comment by JamesNK** [comment]
@davidfowl @jtattermusch

**Comment by JamesNK** [comment]
I still like this idea as a better alternative to how we currently bind services in gRPC. The way we currently search for the bind services method using reflection is flaky.

@jtattermusch we can submit a PR to Grpc.Core.Api to add the attribute and Grpc.Tools to update the code gen. Grpc.AspNetCore.Server would behave the same as it does today when it can't find the attribute (search for bind via the inheritance tree) so no generated code that works today would break.

**Comment by davidfowl** [comment]
Agreed.

**Comment by JamesNK** [comment]
Example of calling bind method with reflection via an attribute:
```cs
var serviceAttribute = typeof(GreetService).GetCustomAttributes(typeof(BindServiceAttribute), inherit: true).FirstOrDefault();
if (serviceAttribute != null)
{
    var bindMethod = serviceAttribute.ServiceType.GetMethod(serviceAttribute.BindMethodName);
    bindMethod.Invoke(null);
}
else
{
    // Existing reflection logic for backwards compat
}
```
