### ISSUE TITLE
How does ProtoBuf deal with properties which contain Classes

### ISSUE THREAD

**Issue by PeterJD** [grpc/grpc-dotnet#1070]
Hi

How does ProtoBuf deal with properties which contain Classes

ClassB references class SettingsDto via properties, will protobuf populate required structure ?
Will it also take care of List<PaymentDto> and SuspensionDto ?

or what should I do?

public Class ClassB
{

	public long? CustomerId { get; set; }
	public string CustomerTypeCode { get; set; }
	public SettingsDto Settings { get; set; }

	public List<PaymentDto> Payment { get; set; }
}

public class SettingsDto{

	public long? InsurerId { get; set; }
	public SuspensionDto Suspension { get; set; }
	....etc
}

public Class SuspensionDto {

	properties etc........
}
Kind regards
Peter

**Comment by JamesNK** [comment]
I don't understand the question. Protobuf messages are generated from proto files.

If you have Protobuf specific questions you should ask them at https://github.com/protocolbuffers/protobuf

**Comment by JunTaoLuo** [comment]
Closing since we don't have any further action items here.
