### ISSUE TITLE
System.InvalidOperationException: 'Error binding SayHello on GreeterService to HTTP API.'

### ISSUE THREAD

**Issue by Alex4684** [grpc/grpc-dotnet#1071]
Hi all,

I am getting the exception below when trying to create a  JSON Web APIs from an existing gRPC service.

I am following the steps described at the link https://docs.microsoft.com/it-it/aspnet/core/grpc/httpapi?view=aspnetcore-3.1, here you are my startup.cs:

`public class Startup
   {
   
      public void ConfigureServices(IServiceCollection services)
      {
         services.AddGrpc();
         services.AddGrpcHttpApi();
         
         services.AddCors(o => o.AddPolicy("AllowAll", builder =>
         {
            builder.AllowAnyOrigin()
               .AllowAnyMethod()
               .AllowAnyHeader()
               .WithExposedHeaders("Grpc-Status", "Grpc-Message", "Grpc-Encoding", "Grpc-Accept-Encoding");
         }));
      }

      public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
      {
         if (env.IsDevelopment())
         {
            app.UseDeveloperExceptionPage();
         }
         app.UseRouting();
         app.UseGrpcWeb();
         app.UseCors();
         app.UseEndpoints(endpoints =>
         {
            //endpoints.MapGrpcService<GreeterService>();
            endpoints.MapGrpcService<GreeterService>().EnableGrpcWeb().RequireCors("AllowAll");

               endpoints.MapGet("/", async context =>
               {
                  await context.Response.WriteAsync("Communication with gRPC endpoints must be made through a gRPC client. To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909");
               });
            
         });
      }
   }
}
`

I changed greet.proto as follow:

`service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) {
	  option (google.api.http) = {
		  get: "v1/greeter/{name}"
	  };
  }

  rpc GetProducts (ProductsRequest) returns (ProductsReply);
  rpc GetOrders (OrdersRequest) returns (OrdersReply);
  rpc GetUnits (UnitsRequest) returns (UnitsReply);
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings.
message HelloReply {
  string message = 1;
}`

Any idea? Thanks in advance.

**Exception:**

_System.InvalidOperationException
  HResult=0x80131509
  Message=Error binding SayHello on GreeterService to HTTP API.
  Source=Microsoft.AspNetCore.Grpc.HttpApi
  StackTrace:
   at Microsoft.AspNetCore.Grpc.HttpApi.HttpApiProviderServiceBinder`1.AddMethodCore[TRequest,TResponse](Method`2 method, HttpRule httpRule, String pattern, String httpVerb, String body, String responseBody, MethodDescriptor methodDescriptor)
   at Microsoft.AspNetCore.Grpc.HttpApi.HttpApiProviderServiceBinder`1.ProcessHttpRule[TRequest,TResponse](Method`2 method, MethodDescriptor methodDescriptor, HttpRule httpRule)
   at Microsoft.AspNetCore.Grpc.HttpApi.HttpApiProviderServiceBinder`1.AddMethod[TRequest,TResponse](Method`2 method, UnaryServerMethod`2 handler)
   at InspectSddGrpc.Greeter.BindService(ServiceBinderBase serviceBinder, GreeterBase serviceImpl) in C:\Web\InspectSddGrpc\InspectSddGrpc\obj\Debug\netcoreapp3.1\Protos\GreetGrpc.cs:line 110

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
InvalidOperationException: Path template must start with /: v1/greeter/{name}_

_

**Comment by Alex4684** [comment]
Hi,

I found my issue, get string must start with a slash.

Maybe it can be useful to update your tutorial.

Thanks



` rpc GetProducts (ProductsRequest) returns (ProductsReply){
	  option (google.api.http) = {
		  get: "/v1/greeter/products"
	  };`

**Comment by JamesNK** [comment]
Which tutorial did you follow?

**Comment by Alex4684** [comment]
> Which tutorial did you follow?

this one: https://docs.microsoft.com/it-it/aspnet/core/grpc/httpapi?view=aspnetcore-3.1

**Comment by JamesNK** [comment]
Fix - https://github.com/dotnet/AspNetCore.Docs/pull/20132

Thanks for reporting

**Comment by Alex4684** [comment]
You're welcome, thank you for your effort, I hope this is going to become a stable official package.
