### ISSUE TITLE
GRPC code first

### ISSUE THREAD

**Issue by DhruvBarot** [grpc/grpc-dotnet#1072]
Here, asking for a new feature request like code first model, currently, we have to write proto first then after class and service created if create class and service first then automatic proto file generated then it will be nice to have this feature, it will help to reduce the learning curve for GRPC, Like WCF it can we achieve.

**Comment by JamesNK** [comment]
You can do that with protobuf-net.Grpc - https://protobuf-net.github.io/protobuf-net.Grpc/
