### ISSUE TITLE
Couldn't load projs using VS, requires "at least version 16.8.0 of MSBuild"

### ISSUE THREAD

**Issue by yabli** [grpc/grpc-dotnet#1075]
Sorry that this might be a dumb question. I'm running into this error all the times when about to load grpc-dotnet projects in VS2019. I search around, while couldn't figure out how to upgrade MSBuild to 16.8.0.

"The project file cannot be opened. Version 5.0.100-rc.2.20464.8 of the .NET Core SDK requires at least version 16.8.0 of MSBuild. The current available version of MSBuild is 16.7.0.37604. Change the .NET Core SDK specified in global.json to an older version that requires the MSBuild version currently available."

I did the cmds mentioned in readme:
  powershell .\build\get-dotnet.ps1
  powershell . .\activate.ps1
  startvs.cmd   -> projects failed to be loaded in VS
  dotnet build Grpc.DotNet.sln  -> this works well
while could help load using VS

thanks a lot

**Comment by JamesNK** [comment]
16.8 is required for .NET 5. It is currently in preview so you need a preview version of VS2019.
