### ISSUE TITLE
Wrong StatusCode when service is unavailable and Grpc.Net.Client.GrpcChannel is used

### ISSUE THREAD

**Issue by kedrzu91** [grpc/grpc-dotnet#1076]
### What version of gRPC and what language are you using?
2.32.0

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET Core SDK:  Version:   3.1.402

### What did you do?
I'm working on error handling. I want to detect when service is unavailable.
I've noticed that when I'm using `Grpc.Core.Channel` everything is ok - status code of `RpcException` is equal to Unavailable (correct).
But when I'm using `Grpc.Net.Client.GrpcChannel` status code of `RpcException` is equal to Internal (incorrect).

Below test that presents the issue:
```csharp
[Test]
public void Wrong_status_code()
{
    var grpcCLibChannel = new Channel("localhost", port, ChannelCredentials.Insecure);
    var grpcCLibClient = new TestService.TestServiceClient(grpcCLibChannel);

    var exceptionCLib = Assert.ThrowsAsync<RpcException>(
        async () => await grpcCLibClient.TestMethodAsync(new TestModelInput()));
            
    TestContext.WriteLine(exceptionCLib);

    Assert.That(exceptionCLib.Status.StatusCode, Is.EqualTo(StatusCode.Unavailable));

    var uri = new UriBuilder("http", "localhost", port).Uri;
    var options = new GrpcChannelOptions() { Credentials = ChannelCredentials.Insecure };
    var grpcCSharpHttpClientChannel = GrpcChannel.ForAddress(uri, options);
    var grpcCSharpHttpClientClient = new TestService.TestServiceClient(grpcCSharpHttpClientChannel);

    var exceptionCSharpHttpClient = Assert.ThrowsAsync<RpcException>(
        async () => await grpcCSharpHttpClientClient.TestMethodAsync(new TestModelInput()));

    TestContext.WriteLine(exceptionCSharpHttpClient);
    Assert.That(exceptionCSharpHttpClient.Status.StatusCode, 
        Is.EqualTo(StatusCode.Internal)); // <--- !!!! should be Unavailable
}
```

The same issue exists when client is created by DI in ASP.NET Core (registered with extension: `service.AddGrpcClient<T>`)

I can detect that connection is unavailable based on `exceptionCSharpHttpClient .Status.DebugException` (which has `HttpRequestException` type) but the docs say that DebugException shouldn't be used in logic.

### What did you expect to see?
`RpcException` should have status equal to Unavailable.

### What did you see instead?
`RpcException` had status equal to `Internal` when `Grpc.Net.Client.GrpcChannel` was used.

**Comment by JamesNK** [comment]
What is the cause of the error? Is the server not running at the specified localhost + port.

**Comment by kedrzu91** [comment]
Yes, server is not running at the specified localhost + port
