### ISSUE TITLE
Is certificate port binding valid for grpc server?

### ISSUE THREAD

**Issue by MaximGurschi** [grpc/grpc-dotnet#1081]
Hi,

Tell me please, i'm generating a certificate to use by the grpc service. The client seems to be able to connect to the service only through "localhost..." not through the host name.

The certificate i generate i bind to the https port the service is listening on. Is that the way to do it, or am i supposed to hook the port with a certificate programmatically?

**Comment by MaximGurschi** [comment]
I managed to get it to work using code (ConfigureKestrel, etc.) - but is Windows port binding to certificate supposed to work?

**Comment by BrennanConroy** [comment]
Can you take a look at https://devblogs.microsoft.com/aspnet/configuring-https-in-asp-net-core-across-different-platforms/ and see if it helps resolve your issue. And https://docs.microsoft.com/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1&tabs=visual-studio#trust-the-aspnet-core-https-development-certificate-on-windows-and-macos

**Comment by MaximGurschi** [comment]
@BrennanConroy Thank you for that. Yes that works as i have posted as well. I was just curious why the certificate port binding feature does not work. At the end of the day it is not a problem as there is another way, i just wanted to understand why the binding does not work.
