### ISSUE TITLE
Value equal to zero not serialized into output JSON

### ISSUE THREAD

**Issue by Alex4684** [grpc/grpc-dotnet#1090]
Hi,

I noticed that values equal to zero for integer fields have not serialized.

In the below example Quantity fields is not present when it is zero, that is the default value for integer.

I've looked for this behavior and I found that there is no configuration available at the moment to avoid this.

`{ "values": [ { "ID": 1, "OrderName": "inor000001", "Type": "Visual Inspection", "Status": "New", "Product": "RaspberryPi", "Quantity": 5, "InputFolder": "./testImages/", "Lot": "InspLot0000" }, { "ID": 2, "OrderName": "inor000002", "Type": "Visual Inspection", "Status": "New", "Product": "RaspberryPi", "Quantity": 4, "InputFolder": "./testImages/", "Lot": "InspLot0001" }, { "ID": 3, "OrderName": "inor000003", "Type": "Visual Inspection", "Status": "New", "Product": "RaspberryPi", "Quantity": 4, "InputFolder": "./testImages/", "Lot": "InspLot0002" }, { "ID": 4, "OrderName": "inord00004", "Type": "Visual Inspection", "Status": "New", "Product": "RaspberryPi", "InputFolder": "./testImages/", "Lot": "InspLot0002" }, { "ID": 5, "OrderName": "inord00005", "Type": "Visual Inspection", "Status": "New", "Product": "RaspberryPi", "InputFolder": "./testImages/", "Lot": "InspLot0001" } ] }`

**Comment by BrennanConroy** [comment]
https://developers.google.com/protocol-buffers/docs/proto3#default defines how default values behave in protobuf. Are you generating the Json from the protobuf output?

**Comment by JamesNK** [comment]
One option could be to use nullable types for properties with values that should serialize a default value.

https://docs.microsoft.com/en-us/aspnet/core/grpc/protobuf?view=aspnetcore-3.1#nullable-types

**Comment by JunTaoLuo** [comment]
Closing as answered.
