### ISSUE TITLE
Chained certificate vs Self signed

### ISSUE THREAD

**Issue by 7amou3** [grpc/grpc-dotnet#1093]
https://github.com/grpc/grpc-dotnet/blob/bf3b057e32dbbb4f5d2db4c6650e73b3ae5ef17c/examples/Certifier/Server/Startup.cs#L40

Hello
This is rather a question than an issue,
for the link above, does that mean any user whith a certificate issued by a trusted CA (letencrypt for exemple) can be authenticated against the grpc service?
In my use case I just want to trust the certificates that are generate by my private CA server.

**Comment by JamesNK** [comment]
I'm not sure. Certificate authentication is not something I'm an expert on. I suggest you as at https://github.com/dotnet/aspnetcore

**Comment by 7amou3** [comment]
For anyone looking for response here is what I found:
Microsoft [docs](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-3.0#configure-your-server-to-require-certificates):

> Validate that the thumbprints of both the client certificate and the server certificate match, otherwise any certificate can be used and will be enough to authenticate.

so in your server's Program.cs add:
   ```              
 httpsOptions.ClientCertificateValidation = (clientCert, validationChain, policyErrors) =>
{
  var serverCert = new X509Certificate2("path/to/rootCert.crt", "Password if Any");                              
   // only trust certs that are signed by our private CA 
    return  validationChain.ChainElements.Cast<X509ChainElement>()
                                    .Any(x => x.Certificate.Thumbprint == serverCert.Thumbprint);
 };
```
