### ISSUE TITLE
Additional KeepAlive settings

### ISSUE THREAD

**Issue by mijkathegreat** [grpc/grpc-dotnet#1096]
Looks there is no way to set option GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA on client
 (https://github.com/grpc/grpc/blob/master/doc/keepalive.md) and it's defaulted to 0 (which is not ok), and looks there is no way to set any of those options when creating a gRPC service. Am I right?
If so, all keepalive settings become unusable if there is .net gRPC-server or go-gRPC server with default settings.

**Comment by JamesNK** [comment]
The only options for pings in the client are what are specified here - https://docs.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-5.0#keep-alive-pings

You'll need to update the server settings to allow pings without data.

**Comment by mijkathegreat** [comment]
Yes, I've seen those options, for my case that in't enough, by i'll prefer to reconfigure server for unlimited "ping strikes". Is there any way to do so using Grpc.AspNetCore? This one isn't enough https://github.com/grpc/grpc-dotnet/blob/master/src/Grpc.AspNetCore.Server/GrpcServiceOptions.cs

**Comment by BrennanConroy** [comment]
Kestrel doesn't do anything with "ping strikes" so the default should work for you. Are you seeing issues with Kestrel and "ping strikes"?

**Comment by mijkathegreat** [comment]
Made some tests - the answer is no.
I've got strikes with Go services or .net services based on "gRPC C#" library (https://github.com/grpc/grpc/tree/master/src/csharp) but both have settings to setup strikes behaviour. Server based on grpc-dotnet is okay with default settings, thanks!
