### ISSUE TITLE
Xamarin Forms and Grpc.Net

### ISSUE THREAD

**Issue by speed2048** [grpc/grpc-dotnet#1097]
I am developing a project that uses xamarin.forms with grpc on a Mac ( getting ready for .net Maui ) and I am getting exception errors (DebugException="System.MissingMethodException: Method not found: System.Buffers.IBufferWriter`1 Grpc.Core.SerializationContext.GetBufferWriter()).

So I did some digging and found out that Xamarin.Forms does not work with grpc.net at this time.

https://docs.microsoft.com/en-us/aspnet/core/grpc/client?view=aspnetcore-3.1

My question is. When will xf support grpc.net? I do not see this on the roadmap I admit I could be looking in the wrong place.

Also is Xamarin.Forms going to support the .net core Framework?

Also wondering if I should provide more details with this issue?

**Comment by JunTaoLuo** [comment]
This would be a question best left for the owners of Xamarin Forms.

Curious if this is a new error you are seeing and it worked at one point for you? The bufferwriter error looks like it could be a new issue that was introduced after we defaulted to using span based serialization/deserialization in https://github.com/protocolbuffers/protobuf/pull/7351. If that is the case, you could try setting `GOOGLE_PROTOBUF_COMPATIBILITY_MODE` as described in https://github.com/protocolbuffers/protobuf/pull/7490 to revert to the previous behaviour and see if that helps with your scenario.

**Comment by speed2048** [comment]
I did ask the Xamarin forms people and suggested posting here..

https://github.com/dotnet/core/issues/5376#issuecomment-718242500

I am hopting the .net 5/6 fixes this mess with .netstandard x.x and .net core. As I cannot seem to find a way to implement grpc.net unless its dotnet 3 app or web app..

**Comment by JoacimWall** [comment]
Hi @speed2048  
i have used the grpc.web nuget and got i working under xamarin.forms this was som months ago.

//Regards Joacim

**Comment by BrennanConroy** [comment]
>you could try setting GOOGLE_PROTOBUF_COMPATIBILITY_MODE as described in protocolbuffers/protobuf#7490 to revert to the previous behaviour and see if that helps with your scenario.

Have you tried this?

**Comment by JunTaoLuo** [comment]
There hasn't been any response in the past 7 days so we are closing this issue. Please reopen or open a new issue if you you would like to discuss further.
