### ISSUE TITLE
Grpc client and AKS Headless service

### ISSUE THREAD

**Issue by rampratapa** [grpc/grpc-dotnet#1098]
Hi,  I have a question on headless service in AKS.  I am running a grpc service as headless and I have injected the client

```
orchestratorUrl = "http://orchstrservice:5002";
            services.AddGrpcClient<OrchestrateClient>(o =>
                {
                    AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
                    o.Address = new Uri(orchestratorUrl);
 
                }).EnableCallContextPropagation(o => o.SuppressContextNotFoundErrors = true)
                .ConfigurePrimaryHttpMessageHandler(() =>
                {
                    var handler = new HttpClientHandler();
                    handler.MaxConnectionsPerServer = 300;
                    return handler;
                });

```
the following is headless service
orchstrservice          ClusterIP   None             <none>        5002/TCP

it returns endpoints
orchstrservice   10.1.2.203:5002,10.1.2.204:5002   7m59s

My question is : how is grpc client is going to handle,  will it take first url and try to connect to same pod or randomly selects it.  How it is being handled?.

Can you please help in understanding the behavior with headless services.

Thank you for your help.
Ram

**Comment by JamesNK** [comment]
I believe that URL doesn't do anything other than return the replica addresses with DNS. Right now the gRPC client doesn't automatically resolve the replica endpoints, so any gRPC calls made will fail.

Supporting client side load balancing in Kubernetes is a planned feature.

**Comment by JamesNK** [comment]
Closing as answered.
