### ISSUE TITLE
How to know if compression is working?

### ISSUE THREAD

**Issue by alexvazquez** [grpc/grpc-dotnet#1101]
I just followed the Compression sample and everything seems to be working fine, but my question is how to make sure the compression is working?

Is there a way to catch the size of the request before is being compressed and after with the Interceptor?

Thanks

**Comment by JamesNK** [comment]
Logging at the `Debug` level reports compression being used - https://docs.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-3.1

**Comment by alexvazquez** [comment]
> > I just followed the Compression sample and everything seems to be working fine, but my question is how to make sure the compression is working?
> 
> Logging at the `Debug` level reports compression being used - https://docs.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-3.1
> 
> > Is there a way to catch the size of the request before is being compressed and after with the Interceptor?
> 
> No. Decompression happens before a request message is passed to interceptors, and compression happens after a response message has exited interceptors.

Awesome @JamesNK I will give a try to Logging at the debug level and see what I get. Does this works also for the client so I can make sure client decompress the request?

Got it, now is clear to me that is not possible to do that at interceptors level. 

Is there a way to create you own Compression handler and if so is there any documentation,sample or tutorial?

Appreciate it so much

**Comment by JamesNK** [comment]
Logging records compressing messages on the client and server.

Implement ICompressionProvider and configure it in the client and server. Example - https://github.com/grpc/grpc-dotnet/blob/c48ae4442fdae1881622ad94d02dfda45912493a/src/Grpc.Net.Common/Compression/GzipCompressionProvider.cs

**Comment by alexvazquez** [comment]
> Logging records compressing messages on the client and server.
> 
> Implement ICompressionProvider and configure it in the client and server. Example - https://github.com/grpc/grpc-dotnet/blob/c48ae4442fdae1881622ad94d02dfda45912493a/src/Grpc.Net.Common/Compression/GzipCompressionProvider.cs

Thanks @JamesNK , I already implement the logging and I can see in the console the Debug info but nothing about compression, maybe my client is not implementing compression correctly but is very strange because I'm sending the headers that are required.

This is my client code:

```

string s = GetRootCertificates();
            var channel_creds = new SslCredentials(s);

            Channel channel = new Channel("localhost:5001", channel_creds, new ChannelOption[] {
                new ChannelOption(ChannelOptions.MaxReceiveMessageLength, 10 * 1024 * 1024), //plenty of room
            });

            var invoker = channel.Intercept(new ClientLoggerInterceptor());

            var client = new Greeter.GreeterClient(invoker);

            var headers = new Metadata();
            //headers.Add("Authorization", $"Bearer {token}");
            headers.Add("grpc-internal-encoding-request", "gzip");
            //headers.Add("grpc-accept-encoding", "gzip");
            headers.Add("requester", "cliente");

            // deadline is the timeout in sedconds
            var callOptions = new CallOptions().WithHeaders(headers).WithDeadline(DateTime.UtcNow.AddSeconds(15)).WithWaitForReady(false);

            DataSetResponse response = await client.GetPatientInfoAsync(new PatientInfoRequest { Uid = "DF24387B-815D-4E06-AD76-9E9E3C255118", LoadContractsOnDemand = false }, callOptions);
            
```

Any clue? Thanks a lot

**Comment by alexvazquez** [comment]
I have done so many tests, with different code changes, adding diff headers, also for logging besides the  "Grpc": "Trace" I  added the following code that I found here https://stackoverflow.com/questions/49031763/grpc-compression-in-c-sharp

```
    Environment.SetEnvironmentVariable("GRPC_TRACE", "compression");
        Environment.SetEnvironmentVariable("GRPC_VERBOSITY", "DEBUG");
        GrpcEnvironment.SetLogger(new ConsoleLogger());
```

I have gone through all the possible options I have seen on the internet and no way I can get any compression message in the server console. I pray for help.

**Comment by alexvazquez** [comment]
@JamesNK I would really appreciate any help please I have been blocked for 1 week on this issue and can't find a way to show the compression message printed in the console. Is there anything wrong I'm doing?

**Comment by JamesNK** [comment]
I looked at this and compression logging happens when the level is `Trace`.

```
dbug: Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware[1]
      Request matched endpoint 'gRPC - /greet.Greeter/SayHello'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'gRPC - /greet.Greeter/SayHello'
dbug: Grpc.AspNetCore.Server.ServerCallHandler[10]
      Reading message.
dbug: Microsoft.AspNetCore.Server.Kestrel[25]
      Connection id "0HM42I9EP91AA", Request id "0HM42I9EP91AA:00000001": started reading request body.
dbug: Microsoft.AspNetCore.Server.Kestrel[26]
      Connection id "0HM42I9EP91AA", Request id "0HM42I9EP91AA:00000001": done reading request body.
trce: Grpc.AspNetCore.Server.ServerCallHandler[20]
      Decompressing message with 'gzip' encoding.
trce: Grpc.AspNetCore.Server.ServerCallHandler[12]
      Deserializing 15 byte message to 'Greet.HelloRequest'.
trce: Grpc.AspNetCore.Server.ServerCallHandler[13]
      Received message.
info: Server.GreeterService[0]
      Sending hello to GreeterClient
trce: Microsoft.AspNetCore.Server.Kestrel[37]
      Connection id "0HM42I9EP91AA" sending HEADERS frame for stream ID 1 with length 79 and flags END_HEADERS
dbug: Grpc.AspNetCore.Server.ServerCallHandler[15]
      Sending message.
trce: Grpc.AspNetCore.Server.ServerCallHandler[18]
      Serialized 'Greet.HelloReply' to 21 byte message.
trce: Grpc.AspNetCore.Server.ServerCallHandler[19]
      Compressing message with 'gzip' encoding.
trce: Grpc.AspNetCore.Server.ServerCallHandler[16]
      Message sent.
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'gRPC - /greet.Greeter/SayHello'
trce: Microsoft.AspNetCore.Server.Kestrel[37]
      Connection id "0HM42I9EP91AA" sending DATA frame for stream ID 1 with length 46 and flags NONE
trce: Microsoft.AspNetCore.Server.Kestrel[37]
      Connection id "0HM42I9EP91AA" sending HEADERS frame for stream ID 1 with length 15 and flags END_STREAM, END_HEADERS
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 POST https://localhost:5001/greet.Greeter/SayHello application/grpc - - 200 - application/grpc 117.9223ms
```

**Comment by alexvazquez** [comment]
> I looked at this and compression logging happens when the level is `Trace`.
> 
> ```
> dbug: Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware[1]
>       Request matched endpoint 'gRPC - /greet.Greeter/SayHello'
> info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
>       Executing endpoint 'gRPC - /greet.Greeter/SayHello'
> dbug: Grpc.AspNetCore.Server.ServerCallHandler[10]
>       Reading message.
> dbug: Microsoft.AspNetCore.Server.Kestrel[25]
>       Connection id "0HM42I9EP91AA", Request id "0HM42I9EP91AA:00000001": started reading request body.
> dbug: Microsoft.AspNetCore.Server.Kestrel[26]
>       Connection id "0HM42I9EP91AA", Request id "0HM42I9EP91AA:00000001": done reading request body.
> trce: Grpc.AspNetCore.Server.ServerCallHandler[20]
>       Decompressing message with 'gzip' encoding.
> trce: Grpc.AspNetCore.Server.ServerCallHandler[12]
>       Deserializing 15 byte message to 'Greet.HelloRequest'.
> trce: Grpc.AspNetCore.Server.ServerCallHandler[13]
>       Received message.
> info: Server.GreeterService[0]
>       Sending hello to GreeterClient
> trce: Microsoft.AspNetCore.Server.Kestrel[37]
>       Connection id "0HM42I9EP91AA" sending HEADERS frame for stream ID 1 with length 79 and flags END_HEADERS
> dbug: Grpc.AspNetCore.Server.ServerCallHandler[15]
>       Sending message.
> trce: Grpc.AspNetCore.Server.ServerCallHandler[18]
>       Serialized 'Greet.HelloReply' to 21 byte message.
> trce: Grpc.AspNetCore.Server.ServerCallHandler[19]
>       Compressing message with 'gzip' encoding.
> trce: Grpc.AspNetCore.Server.ServerCallHandler[16]
>       Message sent.
> info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
>       Executed endpoint 'gRPC - /greet.Greeter/SayHello'
> trce: Microsoft.AspNetCore.Server.Kestrel[37]
>       Connection id "0HM42I9EP91AA" sending DATA frame for stream ID 1 with length 46 and flags NONE
> trce: Microsoft.AspNetCore.Server.Kestrel[37]
>       Connection id "0HM42I9EP91AA" sending HEADERS frame for stream ID 1 with length 15 and flags END_STREAM, END_HEADERS
> info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
>       Request finished HTTP/2 POST https://localhost:5001/greet.Greeter/SayHello application/grpc - - 200 - application/grpc 117.9223ms
> ```

@JamesNK I have it in Trace mode and same issue. Can you share me the project you are testing with please. Really appreciate your support.

This is my settings for logging:

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Trace",
      "System": "Information",
      "Microsoft": "Trace",
      "Microsoft.Hosting.Lifetime": "Information",
      "Grpc": "Trace"
    }
  },
  "AllowedHosts": "*",
  "Kestrel": {
    "EndpointDefaults": {
      "Protocols": "Http2"
    }
  }
}

```

**Comment by JamesNK** [comment]
https://github.com/grpc/grpc-dotnet/tree/master/examples/Compressor

**Comment by alexvazquez** [comment]
> https://github.com/grpc/grpc-dotnet/tree/master/examples/Compressor

@JamesNK thanks, i just saw that the projects are targeted to .NET 5, im using on my server project .NET Core 3.1, could this be the issue?

**Comment by alexvazquez** [comment]
> https://github.com/grpc/grpc-dotnet/tree/master/examples/Compressor

I just installed .NET 5 and ran the github compression sample with the following logging settings:

```
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Trace",
      "System": "Information",
      "Microsoft": "Information",
      "Grpc": "Trace"
    }
  },
  "AllowedHosts": "*",
  "Kestrel": {
    "EndpointDefaults": {
      "Protocols": "Http2"
    }
  }
}

And this is the console result

![image](https://user-images.githubusercontent.com/347747/98422224-ba4ccd00-2050-11eb-9d39-2a08f6250951.png)

```

**Comment by alexvazquez** [comment]
The way to get it working was to forget about appsettings.json, instead I add this:
```

  public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
             .ConfigureLogging(logging =>
             {
                 logging.AddFilter("Grpc", LogLevel.Trace);
             })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
```

![image](https://user-images.githubusercontent.com/347747/98422597-ba010180-2051-11eb-99b9-e693c614433d.png)

**Comment by JamesNK** [comment]
It works the same with 3.1 or 5

**Comment by alexvazquez** [comment]
> It works the same with 3.1 or 5

Yes, it works the same. The only thing to make it work was to add the line:

` logging.AddFilter("Grpc", LogLevel.Trace);`
