### ISSUE TITLE
Unable to share common proto between different projects

### ISSUE THREAD

**Issue by smartaquarius10** [grpc/grpc-dotnet#1104]
Team,

I'm migrating one of my MVC based .net framework api to grpc. Currently, I have one entity class in model project which is referenced in main and dbcontext project. Now, I'm trying to make same like this with grpc .net core project where, I have one main project which has service proto files and a model class library project having messages proto files.

In my main project I wanted to use this message protos, but the moment I run this command on my main project 

`dotnet grpc add-file "path to message proto"`

It edits the .csproj of main project and add this

`<ItemGroup>
    <Protobuf Include="..\Watcher\Protos\entities.proto" Link="Protos\entities.proto" GrpcServices="Client" />
  </ItemGroup>`

This adds a copy of this file **entities.proto** into the Protos folder of main project as well. Now, the moment I try to use it I get ambiguous conflicts and type casting errors: CS04236 & CS00029.

This is obvious because now indirectly, I have 2 proxy classes build by the proto file of same name and same namespace. 

Is there anyway to use the proto file which is build in one project and only referenced in other projects like the way we do in .net framework MVC projects.

Please help!!

**Comment by chwarr** [comment]
> Is there anyway to use the proto file which is build in one project and only referenced in other projects like the way we do in .net framework MVC projects.

A `ProjectReference` to the project that has the .proto files should be sufficient. A wrinkle that can come up: if you need the generated code for both clients and services, make sure that the project that runs codegen is emitting both. I do not remember what the template does by default.

In most of my code bases, I have a dedicated project & assembly just for the generated code. This also allows for deserialized messages to be shared among project according to the usual .NET rules for a common assembly. (Both the pros and the cons...)

**Comment by smartaquarius10** [comment]
But how to refer it in the rpc method of service.proto as input parameter

` rpc PostVDIStatus (package.entitiesMessage) returns (ResponseMessage);  `

Here, visual studio is giving compilation error again and again i.e. entities.proto was not found or package.entitiesMessage is not defined. At the top of service proto file I've tried all these combinations:

import "Models/Protos/entities.proto";
import "../../Models/Protos/entities.proto";

My directory structure is 

C:.
├───Service
         ├───Protos
                   └─── service.proto
└───Models
         └───Protos
                  └─── entities.proto

**Comment by BrennanConroy** [comment]
Dupe of https://github.com/grpc/grpc-dotnet/issues/183
There are some comments with MSBuild that might help you.

**Comment by smartaquarius10** [comment]
I'm pretty new with grpc protos. Trying but unable to understand this nuget thing. I would be grateful if you can share some simple steps to include these proto file in such a way so that it will not create 2 .cs for 2 different projects in same solution. 

Currently, whenever I'm referring same type of proto message in two different projects then they keep on throwing an error of ambiguous files because there are 2 files with same name space created through same copy of proto files.

My project structure with .net framework is

1. A modal project with entities.cs and Machines.cs
2. `entities.cs` has get set properties and `Machines.cs` has this:

    `public static ConcurrentDictionary<string, entites> data = new ConcurrentDictionary<string, entities>();`
3. In main project there is a post method with input parameter of type **[FromBody] entities**
4. In same project there is a separate repository class under the control of quartz for scheduling
5. The error of type casting and ambiguous files comes in this code within repository class
```
 public ConcurrentDictionary<string, entities> machines
        {
           get
            {
                return Machines.details;
            }
        }
```

Can anyone suggest me how to reference same proto.cs class because my whole migration is on stake due to this work. Please help.

**Comment by JamesNK** [comment]
There is a sample that demonstrates sharing a proto file - https://github.com/grpc/grpc-dotnet/tree/master/examples#liber

**Comment by smartaquarius10** [comment]
Thanks a lot @JamesNK and @chwarr , I'm able to use the protos from common place now. The main problem is that I was keeping few protos in project A which is the main project and other in model class library project B.

Both approaches are working now. 
1. Keeping all the protos in model class library project and from there consume in every other project
2. Keeping the protos in a folder and include them as given in Liber project.

Thank you for the help!!
