### ISSUE TITLE
Named Pipe status in .NET 5

### ISSUE THREAD

**Issue by ZoeyR** [grpc/grpc-dotnet#1112]
I know that allowing gRPC to work over named pipes was on the table for .net 5. Is there any status on that? I saw that UDS was implemented and has a working example but I can't find anything for named pipes.

**Comment by BrennanConroy** [comment]
Not yet, we're tracking server-side Kestrel support at https://github.com/dotnet/aspnetcore/issues/14207

**Comment by JamesNK** [comment]
There are extension points in Kestrel and the gRPC client that means named pipes is **possible** today, but there is no sample at the moment. You would need to figure it out.

There are samples for UDS today. Note that UDS works in modern versions of Windows: https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/

**Comment by JunTaoLuo** [comment]
There hasn't been any response in the past 7 days so we are closing this issue. Please reopen or open a new issue if you you would like to discuss further.
