### ISSUE TITLE
Increase logging severity of RPCExceptions

### ISSUE THREAD

**Issue by Euan-McVie** [grpc/grpc-dotnet#1113]
Hi,

We have basic exception handling logic in our service that raises an appropriate RPCException, but when this is subsequently logged it is at `Information` level.
In general we run our service with a root level of `Warning` which means that although the caller can log that there is an error when we look at the server side for more details we get nothing.

I know we can increase logging for the `Grpc.AspNetCore.Server.ServerCallHandler` to `Information`, or write our own interceptor to log it ourselves, but is there a reason that `_rpcConnectionError` is not logged at `Error` severity?
And if there is no specific reason could it be increased (preferably in netcore 3.1) to avoid either of our workarounds being required long term?

**Comment by BrennanConroy** [comment]
Generally we avoid logging client controlled errors at a higher level than Debug, if anything we might consider changing these logs to Debug from Information.

We generally recommend writing interceptors if you're interested in capturing client errors.

**Comment by JamesNK** [comment]
RpcException is not logged as an error because a lot of statuses from RpcException are not exceptional. e.g. Cancelled, Invalid Argument.

**Comment by Euan-McVie** [comment]
Fair enough. Question answered. 
Thanks
