### ISSUE TITLE
Kestrel + grpc-web + http endpoint + Azure AD authentication = lack of claims

### ISSUE THREAD

**Issue by zbigniew-gajewski** [grpc/grpc-dotnet#1116]
### What version of gRPC and what language are you using?
**C#**
**.Net Core 3.1** with **gRPC 2.32.0**  or 
**.Net 5**  with **gRPC 2.33.1**

### What operating system (Linux, Windows,...) and version?
Windows 10 (2004)

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
**.Net Core 3.1** 
**.Net 5**

### What did you do?
1.  Kestrel running as a standard console app, locally, exposing two standard **http** and **https** endpoints:  
![webserver](https://user-images.githubusercontent.com/32226444/99290594-67d09500-2836-11eb-86b7-33c6e675f375.png)
2. **grpc-web** used.
3. **Azure AD authentication** used with **mailing groups included in token**. Mailing groups retrieved from token on server side from **ServerCallContext.GetHttpContext().User.Clamis**  property for authorization purposes. 
4. Client call (after authentication) for both: http and https endpoints sends the same token with correct claims (mailing groups) and now:
  - when  **http** endpoint is used, then there is **no claims** in **ServerCallContext.GetHttpContext().User.Clamis** (server side):   
![http](https://user-images.githubusercontent.com/32226444/99292136-b8e18880-2838-11eb-9e27-88f51c8a69c8.png)
  - when  **https** endpoint is used, then **claims exist** in **ServerCallContext.GetHttpContext().User.Clamis** (server side):   
![https](https://user-images.githubusercontent.com/32226444/99291373-a0bd3980-2837-11eb-8a42-0df4ee549ad9.png)

### What did you expect to see?
When **http** endpoint is called and **grpc-web is used**, then **ServerCallContext.GetHttpContext().User.Clamis** property **should contain claims**. 

### What did you see instead?
When **http** endpoint is called and **grpc-web** is used, then **ServerCallContext.GetHttpContext().User.Clamis** property **does not contain claims**. 

### Anything else we should know about your project / environment?
Seems to be **grpc-web issue** because  when  **http** endpoint is used, but **without grpc-web** (HTTP/2 only, Kestrel on Linux on Docker container) then **claims exist** in **ServerCallContext.GetHttpContext().User.Clamis** property (server side).

**Comment by JamesNK** [comment]
What are you using to set the token for the call in the client? gRPC client credentials will only run if the request is HTTPS.

For example, adding an authorize token manually will always happen, while ClientCrentials will only run if the call is HTTPS: https://docs.microsoft.com/en-us/aspnet/core/grpc/authn-and-authz?view=aspnetcore-5.0#bearer-token-authentication

**Comment by zbigniew-gajewski** [comment]
For refreshing token we are using Microsoft.Identity.Client.AcquireTokenSilent(...).
We are not using CallCredentials (code for setting token attached). 
In all cases the token on the client is the same and contains correct claims (verified with jwt.io). 

As mentioned - when **Kestrel** works on docker container (linux) **without grpc-web** (with **http/2 only**), then **http** calls works as expected - **ServerCallContext.GetHttpContext().User.Clamis** property contains claims on server side and authorization works correctly). 

![Token](https://user-images.githubusercontent.com/32226444/99310575-1f73a000-2853-11eb-9b88-51c5dc73225e.png)

Getting client and header:
```
public (MyServiceGrpcService.MyServiceGrpcServiceClient, Metadata) Create()
{
    var client = GetClient();
    var headers = GetHeaders();

    return (client, headers);
}

private MyServiceGrpcService.MyServiceGrpcServiceClient GetClient()
{
    var handler = new GrpcWebHandler(
        GrpcWebMode.GrpcWeb, 
        new HttpClientHandler 
        { 
            ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator
        });

        handler.HttpVersion = new Version(1, 1);

        var endpointUrl = "http://loclalhost:5550";

        var channel = GrpcChannel.ForAddress(
           endpointUrl,
           new GrpcChannelOptions
           {
               HttpClient = new HttpClient(handler)
               {
                   MaxResponseContentBufferSize = int.MaxValue,
                   Timeout = TimeSpan.FromMinutes(30)
               },
           }); 

       var client = new MyServiceGrpcService.MyServiceGrpcServiceClient(channel) ;
           
       return client;
}

private Metadata GetHeaders()
{
     var token = _clientAuthenticator.RefreshAccessToken();

      return new Metadata
      {
          { "Authorization", $"Bearer {token}" },
      };
}
```

usage:

```
public async Task<GrpcCustomers> GetCustomersAsync(CancellationTokenSource cts)
{
    var (client, headers) = _grpcClientFactory.Create();
    var customers = await client.GetCustomersAsync(request: new Empty(), headers: headers, cancellationToken: cts.Token);

    return userProfile;
}
```

**Comment by JamesNK** [comment]
Ok, that's weird. Thanks for the info. I'll see if I can recreate it.

**Comment by JamesNK** [comment]
I added some tests - https://github.com/grpc/grpc-dotnet/pull/1119 - that do auth over grpcweb using different protocols and I couldn't recreate this.

The test is using JWT token authentication instead of Azure AD. If you are seeing failures then it seems more likely there is either a bug in your app, or Azure AD authentication.

**Comment by zbigniew-gajewski** [comment]
Thanks for analysing. 

Not sure where to look for a bug in our app - this is the same application exposing two endpoints: https and http. The client is the same as well (calling https or http endpoint accordingly). 

Again - when the same app has **grpc-web components removed from server and client** and when server is working on **linux docker container** (exposing **http endpoint**, Http2 protocol only) - the authorization works correctly (which might mean that both: AD and our app works correctly). So it seems like this is something which happens only for **Kestrel** working on **Windows** in conjunction with **AD authentication** and **grpc-web** components.

The priority of this issue is not very high (obviously we can use https for testing purposes), so this ticket can be closed.

**Comment by zbigniew-gajewski** [comment]
Final update - the root cause is: `app.UseHttpsRedirection();` in **Startup.Configure(...)**.
After commenting out this line, **http endpoint** on **Windows** works correctly. 

Correctly working **Startup.cs** (for **http** endpoint on **Windows** with **.Net Core 3.1**):
```csharp
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    app.UseAuthentication();

    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
    }
    else
    {
        app.UseHsts();
    }

    app.UseResponseCompression();

    //  app.UseHttpsRedirection();

    app.UseRouting();
    app.UseCors();
    app.UseMvc();
    app.UseGrpcWeb(new GrpcWebOptions { DefaultEnabled = true });
    
    app.UseEndpoints(endpoints =>
    {
        endpoints.MapGrpcService<MyGrpcService>().EnableGrpcWeb();
    });
}
```

**Comment by JamesNK** [comment]
Ok!
