### ISSUE TITLE
thread was always blocked, when call "await channel.ShutdownAsync()"

### ISSUE THREAD

**Issue by yigeguozhe** [grpc/grpc-dotnet#1122]

**Comment by JamesNK** [comment]
Grpc.Net.Client doesn't do anything in ShutdownAsync. Are you using Grpc.Core?

**Comment by yigeguozhe** [comment]
yes, is there a way that GRPC client close the connection，or client send a signal to server ,then server close connection.

**Comment by BrennanConroy** [comment]
Please file Grpc.Core issues at https://github.com/grpc/grpc
