### ISSUE TITLE
Having the test helpers as separate Nuget package

### ISSUE THREAD

**Issue by lamLeX** [grpc/grpc-dotnet#1124]
In the https://github.com/grpc/grpc-dotnet/blob/master/examples/Tester @JamesNK wrote a few helper classes that are quite helpful for Functional and Unit Tests.

I wonder if we could deliver these helper classes as a separate Nuget package for reusability? 

Suggesting name `Grpc.AspNetCore.Test`

**Comment by JamesNK** [comment]
It would be useful, but there is extra work in maintaining a package.

I'm going to put this in the backlog. It could be done in the future if more people ask for this.

**Comment by lamLeX** [comment]
There is no need for separate package anymore as we could use the `WebApplicationFaction<T>` together with Grpc client factory to achieve the simpler test fixture as described here https://github.com/grpc/grpc-dotnet/issues/1308
