### ISSUE TITLE
Is there any good way to make aspnetcore mvc and grpc run on the same port in aspnetcore

### ISSUE THREAD

**Issue by dingsongjie** [grpc/grpc-dotnet#1138]
I have followed grpc since 3.1. my service is running on kubernetes, TLS termination in these environments usually happens at ingress, so the Http1AndHttp2 option in Kestrel is useless to me.This is why I still can’t use grpc

**Comment by JamesNK** [comment]
HTTP/1.1 and HTTP/2 can only run on the same port when TLS is used. TLS is required to negotiate the connection protocol.
