### ISSUE TITLE
How to map all grpc endpoints at once instead of one by one

### ISSUE THREAD

**Issue by xaviergxf** [grpc/grpc-dotnet#1139]
Hi,

   How can i map all grpc endpoints at once instead of one by one on startup? Instead of 

endpoints.MapGrpcService<GreeterService>();

do you have something like:

endpoints.MapAllGrpcServices();?

Thanks

**Comment by JunTaoLuo** [comment]
This isn't exactly trivial since we'll need to discover the types that represent gRPC service implementations.

**Comment by xaviergxf** [comment]
Is it possible to implement this by searching all types having an attribute grpc::BindServiceMethod?

**Comment by JamesNK** [comment]
It is possible but it isn't something we want apps to do. Using reflection to scan all assemblies in an app to find types will break linking. That means trimming app size or AOT complication won't work.

**Comment by JamesNK** [comment]
Closing as answered.
