### ISSUE TITLE
Create generated code manually

### ISSUE THREAD

**Issue by glerchundi** [grpc/grpc-dotnet#1147]
I would like to create the generated code manually through the `protoc` command. This requirement is mainly motivated by our central specification repository and the set of SDKs we create automatically starting from those.

I've taken a brief look to the code and I wasn't able to see any easy to follow way to build the generator and call it manually from our custom builder.

I'm missing something? Would it be possible to guide me to the right direction?

Thanks!

**UPDATE**: I started tracing `Grpc.Tools` and it seems this contains the generator binary. I found this one in the core repo. documentation: https://github.com/grpc/grpc/blob/master/src/csharp/BUILD-INTEGRATION.md

I don't know if this is the way to go or not, any tip in this matter would be really helpful!

**Comment by BrennanConroy** [comment]
You can call `protoc` yourself and if you remove the `Protobuf` item group from your .csproj, then we wont generate anything for you.

**Comment by glerchundi** [comment]
Thanks for the response!

The doubt I had was mainly because I thought the generator was also part of this project (which isn't). Not having any info. or clue that guided me in that direction would probably avoided this misunderstanding. An update to the docs would be much appreciated!

I think this can be considered closed!
