### ISSUE TITLE
Typo in "canceled" ?

### ISSUE THREAD

**Issue by StefH** [grpc/grpc-dotnet#1150]
At several places `canceled` is used, however the spelling used in .NET Framework is `cancelled`.

See for example here:
https://github.com/grpc/grpc-dotnet/blob/3518cd757002f5a685f34d277e876850b7637ecc/test/Grpc.Net.Client.Tests/CancellationTests.cs#L53-L54

Both spellings are valid according to https://www.grammarly.com/blog/canceled-vs-cancelled/
However it's maybe better to align with the .NET Framework?

**Comment by JamesNK** [comment]
.NET uses Canceled.

https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskcompletionsource-1.trysetcanceled?view=net-5.0

However gRPC tends to use Cancelled, e.g. StatusCode.Cancelled.

I've tried to use Canceled here where possible.

**Comment by StefH** [comment]
I'm confused... 🙂

.NET also uses 'cancellation' ...

**Comment by JamesNK** [comment]
They're different words.
