### ISSUE TITLE
grpc_csharp_ext assembly:<unknown assembly> type:<unknown type> member:(null)

### ISSUE THREAD

**Issue by ComptonAlvaro** [grpc/grpc-dotnet#1151]
I have a Xamarin Android project, which target is Android 8.0 (Oreo). This application is a gRPC client that will consume the gRPC service that is running in a computer.

I have another client, a simple WPF project which target is Net Core 3.1. This is another client, that runs in the same computer where is my gRPC service.

I have a console application, that runs in the computer and start the gRPC service. This console application is a Net Core 3.1 application.

I have a Net Standard 2.1 library, that has the code that creates the gRPC service and calls the service. It is used for both client, Xamarin and WPF.

When I call to  the service from my WPF application, that runs in the same computer, I get response from service, but when I use the Xamarin application, that I am debugging in a device, not in an emultaror, i guet the following error:

`grpc_csharp_ext assembly:<unknown assembly> type:<unknown type> member:(null)`

This is the code of how I set my service:

`public static void Main(string[] args)
        {
            try
            {
                //Configuración del nivel de log
                //Environment.SetEnvironmentVariable("GRPC_VERBOSITY", "DEBUG");

                //Configuración para indicar el tipo de resolución DNS. Esto en principio no es necesario.
                Environment.SetEnvironmentVariable("GRPC_DNS_RESOLVER", "native");

                //Crea un servicio con gRPC directamente, no con .NET
                const int miPort = 5001;

                var cacert = File.ReadAllText("Keys/ca.crt");
                var cert = File.ReadAllText("Keys/server.crt");
                var key = File.ReadAllText("Keys/server.key");

                var keypair = new KeyCertificatePair(cert, key);
                var sslCreds = new SslServerCredentials(new List<KeyCertificatePair>
                                    {
                                        keypair
                                    }, cacert, false);

                Server server = new Server()
                {
                    Services = { Gestor.BindService(new GestorAplicacionesService()) },
                    //Ports = { new ServerPort("0.0.0.0", miPort, ServerCredentials.Insecure) },
                    Ports = { new ServerPort("192.168.1.33", miPort, ServerCredentials.Insecure) },
                    //Ports = { new ServerPort("0.0.0.0", miPort, sslCreds) },
                    //Ports = { new ServerPort("192.168.1.33", miPort, sslCreds) },
                    //Ports = { new ServerPort("localhost", miPort, sslCreds) },
                };
                server.Start();
                Console.WriteLine("Started server on port " + miPort);
                server.ShutdownTask.Wait();
                //Console.WriteLine("Press any key to stop...");
                //Console.ReadKey();
            }
            catch (Exception ex)
            {
                using (System.IO.StreamWriter file = new System.IO.StreamWriter(@"log.txt", true))
                {
                    file.WriteLine(ex.Message);
                }

                Console.WriteLine(ex.Message);
                Console.ReadKey();
            }
        }`

This is the code of my client library:

```
`        private Gestor.GestorClient GetClient()
        {
            Environment.SetEnvironmentVariable("GRPC_VERBOSITY", "DEBUG");
            //Environment.SetEnvironmentVariable("GRPC_TRACE", "api,cares_resolver,cares_address_sorting");


            var keypair = new KeyCertificatePair(_clientCertificate, _clientPrivateKey);
            var sslCreds = new SslCredentials(_caCertificate, keypair);

            //var channel = new Channel(_serviceAddress, _port, sslCreds);
            //var channel = new Channel(_serviceAddress, _port, SslCredentials.Insecure);
            **var channel = new Channel("192.168.1.33", _port, SslCredentials.Insecure);**
            var client = new Gestor.GestorClient(channel);
            return client;
        }`
```

NOTE: in in the line that is in bold characters where I get the exception.

this is the code in my Xamarin client:

`        private async void btnTestServicio_Click()
        {
            try
            {
                GrpcClient.GestorAplicaciones miGrpcClient = new GrpcClient.GestorAplicaciones(_serviceAddress, _port, _caCertificate, _clientCertificate, _clientPrivateKey);

                string miSaludo = await miGrpcClient.PingAsync("Álvaro");

                ShowAlert("Error", miSaludo);
            }
            catch (Exception ex)
            {
                ShowAlert("Error", ex.Message);
            }
        }`

I attached all my solution with all the projects, for this could help.

[GestorAplicaciones.zip](https://github.com/grpc/grpc-dotnet/files/5720692/GestorAplicaciones.zip)

Thanks so much.

**Comment by JamesNK** [comment]
You're using Grpc.Core. This repository is for Grpc.Net.Client and Grpc.AspNetCore.

Please repost your question at https://github.com/grpc/grpc
