### ISSUE TITLE
ASP.NET Core hosted Blazor WebAssembly project throws NETSDK1082 when .proto is compiled with Grpc.AspNetCore

### ISSUE THREAD

**Issue by Hristo-Nikodimov-Nenkov** [grpc/grpc-dotnet#1154]
I've created new ASP.NET Core hosted Blazor WebAssembly project with PWA option on. I've added Grpc.AspNetCore package to Shared and compiled account.proto for Server and Client.

After I've added the protobuf compilation my client project throws:
Code: NETSDK1082
Description: There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'.	
Project: TestApp.Client
File: C:\Program Files\dotnet\sdk\5.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets

**Comment by JamesNK** [comment]
You're referencing an ASP.NET Core library in Web Assembly.

Update your app to reference Grpc.Net.Client and Grpc.Tools instead.

**Comment by Hristo-Nikodimov-Nenkov** [comment]
I am referencing Grpc.AspNetCore in the "Shared" project.
