### ISSUE TITLE
.netstandard2.0 support is missing and needed for Unity3D

### ISSUE THREAD

**Issue by doctorpangloss** [grpc/grpc-dotnet#1155]
Do you have a timeline for when support would be added?

Alternatively, can @jtattermusch spend some time maintaining the native libraries runtime for Unity?

**Comment by BrennanConroy** [comment]
Changing to netstandard2.0 wont do anything. Unity would need to provide an HTTP2 client and support netstandard2.1 for this to work.

**Comment by doctorpangloss** [comment]
In that ecosystem, maybe buying out the asset store package that supports HTTP/2 would work?

**Comment by JamesNK** [comment]
A custom HTTP/2 client probably won't work. Grpc.Net.Client uses HttpClient internally so the HTTP/2 stack needs to be compatible with HttpClient.

**Comment by Rand-Random** [comment]
FYI
Source: https://github.com/grpc/grpc/tree/master/src/csharp
NuGet: https://www.nuget.org/packages/Grpc.Core/
