### ISSUE TITLE
Best practice for including external .proto files in container build images

### ISSUE THREAD

**Issue by deesejohn** [grpc/grpc-dotnet#1160]
I am kind of uncertain what to do when referencing `*.proto` from outside the project.
Example: 
```xml
<Protobuf Include="..\..\protos\example.proto" GrpcServices="Client" />
```

My Dockerfile is included in the project directory `src\example-client\Dockerfile`, and the docker build context is `src\example-client`. I'm trying to avoid changing the docker context to the root of the mono repo. The build will fail because docker cannot reference files outside of the build context (aka, `COPY ../../protos .`). I tried searching around and came accross issue  #183, but that seems like it would result in the same issue just with a nuget reference.

Some examples show manually copying/pasting the `..\..\protos\example.proto` to `src\example-client\Protos\example.proto` and updating the include to:
```xml
<Protobuf Include="Protos\example.proto" GrpcServices="Client" />
```

In order to avoid copy/pasting manually I updated my build to include:
```xml
<Target BeforeTargets="PreBuildEvent" Condition="'$(Configuration)' != 'Release'" Name="CopyProtos">
  <Copy SourceFiles="..\..\protos\example.proto" DestinationFolder="Protos" ContinueOnError="true" />
</Target>
```

It worked, but not ideal. I looked at how gRPC clients are handled with Go, and it looks like the generated `*.pb.go` and `*_grpc.pb.go` files are generally just checked into source control. So I modified my build to do this:
```xml
<ItemGroup Condition="'$(Configuration)' != 'Release'">
  <Protobuf Include="..\..\protos\example.proto" OutputDir="proto"
            GrpcServices="Client" CompileOutputs="false" />
</ItemGroup>
```

This worked and felt like the right approach, until I read it might be an anti-pattern.

> The tooling package Grpc.Tools is required to generate the C# assets from *.proto files. The generated assets (files):
> * Are generated on an as-needed basis each time the project is built.
> * Aren't added to the project or checked into source control.
> * Are a build artifact contained in the obj directory.
>
> -- <cite>[C# Tooling support for .proto files][1]</cite>

So is this actually an anti-pattern in this instance, or are other teams doing similar approaches? Are there better solutions?

[1]: https://docs.microsoft.com/en-us/aspnet/core/grpc/basics?view=aspnetcore-5.0#c-tooling-support-for-proto-files

**Comment by BrennanConroy** [comment]
You can instead check in the built class files from the proto files
cc @JunTaoLuo

**Comment by chwarr** [comment]
At the end of the day, protoc needs to be able to load the .proto files that you are importing. I know of no way around that.

Could you in your build script, before calling `docker build`, create a symlink in the build context to the directory with the external .proto files? (I don't remember if `docker build` will follow symlinks. If not, recursively copy the external protos into the build context.)

**Comment by deesejohn** [comment]
Hey, thanks for the replies.

@BrennanConroy, I believe that is what my last modification is doing, I'm generating the gRPC classes to the directory `proto` which would then be checked into source control. I was worried checking them into source control was an anti-pattern based on that documentation snippet though.

@chwarr, I believe I have seen a symlink solution in the wild, but would prefer including the generated classes if that is not an anti-pattern.

I'm planning to move forward with my last solution (generating the classes to a folder that is included in the build context and checked into source control) but would appriate knowing if there is any reason to not to do so. If there is no reason to be concerned about this approach, please feel free to close the issue.

**Comment by JunTaoLuo** [comment]
The reason we recommend generating the classes is recommended is that it is kept in sync with the proto files. Checking in the generated files is fine if you regenerate those files each time the proto files are changed. This could be accidentally missed or become a burden which is why we recommend against it. However, if you need it in your scenario, that approach is acceptable too.

**Comment by deesejohn** [comment]
Awesome, thanks for the guidance, glad to know it isn't a major issue, but against convention.

**Comment by chwarr** [comment]
You'll also want to regenerate the .cs files if protoc changes (e.g., a different version is used), not just on changes to the .proto files. That's a dependency that often gets missed when writing build system rules, and I've fixed this bug a number of times myself. 😀

Also, keep in mind that protoc and the ProtoBuf library need to be kept in sync with each other. New code gen may rely on newer APIs in the library and vice-versa. (This may not be strictly necessary in all cases, but mismatches have caused problems in the past.)
