### ISSUE TITLE
is xamarin supported, I am trying to access the vs2019 template greeter service from xamarin.forms android app but it can't find the service

### ISSUE THREAD

**Issue by yasarmuh** [grpc/grpc-dotnet#1162]

**Comment by yasarmuh** [comment]
https://stackoverflow.com/questions/65585099/grpc-core-rpcexception-statusstatuscode-unavailable-detail-error-starting

**Comment by JamesNK** [comment]
Grpc.Net.Client currently doesn't support Xamarin. Use Grpc.Core instead.
