### ISSUE TITLE
Is Unix domain socket (UDS) it .NET Framework gRpc?

### ISSUE THREAD

**Issue by Rand-Random** [grpc/grpc-dotnet#1166]
I would like to ask if it is possible to use Unix domain socket (UDS) found eg here.
https://github.com/grpc/grpc-dotnet/tree/master/examples/Transporter

with the "other" gRpc Projekt?
https://www.nuget.org/packages/Grpc.Core/
https://github.com/grpc/grpc/tree/master/src/csharp

I couldn't find a way to specify the `HttpHandler`, searching the Web only brought this unanswered StackOverflow question
https://stackoverflow.com/questions/62285582/grpcchannel-for-net-framework-with-httphandler

Note: 
I wasn't sure where would have been the best place to ask my question here on the other github page.
Sorry, if I chose wrong.

**Comment by BrennanConroy** [comment]
No, this feature only exists for Grpc.Net.Client.

**Comment by Rand-Random** [comment]
To bad :(
Thanks for the fast response.
