### ISSUE TITLE
Updating from .NET Core 3.1 to .NET5 breaks error handling in streaming methods

### ISSUE THREAD

**Issue by moxon6** [grpc/grpc-dotnet#1168]
### What version of gRPC and what language are you using?

gRPC-web / C#

```
Grpc.AspNetCore Version="2.32.0"
Grpc.AspNetCore.Web Version="2.33.1"
```

### What operating system (Linux, Windows,...) and version?

Running inside `.NET 5.0` devcontainer `mcr.microsoft.com/vscode/devcontainers/dotnet:dev-5.0` docker image

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)

```
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.101/

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  5.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### What did you do?

I used the [grpc-web](https://github.com/grpc/grpc-web) to generate commonjs clients for a simple echo service example
`protoc -I=/workspace echo.proto --js_out=import_style=commonjs:client --grpc-web_out=import_style=commonjs,mode=grpcwebtext:client`

I tested a few error scenarios:
1. Unary call that throws an exception
2. Streaming call that throws an exception immediately
3. Streaming call that throws an exception after at least one message

The following code snippet corresponds to scenario 3

```csharp
    public override async Task ServerStreamingEcho(ServerStreamingEchoRequest request, IServerStreamWriter<ServerStreamingEchoResponse> responseStream, ServerCallContext context)
    {
        await responseStream.WriteAsync(
            new ServerStreamingEchoResponse
            {
                Message = $"Reply to {request.Message} from .NET"
            });
        
        var status = new Status(StatusCode.PermissionDenied, "Permission denied");
        throw new RpcException(status);
    }
```

### What did you expect to see?

All three scenarios should trigger the error handler in the following snippet:

```js 
const stream = echoService.serverStreamingEcho(streamRequest, customHeaders);
  stream.on('data', (response) => {
    console.log(response);
    callback(response.getMessage());
  });

  stream.on('status', (...x) => {
    console.log(x);
  });
  
  stream.on('error', (err) => {
    console.error(err);
  });
```

### What did you see instead?

Only the first two scenarios trigger the error handler, the third does not.
Instead the status callback is triggered.

### Anything else we should know about your project / environment?

On closer inspection of the raw base64 response I noticed this:

`echo "AAAAACAKHlJlcGx5IHRvIEhlbGxvIFdvcmxkIGZyb20gLk5FVA==gAAAADFHcnBjLVN0YXR1czogNw0KR3JwYy1NZXNzYWdlOiBQZXJtaXNzaW9uIGRlbmllZA0K" | base64 --decode`

produces 

```
Reply to Hello World from .NET�1Grpc-Status: 7
Grpc-Message: Permission denied
```

It seems upgrade from .NET Core 3.1 to .NET 5 is causing [`GrpcProtocolConstants.StatusTrailer`](https://github.com/grpc/grpc-dotnet/blob/3518cd757002f5a685f34d277e876850b7637ecc/src/Grpc.AspNetCore.Server/Internal/GrpcProtocolConstants.cs#L61) to be `"Grpc-Status"` [due to this line](https://github.com/dotnet/aspnetcore/blob/2f64d67a7ce574f4b02103aea2a6bf00ad256df7/src/Http/Headers/src/HeaderNames.cs#L140) instead of `"grpc-status"` (which is hardcoded)

As a result, the standard grpc-web client implementation is not discovering the error messages in the stream `https://github.com/grpc/grpc-web/blob/master/javascript/net/grpc/web/grpcwebclientreadablestream.js`:

```js
if (GRPC_STATUS in trailers) {
  grpcStatusCode = trailers[GRPC_STATUS];
  delete trailers[GRPC_STATUS];
}
if (GRPC_STATUS_MESSAGE in trailers) {
  grpcStatusMessage = trailers[GRPC_STATUS_MESSAGE];
  delete trailers[GRPC_STATUS_MESSAGE];
}
```

Where

```js
const GRPC_STATUS = "grpc-status";
const GRPC_STATUS_MESSAGE = "grpc-message";
```

It seems the first two scenarios do not have the same issue because Unary calls and Streaming calls that error immediately add the grpc-status header to the request itself, and the headers are case-insensitive

### Resolution

From my understanding of the [grpc web protocol](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md) implementations should "use lower-case header/trailer names".

### Workaround
My current workaround is downgrading to .NET Core 3.1 and using the older lower-case version of grpc-status

**Comment by JamesNK** [comment]
Thanks for the detailed description.

I believe this PR will fix it - https://github.com/grpc/grpc-dotnet/pull/1170
