### ISSUE TITLE
Generic method realizations with different types throw AmbiguousMatchException

### ISSUE THREAD

**Issue by RebelionTheGrey** [grpc/grpc-dotnet#1172]
Hello. 

I have this class implementation

```
    public interface IReadRepository<T> where T: class
    {
        Task<ServiceObject> Get(ExpressionDTO<T> request);
    }

    public sealed class RouteCRUD : IReadRepository<TradeRoute>, IReadRepository<BettingProfile>, IGrpcService
    {
        public RouteCRUD()
        {
        }

        public async Task<ServiceObject> Get(ExpressionDTO<TradeRoute> request)
        {
               ...
        }

        public async Task<ServiceObject> Get(ExpressionDTO<BettingProfile> request)
        {
               ...
        }
    }
```

But on method 'Get' calling I get an error like this:
>       info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
>       Request starting HTTP/2 POST https://localhost:5028/RouteCRUD/Get application/grpc -
>       fail: Microsoft.AspNetCore.Server.Kestrel[13]
>       Connection id "0HM5NAMO0UNB4", Request id "0HM5NAMO0UNB4:00000005": An unhandled exception was thrown by the application.
>       Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches:
> 
>       gRPC - /RouteCRUD/Get
>       gRPC - /RouteCRUD/Get                                                                                                   
>       gRPC - Unimplemented method for RouteCRUD
>       gRPC - Unimplemented service                                                                                               
>          at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
>          at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
>          at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, CandidateState[] candidateState)
>          at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
>          at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher.MatchAsync(HttpContext httpContext)
>          at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
>          at Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.Invoke(HttpContext context)
>          at Microsoft.AspNetCore.Hosting.HostingApplication.ProcessRequestAsync(Context context)
>          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
> info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
>       Request finished HTTP/2 POST https://localhost:5028/RouteCRUD/Get application/grpc - - 500 0 - 55.2336ms

Is it possible to realize generic methods like this or not? And if it possible, so, what should I do for this?

Thank you.

.NET Core - .NET 5.0.1

**Comment by JamesNK** [comment]
You're using protobuf-net.Grpc.

Ask questions about that library here - https://github.com/protobuf-net/protobuf-net.Grpc/issues
