### ISSUE TITLE
Data type for port number in ServerPort

### ISSUE THREAD

**Issue by sbradl** [grpc/grpc-dotnet#1173]
The type of the port number in ServerPort is Int32. Shouldn't this be ushort? Putting a number larger than the max ushort value in results in an overflow.

Is this by design?

**Comment by JamesNK** [comment]
There is the assumption that when you specify a port that you specify a valid value.

**Comment by sbradl** [comment]
Why not enforce this assumption by using a more suited type?

**Comment by JamesNK** [comment]
The only ServerPort property in this repo comes from the command line where the type doesn't really matter.

Are you talking about https://grpc.github.io/grpc/csharp/api/Grpc.Core.ServerPort.html?

That's a Grpc.Core type. Issues for it should go to grpc/grpc repo.
