### ISSUE TITLE
Can we config streaming backpressure using the dotnet Grpc packages ?

### ISSUE THREAD

**Issue by huliang-microsoft** [grpc/grpc-dotnet#1179]
Hello, I am implementation dotnet core microservices using gRPC protocol to communicate. The services are talking in bi-directional streaming

I am using grpc-dotnet libraries to implement my service: e.g. Grpc.AspNetCore, Grpc.Net.Client. I see a similar question here in grpc repo https://github.com/grpc/grpc/issues/13955 but I am not using grpc.core directly. Is there a way to customize the backpressure configuration? or is it fully handled automatically by grpc-dotnet?

Thanks

**Comment by JamesNK** [comment]
You can customize flow control window sizes in Kestrel - https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.http2limits?view=aspnetcore-5.0

I'm not sure whether there is an equivilent setting in HttpClient, or whether HttpClient just uses what the server specifies.

**Comment by JamesNK** [comment]
Closing as answered.
