### ISSUE TITLE
Cannot build "Counter" client example

### ISSUE THREAD

**Issue by daniol** [grpc/grpc-dotnet#1181]
### What version of gRPC and what language are you using?
2.34.0

### What operating system (Linux, Windows,...) and version?
Windows 10 - 1809

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET 5.0.2
Visual Studio 2019 - 16.8.4

### What did you do?
Checkout the gRPC examples. Open Counter.sln

### What did you expect to see?
Client resolves the namespace "Count", I can see "Protos" also in the Client project and the client example compiles.

### What did you see instead?
- Client project cannot resolve the namespace "Count". 
- I don't see the "Protos" (count.proto) on the client project
- Client example does not compile (Server does).
- Warning NU1604 (_Project dependency does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results_)

See build result:

```
1>------ Build started: Project: Client, Configuration: Debug Any CPU ------
1>C:\Projects\gRPC\gRPC_Counter\Client\Client.csproj : warning NU1604: Die Projektabhängigkeit "Google.Protobuf" enthält keine einschließliche Untergrenze. Schließen Sie eine Untergrenze in die Abhängigkeitsversion ein, um konsistente Wiederherstellungsergebnisse zu erzielen.
1>C:\Projects\gRPC\gRPC_Counter\Client\Client.csproj : warning NU1604: Die Projektabhängigkeit "Grpc.Net.Client" enthält keine einschließliche Untergrenze. Schließen Sie eine Untergrenze in die Abhängigkeitsversion ein, um konsistente Wiederherstellungsergebnisse zu erzielen.
1>C:\Projects\gRPC\gRPC_Counter\Client\Client.csproj : warning NU1604: Die Projektabhängigkeit "Grpc.Tools" enthält keine einschließliche Untergrenze. Schließen Sie eine Untergrenze in die Abhängigkeitsversion ein, um konsistente Wiederherstellungsergebnisse zu erzielen.
1>C:\Projects\gRPC\gRPC_Counter\Client\Program.cs(21,7,21,12): error CS0246: The type or namespace name 'Count' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Projects\gRPC\gRPC_Counter\Client\Program.cs(48,52,48,59): error CS0246: The type or namespace name 'Counter' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Projects\gRPC\gRPC_Counter\Client\Program.cs(54,62,54,69): error CS0246: The type or namespace name 'Counter' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Projects\gRPC\gRPC_Counter\Client\Program.cs(71,62,71,69): error CS0246: The type or namespace name 'Counter' could not be found (are you missing a using directive or an assembly reference?)
1>Done building project "Client.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

See screenshot of solution explorer:

![counter_projs](https://user-images.githubusercontent.com/196808/105975639-78e81e80-608f-11eb-95de-34939ccf7173.JPG)

**Comment by JamesNK** [comment]
The example projects reference properties from this file: https://github.com/grpc/grpc-dotnet/blob/76ae64d3b0e28772bc4d97c0d8a146b3609b465d/build/dependencies.props

If you copy the example directory by itself to a new location then you need to update the package references to use the versions in that file.

**Comment by daniol** [comment]
Checking out the entire repository compiles correctly both server and client examples and the "Protos" is also visible. Maybe should be mention this on the "readme" for "newbies" like me?

However I am curious why is this so. I can only find a reference to "build/dependencies.props" on "Directory.Build.props", which is only referenced on "test/Directory.Build.props", but anywhere inside the examples. Excuse me? :D

**Comment by JunTaoLuo** [comment]
Using build/dependencies allows for easier management of package versions used in all projects and samples and is standard practice, see dotnet/runtime or dotnet/aspnetcore for example. The nearest Directory.Build.props (traversing through parent directories from the project file) is imported by convention by MSBuild so none of the csproj files need to import it explicitly.

**Comment by llccig** [comment]
### t骗人；3【入库I人俄经济如何节假日朋克``锐捷假日符号今日发货人靠任何人人类发明们看见额经费纳入迷人风景让人们收客
