### ISSUE TITLE
Mapping don't work when fields do have underscore in it's name

### ISSUE THREAD

**Issue by yehia2amer** [grpc/grpc-dotnet#1184]
### What version of gRPC and what language are you using?
gRPC: Grpc.AspNetCore (2.34.0)
Language: C#

### What operating system (Linux, Windows,...) and version?
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET SDK: 5.0.101

### What did you do?
When I Try to Query a table and return result to a Protobuf message if the field do have underscore in it's name it will not be mapped.

For Example I created this Method called GetCarsDetailsbyPartyNumbers sends a CarNumbersRequest message and receives a CarsDetailsbyCarNumbersReplay message

```
public override async Task<CarsDetailsbyCarNumbersReplay> GetCarsDetailsbyCarNumbers(CarNumbersRequest carNumbersRequest, ServerCallContext context)
        {
            string[] carNumbers = carsNumbersRequest.CarNumbers.ToArray();

            using NpgsqlConnection conn = new NpgsqlConnection(connectionString);
            conn.Open();

            var Query = "SELECT Car_Name, CarModel From Cars where car_number = ANY (@carNumbers);";

            CarsDetailsbyCarNumbersReplay carsDetailsbyCarNumbersReplay = new CarsDetailsbyCarNumbersReplay();

            var result = await conn.QueryAsync<CarsGeneralInfoMessage>(Query, new { carNumbers = carNumbers });

            carsDetailsbyCarNumbersReplay.CarsGeneralInfo.Add(result);

            return await Task.FromResult(carsDetailsbyCarNumbersReplay);
        }
```
greet.proto

```
syntax = "proto3";

option csharp_namespace = "GrpcService";

package greet;

service Greeter {
  rpc GetCarsDetailsbyPartyNumbers (CarNumbers) returns (CarsDetailsbyPartyNumbersReplay);
}

message CarNumbersRequest {
  repeated string CarNumbers = 1;
}

message CarsDetailsbyCarNumbersReplay {
  repeated CarsGeneralInfoMessage CarsGeneralInfo = 1;
}

message CarsGeneralInfoMessage {
    string Car_Name=1;
    string CarModel=2;
}  
```

### What did you expect to see? What did you see instead?

The Car_Name Field is not mapped just because it do have underscore in it's name. and if I Replaced the name with anything else mapping works fine.

**Comment by JamesNK** [comment]
Generated protobuf types have underscores removed.

How that is handled by the data mapper will vary based on what library you are using. You should ask that issue in its GitHub repo or on StackOverflow.

**Comment by yehia2amer** [comment]
> 
> 
> Generated protobuf types have underscores removed.
> 
> How that is handled by the data mapper will vary based on what library you are using. You should ask that issue in its GitHub repo or on StackOverflow.

Thanks for the replay @JamesNK . I Think that at least this should be documented, if it is not going to be fixed. because it is not the expected behavior. The user expects that if the column name is the same as the database name it should be mapped without any customization to the mapper.

**Comment by JamesNK** [comment]
I've updated the docs to explicitly mention that property names change - https://github.com/dotnet/AspNetCore.Docs/pull/21502

However, how that impacts other libraries is outside the scope of the docs.
