### ISSUE TITLE
Empty string is interpreted as null when making calls with C# client

### ISSUE THREAD

**Issue by erikljung** [grpc/grpc-dotnet#1191]
### What version of gRPC and what language are you using?
C# for both client and server
Google.Protobuff 3.14
Grpc.Net.Client 2.35.0
Grpc.Net.ClientFactory 2.35.0
Grpc.Tools 2.35.0

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET 5.0.102

### What did you do?
I tried to pass a message containing a string with the value of `""`. 

### What did you expect to see?
That `Test.Str` should end up as `""` at my server. Tried the same thing with BloomRPC and the value ended up as `""`.

### What did you see instead?
`Test.Str` was `null`. 

### Anything else we should know about your project / environment?
The client code I used to produce this error:

```
message Test {
   string str = 1;
}
service TestService {
   rpc TestEmptyString (Test) returns (TestResponse);
}
```
```
var channel = GrpcChannel.ForAddress("https://localhost:5000");
var client = new TestService.TestServiceClient( channel );
await client.TestEmptyStringAsync( new Test() { Str = "" } );
```

**Comment by JamesNK** [comment]
This is expected. There are docs on how to get null values - https://docs.microsoft.com/en-us/aspnet/core/grpc/protobuf?view=aspnetcore-5.0#nullable-types

**Comment by erikljung** [comment]
@JamesNK Thanks for the quick response. I'm probably missing something here, but I can't find anything in that doc about why empty string is interpreted as `null`. So I just want to get a better understanding about this, so forgive if the questions are stupid. 

1. Did you understand that in my example, the following is what the client is sending and the server receives
```
client | server
""        null
" "       " "
"foo"  "foo"
```

2. If I'm not the constructing the proto contract, then this would mean that I can't pass an empty string with the C# client?
I've verified that passing an empty string with a Node client and the BloomRPC client towards the same server implementation ended up as an expected empty string.

3. Could you please elaborate on why this is the expected behaviour? I unfortunately have a hard time understanding this.

Thanks for your help!
