### ISSUE TITLE
GrpcChannel, Dispose() and ShutDownAsync()

### ISSUE THREAD

**Issue by AnthonyGiretti** [grpc/grpc-dotnet#1192]
Hi,

I'm using a Console application which uses GrpcChannel.ForAddress to create a GrpcChannel.
Grpc.Core documentation says it's strongly recommanded to use ShutdownAsync() method when you don't need the Channel anymore, I checked its implementation and it unregistrer the Channel, but when I check the Dispose() method it seems to dispose every active call and dispose the HttpInvoker. 

So, if I use first Dispose() method do I still need to use ShutdownAsync() right after ?

Thanks

**Comment by JamesNK** [comment]
Just disposing GrpcChannel is fine. It cleans up everything that should be cleaned up.
