### ISSUE TITLE
Could we use grpc without https while the kestrel protocols configured `Http1AndHttp2`

### ISSUE THREAD

**Issue by WeihanLi** [grpc/grpc-dotnet#1194]
I'm trying to use GRPC http API to implement REST API(https://docs.microsoft.com/en-us/aspnet/core/grpc/httpapi?view=aspnetcore-5.0), the kestrel server had configured `Http1AndHttp2` protocal, seemed that I can not access GRPC service when I use http endpoint, error details:

![image](https://user-images.githubusercontent.com/7604648/107117825-e0844200-68b7-11eb-83ce-0df98692dab8.png)

It seemed I found the reason why it occurs

> TLS is required for negotiation when an endpoint is `HttpProtocols.Http1AndHttp2`
<https://github.com/grpc/grpc-dotnet/issues/505#issuecomment-530084100>

But I'm wondering that is there some work around solutions?

Reproduce sample code: <https://github.com/WeihanLi/SamplesInPractice/tree/6963d990ac4874bd00351fab329b91b11c714759/GrpcSample/GrpcClientSample/GrpcServiceTest.cs#L24>

**Comment by JamesNK** [comment]
The work around is to either use HTTPS, or have a HTTP/2 only endpoint.

**Comment by WeihanLi** [comment]
Got it, thanks @JamesNK
