### ISSUE TITLE
Why is a streaming task not ended although I have cancelled the MoveNext() and disposed streamingCall

### ISSUE THREAD

**Issue by BadgerTheAdger** [grpc/grpc-dotnet#1195]
https://github.com/dotnet/AspNetCore.Docs/issues/21464

**Comment by BrennanConroy** [comment]
Can you post the details of your issue here please?

And a minimal sample.

**Comment by BadgerTheAdger** [comment]
I and am wondering if I should await a Task that runs ResponseStream.MoveNext in the background (i.e constantly pulls data from the API)? 

I have the following scenario:
1. Create a cancellation token
2. Create a background task pulling data from the server, pass cancellation token there:

```var streamTask = Task.Run(async () =>
{
    while (await streamingCall.ResponseStream.MoveNext(cancellationTokenSource.Token))
    {
        var current = streamingCall.ResponseStream.Current;
        // do something with current element
    }
    socket.OnStreamClosed();
});```

3. CancellationTokenSource.Cancel(); // or streamingCall.Dispose()
4. await streamTask // this never returns

And I have the same issue if I call streamingCall.Dispose() instead of CancellationToken.Cancel()

My question is:

1. should I await the task?
2. Why doesn't it return the control although we have canceled the cancellationToken / or disposed the streamingCall?

**Comment by JamesNK** [comment]
I think I might have fixed this issue earlier this week. I'll see if I can recreate what you're doing in a unit test to double check.

**Comment by JamesNK** [comment]
This will be in the next gRPC release, or you can try it out using the preview feed - https://github.com/grpc/grpc-dotnet#grpc-nuget-feed

**Comment by Bogdan2033** [comment]
> I am wondering if I should await a Task that runs ResponseStream.MoveNext in the background (i.e constantly pulls data from the API)?
> 
> I have the following scenario:
> 
> 1. Create a cancellation token
> 2. Create a background task pulling data from the server, pass cancellation token there:
>    ```
>    var streamTask = Task.Run(async () =>
>    {
>        while (await streamingCall.ResponseStream.MoveNext(cancellationTokenSource.Token))
>        {
>            var current = streamingCall.ResponseStream.Current;
>            // do something with current element
>        }
>        socket.OnStreamClosed();
>    });
>    ```
> 3. CancellationTokenSource.Cancel(); // or streamingCall.Dispose()
> 4. await streamTask // this never returns
> 
> And I have the same issue if I call streamingCall.Dispose() instead of CancellationToken.Cancel()
> 
> My question is:
> 
> 1. should I await the task?
> 2. Why doesn't it return the control although we have canceled the cancellationToken / or disposed the streamingCall?

Куда пропал? Напиши мне в телегу @ElloVenera
