### ISSUE TITLE
The HTTP/2 server reset the stream. HTTP/2 error code 'HTTP_1_1_REQUIRED'

### ISSUE THREAD

**Issue by mahgo** [grpc/grpc-dotnet#1196]
I have two ASP.NET Core 3.1 servers, of which I'm using gRPC for one to make requests to the other. They are both running on IIS locally (not express) for development. When I make the call, I get the following error:

`Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: An error occurred while sending the request. IOException: The request was aborted. Http2StreamException: The HTTP/2 server reset the stream. HTTP/2 error code 'HTTP_1_1_REQUIRED' (0xd).",`

Here is my code:

`GrpcChannel channel = this.CreateChannel(url);
POI.POIClient client = new POI.POIClient(channel);

GetPOIResponse response;
try
{
    response = await client.GetPOIAsync(
        new GetPOIRequest
        {
            Id = id.ToString(),
            S2CellId = s2CellId
        });
}
catch (RpcException ex)
{
    throw ex;
}`

`private GrpcChannel CreateChannel(string address)
{
    HttpClientHandler httpHandler = new HttpClientHandler();
    HttpClient httpClient = null;
    Uri uri = new Uri(address);
    if (!string.IsNullOrEmpty(uri.LocalPath))
    {
        SubdirectoryHandler subdirectoryHandler = new SubdirectoryHandler(httpHandler, uri.LocalPath);
        httpClient = new HttpClient(subdirectoryHandler);
    }

#if DEBUG
    // Return true to allow certificates that are untrusted/invalid
    httpHandler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;
#endif

    GrpcChannelOptions options = new GrpcChannelOptions();

    if (httpClient != null)
    {
        options.HttpClient = httpClient;
    }
    else
    {
        options.HttpHandler = httpHandler;
    }

    GrpcChannel channel = channel = GrpcChannel.ForAddress(address, options);
    return channel;
}`

Notes: 
- SubdirectoryHandler is from #880 as IIS is running my websites on sub directories.
- I am using self signed certificates for development.

**Comment by BrennanConroy** [comment]
Client certs do not work with HTTP2 and IIS. You need to set up pre-negotiation https://docs.microsoft.com/aspnet/core/grpc/authn-and-authz?view=aspnetcore-5.0#client-certificate-authentication and https://docs.microsoft.com/aspnet/core/security/authentication/certauth?view=aspnetcore-5.0#iis

**Comment by JamesNK** [comment]
There are requirements for using gRPC with .NET and IIS. You need .NET 5 and a new version of Windows.

See https://docs.microsoft.com/en-us/aspnet/core/grpc/supported-platforms?view=aspnetcore-5.0#aspnet-core-server-requirements

**Comment by mahgo** [comment]
Thanks, I'll try these things out.
