### ISSUE TITLE
Distribution and sharing of proto files between servers and clients

### ISSUE THREAD

**Issue by JunTaoLuo** [grpc/grpc-dotnet#12]
Splitting off the service reference consideration from https://github.com/grpc/grpc-dotnet/issues/5. Service reference is a mechanism that could be leveraged to better support .proto file sharing between servers and clients. We may want to use this as part of https://github.com/grpc/grpc-dotnet/issues/8 to illustrate its use for client and server templates.

**Comment by JunTaoLuo** [comment]
We are going to use https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.Extensions.ApiDescription.Design/build/Microsoft.Extensions.ApiDescription.Design.targets

This will allow us to hook into the ServiceReference mechanism. I will be creating a prototype for this to illustrate its use.

**Comment by JunTaoLuo** [comment]
In the current templates, the proto files are are shared file represented as project items. Editing the file under one project prevents the same file from being opened from the other project with the error "This document its opened by another project". Converting to service reference will resolve this issue.

**Comment by JamesNK** [comment]
Need to think about how this is shipped.

**Comment by JunTaoLuo** [comment]
We are no longer using a service reference to solve this problem. Instead we'll look into building a tool https://github.com/grpc/grpc-dotnet/issues/234.
