### ISSUE TITLE
Add extension methods with Type argument(s)

### ISSUE THREAD

**Issue by dmitry-bym** [grpc/grpc-dotnet#1202]
### Problem
I want to scan assembly and register all types but i can't do that for now because there is just generic method to register clients
For now i have to use this:
```c#
            services.AddGrpcClient<RPC.MyRpc.MyRpcClient>(o =>
            {
                o.Address = new Uri("https://localhost:5001/");
            });
            services.AddGrpcClient<RPC.My2Rpc.My2RpcClient>(o =>
            {
                o.Address = new Uri("https://localhost:5001/");
            });
```

I want to do so:
```c#
            var baseClient = typeof(ClientBase);
            var clientTypes = baseClient.Assembly.GetTypes().Where(x => baseClient.IsAssignableFrom(x)).ToArray();
            foreach (var clientType in clientTypes)
            {
                services.AddGrpcClient(clientType, factory =>
                {
                    factory.Address = new Uri("https://localhost:5001");
                });
            }
```

### Solution:
Use generic methods just as public api and use types as arguments inside. As i can see need to rewrite many generics methods. I can do that in pr
Note: Not only applies to this method

**Comment by BrennanConroy** [comment]
> Note: Not only applies to this method

What other methods would you want this to apply to?

Triage: We would be interested in having a method that accepts the type, note, we will not search for types ourselves.

**Comment by dmitry-bym** [comment]
### Just two methods, one for client, one for server:
 - AddGrpcClient
 - MapGrpcService

**Comment by JamesNK** [comment]
Both `AddGrpcClient` and `MapGrpcService` make heavy use of their generic parameter. Its not a simple matter to add non-generic versions of these methods. My guess is using reflection's `MakeGenericMethod` with the Type argument and calling the generic version would be the only quick way to do it.

It is probably possible to refactor these methods like you want, but what you're doing, scanning the assembly for types isn't something we encourage. There are performance costs with doing it, and it makes trimming and linking harder.

**Comment by dmitry-bym** [comment]
So about scaning, this is not an offer this is just example of use, yep for now i have to use `MakeGenericMethod`. 

> My guess is using reflection's MakeGenericMethod with the Type argument and calling the generic version would be the only quick way to do it. That's kind of a hack.

I think so too. 

I see public api which should be changed to implement it properly like `GrpcClientFactory`, so yep it will be a breaking change.
Thank you for answer
