### ISSUE TITLE
 Throw RpcException from RequestStream.WriteAsync() on call failure

### ISSUE THREAD

**Issue by lklein53** [grpc/grpc-dotnet#1205]
Hi,

Recently I started porting some C# projects from the grpc C# implementation to the grpc-dotnet client implementation (version 2.35.0).
I encountered a difference in the behaviour for calls to `RequestStream.WriteAsync()` on call failure. 
The grpc implementation would throw a RpcException whereas the grpc-dotnet implementation seems to throw an InvalidOperation excpetion.
https://github.com/grpc/grpc/issues/5975 is the request in the grpc project to throw a RpcExcpetion instead of an InvalidOperation exception. 

I am wondering if this will also be changed for the grpc-dotnet implementation ?

Kind regards,
Lars

**Comment by BrennanConroy** [comment]
Looks like this was merged in 2016 https://github.com/grpc/grpc/pull/6493, we should look at changing to have parity.

**Comment by JamesNK** [comment]
This was fixed a few weeks ago - https://github.com/grpc/grpc-dotnet/pull/1199. It will be in the next release.
