### ISSUE TITLE
Are there status code and Trailer metadata for BlockingUnaryCall?

### ISSUE THREAD

**Issue by huliang-microsoft** [grpc/grpc-dotnet#1206]
Hello, I am doing some instrumentation work for our gRPC calls. For all the other 4 calls, async unary, client streaming, server streaming and duplex streaming, I can access status code and trailers via call.GetStatus() and call.GetTrailers(). But for BlockUnaryCall, I dont see a method/property that allow me to do so. So my question is, are these information available for BlockingUnaryCall?

Thanks

**Comment by JamesNK** [comment]
No.
