### ISSUE TITLE
Support custom transport for JsInterop

### ISSUE THREAD

**Issue by TFTomSun** [grpc/grpc-dotnet#1208]
At the moment I am not aware of any possibility to define a service contract between blazor (wasm and server) and typescript .
Using grpc with a custom transport implementation over jsintetop might be a possibility to close that gap. As far as I know it could even be made pretty performant for blazor wasm using unmarshalled memory sharing. Has this feature already been considered or is there any other possibility to generate a typesafe contract between c# and typescript?

**Comment by JamesNK** [comment]
I'm not sure what you're asking for.

If you want to call gRPC-Web from WebAssembly you can do that today.

If you want to call gRPC-Web from TypeScript you would generate a client from the proto file using protoc. grpc-dotnet is not involved.

**Comment by TFTomSun** [comment]
Ah, so I can have a grpc server running on blazor wasm? over which protocol would the typescript client then communicate with the server?

**Comment by JamesNK** [comment]
Ok, I see what you're trying to do.

The dotnet-grpc server implementation runs on ASP.NET Core server, and I doubt that will ever support Blazor WASM.

**Comment by TFTomSun** [comment]
Is there a technical reason for that? I think the problem here is that it's not possible to open a http port inside the browser sandbox.  But Am I missing something when I assume that replacing the http protocol with something like blazor - jsinterop (maybe over a custom unmarshalled array transport protocol) would work?

**Comment by JamesNK** [comment]
I doubt it is possible to open a port inside WASM, amoung other technical problems.

It took a lot of work to get the .NET features in Blazor WASM working today. Expanding it to support all of ASP.NET Core isn't going to be worth it to do this one particular thing.

**Comment by JamesNK** [comment]
If you really want this then you need to create an issue at https://github.com/dotnet/aspnetcore and present your case.

**Comment by TFTomSun** [comment]
I think you got me wrong. My goal is **not** to open a port in wasm. In contrast, I want to replace the socket based communication with jsinterp. But you are right, I'll file an issue in the aspnet core repo. It fits better there, and they probably understand my usecase better.

**Comment by TFTomSun** [comment]
moved to aspnet core repository
