### ISSUE TITLE
GRPC Web support for .NET Framework

### ISSUE THREAD

**Issue by TFTomSun** [grpc/grpc-dotnet#1209]
It seems that grpc web (server side) is currently only supported in ASP.NET Core which is limited to .NET Core / .NET 5. Is it possible to use GRPC web with a .NET Framework (e.g. .NET 4.8) server?

**Comment by JamesNK** [comment]
Yes, with a proxy.

Ask Grpc.Core questions at https://github.com/grpc/grpc
