### ISSUE TITLE
HttpApi doesn't write empty strings

### ISSUE THREAD

**Issue by GerardSmit** [grpc/grpc-dotnet#1213]
> _Not sure if I need to make an issue about HttpApi here. https://github.com/grpc/grpc-dotnet/issues/167 is for feedback, however there are 47 people subscribed to the thread which I don't want to notify. Also https://github.com/aspnet/AspLabs has issues disabled which brings me here._

### What version of gRPC and what language are you using?
```
Grpc.AspNetCore						: 2.32.0
Microsoft.AspNetCore.Grpc.HttpApi	: 0.1.0-alpha.20580.2
Microsoft.AspNetCore.Grpc.Swagger	: 0.1.0-alpha.20580.2
```

### What operating system (Linux, Windows,...) and version?
```
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
```

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
```
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7
```

### What did you do?
I've created a gRPC service that returns the following message:
```
message GuildUser {
    uint64 id = 1;
    string username = 2;
    string discriminator = 3;
    string nickname = 4;
}
```

After that I've followed https://docs.microsoft.com/en-us/aspnet/core/grpc/httpapi to create a REST API for the service.

### What did you expect to see?
Messages with all their fields.

### What did you see instead?
Messages with missing fields.

When an empty string is being written, the field is omitted. On the client-side this would cause the value to be `null` (or `undefined` in JavaScript), while it should be an empty string.

**Screenshot:**
![image](https://user-images.githubusercontent.com/2109929/108918985-89f66200-7632-11eb-86cd-e02924b4f46b.png)

**Comment by JamesNK** [comment]
Empty string is the default value and default values aren't written by Protobuf serializer or is equivilent JSON serializer. You could try making the property type `StringValue`.

**Comment by GerardSmit** [comment]
I see, with `StringValue` I get the expected result.

> default values aren't written by Protobuf serializer or is equivilent JSON serializer

Is this the expected behavior for HttpApi? For typed languages (e.g. C#) this doesn't matter since it's using the default value, but for untyped languages (e.g. JavaScript) this means you'll always get `undefined`, even with numbers.

A workaround would be to change everything to `XValue` (e.g. `int32` to `Int32Value`) but I'm not sure if that's the most prettiest solution...

**Comment by JamesNK** [comment]
> Is this the expected behavior for HttpApi

I think so but I haven't compared against grpc-gateway to see what it does (HttpApi is based on it).

**Comment by JamesNK** [comment]
Closing as answered

**Comment by GerardSmit** [comment]
I thought you wanted to compare against grpc-gateway to see what it did, excuse me for not answering.

grpc-gateway had an open issue about this as well. In v2 they emit default values.

**References:**
Issue: https://github.com/grpc-ecosystem/grpc-gateway/issues/233
V2 release planning: https://github.com/grpc-ecosystem/grpc-gateway/issues/1223
PR enabling default values: https://github.com/grpc-ecosystem/grpc-gateway/pull/1377.

---

If HttpApi doesn't want to omit default values by default: currently the `UnaryServerCallHandler` always uses the default formatter (`JsonFormatter.Default`):

https://github.com/aspnet/AspLabs/blob/07ebdf55d59814a85ec0efaded572e88729cc04c/src/GrpcHttpApi/src/Microsoft.AspNetCore.Grpc.HttpApi/UnaryServerCallHandler.cs#L278

If it were possible to provide your own JsonFormatter, then the settings `FormatDefaultValues` could be enabled:

```csharp
services.AddGrpcSwagger(config =>
{
	config.JsonFormatter = new JsonFormatter(JsonFormatter.Settings(true));
});
```

According to the docs the default values should then be written: https://developers.google.com/protocol-buffers/docs/reference/csharp/class/google/protobuf/json-formatter/settings

**Comment by JamesNK** [comment]
It looks like emitting default values is on by default in grpc-gateway V2. I didn't know it had changed.

In that case it should be turned on in HttpApi.

**Comment by JamesNK** [comment]
Done. I'm not sure when the package on NuGet will next be updated but you should be able to get the changes by adding this feed and using the latest version: https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json

**Comment by GerardSmit** [comment]
Alright, thanks! 😄

**Comment by SickoOrange** [comment]
how to turn it on to not emit the default value in json response? i am currently use go and find no way to do this
