### ISSUE TITLE
Up/down throughput difference in bi-di streaming

### ISSUE THREAD

**Issue by TheLever** [grpc/grpc-dotnet#1215]
Using the Racer example provided, I am wondering why there is such a huge difference in messages sent and messages received. While the numbers generally look good (as in messages/sec), I am wondering why the client "only" manages to send ~60k messages during the 30 sec duration, while the server sends ~235k messages in the same timespan?

Thanks,

**Comment by JamesNK** [comment]
Sending HTTP/2 and receiving HTTP/2 are quite different tasks. My guess is HttpClient is not as good at sending data as it is at receiving data.

**Comment by BrennanConroy** [comment]
You could experiment with increasing the starting window size on the server to see if that is causing the slowdown.
https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.server.kestrel.core.http2limits?view=aspnetcore-5.0
