### ISSUE TITLE
GRPC C-Core clients can connect to .NET Core server built on Linux, but not on Windows

### ISSUE THREAD

**Issue by anlsh** [grpc/grpc-dotnet#1218]
I've already asked this question [on StackOverflow](https://stackoverflow.com/questions/66464983/grpc-net-core-server-c-client-https-connection-fails-no-common-applicati), but I thought I'd repost it here.

I'm trying to get a GRPC server (written in .NET core) and client (written in C++) to communicate over a SSL/TLS-secured channel.

The server targets "netcoreapp3.1", and depends on "Grpc.AspNetCore" version 2.28.0. The server code itself is basically copied from some simple online examples. The `Startup.cs` and `Program.cs` are not too interesting on their own & probably aren't the problems, so I just uploaded them to [a gist](https://gist.github.com/anlsh/20b41d9ca5aa7f9c84a6c05e1722d7fb) (do note the call to `UseHttps` though).  Everything builds, and I know that it works because I wrote a .NET core GRPC client which connects over HTTPS just fine (sources for that [here](https://gist.github.com/anlsh/a15adf2244a5e3fba74c4df0520e1f40), also very simple).

Unfortunately, I need to be using a C++ client to make the connection. Theoretically, the process is simple: get the .pfx file corresponding to the certificate passed to the `UseHttps` call, use it to create a `server.crt` [via openssl](https://nerdia.net/2018/06/16/how-to-convert-a-certificate-pfx-file-to-crt-key-using-openssl/), and use that to create a secure channel for the C++ client like so:

    grpc::SslCredentialsOptions sslOpts{};
    sslOpts.pem_root_certs = file_to_string(path_to_server_crt);
    auto creds = grpc::SslCredentials(sslOpts);
    auto channel = grpc::CreateChannel("localhost:50052", creds);

I've used the client successfully with a C++ grpc server, so there's no lingering bugs on that side either. When I point it at my .NET core server though, things break. The client side info isn't interesting, just a GRPC error 14. When the server is set to log things at `Trace` though, something pops out

    dbug: Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer[2] 
      Connection id "0HM6UG4PBICBP" accepted.
    dbug: Microsoft.AspNetCore.Server.Kestrel[1]
          Connection id "0HM6UG4PBICBP" started.
    dbug: Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware[1]
          Failed to authenticate HTTPS connection.
    System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
    ---> System.ComponentModel.Win32Exception (0x80090367): No common application protocol exists between the client and the server. Application protocol negotiation failed.
    --- End of inner exception stack trace ---
    // Some detailed stack trace, pretty sure it's garbage
    dbug: Microsoft.AspNetCore.Server.Kestrel[2]
        Connection id "0HM6UG4PBICBP" stopped.
    dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
        Connection id "0HM6UG4PBICBP" sending FIN because: "The Socket transport's send loop completed gracefully

`No common application protocol exists between the client and the server`, that's certainly interesting: the server must be rejecting whatever protocol the C++ client is trying to use? What's the solution to this problem?

**Note**: I should mention that the C++ client is being compiled/run from WSL 1 (Ubuntu 18.04) whereas the server is being run on Windows Server 2019 Datacenter.

**EDIT**: Just bumped the app to target `netcore5.0` and use `Grpc.AspNetCore` version `2.3.5` and tried again. Nothing changes on the server side,  but the client now prints the following error. I don't think it reveals anything new, but I thought I'd add it

     E0303 14:28:14.976078900    1126 ssl_transport_security.cc:1458] Handshake failed with fatal error SSL_ERROR_SSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE.

The stack trace I describe as "garbage" earlier also gets quite a bit shorter, becoming

         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
         at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context)

**Comment by JamesNK** [comment]
I think your issue is caused by the C++ client wanting to use a TLS protocol that ASP.NET Core server doesn't enable by default

How to configure allowed protocols:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-5.0#ssltls-protocols

By default it is `None`, which means good defaults are chosen for you. Try more, specifically SSL3 - https://docs.microsoft.com/en-us/dotnet/api/system.security.authentication.sslprotocols?view=net-5.0

**Comment by anlsh** [comment]
Just tried setting the `SslProtocols` to `SslProtocols.Ssl3` as you suggested. It suppressed the client output about `SSLV3` and the server-side log entry about no common protocols has disappeared, but I'm getting a different one in its place (`The client and server cannot communicate, because they do not possess a common algorithm`)

    dbug: Microsoft.AspNetCore.Server.Kestrel[39] 
      Connection id "0HM6UJFL6AT99" accepted.
    dbug: Microsoft.AspNetCore.Server.Kestrel[1]
      Connection id "0HM6UJFL6AT99" started.
    fail: Microsoft.AspNetCore.Server.Kestrel[0] 
      Unhandled exception while processing 0HM6UJFL6AT99.
      System.ComponentModel.Win32Exception (0x80090331): The client and server cannot communicate, because they do not possess a common algorithm.
         at System.Net.SSPIWrapper.AcquireCredentialsHandle(ISSPIInterface secModule, String package, CredentialUse intent, SCHANNEL_CRED* scc)
         at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCHANNEL_CRED* secureCredential)
         at System.Net.Security.SslStreamPal.AcquireCredentialsHandleSchannelCred(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
         at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslStreamCertificateContext certificateContext, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
         at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint)
         at System.Net.Security.SecureChannel.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)                 at System.Net.Security.SecureChannel.NextMessage(ReadOnlySpan`1 incomingBuffer)
         at System.Net.Security.SslStream.ProcessBlob(Int32 frameSize)
         at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
         at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1.ExecuteAsync()
    dbug: Microsoft.AspNetCore.Server.Kestrel[2] 
      Connection id "0HM6UJFL6AT99" stopped.
    dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
      Connection id "0HM6UJFL6AT99" sending FIN because: "The Socket transport's send loop completed gracefully

I'll try cycling through the other options and report back

**Comment by anlsh** [comment]
These values fail with the `no common algorithm` error on server-side

     Tls13, Ssl3, Ssl2

These ones fail with the `no common protocol` one

    Tls12, Tls11, Tls, None, Default

None succeed, unfortunately >:(

**Comment by JamesNK** [comment]
I think changing that value created a new error rather than solving the old one.

I'm not a TLS expert so I'm not sure what exactly to try. There are various TLS options available here: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.https.httpsconnectionadapteroptions?view=aspnetcore-5.0

**Comment by anlsh** [comment]
Just in case someone who knows more about TLS happens across this issue, I thought I'd add some more info.

I pulled out Wireshark to take a look at the TLS client hellos being sent from the working and not-working clients

    - [Failed client hello](https://gist.github.com/anlsh/bcf5c4b7c079ddbfa8ee16c4ca40218c): Sent from [this Python Client](https://gist.github.com/anlsh/13542aaae5f65b517583592b3d9a1523)
    - [Working client hello](https://gist.github.com/anlsh/5fef006f526799095d3d52bf63861b0b), sent from the .net core client
    - [Server hello in response to the above](https://gist.github.com/anlsh/d6b83218f5eef55068e8b32aea82baea)

For one thing, the client TLS hello packet is sent with TLS version 1.2: so perhaps that error about `sslv3` wasn't really informative after all.

I'll note a couple of differences here

1. The working packet is sent via ipv6, whereas the failed one is ipv4 (doubtful this matters, since they both make it to the server)
2. The working TLS hello packet seems to be TLS 1.2 "all the way through." The start of the TLS sequence looks like this
      
```
 Transport Layer Security
    TLSv1.2 Record Layer: Handshake Protocol: Client Hello
        Content Type: Handshake (22)
        Version: TLS 1.2 (0x0303)
        Length: 160
        Handshake Protocol: Client Hello
            Handshake Type: Client Hello (1)
            Length: 156
            Version: TLS 1.2 (0x0303)
```

Whereas the corresponding sequence in the failed TLS packet is

```
Transport Layer Security
    TLSv1.2 Record Layer: Handshake Protocol: Client Hello
        Content Type: Handshake (22)
        Version: TLS 1.0 (0x0301)
        Length: 512
        Handshake Protocol: Client Hello
            Handshake Type: Client Hello (1)
            Length: 508
            Version: TLS 1.2 (0x0303)
```
For some reason, there's a mention of `TLS 1.0` in the middle there

3. In its response to the "good" client hello the server chooses the `TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (0xc028)` cipher suite which isn't mentioned in the failed TLS hello packet.

I guess my next step is to fiddle with the ciphers available to GRPC via the `GRPC_SSL_CIPHER_SUITES` environment variable on the client-side. Unfortunately I don't think that's going to solve the TLS "downgrade," which might also be culpable here

**Comment by anlsh** [comment]
@JamesNK I've done some digging on my end, and I have some questions about TLS configuration on aspnetcore, specifically on windows.

I've testing combinations of the C++ client and aspnetcore server being built/run on Windows & Linux, and it appears the failure is caused by the server being run on Windows. 

When the server is hosted on Linux, the C++ client (which can be run on either linux or windows with same result, let's just assume windows for the rest of the post though) sends its client hello packet over TLS 1.3, the server responds with a server hello, and everything works.

However when the server is hosted on Windows, the very same client executable will send its client hello packet over TLS 1.2 and get a TLS handshake error in response (the failure described in my original post). Forcing TLS 1.3 server-side using those options  on the page you linked also doesn't seem to work as expected: it actually causes the client to *downgrade* its client hello to TLS 1.0, whereupon the server just doesn't respond with any TLS messages at all: not even a handshake error like in the original case.

It seems to me that there's some SSL/TLS (mis)configuration on the windows side, either in Aspnetcore, whatever library it uses for SSL (is this openssl?), or on the host OS which is to blame here: and I'd like to find the solution

**Comment by anlsh** [comment]
[This page](https://devblogs.microsoft.com/premier-developer/microsoft-tls-1-3-support-reference/) note

**Comment by halter73** [comment]
> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
---> System.ComponentModel.Win32Exception (0x80090367): No common application protocol exists between the client and the server. Application protocol negotiation failed.

This looks like an ALPN error. It would be interesting to see the protocols listed in the client hello.

**Comment by anlsh** [comment]
@halter73 The ALPN protocols sent by the C++ client in its hello are `grpc-exp` and `h2`

**Comment by BrennanConroy** [comment]
This issue isn't specific to .NET GRPC, could you file an issue at https://github.com/dotnet/aspnetcore/issues if you think there is an issue with TLS in Kestrel.

A wireshark trace of the handshake and the server configuration would be helpful.

**Comment by JamesNK** [comment]
@anlsh Create an issue at the link above and reference this issue.

Whatever the cause is here, it isn't related to the Grpc.AspNetCore. The cause is lower-level in Kestrel's TLS support.

**Comment by anlsh** [comment]
Just a final update: I set a repro repo earlier this week, and was unable to reproduce the issue on other machines. Whatever the issue was, it appears to have been some sort of reconfiguration on my end
