### ISSUE TITLE
Configure emitting default values

### ISSUE THREAD

**Issue by pandabytes** [grpc/grpc-dotnet#1222]
> <em>https://github.com/aspnet/AspLabs has issues disabled so I'm posting my question here.</em>

I see that recently "emitting default values" has been set to `true` as the default value in https://github.com/grpc/grpc-dotnet/issues/1213. Is there any plan to make "emitting default values" configurable?

**Comment by BrennanConroy** [comment]
Yeah, we will be making is configurable.
