### ISSUE TITLE
Use underscore_separated_names for field names in proto files for .Net Applications?

### ISSUE THREAD

**Issue by rizi** [grpc/grpc-dotnet#1223]
Hi,
Regarding this documentation (https://developers.google.com/protocol-buffers/docs/style) the following is recommended:

**The Protobuf style guide recommends using underscore_separated_names for field names. New Protobuf messages created for .NET apps should follow the Protobuf style guidelines. .NET tooling automatically generates .NET types that use .NET naming standards. For example, a first_name Protobuf field generates a FirstName .NET property.**

@JamesNK do you think this is still the correct way to do it, or does it matter at all?
I'm asking because I've nerver seen this in any MS documentation at all.

br

**Comment by JamesNK** [comment]
https://docs.microsoft.com/en-us/aspnet/core/grpc/protobuf?view=aspnetcore-5.0#protobuf-messages

Yes

**Comment by chwarr** [comment]
@rizi: the underscore_separated_names would be in your .proto files, not in your .cs files, in case that wasn't clear.
