### ISSUE TITLE
Update DiagnosticsHandler fork from dotnet/runtime

### ISSUE THREAD

**Issue by shirhatti** [grpc/grpc-dotnet#1236]
Originally raised in https://github.com/grpc/grpc-dotnet/pull/1211

I anticipate changes to the `DiagnosticsHandler` in dotnet/runtime in the 6.0 timeframe. Filing a tracking issue to remind us to sync our changes after the 6.0 changes have stabilized.

**Comment by JamesNK** [comment]
This is done. In the .NET 6 target we use the built-in DiagnosticsHandler.
