### ISSUE TITLE
HttpHandlerFactory is creating the old .NET Core 2.0 HttpClientHandler for .NET Core 3.1

### ISSUE THREAD

**Issue by nuttytree** [grpc/grpc-dotnet#1237]
### What version of gRPC and what language are you using?
2.36.1

### What operating system (Linux, Windows,...) and version?
Windows 10.0.18363 (same issue exists on Linux)

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
3.1.13

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
Added a gRPC client using AddGrpcClient<TClient>(this IServiceCollection services, Action<IServiceProvider, GrpcClientFactoryOptions> configureClient)

### What did you expect to see?
The created clients use SocketsHttpHandler as the primary handler.

### What did you see instead?
The created clients use the old .NET Core 2.0 HttpClientHandler as the primary handler.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc-dotnet/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by JamesNK** [comment]
HttpClientHandler uses SocketsHttpHandler internally.

**Comment by nuttytree** [comment]
Unless there is something I am missing both HttpClientHandler and SocketsHttpHandler inherit from HttpMessageHandler but HttpClientHandler has no reference to SocketsHttpHandler.

**Comment by JamesNK** [comment]
It isn’t inheritance. It delegates calls to it internally.

**Comment by nuttytree** [comment]
Can you point me to where that happens?  I am just not finding it.  Sometimes tracking down MS code can be really tough.

**Comment by JamesNK** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler?view=net-5.0#httpclienthandler-in-net-core

**Comment by JamesNK** [comment]
https://github.com/dotnet/runtime/blob/997dc08f691ee0246990a21c73850a041b80b800/src/libraries/System.Net.Http/src/System/Net/Http/HttpClientHandler.cs#L15

**Comment by nuttytree** [comment]
That helps, I was looking for the actual code which must be buried deep in the library.  While I would say this bug is less relevant it still would be nice if it used the SocketsHttpHandler.  I have a NuGet that is doing some configuration of HttpClients including setting the ConnectTimeout which does not exist on the HttpClientHandler.  For now I am overriding the configuration of the primary handler when creating gRPC clients so that the ConnectTimeout can get set.
