### ISSUE TITLE
Issue: gRPC client do not dispose GrpcChannel

### ISSUE THREAD

**Issue by Banyc** [grpc/grpc-dotnet#1239]
### Is your feature request related to a problem? Please describe.
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

`HttpClient` is `IDisposable`, which enables it to go out of any scope. However, the Grpc client is not `IDisposable` but `GrpcChannel` is `IDisposable`. When I make a factory for clients, the factory has to return the `GrpcChannel` along with the clients for further releasing resources.

The post here described the same issue in detail: <https://stackoverflow.com/questions/47594441/grpc-client-do-not-dispose-channel>.

### Describe the solution you'd like
> A clear and concise description of what you want to happen.

Make client a `IDisposable` and hide the disposable `GrpcChannel` in the clients. In other words, I want GrpcClient to behave like `HttpClient` logically.

The post has also provided a workaround, but that is for the user. I hope a more decent solution can be done in this repo.

### Describe alternatives you've considered
> A clear and concise description of any alternative solutions or features you've considered.

### Additional context
> Add any other context about the feature request here.

**Comment by SartorialOffense** [comment]
I am pretty new to gRPC and this library, but since channels support many connections, I don't think this is something you would normally want to encourage. 

If you did, couldn't you just inherit from the generated client:

```csharp
 public class DisposableClient : DataAccess.DataAccessClient, IDisposable
{
    private readonly GrpcChannel _channel;

    internal DisposableClient(GrpcChannel channel)
    {
        _channel = channel ?? throw new ArgumentNullException(nameof(channel));
    }

    public void Dispose()
    {
        _channel.Dispose();
    }
}
```
And a simple factory would just be:

```csharp
    public static DisposableClient DisposableClientFactory(string address)
    {
        var channel = GrpcChannel.ForAddress($"https://{address}");
        var client = new DisposableClient(channel);
        return client;
    }
```

**Comment by JamesNK** [comment]
A channel is designed to be used by multiple clients. If a client disposed a channel then it would it break all the other clients using it.

**Comment by JamesNK** [comment]
Closing as answered.
