### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#124]
Where will documentation live? docs.microsoft.com and/or grpc.io/docs?

What documentation topics do we need?

**Comment by JamesNK** [comment]
Decisions from meeting:

* gRPC concept documentation will live on grpc.io
* Grpc.AspNetCore.* API docs will live on grpc.io - https://grpc.io/grpc/csharp/api/Grpc.Core.ServerCallContext.html
* Grpc.AspNetCore.Server scenario docs will live on docs.microsoft.com and link to grpc.io as needed

**Comment by JamesNK** [comment]
@DamianEdwards @shirhatti

For scenarios docs for docs.microsoft.com is there a list of topics that you want?

Some things worth covering:

* Basic introduction to protobuf
* Basic introduction to gRPC
* Including proto files in csproj to generate code
* Mapping services in Startup.cs
* Service lifetime and dependency injection
* Configuration - maximum message size (receive defaults to 4KB), returning detailed error message

**Comment by JunTaoLuo** [comment]
I've started writing the overview for grpc-dotnet on docs.asp.net.

**Comment by csteegz** [comment]
Logging examples would be nice - console, application insights, open tracing. 
An doc about hosting both REST MVC and GRPC in the same process would be useful - info around routing, sharing DI containers, etc.

**Comment by JamesNK** [comment]
Logging would be standard ASP.NET Core logging, i.e. inject an ILoggerFactory or ILogger into a service. We could show that as an example for dependency injection.

**Comment by JunTaoLuo** [comment]
Potential tutorials:
- Add duplex streaming
- Add logging and resolve a stateful Singleton service from DI

**Comment by daltonks** [comment]
Maybe another for documentation:
Secure requests/responses. Does it just use the HTTPS certificates like a typical C# API would?

**Comment by JunTaoLuo** [comment]
On the server side, HTTPS is configured on the Kestrel. There's no message security and nothing to configure that's gRPC specific.

**Comment by daltonks** [comment]
Thanks for the information! Certificates are my biggest pain-points using normal GRPC.
I'll be trying out v0.1.19-pre1 because of this.

**Comment by JunTaoLuo** [comment]
Note, we should also mention that the min request body data rate needs to be disabled for client streaming and duplex streaming calls. Link to https://github.com/aspnet/AspNetCore/issues/7635 for future improvement in this area.
