### ISSUE TITLE
Can I use gRPC for .NET inside Blazor WebAssembly?

### ISSUE THREAD

**Issue by JoeMarkov** [grpc/grpc-dotnet#1244]
Can I run a Blazor WebAssembly application in the browser and make real gRPC requests to a gRPC server?

I am aware that Browsers and JavaScript are limited to gRPC-Web, 

but does Blazor with its own HttpClient also constrained to the same limit? or can a Blazor app in the browser do real full gRPC? 

If not possible to get full gRPC with streaming, perhaps its possible to do unary calls from Blazor?

**Comment by JamesNK** [comment]
https://docs.microsoft.com/en-us/aspnet/core/grpc/browser?view=aspnetcore-5.0

There are the same streaming limitations.

**Comment by JoeMarkov** [comment]
thanks.

if you only need unary (no streaming) there is no luck running gRPC in the browser?

**Comment by JamesNK** [comment]
Is this not clear?

>Traditional gRPC over HTTP/2 supports streaming in all directions. gRPC-Web offers limited support for streaming:
> * gRPC-Web browser clients don't support calling client streaming and bidirectional streaming methods.
> * ASP.NET Core gRPC services hosted on Azure App Service and IIS don't support bidirectional streaming.
>
>When using gRPC-Web, we only recommend the use of unary methods and server streaming methods.

https://docs.microsoft.com/en-us/aspnet/core/grpc/browser?view=aspnetcore-5.0#grpc-web-and-streaming

**Comment by JoeMarkov** [comment]
Not really :-)

It talks about streaming and I do understand it is not supported due to the lack of support of trailers and other stuff. That's fine.
For unary requests, the text you quote talks about gRPC-Web, not the original gRPC.

I have never used gRPC-Web and I just assume its a subset of gRPC to work in the browser and I am not familiar with how the interoperable they are for unary requests.

so, the distilled thing that I lack in the documentation and that I want to have confirmation on, is if I can do "real" gRPC unary requests from Blazor against an existing gRPC service?

Is it so that unary requests are the same in gRPC and gRPC-Web? Perhaps that is what I want to have confirmed? or can a  gRPC-Web client do a real unary request call against a real gRPC service?

on is what about unary requests. can I still do that against a gRPC service? 

Or is it so that gRPC and gRPC-Web are the same/compatible for unary requests?

ps, enjoyed your recent gRPC perf talk :-)

**Comment by JamesNK** [comment]
> is if I can do "real" gRPC unary requests from Blazor against an existing gRPC service?

No. You're in a browser. You must use gRPC-Web.

https://docs.microsoft.com/en-us/aspnet/core/grpc/supported-platforms?view=aspnetcore-5.0#net-grpc-client-requirements

**Comment by JoeMarkov** [comment]
ok! thanks for clarification
