### ISSUE TITLE
Grpc-web hosting in iis

### ISSUE THREAD

**Issue by mukthiarahamad** [grpc/grpc-dotnet#1245]
I have created a sample Grpc application with a basic ado .net query and I want to host the same in the IIS. The application works fine when I consume it from a net client but after hosting , I am getting an error in the client application when I try to consume the grpc end point. (https://localhost/test)

'Status(StatusCode="Unimplemented", Detail="Bad gRPC response. HTTP status code: 404")'
I have created entity a grpc app with ef core and a wcf service with EF6. when I compare the response times, the wcf service seeems to respond quicker than grpc app. Am I missing anything?

**Comment by JamesNK** [comment]
Is the IIS website hosted under a subdirectory? If so then some extra configuration is required in the client.

See https://github.com/grpc/grpc-dotnet/blob/3518cd757002f5a685f34d277e876850b7637ecc/test/Grpc.Net.Client.Tests/SubdirectoryHandlerTests.cs

**Comment by JunTaoLuo** [comment]
Looks like this question has been answered.
