### ISSUE TITLE
Grpc.Net.ClientFactory .NETStandard2.0 compatibility

### ISSUE THREAD

**Issue by Dimigergo** [grpc/grpc-dotnet#1247]
### Is your feature request related to a problem? Please describe.
I hava an UWP project which uses Grpc.Net.Client.Web 2.36.0. I see, that this version supports .NETStandard2.0, but the  
Grpc.Net.ClientFactory only supports .NETStandard2.1 and net5.0. 
The UWP doesn't support 2.1 or .net5 yet.

My problem is I would like to use interceptors for the client side, according to this code:
```
services
    .AddGrpcClient<Greeter.GreeterClient>(o =>
    {
        o.Address = new Uri("https://localhost:5001");
    })
    .AddInterceptor(() => new SomeInterceptor())   
```

### Describe the solution you'd like
Grpc.Net.ClientFactory .NETStandard2.0 compatibility

### Describe alternatives you've considered
Closely enough to me that add multiple interceptor with somewhere on these lines:
```
CallCredentials callCredentials = CallCredentials.FromInterceptor(CHttpClientService.AsyncAuthInterceptor);
    return GrpcChannel.ForAddress(Settings.CSettings.ServerAddress, new GrpcChannelOptions
    {
        HttpHandler = new GrpcWebHandler(new CHttpClientService().PrepareHttpMessageHandler()),
        Credentials = ChannelCredentials.Create(new SslCredentials(), callCredentials),
    });
```
AsyncAuthInterceptor is not good for me, because it is called only before the function call.

**Comment by HppZ** [comment]
need .NETStandard2.0 support toooo

**Comment by JamesNK** [comment]
Adding netstandard2.0 to the client factory will be in the next release.

You can add interceptors like this to a channel:
```cs
var channel = GrpcChannel.ForAddress("https://blah");
var invoker = channel.Intercept(new SomeInterceptor());

var client = Greeter.GreeterClient(invoker);
```
The extension method is in `Grpc.Core.Interceptors.ChannelExtensions`.

**Comment by Dimigergo** [comment]
Thank you for your help!
Waiting for the release.

**Comment by HppZ** [comment]
> gRPC requires extra configuration on .NET implementations that don't support gRPC over HTTP/2. An HTTP provider must be specified using GrpcChannelOptions.HttpHandler.The configured HTTP provider must either support HTTP/2 or be configured to use gRPC-Web. See https://aka.ms/pzkMXDs for details.

so grpc.net.client does not support UWP?

**Comment by Dimigergo** [comment]
Grpc.Net.Client 2.36.0 is compatible with .netstandard2.0 so you can use it in UWP project. I only use grpc-web, because we have this project in Uno Platform, and compile it to webassembly, where we can't use grpc, only grpc-web.

**Comment by HppZ** [comment]
I have to set GrpcWebHandler as grpc httphandler in UWP app. [here](https://docs.microsoft.com/en-us/aspnet/core/grpc/netstandard?view=aspnetcore-5.0)

**Comment by Dimigergo** [comment]
Ohh, I see! Microsoft will plan to support .netstandard2.1 and .net 5 for UWP, but don't know when. 21H1 os 21H2. We also wait for it.

**Comment by HppZ** [comment]
hope it won't be long. so sad.
