### ISSUE TITLE
ApplicationInsight InvalidCastException ActivityStartData [Grpc.Net.ClientFactory -> System.Net.Http] after upgrading to package 2.36

### ISSUE THREAD

**Issue by 951p** [grpc/grpc-dotnet#1250]
### What version of gRPC and what language are you using?
.Net 5.0
Nuget: Grpc.AspNetCore Version="2.36.0"   ----   2.35 was working.

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
Runtime:.Net 5.0.1
SDK: 5.0.101

### What did you do?
Add applicationInsight for the requests telemetry on my application that is communicating both with regular REST/HTTP and GRPC
ApplicationInsight nuget: Microsoft.ApplicationInsights.AspNetCore Version="2.17.0" -- Latest

### What did you expect to see?
No error from applicationInsight due to invalid casting of the ActivityStartData.

### What did you see instead?
```
AI (Internal): [Microsoft-ApplicationInsights-Extensibility-DependencyCollector] HttpCoreDiagnosticSourceListener OnNext failed to call event handler. Error details 'System.InvalidCastException: [A]ActivityStartData cannot be cast to [B]ActivityStartData. Type A originates from 'Grpc.Net.ClientFactory, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad' in the context 'Default' at location '/app/Grpc.Net.ClientFactory.dll'.
Type B originates from 'System.Net.Http, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' in the context 'Default' at location '/usr/share/dotnet/shared/Microsoft.NETCore.App/5.0.4/System.Net.Http.dll'.
   at Microsoft.ApplicationInsights.Common.PropertyFetcher.PropertyFetch.TypedFetchProperty`2.Fetch(Object obj)
   at Microsoft.ApplicationInsights.DependencyCollector.Implementation.HttpCoreDiagnosticSourceListener.OnNext(KeyValuePair`2 evnt)'
```

### Anything else we should know about your project / environment?

ApplicationInsight version: 2.17 (Latest)
Issue only occurs with the new version of the package (2.36)   -- 2.35 works fine.

The issue seems to be introduced by this PR #1211

**Comment by JamesNK** [comment]
Looks like it is a problem in ApplicationInsights - https://github.com/microsoft/ApplicationInsights-dotnet/issues/2194

**Comment by JamesNK** [comment]
This is fixed in recent versions of App Insights - https://github.com/microsoft/ApplicationInsights-dotnet/pull/2197
