### ISSUE TITLE
Grpc.Net.Client channel target incorrect if path defined

### ISSUE THREAD

**Issue by darkTomz** [grpc/grpc-dotnet#1254]
### What version of gRPC and what language are you using?
C#

### What operating system (Linux, Windows,...) and version?
Windows10

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
NETCore.App 2.1.25 

### What did you do?
I was making NUnit tests. Server side was dedicated (dockerized).
Service channel link was as example: https://app1-example.com/Calculate.Api
Code example:
```
var channel = GrpcChannel.ForAddress("https://app1-example.com/Calculate.Api",new GrpcChannelOptions
                {
                HttpHandler = new WinHttpHandler()
                });
var client = new UserProfile.UserProfileClient(channel);
```

### What did you expect to see?
Positive response from server (api)

### What did you see instead?
I got error:  Grpc.Core.RpcException : Status(StatusCode="Unimplemented", Detail="")
While I was debugging I noticed that channel target is: https://app1-example.com

!!!/Calculate.Api missing

**Comment by chwarr** [comment]
Looks like issue [#880 Calling a service in a sub-directory?](https://github.com/grpc/grpc-dotnet/issues/880), may be helpful here. I'm not entirely sure, though...

**Comment by JamesNK** [comment]
Specifically, this comment shows how to set a path: https://github.com/grpc/grpc-dotnet/issues/880#issuecomment-618794159
