### ISSUE TITLE
Error building examples on linux aarch64 with 2.37.0

### ISSUE THREAD

**Issue by peterwishart** [grpc/grpc-dotnet#1273]
### What version of gRPC and what language are you using?
2.37.0 / csharp

### What operating system (Linux, Windows,...) and version?
Ubuntu 20.04.2 LTS aarch64 / Raspberry Pi4

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
5.0.202

### What did you do?
 - Clone `grpc/grpc-dotnet` and cd to it.
 - Run `source activate.sh`
 - Edit `build/dependencies.props` to set example projects to use Grpc.AspNetCore 2.37.0
 - Cd to `examples/Greeter/Server`
 - `dotnet build .`

### What did you expect to see?
Successful build (2.36 and below would fail as they lacked arm native tools)

### What did you see instead?
Build fails with: `grpc.tools/2.37.0/tools/linux_arm64/protoc" exited with code 139.` (process stopped due to SIGSEGV?)
Debug log shows:
```
      Task "ProtoCompile"
         /home/username/.nuget/packages/grpc.tools/2.37.0/tools/linux_arm64/protoc --csharp_out=obj/Debug/net5.0 --plugin=protoc-gen-grpc=/home/username/.nuget/packages/grpc.tools/2.37.0/tools/linux_arm64/grpc_csharp_plugin --grpc_out=obj/Debug/net5.0 --grpc_opt=no_client --proto_path=/home/username/.nuget/packages/grpc.tools/2.37.0/build/native/include --proto_path=../Proto --dependency_out=obj/Debug/net5.0/830b0b44ffda90ec_greet.protodep --error_format=msvs ../Proto/greet.proto
1:7>/home/username/.nuget/packages/grpc.tools/2.37.0/build/_protobuf/Google.Protobuf.Tools.targets(280,5): error MSB6006: "/home/username/.nuget/packages/grpc.tools/2.37.0/tools/linux_arm64/protoc" exited with code 139. [/home/username/grpc-dotnet/examples/Greeter/Server/Server.csproj]
       Done executing task "ProtoCompile" -- FAILED.
```
Running `protoc` using the logged commandline manually works - after this is done, `dotnet build` works (until a clean is run or the `proto` sources change).
So I guess its something particular to this SBC environment and the environment passed to `protoc` during the build?

**Comment by peterwishart** [comment]
I built `protoc` (no shared libs, from latest github source) and replaced the `grpc.tools/2.37.0` with it, and the problem no longer occurs. 
So its related to how the `linux_arm64` binary shipped with `Grpc.Tools` is built. 
I've no idea why the problem would only manifest when `dotnet` is calling the tool though.

**Comment by JamesNK** [comment]
Hi

Could you refile this issue in https://github.com/grpc/grpc? Grpc.Tools is built there and that is where its issues go.

**Comment by peterwishart** [comment]
Closing - refiled [here](https://github.com/grpc/grpc/issues/26032)
