### ISSUE TITLE
Enable base-namespace in projects protobuf item group

### ISSUE THREAD

**Issue by maxreb** [grpc/grpc-dotnet#1274]
### Is your feature request related to a problem? Please describe.
When I use proto files from other Web Apis they are often have package names like "api" or "as" or something. As the `Grpc.Tools` automatically creates the namespaces, the calls are like "As.Get()" or "Api.Get()" which is not quite nice and understandable. I know that I can add `option csharp_namespace = "My.Custom.Namespace";` to all of the proto files, but as I want to keep them updated automatically (and there are a lot of proto files on some webapis) I don't want to change them.

### Describe the solution you'd like
protoc has this option: `--csharp_opt=base_namespace=My.Costom.Namespace`. I would like to see this implemented in the Protobuf tag like this:

    <ItemGroup>
                <Protobuf
                   Include="protobuf\**\*.proto"
                   GrpcServices="Client"
                   BaseNamespace="My.Custom.Namespace"/>
    </ItemGroup>

**Comment by JamesNK** [comment]
Grpc.Tools issues should be created in this repo: https://github.com/grpc/grpc

Please move this issue.

**Comment by maxreb** [comment]
Ok, done.
https://github.com/grpc/grpc/issues/26070
