### ISSUE TITLE
gRPC Web full-body compression

### ISSUE THREAD

**Issue by ed10vi** [grpc/grpc-dotnet#1276]
How can I enable grpc-web full body compression in an ASP.NET server as described [here](https://github.com/grpc/grpc-web/blob/master/doc/browser-features.md#compression)?

**Comment by JamesNK** [comment]
[Response compression in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/response-compression?view=aspnetcore-5.0)

**Comment by ed10vi** [comment]
I've already done that:

    services.AddResponseCompression(options =>
    {
        options.EnableForHttps = true;
        options.MimeTypes = ResponseCompressionDefaults.MimeTypes.Concat(new[]
        {
            "image/svg+xml",
            "application/grpc-web",
            "application/grpc-web+proto",
            "application/grpc-web+json",
            "application/grpc-web+thrift",
            "application/grpc-web-text",
            "application/grpc-web-text+proto",
            "application/grpc-web-text+thrift"
        });
    });

And:

    app.UseResponseCompression();

It's working for controllers but not for gRPC services.

**Comment by JamesNK** [comment]
Are you using the gRPC web JavaScript client or .NET Blazor client?
Can you attach a Chrome network trace? Search for .har file if you're not sure how to.

**Comment by ed10vi** [comment]
I'm using Blazor WASM
Here is the network trace: [localhost_Archive [21-04-28 12-59-33].har](https://github.com/grpc/grpc-dotnet/files/6391312/localhost_Archive.21-04-28.12-59-33.txt)

**Comment by JamesNK** [comment]
This works:

```cs
using System.Linq;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.ResponseCompression;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Server.Services;

namespace Server
{
    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddGrpc();
            services.AddResponseCompression(opts =>
            {
                opts.EnableForHttps = true;
                opts.MimeTypes = ResponseCompressionDefaults.MimeTypes.Concat(
                    new[] { "application/octet-stream", "application/grpc" });
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseResponseCompression();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseWebAssemblyDebugging();
            }

            app.UseStaticFiles();
            app.UseBlazorFrameworkFiles();

            app.UseRouting();

            app.UseResponseCompression();

            app.UseGrpcWeb();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapGrpcService<WeatherService>().EnableGrpcWeb();
                endpoints.MapGrpcService<CounterService>().EnableGrpcWeb();
                endpoints.MapFallbackToFile("index.html");
            });
        }
    }
}
```

It only worked if the content-type was `application/grpc` and the compression middleware was before `UseGrpcWeb()`.

Basically, gRPC web rewrites the request, and I guess something about the response compression middleware looks at the internal content-type, and not what gets returned to the browser.
