### ISSUE TITLE
Migration from gRPC.Core

### ISSUE THREAD

**Issue by MD-V** [grpc/grpc-dotnet#1280]
As stated in https://grpc.io/blog/grpc-csharp-future/ gRPC.Core will be deprecated in 2022. 

Currently we use gRPC.Core Server in many of our applications. None of those applications currently use ASP.NET Core. 

gRPC.Core servers can be started anywhere in the program. As far as I understand gRPC-dotnet server will only work if we completly restructure all of our server processes (where some of them even are WPF applications which run minimized) to use ASP.NET Core.

Is there any way of using gRPC-dotnet server without restructuring the complete application to use ASP.Net Core?
Will there be any development efforts to simplify the transition? 

The migration docs don't really help https://docs.microsoft.com/en-us/aspnet/core/grpc/migration?view=aspnetcore-5.0.

Thank you very much.

**Comment by JamesNK** [comment]
An ASP.NET Core server can be started anywhere in a program as well. It is just by convention that most use Program.cs.

The logic to create, build, and run a host that is below could happen wherever you like:
https://github.com/grpc/grpc-dotnet/blob/4c410dcc3942e8705602d63f03f8b6b8b9df8e72/examples/Greeter/Server/Program.cs#L26-L36

**Comment by MD-V** [comment]
Ah I see, this was a misunderstanding on my part, thanks for clarification.
