### ISSUE TITLE
How do ByteString's work?

### ISSUE THREAD

**Issue by johnsimons** [grpc/grpc-dotnet#1281]
I have a few questions regarding the use of the `ByteString` type.

1. If I need to upload/download large files (1-5GB) is using `ByteString` the right choice?

1. Do `ByteString` "stream" the data, in other words, if the client is doing something like `ByteString.FromStreamAsync(stream)` when the Server is processing this data and accesses the "ByteString" eg `fileStream.WriteAsync(request.Data.Memory)` is the data streaming, or is the full stream already on the Server? (I hope this makes sense).

**Comment by JamesNK** [comment]
Docs on performance best practices with ByteString: https://docs.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-5.0#binary-payloads

ByteString itself doesn't stream, but you can split content up into multiple ByteStrings and stream those over gRPC.
