### ISSUE TITLE
Should ByteString.Length  be a long

### ISSUE THREAD

**Issue by johnsimons** [grpc/grpc-dotnet#1282]
### What version of gRPC and what language are you using?
C#
2.37.0

### What operating system (Linux, Windows,...) and version?
Not relevant

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
5.0.5

### What did you do?
![image](https://user-images.githubusercontent.com/122651/117232580-c6311480-ae64-11eb-98de-b7dd7e91a49c.png)

### What did you expect to see?
I expected `ByteString.Length` to be a `long`, same as `Stream.Length`.

**Comment by JamesNK** [comment]
It shouldn't. ByteString wraps a span, and the length on span is an integer.

https://docs.microsoft.com/en-us/dotnet/api/system.span-1.length?view=net-5.0

**Comment by JamesNK** [comment]
Also, ByteString isn't in this repo. Protobuf issues at https://github.com/protocolbuffers/protobuf please.

**Comment by johnsimons** [comment]
So but does this mean a stream larger than `2147483647` would overflow?

**Comment by JamesNK** [comment]
Step 1 is asking yourself whether it is a good idea to allocate an array that is bigger than 2 gigabytes, because that is what you are wanting to do.

**Comment by johnsimons** [comment]
yes, I'm planning to split it, thanks for the advice

**Comment by davidfowl** [comment]
Why does ByteString even support a Stream @jtattermusch @jonskeet

**Comment by jtattermusch** [comment]
> Why does ByteString even support a Stream @jtattermusch?

I think it's for historical reasons: Back when `ByteString.FromStreamAsync()` was introduced, we didn't have a way to efficiently create a ByteString from a stream efficiently without excessive copying (that was way before we had Span and the buffer APIs).
