### ISSUE TITLE
Request: support fast creation of server objects

### ISSUE THREAD

**Issue by Banyc** [grpc/grpc-dotnet#1285]
### Is your feature request related to a problem? Please describe.

`grpc-dotnet` does not have a fast creation of server objects (at least in the tutorials). I don't want to rely on the aspnet core infrastructure when it comes to a class library.

### Describe the solution you'd like

Support something like the following:

```csharp
Grpc.Core.Server rpcServer = new()
{
    Services = { RpcMapReduceService.BindService(controller) },
    Ports = { new ServerPort(_settings.IpAddress, _settings.Port, ServerCredentials.Insecure) }
};
```

### Describe alternatives you've considered

Currently no.

### Additional context
Add any other context about the feature request here.

Due to the fact that `Grpc.Core` is about to be deprecated, I still want the neat API that `Grpc.Core` provides. Please consider this request because it is not appropriate for a class library to depend on aspnet core.

**Comment by BrennanConroy** [comment]
>it is not appropriate for a class library to depend on aspnet core

Sorry, but that isn't possible. Grpc.Core brings in a whole HTTP2 stack, whereas this Grpc library is built on top of the ASP.NET Core HTTP2 stack, it doesn't bundle its own.

Are you concerned that this library requires ASP.NET Core, or that you have to write ConfigureServices etc. when using Grpc server?
