### ISSUE TITLE
How to reduce the size of libgrpc_csharp_ext so file

### ISSUE THREAD

**Issue by chaoscn** [grpc/grpc-dotnet#1288]
Hi,

We are using Grpc.AspNetCore version 2.37.0. 
For linux-x64 build, the so files been generated are very large because it contains debug info.
libgrpc_csharp_ext.x64.so - 88,163KB
libgrpc_csharp_ext.x86.so - 74,160KB

Due to internal requirement we need to use "PublishSingleFile=true" option to combine all dlls and files into one single file and those two large so files are problematic for us.

So how to:
1. Reduce the size of so file so that it no longer contain debug symbols during "dotnet publish" process
2. Automatically remove x86 version as our environment are all x64 based.

Thanks,
Chenhao

**Comment by davidfowl** [comment]
These files should only be needed at development time. I wonder if we need some more msbuild goop here to declare that these assets should not be included at publish time

**Comment by JamesNK** [comment]
Grpc.AspNetCore is a metapackage is includes Grpc.Tools by default. You can reference `Grpc.AspNetCore.Server`, `Google.Protobuf` package directly. And then reference `Grpc.Tools` as a tooling packing so it isn't included.

**Comment by JamesNK** [comment]
You must be referencing the `Grpc.Core` package. It's not needed. Remove it.
