### ISSUE TITLE
Connection refused SocketException: Connection refused

### ISSUE THREAD

**Issue by ComptonAlvaro** [grpc/grpc-dotnet#1289]
I am trying to use gRPC in a Xamarin application. I have my service and the common library to share between the client and the service.

For test in the same computer, I have a WPF application, that use the client library of gRPC and it can receive the response from the service, but when I run the xamarin in a mobile (not emulator) I get the error that the connection is refused.

this is my service configuration:

```
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapMagicOnionService();

                endpoints.MapGet("/", async context =>
                {
                    await context.Response.WriteAsync("Communication with gRPC endpoints must be made through a gRPC client. To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909");
                });
            });
        }
```

This is the main of the service:

```
        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder
                        .UseKestrel(options =>
                        {
                            // WORKAROUND: Accept HTTP/2 only to allow insecure HTTP/2 connections during development.
                            options.ConfigureEndpointDefaults(endpointOptions =>
                            {
                                endpointOptions.Protocols = HttpProtocols.Http1AndHttp2;
                            });
                        })
                        .UseStartup<Startup>();
                });
```

This is the client (where the IP is the IP of the ethernet connection in my computer, I have connected through ethernet):

`var miChannel = GrpcChannel.ForAddress("http://192.168.1.250:5000");`

I have disabled the firewall, because if not, I get an error of timeout, so it means that the xamarin application can find the service. If I disbaled the firewall, then I get the error that the connection is refused.

How could solve this exception?

Thanks.

**Comment by BrennanConroy** [comment]
Couple things, you're using http not https, and you have Http1AndHttp2 instead of just Http2.

This is a similar issue with steps to resolve it https://docs.microsoft.com/aspnet/core/grpc/troubleshoot?view=aspnetcore-5.0#unable-to-start-aspnet-core-grpc-app-on-macos

**Comment by ComptonAlvaro** [comment]
I could solve the problem with this configuration:

```
                    webBuilder.ConfigureKestrel(options =>
                    {
                        options.Listen(IPAddress.Any, 5001, listenOptions =>
                        {
                            listenOptions.Protocols = HttpProtocols.Http2;
                            //listenOptions.UseHttps("<path to .pfx file>", "<certificate password>");
                        });
                    });
                    webBuilder.UseStartup<Startup>();
```

In this case, it is listening to all ports and it creates a HTTP connection, so I can connect without needed of a certificate.

**Comment by ComptonAlvaro** [comment]
Thanks for the response. I could solve this problem, so if you considerate, this issue could be closed.


Thanks.
