### ISSUE TITLE
Build errors due to proto file errors don't include details of error in VS error list

### ISSUE THREAD

**Issue by DamianEdwards** [grpc/grpc-dotnet#129]
It would be nice if we could somehow include more detail in the error message report in the Error List pane in VS when protoc fails due to a .proto file error of some sort. The error detail is included in the build output, but there's no navigation gesture from the Error List error to the build output so the user has to know to do that manually. Indeed, double-clicking on the error in the Error List opens the `Google.Protobuf.Tools.targets` file which isn't helpful at all.

![image](https://user-images.githubusercontent.com/249088/53440333-22609a00-39b9-11e9-835d-4d1782b5b80b.png)

**Comment by jtattermusch** [comment]
CC @kkm000
