### ISSUE TITLE
Will grpc.net.client support .net framework 4.5?

### ISSUE THREAD

**Issue by WeiWang120** [grpc/grpc-dotnet#1290]
I'm trying to use grpc.net.client in my .net framework 4.5 project, but it seems .net45 is not supported. Even though I can work with grpc.core, but as stated in the documentation, grpc.core will be deprecated. Any plans to support .net45 in the future?

**Comment by JamesNK** [comment]
https://docs.microsoft.com/en-us/aspnet/core/grpc/netstandard?view=aspnetcore-5.0#net-framework

**Comment by WeiWang120** [comment]
> https://docs.microsoft.com/en-us/aspnet/core/grpc/netstandard?view=aspnetcore-5.0#net-framework

The problem is I couldn't even build my project, when I build it, I get this error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Grpc.Net.Client 2.37.0 is not compatible with net45 (.NETFramework,Version=v4.5). Package Grpc.Net.Client 2.37.0 supports:
  - net5.0 (.NETCoreApp,Version=v5.0)
  - netstandard2.0 (.NETStandard,Version=v2.0)
  - netstandard2.1 (.NETStandard,Version=v2.1)

**Comment by WeiWang120** [comment]
> You will need .NET Framework 4.6.1 or later.

Yes, I'm aware of that. My question is will grpc-dotnet support 4.5 in the future? If not, should I go with grpc.core for .net framework under 4.6.1 even thought grpc.core is going to be deprecated in the future?

**Comment by JamesNK** [comment]
> grpc-dotnet support 4.5 in the future

Unlikely. Support for .NET Framework 4.5 ended in 2016. Apps shouldn't be using it anymore.

**Comment by JamesNK** [comment]
Closing as answered.
