### ISSUE TITLE
To use a certificate is it not needed to have a service certificate?

### ISSUE THREAD

**Issue by ComptonAlvaro** [grpc/grpc-dotnet#1292]
I wanted to use a certificate for the communication, and I was reading the example that there is here: [https://github.com/grpc/grpc-dotnet/tree/master/examples/Certifier](url)

But in this example I only see the client certificate, not the service certificate. Isn't it needed a service certificate?

Because I have read another documentation, in Microsoft docs, [https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/channel-credentials](url) in which it seems it is needed:

```
public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
        .ConfigureWebHostDefaults(webBuilder =>
        {
            var serverCert = ObtainServerCertificate();
            webBuilder.UseStartup<Startup>()
                .ConfigureKestrel(kestrelServerOptions => {
                    kestrelServerOptions.ConfigureHttpsDefaults(opt =>
                    {
                        opt.ClientCertificateMode = ClientCertificateMode.RequireCertificate;

                        // Verify that client certificate was issued by same CA as server certificate
                        opt.ClientCertificateValidation = (certificate, chain, errors) =>
                            certificate.Issuer == serverCert.Issuer;
                    });
                });
        });
```

So my question is, what I need and how to use it to can use certificates in gRPC dotnet?

Thanks.

**Comment by BrennanConroy** [comment]
You need a server certificate before you can specify a client certificate.

**Comment by JamesNK** [comment]
Closing as answered.
