### ISSUE TITLE
Transition from localhost to publish

### ISSUE THREAD

**Issue by DeanCaspySE** [grpc/grpc-dotnet#1295]
Hi, 
I run your "Aggregator" example, everything working great when the address is "https://localhost:5001".
When I publish to app service using Visual Studio, after changing the address to the Hosting site, I get an exception when the StatusCode is "Cancelled".

Message = "Status(StatusCode=\"Cancelled\", Detail=\"Call canceled by the client.\")"

Under Azure portal ->App Service -> configuration, I changed the HTTP version to 2.0.
My purpose is to run an ASP.NET gRPC service on Azure app service and communicate with a simple C# console application client, is it possible?

**Comment by BrennanConroy** [comment]
Grpc doesn't work on App Service, you can only use Grpc-Web currently.

https://github.com/dotnet/aspnetcore/issues/9020

**Comment by JamesNK** [comment]
Closing as answered.
