### ISSUE TITLE
protoc from Grpc.Tools 2.37 fails on aarch64 Ubuntu

### ISSUE THREAD

**Issue by tiolan** [grpc/grpc-dotnet#1301]
I was testing the new aarch64 support of Grpc.Tools.
Other than https://github.com/grpc/grpc/issues/18338, this here is about Ubuntu, not Alpine.
Not sure if I should have opened this ticket in Grpc.Core, I can move it if requested.

### What version of gRPC and what language are you using?
C# ASP.NET 3.1

```
<PackageReference Include="Google.Protobuf" Version="3.17" />
<PackageReference Include="Grpc.Net.Client" Version="2.37" />
<PackageReference Include="Grpc.Net.ClientFactory" Version="2.37" />
<PackageReference Include="Grpc.Tools" Version="2.37">
```

### What operating system (Linux, Windows,...) and version?
Raspberry PI
Ubuntu 20.04 on aarch64 (not Raspbian)
Linux 5.4.0-1033-raspi #36-Ubuntu SMP PREEMPT Thu Mar 25 19:00:51 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET Core SDK (reflecting any global.json):
 Version:   3.1.405
 Commit:    65f9d75b1c

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-arm64
 Base Path:   /home/ubuntu/dotnet/sdk/3.1.405/

Host (useful for support):
  Version: 3.1.11
  Commit:  f5eceb8105

.NET Core SDKs installed:
  3.1.405 [/home/ubuntu/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.11 [/home/ubuntu/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.11 [/home/ubuntu/dotnet/shared/Microsoft.NETCore.App]

### What did you do?
I implemented a grpc client in C#, that generates the code using 
```
<Protobuf Include="ProtoFiles\MyProtoMessages.proto" />
<Protobuf Include="ProtoFiles\MyProtoServices.proto" ProtoRoot="ProtoFiles" GrpcServices="client" />
```

### What did you expect to see?
protoc should be able the generate the code.

### What did you see instead?
/home/ubuntu/.nuget/packages/grpc.tools/2.37.0/build/_protobuf/Google.Protobuf.Tools.targets(280,5): error MSB6006: "/home/ubuntu/.nuget/packages/grpc.tools/2.37.0/tools/linux_arm64/protoc" exited with code 139.

Unfortunately nothing more.
I need to find out how to obtain more information.

### Anything else we should know about your project / environment?
When building the exact same project on my computer (amd64) everything works as expected.
Same issue happens with version 2.37.1 and also 2.38.0-pre1

**Comment by tiolan** [comment]
I have now updated to dotnet 5 and also used a grpc project delivered with dotnet to make sure it is not caused by my project.

Steps:
`dotnet new grpc`
modify .csproj to use package
`<PackageReference Include="Grpc.AspNetCore" Version="2.37.0" />`
`dotnet build -v d`

gives me

```
       Using "ProtoCompile" task from assembly "/home/ubuntu/.nuget/packages/grpc.tools/2.37.0/build/_protobuf/netstandard1.3/Protobuf.MSBuild.dll".
       Task "ProtoCompile"
         /home/ubuntu/.nuget/packages/grpc.tools/2.37.0/tools/linux_arm64/protoc --csharp_out=obj/Debug/net5.0/Protos --plugin=protoc-gen-grpc=/home/ubuntu/.nuget/packages/grpc.tools/2.37.0/tools/linux_arm64/grpc_csharp_plugin --grpc_out=obj/Debug/net5.0/Protos --grpc_opt=no_client --proto_path=/home/ubuntu/.nuget/packages/grpc.tools/2.37.0/build/native/include --proto_path=. --dependency_out=obj/Debug/net5.0/1255d1a520d30ea4_greet.protodep --error_format=msvs Protos/greet.proto
   1:7>/home/ubuntu/.nuget/packages/grpc.tools/2.37.0/build/_protobuf/Google.Protobuf.Tools.targets(280,5): error MSB6006: "/home/ubuntu/.nuget/packages/grpc.tools/2.37.0/tools/linux_arm64/protoc" exited with code 139. [/src/tmp/tmp.csproj]
```

the directory `obj/Debug/net5.0/Protos/` then actually is empty.

When invoking
`/home/ubuntu/.nuget/packages/grpc.tools/2.37.0/tools/linux_arm64/protoc --csharp_out=obj/Debug/net5.0/Protos --plugin=protoc-gen-grpc=/home/ubuntu/.nuget/packages/grpc.tools/2.37.0/tools/linux_arm64/grpc_csharp_plugin --grpc_out=obj/Debug/net5.0/Protos --grpc_opt=no_client --proto_path=/home/ubuntu/.nuget/packages/grpc.tools/2.37.0/build/native/include --proto_path=. --dependency_out=obj/Debug/net5.0/1255d1a520d30ea4_greet.protodep --error_format=msvs Protos/greet.proto`

manually, it actually produces the source in  `obj/Debug/net5.0/Protos/` 

```
/src/tmp$ ls  obj/Debug/net5.0/Protos/
Greet.cs  GreetGrpc.cs
```

After this manual step, I can actually `dotnet run` the app.

@jtattermusch as you did the arm64 support.

**Comment by tiolan** [comment]
seems to be a dup of https://github.com/grpc/grpc/issues/26032 that I just realized

**Comment by JamesNK** [comment]
Grpc.Tools issues should be at grpc/grpc.

Closing as duplicate.
