### ISSUE TITLE
gRPC hosted using ASP.NET Core slow performance

### ISSUE THREAD

**Issue by fbridger** [grpc/grpc-dotnet#1302]
### What version of gRPC and what language are you using?
"Grpc.AspNetCore" Version="2.28.0"
Language = C#

### What operating system (Linux, Windows,...) and version?
Windows 10 Enterprise Version 1909

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  3.1.407 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

### What did you do?
Our team implemented Grpc using the protobuf-net package in our backend services to avoid having to mantain .proto files.

We are using a Rest Web API that communicates with our Grpc Services.

During the Load Tests we performed using https://locust.io/ we encountered unpredictable and very high response times when being executed by concurrent users (simulated by locust)

### What did you expect to see?
Performance similar to Grpc.Core

### What did you see instead?
Detailed performance information and samples used can be view here:
https://github.com/fbridger/GrpcPerformance

**Comment by JamesNK** [comment]
We made significant performance improvements in gRPC performance in .NET 5. If performance is important to you then I recommend using it over Grpc.AspNetCore on 3.1.

Also, update your Grpc.AspNetCore package version. 2.28.0 is relatively old. Newer versions contain performance improvements.

I think you should rerun your tests on .NET 5 and see whether there are still performance issues. (don't worry about re-testing Grpc.Core on .NET 5. It will be largely unchanged)
