### ISSUE TITLE
How to install latest version of Dependencies with Grpc.AspNetCore

### ISSUE THREAD

**Issue by ArminShoeibi** [grpc/grpc-dotnet#1303]
Hello, I have one server and one client that uses .NET 5.0.6 but this package 
https://www.nuget.org/packages/Grpc.AspNetCore/
wants to install old versions of dependencies for me.

1. Microsoft.Extensions.Configuration.3.0.3
2. Microsoft.Extensions.Configuration.Abstractions.3.0.3
3. Microsoft.Extensions.Configuration.Binder.3.0.3
4. Microsoft.Extensions.DependencyInjection.3.0.3
5. Microsoft.Extensions.DependencyInjection.Abstractions.3.0.3
6. Microsoft.Extensions.Http.3.0.3
7. Microsoft.Extensions.Logging.3.0.3
8. Microsoft.Extensions.Logging.Abstractions.3.0.3
9. Microsoft.Extensions.Options.3.0.3
10. Microsoft.Extensions.Primitives.3.0.3

how can I prevent this, I already have these packages in my projects with version 5.
Thank you in advance.

**Comment by BrennanConroy** [comment]
If you're referencing the 5.x packages then you should be resolving the 5.x packages. It wont use the 3.0.3 packages.

Can you share your csproj(s)?

**Comment by ArminShoeibi** [comment]
> If you're referencing the 5.x packages then you should be resolving the 5.x packages. It wont use the 3.0.3 packages.
> 
> Can you share your csproj(s)?

thank you for answer.
my project is empty right now but I have this pictures
![Grpc.AspNetCore](https://i.stack.imgur.com/zMfOb.png)
I don't want this packages into my project what should I do ?
![Grpc.Net.ClientFactory](https://s18.picofile.com/file/8434575526/grpc_aspnetcore2.png)

**Comment by ArminShoeibi** [comment]
I think the problem is here.
https://github.com/grpc/grpc-dotnet/blob/e0b839290fe2de469e452314f1f7a9397954186a/src/Grpc.Net.ClientFactory/Grpc.Net.ClientFactory.csproj#L22

what should I search for learning this type of attributes ? Version="$(MicrosoftExtensionsPackageVersion)"

**Comment by JamesNK** [comment]
Grpc.Net.ClientFactory is requesting that version as it is the minimum version it supports.

If you want higher versions in your app then you can specify `<PackageReference Include="Microsoft.Extensions.Http" Version="5.0.0" />` in your own app's csproj.

**Comment by ArminShoeibi** [comment]
> Grpc.Net.ClientFactory is requesting that version as it is the minimum version required.
> 
> If you want higher versions in your app then you can specify `<PackageReference Include="Microsoft.Extensions.Http" Version="5.0.0" />` in your own app's csproj. NuGet will download 5.0.0 versions because it is higher.

Thank you James for your answer, it worked like a charm.
![Grpc.AspNetCore](https://s19.picofile.com/file/8434591976/grpc_aspnetcore3.png)

but I have another question, Can I specify this version when installing that nuget package?

**Comment by JamesNK** [comment]
No

**Comment by ArminShoeibi** [comment]
> No

Ok, thanks.
