### ISSUE TITLE
dotnet-grpc refresh requires references

### ISSUE THREAD

**Issue by JSanchezIO** [grpc/grpc-dotnet#1305]
### What version of gRPC and what language are you using?
Where do I find this?

### What operating system (Linux, Windows,...) and version?
Mac OS X

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
```
.NET SDK (reflecting any global.json):
 Version:   5.0.203
 Commit:    383637d63f

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.203/

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  5.0.203 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  ```

### What did you do?
1. Installed the `dotnet-grpc` tool
2. Added multiple URL references via `dotnet-grpc add-url -o ./Protos/some.proto -s Client https://some-url.com/`
3. Deleted the `.protos` locally
4. Ran `dotnet-grpc refresh`

### What did you expect to see?
A success response of it fetching the latest for each proto record in the `.csproj`.

### What did you see instead?
```
Required argument missing for command: refresh

refresh:
  Check remote protobuf references(s) for updates and replace them if a newer version is available. If no file or url is provided, all
  remote protobuf files will be updated.

Usage:
  dotnet-grpc refresh [options] <references>...

Arguments:
  <references>    The URL(s) or file path(s) to remote protobuf references(s) that should be updated. Leave this argument empty to refresh
                  all remote references.

Options:
  -p, --project <project>    The path to the project file to operate on. If a file is not specified, the command will search the current
                             directory for one.
  --dry-run                  Output a list of file(s) that will be updated without downloading any new content.
  -?, -h, --help             Show help and usage information
  ```

### Anything else we should know about your project / environment?
N/A

**Comment by JSanchezIO** [comment]
I do believe it's related to this line:
https://github.com/grpc/grpc-dotnet/blob/master/src/dotnet-grpc/Commands/RefreshCommand.cs#L51

However, I'm unsure as I'm not familiar with building CLIs in C#.

**Comment by JamesNK** [comment]
@JunTaoLuo Can you take a look at this?

**Comment by JunTaoLuo** [comment]
Ah this is a bug, the Arity should be set to ZeroOrMore.
