### ISSUE TITLE
Functional test with WebApplicationFactory and AddGrpcClient can't reach the TestServer

### ISSUE THREAD

**Issue by lamLeX** [grpc/grpc-dotnet#1308]
@JamesNK wrote a very good example to guide us how to do the functional test for grpc service here https://github.com/grpc/grpc-dotnet/tree/master/examples/Tester. It includes two major parts: 

- Setting up a [TestServer](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.testhost.testserver?view=aspnetcore-5.0)
- Setting up a GRPC channel that uses the HttpMessageHandler created by TestServer.

However, it's quite some code to maintain. I decided to take different approach that uses `WebApplicationFactory` and grpc client factory integration (via `AddGrpcClient`). My test fixture is boiled down to this single class
```csharp
namespace Tests.FunctionalTests.GrpcTestHelpers
{
    using System;
    using Grpc.Core;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc.Testing;
    using Microsoft.Extensions.DependencyInjection;

    public class GrpcWebApplicationFactory<TStartup, TClient> : WebApplicationFactory<TStartup>
        where TStartup : class
        where TClient : ClientBase<TClient>
    {
        #region Overrides of WebApplicationFactory<T>

        /// <summary>
        /// Gives a fixture an opportunity to configure the application before it gets built.
        /// </summary>
        /// <param name="builder">The <see cref="T:Microsoft.AspNetCore.Hosting.IWebHostBuilder" /> for the application.</param>
        protected override void ConfigureWebHost(IWebHostBuilder builder) =>
            builder
                .UseEnvironment("Test")
                .ConfigureServices(services =>
                    services.AddGrpcClient<TClient>(options =>
                    {
                        options.Address = new Uri("http://localhost");
                    }))
                ;

        #endregion

        public TClient RetrieveGrpcClient()
        {
            return this.Services.GetRequiredService<TClient>();
        }
    }
}
```

And here is my test class using xunit
```csharp
    public class GreeterServiceTests
    : IClassFixture<GrpcWebApplicationFactory<Startup, Greeter.GreeterClient>>
    {
        private readonly GrpcWebApplicationFactory<Startup, Greeter.GreeterClient> factory;

        /// <summary>
        /// Initializes a new instance of the <see cref="GreeterServiceTests"/> class.
        /// </summary>
        /// <param name="factory">The factory.</param>
        public GreeterServiceTests(GrpcWebApplicationFactory<Startup, Greeter.GreeterClient> factory)
            => this.factory = factory;

        [Fact]
        public async Task SayHelloUnaryTest()
        {
            // Arrange
            var client = this.factory.RetrieveGrpcClient();

            // Act
            var response = await client.SayHelloUnaryAsync(new HelloRequest { Name = "Joe" });

            // Assert
            response.Message.Should().Be("Hello Joe");
        }
   }
```

When I run the test, I encountered this exception 
```
Grpc.Core.RpcException
Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: No connection could be made because the target machine actively refused it. (localhost:80) SocketException: No connection could be made because the target machine actively refused it.", DebugException="System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (localhost:80)
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
......
```

My gut told me that the TestServer may not start yet. Digging a bit deeper into the `WebApplicationFactory.CreateClient()`, I found that it makes sure the TestServer running via private `EnsureServer()` method. I decided to call the `CreateClient()` to trigger this `EnsureServer()` side effect like this
```csharp
public TClient RetrieveGrpcClient()
        {
            this.CreateClient();
            return this.Services.GetRequiredService<TClient>();
        }
```
I still received the same exception.
Finally, I decided to replace the HttpClient instance of the grpcClient like this 
```csharp
protected override void ConfigureWebHost(IWebHostBuilder builder) =>
            builder
                .UseEnvironment("Test")
                .ConfigureServices(services =>
                    services.AddGrpcClient<TClient>(options =>
                    {
                        options.ChannelOptionsActions.Add(channelOptions =>
                        {
                            //Set the handler to null
                            //so that we could use the HttpClient created by this WebApplicationFactory
                            channelOptions.HttpHandler = null;
                            channelOptions.HttpClient = this.CreateClient();
                        });
                        options.Address = new Uri("http://localhost");
                    }))
                ;
```
My test finally passed.

I'm keen to understand this behavior. Is it possibly a bug in `WebApplicationFactory` or is it a bug in `AddGrpcClient`? If all are working as designed, is this a correct way to set it up?

**Comment by JamesNK** [comment]
You need to configure the HttpHandler that the channel created by the client factory uses.

See https://github.com/grpc/grpc-dotnet/blob/e0b839290fe2de469e452314f1f7a9397954186a/test/Grpc.Net.ClientFactory.Tests/DefaultGrpcClientFactoryTests.cs#L52

Looks like you can get that from `this.Server.CreateHandler()` on `WebApplicationFactory`.

**Comment by lamLeX** [comment]
Ah perfect timing, I ran into a deadlock with my solution when running the `SayHelloBidirectionStreamingTest`. 
Using your suggestion, all tests passed. 
Are you open for a PR in the Tester sample to use `WebApplicationFactory`? I can submit one with what I shown earlier. The only downside for using `WebApplicationFactory` is that it hides all the mechanics under the hood. People who can't use grpc client factory may not be able to write their own functional test. 

Alternatively, a PR to this doc https://docs.microsoft.com/en-us/aspnet/core/grpc/client?view=aspnetcore-5.0 for writing functional test for grpc could be a better choice?

**Comment by JamesNK** [comment]
I want to keep the tester sample flexible enough to work without the factory.

A new article on unit testing and functional testing would be useful. That would be a significant investment of time to write, edit and publish an article .

**Comment by Doan-Van-Tuan** [comment]
@JamesNK Is the TestServer in the functional test a real server, i.e. its services can be used by an external consumer?
My situation is like this: I have a standalone console application. When its started and ready, it must notify its controller application via gRPC. To do that, I need to host a real gRPC service in my test. Is there an existing example doing just that?

**Comment by BrennanConroy** [comment]
TestServer can not be used by a separate process, use Kestrel in that case.

**Comment by Doan-Van-Tuan** [comment]
Thanks, I already did that. I was hoped for a more light-weight testing harness. Perhaps it's possible to build a Grpc-over-inter-process-channel for such tests, but Kestrel is acceptable for me now.

**Comment by JamesNK** [comment]
Closing as answered.

**Comment by rdcm** [comment]
@lamLeX Same issue for me. Could you share any worked examples with WebApplicationFactory? 
Thanks

**Comment by lamLeX** [comment]
Hi @rdcm,
I have already provided the example in my original post.
The only change to make it work is to `ConfigurePrimaryHttpMessageHandler` as James suggested.
So the final code should look like this 

```cs
        /// <summary>
        /// Gives a fixture an opportunity to configure the application before it gets built.
        /// </summary>
        /// <param name="builder">The <see cref="T:Microsoft.AspNetCore.Hosting.IWebHostBuilder" /> for the application.</param>
        protected override void ConfigureWebHost(IWebHostBuilder builder) =>
            builder
                .UseEnvironment("Test")
                .ConfigureServices(services =>
                {
                    services
                        .AddGrpcClient<TClient>(options => options.Address = new Uri("http://localhost"))
                        .ConfigurePrimaryHttpMessageHandler(() => this.Server.CreateHandler());

                    this.AddCustomServices(services);
                })
                ;
```

**Comment by rdcm** [comment]
Thanks a lot, works perfect!

As alternative you can run grpc host without `Microsoft.AspNetCore.Mvc.Testing` package, with explicit composition and client creation.

**Comment by j2jensen** [comment]
Just a little warning about `ConfigurePrimaryHttpMessageHandler`: If your tests ever leverage `WithWebHostBuilder` for customizations, that method returns a new derived factory instance. `this.Server` refers to the current Factory instance, and will automatically ensure the server is booted up, so  `.ConfigurePrimaryHttpMessageHandler(() => this.Server.CreateHandler())` can cause a second instance of the web host to boot up, with all of the startup logic in your Program getting executed again. Instead, you can use `.ConfigurePrimaryHttpMessageHandler(services => ((TestServer)services.GetRequiredService<IServer>()).CreateHandler())`.
