### ISSUE TITLE
Publish symbol packages

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#131]
Symbol packages contain debug files (*.pdb). There is a new snupkg package format and NuGet.org hosts a server for them.

More info:
https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/nuget#symbol-packages

This shouldn't be difficult for Grpc.AspNetCore.Server because it uses `dotnet pack`. It is just a matter of adding an extra argument and then publishing the snupkg.

Ideally Grpc.Core and Grpc.Core.Api would also have symbol packages. I think they use nuget.exe and I'm not sure how easy it is to produce a snupkg with that tool. Lower priority.

**Comment by jtattermusch** [comment]
I can take a look into adding symbol packages for Grpc.Core and Grpc.Core.Api (we are using dotnet pack for everything).  The reason why this hasn't been done yet is that the story for symbol packages has been changing over time and it was unclear what really needs to be done to enable good debugging experience (we used to have `.symbols` nugets in the past, which stopped working at some point, then we added sourcelink - I thought just using sourcelink should be enough).

**Comment by JamesNK** [comment]
Packaging the pdb file alongside the dll in the primary NuGet package is fine. This is what Grpc.Core and Grpc.Core.Api do today.

Currently Grpc.AspNetCore.Server does not have the pdb file in the NuGet package.
