### ISSUE TITLE
how to run grpc-dotnet the example of certifier on linux?

### ISSUE THREAD

**Issue by sgalcheung** [grpc/grpc-dotnet#1310]
When I run the examples of certifier on Linux
The client returns the output
```
Setting up HttpClient. Client has certificate: False
Sending gRPC call...
gRPC error from calling service: Error starting gRPC call. HttpRequestException: The SSL connection could not be established, see inner exception. AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot
Setting up HttpClient. Client has certificate: True
Sending gRPC call...
gRPC error from calling service: Error starting gRPC call. HttpRequestException: The SSL connection could not be established, see inner exception. AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot
Press any key to exit...
```
So I tried to add client/certs/client.pfx to the certs root, but an error occurred
![image](https://user-images.githubusercontent.com/42566429/120063690-09188d80-c09b-11eb-9711-aed0df7f2d1c.png)

**Comment by JamesNK** [comment]
I'm not familiar with importing a certificate using the tool in your screenshot.

I think you should figure out how to import pfx files into the tool by asking for help in its forums. You will probably need to cert the pfx certificate into a format it understands.

**Comment by JamesNK** [comment]
Closed because of lack of activity.
