### ISSUE TITLE
Request underlying transport channel support for QUIC (HTTP/3)

### ISSUE THREAD

**Issue by larspaulsen** [grpc/grpc-dotnet#1317]
### Is your feature request related to a problem? Please describe.
QUIC was approved as an IETF standard May 27 2021.

For more information:
https://en.wikipedia.org/wiki/QUIC
https://www.ietf.org/rfc/rfc9000.html
https://datatracker.ietf.org/doc/rfc9000/

I assume this group is aware of the benefits of QUIC, such as:
* Seamless underlying connection media switching, such as switching between: Ethernet <-> Wi-Fi <-> Cellular, etc.
*  Avoid head-of-line-blocking issues.
* Quicker reestablishment of known connections.
* And many other important features...

### Describe the solution you'd like
Support for specifying QUIC (HTTP/3) as the underlying channel transport protocol.

### Describe alternatives you've considered
No alternatives, other than to use the less desirable existing support for TCP.

### Additional context
None

**Comment by chwarr** [comment]
This probably needs to be proposed through the [gRPC proposal process](https://github.com/grpc/proposal/) since it will impact the entire gRPC ecosystem and implementation will be needed across languages.

**Comment by JamesNK** [comment]
When .NET gets support for HTTP/3 then it won't be much work to support gRPC over HTTP/3 in .NET. Both the client and server abstract a lot of the transport level concerns away.

Looking at the [gRPC HTTP/2 spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md):
* gRPC headers won't change.
* gRPC content won't change.
* HTTP/2 transport mapping **will** change. For example, how do HTTP/3 error codes map to gRPC statues.

@jtattermusch

**Comment by jtattermusch** [comment]
I think two things are needed here:
- gRPC as a whole needs to finalize a plan for HTTP/3 support (as @chwarr  has pointed out, a gRPC proposal will most likely be needed for that. The proposal will need to define all the details of gRPC over HTTP/3 protocol).
- .NET adds HTTP/3 support.

See related issue https://github.com/grpc/grpc/issues/19126.

**Comment by JamesNK** [comment]
This is supported in .NET 6.

Proposal is in-progress.
