### ISSUE TITLE
Connect to containerd NamedPipe server on windows

### ISSUE THREAD

**Issue by veerun14** [grpc/grpc-dotnet#1318]
I'm trying to connect to [containerd](https://github.com/containerd/containerd) NamedPipe server on windows by using [SocketsHttpHandler.ConnectCallback ](https://github.com/dotnet/runtime/blob/7c0973ebaa7353239c1127553c6ceeb24edc39b9/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/SocketsHttpHandler.cs#L374)callback to make a new connection

HttpClient will then use this SocketsHttpHandler and grpc-dotnet's GrpcChannel will use this customized HttpClient.

I able to connect to NamedPipe server, but when I attempt to write, nothing gets written over the pipe and after 2 mins, I get an error saying 'Pipe is broken' (probably one end of the pipe timed out and closed the connection)

My question is, has anybody successfully connected to a Namedpipe server by modifying GrpcChanne's HttpClient this way?

Help!

**Comment by JamesNK** [comment]
I have only tested Unix Domain Sockets (UDS). Named pipes are theoretically possible but I haven't heard of anyone using it. Kestrel doesn't have built-in support for named pipes, meanwhile, it does for UDS, so people have been using UDS.

**Comment by veerun14** [comment]
@JamesNK, Aha! That is good to know.
 Any pointers/samples on how to use UDS on windows with .Net Core?

**Comment by JamesNK** [comment]
I don't understand your question. If your server is using unix domain sockets (UDS) then UDS would work. Note that TCP sockets are different from unix domain sockets.

**Comment by veerun14** [comment]
Sorry for the confusion.
I was saying that my server only uses named pipes and not UDS. So, in my case, UDS is not helpful.

thx

**Comment by chwarr** [comment]
@veerun14, if it helps, [Windows has added support for Unix Domain Sockets (AF_UNIX)](https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/). If your Windows builds are new enough (within the past 2 years, IIRC), you could explore using UDS on Windows instead of named pipes.

**Comment by JamesNK** [comment]
Closing as answered.

**Comment by untoldbyte** [comment]
Can krestel with namedpipe be configured such that it does not open a local tcp port e.g. http://localhost:5000 ?
