### ISSUE TITLE
Upgrading grpc-core server to grpc-dotnet 

### ISSUE THREAD

**Issue by kernel32uiuc** [grpc/grpc-dotnet#1324]
I decided to move my codebase from grpc-core to grpc-dotnet. My main motivation for the upgrade is better support for authentication as we can pass a custom HttpClient and HttpClientHandler to GrpcChannel. 

Regarding server-side, do I really need a web server (Kestrel) to host my grpc service? I currently use grpc for machine-to-machine communication in an internal network, so a web server would be pretty redundant.

**Comment by JamesNK** [comment]
Grpc.Core and Kestrel are both web servers. gRPC typically uses HTTP/2 over TCP sockets so a web server is required.

**Comment by JamesNK** [comment]
Closing as answered.
