### ISSUE TITLE
dotnet-grpc vs. grpc-dotnet

### ISSUE THREAD

**Issue by boldt** [grpc/grpc-dotnet#1328]
Hey,

I have some question regaring new dotnet-grpc, which you describe in the blog article [The future of gRPC in C# belongs to grpc-dotnet](https://grpc.io/blog/grpc-csharp-future/):

* Do you provide an official migration guide?
* What's the exact difference between grpc-dotnet (this repo) and the nuget package [grpc-dotnet](https://www.nuget.org/packages/dotnet-grpc/)?
* What's the dotnet replacement nuget for [Grpc.Core](https://www.nuget.org/packages/Grpc.Core/)?
* What's the dotnet replacement nuget for [Grpc.Tools](https://www.nuget.org/packages/Grpc.Tools/)?

Thanks!

**Comment by chwarr** [comment]
> Do you provide an official migration guide?

Take a look at [Migrating gRPC services from C-core to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/migration?view=aspnetcore-5.0) on docs.microsoft.com. Is that what you're looking for?

---------

> What's the exact difference between grpc-dotnet (this repo) and the nuget package [grpc-dotnet](https://www.nuget.org/packages/dotnet-grpc/)?

The grpc-dotnet package implements the `dotnet grpc` functionality. (It's a [.NET tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools).) It helps you do things like add, remove, and refresh ProtoBuf references to your .csproj. The source code for that package is in the [`/src/dotnet-grpc`](https://github.com/grpc/grpc-dotnet/tree/master/src/dotnet-grpc) subdirectory of this repo.

---------

> What's the dotnet replacement nuget for Grpc.Core?

Depending on what you're doing, likely some combination of Grpc.AspNetCore (service-side) and Grpc.Net.Client (client-side). The [gRPC for .NET README](https://github.com/grpc/grpc-dotnet#grpc-for-net) has some more details:


> * [Grpc.AspNetCore](https://www.nuget.org/packages/Grpc.AspNetCore) – An ASP.NET Core framework for hosting gRPC services. gRPC on ASP.NET Core integrates with standard ASP.NET Core features like logging, dependency injection (DI), authentication and authorization.
> * [Grpc.Net.Client](https://www.nuget.org/packages/Grpc.Net.Client) – A gRPC client for .NET Core that builds upon the familiar HttpClient. The client uses new HTTP/2 functionality in .NET Core.
> * [Grpc.Net.ClientFactory](https://www.nuget.org/packages/Grpc.Net.ClientFactory) – gRPC client integration with HttpClientFactory. The client factory allows gRPC clients to be centrally configured and injected into your app with DI.

--------

> What's the dotnet replacement nuget for Grpc.Tools?

No replacement needed. It works for both gRPC.Core and gRPC for .NET.

From [The future of gRPC in C# belongs to grpc-dotnet](https://grpc.io/blog/grpc-csharp-future/):

> Future of Grpc.Tools and Grpc.Core.Api nuget packages
>
> Both packages will continue to be fully supported, since they are strictly speaking not part of Grpc.Core and they are also used by grpc-dotnet.
>
> * the Grpc.Tools nuget package which provides the codegen build integration for C# projects will continue to be supported (and will potentially get improvements) – as it’s used by both Grpc.Core and grpc-dotnet. This package is independent of C core.

**Comment by boldt** [comment]
@chwarr Thanks for the explanation **Grpc.AspNetCore** for server-side and **Grpc.Net.Client** for client-side works well. Thanks.
