### ISSUE TITLE
Refresh JWT token in gRPC client

### ISSUE THREAD

**Issue by MaximGurschi** [grpc/grpc-dotnet#1330]
Hi,

Using HttpClient + SocketsHttpHandler, is there a hook or other mechanism to detect expired bearer tokens during the call and refresh them?

**Comment by MaximGurschi** [comment]
I've managed to set something together for this based on DelegatingHandler as described here:
[https://stackoverflow.com/questions/56204350/how-to-refresh-a-token-using-ihttpclientfactory](url)

Basically i chain together SocketsHttpHandler and override the SendAsync method of DelegatingHandler. On a failed initial request I retrieve a new token and do the call again. This work nice for requests where the client does not stream data to the service.

However that method does not work in case the client does a streaming request. In this case the body of the requests sent to the service seems to disappear. I assume that is by design? I concluded that the body must disappear as my service does in fact register the call but the IAsyncStreamReader requestStream is empty.

**Comment by JamesNK** [comment]
How the server uses and validates a JWT token is up to the server. Typically in ASP.NET Core a JWT token is validated once when a request is started.

**Comment by MaximGurschi** [comment]
@JamesNK Thank you. Can the behaviour be explicitly enforced in the server code such that i can rely on it?

Shall i take your answer as meaning my conclusions are consistent?

**Comment by JamesNK** [comment]
You need to look at how your server uses JWT tokens. I can't tell you how your server works.

**Comment by MaximGurschi** [comment]
@JamesNK Of course. My grpc server really does not do anything special than just requiring jwt tokens. If the token arrives expired then i return a special header to the caller. There is nothing more to the config.

**Comment by JamesNK** [comment]
Closing as answered.
