### ISSUE TITLE
Cannot bypass the execution of other interceptors

### ISSUE THREAD

**Issue by jorgecasals** [grpc/grpc-dotnet#1334]
I haven't found any mechanism that allows me to have a service for which none global interceptors intercept the call. The only way of doing that is by changing the interceptors from global to by-service and apply them to the rest of services, which in my case is very ugly. 
I need a functionality to avoid interceptors to be executed for one specific call. Example of this: when you have a non-authenticated call that doesn't need the authentication interceptors to verify credentials. There are other examples as well ...
Is this a functionality we can expect in the future or is there a way of doing it with the current functionality ( I have tried but not luck as now)

**Comment by JamesNK** [comment]
That isn't supported. Making configuration more complex has drawbacks and your the first person to ask about this, so it isn't a common situation. If there is more demand in the future then that might change.

I suggest you write an interceptor that is added everywhere but doesn't do anything for some calls. You could do that by getting the current request's `HttpContext` from the `ServerCallContext`, then get the `Endpoint` from the `HttpContext`, then inspect its metadata. Run or bypass the interceptor logic depending upon the metadata.

This is close to the way authentication middleware runs in ASP.NET Core. It is always present and whether it runs or not depends on endpoint metadata.
