### ISSUE TITLE
Interceptor not being called

### ISSUE THREAD

**Issue by CoryKoehler** [grpc/grpc-dotnet#1335]
Hi,

I am trying to create a grpc interceptor that will add a bearer token to the request header on every call if it is available.
This is in blazor wasm with pre-rendering and my grpc package versions are 2.37.0

My interceptor code 
```    
public class GrpcAuthInterceptor : Interceptor
    {
        private readonly string _apiUrl;
        private readonly string[] _scopes = new[] { "somescope" };
        private readonly AuthenticationStateProvider _authenticationStateProvider;

        public GrpcAuthInterceptor(string apiUrl, AuthenticationStateProvider authenticationStateProvider)
        {
            _apiUrl = apiUrl;
            _authenticationStateProvider = authenticationStateProvider;
        }

        public override AsyncClientStreamingCall<TRequest, TResponse> AsyncClientStreamingCall<TRequest, TResponse>(
            ClientInterceptorContext<TRequest, TResponse> context,
            AsyncClientStreamingCallContinuation<TRequest, TResponse> continuation)
        {
            Console.WriteLine("In add async client streaming call");
            AddCallerMetadata(ref context);
            
            return continuation(context);
        }

        private void AddCallerMetadata<TRequest, TResponse>(ref ClientInterceptorContext<TRequest, TResponse> context)
            where TRequest : class
            where TResponse : class
        {
            Console.WriteLine("In add caller metadata");
            var headers = context.Options.Headers;
            
            var authState = _authenticationStateProvider.GetAuthenticationStateAsync().GetAwaiter().GetResult();
            var user = authState.User;
            Console.WriteLine("grabbing a user");
            var token = user.Claims.FirstOrDefault(a => a.Type == "access_token")?.Value;
            Console.WriteLine($"{user.Claims.Select(_ => _.Value)}");
            // Call doesn't have a headers collection to add to.
            // Need to create a new context with headers for the call.
            if (headers == null)
            {
                headers = new Metadata();
                var options = context.Options.WithHeaders(headers);
                context = new ClientInterceptorContext<TRequest, TResponse>(context.Method, context.Host, options);
            }

            // Add caller metadata to call headers
            headers.Add("grpc-internal-encoding-request", "gzip");

            Console.WriteLine("adding token");
            headers.Add("Authorization", $"Bearer {token}");
        }
    }
```

I add the interceptor to DI with this line of code 
```
services.AddSingleton(new GrpcAuthInterceptor(apiUrl, services.BuildServiceProvider().GetService<AuthenticationStateProvider>()));
```

I add the interceptor to the grpc client like

```   
serviceCollection
                .AddGrpcClient<SomeClient.Client>("clientname", options =>
                {
                    options.Address = new Uri(apiUrl);
                })
                .AddInterceptor<GrpcAuthInterceptor>()
                .ConfigureChannel(options =>
                {
                    options.ServiceConfig = new ServiceConfig { MethodConfigs = { defaultMethodConfig } };
                })
                .ConfigurePrimaryHttpMessageHandler(() =>
                {
                    var handler = new GrpcWebHandler(GrpcWebMode.GrpcWeb, new HttpClientHandler());
                    return handler;
                });
```

I can see the constructor of the interceptor being called but no other methods are called.
Any help is appreciated thank you!

**Comment by JamesNK** [comment]
You're only implementing `AsyncClientStreamingCall`. Are you making a client streaming call with your client? It won't be called for other method types.

**Comment by CoryKoehler** [comment]
Yes - that is the only type of call I am making with my grpc clients currently

**Comment by JamesNK** [comment]
I don't know why then. The interceptor is successfully called in this test I wrote - https://github.com/grpc/grpc-dotnet/pull/1337

What are you doing that is different?

**Comment by CoryKoehler** [comment]
I am not setting up ConfigureGrpcClientCreator or ConfigurePrimaryHttpMessageHandler which I am not sure if that would be it. Other than that it could be because I am using AuthenticationStateProvider in the interceptor which is in blazor wasm app with pre-rendering. I am not sure if either of those could cause any issues.

**Comment by JamesNK** [comment]
Neither of those should be relevent. They are just for the functional test.

Can you upload a simple repro?

**Comment by CoryKoehler** [comment]
Yeah I can do that. I am going to be out of office today though so won't get to it till next week.

**Comment by CoryKoehler** [comment]
Overall I was able to solve the not hitting the grpc interceptor. The problem was my app swallowing an exception with regards to async and never making the call to the interceptor. "Cannot await monitors in this runtime". Is there anyway within the interceptor call an async method to modify the request?
I pulled up https://github.com/grpc/grpc-dotnet/issues/694 and it seems that this may still not be possible but at the same time there is https://github.com/grpc/grpc-dotnet/issues/825 with some code https://github.com/grpc/grpc-dotnet/pull/827/files
that essentially modifies the response since it is looking for Task<TResponse>

Any thoughts on how to accomplish?

**Comment by CoryKoehler** [comment]
This was as close as I was able to get...still no go on actually providing the bearer token via Provider.
Is the below an intended/correct usage of the AsyncAuthInterceptor? 
```
  public override AsyncClientStreamingCall<TRequest, TResponse> AsyncClientStreamingCall<TRequest, TResponse>(
      ClientInterceptorContext<TRequest, TResponse> context,
      AsyncClientStreamingCallContinuation<TRequest, TResponse> continuation)
  {
      var headers = context.Options.Headers;
      // Call doesn't have a headers collection to add to.
      // Need to create a new context with headers for the call.
      if (headers == null)
      {
          headers = new Metadata();
          var options = context.Options.WithHeaders(headers);
          context = new ClientInterceptorContext<TRequest, TResponse>(context.Method, context.Host, options);
      }
      
      // Add caller metadata to call headers
      headers.Add("grpc-internal-encoding-request", "gzip");
      context.Options.WithHeaders(headers);
      
      var callCredentials = CallCredentials.FromInterceptor(async (authInterceptorContext, metadata) => {
          // The operation is asynchronous to ensure delegate is awaited
          var authState = await _authenticationStateProvider.GetAuthenticationStateAsync();
          var user = authState.User;
          var token = user.Claims.FirstOrDefault(a => a.Type == "access_token")?.Value;
      
          //headers.Add("authorization", token);
          metadata.Add("authorization", token);
      });
      context.Options.WithCredentials(callCredentials);
      
      return continuation(request, context);
}
```

**Comment by RonPeters** [comment]
@CoryKoehler Did you ever figure this out? I want to do this in an interceptor because I can't figure out how to do it in the factory without DI re-instantiating the entire scope for every call. But for the life of me I can't figure out how to asynchronously modify the request in an interceptor. All the async examples modify the response.

**Comment by CoryKoehler** [comment]
@RonPeters I wouldn't say I figured it out. As mentioned above my issue comes from blazor wasm where I can't use some of the async functionality due to the run time monitors. So above was as close as I was able to get before having to abandon this

**Comment by RonPeters** [comment]
@CoryKoehler Just got a response from the team yesterday that they have added a way to do this properly using `AddCallCredentials` in 2.46.0-pre1: (https://github.com/dotnet/AspNetCore.Docs/pull/25734/commits/1e9bb3ba38f68021aeebebb45bc83c7d1dba9d60)

**Comment by JamesNK** [comment]
> It's not a generic way to modify the headers asynchronously in an interceptor, but solves the specific use case of setting up the call credentials.

Although it is called "AddCallCredentials", you can set whatever headers you want in it with async + DI.

**Comment by CoryKoehler** [comment]
> > It's not a generic way to modify the headers asynchronously in an interceptor, but solves the specific use case of setting up the call credentials.
> 
> Although it is called "AddCallCredentials", you can set whatever headers you want in it with async + DI.

thanks for the clarity. I will be sure to try this out

**Comment by RonPeters** [comment]
@CoryKoehler Just tried AddCallCredentials in the latest release. Works like a charm with DI and doesn't create a new scope.
