### ISSUE TITLE
How is the retry delay duration exponential?

### ISSUE THREAD

**Issue by macon** [grpc/grpc-dotnet#1339]
https://github.com/grpc/grpc-dotnet/blob/6920e2abd016401ba2a602fbee45a25872acbea8/src/Grpc.Net.Client/Internal/Retry/RetryCall.cs#L213

I don't see how subsequent delay durations can be exponential when it is recalculated each retry attempt based on the above line i.e.

```
delayDuration = TimeSpan.FromMilliseconds(Channel.GetRandomNumber(0, Convert.ToInt32(_nextRetryDelayMilliseconds)));
```

All the `BackoffMultiplier` is doing is increasing the upper bound of the RNG but it can still return non-increasing numbers.

**Comment by JamesNK** [comment]
The retry delay range increases exponentially, but the actual delay is random. That is by-design to avoid the situation of many clients making calls simultaneously. Randomness makes them offset from one another.

https://github.com/grpc/proposal/blob/master/A6-client-retries.md#exponential-backoff

**Comment by JamesNK** [comment]
Improved the docs to say what and why - https://github.com/dotnet/AspNetCore.Docs/pull/22672

**Comment by macon** [comment]
Thanks for clarifying the design. 

My issue with this approach is that I can't guarantee a retry after e.g. 1s. Why not calculate a 'normal' exponential backoff and then add a small amount of jitter to it?

If I want a retry profile like 1s, 2s, 4s, I don't mind getting 1.01s, 2.32s, 4.3s but I don't want to get 1s, 1s, 1s.

**Comment by JamesNK** [comment]
All gRPC clients follow a spec about how retrying is implemented (linked to earlier). I looked at comments about why this kind of randomness was chosen and people felt that a small offset like you discribed isn't enough to stop a server from getting overloaded by clusters of retries.

If more people raise this as an issue then it might change, but no plans for now.
