### ISSUE TITLE
AsyncUnaryCall and similar should have compiler warnings for unawaited calls.

### ISSUE THREAD

**Issue by taori** [grpc/grpc-dotnet#1340]
### Is your feature request related to a problem? Please describe.
I just spent a couple hours looking into flaws of the sources of the HttpClientHandler implementation for android, just to find out that the issue had nothing to do with that class, but there were unawaited AsyncUnaryCall cases.

### Describe the solution you'd like
A compiler warning for any awaitable types similar to how it is done for Task<T>

### Describe alternatives you've considered
No idea - compiler warning would be the best

### Additional context
I have written compiler warnings before and would be willing to contribute

**Comment by JamesNK** [comment]
I tested this out and I got a warning in VS that `AsyncUnaryCall` wasn't awaited:

![image](https://user-images.githubusercontent.com/303201/125159028-e95fa380-e1c8-11eb-81a4-097f42c974a4.png)

**Comment by taori** [comment]
Ok - that is odd. Do i have to install additional packages to get that compiler warning? There was no warning in my xamarin android project.
