### ISSUE TITLE
Please add application/grpc-web to allowed content types for Grpc.AspNetCore.Server

### ISSUE THREAD

**Issue by Brian-Wuest** [grpc/grpc-dotnet#1343]
### Is your feature request related to a problem? Please describe.
Grpc.AspNetCore.Server/Internal/CallHandlers/ServerCallHandlerBase.cs does not allow for a content-type of "application/grpc-web.

It only seems to allow for "application/grpc" (with the +proto or whatever else the format happens to be).

This line appears to not use the GrpcWebContentType constant: https://github.com/grpc/grpc-dotnet/blob/6920e2abd016401ba2a602fbee45a25872acbea8/src/Grpc.AspNetCore.Server/Internal/GrpcProtocolHelpers.cs#L85

constant location: https://github.com/grpc/grpc-dotnet/blob/6920e2abd016401ba2a602fbee45a25872acbea8/src/Grpc.AspNetCore.Server/Internal/GrpcProtocolConstants.cs#L30

I have tested out an Angular application using grpc-web to see if it would work with grpc-dotnet and when I change the content-type to "application/grpc" the message processes successfully. This was a small test with just a simple message so there might be some edge cases I haven't considered.

### Describe the solution you'd like
Add an || clause to the else-if to include the GrpcWebContentType constant as part of the check of valid content types: https://github.com/grpc/grpc-dotnet/blob/6920e2abd016401ba2a602fbee45a25872acbea8/src/Grpc.AspNetCore.Server/Internal/GrpcProtocolHelpers.cs#L85

### Describe alternatives you've considered
As stated in the problem statement; I was able to get this to work by modifying the grpc-web source code locally to send a different content type but that is not a long-term solution.

**Comment by JamesNK** [comment]
The server won't produce a valid `application/grpc-web` response.

You can configure ASP.NET Core middleware to support gRPC-Web correctly - https://docs.microsoft.com/en-us/aspnet/core/grpc/browser

**Comment by Brian-Wuest** [comment]
Ugh, how could I be so blind!

I missed this part of the setup:

![image](https://user-images.githubusercontent.com/13502068/125946390-a638f662-f381-4290-8f4a-03c38865b7c8.png)

That worked perfectly!

Sorry to waste your time.

Closing issue.
