### ISSUE TITLE
Reflection extension doesn't work properly when Grpc service has a super class

### ISSUE THREAD

**Issue by NielsHoogeveen** [grpc/grpc-dotnet#1344]
In  GrpcReflectionServiceExtensions, the method GetServiceBaseType tries to retrieve that generated server implemention class by going down the hierarchy of the actual service class. 

The assumption here is that the generated server implementation derives directly from object, but this is not necessarily the case. 

Since the generated server implementation is a partial class, it is possible to create a partial class for that server implementation that inherits from some class. 

When this construct is used, these services are not included for reflection.

**Comment by JamesNK** [comment]
Thanks. Fixed.
