### ISSUE TITLE
Add non generic "MapGrpcService" method in GrpcEndpointRouteBuilderExtensions.cs

### ISSUE THREAD

**Issue by mhehle** [grpc/grpc-dotnet#1345]
### Is your feature request related to a problem? Please describe.
In a moduar architecture i want to register gRPC service classes manually at runtime.
Currently i need to use a workaround for the generic method to register my services.

### Describe the solution you'd like
Add new non generic "MapGrpcService" method to GrpcEndpointRouteBuilderExtensions.cs

`GrpcEndpointRouteBuilderExtensions.MapGrpcService(Type grpcType)`

### Describe alternatives you've considered
Workaround:

``` c#
 var method = typeof(GrpcEndpointRouteBuilderExtensions)
                    .GetMethod(nameof(GrpcEndpointRouteBuilderExtensions.MapGrpcService))
                    .MakeGenericMethod(myGrpcType);

method.Invoke(null, new[] { endpointRouteBuilder }); 
```

**Comment by davidfowl** [comment]
Are you looking for a convenience method?

**Comment by mhehle** [comment]
in my case yes, in general I would find it really helpful if there was the possibility to add grpc services manually to the service collection (via a generic method as well as a non-generic one).

currently there is only one method for bootstrapping Grpc Services 

``` c# 
IServiceCollection.AddGrpc()
```

Iam missing something like this:

``` c#
IServiceCollection.AddGrpcService<TService>()
IServiceCollection.AddGrpcService(Type serviceType)
```

**Comment by davidfowl** [comment]
I'm just saying that if it existed, it would do the same thing you're doing right now. GRPC has a heavy dependency on generics so the non generic overloads would need to convert to the typed overload for it to work. You'd also lose the ability to make the application trim friendly but if you're already dynamically loading assemblies and using plugins that won't work anyways..

**Comment by mhehle** [comment]
okay, thanks for the explanation.

i think it's probably better if i stick with my workaround, so you don't have to turn the concept behind this library upside down.
