### ISSUE TITLE
Multiple resolutions of load-balanced gRPC client using Grpc.Net.ClientFactory seems to fail.

### ISSUE THREAD

**Issue by pcwiese** [grpc/grpc-dotnet#1348]
I'm running into an issue while I was building a custom resolver to return endpoints to the round-robin balancer. It seems like the resolution of a client after the first (in a test) is failing and I'm not starting any rpcs on either client. I'm wondering if this is a bug or I am misusing the APIs in some way.

The exception is:
System.InvalidOperationException : Channel is configured with an HTTP transport doesn't support client-side load balancing or connectivity state tracking. The underlying HTTP transport must be a SocketsHttpHandler with no SocketsHttpHandler.ConnectCallback configured. The HTTP transport must be configured on the channel using GrpcChannelOptions.HttpHandler.

I thought perhaps it was my own resolver but I can repro the same issue using the built-in StaticResolver. I added a small unit test in the repo that illustrates the issue. My repo change is here against the tip of the tree. [My Repo Commit](https://github.com/pcwiese/grpc-dotnet/commit/2f6a8d9ef3456848174d38597ac9ad831e99fad5). It's only the 2nd resolution of the client. Granted this is from a unit test.

```csharp
  var services = new ServiceCollection();

  services.AddSingleton<ResolverFactory>(new StaticResolverFactory(_ => new[]
  {
      new DnsEndPoint("localhost", 50051),
  }));

  // TestClient requires a Method registration.
  services.AddSingleton(DynamicGrpcServiceRegistry.CreateMethod<HelloRequest, HelloReply>(MethodType.Unary, "unused" ?? Guid.NewGuid().ToString()));

  // Register the client using the Factory
  services
      .AddGrpcClient<TestClient<HelloRequest, HelloReply>>(
          o =>
          {
              o.Address = new Uri("static:///localhost");
          })
      .ConfigureChannel(
          o =>
          {
              o.Credentials = global::Grpc.Core.ChannelCredentials.Insecure;
              o.DisableResolverServiceConfig = true;
              o.ServiceProvider = services.BuildServiceProvider();
              o.ServiceConfig = new ServiceConfig
              {
                  LoadBalancingConfigs = { new RoundRobinConfig() }
              };
          });

  var serviceProvider = services.BuildServiceProvider();

  // 1st resolution succeeds
  var client1 = serviceProvider.GetRequiredService<TestClient<HelloRequest, HelloReply>>();

  // 2nd does not.
  var client2 = serviceProvider.GetRequiredService<TestClient<HelloRequest, HelloReply>>();

```
cc: @JamesNK

**Comment by JamesNK** [comment]
Client factory currently doesn't work together with load balancing. Today the client factory createa a new channel each time (but no the HTTP layer), which isn't good once you have state.

That's mentioned in the docs.

Will figure out how they will work together later.

**Comment by pcwiese** [comment]
closing this as by design for now.

**Comment by jvanderflier** [comment]
Load balancing using GRPC Client 

builder.Services
    .AddGrpcClient<NotificationGrpc.NotificationGrpcClient>((services, options) => {

        options.Address = new Uri("static:///localhost");
    })
        .ConfigureChannel(options => {

            var services = new ServiceCollection();

            var factory = new StaticResolverFactory(addr => new[]
                {
                    new BalancerAddress("localhost", 5001),
                    new BalancerAddress("localhost", 5002)
                });

            services.AddSingleton<ResolverFactory>(factory);

            options.ServiceConfig = new ServiceConfig { LoadBalancingConfigs = { new RoundRobinConfig() } };
            options.ServiceProvider = services.BuildServiceProvider();
            options.Credentials = ChannelCredentials.SecureSsl;

        })
        .ConfigurePrimaryHttpMessageHandler(() => {

            //var httpHandler = new HttpClientHandler();
            //// Return `true` to allow certificates that are untrusted/invalid
            //httpHandler.ServerCertificateCustomValidationCallback =
            //    HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;

            // use socket handler to support load balancing

            var socketsHandler = new SocketsHttpHandler();
            // Return `true` to allow certificates that are untrusted/invalid
            socketsHandler.SslOptions = new System.Net.Security.SslClientAuthenticationOptions {
                RemoteCertificateValidationCallback = delegate { return true; }
            };


            return socketsHandler;
        });
