### ISSUE TITLE
Add support for grpc.ssl_target_name_override

### ISSUE THREAD

**Issue by jayd16** [grpc/grpc-dotnet#1362]
I would like to see support for for the [grpc.ssl_target_name_override](https://grpc.github.io/grpc/csharp/api/Grpc.Core.ChannelOptions.html#Grpc_Core_ChannelOptions_SslTargetNameOverride) ChannelOption from the legacy Grpc.Core implementation supported in grpc-dotnet.  This is a very nice testing feature.

I can't find the equivalent configuration in grpc-dotnet.  I've also tried setting the request host header from HttpClientHandler by overriding SendAsync and that doesn't seem to work.

I cannot simply ignore the server certificate from the client either.  The ServerCertificateCustomValidationCallback is never even hit because the Grpc server will only return a cert for the requested host and otherwise kill the socket.  An example of the server error when requesting the wrong host:
`E0805 18:58:05.678826 123145379745792 /tmpfs/src/github/grpc/workspace_csharp_ext_macos_x64/src/core/tsi/ssl_transport_security.cc:1837: No match found for server name: localhost.`

Can this be added or is there some other way to achieve this?  Thanks!

**Comment by JamesNK** [comment]
I think this would need to be supported in SocketsHttpHandler first. Grpc.Net.Client uses it for its networking layer.

**Comment by jayd16** [comment]
If that's the case, there might already be a way?  [SocketsHttpHandler.SslOptions.TargetHost](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslclientauthenticationoptions.targethost?view=netstandard-2.1#System_Net_Security_SslClientAuthenticationOptions_TargetHost).

Is there a way to get at this configuration already?

**Comment by JamesNK** [comment]
Create `SocketsHttpHandler`, configure it how you want, then pass it to gRPC channel using `GrpcChannelOptions.HttpHandler` property.

**Comment by jayd16** [comment]
Hmm I'm using Unity's new `.net standard 2.1` support which uses the older HttpClientHandler.  

There also seem to be Unity related issues.  I confirmed that customizing the HttpClientHandler.ServerCertificateCustomValidationCallback works fine in a normal .net5.0 app.

I'll close this ticket and move the discussion to https://github.com/grpc/grpc-dotnet/issues/1309.
