### ISSUE TITLE
How to check for Grpc OK status code in Grpc client

### ISSUE THREAD

**Issue by sadashivjp** [grpc/grpc-dotnet#1363]
I got to know that, Grpc OK status code is returned when there is no error and RPC is successful. But, how can Grpc client can check for StatusCode == StatusCode.OK after getting the awaited result of Grpc service call.
`var result = await client.SayHelloAsync(new HelloRequest {});`

Is there a way in Grpc-dotnet to return OK status code or any other status code from Grpc service without raising any RPC exception? Or any way through which Grpc client can inspect status code returned from Grpc service on success?

**Comment by JamesNK** [comment]
The simple answer is no. Throwing `RpcException` is the primary way to get the status code.

The status code is available on the call so you can do something like this:

```cs
var call = client.SayHelloAsync(new HelloRequest {});
var result = await client.ResponseAsync; // This could still throw RpcException
var statusCode = client.GetStatus().StatusCode;
```
