### ISSUE TITLE
Nginx Upstream timeout

### ISSUE THREAD

**Issue by xTeare** [grpc/grpc-dotnet#1364]
So, i've got these things : a client, a server, nginx. They all run on the same machine.

The client does some network scanning and is supposed to send it's results to the server.
The server is supposed to take the scanning-results and put them into a database. 
The server is based on ASP.Net.

The client and server use the following packages
- grpc-dotnet
- [protobuf-net](https://github.com/protobuf-net/protobuf-net)

 Both also use the SSL certificate and generally they both work as expected.

The nginx proxy is supposed to be used as a Reverse-Proxy -> Clients only need to know one Endpoint for all their Requests. Nginx is only configured to pass grpc requests, nothing else.

First of all, almost all grpc requests do work. But they stop working, if the request gets too big. I dont know the exact size, but it must be under 180kb.

(180kb is the size of the scan results.In a test, sending half of these results succeded, where sending all did not. Custom test data (with the same class of course) did show the same results. If they got too big, it stopped working)

Without nginx, there are no errors while sending data from client to server. With nginx however, the client does recieve a HTTP 504 error.

Do you guy's have heard of this behaviour / know how to fix this ? 

### Resources
[Original Question with just C# implementations ](https://stackoverflow.com/questions/68547210/c-sharp-nginx-upstream-timed-out)
[New Question by my Co-Worker with additional Java implementation](https://stackoverflow.com/questions/68708438/grpc-communication-stucks-using-nginx)
[Github Repository with both C# and Java Implementations aswell as nginx](https://github.com/xTeare/GrpcAndNGINX)
[/r/nginx Post](https://www.reddit.com/r/nginx/comments/otwhma/c_grpc_with_nginx_does_not_work/)
[/r/csharp Post](https://old.reddit.com/r/csharp/comments/otwgta/grpc_with_nginx_does_not_work/)

Thanks in advance
xTeare

**Comment by JamesNK** [comment]
I haven't heard of this before. I'm not familiar with using nginx and gRPC.

**Comment by JamesNK** [comment]
I looked at your logs and it appears that nginx is timing out while sending the request to the gRPC server.

```
2021/08/04 17:33:05 [warn] 5528#26564: *1 upstream server temporarily disabled while sending request to upstream, client: 127.0.0.1, server: , request: "POST /greet.Greeter/SayHello HTTP/2.0", upstream: "grpcs://[::1]:5001", host: "localhost:5002"
2021/08/04 17:33:05 [debug] 5528#26564: *1 free rr peer failed: 029A1C08 0
2021/08/04 17:33:05 [error] 5528#26564: *1 upstream timed out (10060: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat) while sending request to upstream, client: 127.0.0.1, server: , request: "POST /greet.Greeter/SayHello HTTP/2.0", upstream: "grpcs://[::1]:5001", host: "localhost:5002"
```

What are your server logs? See https://docs.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-5.0#grpc-services-logging for information about configuring server logging.

**Comment by xTeare** [comment]
Hey James,

seems like there is a Bug within nginx : https://trac.nginx.org/nginx/ticket/2229
