### ISSUE TITLE
"Grpc.Tools v2.39.0-pre1" error with: GrpcServices="Client" Access="Internal" (.NET 6 prev. 6 & 7)

### ISSUE THREAD

**Issue by JeepNL** [grpc/grpc-dotnet#1367]
FYI/Question

_(I'm using .NET 6 Preview 7)_

**Grpc.Tools v2.39.0-pre1** was released some time ago and I haven't upgraded from **v2.38.1** because using it results in errors when using (_in .csproj_):

`<Protobuf Include="Protos\greeter.proto" GrpcServices="Client" Access="Internal" />`

**Errors: (2)**
 * Protos/greeter.proto: Unknown generator option: internal_access	

When I delete `Access="Internal"` another error pops up:
 * Protos/greeter.proto: Unknown generator option: no_server

When I delete both `GrpcServices="Client" Access="Internal"` everything seems to work okay.

All the other gRPC Nuget packages have now 2.39-pre1 releases and now I'm wondering if the `GrpcServices="Client" Access="Internal"` aren't necessary anymore. Can I just delete it?

**Comment by adityamandaleeka** [comment]
This is a known issue that's been fixed and will come out next release. For now, please use 2.38.

**Comment by JeepNL** [comment]
Okay, and thank you for your reply!
