### ISSUE TITLE
Grpc channel closing too soon

### ISSUE THREAD

**Issue by sunkararp** [grpc/grpc-dotnet#1380]
Dotnet Core 5.0
Grpc version 2.38.0
AKS Kubernetes version: 1.20.7

In gRpc streaming, our service writes following to the client
- Write header (at least one protobuf message)
- Write message (multiple protobuf messages from multiple thread)
- Write a footer (at least one protobuf message)

Out service was able to stream almost around 100K messages to the client successfully,  **except footer message wasn't sent to the client**. We see **Cannot write to the response body, the response has completed** error message below in the GRPC open elemetry instrumentation logs (see below for complete entry).  However, if we introduce a artificial sleep about 10 seconds after sending footer message, client was receiving the footer message as well.

Question: Does anyone aware of this issue?

Channel creation code snippet
```
private Channel<T> _channel = Channel.CreateUnbounded<T>(
	new UnboundedChannelOptions
	{
		SingleWriter = false,
		SingleReader = true,
	});
```

Writing footer to the channel  code snippet
```
private async Task WriteFooterAsync(string shortDes, string longDes, bool success)
{
    -----     REDACTED     -----

    await _queue.WriteAsync(
       message,
        _context.CancellationToken).ConfigureAwait(false);

    // Temprary hack to handle channel closing too soon
    // "Cannot write to the response body, the response has completed."

    Thread.Sleep(10 * 1000);
}
```

GRPC OpenTelemetry trace log
```
Activity.Id:          00-a8a71ffdef37a7ec583a2c5e031f96fe-d5118f68f670ed4c-01
Activity.ParentId:    00-a8a71ffdef37a7ec583a2c5e031f96fe-877620c7e6bce468-01
Activity.ActivitySourceName: OpenTelemetry.Instrumentation.AspNetCore
Activity.DisplayName: REDACTED.v1.QueryFrontdoor/GetSearchProStream
Activity.Kind:        Server
Activity.StartTime:   2021-08-11T04:42:00.1086956Z
Activity.Duration:    00:00:00.2725493
Activity.TagObjects:
    http.host: 10.200.32.233
    http.method: POST
    http.path: /REDACTED.v1.QueryFrontdoor/GetSearchProStream
    http.url: https://10.200.32.233:443/REDACTED.v1.QueryFrontdoor/GetSearchProStream
LogRecord.TraceId: a8a71ffdef37a7ec583a2c5e031f96fe
    http.user_agent: grpc-python/1.39.0 grpc-c/18.0.0 (linux; chttp2)
LogRecord.SpanId: c67812c9a778fe47
    http.status_code: 200
    rpc.system: grpc
    net.peer.ip: 10.200.16.191
LogRecord.Timestamp: 2021-08-11T04:42:00.3812994Z
    net.peer.port: 43668
LogRecord.EventId: ErrorSendingMessage
    otel.status_code: UNSET
LogRecord.CategoryName: Grpc.AspNetCore.Server.ServerCallHandler
    rpc.service: REDACTED.v1.QueryFrontdoor
LogRecord.LogLevel: Information
    rpc.method: GetSearchProStream
LogRecord.TraceFlags: Recorded
    rpc.grpc.status_code: 0
LogRecord.State:  Error sending message.
Resource associated with Activity:
    service.name: QueryFrontdoor
LogRecord.Exception: Cannot write to the response body, the response has completed.
Object name: 'HttpResponseStream'.
    service.instance.id: c18da8ba-2b5e-4911-9cbd-a33e43665be5
Resource associated with LogRecord:
```

**Comment by JamesNK** [comment]
The problem is you're writing to the queue and then finishing the call on the server by allowing the gRPC method to exit.

You have to wait until after the item has been read on the other side of the queue, and the `responseStream.WriteAsync` call has returned. Once that has happened then it is safe to allow the server method to exit.

**Comment by sunkararp** [comment]
Thanks for the quick reply.

Code that writes footer is awaiting like below, this goes all the way up to the entry point.
```
 await WriteFooterAsync(...)
```

**Comment by JamesNK** [comment]
If I understand your code correctly, you're awaiting **writing** the item to the queue. You're not awaiting reading the item from the queue and writing it to the response stream.

I'd refactor the code to complete the channel writer when you're done with it, then on the reader side set a TaskCompeletionSource as complete when the end is encountered. The gRPC method would then await the TaskCompleteSource task.

**Comment by sunkararp** [comment]
My queue code is from this issue [579](https://github.com/grpc/grpc-dotnet/issues/579). My understanding was, await WriteFooterAsync (...).ConfigureAwait(false) will make sure gRpc method completes.

**Comment by JamesNK** [comment]
> you're awaiting **writing** the item to the queue

**Comment by sunkararp** [comment]
The class wasn't name correctly.  My WriteFooterAsync calls _queue.WriteAsync which intern writes to the channel like below. As  you can see below there isn't any queue here.

```
public async ValueTask WriteAsync(T message, CancellationToken cancellationToken = default)
{
	await _channel.Writer.WriteAsync(message, cancellationToken);
}
```

The code snippet I'm using from [#579]  is below
```
/// <summary>
/// Wraps <see cref="IServerStreamWriter{T}"/> which only supports one writer at a time.
/// This class can receive messages from multiple threads, and writes them to the stream
/// one at a time.
/// </summary>
/// <typeparam name="T">Type of message written to the stream</typeparam>
public class GrpcStreamResponseQueue<T>
{
	private readonly IServerStreamWriter<T> _stream;
	private readonly Task _consumer;

	private readonly Channel<T> _channel = Channel.CreateUnbounded<T>(
		new UnboundedChannelOptions
		{
			SingleWriter = false,
			SingleReader = true,
		});

	public GrpcStreamResponseQueue(
		IServerStreamWriter<T> stream,
		CancellationToken cancellationToken = default
	)
	{
		_stream = stream;
		_consumer = Consume(cancellationToken);
	}

	/// <summary>
	/// Asynchronously writes an item to the channel.
	/// </summary>
	/// <param name="message">The value to write to the channel.</param>
	/// <param name="cancellationToken">A <see cref="T:System.Threading.CancellationToken" /> used to cancel the write operation.</param>
	/// <returns>A <see cref="T:System.Threading.Tasks.ValueTask" /> that represents the asynchronous write operation.</returns>
	public async ValueTask WriteAsync(T message, CancellationToken cancellationToken = default)
	{
		await _channel.Writer.WriteAsync(message, cancellationToken);
	}

	/// <summary>
	/// Marks the writer as completed, and waits for all writes to complete.
	/// </summary>
	public Task CompleteAsync()
	{
		_channel.Writer.Complete();
		return _consumer;
	}

	private async Task Consume(CancellationToken cancellationToken)
	{
		await foreach (var message in _channel.Reader.ReadAllAsync(cancellationToken))
		{
			await _stream.WriteAsync(message);
		}
	}
}
```

**Comment by JamesNK** [comment]
You need to call CompleteAsync.

**Comment by sunkararp** [comment]
Yes, below is the code snippet of how we are calling CompleteAsync. 
If no Thread.Sleep(10 * 1000) inside WriteFooterAsync, 'Grpc channel closing too soon' error is coming.
Note, this is not a 100% repro.

```
// WriteFooterAsync will sleep for 10 after write the footer
// This is to workaround 'Grpc channel closing too soon' issue
await WriteFooterAsync(...).ConfigureAwait(false);

// Signal end of writing
await CompleteAsync(...).ConfigureAwait(false);
```

**Comment by sunkararp** [comment]
Could this be our client which  is JupyterHub notebook issue?

**Comment by JamesNK** [comment]
I don't know.

I need [client and server logs](https://docs.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-5.0) or a simple reproduction to know more.

**Comment by sunkararp** [comment]
Your earlier suggestion calling CompleteAsync fixed.
