### ISSUE TITLE
Report info about .NET version and platform in user-agent 

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc-dotnet#1392]
We've recently added info about .NET version to Grpc.Core: https://github.com/grpc/grpc/pull/25889, so the user-agent string in Grpc.Core looks sth like this: `grpc-csharp/2.38.0-dev (.NET 5.0.0; CLR 5.0.0; netstandard2.0; x64) grpc-c/16.0.0 (osx; chttp2)`

Currently the user-agent string of grpc-dotnet is very basic (e.g. `grpc-dotnet/2.36.0.0`) and there are situations in which .NET version info comes very handy (and platform like e.g. 'linux/windows/osx')

**Comment by JamesNK** [comment]
I believe the SignalR .NET client also logs some extra information. We could look at it for ideas.

**Comment by jtattermusch** [comment]
@captainsafia this looks like a good first issue to get familiar with the codebase - did you wanna look into implementing it?

**Comment by jtattermusch** [comment]
> The first chunk of data: `(.NET 5.0.0; CLR 5.0.0; netstandard2.0; x64)` seems like it would useful. The later c-core info would be skipped in grpc-dotnet.

I think the CLR info is more useful when on legacy .NET Framework, on .NET Core and later it likely doesn't provide much value. But since we want to support .NET Framework for some scenarios (grpc client over WinHttp2 and grpc-web), it probably still makes sense to include it.

One important part that's available in Grpc.Core under the "grpc-c" part of the user string is the platform (e.g. "linux", "windows", "osx", but also other values such as "ios" or "android"). So we should count on including that info in the grpc-dotnet user agent string as well (to at least be able to differentiate between linux/windows/osx - and we'll have to see what string to provide for more interesting platforms such as android/ios/xamarin/blazor etc.). 

> 
> I believe the SignalR .NET client also logs extra information in its user-agent. We could look at it for other useful data to include for diagnostics.


An  exma
