### ISSUE TITLE
"Detected package downgrade: Microsoft.NETCore.Platforms" when attempting to install Grpc.AspNetCore.Server from NuGet.

### ISSUE THREAD

**Issue by daltonks** [grpc/grpc-dotnet#140]
My project has 3.0.0-preview.19073.11 installed, and there is no Microsoft.NETCore.Platforms 3.0.0-preview3.19115.9 on NuGet. Because of this, I receive the error below when attempting to install Grpc.AspNetCore.Server 0.1.19.pre-1.

`Detected package downgrade: Microsoft.NETCore.Platforms from 3.0.0-preview3.19115.9 to 3.0.0-preview.19073.11. Reference the package directly from the project to select a different version. `

**Comment by daltonks** [comment]
Sorry, accidentally hit enter before filling in information. Doing that now.

**Comment by JunTaoLuo** [comment]
This should be resolved once the 3.0 preview3 SDK is available, which should happen shortly. The current package requires a nightly SDK.

**Comment by daltonks** [comment]
Thank you, installing a daily SDK fixes this issue!

**Comment by shirhatti** [comment]
As an FYI, preview3 is now available- https://dotnet.microsoft.com/download/dotnet-core/3.0
