### ISSUE TITLE
Authorization vs authorization: Cross platform authorization header

### ISSUE THREAD

**Issue by sunkararp** [grpc/grpc-dotnet#1403]
Dotnet gRpc expects 'Authorization' (upper case first letter).

While this works fine with DOTNET clients but Python clients can only send 'authorization'  (lower case first letter) header. 
We are getting below error, if we try to send 'Authorization' header using Python client.
```
validate_metadata: {"created":"@1630971128.039261428","description":"Illegal header key","file":"src/core/lib/surface/validate_metadata.cc","file_line":44,"offset":0,"raw_bytes":"41 75 74 68 6f 72 69 7a 61 74 69 6f 6e 'Authorization'\u0000"}
```

Is there any way, I can make my DOTNET CORE gRpc service recognize 'authorization' header?

**Comment by sunkararp** [comment]
Any workaround, can someone please help us here.

**Comment by adityamandaleeka** [comment]
Can you please file this issue at http://github.com/grpc/grpc ? The error isn't coming from grpc-dotnet.

**Comment by sunkararp** [comment]
Sure, I can file a bug.

Here is the [link](https://github.com/Juniper/grpc-c/issues/38) someone else reported the same issue, although it wasn't clear platform.

**Comment by adityamandaleeka** [comment]
@sunkararp It was unclear because your initial message indicated that the error was coming from src/core/lib/surface/validate_metadata.cc which is part of grpc.core. However you said in your latest message that you're using Grpc.AspNetCore.

Can you share a repro so we can take a look?

**Comment by sunkararp** [comment]
Opened a formal bug, see #1417

Happy to provide any further details.

**Comment by JamesNK** [comment]
Closing to avoid dup with #1417
