### ISSUE TITLE
Template improvements

### ISSUE THREAD

**Issue by JunTaoLuo** [grpc/grpc-dotnet#141]
- [x] ~~Fix docker support cc @shirhatti~~
- [x] Missing types. Pending work on design-time build: https://github.com/grpc/grpc-dotnet/issues/17

Server
- [x] Request body rate limit requirements for client streaming calls: https://github.com/aspnet/AspNetCore/issues/7635
- [x] Https by default
  - Intention is to use PKI for managed server and client. Interop with c core client and server will need design (static utility/extension methods?).
- [x] Add Http endpoint as fallback for non-gRPC requests
  - Dependent on Https support as well. We need to serve HTTP/2 requests only which requires HTTPS to be enabled, which means macOS will fail. Current templates use H2C which is not used by browsers.
- [x] Clean up appSettings.json to remove unnecessary configurations. The intended protocols to support is Http2 only which is not the default.

Client
- [x] Service discovery, including ports and shared proto files
    - Docker specific solution
    - Outside of docker, no solution discussed
    - Will use a CLI to do this instead

**Comment by shaggygi** [comment]
Not sure if this is the issue to add, but noticed there is a "Page Not Found" when creating new gRPC project in VS 2019 and .NET Core v3 P5.

The created project has the doc link below in Startup.cs file how to create client.

> // Communication with gRPC endpoints must be made through a gRPC client.
> // To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909

**Comment by JamesNK** [comment]
Thanks for the heads up. I've logged a bug to fix this in our docs - https://github.com/aspnet/AspNetCore.Docs/issues/12633

**Comment by JunTaoLuo** [comment]
Follow up at https://github.com/grpc/grpc-dotnet/issues/358
