### ISSUE TITLE
Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="invalid HTTP version parsed") 

### ISSUE THREAD

**Issue by krikke999** [grpc/grpc-dotnet#1415]
We created microservices with Asp.Net Core based on the architecture defined in eshopcontainer on [Github](https://github.com/dotnet-architecture/eShopOnContainers).
All REST calls and the triggered GRPC calls work under normal load. (1 req/sec avg).
When I run some jmeter test to subset of the available API calls, one microservice goes into a failure mode only for that single method and will not recover unless I kill the pod in my AKS cluster.

The exception thrown by the failing GRPC method: 

```
Error thrown by /Measurement.MeasurementTypeProto/GetConfiguredMeasurementTilesByGroupForUser.
││ Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="invalid HTTP version parsed")
││    at Measurement.API.Grpc.MeasurementTypeGrpcService.GetConfiguredMeasurementTilesByGroupForUser(GetConfiguredMeasurementTilesByGroupForUserRequest request, ServerCallContext context
││    at Grpc.Shared.Server.UnaryServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest resolvedRequest, ServerCallContext resolvedContext)
││    at Grpc.Shared.Server.UnaryServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest resolvedRequest, ServerCallContext resolvedContext)
││    at Measurement.API.Configuration.GrpcLoggerInterceptor.UnaryServerHandler[TRequest,TResponse](TRequest request, ServerCallContext context, UnaryServerMethod`2 continuation)
```

We are using .Net Core 3.1 with the following nugets:
- Grpc.AspNetCore 2.39
- Grpc.Core.Api 2.40
- Grpc.Net.Client 2.39
- Grpc.Net.ClientFactory 2.39
- Grpc.Tools 2.40
- Google.Protobuf 3.18

Running on Azure AKS 1.19.11 B4MS single node.
We use mcr.microsoft.com/dotnet/core/sdk:3.1-alpine as build image mcr.microsoft.com/dotnet/core/runtime-deps:3.1-alpine and use that as target image.

We also added this to the build process to run Grpc.Tools on alpine based images:

```
# Fix Grpc.Tools: Cannot run protoc in alpine based dotnet SDK => https://github.com/grpc/grpc/issues/18338
RUN apk update \
    && apk --no-cache add ca-certificates wget \
    && wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
    && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.30-r0/glibc-2.30-r0.apk \
    && apk add glibc-2.30-r0.apk
```

What can cause this error?

I forgot to mention that we use mTLS via LinkerD and use the following code to allow insecure communication:

```
services.AddGrpcClient<KnowledgeBaseProto.KnowledgeBaseProtoClient>(o =>
{
    AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
    AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2Support", true);                
    o.Address = new Uri(Configuration.GetSection(GrpcUrls.SectionName).Get<GrpcUrls>().Profile);
});
```

Also tried without LinkerD with insecure communication => same result => stuck

**Comment by krikke999** [comment]
An update:

We just upgraded the entire code base from .net core 3.1 to .net 5.0 and upgraded all the nuget packages to the latest versions.
Problem still exists but we get another error now: 

```
Error starting gRPC call. HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while HTTP/2 is not enabled.
```

Full stack:

```
Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while HTTP/2 is not enabled.", DebugException="System.Net.Http.HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while HTTP/2 is not enabled.
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Grpc.Shared.TelemetryHeaderHandler.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
  at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult
  at Measurement.API.Grpc.MeasurementTypeGrpcService+<GetConfiguredMeasurementTilesByGroupForUser>d__10.MoveNext
    C:\Projects\Selfcare\selfcare-2.0\src\Services\Measurement\Measurement.API\Grpc\MeasurementTypeGrpcService.cs:99
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
  at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult
  at Grpc.Shared.Server.UnaryServerMethodInvoker`3+<ResolvedInterceptorInvoker>d__3.MoveNext
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
  at Grpc.Shared.Server.UnaryServerMethodInvoker`3+<ResolvedInterceptorInvoker>d__3.MoveNext
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
  at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult
  at Measurement.API.Configuration.GrpcLoggerInterceptor+<UnaryServerHandler>d__2`2.MoveNext
 
```

We have a BFF listening to HTTP requests => calls underlying microservice Measurement.API via GRPC => Measurement.API calls Profile.API and Dashboard.Api via Grpc.

Service clients are registered like: (both clients are pointing to same microservice endpoint Profile

```
services.AddGrpcClient<DashboardProto.DashboardProtoClient>(o =>
            {
                o.Address = new Uri(Configuration.GetSection(GrpcUrls.SectionName).Get<GrpcUrls>().Profile);
            });

services.AddGrpcClient<ProfileProto.ProfileProtoClient>(o =>
            {
                o.Address = new Uri(Configuration.GetSection(GrpcUrls.SectionName).Get<GrpcUrls>().Profile);
            });

```

**Comment by JamesNK** [comment]
You're hitting this error: https://github.com/dotnet/runtime/blob/release/5.0/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L349-L353

It seems like the most likely reason that HTTP/2 is disabled is the server isn't configured to support HTTP/2 - https://github.com/dotnet/runtime/blob/release/5.0/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L668

Have you verified your server has HTTP/2 enabled? Also, if you aren't using TLS then a port can't use HTTP/1.1 and HTTP/2. It can only use HTTP/2.

**Comment by krikke999** [comment]
> You're hitting this error: https://github.com/dotnet/runtime/blob/release/5.0/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L349-L353
> 
> It seems like the most likely reason that HTTP/2 is disabled is the server isn't configured to support HTTP/2 - https://github.com/dotnet/runtime/blob/release/5.0/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L668
> 
> Have you verified your server has HTTP/2 enabled? Also, if you aren't using TLS then a port can't use HTTP/1.1 and HTTP/2. It can only use HTTP/2.

Thanks @JamesNK for your feedback, but everything works under normal load, once the requests increases that error pops up. => seems more like a threading issue?

**Comment by krikke999** [comment]
For .Net 5.0 I found the issue => there was only one class left that still had 3.1 wrappers to support unencrypted GRPC calls:

(based on eshopContainer [GrpcServiceCaller](https://raw.githubusercontent.com/dotnet-architecture/eShopOnContainers/dotnet3-migration/dev-dotnet3/src/ApiGateways/Web.Bff.Shopping/aggregator/Services/GrpcCallerService.cs))
```
public class XXXClientService : IXXXClientService
    {
        private readonly XXXClient _client;

        public XXXClientService(
            IOptions<CoreSupplierGrpcUrls> optionsCoreSupplierGrpcUrls)
        {
            AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
            AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2Support", true);

            var channel = GrpcChannel.ForAddress(optionsCoreSupplierGrpcUrls.Value.Mailing);
            _client = new XXXClient(channel);

            AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", false);
            AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2Support", false);
        }

       // .....
```
It seems that the AppContext.SetSwitch is not thread safe to wrap the GrpcChannel.ForAddress with?
That single class, that was called in a loop in the main REST call under load tests, was breaking that specific grpc service host.

Now all places usage AddGrpcClient without the AppContext.SetSwitch and everything seems to work correctly under load.
Not sure if AddGrpcClient the best way to use in a application with peak loads, because it generates a new Channel per container resolve...

**Comment by JamesNK** [comment]
> It seems that the AppContext.SetSwitch is not thread safe to wrap the GrpcChannel.ForAddress with?

`AppContext.SetSwitch` is static. As soon as there are multiple threads then you'll have this problem. Don't use these switches like this.
