### ISSUE TITLE
Implementing a grpc server in .net standard class library

### ISSUE THREAD

**Issue by asheesh1996** [grpc/grpc-dotnet#1419]
How can I implement a server using grpc-dotnet in a class library like we used to implement in earlier versions??
```

using System;
using System.Threading.Tasks;
using Grpc.Core;
using Helloworld;

namespace GreeterServer
{
    class GreeterImpl : Greeter.GreeterBase
    {
        // Server side handler of the SayHello RPC
        public override Task<HelloReply> SayHello(HelloRequest request, ServerCallContext context)
        {
            return Task.FromResult(new HelloReply { Message = "Hello " + request.Name });
        }
    }

    class TestServer
    {
        const int Port = 30051;

        public TestServer()
        {
            Server server = new Server
            {
                Services = { Greeter.BindService(new GreeterImpl()) },
                Ports = { new ServerPort("localhost", Port, ServerCredentials.Insecure) }
            };
            server.Start();

            Console.WriteLine("Greeter server listening on port " + Port);
        }
        ~TestServer()
        {
          server.ShutdownAsync().Wait();
        }
    }
}
```

**Comment by JamesNK** [comment]
You can't. Grpc.AspNetCore requires ASP.NET Core.

**Comment by asheesh1996** [comment]
https://grpc.io/blog/grpc-csharp-future/ This makes no sense

**Comment by hawkerm** [comment]
If it's possible to use [grpc web on .NET Standard 2.0](https://docs.microsoft.com/en-us/aspnet/core/grpc/netstandard), is there not a compatible server for the same?

What if I want a console app or UWP app to be a server as part of some service or a game? Being tied strictly to ASP seems really limiting compared to other scenarios in the .NET ecosystem.

Seems like it'd be easier to write a grpc server in some other language to host as a separate process than being able to keep my client and backend both in .NET. ☹

**Comment by JamesNK** [comment]
> If it's possible to use grpc web on .NET Standard 2.0, is there not a compatible server for the same?

It doesn't make a difference. A gRPC server app needs a server to run on. ASP.NET Core gives you the choice of Kestrel/IIS/HTTP.sys.

> What if I want a console app or UWP app to be a server as part of some service or a game? Being tied strictly to ASP seems really limiting compared to other scenarios in the .NET ecosystem.

An ASP.NET Core website is a console app by default. For projects with other SDK types, add a framework reference to get the ASP.NET Core types:

```xml
<FrameworkReference Include="Microsoft.AspNetCore.App" />
```

I don't think that will work in UWP. UWP won't have all the APIs required to host a website (sockets, TLS, etc)

**Comment by nathan130200** [comment]
> You can't. Grpc.AspNetCore requires ASP.NET Core.

For which reason gRPC forces us to use ASPNet Core???

**Comment by JamesNK** [comment]
A gRPC server needs a server to run on. Saying "just make a new server" is unrealistic. HTTP/2 is a very complicated protocol. A new server would be slower, less secure and less scalable than Kestrel because it will have a faction of the resources.

Can you use Grpc.AspNetCore in a console app? Yes.
Can you use Grpc.AspNetCore in a WinForms app? Yes.
Can you use Grpc.AspNetCore in a WPF app? Yes.
Can you use Grpc.AspNetCore in a WinUI 3 app? Yes.
Can you use Grpc.AspNetCore in a UWP app? No, ASP.NET Core isn't supported here. In this case you might need to use Grpc.Core.

**Comment by HppZ** [comment]
> You can't. Grpc.AspNetCore requires ASP.NET Core.

This design is confusing!!!
