### ISSUE TITLE
Determining if a channel is secure when client-side load balancing is used. 

### ISSUE THREAD

**Issue by erni27** [grpc/grpc-dotnet#1421]
Hi there, 
I was trying to configure `StaticResolverFactory` and use it along with the configured `ChannelCredentials` for the channel including `CallCredentials`.
```csharp
var factory = new StaticResolverFactory(addr => new[]
{
    new DnsEndPoint("localhost", 80),
    new DnsEndPoint("localhost", 81)
});

var services = new ServiceCollection();
services.AddSingleton<ResolverFactory>(factory);

var credentials = CallCredentials.FromInterceptor((context, metadata) =>
{
    if (!string.IsNullOrEmpty(_token))
    {
        metadata.Add("Authorization", $"Bearer {_token}");
    }
    return Task.CompletedTask;
});

var channel = GrpcChannel.ForAddress(
    "static:///my-example-host",
    new GrpcChannelOptions
    {
        ChannelCredentials = ChannelCredentials.Create(new SslCredentials(), credentials),
        ServiceProvider = services.BuildServiceProvider()
    });
var client = new Greet.GreeterClient(channel);
```

But it doesn't work. I believe that's caused by the guard inside the `ReadCredentials` method.
https://github.com/grpc/grpc-dotnet/blob/bb9284fb62bc2519b77bd7816436aed9fd6521d3/src/Grpc.Net.Client/Internal/GrpcCall.cs#L760-L785

During the execution the address points to `static` scheme instead of `https`. Maybe it would be better to use `IsSecure` 
property since it was assigned during the initialization (in a more precise manner) instead of checking the scheme. 
Is there any explanation for the current behavior?

**Comment by JamesNK** [comment]
Yes, you're right. This should be fixed.
