### ISSUE TITLE
Throwing RpcException with OK status code

### ISSUE THREAD

**Issue by janseris** [grpc/grpc-dotnet#1425]
Hello. I am currently trying out some extensive tests of the gRPC if it can fit the needs of our company.
I have developed a .NET 5 (Grpc.Net NuGet package) server and .NET 5 (Grpc.Net NuGet package) client and .NET Framework client (Grpc.Core NuGet package) running on HTTP/2 and without TLS.

When I throw a RpcException in the server method implementation, it causes RpcException handling in the client.
This allows me to send various status codes. 
However sending a RpcException with OK status code results in another exception with Internal status code received on the client because it tries to deserialize the "response" which is not in fact a response.
The detail message of this RpcException is: "Failed to deserialize response message.".

The behavior is the same in both .NET Framework client (Grpc.Core) and .NET 5 client (Grpc.Net).

Is this intended behavior because I am abusing the OK status usage? 

This Go implementation mentions that there is an invariant that the result is always OK or an error but never a combination of the two: https://pkg.go.dev/google.golang.org/grpc/status

**Comment by JamesNK** [comment]
> The detail message of this RpcException is: "Failed to deserialize response message.".

That's expected. When `RpcException` is thrown then there is no response message. A successful RPC call needs a response message.
