### ISSUE TITLE
React to Response.StartAsync change

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#144]
StartAsync behavior is changing with https://github.com/aspnet/AspNetCore/issues/7779

Delay calling StartAsync when buffering on the server so user can send HTTP headers afterwards.

**Comment by davidfowl** [comment]
Well no, if you do that then it'll be inefficient. You want to keep calling StartAsync so that on kestrel, it'll be optimized.

**Comment by JamesNK** [comment]
@jtattermusch What is the current behavior of c-core when it comes to buffering? I wanted to test out whether it prevents headers from being sent but in the following code it hangs on the first `await WriteAsync(message)`.

```cs
public override async Task SayHellos(HelloRequest request, IServerStreamWriter<HelloReply> responseStream, ServerCallContext context)
{
    responseStream.WriteOptions = new WriteOptions(WriteFlags.BufferHint);

    for (int i = 0; i < 3; i++)
    {
        var message = $"How are you {request.Name}? {i}";
        await responseStream.WriteAsync(new HelloReply
        {
            Message = message,
            Timestamp = Timestamp.FromDateTime(DateTime.UtcNow)
        });
    }

    await responseStream.WriteAsync(new HelloReply
    {
        Message = $"Goodbye {request.Name}!",
        Timestamp = Timestamp.FromDateTime(DateTime.UtcNow)
    });

    var metadata = new Metadata();
    metadata.Add("test", "value!");

    await context.WriteResponseHeadersAsync(metadata);
}
```

**Comment by jkotalik** [comment]
@JamesNK this was merged just now.

**Comment by jtattermusch** [comment]
> @jtattermusch What is the current behavior of c-core when it comes to buffering? I wanted to test out whether it prevents headers from being sent but in the following code it hangs on the first `await WriteAsync(message)`.
> 
> ```cs
> public override async Task SayHellos(HelloRequest request, IServerStreamWriter<HelloReply> responseStream, ServerCallContext context)
> {
>     responseStream.WriteOptions = new WriteOptions(WriteFlags.BufferHint);
> 
>     for (int i = 0; i < 3; i++)
>     {
>         var message = $"How are you {request.Name}? {i}";
>         await responseStream.WriteAsync(new HelloReply
>         {
>             Message = message,
>             Timestamp = Timestamp.FromDateTime(DateTime.UtcNow)
>         });
>     }
> 
>     await responseStream.WriteAsync(new HelloReply
>     {
>         Message = $"Goodbye {request.Name}!",
>         Timestamp = Timestamp.FromDateTime(DateTime.UtcNow)
>     });
> 
>     var metadata = new Metadata();
>     metadata.Add("test", "value!");
> 
>     await context.WriteResponseHeadersAsync(metadata);
> }
> ```

WriteFlag.BufferHint only affects message writes:
https://github.com/grpc/grpc/blob/aa94bab5893751284e3a75dfc42e95278b3f2334/include/grpc/impl/codegen/grpc_types.h#L426  (send_message operation in C-core terminology)

There might be a way to cork initial metadata too using this flag
https://github.com/grpc/grpc/blob/aa94bab5893751284e3a75dfc42e95278b3f2334/include/grpc/impl/codegen/grpc_types.h#L447, but I've never used it and it's not exposed in the C# layer.

It is not clear to me why your snippet hangs (I don't see anything bad with it except trying to invoke WriteReponseHeadersAsync  after calling WriteAsync will throw as that's forbidden).

**Comment by jtattermusch** [comment]
@JamesNK  I ran a few experiments as of why the WriteAsync() with buffer hint hangs.
The reason seems to be that the first WriteAsync() also sends the response metadata by default which for some reasons causes trouble.
I have a repro here: https://github.com/grpc/grpc/pull/18609 (note that if context.WriteResponseHeadersAsync() is run in advance, everything works as expected).

**Comment by JamesNK** [comment]
Blocked on an answer for it buffering and headers interact in Grpc.Core.

**Comment by JunTaoLuo** [comment]
We don't plan on doing further work on this right now. We can always revisit this decision in the future.
