### ISSUE TITLE
GRPC JSON transcoding : query parameters not "discovered"

### ISSUE THREAD

**Issue by christopheblin** [grpc/grpc-dotnet#1450]
This is about #167  and https://docs.microsoft.com/en-us/aspnet/core/grpc/httpapi?view=aspnetcore-5.0

Given the following proto

```
syntax = "proto3";

option csharp_namespace = "user_management";

import "google/api/annotations.proto";

service UserListService {
    //List users 
    rpc ListUsers (ListUserRequest) returns (UserList) {
        option (google.api.http) = {
            get: "/v1/users";
        };
    }
}

message ListUserRequest {
    int32 page_size = 1;
    int32 page_nb = 2;
    string order_by = 3;
    
    string name = 4;
}

message UserList {
    int32 total = 1;
    int32 page_nb = 2;
    repeated UserItem data = 3;
}

//Partial details for a user
message UserItem{
	string id = 1;
	string name = 2;
}
```

I would expect that ListUserRequest is exposed as query parameters

Indeed, calling http://localhost:5000/v1/users?page_size=10&page_nb=1 will correctly submit the parameters to the C# class

However, the generated swagger as explained at https://docs.microsoft.com/en-us/aspnet/core/grpc/httpapi?view=aspnetcore-5.0#enable-swaggeropenapi-support  does not contain them

![Capture d’écran 2021-10-13 224905](https://user-images.githubusercontent.com/11044877/137210596-a31c5b1e-37e9-4c52-9098-dd9c67b12877.png)

**Comment by TXP-AlbertPucciani** [comment]
Having this work would be immensely useful. I'm currently running into the same issue, so I've been using BloomRPC client, but swagger is much more friendly.

**Comment by christopheblin** [comment]
Just to mention that I do not use this plugin anymore

The first workaounf was to declare 2 apps inside my program.cs : an OpenApi app and a grpc app

Inside the grpc app, i use the code-first approach

Inside the openapi app, I use builder.AddControllers and AddSwaggerGen

Both the grpc and the openapi controlers are calling the same business logic under the hood

That was working great if you need to provide the same services internally (grpc) and externally (openapi)

In the end, i now switched to a Backend for frontend approach so each frontend have its own api layer and calls one (or more) grpc service under the hood and I use grpccurl to to talk with grpc services in a more friendly way (not as friendly as swagger, but grpcui does not work for me, I'm going to try bloomrpc asap)

**Comment by JamesNK** [comment]
This is done in the OpenAPI integration for gRPC JSON transcoding:

https://learn.microsoft.com/en-us/aspnet/core/grpc/json-transcoding-openapi?view=aspnetcore-7.0
