### ISSUE TITLE
Allow clients to adding a prefix for user-agent string

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc-dotnet#1468]
Grpc.Core currently allows adding a user-configured prefix to user agent string. This feature is used by Google API client libraries.

In Grpc.Core, this is configured via the "grpc.primary_user_agent" and "grpc.secondary_user_agent" channel options,
so we'd need a different way of configuring it for grpc-dotnet client, but it should still be possible to configure this behavior.
https://github.com/grpc/grpc/blob/882cc1259effd1f9d2a34e6abd49d438b85f8bb1/src/csharp/Grpc.Core/Channel.cs#L311

Usage in Google API clients e.g.
https://github.com/googleapis/gax-dotnet/blob/6a6dd811c11d9fdfeb6a9aaa5fdba24ec32b2b4b/Google.Api.Gax.Grpc.GrpcCore/GrpcCoreAdapter.cs#L69

**Comment by jtattermusch** [comment]
CC @JamesNK @jskeet

**Comment by JamesNK** [comment]
Seems like an odd thing to do but I guess an option could get added to GrpcChannelOptions to specify a UA prefix.

**Comment by jtattermusch** [comment]
I don't think it's odd. If grpc is used as a transport layer for a higher-level library, it's quite normal for that library to add itself to the user agent string (in the same way grpc-csharp adds itself as a prefix for the C-core user agent string).

E.g. a client library for Cloud Bigtable client might generate:
`cbt-csharp/v1.0.0 grpc-csharp/1.15.0 grpc-c/6.0.0 (windows; chttp2; glider)`

**Comment by JamesNK** [comment]
I thought about this more and I don't believe any code changes are required to support this.

A custom `DelegatingHandler` can override the user-agent header and prepend the desired text to it. Then just configure the channel to use the custom delegating handler.

**Comment by jskeet** [comment]
Thanks James - will prototype that when I get a chance.

**Comment by JamesNK** [comment]
I don't think this needs to be a feature in gRPC. Can reopen if new information becomes available.
