### ISSUE TITLE
Is a successful GrpcChannel constructor call enough to be confident in platform support?

### ISSUE THREAD

**Issue by jskeet** [grpc/grpc-dotnet#1469]
I'm writing an adaptation layer allowing customers to use either Grpc.Core or Grpc.Net.Client, ideally with them not having to care at all, but with sufficient control if they _do_ want to care.

I have a prototype where I've got code like this (`GrpcAdapter` is the "adaptation layer" effectively):

```csharp
private static GrpcAdapter CreateDefaultAdapter()
{
    try
    {
        GrpcChannel.ForAddress("https://ignored.com");
        return GrpcNetClientAdapter.Default;
    }
    catch
    {
        return GrpcCoreAdapter.Instance;
    }
}
```

(Just in case folks are interested, we're taking a direct dependency on Grpc.Net.Client, but no dependency on Grpc.Core - the GrpcCoreAdapter accesses the relevant types via compiled expression trees. If the user hasn't got their own dependency on Grpc.Core, the exception message will inform them what they need to do. We'll also probably provide some sort of escape hatch, e.g. via an environment variable, to make it easy to require a specific implementation.)

The above code is only executed once, so I'm definitely not bothered by the performance aspect of relying on an exception.

However, I would like to clarify whether this is a sufficiently reasonable "is this platform supported" check. It's worked in my tests so far, but I'm concerned that possibly the constructor could succeed because *some* level of functionality is available, but not necessarily all of it - e.g. bidi streaming. Am I right to worry, or is Grpc.Net.Client support a binary "yes, everything works" or "no, everything fails" matter?

In an ideal world of course there'd be a nicer way of checking than calling the constructor and catching the exception, but that's a slightly separate matter :)

**Comment by jtattermusch** [comment]
@JamesNK  this is the google api client libraries use case we discussed in our yesterday's sync up.

**Comment by JamesNK** [comment]
On .NET Core 3, .NET 5+: GrpcChannel is created with SocketsHttpHandler as the internal client. However, HTTP/2 can be disabled by an environmental variable.

Other platforms (e.g. .NET Framework, or Xamarin): GrpcChannel will throw an exception with a message that you must configure a HttpHandler on the channel options. On .NET Framework that could be WinHttpHandler (which then has OS requirements that should be validated). Other platforms will need to configure GrpcWebHandler. Code: https://github.com/grpc/grpc-dotnet/blob/e3a2c06639c49f903663aee7acddbc1a7fcc7efd/src/Shared/HttpHandlerFactory.cs#L27-L52

See https://docs.microsoft.com/en-us/aspnet/core/grpc/supported-platforms?view=aspnetcore-5.0#net-grpc-client-requirements

**Comment by jskeet** [comment]
Right - so in all those cases, if it's not supported, it throws an exception, correct? It won't return a valid-looking object that can't be used later? That's what I'm worried about. (And that that expectation is permanent, of course!)

**Comment by JamesNK** [comment]
If a platform reports that SocketsHttpHandler isn't supported then it will error. That doesn't guarantee HTTP/2 will work though. Someone could disable HTTP/2 with an environmental variable, order disable TLS 1.2 in the OS.

For .NET Framework, I think it might be a good idea to have a net462 (or something around there) target that brings in WinHttpHandler and does the OS check for you.

Note that for WinHttpHandler, unary calls are supported in an earlier Windows version than streaming calls. Do you need both?

**Comment by jskeet** [comment]
Hmm. So it's more complex than what I've done so far - that's not terribly unexpected.

In terms of streaming, some APIs need streaming, others don't - this layer doesn't know.

I'll have another think about the best course of action. Thanks for the info.
