### ISSUE TITLE
grpc service sipport in .net 6.0 seems to have problems when publishTrimmed is enabled

### ISSUE THREAD

**Issue by lechgu** [grpc/grpc-dotnet#1477]
### What version of gRPC and what language are you using?
Grpc.AspNetCore, 2.40.0

### What operating system (Linux, Windows,...) and version?
Alpine Linux, from the mcr.microsoft.com/dotnet/runtime-deps:6.0-alpine Docker base image

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.net .6.0

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
Ported a working gRPC service from .net 5.0 to 6.0.

### What did you expect to see?
The service continues to work

### What did you see instead?
Service fails to start, with an unhadled exception:

Unhandled exception. System.ArgumentException: Generic implementation type 'Grpc.AspNetCore.Server.Internal.DefaultGrpcServiceActivator`1' has a DynamicallyAccessedMembers attribute applied to a generic argument type, but the service type 'Grpc.AspNetCore.Server.IGrpcServiceActivator`1' doesn't have a matching DynamicallyAccessedMembers attribute on its generic argument type.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.ValidateTrimmingAnnotations(Type , Type[] , Type , Type[] )
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc-dotnet/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
This happens when compiling with:
dotnet publish Service -c release -r linux-musl-x64 -p:PublishSingleFile=true -p:PublishReadyToRun=true -p:PublishTrimmed=true

Removing the "PublishTrimmed=true" flag seems to be a workaround. However it makes resulting docker image larger, so it would be good if this is fixed.

**Comment by JamesNK** [comment]
This was fixed a couple of days ago. A preview release should be available on NuGet this week or early next week with the fix

https://github.com/grpc/grpc-dotnet/issues/1470
