### ISSUE TITLE
Can't get DNS load balancer to work

### ISSUE THREAD

**Issue by vasicvuk** [grpc/grpc-dotnet#1482]
### What version of gRPC and what language are you using?
Tried 2.39.0-pre1 and 2.40.0-pre1

### What operating system (Linux, Windows,...) and version?

Linux

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)

.Net 3.1.412

### Problem

When I create connection using **dns:///** prefix I get following error:

```
Something went wrong: System.ArgumentException: Address 'dns:///samplee.ns-ondemand.svc.cluster.local' doesn't have a host. Address should include a scheme, host, and optional port. 
```

I followed sample from here:
https://docs.microsoft.com/en-us/aspnet/core/grpc/loadbalancing?view=aspnetcore-6.0#configure-load-balancer

**Comment by JamesNK** [comment]
Can you provide the full exception stack trace?

**Comment by vasicvuk** [comment]
@JamesNK As mentioned I use .Net core 3.1. I see that option is available only for .net 5 and 6 so I will try with .NET 6

**Comment by vasicvuk** [comment]
@JamesNK With .NET 6 i don't have this issue but now I am facing:

```
System.InvalidOperationException: Channel is configured with an HTTP transport doesn't support client-side load balancing or connectivity state tracking. The underlying HTTP transport must be a SocketsHttpHandler with no SocketsHttpHandler.ConnectCallback configured. The HTTP transport must be configured on the channel using GrpcChannelOptions.HttpHandler.
at Grpc.Net.Client.GrpcChannel.ValidateHttpHandlerSupportsConnectivity()
at Grpc.Net.Client.GrpcChannel..ctor(Uri address, GrpcChannelOptions channelOptions)
at Grpc.Net.Client.GrpcChannel.ForAddress(Uri address, GrpcChannelOptions channelOptions)
at Grpc.Net.Client.GrpcChannel.ForAddress(String address, GrpcChannelOptions channelOptions)
```

Probably because of httpClientFactory used

**Comment by vasicvuk** [comment]
When removing the HttpClient DNS resolution started working but now I cannot specify port in which grpc server is running when i specify port it cannot resolve the name as it includes port in resolution

**Comment by vasicvuk** [comment]
@JamesNK  I created a PR resolving the issue, but it involved some refactoring and new tests, so please check it.

https://github.com/grpc/grpc-dotnet/pull/1489

**Comment by JamesNK** [comment]
@vasicvuk I want to double-check my understanding of what you're doing.

You have configured `dns:///samplee.ns-ondemand.svc.cluster.local:8080` because you want to resolve addresses from the DNS at `samplee.ns-ondemand.svc.cluster.local`. Lets say addresses `1.1.1.1` and `1.1.1.2` are returned.

The gRPC client will then send RPC calls to those addresses with port 8080. e.g. `1.1.1.1:8080`

Correct?

**Comment by vasicvuk** [comment]
@JamesNK Yes, that is correct.

**Comment by JamesNK** [comment]
Thanks for reporting this. Will be fixed in the next release.
