### ISSUE TITLE
Correct Kestrel Configuration for Asp.Net Core GRPC with https (deployed)

### ISSUE THREAD

**Issue by dgerding** [grpc/grpc-dotnet#1492]
Assuming ASP.NET Core 5 latest targeting Azure deployment, I can't seem to get the right mix of Kestrel settings to get a connection to Greeter service. (The same site serves Razor pages and has Duende Identity integrated)

I am deploying to a docker linux target on an Azure web service that has an Azure cert in a vault. 

I have the ssl cert (it's pulled from Vault on startup and cached in temp for single run use) available
during Startup.cs and Program.cs, and am using it to configure Kestrel for https (see Startup.cs fragment).

Site is configured on Azure side for HTTP2, and has websockets enabled as well. Site is serving pages, authenticating and 
serving https pages.

## Kestrel Settings?

Given all that context, what are the right Kestrel (and or grpc?) settings so that a **GRPC-dotnet client** 
can connect to Greeter? (And will I be able to use the client from within Xamarin Forms?)

Right now, when I try and run the standard Greeter example client code against the site, the call to 
```
SayHelloAsync 
```
returns
```
{"Status(StatusCode=\"Internal\", Detail=\"Request protocol 'HTTP/1.1' is not supported.\")"}
```

I've left in some of the different approaches, suggesstions, but they are commented out. Any help appreciated. 

And if I'm asking the wrong question, and should be asking "how to get the client to request http2" please let me know. 

Thanks

### program.cs fragment
```
  .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>()
                    //https://stackoverflow.com/questions/60430781/unable-to-start-kestrel-on-azure-app-services-throws-unable-to-configure-https-e
                    .UseKestrel(options =>
                     {
                         // configure Kestrel with our HTTPS certificate
                         options.ConfigureHttpsDefaults(ConfigureHttps);
                     });


                    /*
                    webBuilder.UseKestrel((builderContext, options) =>
                    {
                        options.ConfigureHttpsDefaults(ConfigureHttps);

                        options.Limits.MinRequestBodyDataRate = null;

                        options.ListenLocalhost(8008, listenOptions =>
                        {
                            listenOptions.Protocols = HttpProtocols.Http1AndHttp2;
                            listenOptions.UseHttps(adapterOptions =>
                            {
                                adapterOptions.ClientCertificateMode = ClientCertificateMode.NoCertificate;
                                adapterOptions.ServerCertificate = null;
                            });
                            listenOptions.UseHttps("<path to .pfx file>", "<certificate password>");
                        });
                    
                    });
                    */
```

### AppSetings
```
{
  "ConnectionStrings": {
    "DefaultConnection": "Server=[redacted];Trusted_Connection=True;MultipleActiveResultSets=true"
  },
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Grpc": "Information",
      "Microsoft": "Information"
    }
  },
  "AllowedHosts": "*",
}  
    
    //,
  //
  //"Kestrel": {
//    "EndPoints": {
  //    "Http": {
     //   "Url": "http://MyApp.com"
//      },

      // Note: You most likely only need one of the following Https sections, thus only one is uncommented here...

      //"HttpsInlineCertFile": {
      //  "Url": "https://yoursite.azurewebsites.net:443",
      //  "Certificate": {
      //      "Subject": "YourCertName",
      //      "Store": "My", //"root",
      //      "Location": "LocalMachine", //"CurrentUser",
      //      "AllowInvalid": "True"
      //  }
      //}
      //"HttpsInlineCertStore": {
      //  "Url": "https://yoursite.azurewebsites.net:443",
      //  "Certificate": {
      //      "Subject": "YourCertName",
      //      "Store": "My", //"root",
      //      "Location": "LocalMachine", //"CurrentUser",
      //      "AllowInvalid": "True"
      //  }
      //}
      //"HttpsDefaultCert": {
        //"Url": "https://MyApp.com:443"
      //}
    //}
  //}
//}
      //"Https": {
      //        "Url": "https://*:443",
      //"Certificate": {
      //          "Subject": "localhost",
      //        "Store": "My", //"root",
      //      "Location": "LocalMachine", //"CurrentUser",
      //"AllowInvalid": "True"
    
  //"Certificates": {
    //"Default": {
//      "Subject": "YourCertName",
      //"Store": "My", //"root",
      //"Location": "LocalMachine", //"CurrentUser",
      //"AllowInvalid": true
    //}
  
  //}
  

```

**Comment by JamesNK** [comment]
> And if I'm asking the wrong question, and should be asking "how to get the client to request http2" please let me know.

When TLS is used the client negotiates HTTP/2 using ALPN. It does this automatically. If the server has HTTP/2 configured then HTTP/2 is used.

But Azure App Service doesn't have support for gRPC over HTTP/2 - https://docs.microsoft.com/en-us/aspnet/core/grpc/supported-platforms?view=aspnetcore-6.0#azure-services

**Comment by dgerding** [comment]
I had misunderstood the Azure GRPC HTT2 restriction to apply to non-Linux runtimes.

Rephrasing question: **What is/are the correct Server and Client configurations to support GRPC on Azure Web (Linux Docker) with Azure SSL (TLS/SLI) when that web service is also serving razor pages?**
