### ISSUE TITLE
Correct way (Example?) to Deploy GRPC on Azure "Anything" using Azure Cert (sni)?

### ISSUE THREAD

**Issue by dgerding** [grpc/grpc-dotnet#1495]
I've asked this question different ways, but it seems I keep asking it the wrong way. 

Here's the latest version of the question:

**What is the correct way to configure asp.net core to support GRPC service that:**

- Runs on Azure using an Azure cert and an ASP.NET Core 5 runtime
- Supports Grpc over Web (needed for Xamarin Client)
- Serves razor pages and can authenticate/authorize (duende identity server)

I am intentionally NOT posting the configurations I've tried because that seems to lead the responses astray in terms of the goal. My bad. 

I just want to run grpc on azure _somehow_ that will support my xamarin client now and "grow into" http2 support when/if it needs it and Azure supports it. I have an azure cert. I have an asp.net core (5) web service, etc. that does everything but "grpc".

Maybe I have to use Kubernetes service instead of Azure App Service?

Any help appreciated.

**Comment by rafikiassumani-msft** [comment]
@dgerding  have you considered the general deployment guidance for aspnetcore app ?  see the following: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/?view=aspnetcore-6.0#:~:text=Host%20and%20deploy%20ASP.NET%20Core%201%20Publish%20to,with%20MSDeploy%20on%20Windows.%20...%20More%20items...%20

**Comment by dgerding** [comment]
@rafikiassumani-msft Thanks for that, but there are no specifications/recommendations for "serving grpc via azure", which is the nut of the question. "How to configure asp.net 5/6 server to serve grpc (and razor) from Azure." Again, sounds like the means is a Kubernetes hosted process instead of app service publish target for Azure. But I'm perplexed that what I'm asking doesn't make sense: How do I run grpc service on azure using azure ssl?

I have all three bullets from my question above working now via grpc web. Asking about grpc support for standard (not "web") grpc clients and services on Azure (including http2 ... needed for the more advanced grpc streaming functionality?).

It sounds like there isn't an example because it would mean recommending a Kubernetes deploy instead of the more familiar "azure app service". Just guessing?

**Comment by JamesNK** [comment]
Azure App Service doesn't support gRPC. Support is coming but it is not here yet. You need to use AKS. The new Azure Container Apps might also support gRPC, but I haven't looked at it closely yet.

I previously linked this doc: https://docs.microsoft.com/en-us/aspnet/core/grpc/supported-platforms?view=aspnetcore-6.0#azure-services

I am not an Azure expert. I have tested grpc-web in Azure App Service, but I haven't tested gRPC over HTTP/2 in Azure because of its troublesome support. If you are looking for detailed instructions or guidence about how to configure HTTP/2 + TLS + Azure then I think you will need to look at Azure docs and talk to Azure experts.

**Comment by captainsafia** [comment]
Closing this as answered.

Triage: we discussed following up independently with to get some deployment scenarios documented on Azure.

**Comment by dgerding** [comment]
Thanks @captainsafia and @JamesNK.

**Comment by f9analytics** [comment]
Tell me this is fixed? We attempted deployment today from VS22.
