### ISSUE TITLE
Client-side load-balancing with gRPC Client Factory?

### ISSUE THREAD

**Issue by markrendle** [grpc/grpc-dotnet#1499]
In [the docs for client-side load-balancing](https://docs.microsoft.com/en-us/aspnet/core/grpc/loadbalancing?view=aspnetcore-6.0) the preview call-out at the top says the feature is "currently not supported for gRPC client factory".

Will gRPC client factory be supported in the final version?

**Comment by JamesNK** [comment]
The latest preview now supports load balancing + client factory. Update to the docs: https://github.com/dotnet/AspNetCore.Docs/pull/24028

Let me know if you have any issues with it.
