### ISSUE TITLE
Any up for grabs?

### ISSUE THREAD

**Issue by zoeysaurusrex** [grpc/grpc-dotnet#150]
I'd love to give a helping hand to this effort if possible, but I don't want to jump in without seeing where you guys might need help.

I'm up to help anywhere I can find a niche with the knowledge I have so far, including samples or documentation.

**Comment by shirhatti** [comment]
Unfortunately, we're currently in a state of rapid change right now making it hard for folks to see where they can contribute right away.

Starting with triage today, we've marked a couple of issues with the label [`good first issue`](https://github.com/grpc/grpc-dotnet/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) as a first step. We plan to use this label more frequently going forward, but bear with us as we get a hang for it.

**Comment by zoeysaurusrex** [comment]
Hey no worries! I’m going to keep watching out.
