### ISSUE TITLE
Is gRpc over named pipes binding is going to be implemented?

### ISSUE THREAD

**Issue by ychumpov** [grpc/grpc-dotnet#1506]
[Microsoft webpage](https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/wcf-bindings) says that named pipes should be implemented.

"Named pipes

WCF provided a named pipes binding for communication between processes on the same physical machine. The first release of ASP.NET Core gRPC does not support named pipes. Adding client and server support for named pipes (and Unix domain sockets) is a goal for a future release."

Are there any news about this feature?

**Comment by JamesNK** [comment]
IPC is supported using unix domain sockets.

Fix docs: https://github.com/dotnet/docs/pull/27275
gRPC IPC docs: https://docs.microsoft.com/en-us/aspnet/core/grpc/interprocess?view=aspnetcore-6.0

**Comment by ychumpov** [comment]
Thanks for your clarification. Is it possible to use unix domain sockets in Dot Net Framework 4.8 for Wpf/WinForms apps?

**Comment by JamesNK** [comment]
No

**Comment by ychumpov** [comment]
Thanks for your clarification. Is it possible to use unix domain sockets in Dot Net Framework 4.8 for Wpf/WinForms apps?
