### ISSUE TITLE
Introduce [GrpcService] Attribute for Automapping

### ISSUE THREAD

**Issue by Blackclaws** [grpc/grpc-dotnet#1508]
### Is your feature request related to a problem? Please describe.
Mapping each service individually introduces mostly unnecessary boilerplate. For regular controllers mapping them using MapControllers() works fine for all classes that implement ControllerBase or have the [ApiController] attribute.

### Describe the solution you'd like
Introduce a similar attribute for registering grpc service implementations [GrpcService] which would then be used to autoregister all types that have this attribute attached.

This is a bit similar to this question here: https://github.com/grpc/grpc-dotnet/issues/1139

I'm wondering at the reason why scanning the assembly would be an issue for linking as that is exactly what is being done for normal controllers already or is there some special linker magic involved there?

**Comment by JamesNK** [comment]
> I'm wondering at the reason why scanning the assembly would be an issue for linking as that is exactly what is being done for normal controllers already or is there some special linker magic involved there?

Do you think trimming works with controllers today?

**Comment by Blackclaws** [comment]
I'm actually not a hundred percent sure whether it does or not. There is hardly any documentation about which parts are easily trimmable and which aren't.

I think in the context of aspnetcore server applications its less important that trimming is performed than it is for applications that are actually being deployed to end-users. Typically server side application size doesn't play that big a role unless we're talking IoT devices in which case you could also opt out of using the MapGrpcServices() method and just fall back to single registration if needed.

If trimming doesn't work with controllers anyway, what is the perceived advantage of trimming working for GrpcService implementations? Trimming the generated base code definitely makes sense if it isn't being used.

**Comment by JamesNK** [comment]
There is a community NuGet package that enables automapping of gRPC services: https://github.com/ShreyasJejurkar/Grpc.AspNetCore.Server.AutomaticServiceRegistration

**Comment by rafikiassumani-msft** [comment]
@Blackclaws We are not planning to do this and advise you to use the community packagehttps://github.com/ShreyasJejurkar/Grpc.AspNetCore.Server.AutomaticServiceRegistration

**Comment by Blackclaws** [comment]
Gotcha, its fair game if you decide it simply won't be done. I think adding a small sentence to the documentation that autoregistration isn't planned for the foreseeable future might help prevent future questions about this. Cheers.
