### ISSUE TITLE
Use Buf instead off protoc

### ISSUE THREAD

**Issue by careless6666** [grpc/grpc-dotnet#1510]
Hi. We started using your library and it is very cool. But at some point we decided to switch from a protoc to a buff (buf build) and faced with the fact that the library completely stopped working. Similar behavior can be obtained, for example, if you specify in the config
`<Protobuf Include="**/*.proto" GrpcServices="Server" Link="Proto\greet.proto" ProtoRoot="Proto" />`
instead off
`<Protobuf Include="Proto\greet.proto" GrpcServices="Server" Link="Proto\greet.proto" ProtoRoot="Proto" />`
In our project, we do not have a section at all Protobuf

Can I get Http.Api to work around this issue?

**Comment by JamesNK** [comment]
I'm confused by what exactly you're asking. `Protobuf` elements certainly work with wildcards, although I think you should remove the `Link` attribute.

I'm not familiar with Buf. I can't comment on its functionality.

I don't understand how Http.Api (did you mean Microsoft.AspNetCore.Grpc.HttpApi?) comes into your question.

Perhaps you should upload an example of your problem, describe what the error is, and what you expect to happen.

**Comment by careless6666** [comment]
Sorry for not giving a link directly to the project

https://github.com/careless6666/grpc-swagger-issue

There are 3 projects
  - WebApplicationStanard is a working version as in the documentation
 - WebApplicationWildcard is just a Wildcard
 - WebApplicationBuf is a variant with a buf, an alternative collector of proto files

for the second and third options, I receive a message in swagger

`No operations defined in spec! `

**Comment by careless6666** [comment]
And your issue from code

https://github.com/aspnet/AspLabs/blob/339524fecb7dc8f6e30533d82551a26185db64d8/src/GrpcHttpApi/src/Shared/ServiceDescriptorHelpers.cs#L215
https://github.com/protocolbuffers/protobuf/issues/7127 was closed

but it seems that something new is needed
`
  var options = methodDescriptor.GetOptions();
  var httpRule = options.HasExtension(AnnotationsExtensions.Http) ? options.GetExtension(AnnotationsExtensions.Http) : null;
`

method GetOptions fixed, nut GetExtension not work(

**Comment by careless6666** [comment]
I found answer for my question
If i use <Protobuf Include="**/*.proto" GrpcServices="Server" Link="Proto\greet.proto" ProtoRoot="Proto" />
instead off 
<Protobuf Include="Proto\greet.proto" GrpcServices="Server" Link="Proto\greet.proto" ProtoRoot="Proto" />

when in obj directory will be created Annotation.CS and when types for extract http rules will differ, in my example it was 
expected type:
`Google.Protobuf.ExtensionValue`1[[Google.Api.HttpRule, Google.Api.CommonProtos, Version=2.4.0.0, Culture=neutral, PublicKeyToken=3ec5ea7f18953e47]]`
recieved type:
`Google.Protobuf.ExtensionValue`1[[Google.Api.HttpRule, WebApplicationTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]`

WebApplicationTest, instead off Google.Api.CommonProtos 

An unexpected fail for me because I was counting on what I can generate
