### ISSUE TITLE
grpc-dotnet Interop tests highly flaky on grpc/grpc repository

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc-dotnet#1511]
This started flaking a few days ago.
Once of the first occurrences is 
https://source.cloud.google.com/results/invocations/29f7f9fc-47d6-4846-8ec4-368cbb688436/targets/github%2Fgrpc%2Finterop_test/tests
and it's been ~50% flaky since.

Likely caused by a recent change in grpc-dotnet?

![image](https://user-images.githubusercontent.com/9939684/144089744-dee4cb47-24ac-4197-b3e2-bba2c46fbd66.png)

**Comment by JamesNK** [comment]
Error is coming from underlying HttpClient logic. Most likely culprit is updating interop tests to .NET 6 - https://github.com/grpc/grpc-dotnet/commit/b9cb8806ae24ee260648dc5f1f24ae552eaf57a7

**Comment by JamesNK** [comment]
I couldn't reproduce this when calling the sandbox server from my local machine. I put server streaming and large unary in a loop and ran them both 100 times without error.

**Comment by JamesNK** [comment]
Changed the interop tests to use net5.0. If tests consistently pass then that confirms the issue is a regression from 5.0 to 6.0.

**Comment by jtattermusch** [comment]
Looks like after merging https://github.com/grpc/grpc-dotnet/pull/1514, the failure on the CI went away, so this really about the net5.0 vs net6.0 difference.

I also tried to reproduce with net6.0 locally and also wasn't able to do so.

**Comment by jtattermusch** [comment]
Since I wasn't able to reproduce locally, I tried to find the CI log where the test is failing with the extra diagnostic info (https://github.com/grpc/grpc-dotnet/pull/1513) but before we reverted back to net5.0 https://github.com/grpc/grpc-dotnet/pull/1514.

Looks like this is the log:
https://source.cloud.google.com/results/invocations/e229d041-9371-4e16-99bb-592991ebf10b/targets/github%2Fgrpc%2Finterop_test/tests;group=tests;test=cloud_to_prod:aspnetcore:default:large_unary:tls;row=3

Is that helpful?

**Comment by JamesNK** [comment]
I believe the issue is SocketsHttpHandler is sending too many pings, and the server is closing the connection. This is for a feature to measure latency between the client and server, and dynamically adjust window sizes. This is a new feature in .NET 6.

See https://github.com/dotnet/runtime/issues/62216

This should get fixed in a .NET 6 servicing release sometime early next year. Until then the interop tests can continue to use .NET 5.

**Comment by JamesNK** [comment]
Blocked on https://github.com/dotnet/runtime/issues/62216

**Comment by jtattermusch** [comment]
I spent some time trying to reproduce and I have some new inputs:
- The failure pattern seems to be that the CI job runs alternate between all the tests passing in one run and all the impacted test failing in other runs.
- I found that the cases when the test cases fail consistently are correlated with the location of the VM that runs test tests (whenever the interop client is run from a VM in the `us-east1` region, the impacted tests are failing).
- The CI (Kokoro) job run get scheduled across multiple compute zones (more or less randomly), which explains why some CI runs pass just fine, while other ones see the tests fail with very high rate (~ 95%).
- interestingly enough, the "grpc-test.sandbox.googleapis.com" service is hosted on servers that are geographically close to the "us-east1" region.


So I can now consistently reproduce the behavior by creating a VM in the right compute zone and manually running the interop client.

create VM
```
# create GCP VM in the a compute zone "close" to the grpc-test.sandbox.googleapis.com backends.
gcloud compute instances create jtattermusch-debug --machine-type e2-standard-4 --zone us-east1-c --image-project debian-cloud --image-family  debian-11 
# ssh to the VM
gcloud compute ssh  jtattermusch-debug
```

prepare
```
# install prerequisites
sudo apt-get install -y git libicu67

# clone the repository
git clone https://github.com/grpc/grpc-dotnet.git

cd grpc-dotnet
# Install dotnet SDK
sudo apt-get install -y jq
./build/get-dotnet.sh
source ./activate.sh
```

# build and run the test
```
dotnet build testassets/InteropTestsClient/ --framework net6.0
dotnet exec testassets/InteropTestsClient/bin/Debug/net6.0/InteropTestsClient.dll --server_host=grpc-test.sandbox.googleapis.com --server_port=443 --test_case=large_unary --use_tls=true
```

When the VM running the client is in the right compute zone ("close enough" to the backends), the test will fail at a very high rate >95%.
It seems very likely that the issue has to do with low latency / high throughput of the connection between the client and the backend. That might indicate where to look for a bug in https://github.com/dotnet/runtime/issues/62216 (when connecting to a hardened backend with low latency connection, the dynamic windows sizing feature from .NET6 might actually lead to generating ping flood conditions with RTT pings and the server reacts to that by closing the connection).

**Comment by jtattermusch** [comment]
Let see what the test results are after merging #1765 and then we can close this.
