### ISSUE TITLE
Compile as .netmodule fails

### ISSUE THREAD

**Issue by nedy13** [grpc/grpc-dotnet#1515]
Hi,

I am usually not a C# developer, so I'm not really familiar with the C# world, frameworks and the environment, but we have a small integration in our product where we transport data via HTTP. So we have a DLL which has a small C# HTTP1 server and HTTP1 client in it. The main problem is that this solution is too slow and we want to give GRPC a try.

The main problem is that our DLL is a mixed-code assembly (C++ and C#). So I need to compile the C# part in a .netmodule and later on it is linked together to one DLL. This was working fine with .Net 4.8 and the HTTP1 code.

With .Net5 / .Net6 and grpc-dotnet it seems not to work.

The compiler is complaining the following:

error **CS0518: Predefined type 'System.Runtime.CompilerServices.NullableAttribute'** is not defined or im

I really have no idea how to fix it.

If I build it with "OutputType>exe</OutputType", then it is working.

![image](https://user-images.githubusercontent.com/4283170/144435164-f5bf69a7-c068-406a-bb8b-18e4abf42589.png)

If I build the example greeter server application with "OutputType>module</OutputType", then I got this message.

![image](https://user-images.githubusercontent.com/4283170/144435375-df17c5c7-eb90-437a-89ae-2590395054b5.png)

Code parts which are failing:

![image](https://user-images.githubusercontent.com/4283170/144436353-c54e24c9-0c3e-4f24-b1c5-6fdb737ad782.png)

My complete project file looks like this.

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <OutputType>module</OutputType>
    <!-- <OutputType>exe</OutputType> -->
    <Utf8Output>true</Utf8Output>
    <!-- <NoConfig>true</NoConfig> -->
    <!-- <NoStandardLib>true</NoStandardLib> -->
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <ProduceOnlyReferenceAssembly>false</ProduceOnlyReferenceAssembly>
	  <!-- <Nullable>disable</Nullable> -->
  </PropertyGroup>

  <ItemGroup>
    <Protobuf Include="..\Protos\prpc.proto" GrpcServices="Server" Link="..\Protos\prpc.proto" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.40.0" />
  </ItemGroup>

</Project>
```

Has somebody an idea, why this is not working with this project? Is this a .Net5/6 limitation?

Thank you very much in advance.

**Comment by JamesNK** [comment]
I don't know what the issue is, but I don't believe it is caused by grpc-dotnet itself.

It seems like module doesn't work well with nullable type attributes. You could raise this issue at https://github.com/dotnet/runtime. I don't think that is the right place to ask, but they should move the issue for you.

**Comment by nedy13** [comment]
Hi James,

I was just hoping that experienced .Net developers might be aware of the problem. I have opened a bug in the .Net framework project. Possibly someone can help me there. 
Thanks a lot anyway!

Link: https://github.com/dotnet/runtime/issues/62517

Have a nice day!
