### ISSUE TITLE
Missing Accept headers on GrpcMode.GrpcWebText

### ISSUE THREAD

**Issue by MHDante** [grpc/grpc-dotnet#1520]
### What version of gRPC and what language are you using?
2.40 in dotnet standard 2.0
Envoy proxy v1.20 with Python backend.
### 

I tried to set up a client using the following code:

```csharp
        var innerHandler = new HttpClientHandler();
        var handler = new GrpcWebHandler(GrpcWebMode.GrpcWebText, innerHandler);
```

However, I got the following error:

```
RpcException: Status(StatusCode="Cancelled", Detail="Bad gRPC response. Invalid content-type value: application/grpc-web+proto")
```

This is likely since the envoy proxy is expecting the Accept header to be set.

The Grpc-Web spec specifies the following: 

> Text-encoded (response) streams
> 
> 1. The client library should indicate to the server via the "Accept" header that the response stream needs to be text encoded e.g. when XHR is used or due to security policies with XHR
>  - Accept: application/grpc-web-text

This implies that when using `GrpcMode.GrpcWebText`, the `GrpcWebHandler` should insert the Accept header. 
If I do this manually by wrapping the inner handler and adding the header in SendAsync, calls proceed as normal.

Please let me know if this is a bug or if I'm forgoing a configuration step.

**Comment by MHDante** [comment]
@JamesNK As a note, is there a chance that the server also doesn't conform to the standard? (as it may have been the one used to test the client before)

**Comment by JamesNK** [comment]
Technically yes. However, in practice, there are only two gRPC-Web clients: the grpc-web JS client and this .NET client. Both of them now always send an accept header with application/grpc-web-text content type.

I'll look into using accept on the server to decide the response content-type, but I don't think it is important.
