### ISSUE TITLE
grpc client CompileXaml error 

### ISSUE THREAD

**Issue by inforzip** [grpc/grpc-dotnet#1521]
<I appreciate all the help given so far.

I have been testing all the suggestions that have come to me, but the problem has not been solved. This leads to frustration due to the time spent and not seeing any light at the end of the tunnel.
I have all the nuget packages installed (grpc.core;grpc.net.client;grpc.tools;google.protobuf).
I manage to create the connection with the grpc server, but when I try to create the client I get the error:
**The CompileXaml task returned false but did not log an error. testGrpc2.Uwp**
although the classes are created in the \obj folder by google.protobuf.

```
var channel = GrpcChannel.ForAddress("https://localhost:5001", new GrpcChannelOptions
{
    HttpHandler = new System.Net.Http.HttpClientHandler(),
});

//Comment bottom line to cleaar the issue
var client = new Greet.Greeter.GreeterClient(channel);
```
What will be causing the crap of this error. I have already eliminated the \obj and \bin folders and restarted visual studio but the problem remains.
Any clue is welcome.

**Comment by rafikiassumani-msft** [comment]
@inforzip can you follow the guidance in this document to troubleshoot your issue ? https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-6.0#wpf-projects-unable-to-generate-grpc-c-assets-from-proto-files

**Comment by rafikiassumani-msft** [comment]
@inforzip We will close this issue due to inactivity.

**Comment by inforzip** [comment]
Greetings
Sorry for the late reply, I still can't work with grpc client in a project uwp/uno platform I always get the error "CompileXaml" task returned false but did not log an error. testGrpc2.Uwp" in the line that creates the client:

```
    var channel = GrpcChannel.ForAddress("https://localhost:5001", new GrpcChannelOptions
    {
        HttpHandler = new System.Net.Http.HttpClientHandler()
    });
    //Uncomment bottom line to repro the issue
    var client = new xizServer.Greeter.GreeterClient(channel);
```
I attach a copy of the project, for any help.

**Comment by inforzip** [comment]
I already deleted the \obj folder and recompile the project but the problem remains.
This situation happens in the uno project that I made available but also in a uwp project. 
In console and wpf projects everything seems to work much better
