### ISSUE TITLE
Grpc.Net.Client remoe Grpc.Net.Client.Balancer?

### ISSUE THREAD

**Issue by shenyang1007** [grpc/grpc-dotnet#1524]
Grpc.Net.Client 2.41.0 removed Grpc.Net.Client.Balancer?

**Comment by rodrigoreis** [comment]
I am facing this same problem. It is known that access to the features of this namespace is conditioned to the version of the dotnet implementation (dotnet5 or dotnet6) through the SUPPORT_LOAD_BALANCING directive, but even I using the dotnet6 version these features are unavailable to me.

![image](https://user-images.githubusercontent.com/324262/146042604-ad632264-d651-4c6d-8909-1f41af3c3ff4.png)

Sorrow...

![image](https://user-images.githubusercontent.com/324262/146042661-0a50a8b1-b2a5-4d47-855b-02eded561a6b.png)

**Comment by JamesNK** [comment]
https://docs.microsoft.com/en-us/aspnet/core/grpc/loadbalancing?view=aspnetcore-6.0

![image](https://user-images.githubusercontent.com/303201/146047524-c67a0fff-228f-4b2f-8407-ab9414abf720.png)

Your follow-up question: Hopefully in the next few months.
