### ISSUE TITLE
Question: Is a good practice replace REST with gRPC in a new web app?

### ISSUE THREAD

**Issue by Gambero81** [grpc/grpc-dotnet#1525]
Hi, i don't find any detailed answer about this question.

I have to develop a brand new web application in ASP.NET Core / Blazor WASM.

Is a good practice to use gRPC (gRPC Web) for client / server communication instead of REST?

Is best to mix REST / gRPC?

For a web applications is best to keep using REST, and use gRPC only for server to server communication?

Thanks

**Comment by sebastienros** [comment]
It all depends on what you need to do which explains why there are no specific answer given.
If your scenario could benefit from gRPC, e.g., streaming, big payloads, strongly typed clients, contract first APIs then it might be worth doing it. Or just the cool factor?
