### ISSUE TITLE
memory leak after .net 6 upgrade

### ISSUE THREAD

**Issue by ldsenow** [grpc/grpc-dotnet#1526]
Hi all,

I am having memory leak issues after upgrade to .net 6. My situation is blazor wasm + code first grpc web. It ran very well on .net 5.
However, i experienced memory leak quite often after .net 6. Please see the error below, Sorry about that it is not that helpful but better than nothing.

![image](https://user-images.githubusercontent.com/177045/146299691-f58ff393-1986-4ce2-b58e-5b7406887dc6.png)

I found an reported issue in .net github repo someone has a similar issue. He mentioned that everything becomes fine after remove the grpc packages. So I started to replace one of the page to use REST and I dont see the memory leak issue after the switch.

I am afraid it might be related to grpc net. Another part that i cant explain is I dont experience the memory issue on kestrel dev server, however, I get the error very easily after publish to IIS. It makes it harder to know which was the root cause.

I hope someone can look into this.

Cheers,
LD

**Comment by ldsenow** [comment]
![image](https://user-images.githubusercontent.com/177045/146309468-93e645f8-6a4a-4c5e-81d5-375115b8e46a.png)

![image](https://user-images.githubusercontent.com/177045/146309502-17cd6063-d61c-4863-afc1-c225a581337f.png)

First img is on .net 6 and second is on .net 5. The memory heap is 4-5 time more on .net 6. Exactly the same data returns back from server side.

**Comment by JamesNK** [comment]
Is this correct:

.NET 5 + wasm + gRPC = works
.NET 6 + wasm + gRPC = memory leak
.NET 6 + wasm + REST = works

If that is correct then it appears there is a problem in how gRPC runs on wasm.

**Comment by JamesNK** [comment]
Could you add a link to the dotnet/runtime issue?

**Comment by ldsenow** [comment]
> Is this correct:
> 
> .NET 5 + wasm + gRPC = works .NET 6 + wasm + gRPC = memory leak .NET 6 + wasm + REST = works
> 
> If that is correct then it appears there is a problem in how gRPC runs on wasm.

Yes, i am creating new projects to compare .net 5 and .net 6 with grpc and rest on blazor wasm. Will share the result later

Here is the dotnet runtime issue reported by another person
https://github.com/dotnet/runtime/issues/62054

**Comment by JamesNK** [comment]
Because this problem occurs after upgrading to .NET 6, I think this problem is in a change that Mono wasm made in .NET 6.

The dotnet/runtime is the best place to discuss this.

**Comment by ldsenow** [comment]
I cannot explain why .net 6 + wasm + REST works. However, I have limited info atm, will do a bit more investigation.

**Comment by JamesNK** [comment]
I'm closing this. Bug is tracked in dotnet/runtime issue.
