### ISSUE TITLE
Nullable DateTime array limitation

### ISSUE THREAD

**Issue by ldsenow** [grpc/grpc-dotnet#1533]
Hi there,

I have a prop in my model which is DateTime?[]. It is a date range. The start and end date can be null.
The issue is e.g. if the start date is null and the end date has value. Our application populates the array properly with first index's value is null. When I receive it on the other end, the array only contains 1 value. It ignores the null value and moves the second one with value to first. That means the end date becomes start date. It is wrong intend from the user perspective. 

Is there is better way to handle this other than breaks the prop into 2?

BTW, i'm using grpcweb.

**Comment by JamesNK** [comment]
I'm guessing you are using protobuf-net.Grpc. Please report bugs in that library in its reprosity.
