### ISSUE TITLE
gRPC Transporter example not working on macOS, what am I doing wrong?

### ISSUE THREAD

**Issue by MikePapinski** [grpc/grpc-dotnet#1536]
I have found this error, what am I doing wrong? 
I need to build reliable and low latency IPC for multiple modules. All modules will run on the same machine on the same OS but I need to be able to run it on Windows 10+ and MacOS.

<img width="1915" alt="image" src="https://user-images.githubusercontent.com/48183086/147142884-18c8dd04-9160-46b3-a959-468de6b4ffaf.png">

**Comment by JamesNK** [comment]
This is a bug. I have a fix for the next version but for now, use 2.40.0
