### ISSUE TITLE
Way for checking the server response status without getting exception

### ISSUE THREAD

**Issue by ziaulhasanhamim** [grpc/grpc-dotnet#1538]
In gprc C# client, it throws an exception if the server responded with an unsuccess response status. 
```c#
var response = await client.SomeRpcCallAsync(request); // It will throw rpc exception if the server responded with an unsuccess response status
```
I don't really like exceptions. So I tried this
```c#
var response = client.SomeRpcCallAsync(request);
var headers = await  response.ResponseHeadersAsync;
var status = response.GetStatus();
Console.WriteLine($"{status.StatusCode}: {status.Detail}");
```
But ended up with InvalidOperationException with the error message `Unable to get the status because the call is not complete`.

So why don't Gprc Clients provide an option to check the status before reading responses like C# HttpClient so that I'm not forced to work with exceptions?

**Comment by JamesNK** [comment]
HttpClient throws exceptions from its methods in many situations. I'm guessing you're referring to it not throwing an error if the response status code isn't 200. HttpClient is designed that way because a non-200 status code isn't necessarily an error. In gRPC, a non-OK status code is always considered an error.

> I don't really like exceptions. So I tried this
> 
> ```cs
> var response = client.SomeRpcCallAsync(request);
> var headers = await  response.ResponseHeadersAsync;
> var status = response.GetStatus();
> Console.WriteLine($"{status.StatusCode}: {status.Detail}");
> ```
> 
> But ended up with InvalidOperationException with the error message `Unable to get the status because the call is not complete`.

gRPC sends the status in the response trailers, which means the response needs to have been completed received. If the response is still in progress then that error is thrown.

If you object to seeing exceptions then you could have an extension method in your project:

```csharp
internal static class GrpcExtensions
{
    public async static Task<Status> WaitForStatusAsync<TResponse>(this AsyncUnaryCall<TResponse> call)
    {
        try
        {
            await call.ResponseAsync.ConfigureAwait(false);
        }
        catch
        {
        }

        return call.GetStatus();
    }
}

var response = client.SomeRpcCallAsync(request);
await  response.WaitForStatusAsync();
```

**Comment by ziaulhasanhamim** [comment]
Yeah, I got the point. I was thinking in a rest API way where you send Bad Request(400) which is not necessarily an error. It's an acknowledgment that the data provided for that request was not correct. 

But I really like the API that HttpClient provide 
```c#
using HttpClient client = new();
using var response = await client.GetAsync("https://example.com/");
if (response.IsSuccessStatusCode)
{
    var responseModel = await response.Content.ReadFromJsonAsync<ResponseModel>();
    ProcessData(responseModel);
}
```

**Comment by JamesNK** [comment]
I don't think we'll introduce a new API. If you want to avoid try/catch blocks in your code then it is a simple to write an extension method to hide it away.
