### ISSUE TITLE
I get an error "Language must be specified" when add a new item->protocol buffer file in visual studio 2022

### ISSUE THREAD

**Issue by bilal-dandara** [grpc/grpc-dotnet#1540]
I get an error "Language must be specified" when add a new item->protocol buffer file in visual studio 2022. is there a way to fix this?

**Comment by JamesNK** [comment]
This was fixed in .NET 6.0.1. Could you double-check what version you are using and update to it if required - https://github.com/dotnet/aspnetcore/issues/37815

**Comment by bilal-dandara** [comment]
My dotnet version is 6.0.101

**Comment by NuxYoung** [comment]
My .Net version is 6.0.101, vs2022 is 17.0.5
but I got the same error

**Comment by dartur123** [comment]
> My .Net version is 6.0.101, vs2022 is 17.0.5 but I got the same error

I also get the same error on the same version of vs2022. I hope this will be solved soon.

**Comment by JamesNK** [comment]
I tested in a preview of 2022 and it works for me:

```
Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.1.0 Preview 2.0
```

**Comment by dartur123** [comment]
> I tested in a preview of 2022 and it works for me:
> 
> ```
> Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
> Version 17.1.0 Preview 2.0
> ```

Sorry I forgot to screenshot the version of my vs2022 where the error occurs
![image](https://user-images.githubusercontent.com/10369840/150062389-7643e58c-7fea-4173-9ad8-8fa6d0d1cd4f.png)

**Comment by NuxYoung** [comment]
> I tested in a preview of 2022 and it works for me:
> 
> ```
> Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
> Version 17.1.0 Preview 2.0
> ```

When I update to 17.1.0 Community, it do work. but I got another bug :(
I will revert to 17.0.5 and wait for the release.
Thanks a lot

**Comment by JamesNK** [comment]
This is fixed, it's just a matter of getting a VS version and .NET SDK with the fix.

**Comment by zenjia** [comment]
Still got the same error with visual studio 2022 ver17.0.6 and .Net6 SDK ver6.0.102.

**Comment by izersoft** [comment]
Still got the same error with visual studio 2022 ver17.0.6 and .Net6 SDK ver6.0.102.
THİS IS HUGE PROBLEM FOR MICROSERVICES PROJECTS
