### ISSUE TITLE
"Failed to deserialize response message" when grpc-timeout header isn't set

### ISSUE THREAD

**Issue by iterativestudios** [grpc/grpc-dotnet#1541]
Im using grpc-dotnet and all the server responses include a grpc-status header (status 0), which the client interpret as "Failed to deserialize response message.".
The server always seems to set this header (ConsolidateTrailers) if the DeadlineManager in the HttpContextServerCallContext is null, which seems to the case if the client hasn't specified a grpc-timeout header.

Is this correct behavior for Unary calls?
(I'll mention that I'm using a custom HttpMessageHandler on the client so I'm trying to exclude that it's not the culprit.)

**Comment by JamesNK** [comment]
grpc-status=0 means the call is successful and should be present.

Your HttpMessageHandler is probably the cause of this error. I'm guessing you're reading the response content in it, so the content then isn't available when the gRPC client tries to read it. The client then errors.

You'll need to stop doing that or buffer the content when you read it, and replace it so the gRPC client can read it later.

**Comment by iterativestudios** [comment]
@JamesNK 
But the client throws an error if grpc-status is present in the response header.
What am I missing?

GrpcCall.cs line 481:
`// gRPC status in the header
if (status.Value.StatusCode != StatusCode.OK)
{
    finished = FinishCall(request, diagnosticSourceEnabled, activity, status.Value);
}
else
{
    // The server should never return StatusCode.OK in the header for a unary call.
    // If it does then throw an error that no message was returned from the server.
    GrpcCallLog.MessageNotReturned(Logger);

    // Change the status code to a more accurate status.
    // This is consistent with Grpc.Core client behavior.
    status = new Status(StatusCode.Internal, "Failed to deserialize response message.");

    finished = FinishCall(request, diagnosticSourceEnabled, activity, status.Value);
}`

I am reading the body in the HttpMessageHandler (overriding SendAsync), because i'm creating a custom HTTP/2 request and then filling the HttpResponseMessage.Content with the actual response, and then returning it for consumption.

**Comment by JamesNK** [comment]
A grpc-status of 0 and the response message is required for success. You're reading the response message so the gRPC client can't and it is failing. Stop doing that.

**Comment by iterativestudios** [comment]
Thanks James, i'll try and get it working (this is for Unity where http/2 isn't supported, and i'm trying to avoid using grpc.core).
