### ISSUE TITLE
   **Transfer Message of size more than 5Gb**

### ISSUE THREAD

**Issue by luvukr** [grpc/grpc-dotnet#1544]
I am trying to transfer an instance of size more than 2GB, let's say 4GB. Initially it said Message limit restriction, then I set all the relevant values to null. Now It's been more than 1 hour but still the client hasn't received the message._

I was curious to know why it's happening then, I came across an auto generated piece of code where serialization happens....{Image 2}.
At  line no 20 in 2nd image it calculated Size of the message for serialization whose return type is Int. Does it mean even after setting null value to relevant properties, we can only transmit message of max 2 GB._ 

I was checking size of my object using this method. It was giving -ve value. What does it mean?
I have tested it for 1.5Gb, it seems to be working absolutely fine.
If I remove compression properties, then  below exception arises.

```
Grpc.Core.RpcException
  HResult=0x80131500
  Message=Status(StatusCode="Internal", Detail="Error starting gRPC call. InvalidDataException: Message too large.", 
```

Image 3:- Machine config.

Image 4: The place where exception originates. 

![image](https://user-images.githubusercontent.com/17564451/147558770-a00f6bc2-3319-48ea-8cc9-cb35d455ee10.png)
![image](https://user-images.githubusercontent.com/17564451/147558936-c009b0e5-2568-4547-938c-eeed95bf5faf.png)
![image](https://user-images.githubusercontent.com/17564451/147559272-c9c0c11d-04a7-4337-9de6-27634db37a1b.png)
![image](https://user-images.githubusercontent.com/17564451/147560320-d419f651-345d-4bc3-bca9-a4bda1d6611a.png)

**Comment by JamesNK** [comment]
You can't send a single message that large. Use streaming and send the data in chunks.

See https://docs.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-6.0#grpc-services-and-large-binary-payloads

**Comment by rafikiassumani-msft** [comment]
Closing as the question has been answered.
