### ISSUE TITLE
ObjectDisposedException thrown by ReadMessageAsync

### ISSUE THREAD

**Issue by lklein53** [grpc/grpc-dotnet#1547]
### What version of gRPC and what language are you using?
Grpc.Net.Client Version 2.40.0, C# Language Version 9.0

### What operating system (Linux, Windows,...) and version?
Linux Ubuntu 18.04

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
5.0.404

### What did you do?
The code uses a grpc Client to perform an AsyncUnaryCall with a deadline being set.

### What did you expect to see?
Either a successful call or a RpcException with a DeadlineExceeded status code if the server hasn't responded within the set deadline.

### What did you see instead?
```
Error starting gRPC call. ObjectDisposedException: Cannot access a disposed object.
Object name: 'Http2ReadStream'.", DebugException="System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Http2ReadStream'.
at System.Net.Http.Http2Connection.Http2Stream.Http2ReadStream.ReadAsync(Memory`1 destination, CancellationToken cancellationToken) 
at Grpc.Net.Client.StreamExtensions.ReadMessageAsync[TResponse](Stream responseStream, GrpcCall call, Func`2 deserializer, String grpcEncoding, Boolean singleMessage, CancellationToken cancellationToken)
```

**Comment by JamesNK** [comment]
Does this error happen every time or is it intermittent?

Could you [enable logging](https://docs.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-6.0#grpc-client-logging) and provide the logs? They give more information about what is going on.

**Comment by lklein53** [comment]
Hi,
thanks for the quick reply. The error happens only sometimes other times the deadline exceeded error is returned.
I have enabled logging and extracted the following order of events for one of the failing requests

```
Starting gRPC call. Method type: 'Unary', URI: 'SERVICE-URI'.
Sending message.
Reading message.
gRPC call deadline exceeded.
gRPC call canceled.
Error reading message. (Here the exceptions is reported)
Finished gRPC call.
```
Thansk for your help and please let me know if you need more information

**Comment by JamesNK** [comment]
Thanks. I think I know what is going on and have a fix.

**Comment by lklein53** [comment]
Thanks a lot for the quick fix.
