### ISSUE TITLE
First calls are slow when using unary grpc

### ISSUE THREAD

**Issue by melfeqy** [grpc/grpc-dotnet#1549]
Hi ,

i'm using grpc unary mode, i noticed that the first 5 to 10 calls are slow compared with the next calls ?

is there any reason for this ?

thanks

**Comment by JamesNK** [comment]
Could be lots of things:

* JIT
* Startup logic and caching
* Establishing TCP connection
* Negotiating TLS
* Starting HTTP/2 connection
* etc
