### ISSUE TITLE
Is There A Rough ETA On A Final Version of the Client Side Load Balancing APIs

### ISSUE THREAD

**Issue by pnquest** [grpc/grpc-dotnet#1553]
Referring to the [docs found here](https://docs.microsoft.com/en-us/aspnet/core/grpc/loadbalancing?view=aspnetcore-6.0#write-custom-resolvers-and-load-balancers). Is there any sense when these might be available in the non-pre releases of `Grpc.Net.Client`?

**Comment by JamesNK** [comment]
Hopefully within the next couple of months. It is a big feature and signoff is needed from multiple teams.

**Comment by pnquest** [comment]
Thanks, @JamesNK! Understood it's a big lift. Really looking forward to it!
