### ISSUE TITLE
Is grpc.core.api being deprecated with grpc.core?

### ISSUE THREAD

**Issue by IIFE** [grpc/grpc-dotnet#1566]
Hi,

I've got a question regarding the replacement of `grpc.core` with `grpc-dotnet`.

I'm slightly confused on which exact package is being deprecated because there are two "core" packages:
- `grpc.core`
- `grpc.core.api`

From what I understand `grpc.core` is the one being replaced/deprecated, but does that mean `grpc.core.api` is also being deprecated, or is that a fundamental package that we can continue using?

`grpc.core.api` has the functionalities of creating channels and interceptors which seems fundamental, so wasn't sure if this package is being affected.

If `grpc.core.api` is not affected, then is there any good reason to use `grpc.net.client` instead if we're already using the `grpc.core.api` package for client side? I know the server side uses `grpc.core` which is definitely being replaced, so that has to change, but my question is more about the client side that relies only on `grpc.core.api`.

Hope my questions make sense.

**Comment by JamesNK** [comment]
Grpc.Core.Api isn't being deprecated.

Grpc.Core.Api just contains shared types used by implementations. It doesn't have a client or server in it.

**Comment by IIFE** [comment]
Thanks @JamesNK 

Grpc.Core.Api has ChannelBase and CallInvoker that allows instantiations of gRPC stubs (this is how I'm creating stubs now). I assume that's staying too? There is no explicit client factory but someone can still use the channel class and instantiate a stub, correct?

Another question please regarding the server part in gRPC dotnet (this might be a .net 5 question). Is gRPC dotnet supported on Windows 7 and server 2012 for the server part? I know there are limitations on the client part but was was wondering on the server aspect.

MS docs suggest using Http1AndHttp2 with Kestrel is compatible with Windows 7 as it will downgrade to Http1, but I'm unsure if that also means I can use self signed SSL certificate with Kestrel on Windows 7?

My current setup is that I'm generating a self signed SSL certificate and giving that to gRPC.Core server, which runs as a Windows service and is only communicated to within a LAN. I want to migrate the server to gRPC dotnet, but not sure if I can still support Windows 7 and use the self signed certificate.

Thanks.

**Comment by IIFE** [comment]
I can see now that `Channel` (the implementation of `ChannelBase` is part of grpc.core rather than grpc.core.api. This is quite an issue as we can't migrate from .NET Framework, which grpc.net.client doesn't fully support. The suggestion [here](https://github.com/grpc/grpc-dotnet/issues/625) is to use grpc.core, but that's being deprecated.

Is there no other option at all to use grpc.net.client with .net framework?

**Comment by JamesNK** [comment]
The official documentation.
