### ISSUE TITLE
deprecated option in proto definitions should add Obselete attribute to generated code

### ISSUE THREAD

**Issue by mrt181** [grpc/grpc-dotnet#1568]
### Is your feature request related to a problem? Please describe.
Adding the `Obsolete` attribute to an rpc method that is overriden warns that the base method is non-obselete:
`Obsolete member 'SomeService.SomeMethod(SomeRequest, ServerCallContext)' overrides non-obsolete member 'SomeService.SomeServiceBase.SomeMethod(SomeRequest, ServerCallContext)' [SomeService]csharp(CS0809)`

The proto definitions look like this: 
```proto
service SomeService {
  rpc SomeMethod (SomeRequest) returns (SomeReply) {
    option deprecated = true;
  }
```

This is ignored in the generated code.
```cs
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GrpcSomeService.SomeReply> SomeMethod(global::GrpcSomeService.SomeRequest request, grpc::ServerCallContext context)
```

It also does not work on the enum level:
```proto
enum SomeEnum {
  option deprecated = true;
  A = 0 [deprecated = true];
}
```
No attribute is added: 
```cs
#region Enums
  public enum SomeEnum {
    [pbr::OriginalName("A")] A = 0,
}
```

It works on the message level:
```proto
message SomeRequest {
  option deprecated = true;
  SomeEnum somefield = 1;
}
```
Which adds the `Obsolete` attribute:
```cs
  [global::System.ObsoleteAttribute]
  public sealed partial class SomeRequest : pb::IMessage<SomeRequest>
```

### Describe the solution you'd like
Add the Obsolete attribute on the generated code when the deprecated option is set in the proto definition.

### Describe alternatives you've considered
ignore warnings and use additional documentation and communication.

**Comment by JamesNK** [comment]
Please recreate this issue in grpc/grpc. That is where code-generation lives.
