### ISSUE TITLE
Be able to run a gRPC server inside a mobile app(.Net Maui or Xamarin.Forms)

### ISSUE THREAD

**Issue by nextfool** [grpc/grpc-dotnet#1571]
Currently the dotnet-grpc is dependent on asp.net core framework, which is not supported on Android/iOS platforms. 
It would be great if dotnet-grpc server can be integrated in a mobile app without asp.net core.

**Comment by JamesNK** [comment]
That will never happen in this project. `Grpc.AspNetCore.Server` is completely dependent on ASP.NET Core.

It can be done, but it would be an entirely new project.

**Comment by Michael-Kempe** [comment]
Are there any plans to do this? 
I could imagine that there are quite a few people who want to host a grpc server - in a window service for example. This was possible with Grpc.Core  but it's in maintenance mode and will be deprecated soon.

**Comment by JamesNK** [comment]
No plans. Grpc.AspNetCore.Server is the only server we're working on.
