### ISSUE TITLE
.net client connect to a grpc server with self signed cert, the .net client throw DeadlineExceeded exception when it first time(only first time call, only when client runs at windows server) call grpc method. 

### ISSUE THREAD

**Issue by luchunminglu** [grpc/grpc-dotnet#1578]
### What version of gRPC and what language are you using?
gpc-dotnet 2.42.0

### What operating system (Linux, Windows,...) and version?
windows server 2016

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.net6

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

.net client connect to a grpc server with self signed cert, the .net client throw DeadlineExceeded exception when it first time(only first time call, only when client runs at windows server) call grpc method. 

if .net grpc client runs at windows 10, it runs normally.

i only test it on windows10 and windows server 2016.

when run at windows server 2016, client and server runs at same machine, but it always throw  DeadlineExceeded exception on first time call.

```
HttpClientHandler httpClientHandler = new HttpClientHandler();
                    httpClientHandler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;

                    GrpcChannelOptions channelOptions = new GrpcChannelOptions()
                    {
                        MaxSendMessageSize = 4*1024*1024,
                        MaxReceiveMessageSize = 4*1024*1024,
                        HttpHandler = httpClientHandler,
                        DisposeHttpClient = true,
                    };

                    channel = GrpcChannel.ForAddress(serverAddress, channelOptions);
```

**Comment by JamesNK** [comment]
If there isn't a deadline then does the first request succeed? How long does it take vs how long is the deadline?

There is overhead in the first by a gRPC client - it has to create a TCP connection, negotiate TLS, negotiate HTTP/2. It might just be that the first request takes extra time so it goes over the deadline time.

**Comment by luchunminglu** [comment]
Yes, the first request succeed but it used about 15 seconds on windows server 2016

**Comment by JamesNK** [comment]
"Starting deadline timeout." is written when the gRPC client is setting up the class.
"Sending message" is written when the underlying HTTP client begins sending the request body.

It looks like the delay is in the underlying SocketsHttpHandler. There is a long delay between SendAsync and the request body being sent. I'm not an expect when it comes to SocketsHttpHandler. I suggest reaching out to that team at https://github.com/dotnet/runtime and ask for advice.
