### ISSUE TITLE
Clean up nullable TODOs

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#1582]
Grpc.Core.Api has recently been annotated with nullable attributes. Some issues were found when updating grpc-dotnet to use it. Warnings were suppressed: https://github.com/grpc/grpc-dotnet/pull/1576

Nullable issues fixed in grpc/grpc repo with PR: https://github.com/grpc/grpc/pull/28616

When new Grpc.Core.Api is available then remove suppressions.

**Comment by Allaev1** [comment]
Can I take this issue?

**Comment by JamesNK** [comment]
Thanks but unfortunately this is blocked until the referenced Grpc.Core.Api is updated to a fixed version. That will be version 2.44.0 or 2.45.0.

**Comment by JamesNK** [comment]
Was fixed a while ago.
