### ISSUE TITLE
Grpc.Net.Client.Balancer namespace unavailable in 2.42.0

### ISSUE THREAD

**Issue by olivierboucher** [grpc/grpc-dotnet#1589]
### What version of gRPC and what language are you using?

2.42.0

### What operating system (Linux, Windows,...) and version?

macOs big surn11.4

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)

5.0.101

### What did you do?

Switched from 2.42.0-dev202201120801 to 2.42.0

I was using a nightly version because of #1560. 

### What did you expect to see?

I was expecting my build to work as it had with the nightly version

### What did you see instead?

The `Grpc.Net.Client.Balancer` namespace is unavailable. I'm using `<TargetFramework>net5.0</TargetFramework>` so I'm expecting the `SUPPORT_LOAD_BALANCING` to be defined. On top of that, 2.42.0-dev202201120801 and 2.42.0-pre1 both work fine.

### Anything else we should know about your project / environment?

This was happening on my windows PC as well, running the same major sdk version. Am I missing something?

**Comment by JamesNK** [comment]
https://docs.microsoft.com/en-us/aspnet/core/grpc/loadbalancing?view=aspnetcore-6.0

> This feature is in preview. Integration with other gRPC features is not complete and testing is required.
> 
> Client-side load balancing is currently only available in prerelease versions of Grpc.Net.Client on NuGet.org.

**Comment by olivierboucher** [comment]
Got it, my bad for missing that !
