### ISSUE TITLE
EnableCallContextPropagation's configure input results in a global configuration, how to make this client specific?

### ISSUE THREAD

**Issue by EraYaN** [grpc/grpc-dotnet#1595]
So say I have two Grpc clients defined:

```cs

services
.AddGrpcClient<TClient>(o =>
{
    o.Address = clientOptions.Address;
})
.EnableCallContextPropagation(o =>
{
    o.SuppressContextNotFoundErrors = true
});

services
.AddGrpcClient<TClient2>(o =>
{
    o.Address = clientOptions.Address;
})
.EnableCallContextPropagation(o =>
{
    o.SuppressContextNotFoundErrors = false
});

```

When I now request a TClient instance from the container both of these configure handlers are run and the `SuppressContextNotFoundErrors` equals false. How do I make it so it does not do this, it should really only call one of these actions (the one that belongs to the specific client)

**Comment by JamesNK** [comment]
This is a bug. Multiple configurations aren't supported. I have created a fix that will be in a future release.

For now, I recommend suppressing the context not found error everywhere.
