### ISSUE TITLE
GRpc INotifyPropertyChanged

### ISSUE THREAD

**Issue by inforzip** [grpc/grpc-dotnet#1597]
Greetings
I'm using grpc in C#, I have to implement INotifyPropertyChanged in the classes coming from the grpc server. 
I've searched in the internet but can't find anything that seems to work. 
Is it possible to implement INotifyPropertyChanged in grpc classes?
Will I have to clone the classes to classes that have INotifyPropertyChanged implemented?
Is there any tool that helps in this almost impossible task?

**Comment by rafikiassumani-msft** [comment]
Triage: @inforzip This change will need to be made in the google protobuf repo (https://github.com/protocolbuffers/protobuf). We suspect that they may refuse the make to change. 

The best way to support the `INotifyPropertyChanged ` is to wrap the protobuf message in the view model that implements it.

**Comment by JamesNK** [comment]
See https://stackoverflow.com/questions/34676925/how-to-wrap-model-property-in-viewmodel-property

Or search for more about working with models and wrapped view models.

**Comment by inforzip** [comment]
Thanks for the help, I hadn't researched about wrapped view models, I understood the concept and it seems to work
