### ISSUE TITLE
Misunderstanding about underlying channel's HttpHandler configuration

### ISSUE THREAD

**Issue by AndrewP-GH** [grpc/grpc-dotnet#1599]
[**Performance best practices with gRPC**](https://docs.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-6.0) contains part about [Keep alive pings](https://docs.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-6.0#keep-alive-pings), which are configured as part of `HttpHandler` in `GrpcChannelOptions`.

But on the other hand, when I configure the named gRPC client via Microsoft DI in ASP.Net Core app (.net6), I have the opportunity to configure `PrimaryHandler` using `ConfigurePrimaryHttpMessageHandler` extension method.

Example:
```
private static IHttpClientBuilder AddPluginGrpcClient<TClient>(
        this IServiceCollection services,
        Uri address)
        where TClient : ClientBase<TClient>
        => services
            .AddGrpcClient<TClient>(
                "some_name",
                opt => opt.Address = address
            )
            .ConfigureChannel(
                (_, options) =>
                {
                    options.HttpHandler = new SocketsHttpHandler
                    {
                        PooledConnectionIdleTimeout = Timeout.InfiniteTimeSpan,
                        KeepAlivePingDelay = TimeSpan.FromSeconds(60),
                        KeepAlivePingTimeout = TimeSpan.FromSeconds(30),
                        EnableMultipleHttp2Connections = true
                    };
                }
            )
            .ConfigurePrimaryHttpMessageHandler(
                _ => new SocketsHttpHandler
                {
                    PooledConnectionIdleTimeout = Timeout.InfiniteTimeSpan,
                    KeepAlivePingDelay = TimeSpan.FromSeconds(60),
                    KeepAlivePingTimeout = TimeSpan.FromSeconds(30),
                    EnableMultipleHttp2Connections = true,
                }
            );
```

So which is the correct way to configure `HttpHandler` for gRPC channel?

**Comment by adityamandaleeka** [comment]
@AndrewP-GH both of them will work... we have both ways for historical reasons.

This might be useful: https://docs.microsoft.com/en-us/aspnet/core/grpc/clientfactory?view=aspnetcore-6.0#configure-httphandler

**Comment by JamesNK** [comment]
I've updated the docs with a note about what is already set on `GrpcChannelOptions`: https://docs.microsoft.com/en-us/aspnet/core/grpc/clientfactory?view=aspnetcore-6.0#configure-channel

**Comment by AndrewP-GH** [comment]
@JamesNK thanks! It's much clearer now :)
