### ISSUE TITLE
timeout_on_sleeping_server interop test is flaky

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc-dotnet#160]
ruby client
https://source.cloud.google.com/results/invocations/1a3e71ed-19e3-4161-8a98-4d01e625289f/targets/github%2Fgrpc%2Finterop_test/tests
```
cloud_to_cloud:ruby:aspnetcore_server:timeout_on_sleeping_server:tls

/var/local/git/grpc/src/ruby/lib/grpc/generic/active_call.rb:31:in `check_status': 13:Received RST_STREAM with error code 2 (GRPC::Internal)
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/bidi_call.rb:209:in `block in read_loop'
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/bidi_call.rb:195:in `loop'
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/bidi_call.rb:195:in `read_loop'
	from src/ruby/pb/test/client.rb:461:in `each'
	from src/ruby/pb/test/client.rb:461:in `timeout_on_sleeping_server'
	from src/ruby/pb/test/client.rb:763:in `call'
	from src/ruby/pb/test/client.rb:763:in `main'
	from src/ruby/pb/test/client.rb:768:in `<main>'
I, [2019-03-13T09:31:34.366230 #77]  INFO -- : ... connecting securely to localhost:32771
W, [2019-03-13T09:31:35.367384 #77]  WARN -- : bidi: read-loop failed
W, [2019-03-13T09:31:35.367455 #77]  WARN -- : 13:Received RST_STREAM with error code 2 (GRPC::Internal)
/var/local/git/grpc/src/ruby/lib/grpc/generic/active_call.rb:31:in `check_status'
/var/local/git/grpc/src/ruby/lib/grpc/generic/bidi_call.rb:209:in `block in read_loop'
/var/local/git/grpc/src/ruby/lib/grpc/generic/bidi_call.rb:195:in `loop'
/var/local/git/grpc/src/ruby/lib/grpc/generic/bidi_call.rb:195:in `read_loop'
src/ruby/pb/test/client.rb:461:in `each'
src/ruby/pb/test/client.rb:461:in `timeout_on_sleeping_server'
src/ruby/pb/test/client.rb:763:in `call'
src/ruby/pb/test/client.rb:763:in `main'
src/ruby/pb/test/client.rb:768:in `<main>'
```

And python client:
https://source.cloud.google.com/results/invocations/1a3e71ed-19e3-4161-8a98-4d01e625289f/targets/github%2Fgrpc%2Finterop_test/tests
```
running run_interop
...
(and times out later)
```

**Comment by JunTaoLuo** [comment]
@jtattermusch do you know if the flakiness comes from the server/client or how the test is written.

**Comment by jtattermusch** [comment]
I checked the interop test results history and I'm not seeing this problem anymore (on the last ~20 builds or so), so I'm going to assume that this problem just went away (probably by upgrading to the latest netcore preview?).

**Comment by jtattermusch** [comment]
I'm still seeing this problem.
Recent failures:
https://source.cloud.google.com/results/invocations/ba3e4b8a-241b-463a-a83b-219ac7c59970/targets/github%2Fgrpc%2Finterop_test/tests
https://source.cloud.google.com/results/invocations/4e45fa36-dde6-4baf-a1ff-1ab1c3231552/targets/github%2Fgrpc%2Finterop_test/tests
https://source.cloud.google.com/results/invocations/88386a33-c5a8-4b2c-8ef9-83575ada48af/targets/github%2Fgrpc%2Finterop_test/tests
https://source.cloud.google.com/results/invocations/47d5a344-a556-4876-98ba-22b86ef15c67/targets/github%2Fgrpc%2Finterop_test/tests

Looks like this keeps happening for go and ruby clients

```
/var/local/git/grpc/src/ruby/lib/grpc/generic/active_call.rb:31:in `check_status': 13:Received RST_STREAM with error code 2 (GRPC::Internal)
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/bidi_call.rb:209:in `block in read_loop'
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/bidi_call.rb:195:in `loop'
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/bidi_call.rb:195:in `read_loop'
	from src/ruby/pb/test/client.rb:461:in `each'
	from src/ruby/pb/test/client.rb:461:in `timeout_on_sleeping_server'
	from src/ruby/pb/test/client.rb:763:in `call'
	from src/ruby/pb/test/client.rb:763:in `main'
	from src/ruby/pb/test/client.rb:768:in `<main>'
I, [2019-03-21T00:51:21.855558 #77]  INFO -- : ... connecting securely to localhost:32771
W, [2019-03-21T00:51:22.855458 #77]  WARN -- : bidi: read-loop failed
W, [2019-03-21T00:51:22.855527 #77]  WARN -- : 13:Received RST_STREAM with error code 2 (GRPC::Internal)
/var/local/git/grpc/src/ruby/lib/grpc/generic/active_call.rb:31:in `check_status'
/var/local/git/grpc/src/ruby/lib/grpc/generic/bidi_call.rb:209:in `block in read_loop'
/var/local/git/grpc/src/ruby/lib/grpc/generic/bidi_call.rb:195:in `loop'
/var/local/git/grpc/src/ruby/lib/grpc/generic/bidi_call.rb:195:in `read_loop'
src/ruby/pb/test/client.rb:461:in `each'
src/ruby/pb/test/client.rb:461:in `timeout_on_sleeping_server'
src/ruby/pb/test/client.rb:763:in `call'
src/ruby/pb/test/client.rb:763:in `main'
src/ruby/pb/test/client.rb:768:in `<main>'
```

```
FATAL: 2019/03/19 14:41:54 &{0xc00021a000}.Recv() = _, rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: INTERNAL_ERROR, want error code 4
exit status 1
```

**Comment by jtattermusch** [comment]
Actually, could this problem be because of https://github.com/grpc/grpc-dotnet/blob/e35404543ceb5401114666e32900cacb43be683c/src/Grpc.AspNetCore.Server/Internal/HttpContextServerCallContext.cs#L266?
CC @JamesNK

**Comment by JunTaoLuo** [comment]
Hey @jtattermusch are you still seeing this flaky test?

**Comment by jtattermusch** [comment]
I think I'm still seeing it, but the flakiness rate is relatively low.
The last 5 occurrences (since May 5) are:
https://source.cloud.google.com/results/invocations/93f2c9f5-2d79-4ce1-8513-9083eee71c17
https://source.cloud.google.com/results/invocations/e56d5a20-6ecb-49df-86eb-c34e5025b992
https://source.cloud.google.com/results/invocations/5f0ab98f-9c03-4ffb-a040-2fd567bc54fd
https://source.cloud.google.com/results/invocations/b4dfa0a8-4ca4-45aa-a06e-cb995f95387a
https://source.cloud.google.com/results/invocations/19516b36-ece0-4bd1-934d-6cf5d6cd53a7

all of them are ruby client against aspnetcore server, it think the rootcause might be what I posted earlier https://github.com/grpc/grpc-dotnet/issues/160#issuecomment-481641602.

**Comment by jtattermusch** [comment]
Another occurrence https://source.cloud.google.com/results/invocations/00ae4ca9-f979-4b55-92ce-5f80de663476/targets/github%2Fgrpc%2Finterop_test/tests

**Comment by JamesNK** [comment]
What is the response from a method the exceeds its deadline suppose to be? Right now the server is sending RST_STREAM with INTERNAL_ERROR and no status trailers. I'm guessing it should send RST_STREAM with NO_ERROR and status trailers.

And when should the server send the response? As soon as the deadline is hit or when the method exits? If it is sent as soon as the deadline is hit then what happens to the still executing code on the server?

**Comment by jtattermusch** [comment]
I think it should send RST_STREAM with NO ERROR and no status trailers? (AFAIK you cannot reset a stream and send trailers at the same time).

The method should be reset as soon as the deadline is hit, we cannot rely on user code to behave nicely and return on time. Well behaved code on server side should be checking updates from the ServerCallContext.CancellationContext and exit anyway.

**Comment by JamesNK** [comment]
I believe this should now be fixed.

grpc/grpc issue - https://github.com/grpc/grpc/issues/18523
