### ISSUE TITLE
Will project convert generic type etc

### ISSUE THREAD

**Issue by PeterJD** [grpc/grpc-dotnet#1608]
<!--
Hi 
Will project convert generic type etc?
Peter

**Comment by MD-V** [comment]
Can you please elaborate more on your question?

**Comment by PeterJD** [comment]
Hi 
Is this enough Elaboration


public struct SerializeKeyValue<A,B>
{
public A Key {get; set;}
public B Value  {get; set;}
}
Kind regards
Peter

**Comment by PeterJD** [comment]
Hi
Thanks for your information, as I suspected not so easy, having invested a large amount of time investigating Visual ReCode, a converter would be possible, tried this with ReCode proved to be extremely hard.
Your app may prove to be more flexible?
Kind regards
Peter

**Comment by JamesNK** [comment]
Google.Protobuf never generates generic types from proto files.
