### ISSUE TITLE
Are HttpMessageHandler instances shared between clients when client factory integration is used

### ISSUE THREAD

**Issue by LapNik** [grpc/grpc-dotnet#1613]
I understand that `IHttpClientFactory` usually pools `HttpMessageHandler` instances and reuses them for `HttpClient` instances. `AddGrpcClient` looks like it [creates a new handler for each named client](https://github.com/grpc/grpc-dotnet/blob/master/src/Grpc.Net.ClientFactory/GrpcClientServiceExtensions.cs#L334). Does it actually create new instances or does it just configure the used handler?

Question #950 implies that at least in some cases the cookies are not shared between clients. That could mean that `HttpMessageHandler` is never shared between clients or that ÌHttpCilentFactory` decided not to use the same instance. However, is there a risk for [unanticipated cookie sharing](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-6.0#cookies)?

**Comment by JamesNK** [comment]
Each named client, usually that means each gRPC client type, shares a handler.

**Comment by LapNik** [comment]
I see, so different client types do not share handlers. In that case if I want to reuse a handler between multiple client types (one server hosts multiple services) I should probably manually create the clients manually with a shared channel.

**Comment by JamesNK** [comment]
Or override how the primary handler is created. I don't believe there is anything stopping you from creating a SocketsHttpHandler once, then setting it on all client types using `ConfigurePrimaryHttpMessageHandler`.
