### ISSUE TITLE
ServerCallHandlerFactory<TService> extensibility

### ISSUE THREAD

**Issue by ladeak** [grpc/grpc-dotnet#1616]
### Is your feature request related to a problem? Please describe.
I would like to provide custom xxxServerCallHandler. Currently `ServerCallHandlerFactory` creates a fixed

```C#
return new UnaryServerCallHandler<TService, TRequest, TResponse>(methodInvoker, _loggerFactory);
```
Which I would like to customize and use my own type instead of UnaryServerCallHandler. Today to achieve this, I would need to re-create `ServerCallHandlerFactory` and `ServiceMethodProviderContext`, `ProviderServiceBinder` and a lot more.

### Describe the solution you'd like
I would like to override the implementation for `ServerCallHandlerFactory`'s _CreateUnary(...), CreateXXX(...)_ methods. This might be achieved by providing the interface for ServerCallHandlerFactory or making the current methods virtual.

### Describe alternatives you've considered
I think an equivalent solution could be achieved by abstracting `ServiceMethodProviderContext` with an interface or making its methods virtual - and depend on this abstraction in the rest of classes.

### Additional context

Performance considerations: my understanding is that these methods are invoked while a service is added/mapped during application startup (and not while serving requests). Performance impact due to the interface dispatch could be acceptable IMHO in this case.

`ServerCallHandlerFactory` is a partial class, but cannot think of a way that extending this class would help preventing re-implementing the above mentioned context and binder classes.

I would be happy to implement either of the changes if it is agreed.

**Comment by JamesNK** [comment]
Why do you want to create a custom `UnaryServerCallHandler`?

There is already an extension point: `IServiceMethodProvider<TService>`. For a mapped gRPC service method you can then call `AddMethod`. However, `AddMethod` just expects a request delegate so you'll be responsible for handling everything about the request.

**Comment by ladeak** [comment]
I would like to implement a Proxy with a pass-through implementation.

So you suggest I create a custom `IServiceMethodProvider` and `ServiceBinderBase`, but as I see I would still need my own context and servicefactory implementation.

**Comment by JamesNK** [comment]
> So you suggest I create a custom `IServiceMethodProvider`

Yes

> and `ServiceBinderBase`

No

**Comment by ladeak** [comment]
As of now I only wanted to replace/extend `ServerCallHandlerFactory`, and that is my concern, that to do so I will need to extend/implement `ServiceBinderBase` and `IServiceMethodProvider` and a custom context too - but I was hoping for re-using those classes. I could reuse all with an `IServerCallHandlerFactory`.

This is a nice to have for me, I am not 'blocked', so feel free to close the issue.
