### ISSUE TITLE
one Interceptor class for client and server

### ISSUE THREAD

**Issue by menaheme** [grpc/grpc-dotnet#1619]
Hi

I am porting a rather large corporate WCF app to .net core using grpc.
Using Interceptors, i noticed (after making a mistake) that client and server interceptor are implemented in the same class, 
Would like to suggest separate classes for server and clients since an interceptor is rarely doing both.

**Comment by JamesNK** [comment]
I agree. Unfortunately, interceptors are now public API that lots of people depend on. It can't be changed.

Work is happening to document using and implementing interceptors. That should clear up how to use them correctly.

**Comment by menaheme** [comment]
I guess creating 2 additional new classes is a non breaking option, but
that would clutter up the api

**Comment by menaheme** [comment]
closing as an answer was recieved
