### ISSUE TITLE
gRPC with Flat buffers?

### ISSUE THREAD

**Issue by LiorBanai** [grpc/grpc-dotnet#1623]
is it possible to use gRPC with flat buffers as the serialization framework instead of protobuf?

I didn't find any mention of this..

**Comment by gfoidl** [comment]
> use gRPC with flat buffers as the serialization framework

--> from the FAQ [Can I use gRPC with my favorite data format (JSON, Protobuf, Thrift, XML)?](https://grpc.io/docs/what-is-grpc/faq/#can-i-use-grpc-with-my-favorite-data-format-json-protobuf-thrift-xml-)

> Yes. gRPC is designed to be extensible to support multiple content types. The initial release contains support for Protobuf and with external support for other content types such as FlatBuffers and Thrift, at varying levels of maturity

But I can't tell what's the current state for gRPC for .NET on this.

**Comment by LiorBanai** [comment]
Ok. Thanks
