### ISSUE TITLE
Auto implementation of INotifyPropertyChanged

### ISSUE THREAD

**Issue by MrDeej** [grpc/grpc-dotnet#1627]
### Is your feature request related to a problem? Please describe.
Today we are converting and reconverting the messages between our own .NET classes, this adds an additional layer of bugs and testing which could be easily avoided by implementing the interface suggested over.

### Describe the solution you'd like
All public properties in the auto-generated message class should implement INotifyPropertyChanged by default or by option.

### Describe alternatives you've considered
We have considered building our own source code generator for Proto messages.
We have considered using gRPC code-first approach. 

### Additional context
We also convert to and from messages/EF.core models on the back-end, however this is not important as we should use EF.core code-first with the messages from the .proto file.

**Comment by JamesNK** [comment]
INotifyPropertyChanged is primarily used in view models. Putting it on DTOs, like generated protobuf messages, isn't appropriate.

You will need to come up with your own solution.

**Comment by MrDeej** [comment]
> INotifyPropertyChanged is primarily used in view models. Putting it on DTOs, like generated protobuf messages, isn't appropriate.
> 
> You will need to come up with your own solution.

But I do not understand why I should not use the messages in the ViewModel. As i describe in the OP, the challenge is that we actually need to do this.

Short summary: We have 10 different back-end services, which delivers data from different domain. For example we have a Products gRPC service, which delivers product entities to a WinUI 3 application. The WinUI 3 application typically uses this Product information instances directly in the user interface, but now we have too convert them to DTO cause we would want the properties to be refreshed from back-end when something changes on that part.

So we have an:

`message msgWpfVfaProduct
{
	int32 productNumer = 1;
	string productName = 2;
	int32 supplierNumber = 3;
	string supplierBrand = 4;
	bool supplierReturnAgreement = 5;
	int32 mainCategoryCode = 6;
	string mainCategoryName = 7;
	int32 subCategoryCode = 8;
	string subCategoryName = 9;
	string subCategoryManager = 10;
	string groupName = 11;
	double priceVatPercent = 12;
	string quantity = 13;
	string quantityUnit = 14;
	string consumerInfoQuantity = 15;
	string sortimentcode = 16;
	string sortimentTekst = 17;
	
	productStatusEnum status = 18;
	string baseOwnBrand = 19;
	string drugAtcKode = 20;
	int32 groupCode = 21;
	string consumerInfoProductName = 22;
	string supplierProductNumber = 23;
	string drugAlternativeDrugCode = 24;
	bool drugPreferredPharmacy = 25;
	string consumerInfoSouldOutAdvice = 26;
	int32 relationLinkedProductNumber = 27;
	string supplierPurchaser = 28;
	string drugLinkToSpc = 29;

}`

And then we need to convert the message instance into this:

` public class DtoWpfVfaProduct : INotifyPropertyChanged
    {

        private int productNumber;

        public int ProductNumber
        {
            get => productNumber;
            set
            {
                if (value == productNumber)
                    return;

                productNumber = value;
                NotifyPropertyChanged();
            }
        }

        private string productName;

        public string ProductName
        {
            get => productName;
            set
            {
                if (value == productName)
                    return;

                productName = value;
                NotifyPropertyChanged();
            }
        }

        private int suppliernumber;

        public int SupplierNumber
        {
            get => suppliernumber;
            set
            {
                if (value == suppliernumber)
                    return;

                suppliernumber = value;
                NotifyPropertyChanged();
            }
        }

        private string supplierBrand;

        public string SupplierBrand
        {
            get => supplierBrand;
            set
            {
                if (value == supplierBrand)
                    return;

                supplierBrand = value;
                NotifyPropertyChanged();
            }
        }


        private bool supplierReturnAgreement;

        public bool SupplierReturnAgreement
        {
            get => supplierReturnAgreement;
            set
            {
                if (value == supplierReturnAgreement)
                    return;

                supplierReturnAgreement = value;
                NotifyPropertyChanged();
            }
        }


        private int mainCategoryCode;

        public int MainCategoryCode
        {
            get => mainCategoryCode;
            set
            {
                if (value == mainCategoryCode)
                    return;

                mainCategoryCode = value;
                NotifyPropertyChanged();
            }
        }


        private string mainCategoryName;

        public string MainCategoryName
        {
            get => mainCategoryName;
            set
            {
                if (value == mainCategoryName)
                    return;

                mainCategoryName = value;
                NotifyPropertyChanged();
            }
        }


        private int subCategoryCode;

        public int SubCategoryCode
        {
            get => subCategoryCode;
            set
            {
                if (value == subCategoryCode)
                    return;

                subCategoryCode = value;
                NotifyPropertyChanged();
            }
        }


        private string subCategoryName;

        public string SubCategoryName
        {
            get => subCategoryName;
            set
            {
                if (value == subCategoryName)
                    return;

                subCategoryName = value;
                NotifyPropertyChanged();
            }
        }


        private string subCategoryManager;

        public string SubCategoryManager
        {
            get => subCategoryManager;
            set
            {
                if (value == subCategoryManager)
                    return;

                subCategoryManager = value;
                NotifyPropertyChanged();
            }
        }


        private string groupName;

        public string GroupName
        {
            get => groupName;
            set
            {
                if (value == groupName)
                    return;

                groupName = value;
                NotifyPropertyChanged();
            }
        }


        private double priceVatPercent;

        public double PriceVatPercent
        {
            get => priceVatPercent;
            set
            {
                if (value == priceVatPercent)
                    return;

                priceVatPercent = value;
                NotifyPropertyChanged();
            }
        }


        private string quantity;

        public string Quantity
        {
            get => quantity;
            set
            {
                if (value == quantity)
                    return;

                quantity = value;
                NotifyPropertyChanged();
            }
        }

        private string quantityUnit;

        public string QuantityUnit
        {
            get => quantityUnit;
            set
            {
                if (value == quantityUnit)
                    return;

                quantityUnit = value;
                NotifyPropertyChanged();
            }
        }


        private string consumerInfoQuantity;

        public string ConsumerInfoQuantity
        {
            get => consumerInfoQuantity;
            set
            {
                if (value == consumerInfoQuantity)
                    return;

                consumerInfoQuantity = value;
                NotifyPropertyChanged();
            }
        }


        private string sortimentCode;

        public string SortimentCode
        {
            get => sortimentCode;
            set
            {
                if (value == sortimentCode)
                    return;

                sortimentCode = value;
                NotifyPropertyChanged();
            }
        }

        private string sortimentTekst;

        public string SortimentTekst
        {
            get => sortimentTekst;
            set
            {
                if (value == sortimentTekst)
                    return;

                sortimentTekst = value;
                NotifyPropertyChanged();
            }
        }


        private productStatusEnum status;

        public productStatusEnum Status
        {
            get => status;
            set
            {
                if (value == status)
                    return;

                status = value;
                NotifyPropertyChanged();
            }
        }

        private string baseOwnBrand;

        public string BaseOwnBrand
        {
            get => baseOwnBrand;
            set
            {
                if (value == baseOwnBrand)
                    return;

                baseOwnBrand = value;
                NotifyPropertyChanged();
            }
        }

        private string drugAtcKode;

        public string DrugAtcKode
        {
            get => drugAtcKode;
            set
            {
                if (value == drugAtcKode)
                    return;

                drugAtcKode = value;
                NotifyPropertyChanged();
            }
        }

        private int groupCode;

        public int GroupCode
        {
            get => groupCode;
            set
            {
                if (value == groupCode)
                    return;

                groupCode = value;
                NotifyPropertyChanged();
            }
        }


        private string consumerInfoProductName;

        public string ConsumerInfoProductName
        {
            get => consumerInfoProductName;
            set
            {
                if (value == consumerInfoProductName)
                    return;

                consumerInfoProductName = value;
                NotifyPropertyChanged();
            }
        }


        public string NorskProduktNavn => consumerInfoProductName == null ? productName : consumerInfoProductName;


        private string supplierProductNumber;

        public string SupplierProductNumber
        {
            get => supplierProductNumber;
            set
            {
                if (value == supplierProductNumber)
                    return;

                supplierProductNumber = value;
                NotifyPropertyChanged();
            }
        }



        private string drugAlternativeDrugCode;
        public string DrugAlternativeDrugCode
        {
            get => drugAlternativeDrugCode;
            set
            {
                if (value == drugAlternativeDrugCode)
                    return;

                drugAlternativeDrugCode = value;
                NotifyPropertyChanged();
            }
        }


        private bool drugPrefferedPharmacy;
        public bool DrugPreferredPharamacy
        {
            get => drugPrefferedPharmacy;
            set
            {
                if (value == drugPrefferedPharmacy)
                    return;

                drugPrefferedPharmacy = value;
                NotifyPropertyChanged();
            }
        }

        private string consumerInfoSoldoutAdvice;

        public string ConsumerInfoSoldoutAdvice
        {
            get => consumerInfoSoldoutAdvice;
            set
            {
                if (value == consumerInfoSoldoutAdvice)
                    return;

                consumerInfoSoldoutAdvice = value;
                NotifyPropertyChanged();
            }
        }


        private int relationLinkedProductNumber;

        public int RelationLinkedProductNumber
        {
            get => relationLinkedProductNumber;
            set
            {
                if (value == relationLinkedProductNumber)
                    return;

                relationLinkedProductNumber = value;
                NotifyPropertyChanged();
            }
        }

        public string ProductNameFarmaPro => $"{ProductName} {Quantity} {QuantityUnit}";

        public event PropertyChangedEventHandler PropertyChanged;

        private void NotifyPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }`


Which could be avoided by the message getting the interface in the first place. 

And we have like 50-60 different message types we have this pattern on. 
Its just another layer with code, and adds no value to the application.
