### ISSUE TITLE
Is there an example of how to use interceptors for outgoing server responses?

### ISSUE THREAD

**Issue by h-j-ashman** [grpc/grpc-dotnet#1630]
Hi,
I've been having a read around the interceptor documentation, and although I see references to being able to access the outgoing response for server side calls, I've not found an example of how to go about doing that. There's examples in the docs (https://docs.microsoft.com/en-us/aspnet/core/grpc/interceptors?view=aspnetcore-6.0) and examples (https://github.com/grpc/grpc-dotnet/blob/master/examples/Interceptor/Server/ServerLoggerInterceptor.cs) on how to intercept an incoming server request, as well as how to intercept a response from within the client, but I can't find a corresponding outgoing server side example.

As a (slightly contrived) example of why I'd want to do this, let's say I want to log a response to a centralized logging service, but need to apply some custom filtering on the logs to mask off sensitive data (e.g. user names) and I want to do that via an interceptor. How would I go about doing that?

Thanks in advance,
Henry

**Comment by JamesNK** [comment]
Await the continuation. The docs and samples show this.

**Comment by JamesNK** [comment]
Update doc to make this clearer: https://github.com/dotnet/AspNetCore.Docs/pull/25226
