### ISSUE TITLE
Add [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage] to generated code

### ISSUE THREAD

**Issue by CzBuCHi** [grpc/grpc-dotnet#1643]
### Is your feature request related to a problem? Please describe.
Code coverage is counting all generated classes as uncovered, which prevents me to have 100% coverage (yes i know it dont mean that i have all edge cases tested).

### Describe the solution you'd like
Add `[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]` to generated code.
- for backwards compatibility it could be flag, that needs to be enabled on each .proto file (msbuild metadata)

### Describe alternatives you've considered
- All generated classes are partial so i can manually add ExcludeFromCodeCoverage to them in separate file ...
- I can write tests for generated code ...

**Comment by JamesNK** [comment]
Code generation logic is in different repos: https://github.com/protocolbuffers/protobuf and https://github.com/grpc/grpc

Please request this change in those repos.
