### ISSUE TITLE
Calling a dotnet GRPC server over UDS from a different framework/language (grpc-node)

### ISSUE THREAD

**Issue by andreasdj** [grpc/grpc-dotnet#1648]
Hi! 

We have setup a local grpc server using `grpc-dotnet` over TCP. It's working fine and we can communicate with it using a dotnet client as well as with a node client using [grpc-node](https://github.com/grpc/grpc-node).

When testing to switch over to UDS it works fine from the dotnet client but not from the node client (getting EACCESS denied). grpc-node claims to have support for GRPC over UDS so I wonder if there are any technical details/limitations to be aware of that exists in grpc-dotnet or should it just work (if it's correctly implemented on the node side).

Thanks!

**Comment by JamesNK** [comment]
I'm not familiar with gRPC in Node or its support for UDS.

**Comment by andreasdj** [comment]
Ok! I understand that any potential issues related to the other package is outside of the scope for this repo. I'm mostly interested to hear if there are any technical implications I'm not aware of.

If there is a standard of using GRPC over UDS and grpc-dotnet is following that, it's easy to know where the issue lies and where to put the effort.

**Comment by JamesNK** [comment]
gRPC over UDS is exactly the same as gRPC over TCP. The bytes are the same. The only difference is the transport.
