### ISSUE TITLE
IHostApplicationLifetime.StopApplication causes in-flight calls to hang until HostOptions.ShutdownTimeout kicks in

### ISSUE THREAD

**Issue by jwfx** [grpc/grpc-dotnet#1649]
### What version of gRPC and what language are you using?
2.44 / C#
### What operating system (Linux, Windows,...) and version?
Win 10
### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET 6.0.201
### What did you do?
Sample application: https://github.com/jwfx/GrpcShutdownTest

1. Run the server (GrpcShutdownTest project)
2. Run the client (Client project)
3. Within 10 sec run another client calling the Shutdown API. (I used [BloomRPC](https://github.com/bloomrpc/bloomrpc) for that)

### What did you expect to see?
`HostOptions.ShutdownTimeout` is set to 30 seconds.
The Client project is calling the LongRunningTask API that should finish after 10 seconds.
The second client is calling the Shutdown API that triggers `IHostApplicationLifetime.StopApplication`

The server should shut down immediately after the LongRunningTask call finishes. It should not be possible for clients to "keep connections open" and thus blocking the shutdown until the timeout.

### What did you see instead?

Even though the LongRunningTask call handler finishes (Timestamp 14:41:31.752) and the response is sent (Timestamp 14:41:31.754), the connection does not properly close for some reason. On the client side the call is also not finishing, it errors out once the server is terminated.
At the end on the server, the HostOptions.ShutdownTimeout kicks in and terminates the connection forcefully.

<details><summary> Click for log output</summary>
<p>

```
14:41:24.331 info: GrpcShutdownTest.Services.ShutdownTestService[0]
      Received Shutdown request
14:41:24.332 info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
14:41:24.333 dbug: Microsoft.Extensions.Hosting.Internal.Host[3]
      Hosting stopping
14:41:24.350 dbug: Grpc.AspNetCore.Server.ServerCallHandler[15]
      Sending message.
14:41:24.359 dbug: Microsoft.AspNetCore.Server.Kestrel.Http2[36]
      Connection id "0HMGECKITID2E" is closing.
14:41:24.359 dbug: Microsoft.AspNetCore.Server.Kestrel.Http2[36]
      Connection id "0HMGECKITID2D" is closing.
14:41:24.374 info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'gRPC - /grpc_shutdown_test.ShutdownTest/Shutdown'
14:41:24.376 info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 POST https://localhost:9000/grpc_shutdown_test.ShutdownTest/Shutdown application/grpc - - 200 - application/grpc 46.2920ms
14:41:24.387 dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[6]
      Connection id "0HMGECKITID2E" received FIN.
14:41:24.388 dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
      Connection id "0HMGECKITID2E" sending FIN because: "The client closed the connection."
14:41:24.389 dbug: Microsoft.AspNetCore.Server.Kestrel.Http2[48]
      Connection id "0HMGECKITID2E" is closed. The last processed stream ID was 1.
14:41:24.392 dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[2]
      Connection id "0HMGECKITID2E" stopped.
14:41:31.752 info: GrpcShutdownTest.Services.ShutdownTestService[0]
      Finished LongRunningTask request
14:41:31.754 dbug: Grpc.AspNetCore.Server.ServerCallHandler[15]
      Sending message.
14:41:31.758 info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'gRPC - /grpc_shutdown_test.ShutdownTest/LongRunningTask'
14:41:31.770 dbug: Microsoft.AspNetCore.Server.Kestrel.Http2[48]
      Connection id "0HMGECKITID2D" is closed. The last processed stream ID was 1.
14:41:54.345 dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[16]
      Some connections failed to close gracefully during server shutdown.
14:41:54.345 dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
      Connection id "0HMGECKITID2D" sending FIN because: "The connection was aborted because the server is shutting down and request processing didn't complete within the time specified by HostOptions.ShutdownTimeout."
14:41:55.349 dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[21]
      Some connections failed to abort during server shutdown.
14:41:55.349 dbug: Microsoft.Extensions.Hosting.Internal.Host[4]
      Hosting stopped
```
</p>
</details>

Running the Client without triggering the shutdown while the call is running lets the request finish cleanly.

### Anything else we should know about your project / environment?
This may be some sort of race problem, as it is not 100% reproducible. 
I initially thought the `RetryPolicy` in the client had something to do with it, but the issue still appears without it, that's why I commented it out.
The returned data in the LongRunningTask call also seems to have something to do with the issue, commenting this out seems to reduce the number occurrences.

**Comment by JamesNK** [comment]
Hi

I tested this and confirmed there is a bug. However, the bug isn't specific to gRPC. Triggering application shutdown causes Kestrel to not send the complete response.

I modified your repro to remove gRPC and created an issue on the aspnetcore repo: https://github.com/dotnet/aspnetcore/issues/40904

**Comment by JamesNK** [comment]
I believe I have a fix for this. It is in ASP.NET Core. How important is this to you?

i.e. do you mind waiting for .NET 7 to get the fix, or do you need it fixed in .NET 6?

**Comment by jwfx** [comment]
First of all, let me say thank you for both the reaction time and all the effort you put into this issue. It is really appreciated.

Of course it would be great to see if the fix could make it to .NET 6, as we are already running our application in production and .NET 7 release is still a while out. That said, this is just a wish, so just include it where it works best for you.

Also, since this is not a gRPC specific problem, from my side this issue here could be closed.

**Comment by JamesNK** [comment]
This is a pretty low-level change in HTTP/2. Given the risk, for now, the fix will be in .NET 7 and later. We'll reevaluate backporting if more people are impacted by this.

Thanks for reporting and the good repo.
