### ISSUE TITLE
How to suppress an error from Google.Protobuf.Tools.Targets?

### ISSUE THREAD

**Issue by InteXX** [grpc/grpc-dotnet#1650]
I'm getting a build error in my [Vazor][1] project:

> Google.Protobuf.Tools proto compilation is only supported by default in a C# project

However, I'm not doing proto compilation in this project. The codegen project is a C# project, which I'm referencing in my Vazor project. Apparently the compiler isn't smart enough to figure that out.

Here's the relevant snippet from the `Google.Protobuf.Tools.Targets` file:

```
<!-- Check configuration sanity before build. -->
<Target Name="_Protobuf_SanityCheck" BeforeTargets="PrepareForBuild">
  <Error
    Condition=" '$(Protobuf_ProjectSupported)' != 'true' "
    Text="Google.Protobuf.Tools proto compilation is only supported by default in a C# project (extension .csproj)" />
</Target>
```

This started when I added the `Grpc.AspNetCore` package, so I could do this in `Startup.vb`:

```
Services.AddGrpc
```

I tried commenting out the `<Error />` element, and that works, but it's a hack—and a pretty lousy one at that.

Here's a [repro project][3]. Build VazorMVC1 and you'll see the error.

Is there a dignified way to suppress this error so my project can build, perhaps in declarative MSBuild syntax, without my having to alter the targets file?

  [1]: https://github.com/VBAndCs/Vazor
  [2]: https://stackoverflow.com/q/1023858/722393
  [3]: https://github.com/InteXX/vazor-grpc

**Comment by JamesNK** [comment]
`Grpc.AspNetCore` references `Grpc.Tools` but it isn't necessary.

You can fix this problem by referencing `Grpc.AspNetCore.Server` and `Google.Protobuf` instead.

**Comment by InteXX** [comment]
This looks like a great solution, exactly what I was looking for at the time.

However, I've unfortunately been forced to abandon my gRPC efforts, due to its inability to run on any but [the very latest versions](https://docs.microsoft.com/en-us/aspnet/core/grpc/supported-platforms?view=aspnetcore-6.0#supported-aspnet-core-servers) of IIS.

Correct me, please, if I'm mistaken in my understanding.

**Comment by JamesNK** [comment]
Correct.

**Comment by JamesNK** [comment]
Correct.

**Comment by InteXX** [comment]
Very good, thank you.
