### ISSUE TITLE
Comparison of gRPC with REST doc

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#166]
Once the initial documentation is merged - https://github.com/grpc/grpc-dotnet/issues/124 - I'm going to add a gRPC vs REST comparison doc.

Should generate some spicy discussion 🌶

**Comment by calvin-pietersen** [comment]
Might be useful for you to see what we’re doing in the wild. Performance and ease of use make it attractive to devs. The main challenge is around load balancing, which may warrant a section in your comparison.

https://rokt.com/engineering_blog/learnings-grpc-aws

**Comment by AlgorithmsAreCool** [comment]
@JamesNK  BTW, your doc says that we should prefer WCF over NamedPipes for IPC scenarios.

But that is not a thing for .net core apps.
