### ISSUE TITLE
Server side callback after a message is sent to client

### ISSUE THREAD

**Issue by searchmon** [grpc/grpc-dotnet#1661]
Is there way to hook up a callback from grpc server side after each message is sent to the client? Or it could be after the data is serialized to a different memory space.
I am trying to use a memory pool for some fields in the response object and want to release those for reuse after the transmission is done.
For example, I would like to return the memory space for 'bigPayload' back to 'myMemoryPool' and reuse it.

public override Task\<ExampleResponse\> UnaryCall(ExampleRequest request,
    ServerCallContext context)
{
    var response = new ExampleResponse()
    response.bigPayload = myMemoryPool.get();
    return Task.FromResult(response);
}

**Comment by JamesNK** [comment]
Answered via email

**Comment by JamesNK** [comment]
Answered via email

**Comment by coffee-core** [comment]
> Answered via email
I have the same problem as searchmon. Although my question is for grpc-java, I think your answer can still help me. so i would like to know your answer, thank you very much.
