### ISSUE TITLE
DNS issues when using gRPC client-side load balancing

### ISSUE THREAD

**Issue by xontab** [grpc/grpc-dotnet#1672]
I have a question regarding the new gRPC client-side load balancing feature - https://docs.microsoft.com/en-us/aspnet/core/grpc/loadbalancing?view=aspnetcore-6.0

I am using the following setup for the gRPC client.

```
o.Address = new Uri("dns:///xxx:8080");
o.ChannelOptionsActions.Add(x =>
{
    x.Credentials = ChannelCredentials.Insecure;
    x.ServiceConfig = new ServiceConfig
    {
        LoadBalancingConfigs =
        {
            new RoundRobinConfig()
        }
    };
});
```

I noticed that when the service is called via K8s headless service endpoint and the service has 0 replicas (thus there are no DNS records), a `Name does not resolve` exception is thrown which is expected.  However, when the service is scaled back to 1 or more replicas, the gRPC calls throw the same exception indefinitely as it looks like the DNS addresses are being cached even though there were failures.

Looks like adding the following resolver factory fixes the issue.  However, I was wondering if there is a way that the client library re-fetches the DNS records automatically after there are connection failures.  The current issue is that the following is adding an additional delay depending on when the `Timer` is triggered.

```
services.AddSingleton<ResolverFactory>(_ => new DnsResolverFactory(TimeSpan.FromSeconds(30)));
```

**Comment by JamesNK** [comment]
Hi, that sounds like a bug. Your workaround is a good temporary fix, but we'll try to improve this.

There is a chance this issue is related to https://github.com/grpc/grpc-dotnet/issues/1656

A new release will come soon with the fix for that. I'll ping this thread and you can retest with the new version and without the temporary fix.

**Comment by xontab** [comment]
Thanks a lot.  Will test out the new version when it is out and let you know the outcome.

**Comment by JamesNK** [comment]
FYI 2.45.0-pre1 doesn't fix this issue. I'll see about fixing it in a later preview or 2.46.0.
