### ISSUE TITLE
gRPC client factory integration in Blazor WebAssembly.

### ISSUE THREAD

**Issue by GevorDanielyan** [grpc/grpc-dotnet#1678]
Hello everyone.

I have a gRPC server and Blazor WASM for my frontend. Version is .NET 6. In my client application, in ### Program.cs  file I'm setup dependency injection system to be able to provide instances of my gRPC services. For example --

```
var builder = WebAssemblyHostBuilder.CreateDefault(args);

builder.Services.AddSingleton(services =>
{
    var backendUrl = "https://localhost:7044"; // Local debug URL

    // Now we can instantiate gRPC clients for this channel
    var httpClient = new HttpClient(new GrpcWebHandler(GrpcWebMode.GrpcWebText, new HttpClientHandler()));
    var channel = GrpcChannel.ForAddress(backendUrl, new GrpcChannelOptions { HttpClient = httpClient });
    return new CashgRPCService.CashService.CashServiceClient(channel);
});
```

And since according to Microsoft documentation it is better to use gRPC client factory, how can I change the above code to use httpClientFactory ?

I tried to make service collection extension class but it does not work, for example --

```
public static class ServiceCollectionExtensions
    {
        public static IServiceCollection AddGrpcServicesClient(this IServiceCollection services)
        {
            services.AddGrpcClient<CashService.CashServiceClient>(client =>
            {
                client.Address = new Uri("https://localhost:7044");
            }).ConfigurePrimaryHttpMessageHandler(() =>
            {
                var handler = new HttpClientHandler();
                return handler;
            });
            return services;
        }
    }
```

and in client Program.cs I call  `builder.Services.AddGrpcServicesClient();`  but this not working.

How can I integrate gRPC client factory in my client app(Blazor WASM)?

Thanks in advance.

**Comment by BrennanConroy** [comment]
Can you specify what isn't working? And if possible provide a minimal repro app as a github repo.

**Comment by JamesNK** [comment]
One problem I can see with your factory code is you haven't configured it to use `GrpcWebHandler` in `ConfigurePrimaryHttpMessageHandler`.

**Comment by GevorDanielyan** [comment]
> One problem I can see with your factory code is you haven't configured it to use `GrpcWebHandler` in `ConfigurePrimaryHttpMessageHandler`.

@JamesNK I'm already added `GrpcWebHandler` and it works .

**Comment by GevorDanielyan** [comment]
It should have been written like this here, for example

```
public static class ServiceCollectionExtensions
    {
        public static IServiceCollection AddGrpcServicesClient(this IServiceCollection services)
        {
            services.AddGrpcClient<CashService.CashServiceClient>(client =>
            {
                client.Address = new Uri("https://localhost:7044");
            }).ConfigurePrimaryHttpMessageHandler(() =>
            {
                var handler = new GrpcWebHandler(GrpcWebMode.GrpcWebText, new HttpClientHandler());
                return handler;
            }).ConfigureChannel(configureChannel => new GrpcChannelOptions
            {
                ServiceConfig = new ServiceConfig
                {
                    MethodConfigs = { defaultMethodConfig }
                }
            });
        }
    }
```
