### ISSUE TITLE
Please provide an example of the Interceptor class using *async* methods

### ISSUE THREAD

**Issue by danm-de** [grpc/grpc-dotnet#1682]
Hi,

I am trying to implement JWT token authentication for a gRPC client. I've read the [documentation](https://docs.microsoft.com/en-us/aspnet/core/grpc/authn-and-authz?view=aspnetcore-6.0#bearer-token-with-grpc-client-factory) and I think the "Interceptor" approach is the most promising.

Unfortunately, the documentation seems to be out of date:

```csharp

public override AsyncUnaryCall<TResponse> AsyncUnaryCall<TRequest, TResponse>(...)
{
    [..]
    context.Options.Metadata.Add("Authorization", $"Bearer {_tokenProvider.GetToken()}");
    [..]
}
```
There is no property with name `Metadata`. Instead there is a `Headers` property - but its content is `null`. I could do this:

```csharp
public override AsyncUnaryCall<TResponse> AsyncUnaryCall<TRequest, TResponse>(...)
{
        // replace context if it comes without meta data ...
        var ctx = context.Options.Headers is null
            ? new ClientInterceptorContext<TRequest, TResponse>(
                method: context.Method,
                host: context.Host,
                options: context.Options.WithHeaders(new Metadata()))
            : context;

        // add JWT token
        ctx.Options.Headers.Add("Authorization", "Bearer <insert token here>");

        return continuation(request, ctx);
}
``` 

This will work - but it has two fundamental problems. 

1. JWT tokens have an expiration time. It should renew the token once the expiration time is reached. Of course, this should only happen if RPC methods are actively used.
2. The overwritten method is synchronous.

Suppose I have a class `IJwtProvider` defined like this:

```csharp
public interface IJwtProvider
{
    Task<string> GetToken(CancellationToken cancellationToken);
}
``` 

To keep it as simple as possible, the provider's only job is to request, cache & update JWT tokens. No fiddling with scopes etc.

Here is the code I've written to archive this:
(inspired by this [StackOverflow](https://stackoverflow.com/questions/61654884/aspnet-core-grpc-async-interceptor-method) question)

```csharp
public class JwtAuthInterceptor : Interceptor 
{
    private readonly IJwtProvider _jwtProvider;

    public JwtAuthInterceptor(IJwtProvider jwtProvider) {
        _jwtProvider = jwtProvider;
    }

    /// <inheritdoc />
    public override AsyncUnaryCall<TResponse> AsyncUnaryCall<TRequest, TResponse>(
        TRequest request,
        ClientInterceptorContext<TRequest, TResponse> context,
        AsyncUnaryCallContinuation<TRequest, TResponse> continuation)
    {
        // replace context if it comes without meta data ...
        var ctx = context.Options.Headers is null
            ? new ClientInterceptorContext<TRequest, TResponse>(
                method: context.Method,
                host: context.Host,
                options: context.Options.WithHeaders(new Metadata()))
            : context;

        var ctn = continuation(request, ctx);

        var task = AttachJwtToken(
            responseAsync: ctn.ResponseAsync,
            metadata: ctx.Options.Headers,
            cancellationToken: ctx.Options.CancellationToken);

        // wrap request in order to attach the JWT bearer token to the authentication header
        return new AsyncUnaryCall<TResponse>(
            responseAsync: task,
            responseHeadersAsync: ctn.ResponseHeadersAsync,
            getStatusFunc: ctn.GetStatus,
            getTrailersFunc: ctn.GetTrailers,
            disposeAction: ctn.Dispose);
    }

    private async Task<TResponse> AttachJwtToken<TResponse>(
        Task<TResponse> responseAsync,
        Metadata metadata,
        CancellationToken cancellationToken)
        where TResponse : class
    {
        // request bearer token (JWT)
        var token = await _jwtProvider.GetToken(cancellationToken: cancellationToken);

        // add access token to authorization header
        metadata.Add("Authorization", $"Bearer {token}");

        return await responseAsync;
    }
}
``` 

This will *not* work and I have no idea why. For some reason, the JWT token is not added to the header of the request. I've searched Stackoverflow, Github, ... but could not find a working example. Most blogs just copied Microsoft's example - using a static JWT token.

I think it has something to do with the fact that `ClientInterceptorContext<TRequest, TResponse>` and `CallOptions` are `struct` types (copy by value).

Is it possible to provide an example of "How to use Interceptor with async methods and provide metadata for the request"?

I would really appreciate that, thank you!

**Comment by danm-de** [comment]
Here is a work-a-round I am currently using:

Service registration (IoC)
```csharp
        services.AddGrpcClient<MyRpcService.MyRpcServiceClient>((sp, options) =>
        {
            options.Address = new Uri("https://myservice.domain.com"); // <-- read from appsettings.json
            options.ChannelOptionsActions.Add(x =>
            {
                x.ThrowOperationCanceledOnCancellation = true;
            });
        }).ConfigureChannel((sp, options) => {
            var scopeFactory = sp.GetRequiredService<IServiceScopeFactory>();
            var asyncAuthInterceptor = new AsyncAuthInterceptor(async (authUri, metadata) =>
            {
                using var scope = scopeFactory.CreateScope();
                var tokenProvider = scope.ServiceProvider.GetRequiredService<IJwtProvider>();
                var token = await tokenProvider.GetToken(CancellationToken.None);
                metadata.Add("Authorization", $"Bearer {token}");
            });
            options.Credentials = ChannelCredentials.Create(
                channelCredentials: new SslCredentials(),
                callCredentials: CallCredentials.FromInterceptor(asyncAuthInterceptor));
        });
```

**Comment by JamesNK** [comment]
Interceptors don't allow async before the call is sent. There is some unfortunate naming that `Interceptor` and `AuthInterceptor` share a similar name. The concept is the same, but they're quite different. You've already found the right solution which is to use `AsyncAuthInterceptor`.

I think there is an opportunity to make this clearer in docs.

**Comment by RonPeters** [comment]
I have discovered all this the hard way. My fundamental issue with the accepted approach is that the DI container is forced to rebuild the scope on every call. This is very inefficient and also screws with my unit/integration tests (because it's a new scope, my singleton holding the access token is not used and another singleton is instantiated, so I have to use backing storage that is either static or persistent to get around this).

Why, oh why, didn't you just use Tasks in the Interceptors so we can async/await any time we want? Please consider at least adding a way for us to asynchronously modify the request in an interceptor.

**Comment by JamesNK** [comment]
Fixed with https://github.com/dotnet/AspNetCore.Docs/pull/25734
