### ISSUE TITLE
gRPC-Web: maximum of concurrent server streaming calls

### ISSUE THREAD

**Issue by kegesch** [grpc/grpc-dotnet#1684]
Recently, we migrated from Grpc.Core to Grpc.Net in our client and server. Our client is a seperate library in netstandard2.0 wich is used by dotnet 6.0 applications and one net48 application. For the net48 application we use grpc-web since HTTP/2 is not supported (and we do not want to use SSL/TLS). 
Everything worked at first glance on our development machines, on the deployment setup one problem arised. 
Once the net48 application created 2 concurrent server streaming calls. the application hang and could not communicate with the server anymore. This leads me to my question, **how many concurrent server streaming calls can be handled in grpc-web in .Net Framework 4.8**? The hanging of the application could only be reproduced if the server and the client are on two different machines. If they are on the same machine, it works normally.
Does it somehow relate to the limit of maximum concurrent calls in browsers (see: https://stackoverflow.com/questions/985431/max-parallel-http-connections-in-a-browser)?

**Comment by JamesNK** [comment]
Yes, it is related.

See https://docs.microsoft.com/en-us/dotnet/framework/network-programming/managing-connections for instructions for raising the TCP connection limit.

**Comment by kegesch** [comment]
Thanks for pointing me in the right direction!
