### ISSUE TITLE
Channel idle timeout for my dotnet library

### ISSUE THREAD

**Issue by chuyangliu** [grpc/grpc-dotnet#1686]
Hi, I'm using gRPC dotnet library with version below:

```
<PackageReference Update="Grpc" Version="2.37.1" />
<PackageReference Update="Grpc.Core" Version="2.37.1" />
<PackageReference Update="Grpc.Tools" Version="2.37.1" />
```

When I create gRPC channel from the client I know there's an option called idle timeout: https://github.com/grpc/grpc/blob/master/include/grpc/impl/codegen/grpc_types.h#L172

**Question 1:** But I don't know what's the default value of this option for my library version. Can someone help check?

Also I notice that there's another option called connection timeout: https://github.com/grpc/grpc/blob/master/include/grpc/impl/codegen/grpc_types.h#L162

**Question 2:** Do you know what's the different between these two timeouts and how are they interacting with each other?

**Comment by JamesNK** [comment]
You're using Grpc.Core which is maintained at https://github.com/grpc/grpc. Please recreate your issue there.
