### ISSUE TITLE
gRPC JSON/REST transcoding with FlatBuffers

### ISSUE THREAD

**Issue by cove** [grpc/grpc-dotnet#1687]
### Is your feature request related to a problem? Please describe.
No

### Describe the solution you'd like
Support gRPC JSON/REST transcoding with FlatBuffers too.

### Describe alternatives you've considered
NA

### Additional context
See #167

**Comment by cove** [comment]
Closing this out since it's probably better handled in https://github.com/grpc/grpc-dotnet/issues/167 and https://github.com/grpc/grpc-dotnet/issues/1687

**Comment by cove** [comment]
reopening, closed wrong issue

**Comment by JamesNK** [comment]
The feature uses the Protobuf to JSON mapping (part of the Protobuf spec). That doesn't really apply for other languages. Also, how will annotating service methods with HTTP info work? That's part of the proto file.

**Comment by cove** [comment]
Yep, good points. There likely is work to be done on FlatBuffers before a robust implementation is viable. I'll close this out in the mean time.
