### ISSUE TITLE
Hosting gRPC on IIS with Windows Server 2022

### ISSUE THREAD

**Issue by plombaer** [grpc/grpc-dotnet#1698]
I'd like to see an example on how to use gRPC with IIS. 
How to configure IIS. 
Is https mandatory ?
Can I still use JWT ?
Thanks

**Comment by rafikiassumani-msft** [comment]
@plombaer The following guidance has more information on how to configure IIS: https://docs.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-6.0&tabs=visual-studio#iis. 
https is required and you should be able to JWT for authorization.

**Comment by plombaer** [comment]
Dear, Thanks.
I build a small client/server test but I'm getting the following error :
Http2StreamException: The HTTP/2 server reset the stream. HTTP/2 error code 'HTTP_1_1_REQUIRED'

Here is my code :
- **Server**
Added to the csproj
<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>

`var builder = WebApplication.CreateBuilder(args);

builder.Services.Configure<IISServerOptions>(options =>
{
    options.AutomaticAuthentication = false;
});

builder.Services.AddAuthentication(
        CertificateAuthenticationDefaults.AuthenticationScheme)
    .AddCertificate();

builder.Services.AddGrpc();

var app = builder.Build();

app.UseRouting();

app.UseAuthentication();

app.MapGrpcService<GreeterService>();
app.MapGet("/", () => "Communication with gRPC endpoints must be made through a gRPC client. To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909");

app.Run();
`
- **Client**
`            var clientHandler = new HttpClientHandler();
            clientHandler.ClientCertificates.Add(new X509Certificate2(@"...", "..."));
            
            var handler = new SubdirectoryHandler(clientHandler, "/TestGrpc");
            var channel = GrpcChannel.ForAddress("https://...",
                new GrpcChannelOptions { HttpHandler = handler});
            var client = new Greeter.GreeterClient(channel);

            var request = new HelloRequest();
            request.Name = "test";

            var reply = await client.SayHelloAsync(request);`

- **IIS**
![image](https://user-images.githubusercontent.com/15078623/164616805-dcc2e26d-c2e0-4336-863b-d0f9a1ecc305.png)
![image](https://user-images.githubusercontent.com/15078623/164616931-7e334bce-62eb-4bac-9ca1-43dd71279134.png)
![image](https://user-images.githubusercontent.com/15078623/164617335-cdb66e80-1644-4b75-befc-7923294143e0.png)
![image](https://user-images.githubusercontent.com/15078623/164618335-60ddbf62-7b2a-4689-8d68-a5aa3632f45a.png)
![image](https://user-images.githubusercontent.com/15078623/164618841-d12eaf8a-30f7-4c8c-868f-caaf443d7427.png)
Now you have a view of my config.

**Comment by JamesNK** [comment]
Some ideas:

1. Does your server meet all of the requirements here: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/protocols?view=aspnetcore-6.0
2. Are you using the latest version of Grpc.AspNetCore and Grpc.Net.Client?
3. Does it work if the client doesn't add a client certificate?

**Comment by plombaer** [comment]
> Some ideas:
> 
> 1. Does your server meet all of the requirements here: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/protocols?view=aspnetcore-6.0
    ![image](https://user-images.githubusercontent.com/15078623/165521674-d7e4340c-7ff6-402c-b74c-8f29a459e897.png)

> 2. Are you using the latest version of Grpc.AspNetCore and Grpc.Net.Client?
    Using the latest version solved my problem.

> 3. Does it work if the client doesn't add a client certificate?
     I removed the client add certificate and changed the SSL Settings.

Thanks for your help

**Comment by plombaer** [comment]
Dear,
I reopen the question.
I used my client code into a .Net Framework 4.8 project.
Everything compiles fine but when I run the code I get the following error:
Status(StatusCode="Internal", Detail="Error starting gRPC call. ArgumentException: Only HTTP/1.0 and HTTP/1.1 version requests are currently supported.
Parameter name: value", DebugException="System.ArgumentException: Only HTTP/1.0 and HTTP/1.1 version requests are currently supported.
Parameter name: value
   at System.Net.HttpWebRequest.set_ProtocolVersion(Version value)
   at System.Net.Http.HttpClientHandler.CreateAndPrepareWebRequest(HttpRequestMessage request)
   at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Grpc.Net.Client.Internal.GrpcCall`2.<RunCall>d__73.MoveNext() in /_/src/Grpc.Net.Client/Internal/GrpcCall.cs:line 493")

My client code:
```
            var clientHandler = new HttpClientHandler();

            var handler = new SubdirectoryHandler(clientHandler, "/TestGrpc");
            var channel = GrpcChannel.ForAddress("https://...",
                new GrpcChannelOptions
                {
                    HttpHandler = handler,
                    //Credentials = ChannelCredentials.Create(ChannelCredentials.SecureSsl, credentials)
                });
            var client = new Greeter.GreeterClient(channel);

            var request = new HelloRequest();
            request.Name = "test";

            var reply = await client.SayHelloAsync(request);
```

Any idea?

**Comment by JamesNK** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/grpc/netstandard?view=aspnetcore-6.0#net-framework

**Comment by plombaer** [comment]
> See https://docs.microsoft.com/en-us/aspnet/core/grpc/netstandard?view=aspnetcore-6.0#net-framework

Is it possible to have the server (IIS) accept both HTTP/1 and HTTP/2 ?
The .Net6 client would use HTTP/2 and .Net Framework the HTTP/1
Is this possible ?

**Comment by JamesNK** [comment]
No. gRPC requires HTTP/2.

You could setup gRPC-Web which supports HTTP/1.1.

**Comment by thinhbing** [comment]
It is possible to host gRPC in IIS on Win Server 2019? Or plan to make it happen ?
