### ISSUE TITLE
Grpc with multiple database connections

### ISSUE THREAD

**Issue by inforzip** [grpc/grpc-dotnet#1699]
I am using grpc with .net, I have already created a grpc server application that connects to a database to validate logins to respond to the client application.
After the login validation, I wanted each username to connect to a different database, i.e. I wanted to change the datacontext on the server application for a particular channel created in the client.

Is it possible to create public variables for a grpc.channel?
Is it possible to define the datacontext for each grpc.channel? 
What is the best practice to use in the grpc server application to achieve this goal.

I have searched a lot, but did not find anything that would help me, I thank you in advance for any help or tip.

**Comment by JamesNK** [comment]
I guess you could configure channel's with an interceptor that passes along the channel name in metadata, then read that on the server and make a decision about what database you want to connect to.

**Comment by inforzip** [comment]
With the help given i be able to create an interceptor on the server that receives some data from the client, according to the code that I leave here for the help of someone with the same problem.

For now it is not working, what am i doing wrong?

In the interceptor I use ServiceProvider to get the companyDbContext service created in the ConfigureServices method of the startup of the grpc server. Then I change the service with a new connectionstring with the name of the database to which I want to connect but this is not work.

When i query de datatabase always happens in the initial datacontext created in startup.

```
 public class ServerAutorizationInterceptor : Interceptor
    {
        public readonly ILogger<ServerAutorizationInterceptor> _logger;
        private readonly IServiceProvider _serviceProvider;
        private readonly IConfiguration _configuration;

        public ServerAutorizationInterceptor(ILogger<ServerAutorizationInterceptor> logger, IServiceProvider serviceProvider, IConfiguration configuration)
        {
            _logger = logger;
            _serviceProvider = serviceProvider;
            _configuration = configuration;
        }

        public override async Task<TResponse> UnaryServerHandler<TRequest, TResponse>(
            TRequest request, 
            ServerCallContext context, 
            UnaryServerMethod<TRequest, TResponse> continuation)
        {
            _logger.LogInformation($"Starting receiving call. Type: {MethodType.Unary}. " + $"Method: {context.Method}.");
            try
            {
                foreach (var item in context.RequestHeaders)
                {
                    switch (item.Key)
                    {
                        case "appuser":
                            _logger.LogInformation("AppUser value is {0}", item.Value);
                            break;
                        case "companydb":
                            var companyDC = _serviceProvider.GetRequiredService<CompanyDbContext>();
                            companyDC = new CompanyDbContext(
                                _configuration.GetConnectionString("DbCompany").Replace(";Database=;", ";Database=" + item.Value + ";"));
                            _logger.LogInformation("CompanyDb value is {0}", item.Value);
                            break;
                    }
                }
                return await continuation(request, context);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, $"Error thrown by {context.Method}.");
                throw;
            }
        }
    }
```
