### ISSUE TITLE
How is Certifier example a mTLS setup ?

### ISSUE THREAD

**Issue by Clement-Jean** [grpc/grpc-dotnet#1704]
Hi,

I wrote multiple gRPC servers and client in the past but I'm no expert on security. What I did in Golang or Java is that I had a ca.crt and a server private key, I would use these two to setup the server and then I would use the ca.crt to setup the client.

After checking at the Certifier example, I do not really get what's going on. I understand that the client is using a .pfx file (which is self signed) but I don't really get the server side configuration. Could someone explain that to me ? and then, could I be using the same kind of setup I did before (server use .crt and .pem and client use .crt) ?

Thank you for your time

**Comment by JamesNK** [comment]
The server uses TLS. The server certificate is the ASP.NET Core https dev certificate.

**Comment by Clement-Jean** [comment]
@JamesNK thank you for clearing that up. Is the the certificate generated by doing `dotnet dev-certs https` ?

**Comment by JamesNK** [comment]
Yes. If no certificate is defined, and you're running an app from source (i.e. it's not published as compiled DLLs) then the dev certificate is automatically used.
