### ISSUE TITLE
GRPC dotnet very slow with .net 5 framework

### ISSUE THREAD

**Issue by CosbyBs86** [grpc/grpc-dotnet#1707]
Hello all
I'm facing a very weird behavior. I'm using GRPC .net client package (version 2.45.0) on .NET framework 5 as a very stupid client for a grpc server written in Golang. The client -> server communication is in streaming. With GRPC core package the client/server communication run about 15000 operations per second. With GRPC .net client package the communication is about 1200 ops/s.

Please find here below the cliente code:

GRPC core code:
`
var chanel = new Channel("172.25.0.100", 4424, ChannelCredentials.Insecure);
var service = new GrpcService.GrpcServiceClient(chanel);
var call = service.AppendItems();

foreach (var i in grpcItems)
{
await call.RequestStream.WriteAsync(r).ConfigureAwait(false);
}
await call.RequestStream.CompleteAsync();
`

GRPC .net client code:
`
var chanel = GrpcChannel.ForAddress("http://172.25.0.100:4424/", new GrpcChannelOptions
{
HttpHandler = new SocketsHttpHandler
{
EnableMultipleHttp2Connections = true,
PreAuthenticate = false,
UseCookies = false,
PooledConnectionIdleTimeout = Timeout.InfiniteTimeSpan,
},
});
var service = new GrpcService.GrpcServiceClient(chanel);
var call = service.AppendItems();

foreach (var i in grpcItems)
{
await call.RequestStream.WriteAsync(r).ConfigureAwait(false);
}
await call.RequestStream.CompleteAsync();
`

Using .net 6 frameworks times are almost the same but I was expecting something faster. Can you kindly point me out on how to improve performances.

Thank you

**Comment by rafikiassumani-msft** [comment]
@CosbyBs86 Can you provide a github repo for us to be able to investigate the issue ?

**Comment by JamesNK** [comment]
Thanks for the repo. I tested and found some interesting results. Did you test with the debugger attached? I found that it made Grpc.Net.Client much slower:

![image](https://user-images.githubusercontent.com/303201/165510277-67ae3fdf-f188-4f98-b109-d06bfb40d7d0.png)


But when the app is built as Release and run without a debugger Grpc.Net.Client is very fast. Faster than Grpc.Core:

![image](https://user-images.githubusercontent.com/303201/165510396-0a026151-f6e0-4e57-a468-01ec247d36c7.png)

**Comment by CosbyBs86** [comment]
Thank yoy @JamesNK. Yes, I'm facing the same results. with debugger is very slower, using .net 5 without the debugger is very fast. This is weird.

**Comment by halter73** [comment]
It's pretty expected for a debugger to slow things down. Is it important for it to run faster under a debugger for some reason?

**Comment by BrennanConroy** [comment]
Closing as answered.

**Comment by ogxd** [comment]
@BrennanConroy Can we reopen the issue? Or maybe I can create a new one?

**Comment by JamesNK** [comment]
I took a look and found Grpc.Net.Client is as fast (or faster) by setting `<ServerGarbageCollection>true</ServerGarbageCollection>` property in the test project.

```
Server on 8500 answered 100000 times
- Average QPS = 19640 calls / s
- Success rate = 100 %
- 95p quantile = 7.2161 ms
- 50p quantile = 3.7953 ms
- Average = 4.6495 ms
```

**Comment by JamesNK** [comment]
You should set the property I mentioned in the csproj.

I've created an issue to look into why there is such a large difference: https://github.com/dotnet/runtime/issues/69475

**Comment by AmSoMad** [comment]
It's a very interesting conversation. flagged up

**Comment by BrennanConroy** [comment]
Closing as the primary issue is being tracked in https://github.com/dotnet/runtime/issues/69475

**Comment by ogxd** [comment]
Because the conclusion was that the difference would only be there when under workstation GC and because my application uses server mode GC, I switched to Grpc.Net.Client. There is however an important difference in performance still :(

<img width="2137" alt="image" src="https://user-images.githubusercontent.com/12692438/195803777-cbd3b8c4-1694-457a-9ddc-b79e608af109.png">
