### ISSUE TITLE
Integration test with minimal APIs

### ISSUE THREAD

**Issue by listepo** [grpc/grpc-dotnet#1709]
@JamesNK  how to write integration tests with minimal APIs?

**Comment by rafikiassumani-msft** [comment]
@listepo  Please use the following guide: https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-6.0

**Comment by halter73** [comment]
https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60-samples?view=aspnetcore-6.0#test-with-webapplicationfactory-or-testserver is a migration guide if you're starting from an existing project.

**Comment by listepo** [comment]
If I'm not mistaken this is an example/docs for Microsoft.AspNetCore.Mvc.Testing, but not grpc-net

**Comment by JamesNK** [comment]
https://docs.microsoft.com/en-us/aspnet/core/grpc/test-services?view=aspnetcore-6.0

**Comment by listepo** [comment]
@JamesNK thanks, but this example uses `GrpcTestFixture<TStartup>`, minimal APIs does not use TStartup)

**Comment by listepo** [comment]
I already figured it out, thanks everyone
