### ISSUE TITLE
Combining gRPC hosted in IIS with JWT

### ISSUE THREAD

**Issue by plombaer** [grpc/grpc-dotnet#1718]
Dear,
I managed to host my service under IIS. In a separate project I successfully used an ADFS JWT token with gRPC.
But now I'd like to combine both. For the moment I receive a permission denied. Here is my code:
Server:

```csharp
var builder = WebApplication.CreateBuilder(args);

builder.Services.Configure<IISServerOptions>(options =>
{
    options.AutomaticAuthentication = false;
});

builder.Services.AddGrpc();

builder.Services.AddAuthentication(CertificateAuthenticationDefaults.AuthenticationScheme)
    .AddCertificate()
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters = new TokenValidationParameters
        {
            IssuerSigningKey = new RsaSecurityKey(new RSAParameters
            {
                Exponent = FromBase64Url("..."),
                Modulus = FromBase64Url("...")
            }),
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidIssuer = "http://.../adfs/services/trust",
            ValidAudiences = new[] { "http://.../adfs/trust" }
        };
    });

builder.Services.AddAuthorization(options =>
{
    options.AddPolicy(JwtBearerDefaults.AuthenticationScheme, policy =>
    {
        policy.AddAuthenticationSchemes(JwtBearerDefaults.AuthenticationScheme);
        policy.RequireClaim(ClaimTypes.Name);
    });
});

var app = builder.Build();

app.UseRouting();

app.UseAuthentication();
app.UseAuthorization();

app.MapGrpcService<GreeterService>();

app.Run();
```

Client:

```csharp
var credentials = CallCredentials.FromInterceptor((c, m) =>
            {
                m.Add("Authorization", "Bearer " + GetStsClaim());
                return Task.CompletedTask;
            });

            var clientHandler = new HttpClientHandler();
            
            var handler = new SubdirectoryHandler(clientHandler, "/TestGrpc");
            var channel = GrpcChannel.ForAddress("https://...",
                new GrpcChannelOptions 
                {
                    HttpHandler = handler,
                    Credentials = ChannelCredentials.Create(ChannelCredentials.SecureSsl, credentials)
                });
            var client = new Greeter.GreeterClient(channel);

            var request = new HelloRequest();
            request.Name = "test";

            var reply = await client.SayHelloAsync(request);

```

You input is more than welcome

**Comment by rafikiassumani-msft** [comment]
@plombaer Triage: Can you provide a sample of the logs with the specific error message?

**Comment by plombaer** [comment]
> @plombaer Triage: Can you provide a sample of the logs with the specific error message?

Status(StatusCode="PermissionDenied", Detail="Bad gRPC response. HTTP status code: 403")

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TestGrpcClient.Program.<Main>d__0.MoveNext() in ...

**Comment by JamesNK** [comment]
Could you provide your server logs at a debug or trace level? That provides us with information about what is going on when the request is received by the server.

See https://docs.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-6.0#grpc-services-logging

**Comment by plombaer** [comment]
I added this
```
builder.Host.ConfigureLogging(logging =>
{
    logging.AddFilter("Grpc", LogLevel.Debug);
    logging.SetMinimumLevel(LogLevel.Debug);
    logging.AddEventLog();
});
```
But I see nothing the Application EventLog

**Comment by JamesNK** [comment]
Logging to console is usually the easiest, but you might not get that output with IIS. You could use serilog to write to disk.

Also, remember to remove other log filters from appsettings.*.json files.

**Comment by plombaer** [comment]
Thanks
I used Serilog and here is the log it generated.
The error I see :
Authorization failed. These requirements were not met:
DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
[log.txt](https://github.com/grpc/grpc-dotnet/files/8634084/log.txt)

**Comment by JamesNK** [comment]
It looks like the server is returning a 403 status because there is no client certificate. Have you tried removing client certificate authentication configuration from the server?

```
2022-05-05 20:39:33.126 +02:00 [DBG] No client certificate found.
2022-05-05 20:39:33.126 +02:00 [DBG] AuthenticationScheme: Certificate was not authenticated.
2022-05-05 20:39:33.131 +02:00 [INF] Authorization failed. These requirements were not met:
DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
2022-05-05 20:39:33.133 +02:00 [INF] AuthenticationScheme: Certificate was challenged.
```

**Comment by plombaer** [comment]
Thanks for the help
