### ISSUE TITLE
Allow AsyncAuthInterceptor to be registered in DI container

### ISSUE THREAD

**Issue by RonPeters** [grpc/grpc-dotnet#1719]
Interceptors can modify the call headers synchronously, and AsyncAuthInterceptors can modify the call headers asynchronously. The problem is that Interceptors can be registered in DI, but AsyncAuthInterceptors cannot.

The reason this is a problem is because if your AsyncAuthInterceptors requires access to DI services, the current implementation requires you to instantiate a new DI scope. This rebuilds the entire container and gives you a new set of services. This is inefficient and inconvenient, especially when your singleton services are reinstantiated.

Interceptors have IHttpBuilder.AddInterceptor. I propose adding IHttpBuilder.AddAsyncAuthInterceptor so that the auth interceptor can be registered in DI and not have performance or scoping issues.

I'm not sure if there are implications around the creation of the Channel Credentials, but I've seen this question come up many times and it took me quite a while to figure out what was going wrong with my unit tests because of the DI scoping.

**Comment by JamesNK** [comment]
Hi

I think the feature you're looking for was just added in 2.46.0-pre1. Try out the `AddCallCredentials` extension method.

**Comment by RonPeters** [comment]
@JamesNK Yes, that appears to solve my use case. Thanks!
