### ISSUE TITLE
[Question] Simple docs/example for Linux

### ISSUE THREAD

**Issue by shaggygi** [grpc/grpc-dotnet#1725]
Trying to use this API on a RPi and wanted to know if there are any examples on how to copy/setup the files (including certs) to run the server.

Any help providing docs or explaining steps will be appreciated.  Thx

**Comment by JamesNK** [comment]
There aren't docs like that specific to gRPC + .NET. You should look for what docs are available for .NET and ASP.NET Core apps.

**Comment by shaggygi** [comment]
Looks like there is a few YouTubes that demo this.  I'll go ahead and close.

@JamesNK  BTW (and side question), you have any plans on a new Community Standup discussing related .NET 7 features?  You also do a good job on those.  Thx 👍

**Comment by shaggygi** [comment]
Referencing: https://docs.microsoft.com/en-US/aspnet/core/grpc/troubleshoot?view=aspnetcore-6.0
