### ISSUE TITLE
Exception in Grpc.AspNetCore on Windows 11

### ISSUE THREAD

**Issue by czmirek** [grpc/grpc-dotnet#1727]
### What version of gRPC and what language are you using?
proto3, C#

### What operating system (Linux, Windows,...) and version?
Microsoft Windows 11 Pro
10.0.22000 Build 22000

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET SDK (reflecting any global.json):
 Version:   6.0.300-preview.22204.3
 Commit:    4f23310c97

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300-preview.22204.3\

### What did you do?
Run the default Visual Studio GRPC Service project template and test it with `grpcurl`
![image](https://user-images.githubusercontent.com/18615545/167260864-62fca31e-ec8d-4f51-bb90-82ebdc2794b6.png)

### What did you expect to see?
The command `grpcurl -plaintext localhost:7172 greet.Greeter/SayHello` works and the Service app responds correctly.

### What did you see instead?
The command does not work and when you configure `appsettings.json` logging to "Debug" in the Service app, this exceptions pops up.

```
dbug: Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware[1]
      Failed to authenticate HTTPS connection.
      System.IO.IOException: Cannot determine the frame size or a corrupted frame was received.
         at System.Net.Security.SslStream.GetFrameSize(ReadOnlySpan`1 buffer)
         at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
         at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context)
```

### Anything else we should know about your project / environment?
- I read that Windows 11 do some shenanigans with TLS 1.3 so I tried to force Kestrel to use TLS 1.2 but without luck.
- I updated the Grpc.AspNetCore nuget from 2.40.0 to 2.45.0, no luck.
- I'm running this in Visual Studio 2022 and I even restarted the development certificates, also no luck.

Also, Visual Studio version:

Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.1.6

**Comment by BrennanConroy** [comment]
It looks like you're using `-plaintext` with an HTTPS endpoint, if you want to use that option it should be against a non-tls endpoint.
