### ISSUE TITLE
Is there Support for streaming with GRPC method calling from REST api

### ISSUE THREAD

**Issue by Naganathan** [grpc/grpc-dotnet#1728]
Regarding this approach, http://james.newtonking.com/archive/2020/03/31/introducing-grpc-http-api

Can we do GRPC streaming data using REST API? like in below code

```
`service Greeter {
  rpc SayHello (stream HelloRequest) returns (stream HelloReply) {
    option (google.api.http) = {
      get: "/v1/greeter/{name}"
    };
  }
}`
```

**Comment by JamesNK** [comment]
Yes in the new package coming next week. It’ll return line delimited JSON

**Comment by JamesNK** [comment]
Available here: https://devblogs.microsoft.com/dotnet/announcing-grpc-json-transcoding-for-dotnet/
