### ISSUE TITLE
Using one grpc channel 

### ISSUE THREAD

**Issue by menaheme** [grpc/grpc-dotnet#1730]
Hello, 

Read at [msdocs ](https://docs.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-6.0) that channels should be reused.

To better understand , I created a typical ASPNET app and a gRPC client factory. 
The factory holds a single gRpc channel as a private member.
Each time a client in needed (in a controller presumably) that factory will create one from that channel.

Registering the factory as a singleton in the ASPNET dependency injector, effectively means this channel will be reused for all clients in that ASPNET app for the lifetime of the process.

Is that a good idea or is this going to far with the reuse here ? 

Also, if a channel fails (A-LA WCF channel fault) what deos that mean for the application ? (re create the factory maybe)

**Comment by BrennanConroy** [comment]
Reusing is fine, if there is a connection error then the channel will automatically reconnect.

**Comment by chris-brown** [comment]
From the [documentation](https://learn.microsoft.com/en-us/aspnet/core/grpc/retries?view=aspnetcore-6.0#streaming-calls), My understanding that any streaming RPC would not automatically reconnect. Can you provide best practice in how to do this? For example is it just as simple as creating a new client with the existing channel and the client will handle the reconnect or do you have to complete the request/response streams and manually create a new channel.

I feel theres lots to consider here and would benefit alot of people (at least me) with a best approach example?

Thanks,
