### ISSUE TITLE
How can clients cancel server-side streaming?

### ISSUE THREAD

**Issue by Goldenflamer** [grpc/grpc-dotnet#1735]
How can I cancel server-side streaming from the client-side (eg. when the client is shut down) correctly? 

I am currently using many different grpc services for client and server communication in Unity. The problem is that whenever the client is stopped it cannot be restarted anymore because it hangs, as there are still running threads in the background which aren't destroyed with the client. I cannot seem to find a way to close the grpc connections like you can do it with sockets.

Maybe someone could show me the correct way to close all grpc connections.

I currently got the following code in Unity:

  ```
          public async void SubscribeDistantTerrain()
            {
                using var call = _client.subscribeDistantTerrain(new UserAuth {Username = "Test"});
                
                var nextTask = call.ResponseStream.MoveNext();
                while (true)
                {
                    if (await Task.WhenAny(nextTask, Task.Delay(1000)) == nextTask)
                    {
                        foreach (var chunk in call.ResponseStream.Current.Chunks)
                        {
                            //Process data
                        }
                        nextTask = call.ResponseStream.MoveNext();
                    }
                    
                    if (!CommunicationState.Instance.IsGameRunning())
                    {
                        _channel.ShutdownAsync().Wait();
                        break;
                    }
                }
            }
```

Actually, the code above makes it possible that the client can be restarted after being stopped without hanging, because of the _channel.ShutdownAsync().Wait() call. But, also this call only finishes once the client is restarted, so the grpc connection stream stays open until a new client instance tries to connect.

**Comment by Goldenflamer** [comment]
It is super simple.

I just need to call _call.Dispose(); and _channel.ShutdownAsync().Wait(); afterwards.

**Comment by 1wayticket** [comment]
> How can I cancel server-side streaming from the client-side (eg. when the client is shut down) correctly?
> 
> I am currently using many different grpc services for client and server communication in Unity. The problem is that whenever the client is stopped it cannot be restarted anymore because it hangs, as there are still running threads in the background which aren't destroyed with the client. I cannot seem to find a way to close the grpc connections like you can do it with sockets.
> 
> Maybe someone could show me the correct way to close all grpc connections.
> 
> I currently got the following code in Unity:
> 
> ```
>         public async void SubscribeDistantTerrain()
>           {
>               using var call = _client.subscribeDistantTerrain(new UserAuth {Username = "Test"});
>               
>               var nextTask = call.ResponseStream.MoveNext();
>               while (true)
>               {
>                   if (await Task.WhenAny(nextTask, Task.Delay(1000)) == nextTask)
>                   {
>                       foreach (var chunk in call.ResponseStream.Current.Chunks)
>                       {
>                           //Process data
>                       }
>                       nextTask = call.ResponseStream.MoveNext();
>                   }
>                   
>                   if (!CommunicationState.Instance.IsGameRunning())
>                   {
>                       _channel.ShutdownAsync().Wait();
>                       break;
>                   }
>               }
>           }
> ```
> 
> Actually, the code above makes it possible that the client can be restarted after being stopped without hanging, because of the _channel.ShutdownAsync().Wait() call. But, also this call only finishes once the client is restarted, so the grpc connection stream stays open until a new client instance tries to connect.

We are using grpc dot_net in our unity 2d mobile project（.net standard2.1/Unity 2021/VS 2021),but out client can not connet to our server even we try GrpcWebClient and other methods. so can you share your experience about grpc in unity? thanks a lot!
