### ISSUE TITLE
System.MissingMethodException when DeadlineExceeded

### ISSUE THREAD

**Issue by semihokur** [grpc/grpc-dotnet#1736]
### What version of gRPC and what language are you using?
2.46.0-pre1, C#

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.net 6

### What did you see instead?
```
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task Grpc.Core.IAsyncStreamWriter`1.WriteAsync(!0, System.Threading.CancellationToken)'.
at void Grpc.Net.Client.Internal.GrpcCall<TRequest, TResponse>.CancelCall(Status status) in /_/src/Grpc.Net.Client/Internal/GrpcCall.cs:line 436
at void Grpc.Net.Client.Internal.GrpcCall<TRequest, TResponse>.DeadlineExceeded() in /_/src/Grpc.Net.Client/Internal/GrpcCall.cs:line 1050
at void Grpc.Net.Client.Internal.GrpcCall<TRequest, TResponse>.DeadlineExceededCallback(object state) in /_/src/Grpc.Net.Client/Internal/GrpcCall.cs:line 1022
at void System.Threading.TimerQueueTimer.Fire(bool isThreadPool)
at void System.Threading.TimerQueue.FireNextTimers()
```

**Comment by JamesNK** [comment]
This error is weird. `IAsyncStreamWriter`1.WriteAsync(!0, System.Threading.CancellationToken)` was recently added as a default interface implementation. 2.46.0-pre1 requires Grpc.Core.Api of 2.45.0 which has this method:

![image](https://user-images.githubusercontent.com/303201/167956947-0b43af1f-504a-4912-a332-66f9dc15e367.png)

I don't know why .NET would say the method is missing.

Can you provide a repo that recreates this?

**Comment by semihokur** [comment]
We use 2.46.0-pre1 for grpc.core as well: https://github.com/microsoft/BuildXL/blob/8a780f4bee0d409dc8e28404bc0e84fe54c902bb/config.nuget.grpc.dsc#L20

It would be hard to have a repro as this is BuildXL. We still do not use grpc.net in production, and we have been validating it in a separate environment. We first had issues with UnobservedTaskExceptions after failed calls. We upgraded to 2.46.0 due to your recent fix for those exceptions.

**Comment by JamesNK** [comment]
The only way I can think this happens is an older version of Grpc.Core.Api (2.44.0 or earlier) is being loaded by the app at runtime.

**Comment by halter73** [comment]
@semihokur Can you provide us your `project.assets.json` in your obj directory? This should show us all your dependencies and versions.

**Comment by semihokur** [comment]
Thanks for the responses. It is clear that we somehow fail to use the latest (>=2.45.0) grpc.core.api. I close the issue. 
@halter73 we do not have project.assets.json files as BuildXL uses a custom nuget resolver.
