### ISSUE TITLE
Client streaming fails at max buffer size with grpc-web / Grpc.Net.Client.Web and .NET FW 4.8

### ISSUE THREAD

**Issue by mooware** [grpc/grpc-dotnet#1738]
### What version of gRPC and what language are you using?

C#, .NET Framework 4.8
Grpc.Net.Client 2.44.0
Grpc.Net.Client.Web 2.44.0

### What operating system (Linux, Windows,...) and version?

Windows 10 20H2

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)

```
.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.201\

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91
[grpcweb.zip](https://github.com/grpc/grpc-dotnet/files/8680285/grpcweb.zip)

.NET SDKs installed:
  3.1.302 [C:\Program Files\dotnet\sdk]
  3.1.415 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]
  6.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### What did you do?

When implementing a grpc client with .NET FW 4.8 and Grpc.Net.Client.Web (server is .NET 6), I encountered an issue when streaming from client to server. After sending enough messages, I am getting the exception `"System.Net.Http.HttpRequestException: Cannot write more bytes to the buffer than the configured maximum buffer size: 2147483647."`. It seems that even though it should be streaming, all messages are buffered and only sent when calling CompleteAsync() on the RequestStream. In the other direction, from server to client, streaming seems to work infinitely as expected, at least well past the amount that causes the exception in the other direction.

See the attached source code for a sample application to reproduce the issue. Run the client with `"--send --endless https://localhost:7299"`, it should fail at ~428.8k messages.

### What did you expect to see?

Being able to stream endlessly from client to server, with the messages not being buffered, or not buffered for long at least. Also having the server receive messages before the client has finished streaming.

### What did you see instead?

The messages seem to be buffered until the client completes the stream, causing it to reach a size limit in the http request.

```
Unhandled Exception: System.Net.Http.HttpRequestException: Cannot write more bytes to the buffer than the configured maximum buffer size: 2147483647.
   at System.Net.Http.HttpContent.LimitMemoryStream.CheckSize(Int32 countToAdd)
   at System.Net.Http.HttpContent.LimitMemoryStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Grpc.Net.Client.StreamExtensions.WriteAsync(Stream stream, ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at Grpc.Net.Client.StreamExtensions.<WriteMessageAsync>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Net.Client.Internal.HttpContentClientStreamWriter`2.<WriteAsyncCore>d__19`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at grpctestclient.Program.<RunSend>d__1.MoveNext() in C:\workspaces\misc\grpcweb\client\Program.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at grpctestclient.Program.<Main>d__0.MoveNext() in C:\workspaces\misc\grpcweb\client\Program.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at grpctestclient.Program.<Main>(String[] args)
```

**Comment by JamesNK** [comment]
Client and bidirectional streaming isn’t supported.  Only server streaming is supported.

**Comment by mooware** [comment]
The documentation does not make that very clear, at least here: https://docs.microsoft.com/en-us/aspnet/core/grpc/browser?view=aspnetcore-5.0

> Traditional gRPC over HTTP/2 supports streaming in all directions. gRPC-Web offers limited support for streaming:
> 
> - gRPC-Web browser clients don't support calling client streaming and bidirectional streaming methods.
> - ASP.NET Core gRPC services hosted on Azure App Service and IIS don't support bidirectional streaming.
>
> When using gRPC-Web, we only recommend the use of unary methods and server streaming methods.

It says "browser clients don't support calling client streaming", which sounds like other client types can support it.

**Comment by JamesNK** [comment]
Client streaming with gRPC-Web **_might_** succeed if you're using a runtime that supports HTTP/2. However, .NET Framework only supports HTTP/1.1.

I think it's safest for the docs to just say client streaming isn't supported. gRPC-Web is design to work with HTTP/1.1.

**Comment by JamesNK** [comment]
PR to update docs: https://github.com/grpc/grpc-dotnet/issues/1738

I added an extra bullet point about .NET over HTTP/1.1. I think the summary at the bottom is the best recommendation:

> When using gRPC-Web, we only recommend the use of unary methods and server streaming methods.
