### ISSUE TITLE
Publishing to Azure

### ISSUE THREAD

**Issue by daltonks** [grpc/grpc-dotnet#174]
Is this possible at this time?
I am able to run a localhost server using the prerelease package and the new template, but I am having difficulties figuring out how to configure my GRPC server to work when published to Azure (as self-contained).
I am trying different ports and different forms of the host name, but nothing has been working. I've also tried to configure kestrel to listen on a port that's not 80, and that's not working either.

Is there an example project that is configured for Azure publishing?

Thank you

**Comment by daltonks** [comment]
Today I tried binding to 443 and using a certificate generated for my Azure domain name. Couldn't get that working either, but I might not be generating the certificate properly. Not sure how to get meaningful GRPC logs out of the running service in Azure.

I also attempted putting my generated .pfx into the Azure UI, setting the HTTP type to HTTP 2, forcing HTTPS, and making sure all the other configuration looks good and no bones.

I'll just delete my App Service Plan for now and come back to the problem later.

**Comment by shirhatti** [comment]
The HTTP/2 implementation on Azure App Service doesn't support response trailers and ergo doesn't support gRPC. For the time being, you're best is to run on AKS

**Comment by daltonks** [comment]
Thanks for the info.
I am also trying to run it on my Ubuntu NUC at home, and I am getting Kestrel errors saying "HTTP/2 over TLS was not negotiated on an HTTP/2-only endpoint."
Not sure if anyone knows if that's supposed to happen as well.

**Comment by shirhatti** [comment]
What client are you using? Sounds like your client doesn't claim to support HTTP/2 as part of ALPN.

https://github.com/aspnet/AspNetCore/blob/master/src/Servers/Kestrel/Core/src/Internal/HttpConnection.cs#L333-L336

**Comment by daltonks** [comment]
It is a Xamarin.Forms UWP project using Grpc.Core v1.19.0, Xamarin.Forms 3.6.0.22.0655, and Microsoft.NETCore.UniversalWindowsPlatform v6.2.8.

**Comment by daltonks** [comment]
Aha! I figured out why it wasn't connecting to a non-localhost CN.
My problem was that I wasn't generating the certs properly. I set my client CN to the domain when generating the client.csr 🤦‍♂️.
