### ISSUE TITLE
get the Metadata Headers

### ISSUE THREAD

**Issue by inforzip** [grpc/grpc-dotnet#1748]
How to get the Metadata Headers sent by the grpc client channel in the constructor of a service on server side.
 ```
public class CompanyService : RemoteCompany.RemoteCompanyBase
 {
        private readonly ILogger<CompanyService> _logger;

        public CompanyService(ILogger<CompanyService> logger)
        {
            _logger = logger;

            // I need to catch here the metadata headers
           // something like this
           // var metadataEntry = context.RequestHeaders.FirstOrDefault(m => String.Equals(m.Key, "metadataName", StringComparison.OrdinalIgnoreCase));
        }
(...)
}
```
I already tried to inject ServerCallContext but it is not possible, How to work around the situation
A clue or a small example would help a lot.
Thanks in advance

**Comment by JamesNK** [comment]
This is kind of an odd thing to do, but I think it can be done.

1. Follow the instructions here to get the `HttpContext` in the constructor: https://nodogmablog.bryanhogan.net/2019/09/accessing-the-httpcontext-from-the-constructor-of-a-controller-or-a-dependency/

3. Get the `ServerCallContext` from the `HttpContext` by calling `var serverCallContext = httpContext.Features.Get<IServerCallContextFeature>()?.ServerCallContext;`
