### ISSUE TITLE
Improve get-dotnet.ps1 script to install onto default path

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#175]
By default https://github.com/grpc/grpc-dotnet/blob/master/build/get-dotnet.ps1 is installing into the user's profile directory. This is accessible when building with `dotnet run` in PS but not VS. Likely the problem is the user's profile directory is not in the path.

We should install the nessessary version of .NET into a location that works for building via the commandline in CI *and* developing in Visual Studio.

**Comment by JunTaoLuo** [comment]
We need the -InstallDir <DIRECTORY> or --install-dir <DIR> options to be set.

**Comment by JamesNK** [comment]
@mgravell as a temporary work around you could install using the script above and adding the profile install location to `Path` environment variable in Windows.

**Comment by mgravell** [comment]
Thanks, will try.

**Comment by mgravell** [comment]
no luck with path hacks; I tried manually copying the extra SDK folder, but that resulted in:

```
C:\code\grpc-dotnet>dotnet build
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '3.0.0-preview4-27518-02' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\
```

I can build from PS for now, but... yeah, this doesn't make playing easy.

**Comment by mgravell** [comment]
I got it working by manually copying both the sdk and the relevant `\shared\Microsoft.NETCore.App` folder over to the program-files location
