### ISSUE TITLE
DbContext per service call

### ISSUE THREAD

**Issue by inforzip** [grpc/grpc-dotnet#1754]
It is possible to create a dbcontext per service call.?
I mean a dbcontext with lifetime of the service call.
How could this be achieved?

**Comment by JamesNK** [comment]
Yes. It works the same way as MVC via dependency injeciton.

**Comment by JamesNK** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
