### ISSUE TITLE
For bi-directional streaming calls failure can we expect all responses to be delivered to client

### ISSUE THREAD

**Issue by vangarp** [grpc/grpc-dotnet#1755]
For bi-directional streaming calls, suppose the client is streaming data to the server and server does not like something in it and decides to end the call with an error status (invalid argument for example), but before setting the status the server sends a final response which indicates some more details on the error etc. Can we expect the client to always receive the final response message with MoveNext() before it throws an RpcException? Or is that not always guaranteed?

**Comment by chwarr** [comment]
(Related: see issue [#303, Add support for the richer error model for gRPC ("google.rpc.status")](https://github.com/grpc/grpc-dotnet/issues/303) for a possible alternative approach that uses RpcException + trailers to send structured information and a failure at the same time.)

**Comment by vangarp** [comment]
Right https://github.com/grpc/grpc-dotnet/issues/1011#issuecomment-669615266 seems to suggest that if we send a response before returning the status then client should be able to read that final message before MoveNext() throws an RpcException with the details, however I am seeing that that is not the case

**Comment by JamesNK** [comment]
> Can we expect the client to always receive the final response message with MoveNext() before it throws an RpcException? Or is that not always guaranteed?

I would expect that the client can read the final response message. HTTP/2 frames are sent and received in order. The client should read the final request frames, and then read the error afterwards.
