### ISSUE TITLE
Error starting gRPC call. InvalidDataException: Unexpected data after finished reading message.

### ISSUE THREAD

**Issue by staunchheart** [grpc/grpc-dotnet#1757]
grpc on .net 6   
Grpc.AspNetCore 2.46.0   /2.45.0
Grpc.Net.Client 2.46.0   /2.45.0

server:
  var host = Host.CreateDefaultBuilder(args)
                   .ConfigureWebHostDefaults(webBuilder =>
                   {
                       webBuilder.ConfigureKestrel(options =>
                    {
                        options.ListenAnyIP(5002, o => {
                            o.Protocols = Microsoft.AspNetCore.Server.Kestrel.Core.HttpProtocols.Http2;
                        });
                    });
                       webBuilder.UseStartup<Startup>();
                   });

client :
  ..... static mClient

    var rep = await mClient.CallAsync(new Frame.Rpc.GRpc.GrpcRequest()

95% OK 
5%   Get  Exception

Status(StatusCode="Internal", Detail="Error starting gRPC call. InvalidDataException: Unexpected data after finished reading message.", DebugException="System.IO.InvalidDataException: Unexpected data after finished reading message.
   at Grpc.Net.Client.StreamExtensions.ReadMessageAsync[TResponse](Stream responseStream, GrpcCall call, Func`2 deserializer, String grpcEncoding, Boolean singleMessage, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")

**Comment by JamesNK** [comment]
Could you provide a simple app that reproduces this problem? That way I can debug it and see exactly what is going on.

**Comment by staunchheart** [comment]
TKS ,
I mistakenly used task on server.
