### ISSUE TITLE
Client load balancing & SRV record DNS config

### ISSUE THREAD

**Issue by plombaer** [grpc/grpc-dotnet#1758]
Dear,

My service is hosted under IIS (https) and JWT is used for authentication/authorization.
The IT person configured an SRV record DNS but I'm not sure he did it correctly.
I'm getting the following error:
'Status(StatusCode="Unavailable", Detail="Error getting DNS hosts for address 'grpcpocclientsideloadbalancing.400dev.rsvzinasti.be'. SocketException: The requested name is valid, but no data of the requested type was found."
The DNS config:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/15078623/169888363-76aaf6d5-241f-408b-983f-f3298b6ba7a8.png)

My code looks like this:
```
            var credentials = CallCredentials.FromInterceptor((c, m) =>
            {
                m.Add("Authorization", "Bearer " + GetStsClaim());
                return Task.CompletedTask;
            });

            var clientHandler = new SocketsHttpHandler();
            clientHandler.UseProxy = false;

            var handler = new SubdirectoryHandler(clientHandler, "/TestGrpc");
            var channel = GrpcChannel.ForAddress("dns:///grpcpocclientsideloadbalancing.400dev.rsvzinasti.be",
                new GrpcChannelOptions 
                {
                    HttpHandler = handler,
                    Credentials = ChannelCredentials.Create(ChannelCredentials.SecureSsl, credentials),
                    ServiceConfig = new ServiceConfig
                    {
                        LoadBalancingConfigs = { new RoundRobinConfig() }
                    }
                });
            var client = new Greeter.GreeterClient(channel);

            var request = new HelloRequest();
            request.Name = "test";

            var reply = await client.SayHelloAsync(request);

```

Calling Dns.GetHostAddresses("grpcpocclientsideloadbalancing.400dev.rsvzinasti.be") returns
'No such host is known.'

Could you help me find what is wrong with my config ?
Thanks in advance

**Comment by JamesNK** [comment]
`Dns.GetHostAddresses` gets A records. It doesn't resolve SRV records.

**Comment by plombaer** [comment]
> `Dns.GetHostAddresses` gets A records. It doesn't resolve SRV records.

it throws an exception:
System.Net.Sockets.SocketException: 'No such host is known.'

**Comment by JamesNK** [comment]
I suggest you ask about it on StackOverflow. I'm not an expert at DNS or how that particular API works.

**Comment by plombaer** [comment]
> I suggest you ask about it on StackOverflow. I'm not an expert at DNS or how that particular API works.
https://stackoverflow.com/questions/72362135/grpc-net6-client-load-balancing-srv-record-dns-config

**Comment by plombaer** [comment]
Hi,
When I use nslookup I can access the SRV record DNS
![image](https://user-images.githubusercontent.com/15078623/172043900-919c93e4-a97f-4186-9397-b80f0769093a.png)
I still fails with gRPC.
