### ISSUE TITLE
TestServer.SendAsync when testing grpc middleware

### ISSUE THREAD

**Issue by jernejg** [grpc/grpc-dotnet#1759]
Hey, my question is related to writing integration tests for grpc middleware. As shown in the documentation [Test ASP.NET Core middleware - Send requests with HttpContext](https://docs.microsoft.com/en-us/aspnet/core/test/middleware?view=aspnetcore-6.0#send-requests-with-httpcontext) :
```csharp
var context = await server.SendAsync(c =>
{
    c.Request.Method = HttpMethods.Post;
    c.Request.Path = "/and/file.txt";
    c.Request.QueryString = new QueryString("?and=query");
});
```
It is quite easy to get access to `HttpContext` on the server side if you are writing tests for a REST Api server. But what about when you are writing integration tests for a grpc server? My attempt:

```csharp
var httpContext = await factory.Server.SendAsync(context =>
{
    context.Request.Method = HttpMethods.Post;
    context.Request.Headers.Add("grpc-accept-encoding", new StringValues("identity,gzip"));
    context.Request.Headers.Add("Content-Type", new StringValues("application/grpc"));
    context.Request.Path = "/path.to.grpc.service.v1.SomeAPI/DoStuff";
    //
    //complex code for populating `context.Request.Body` with a grpc request payload ??
    //
});
```
I'm wondering if there is a better way to do this than manually like I'm trying to do above. Or is there an easy way to provide grpc body content?

**Comment by JamesNK** [comment]
I would use the gRPC client to create the request. That avoids you having to manually create requests.

https://docs.microsoft.com/en-us/aspnet/core/grpc/test-services?view=aspnetcore-6.0#integration-test-grpc-services

**Comment by jernejg** [comment]
Hi James, thanks for replying.

This is the gist of my question actually. If I use gRPC client, there is no way (I'm aware of) to access `HttpContext` associated with the request.

`SendAsync` has this nice feature as you can see from the signature as well, that it returns the `HttpContext`:
```csharp
public Task<HttpContext> SendAsync (Action<HttpContext> configureContext, CancellationToken cancellationToken = default);
```

> Use [SendAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.testhost.testserver.sendasync) to manipulate structures only available on the server, such as [HttpContext.Items](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpcontext.items#microsoft-aspnetcore-http-httpcontext-items) or [HttpContext.Features](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpcontext.features#microsoft-aspnetcore-http-httpcontext-features).

**Comment by JamesNK** [comment]
No you can't. I'm not sure why you'd want to.

**Comment by jernejg** [comment]
For Testing ASP.NET Core middleware. That is the purpose of `TestServer.SendAsync` as per documentation [Test ASP.NET Core middleware](https://docs.microsoft.com/en-us/aspnet/core/test/middleware?view=aspnetcore-6.0#send-requests-with-httpcontext).

Your question makes me think I'm doing something wrong :/

But then why would `TestServer.SendAsync` exist? The difference is just that I'm writing an integration test for a grpc server and the documentation shows calling a simple `POST` to trigger the call.

**Comment by JamesNK** [comment]
It's a way to send requests to test server. With gRPC, it's easier to have the client create the request. From the same page: https://docs.microsoft.com/en-us/aspnet/core/test/middleware?view=aspnetcore-6.0#send-requests-with-httpclient

**Comment by jernejg** [comment]
> It's a way to send requests to test server without having to mess with HttpClient. I've never used it before.

But it is not just that right? It is also the only way to access the `HttpContext` associated with the request you sent, so that you can assert it.

**Comment by JamesNK** [comment]
> But it is not just that right? It is also the only way to retrieve the `HttpContext` associated with the request you sent, so that you can assert it in the end.

If you want to assert the `HttpContext` after a request is complete then register a middleware that captures it to a variable and assert it after the request is complete.

```csharp
[Fact]
public async Task MiddlewareTest_ReturnsNotFoundForRequest()
{
    HttpContext lastContext = null;

    using var host = await new HostBuilder()
        .ConfigureWebHost(webBuilder =>
        {
            webBuilder
                .UseTestServer()
                .ConfigureServices(services =>
                {
                    services.AddMyServices();
                })
                .Configure(app =>
                {
                    app.Use((c, next) =>
                    {
                        lastContext = c;
                        next(c);
                    });
                    app.UseMiddleware<MyMiddleware>();
                });
        })
        .StartAsync();

    var response = await host.GetTestClient().GetAsync("/");

    Assert.NotNull(lastContext);
}
```

**Comment by jernejg** [comment]
Thanks James, I was thinking in the same direction, but 
- it kind of felt like a hack
- I'm using `WebApplicationFactory<Program>` to set up the TestServer and `Configure` is already declared in `Program` so using it again in the test seems to replace the original delegate. Is there a way to add my custom test specific middleware on top any configuration already declared in Program?

**Comment by jernejg** [comment]
This is my current attempt to perform a grpc call manually in `SendAsync` :grimacing:

```csharp
var sendAsync = await factory.Server.SendAsync(context =>
{
    context.Request.Method = HttpMethods.Post;
    context.Request.Headers.Add("grpc-accept-encoding", new StringValues("identity,gzip"));
    context.Request.Headers.Add("TE", new StringValues("trailers"));
    context.Request.Headers.Add("Content-Type", new StringValues("application/grpc"));
    context.Request.Path = "/path.to.grpc.service.v1.SomeAPI/DoStuff";
    var grpcRequest = new GrpcRequest()
    {
        //init request message
    };
    var ms = new MemoryStream();
    ms.WriteByte(0); //set compression to none
    var span = new Span<byte>(new byte[4]);
    BinaryPrimitives.WriteUInt32BigEndian(span, (uint) revokeRequest.CalculateSize());
    ms.Write(span); //set the length of the message
    revokeRequest.WriteTo(ms);
    ms.Position = 0;
    context.Request.Body = ms;
});
```
It seems to be working and does the trick. But I guess in this form its even a bigger hack then registering a capturing middleware.

**Comment by JamesNK** [comment]
Closing as answered.
