### ISSUE TITLE
how to Detect Client connection and  Disconnection in Server using grpc donet?

### ISSUE THREAD

**Issue by zhoudeji** [grpc/grpc-dotnet#1761]
how to Detect Client connection and  Disconnection in Server? Thanks.

**Comment by BrennanConroy** [comment]
Could you explain your scenario here and what you're trying to do?

**Comment by chwarr** [comment]
> how to know the client IP in the server ?

Are you looking for [`ServerCallContext.Peer`](https://cloud.google.com/dotnet/docs/reference/Grpc.Core/latest/Grpc.Core.ServerCallContext#Grpc_Core_ServerCallContext_Peer), "Address of the remote endpoint in URI format"?

**Comment by JamesNK** [comment]
You could write connection middleware.

This isn't a well-documented feature, but you can see an example that's part of the ASP.NET Core framework here: https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/Servers/Kestrel/Core/src/Middleware/LoggingConnectionMiddleware.cs
