### ISSUE TITLE
Nuget Package Update

### ISSUE THREAD

**Issue by EchoSlam** [grpc/grpc-dotnet#1762]
Please Update the Nuget Package Since you have new commit, the last update time is still 2021/06/18, thank you!

**Comment by gfoidl** [comment]
@EchoSlam can you please share where did you look for that?

In https://www.nuget.org/packages?q=Tags%3A%22gRPC%22 the last package upload is just a couple of days old.

**Comment by JamesNK** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
