### ISSUE TITLE
xamarin   keep alive 

### ISSUE THREAD

**Issue by SalimiHabib** [grpc/grpc-dotnet#1766]
Can not find Keep alive setting in xamarin  , also there is no  `SocketsHttpHandler `in xamarin .

How to set **Keep alive**  in **xamarin** to detect disconnected network for server streaming ?

**Comment by JamesNK** [comment]
It's not supported. MAUI will have some support for SocketsHttpHandler so you might be able to use it there.

grpc-dotnet isn't officially supported on Xamarin/MAUI with HTTP/2. That's something we're looking at improving in .NET 7.
