### ISSUE TITLE
Difference between AddGrpcHealthChecks and AddHealthChecks

### ISSUE THREAD

**Issue by EvyaB** [grpc/grpc-dotnet#1768]
In my project, we have both REST and gRPC endpoints. We also have HealthChecks that are currently available through REST, and wanted to add gRPC healthchecks. I've followed [this instructions](https://docs.microsoft.com/en-us/aspnet/core/grpc/health-checks?view=aspnetcore-6.0) but came across some unexpected behavior (for me at least).

I've managed to create and access the endpoint correctly, and added a single health check that always succeeds:
`services.AddGrpcHealthChecks().AddCheck("", () => HealthCheckResult.Healthy());`
but every time I've accessed the gRPC HealthCheck endpoint I've received NotServing status.  

I've researched this and found out the cause - turns out it checks every HC in the project, regardless if it was registered as an gRPC or REST HC, and since some of my REST HC were failing I was receiving NotServing.
More specifically, the GrpcHealthChecksPublisher::PublishAsync method that runs the list of gRPC health checks gets a list of all the HC, not only HC that were registered with AddGrpcHealthCheck. There is a predicate to filter the HC list, but that predicate is by default defined in GrpcHealthChecksServiceExtensions::AddGrpcHealthChecks as always true, so it doesn't actually filter anything out.

On one hand, it does make some sense that the HC are shared - gRPC/REST is just a protocol, and the program logic shouldn't depend on the protocol.  On the other hand, part of the reason we wanted to add both gRPC and REST endpoints was to have a simple test checking if the gRPC/REST connections are even possible from our services, and those do not necessarily depend on one another, though I guess that can be solved with tags. 
Assuming this all is on purpose and the HC should be shared, what is the point in having different AddGrpcHealthChecks and AddHealthChecks calls?

**Comment by halter73** [comment]
I'm guessing `AddGrpcHealthChecks` adds a `IHealthCheckPublisher` so you don't have to notify both `MapGrpcHealthChecksService()` and `MapHealthChecks()` of status issues assuming you're using both. You can register more than one `IHealthCheckPublisher`.

If you want to have different statuses for normal HTTP health checks and gRPC health checks, I'm not sure that's possible outside of removing the `GrpcHealthChecksPublisher : IHealthCheckPublisher` from the `IServiceCollection` and invoking it manually. I wouldn't recommend this since it seems like the kind of implementation detail that is likely to break in future releases. Using separate hosts would be less fragile if possible. Are there any other options @JamesNK?

**Comment by EvyaB** [comment]
I've managed to limit the gRPC to only utilize specific health checks by calling Services.MapService inside the AddGrpcHealthChecks in the server side and using a tag like this:
```
services.AddGrpcHealthChecks(o =>
                    o.Services.MapService("", r => r.Tags.Contains("grpc"))).AddCheck("my test", () => HealthCheckResult.Healthy(), new[] { "grpc", "live" });
```
This is definitely workable for me, and does make sense to me that the HC can be shared so they don't need to be defined multiple times in cases we want multiple access points to the same tests. However I still think the methods are confusing.

I think the problem is that AddHealthChecks/AddGrpcHealthChecks methods do two separate things:
1.  Add services handling the flow behind the scenes (the IHealthCheckPublisher and such) which are different between gRPC and REST.
2. Create & return an IHealthChecksBuilder which is used to add the actual health checks, but is the same for both gRPC and REST health checks.

**Comment by JamesNK** [comment]
The purpose of `AddGrpcHealthChecks` is to integrate ASP.NET health checks with the gRPC health service.

If you don't want the gRPC health service to use ASP.NET health checks then you could use `Grpc.HealthCheck` directly.

1. Reference Grpc.HealthCheck package
2. Register an instance of the implementation and add a status for `""`.
3. Register the service with MapGrpcService.

See https://github.com/grpc/grpc-dotnet/pull/1793 as an example.
