### ISSUE TITLE
gRPC Client Factory does not correctly pool the underlying HttpMessageHandler

### ISSUE THREAD

**Issue by RobbyScherpereel** [grpc/grpc-dotnet#1769]
### What version of gRPC and what language are you using?
Grpc.Net.ClientFactory 2.46.0

### What operating system (Linux, Windows,...) and version?
Windows 11 Enterprise - 21H2

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
PM> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300\

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  3.1.419 [C:\Program Files\dotnet\sdk]
  5.0.404 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

### What did you do?
We are starting to use the GrpcClientFactory (https://www.nuget.org/packages/Grpc.Net.ClientFactory) in our new .net 6 project and I encounter an issue, 
at least for us it is an issue, maybe it is by design but it is blocking me at the moment.

Here is the situation:
We are using Blazor Server.
Via DI I am registering the client as follows (pseudo code):

```
services.AddGrpcClient<Health.HealthClient>(options => options.Address = new Uri($"https://someuri"))
    .ConfigurePrimaryHttpMessageHandler(sp => {
        var proxyProvider = sp.GetRequiredService<IProxyProvider>();
        return new HttpClientHandler { Proxy = proxyProvider.CreateWebProxy() } 
});
```
As you can see we are configuring the underlying HttpMessageHandler and are setting some proxysettings on it.. proxyPovider is also registered as transient on the DI and is retrieved via the ServiceProvider here.
proxyProvider is getting ProxySettings from a database via EFcore.

As I understand, the grpc clients are also registered as transient by the factory, right?
And I also know about the HandlerLifetime being set on 2 minutes, although it is in the normal IHttpClientFactory, not sure if it is the same here… could not find any info on this..

My issue is now as follows: the end user can enable or disable these proxy settings in the front end, and when saving, the settings are saved in the database. I have some component which Injects a transient service which uses the GrpcClient which on his turn is injected via the constructor..
I can see that the service is realy injected every time the component activates (breakpoint in the constructor is hit) but the inline HttpClient of the GrpcClient is never refreshed, even if the client should be transient, and so this proxy setting is always the same until I restart the application..
I did try putting the SetHandlerLifetime on 5 seconds as a test but did not help..

I have the same setup with a normal HttpClient, also injected with the IHttpClientFactory and there I can see that the HttpClientHandler gets refreshed by the factory once the HandlerLifetime has exceeded..

I hope I explained it clearly enough.. and I hope you can give us some insights on following:
Do the HttpMessageHandler works differently in GrpcClientFactory vs IHttpClientFactory?
Do you have any idea why the Underlying HandlerLifetime is not pooled out after the 2 min?
Do I see it wrong, and is it perhaps a misconfig somewhere or could it be a bug in the library?

### What did you expect to see?
The underlying HttpMessageHandler (and thus the Proxy settings along with it) should be cleaned after the HandlerLifetime exceeds?

### What did you see instead?
The underlyting HttpMessageHandler is not cleaned and we are always using the same..

**Comment by RobbyScherpereel** [comment]
Thanks for your answer @JamesNK .
At least I know it is not an issue in my config and I was right in my conclusion.

It is confusing that we could set the handler lifetime using SetHandlerLifetime while it is not doing anything.. But yeah it is a wrapper on the normal IHttpClientFactory so you cannot really do it differently I guess, unless you can update the XmlDocs for it on the GrpcClientFactory.

It could indeed definitely help if it was mentionned on the docs somewhere.

Let me know if you are going to change this expiry of channels in future.
For now we can close the issue.

**Comment by rafikiassumani-msft** [comment]
Triage: Closing the issue per author request.
