### ISSUE TITLE
`Deadline` precedence when `EnableCallContextPropagation` is on

### ISSUE THREAD

**Issue by jernejg** [grpc/grpc-dotnet#1774]
Hey,

I read the docs and looked at `ContextPropagationInterceptor` but I can't understand which `Deadline` will take precedence. The one from the current context or the one that is optionally passed to the client when making a grpc call?

Thank you.

**Comment by JamesNK** [comment]
The shortest value deadline is used - https://github.com/grpc/grpc-dotnet/blob/543c363c5e601eb9d5fe170758f6b989891dae63/src/Grpc.AspNetCore.Server.ClientFactory/ContextPropagationInterceptor.cs#L141-L145

Doc update - https://github.com/dotnet/AspNetCore.Docs/pull/26208
