### ISSUE TITLE
auto generated files should not have warnings

### ISSUE THREAD

**Issue by Varorbc** [grpc/grpc-dotnet#1779]
### What did you expect to see?

no warn

### What did you see instead?

![image](https://user-images.githubusercontent.com/5714438/174767580-60ef7236-5d7d-4a42-9516-fd83757d3476.png)

**Comment by JamesNK** [comment]
Known issue. This has been fixed in Protobuf and Grpc.Tools. We're waiting for dependencies to update. Add `<NoWarn>` to your project to suppress it.

**Comment by JamesNK** [comment]
You're welcome to work around the warning however you like until the fix is available.
