### ISSUE TITLE
DnsResolver - using A record type instead of SRV record type

### ISSUE THREAD

**Issue by tichaczech** [grpc/grpc-dotnet#1787]
gRPC Client-side load balancing documentation states, that DnsResolver (created by DnsResolverFactory) is using SRV record for resolving service address(es). This makes sense as the SRV record name for gRPC load balancing is well defined (https://github.com/grpc/proposal/blob/master/A5-grpclb-in-dns.md) and also the port is part of the SRV record. So far so good.
<img width="767" alt="image" src="https://user-images.githubusercontent.com/1013280/175292487-db2c03b3-3e52-4ce8-9a57-8c93f1306656.png">

While trying to use this I found that the SRV record does not work as expected because implementation (https://github.com/grpc/grpc-dotnet/blob/master/src/Grpc.Net.Client/Balancer/DnsResolver.cs) is using A record, which is not just contrary to the documentation, but also makes no sense as the port is not part of A record and has to be _hardcoded_ in service URI. 
<img width="819" alt="image" src="https://user-images.githubusercontent.com/1013280/175292630-4b4c5b2f-5ffe-4288-97ff-9bec2a72ed17.png">

**Which record type should be used - SRV (as stated in documentation) or A (as used in implementation)?**

Just a side note - as client-side load balancing is relatively standard nowadays and rootless containers (with dynamic ports) are gaining popularity, we prefer to use SRV records as it should give us more control with less _hardcoded_ configuration.

**Comment by JamesNK** [comment]
The load balancing in the client isn't based on https://github.com/grpc/proposal/blob/master/A5-grpclb-in-dns.md?rgh-link-date=2022-06-23T11%3A55%3A59Z. That's the old spec.

Our doc is wrong. I'll update it to say A (and AAAA) records are used.

**Comment by tichaczech** [comment]
Understand! Thank you for your clarification.

BTW - Is there a place for an SRV address resolver? And if yes - where to start? I can prepare PR in a few days (as we are already working on it for our code base), but I can imagine that such _a proposal_ has to be in line with the roadmap.

**Comment by JamesNK** [comment]
There are instructions for adding your own resolve in the docs. The problem is there isn't a way to get SRV records built into .NET.

**Comment by tichaczech** [comment]
I was asking if you are interested in adding SRV resolver to Grpc.Net.Client (I am sorry, as a non-native speaker, I have some times trouble expressing myself 😄) - based on my experience this would be a more "real world" fit. But I understand your point that there is no (direct) way to get SRV records in plain .NET and using external libraries (like https://github.com/MichaCo/DnsClient.NET) is not an option (not talking options like P/Invoke 🤣).

On the other hand - this can be an external part, available as a NuGet package (like Grpc.Net.Client.DnsSrvResolver), but still under grpc-dotnet governance 😉.

**Comment by JamesNK** [comment]
No thankyou. I'll work with the .NET team to add built-in support for SRV in .NET 8. Grpc.Net.Client can use that in the future.

But you can write your own resolver now that uses the external package. It would be great if you put it on GitHub so other people to use it.

**Comment by tichaczech** [comment]
Considered as resolved, closing.
