### ISSUE TITLE
HealthCheckServiceImpl has noticable startup delay. Is it intended?

### ISSUE THREAD

**Issue by Maggus503** [grpc/grpc-dotnet#1790]
Hello,

I tried running gRPC health checks example from the Microsoft documentation:
https://docs.microsoft.com/en-us/aspnet/core/grpc/health-checks?view=aspnetcore-6.0

Then I wrote some simple integration tests to see how it works and I noticed that my test for CheckAsync() method fails unless I add a significant delay before the call. The error message (see below) would also indicate that such service doesn't exist which may be misleading. Is this intended behaviour?

![obraz](https://user-images.githubusercontent.com/36055845/175811361-2fe37c31-312a-48b7-ba33-84218e020839.png)

Source: https://github.com/Maggus503/grpc-hc-integration-test-example

I'm quite sure it is because the service name is added to the statusMap in HealthCheckServiceImpl when the GrpcHealthChecksPublisher is run for the first time.

**Comment by JamesNK** [comment]
Yes, it's intended, but it can be customized. The problem is the documentation doesn't talk about it.

I've improved the docs [here](https://github.com/grpc/grpc-dotnet/issues/1790). (note that there is some duplication)

Does that provide you with enough information?

**Comment by Maggus503** [comment]
@JamesNK yes, thank you. Would it be also possible to improve the error handling in the code? It's an exception with NotFound status and an empty message at this moment. I think that it is misleading.

**Comment by JamesNK** [comment]
It's part of the service contract - https://github.com/grpc/grpc/blob/ab7a8d382629c541f051e70167a9e221ad6d0aa2/src/proto/grpc/health/v1/health.proto#L43-L45
