### ISSUE TITLE
How can i response exception with details?

### ISSUE THREAD

**Issue by Juandavi1** [grpc/grpc-dotnet#1799]
Hi ! 

How Can I return an exception response with details ? 

i'm doing it like this

![image](https://user-images.githubusercontent.com/18731612/176710975-b5e7ed1e-f234-47b7-8b2c-7db5e31946f0.png)

but response details returned is empty 

![image](https://user-images.githubusercontent.com/18731612/176711087-d55309ac-d48e-4910-82ce-f7bc66a182b5.png)

and the metadata object has items 

![image](https://user-images.githubusercontent.com/18731612/176711601-4abcdd24-628b-4818-868d-aa9b2c522a0c.png)

these are our dependencies 

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/18731612/176712088-9e4cb041-73f1-4eea-9334-28c67582482b.png">

thanks

**Comment by JamesNK** [comment]
EnableDetailedErrors - https://docs.microsoft.com/en-us/aspnet/core/grpc/configuration?view=aspnetcore-6.0
