### ISSUE TITLE
Server logging

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#18]
Ensure we have sufficient server logging with appropriate log levels

**Comment by JunTaoLuo** [comment]
What logging would we need that's additional to the Kestrel logging that's currently available?

**Comment by JamesNK** [comment]
I haven't thought about it in detail.

Couple of examples that spring to mind:
* Logging the service method that is invoked for a request
* Logging protobuff serialization errors

**Comment by JamesNK** [comment]
This isn't urgent. It can happen after the sandbox code is here or in a fork.
