### ISSUE TITLE
Bad Grpc Response

### ISSUE THREAD

**Issue by skumari123** [grpc/grpc-dotnet#1807]
i am trying to interact Grpc Server and Client using .net version 3.1 and getting below error.I followed the below blog to make them work :
https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-6.0&tabs=visual-studio
 
I tried using the below statements in Client too to disable Https issue.

AppContext.SetSwitch(
    "System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2Support", true);

i got the below issue when i tried to make them work:

**Status(StatusCode="Internal", Detail="Bad gRPC response. Response protocol downgraded to HTTP/1.1.")**

Can anybody please help on this?

**Comment by JamesNK** [comment]
Are you using http or https?

When using http on .NET Core 3.1 the switch needs to be set before creating the channel. And the port must be HTTP/2 only.

See https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-6.0#call-insecure-grpc-services-with-net-core-client

If you're using https then the port needs to support HTTP/2.

**Comment by skumari123** [comment]
I am using Http  and i already did the above things you mentioned.
Is there anything else i could try.what are the other possibilities?

**Comment by JamesNK** [comment]
You could have a proxy on computer that is downgrading the request. Or TLS 1.2 is not supported on your computer, which is required for HTTP/2.

**Comment by skumari123** [comment]
This scenario works if i create new solutions for the projects but when i create projects under already existing solutions.it doesnt work.
What must be the reason?

**Comment by JamesNK** [comment]
I've given you a list of ways this situation could happen.

**Comment by skumari123** [comment]
Yes,but how come it works when i create new solutions in the computer .And it doesnt work for some other folders which are for some applications in the builder.

**Comment by JamesNK** [comment]
I don't know. I don't know exactly what you're doing but what you've described shouldn't matter.

**Comment by skumari123** [comment]
Hi,
Is it possible to connect to remote Grpc Server from local  client using IP
address.how do we do that?

**Comment by JamesNK** [comment]
Use `GrpcChannel.ForAddress`.

**Comment by skumari123** [comment]
I was able to resolve the issue on the remote server where i used IP
address and SSL to communicate with the client.
Now i am trying to connect the Grpc remote server from the local client but
i am not able to do so.There is a firewall here for the remote server.

when i am trying to execute the grpc client on the local desktop ,its not
able to run and the screen vanishes.
what can i do to overcome the firewall?Do i need to bypass it or Grpc
provides some way to do this?

**Comment by JamesNK** [comment]
gRPC doesn't provide a way to do this.

**Comment by skumari123** [comment]
i am able to connect to the remote server from the local desktop powershell
using command  test-netconnection myserver -port 1234
This means the remote server is getting connected from the local desktop
but when i run local client using grpc protocol ,it doesnt.

I am trying  to run the client exe file on local desktop and try connecting
it  to the remote server which is running ,the exe file vanishes with no
error or anything.
I am not sure if its the Grpc error or something to do with my local
desktop settings.
please suggest me what should i do in this?

**Comment by JamesNK** [comment]
I don't have enough information to provide any suggestions. You should have logging setup so you can capture what is going on in your app. Logging might provide some insight to what is happening.

**Comment by JamesNK** [comment]
Closing because of a lack of activity.
