### ISSUE TITLE
Grpc Client and Server on different folder

### ISSUE THREAD

**Issue by skumari123** [grpc/grpc-dotnet#1808]
I am trying to make server and client interact and i see its possible if they are under the same directory .But when i make them interact from different directories,it doesnt work.
Can somebody suggest me a way to specify the path or how should i achieve this.

i did the same directory Grpc Server and Client implementation using the below blog:
https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-6.0&tabs=visual-studio

Please suggest me how to do it for different directories.

**Comment by JamesNK** [comment]
I don't know what different directories means. The tutorial has different projects for the client and server and they're in different directories.

**Comment by skumari123** [comment]
my client is located under some other subdirectory and my server is under some other subdirectory.I am getting bad grpc response.How should i make them interact?

**Comment by JamesNK** [comment]
Source code in different directories has no impact.

**Comment by skumari123** [comment]
Then what could be the reason of the error?It says internal error as:
Status(StatusCode="Internal", Detail="Bad gRPC response. Response protocol downgraded to HTTP/1.1.")

Why does it work when i directly make them from the visual studio.But when i make them from the builder applications by opening their solutions.It shows above error.

**Comment by skumari123** [comment]
Any blog to follow for configuring launchsettings.json?

**Comment by skumari123** [comment]
Thank you.this issue got resolved.I just to create different solutions for the projects in different directories.
