### ISSUE TITLE
`GrpcChannelOptions.ServiceProvider` and `GrpcChannelOptions.ServiceConfig` are both experimental?

### ISSUE THREAD

**Issue by SIkebe** [grpc/grpc-dotnet#1809]
docs says that APIs for **custom resolvers and load balancers** are experimental.
>The APIs used to extend client-side load balancing are experimental. They can change without notice.

https://docs.microsoft.com/en-us/aspnet/core/grpc/loadbalancing?view=aspnetcore-6.0#write-custom-resolvers-and-load-balancers

However, `GrpcChannelOptions.ServiceProvider` and `GrpcChannelOptions.ServiceConfig` themselves are experimental accordings to thier xml documents.
https://github.com/grpc/grpc-dotnet/blob/a984c6d55c975cdce1eedd7aa3f687f5c6642a54/src/Grpc.Net.Client/GrpcChannelOptions.cs#L282-L288
https://github.com/grpc/grpc-dotnet/blob/a984c6d55c975cdce1eedd7aa3f687f5c6642a54/src/Grpc.Net.Client/GrpcChannelOptions.cs#L204-L212

You can use these APIs for built-in resolvers and load balancers, too, not just for custom resolvers and load balancers.
Are those xml documents corrext? (i.e. these APIs are both experimental regardless of their usage)
Or expermental for only custom resolvers and load balancers scenario as per the docs?

**Comment by SIkebe** [comment]
@JamesNK Any thoughts?

**Comment by JamesNK** [comment]
The APIs added to support load balancing were made experimental just in case they needed to change. They're unlikely to change.

**Comment by SIkebe** [comment]
@JamesNK Is there any plan to make these APIs GA? .NET 7 time-frame or later?

**Comment by JamesNK** [comment]
There have been some small changes to those APIs in the last year. I think the experimental comments will get removed later this year.

If there are more changes to those APIs, the changes will be minor.

**Comment by SIkebe** [comment]
Thanks!
