### ISSUE TITLE
Generated client as an ASP.NET Core service

### ISSUE THREAD

**Issue by jamiewinder** [grpc/grpc-dotnet#181]
I have an ASP.NET Core web application which I want to be able to talk to a GRPC service. 

The idiomatic way to do this would seem to be to create / add a service (e.g. `services.AddSingleton(new MyGrpcClient())`) for the client for the GRPC service, and allow this to be injected into my controller. However, since the channel has a very different lifespan to the individual clients, I'm not sure how best to do this.

It reminds me a little of `AddHttpClient<T>`, allowing specific channels / clients to be injected into specific controllers / services. Is there anything similar planned for GRPC?

**Comment by JamesNK** [comment]
There sure is - https://github.com/grpc/grpc-dotnet/pull/142

Note that it is being made to work with a new prototype managed gRPC client. This is not ready to be used for some months, but it is something we are aiming to support.

**Comment by jamiewinder** [comment]
Many thanks, that looks ideal. Looking forward to it!
