### ISSUE TITLE
Grpc Server in C++ and Grpc Client in C#

### ISSUE THREAD

**Issue by skumari123** [grpc/grpc-dotnet#1810]
Hi all,
i am trying to make Grpc Server in C++ interact with Grpc Client in C#. Is this Scenario possible?If yes ,can anybody please suggest me any blog or something to follow.
And what changes are to be made to the normal scenario given below:

https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-6.0&tabs=visual-studio

**Comment by skumari123** [comment]
I tried following the below blog.Is this blog good for C++ server side.The Git clone command given below doesnt work:

https://medium.com/@andrewvetovitz/grpc-c-introduction-45a66ca9461f

Some input on this would be good.

Thanks :-)

**Comment by JamesNK** [comment]
This isn't a place to ask for support on other gRPC implementations.
