### ISSUE TITLE
Does Bi-directional stream block until CompleteAsync?

### ISSUE THREAD

**Issue by M1XGear** [grpc/grpc-dotnet#1814]
Hi, I am new to gRPC and trying to understand bi-directional streaming through [Mailer example](https://github.com/grpc/grpc-dotnet/tree/master/examples/Mailer).

As I understand bi-directional streaming should be non blocking so I should be able to use single connection to send and receive messages simultaneously.
But as you can see in the attachment I am receiving messages back from the server only then `await call.RequestStream.CompleteAsync();` is called from client, but after that connection is closed and no more messages from Server can be received.

![image](https://user-images.githubusercontent.com/6458352/178136581-f604256d-2701-4b45-83a0-99ca3d079f56.png)

Is this intended behaviour or is it bug?

**Comment by M1XGear** [comment]
Modifications made to Client in Mailer project
1) 
```
await foreach (var message in call.ResponseStream.ReadAllAsync())
{
    ....
}

to

while (await call.ResponseStream.MoveNext())
{
    var message = call.ResponseStream.Current;
    ...
}
```
2)
```
var result = Console.ReadKey(intercept: true);
if (result.Key == ConsoleKey.Escape) { break; }

to

var result = Console.ReadLine();
if (string.IsNullOrEmpty(result)) { break; }
```

**Comment by M1XGear** [comment]
Modifications made to Client in Mailer project
1) 
```
await foreach (var message in call.ResponseStream.ReadAllAsync())
{
    ....
}

to

while (await call.ResponseStream.MoveNext())
{
    var message = call.ResponseStream.Current;
    ...
}
```
2)
```
var result = Console.ReadKey(intercept: true);
if (result.Key == ConsoleKey.Escape) { break; }

to

var result = Console.ReadLine();
if (string.IsNullOrEmpty(result)) { break; }
```

**Comment by JamesNK** [comment]
It works for me:

![image](https://user-images.githubusercontent.com/303201/178487937-482f2311-7c9d-42c1-aa12-c378e7067b23.png)

**Comment by M1XGear** [comment]
1) Just switched to http for convenience
2) Yeah I tried to run it in JetBrains Rider
3) Similar result running through `dotnet run`

I will try to test it on a different machine for clarity

FYI: `dotnet --version` 6.0.301

![image](https://user-images.githubusercontent.com/6458352/178649558-bbcfeb87-db21-40cb-8c90-650992deebda.png)

**Comment by JamesNK** [comment]
I don't know what is causing this. The same code runs fine on my machine. And no one else has ever reported this issue. I can only guess that there is something about your computer, like a proxy, is doing something to the HTTP request.

**Comment by M1XGear** [comment]
So the reason of this behaviour on my PC was Kaspersky antivirus interfering with network connections.
After shutting it down or adding Client and Server to allowed list it works perfectly fine.
