### ISSUE TITLE
GrpcChannel ShutdownAsync does not change the State

### ISSUE THREAD

**Issue by topsterde** [grpc/grpc-dotnet#1818]
### What version of gRPC and what language are you using?
C# / gRPC 2.47.0

### What operating system (Linux, Windows,...) and version?
Windows 10, 20H2

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
Microsoft.NETCore.App 6.0.6

### What did you do?
I call await ShutdownAsync() on GrpcChannel with SocketsHttpHandler.

### What did you expect to see?
GrpcChannel.State is ConnectivityState.Shutdown

### What did you see instead?
GrpcChannel.State is still ConnectivityState.Ready

### Anything else we should know about your project / environment?
No

**Comment by topsterde** [comment]
Thank you for the answer.

I think the code documentation of GrpcChannel.State is wrong:
_After the channel has been shutdown, ConnectivityState.Shutdown is returned._
Better:
_After the channel has been disposed, ConnectivityState.Shutdown is returned._

Would it make sense to add an IDisposable to the Grpc.Core "Channel" as well?
Would it make sense to change the ShutdownAsync in the grpc-dotnet implementation? Only Dispose() must be called (instead of do nothing).

Why can't both interfaces (Grpc.Core and grpc-dotnet) behave the same way?

**Comment by JamesNK** [comment]
Grpc.Core is no longer being updated.

> Why can't both interfaces (Grpc.Core and grpc-dotnet) behave the same way?

Because https://github.com/grpc/grpc-dotnet/issues/1712 hasn't been done.

**Comment by JamesNK** [comment]
Closing because https://github.com/grpc/grpc-dotnet/issues/1712 already tracks this.
