### ISSUE TITLE
Reflection API

### ISSUE THREAD

**Issue by JunTaoLuo** [grpc/grpc-dotnet#182]
We should implement https://github.com/grpc/grpc/blob/master/doc/server-reflection.md. This seems like a popular extension point/service.

**Comment by JunTaoLuo** [comment]
May be able to leverage the code in https://github.com/grpc/grpc/tree/master/src/csharp/Grpc.Reflection

**Comment by JamesNK** [comment]
Thoughts:

* Grpc.Reflection has a dependency on Google.Protobuf
* Grpc.Reflection has a dependency on Grpc.Core
* Grpc.Reflection includes a c-core client
* Grpc.Reflection requires the developer to explicitly specify the services that are published. Good: it gives user's control, bad: duplication of work is involved to register a service in two places

I don't think there is anything stopping someone using Grpc.Reflection with Grpc.AspNetCore.Server. Should test that to find out.

**Comment by shirhatti** [comment]
> Grpc.Reflection requires the developer to explicitly specify the services that are published.

I'm not a fan. Comparing with other implementations, it looks neither Java, Go nor C++ require explicit registration. Python was the only other implementation that required it.

**Comment by JunTaoLuo** [comment]
Let's evaluate the options in Preview 5

**Comment by JamesNK** [comment]
Java tutorial: https://github.com/grpc/grpc-java/blob/master/documentation/server-reflection-tutorial.md

**Comment by JamesNK** [comment]
Done with https://github.com/grpc/grpc-dotnet/pull/192

This is available for devs to build from source. If we want to ship this then the Grpc.Core.Reflection dependency should be removed because it depends on Grpc.Core.
