### ISSUE TITLE
Grpc.Core.ClientBase Error in IIS when service invoked from Blazor Webassembly app

### ISSUE THREAD

**Issue by javipardoq** [grpc/grpc-dotnet#1821]
Hi:

I'm having the following error in the browser console that is not allowing the Blazor Webassembly app to continue consuming the grpc API:

**System.ArgumentException: The base-type Grpc.Core.ClientBase for service-proxy CalibrationSaaS.Application.Services.IBasicsServices`1[ProtoBuf.Grpc.CallContext] lacks a suitable CallInvoker API**

The code where this is happening is the following:

var httpClient = new HttpClient(new GrpcWebHandler(GrpcWebMode.GrpcWeb, new HttpClientHandler()));

           using (var channel = Grpc.Net.Client.GrpcChannel.ForAddress(builder.Configuration["Kestrel:Endpoints:Http3:Url"], new GrpcChannelOptions
            {
                HttpClient = httpClient
            }))
            {                
                var a = channel.CreateGrpcService<Application.Services.IBasicsServices<CallContext>>(); //The error happens in this line of code
                var b = await a.GetRoles(CallContext.Default); //This method is implemented
                return b;
            }

It was working until last week. **This error Only happens when the application is published in the respective IIS**, in the development Visual Studio environment it works normally.

I appreciate if you could help me with this issue, I can provide more information if needed.

Thank you.

Regards.

**Comment by rafikiassumani-msft** [comment]
@javipardoq Can you provide a full stack trace to help us diagnose the issue?

**Comment by JamesNK** [comment]
Your error is coming from https://github.com/protobuf-net/protobuf-net.Grpc. That's a third-party library. Please log the issue there.

**Comment by javipardoq** [comment]
> Your error is coming from https://github.com/protobuf-net/protobuf-net.Grpc. That's a third-party library. Please log the issue there.

Thank you!. I will.

**Comment by HarmanMS** [comment]
@javipardoq Have you already solved the problem? Have the same behavior...
