### ISSUE TITLE
GrpcChannel state throw Exception

### ISSUE THREAD

**Issue by luchunminglu** [grpc/grpc-dotnet#1822]
var httpHandler = new HttpClientHandler();
// Return `true` to allow certificates that are untrusted/invalid
httpHandler.ServerCertificateCustomValidationCallback = 
    HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;

var channel = GrpcChannel.ForAddress("https://localhost:5001",
    new GrpcChannelOptions { HttpHandler = httpHandler });
var client = new Greet.GreeterClient(channel);

//State should be idle, but instead it throw exception.
var state = client.State;

**Comment by JamesNK** [comment]
1. Client doesn't have a State. The channel does. I'm guessing you are referring to it.
2. The exception message is very clear about why it is thrown:

> System.InvalidOperationException : Channel is configured with an HTTP transport doesn't support client-side load balancing or connectivity state tracking. The underlying HTTP transport must be a SocketsHttpHandler with no SocketsHttpHandler.ConnectCallback configured. The HTTP transport must be configured on the channel using GrpcChannelOptions.HttpHandler.

**Comment by luchunminglu** [comment]
Starting in .NET Core 2.1, the implementation of the HttpClientHandler class was changed to be based on the cross-platform HTTP protocol stack used by the System.Net.Http.SocketsHttpHandler class.  
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler?view=net-6.0
Although HttpClientHandler is not SocketsHttpHandler, but it Internally use SocketsHttpHandler .  



  private void ValidateHttpHandlerSupportsConnectivity()
        {
            if (HttpHandlerType == HttpHandlerType.SocketsHttpHandler)
            {
                // SocketsHttpHandler is being used.
                return;
            }

            if (SubchannelTransportFactory is not SubChannelTransportFactory)
            {
                // Custom transport is configured. Probably in a unit test.
                return;
            }

            // Either the HTTP transport was configured with HttpClient, or SocketsHttpHandler.ConnectCallback is set.
            // We don't know how HTTP requests will be sent so we throw an error.
            throw new InvalidOperationException(
                $"Channel is configured with an HTTP transport doesn't support client-side load balancing or connectivity state tracking. " +
                $"The underlying HTTP transport must be a {nameof(SocketsHttpHandler)} with no " +
                $"{nameof(SocketsHttpHandler)}.{nameof(SocketsHttpHandler.ConnectCallback)} configured. " +
                $"The HTTP transport must be configured on the channel using {nameof(GrpcChannelOptions)}.{nameof(GrpcChannelOptions.HttpHandler)}.");
        }
