### ISSUE TITLE
Server: route requests between multiple instances of service

### ISSUE THREAD

**Issue by nayato** [grpc/grpc-dotnet#1831]
I want to inspect HTTP request (headers) to decide what instance of class implementing gRPC contract to use. All objects are instances of the same class. I assume that I'd need to customize routing process somehow. Could someone provide an insight into what I need to replace/rewrite to make it happen?

Thanks!

**Comment by JamesNK** [comment]
gRPC uses convention-based routes. It's always `packageName.serviceName/methodName`

**Comment by nayato** [comment]
Let me elaborate:
I have one proto contract. To implement the service though I need to resolve an instance of class I don't have direct control over. I plan to pass the identity of the instance via request header.
Straight-forward approach would be to implement contract so that in each method there's code to:
- pull "instance-id" from ServerCallContext.RequestHeaders,
- resolve instance based on the id from header,
- relay the call to that instance.

I'm wondering though if I can alter service routing in gRPC such that I can replace gRPC service instance resolution with the logic described above.

**Comment by JamesNK** [comment]
There is `IGrpcServiceActivator` which you could try. You'd need to hook up `IHttpContextAccessor` to get access to the request. I don't know if that would let you do what you want.
