### ISSUE TITLE
REST calls are being rerouted through gRPC

### ISSUE THREAD

**Issue by dijar-kadriu** [grpc/grpc-dotnet#1834]
### What version of gRPC and what language are you using?
Issue detected with 2.47.0. C#

### What operating system (Linux, Windows,...) and version?
Linux container - original Microsoft ASP.NET runtime container (latest)

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET SDK (reflecting any global.json):
 Version:   6.0.104
 Commit:    915d644e45

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /home/linuxbrew/.linuxbrew/Cellar/dotnet/6.0.104_1/libexec/sdk/6.0.104/

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  6.0.104 [/home/linuxbrew/.linuxbrew/Cellar/dotnet/6.0.104_1/libexec/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.4 [/home/linuxbrew/.linuxbrew/Cellar/dotnet/6.0.104_1/libexec/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.4 [/home/linuxbrew/.linuxbrew/Cellar/dotnet/6.0.104_1/libexec/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

### What did you do?
We are trying to create a project that has both gRPC and Rest. After we added the gRPC contracts and server our GetAll method stopped working. The endpoint for our GetAll method is localhost/v1/x. 
Removing gRPC services started working again.  While checking the logs we noticed that it started rerouting our REST calls via gRPC this was the error that it was being reported. 
```
11:44:48 dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1003]
      Endpoint 'gRPC - Unimplemented service' with route pattern '{unimplementedService}/{unimplementedMethod}' was rejected by constraint 'contentType':'Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder`1+GrpcUnimplementedConstraint[Endeavour.CasinoConfiguration.Grpc.AspNetCore.ProviderConfigService]' with value '(null)' for the request path '/v1/test'
```
We noticed that it even though the call is coming through our 8080 port but we are listening for gRPC calls on 8081 port its still being rerouted to a GRPC call. 

### What did you see instead?

```
11:44:48 dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1003]
      Endpoint 'gRPC - Unimplemented service' with route pattern '{unimplementedService}/{unimplementedMethod}' was rejected by constraint 'contentType':'Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder`1+GrpcUnimplementedConstraint[Endeavour.CasinoConfiguration.Grpc.AspNetCore.ProviderConfigService]' with value '(null)' for the request path '/v1/test'
```

**Comment by rafikiassumani-msft** [comment]
@dijar-kadriu Can you provide a GitHub project to help us reproduce this issue ?

**Comment by halter73** [comment]
It's possible that using [RequireHost](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-6.0#host-matching-in-routes-with-requirehost) on your MapGrpc call will limit it to matching only request to 8080 and not 8081. I'm not sure this will fix your overall problem though.

**Comment by dijar-kadriu** [comment]
Hello @halter73 @rafikiassumani-msft we have managed to find track down the issue. We are adding a filter ( `new ConsumesAttribute(MediaTypeNames.Application.Json)` ) inside the `AddControllers` in the Startup class and that is causing the issue for us. I have created a sample project which reproduces the scenario https://github.com/dijar-kadriu/GRPC-Test.
Steps to reproduce:
Start the Server
Start the Client (this proves that the gRPC is working)
Open a browser and navigate to http://localhost:8080/v1/game-configs you should hit a 404 error.

Fixing it
Go to `Startup` replace `services.AddControllers(o => { o.Filters.Add(new ConsumesAttribute(MediaTypeNames.Application.Json)); });` with services.AddControllers();
Start the Server
Start the Client (this proves that the gRPC is working)
Open a browser and navigate to http://localhost:8080/v1/game-configs and you should see an string with the value 1

**Comment by JamesNK** [comment]
I see the error. gRPC and REST services are conflicting with each other. Another way to fix this is to register gRPC like this:

```cs
services.AddGrpc(o => o.IgnoreUnknownServices = true);
```

Does that fix your problem?

**Comment by dijar-kadriu** [comment]
Hi @JamesNK it did thanks.
