### ISSUE TITLE
Pass state to SubchannelPicker

### ISSUE THREAD

**Issue by johncrim** [grpc/grpc-dotnet#1835]
This is either a question or a feature request. I need a way to pass per-call state from the GRPC client caller to the Load Balancer `SubchannelPicker.Pick()` method. In `SubchannelPicker.Pick()` I can access the `HttpRequestMessage`, but I don't see a way to access any state from the GRPC request or call. I need this state to identify a service partition to select in the picker.

In short, the picker resides in the downstream Http end of a pipeline, and it doesn't appear that there's a generalized mechanism to pass information from the upstream GRPC end of the pipeline.

I have considered the following solutions:
* The `HttpRequestMessage.Content` is a `PushUnaryContent<,>` object which contains the GRPC request object. However the request is in a private field, and `PushUnaryContent` is internal. If I could access my request object here I would have everything I need.
* I could write an `Interceptor`, but I don't see a way using an `Interceptor` to set state on the `HttpRequestMessage`. As far as I can tell in `Grpc.Net.Client.Internal.GrpcCall`, there is no way to pass state (eg headers) to the message that is built.

I'm going to dig further into these options; and will try using reflection to access the GRPC request. But I'm wondering if you can recommend a better approach. If not, please consider supporting this use-case.

Thank you in advance.

**Comment by JamesNK** [comment]
You could set up a DelegatingHandler to access the HttpRequestMessage.

If you want to pass state from where a call is made then request header metadata is set on the HttpRequestMessage and is accessible in the picker.

**Comment by johncrim** [comment]
Thank you @JamesNK - your second suggestion was spot on. I was able to pass state using `Metadata` from the call site and an Interceptor, which become HTTP headers. In an Interceptor, you can automatically populate headers from the GRPC request if doing so makes sense.

In case it helps anyone else:

```csharp
// At call site, or in an Interceptor
        var headers = new Metadata
                      {
                          { "x-my-header", stateString }
                      };
        var callOptions = new CallOptions(headers, cancellationToken: HttpContext.RequestAborted);
        await grpcClient.ApiMethod(callOptions);
```

Then in the picker:

```csharp
    public override PickResult Pick(PickContext context)
    {
        var httpRequest = context.Request;
        if (httpRequest == null)
        {
            return PickResult.ForFailure(new Status(StatusCode.NotFound, "HttpRequestMessage needed for endpoint resolution"));
        }

        if (httpRequest.Headers.TryGetValues("x-my-header", out var myHeaders))
        {
            var headerValue = myHeaders.Single();
            // Do something with the header
        }

        ...
```
