### ISSUE TITLE
Is there any Example for receiving bunch of object as list of array or anything. 

### ISSUE THREAD

**Issue by Mansoun** [grpc/grpc-dotnet#1836]
Hi. 
I am newbe in Grpc. 
how to send list of ids or object to Grpc?
for example I want to save list of object and I want to send once via Grpc. 
What should i do?
thanks.

**Comment by JamesNK** [comment]
https://docs.microsoft.com/en-us/aspnet/core/grpc/protobuf?view=aspnetcore-6.0#collections
