### ISSUE TITLE
Client to Client Communication using GRPC

### ISSUE THREAD

**Issue by affan848** [grpc/grpc-dotnet#1837]
Hi, I want to ask if we can implement client-to-client communication with GPRC, What I need to do is for Client 1 to send a message to Server, then Server should reply message from Client 1 to Client 2. How can I achieve this? Is it possible without using any other component like a database at the server end? Is any example available for that?

Basically, I want to achieve interprocess communication between two WPF applications using GRPC. I understand the communication between the client-server and server-client. But I want to send the response to some other client. Please assist.

**Comment by JamesNK** [comment]
There is a doc that talks about gRPC inter-process communication, but it's not clear about client vs server.

I've created a PR to improve the page. This should answer your question: https://github.com/dotnet/AspNetCore.Docs/pull/26660
