### ISSUE TITLE
Is there Possible Memory leak on GRPC dot net implementation?

### ISSUE THREAD

**Issue by smartnik83** [grpc/grpc-dotnet#1838]
What version of gRPC and what language are you using?
c#
GRPC 2.34.0
Google.Protobuf 3.17.3

What operating system (Linux, Windows,...) and version?
Windows 10

What runtime / compiler are you using (e.g. python version or version of gcc)
.net 5

What did you do?
I have a c# GRPC service self hosted as Windows service. It gets loaded with 2.5 GB of data when it starts. After running a small load test we could see memory increasing and eventually giving out of memory error.

What did you expect to see?
No out of memory error.

What did you see instead?
out of memory error.

Sample project is here https://github.com/smartnik83/LeakSimulation

**Comment by JamesNK** [comment]
.NET 5 is out of support. You should update your app to .NET 6 and the latest versions of gRPC and Protobuf.

I ran the sample and didn't see a memory leak. Server memory usage when up to 310 megabytes and then stayed the same no matter how many requests were made.

**Comment by smartnik83** [comment]
thank @JamesNK  for your reply.
Regarding, "Server memory usage when up to 310 megabytes and then stayed the same no matter how many requests were made "- Is that normal behavior?  I was expecting server to release memory after reaching 310 MB, as no more requests are received.

**Comment by JamesNK** [comment]
Kestrel caches some reusable buffers that are used for HTTP requests. Those are held onto forever and aren't released. It's something that's been considered but hasn't been reported as a problem in the past.

Also, the .NET GC doesn't necessarily clean up memory if it doesn't need to (at least that's what I've been told, I'm not a GC expert).
