### ISSUE TITLE
make ConvertStatusCode public 

### ISSUE THREAD

**Issue by setood** [grpc/grpc-dotnet#1852]
in systems written in different languages, to analyze logs and metrics, you need GRPS status codes to be from the standard https://grpc.github.io/grpc/core/md_doc_statuscodes.html.
the `StatusCode.ToString()` method gives a different output, so it would be great to be able to use the converter from the standard library

https://github.com/grpc/grpc-dotnet/blob/bce585246db48c655b744976e55cb6c3819bc6c1/src/Grpc.Net.Client/Internal/Configuration/ConvertHelpers.cs#L22-L49

**Comment by JamesNK** [comment]
If this is made public, then it can't be changed and has to be supported and maintained forever by the gRPC team. Because of this, internal helper methods and types like this aren't made public.

However, you can copy and paste it if you want.
