### ISSUE TITLE
CallOptions deadline calculations inaccurate due to using DateTime values

### ISSUE THREAD

**Issue by jonathanbrecher** [grpc/grpc-dotnet#1854]
The latest version (2.47.0) of the .NET Core code uses DateTime values to calculate deadlines. One example is at https://github.com/grpc/grpc-dotnet/blob/master/src/Grpc.Net.Client/Internal/GrpcCall.cs#L881 👍 

`return _deadline <= Channel.Clock.UtcNow;`

Calculations that use DateTime values will fail near the Daylight Savings Time boundaries. Consider

```
_deadline =  2022-11-06 01:58
Channel.Clock.UtcNow = 2002-11-06 01:59
```

Has the deadline passed or not (for clients running in the United States)? On 2022-11-06, the times 01:58 and 01:59 will each happen twice: "Spring forward, fall back". There is no way to know if 2022-11-06 01:58 is before or after 2002-11-06 01:59 without considering  time zone offsets, which are not available in DateTime objects. The code won't crash as written, but it might not give the expected result.

The CallOptions object should be modified to store its deadline as a DateTimeOffset rather than a DateTime.

**Comment by JamesNK** [comment]
The time is alway UTC which doesn't have daylight savings.

**Comment by jonathanbrecher** [comment]
I don't see a guarantee that the time is always UTC? 

The CallOptions constructor accepts a DateTime object (https://github.com/grpc/grpc-dotnet/blob/master/src/Grpc.Core.Api/CallOptions.cs#L48). 

The client can provide a DateTime object specified DateTimeKind.Local.

Once a DateTime is provided with DateTimeKind.Local, there's no reliable way to convert it to UTC time. If you try to convert local time 2022-11-06 01:58 to UTC time you'll get some consistent result that has a 50/50 chance of being the result that was intended.

No?

**Comment by JamesNK** [comment]
Have you tried making a gRPC call with a local deadline?

https://github.com/grpc/grpc-dotnet/blob/bbbfdc0f02e801df574b3da66967da93c0f2a5d3/test/Grpc.Net.Client.Tests/DeadlineTests.cs#L439-L455

**Comment by jonathanbrecher** [comment]
Huh. Yes, we found this in local builds. Our local code behaved properly (since we're not near a Daylight Savings transition today). We're still using Grpc.Core, maybe the exception was added since then.

I guess this bug should be closed off for now. I'm not in a position to upgrade our code to test against grpc-dotnet right away.

Sorry for the noise!
