### ISSUE TITLE
implicit behavior if continuation thrown exception synchronously

### ISSUE THREAD

**Issue by setood** [grpc/grpc-dotnet#1864]
if continuation thrown exception synchronously (if deadline not UTC DateTime, for example ), then HandleResponse never called

https://github.com/grpc/grpc-dotnet/blob/2116d1efce933b1185baa1c577cc09b6a9a6c88a/examples/Interceptor/Client/ClientLoggerInterceptor.cs#L39-L50

**Comment by JamesNK** [comment]
I improved the client logger interceptor to handle these errors: https://github.com/grpc/grpc-dotnet/pull/1868
