### ISSUE TITLE
How should I configure windows firewall to allow a gRPC service hosted in an ASP Core .NET 6 application?

### ISSUE THREAD

**Issue by ComptonAlvaro** [grpc/grpc-dotnet#1865]
I would like to configure the windows firewall to can connect to the gRPC service that is hosted in an ASP Core .NET 6 application.

I have tried to open the TCP port that is used for the HTTPS and it works, but I would like to avoid this way, I would like to allow only the service.

I have found this documentation, https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-firewall/create-inbound-rules-to-support-rpc, in which it seems it explains how to do it. But I am not able to make it work. I have created this two rules:

- To create a rule to allow inbound network traffic to the RPC Endpoint Mapper service
- To create a rule to allow inbound network traffic to RPC-enabled network services.

But it doesn't work.

So how should I configure the windows firewall to can allow only my ASP Core application?

Thanks.

**Comment by JamesNK** [comment]
I don't know what the doc is referring to as RPC, but I doubt it's gRPC. gRPC is standard HTTP over TCP.

I don't know how to configure windows firewall. Please ask a windows firewall expert.
