### ISSUE TITLE
Feature request: Improve gRPC client Certificate handling

### ISSUE THREAD

**Issue by damienbod** [grpc/grpc-dotnet#188]
It would help, if it was possible to use a pfx file with password, or a thumbprint from the client. This would make it easy to setup HTTPS with the client for different deployment types.

something like this:

example 1:
```
cert = new X509Certificate2(Path.Combine(_environment.ContentRootPath, "sts_dev_cert.pfx"), "1234");
```

example 2:
```
using (X509Store store = new X509Store(StoreName.My, StoreLocation.LocalMachine))
{
  store.Open(OpenFlags.ReadOnly);
  var certs = store.Certificates.Find(X509FindType.FindByThumbprint, certificateThumbprint, false);
  cert = certs[0];
  store.Close();
}
```

example 3:
```
var vaultConfigSection = Configuration.GetSection("Vault");
var keyVaultService = new KeyVaultCertificateService(vaultConfigSection["Url"], vaultConfigSection["ClientId"], vaultConfigSection["ClientSecret"]);
cert = keyVaultService.GetCertificateFromKeyVault(vaultConfigSection["CertificateName"]);
```

**Comment by vincentparrett** [comment]
+100 for this. The current SSLCredentials setup is not great. I'm deciding whether to use grpc or halibut (to replace wcf) at the moment and halibuts uses x509 certs with thumbprints and it's a lot easier to manage.

**Comment by JunTaoLuo** [comment]
This is a good ask, we'll investigate further in the next release.

**Comment by JamesNK** [comment]
From preview 6 you will be able to use a new client that uses HttpClient to make calls internally. You can set the client certificate on the HttpClient like you do today.

**Comment by JamesNK** [comment]
In preview 6 there is a new gRPC client that uses HttpClient internally.

I have added a example of sending a client certificate with gRPC calls and using them on the server. It is available here - https://github.com/grpc/grpc-dotnet/pull/306

**Comment by wazzamatazz** [comment]
The new HttpClient-based client is great, but it's only an option if you're using .NET Core 3.0 on the client side. Improving certificate handling for the Grpc.Core-based client as described above would be a great help when working with a target framework that doesn't support .NET Standard 2.1.

**Comment by JamesNK** [comment]
Raise Grpc.Core related improvements at https://github.com/grpc/grpc
