### ISSUE TITLE
Build .proto files from interface

### ISSUE THREAD

**Issue by dgxhubbard** [grpc/grpc-dotnet#189]
We are trying to replace WCF in our apps. One of the greatest features of WCF it creates the proxy or service middleware from an interface definition. I looked at your server example and saw the proto files and started thinking about the state of RPC in the 90s. Would it be difficult to build the proxy and service files required by grpc from an interface definition dynamically in code. Then put an api on top that to allow opening a connection to the server, and likewise build a service endpoint?

**Comment by JamesNK** [comment]
I doubt we will ever generate .proto files from an interface.

Supporting a .NET contract like WCF has an issue here - https://github.com/grpc/grpc-dotnet/issues/68

Closing this a duplicate.
