### ISSUE TITLE
How to intercept the repsonse of AsyncClientStreamingCall?

### ISSUE THREAD

**Issue by boldt** [grpc/grpc-dotnet#1893]
Looking into the `ClientLoggerInterceptor.cs`, **AsyncUnaryCall** can log the request with `LogCall` and the response with `HandleResponse`: 
https://github.com/grpc/grpc-dotnet/blob/master/examples/Interceptor/Client/ClientLoggerInterceptor.cs#L55

The **AsyncClientStreamingCall** only logs the  request with `LogCall`: 
https://github.com/grpc/grpc-dotnet/blob/master/examples/Interceptor/Client/ClientLoggerInterceptor.cs#L91

Is there any way to intercept the response of **AsyncClientStreamingCall** as well?

**Comment by JamesNK** [comment]
Yes. It's more complicated.

SO answer that covers it: https://stackoverflow.com/questions/62197301/how-to-create-grpc-streaming-interceptors-using-c

**Comment by boldt** [comment]
That answer is a bit blown up, but that helped. Thanks.
