### ISSUE TITLE
Same issue as #1846 has anyone else dealt with this?

### ISSUE THREAD

**Issue by gjiremadzeBECKMAN** [grpc/grpc-dotnet#1896]
Can anyone help me, seems this issue was closed without an answer and i'm having the same issue when trying to use certificates in grpc in .NET.

https://github.com/grpc/grpc-dotnet/issues/1846

Thank you

**Comment by JamesNK** [comment]
From that issue:

> Your log indicates the server never received the request. However, I would have expected a different error from the client if that was the case.
> 
> I suggest you simplify your app to not use client certificates, get your client to successfully call the server, then attempt to readd client certificates.
> 
> If you still have problems then you might need to reach out to the folks at [dotnet/runtime](https://github.com/dotnet/runtime). I'm not a certificate expert. grpc-dotnet uses the client certificate support in HttpClient and the .NET runtime team have much more knowledge about client certificates than I do.

**Comment by gjiremadzeBECKMAN** [comment]
I have everything working without client certificates. however as soon as i try to add them in i'm getting this same error.

**Comment by JamesNK** [comment]
Continuation of issue on dotnet/runtime: https://github.com/dotnet/runtime/issues/74066
