### ISSUE TITLE
Connect two Clients directly

### ISSUE THREAD

**Issue by mobycorp** [grpc/grpc-dotnet#1897]
Greetings,

I am working on a peer-to-peer content delivery application and want to connect two clients directly once registered with a server. The server is basically just a directory lookup service used to connect two (or more) clients directly. Here is what I am trying to accomplish:

1) The directory service starts and listens for clients to register themselves.
2) The first client (Client A) starts and registers with the directory service.  From this, I can get the client's endpoint address from the call's context.RemoteEndPoint (using a long-running stream).
3) The second client (Client B) perform the same registration.
4) Client A wants to send Client B a message but not through the directory service, but instead, directly between themselves.
4a) Client A asks the directory service where Client B is (I am using a user ID to facilitate this lookup).
4b) The directory service finds Client B in its list of registered clients and responds to Client A with Client B's endpoint.
5) Then, the clients take on a new life of being both a server and a client between themselves.
5a) Client A uses the endpoint returned by the directory service to connect directly to Client B.
5b) Client A then opens a channel to Client B, thus making Client A a client of Client B (which is effectively now a server to Client a).
6) Client A interacts with Client B directly to send messages with content until the content is fully delivered.

I am worried that Client B's address is only usable between Client B and the directory service and not between clients A and B. Basically, Client A and B do not know where each other is but need to communicate directly. I am hoping the directory service can arbitrate the connection necessary to do this.

How can this effectively be done?

**Comment by mobycorp** [comment]
I am thinking out loud here...

When preparing to register with the directory service, the client:

1) Finds its external IP address
2) Finds the next open port on the localhost.
3) The client creates an end point by $"{externalIpAddress}:{availablePort}"
4) The client then starts to listen on that port.
5) The client then registers with the directory service with this created end point.

It appears as though I can only use TCP ports and not UDP ports. Will gRPC ever use UDP?

**Comment by chwarr** [comment]
Non-direct answers to some of your questions:

> I am worried that Client B's address is only usable between Client B and the directory service and not between clients A and B. Basically, Client A and B do not know where each other is but need to communicate directly. I am hoping the directory service can arbitrate the connection necessary to do this.

Fortunately (unfortunately?), none of this is specific to gRPC. 😄 This is a general TCP running "on the real Internet" problem. You can remove gRPC from the equation if that makes solving it easier. 

gRPC's support for bi-directional streaming does provide you some flexibility too: if your application protocol is a series of messages exchanged over a bi-directional stream, regardless of which host is the TCP client or server, either one can "initiate" a request. Your application would need to handle request/response pairing somehow in this scheme.

> Will gRPC ever use UDP?

There's a proposal for [gRPC over HTTP/3](https://github.com/grpc/proposal/blob/master/G2-http3-protocol.md), which would run over UDP. gRPC.NET implements a version of this protocol as an attempt to demonstrate the viability of the design.

gRPC runs over HTTP/2 today and relies on some of the message deliver & ordering guarantees that HTTP/2 provides (and some other HTTP semantics). So, swapping TCP for UDP is more involved that just changing the underlying protocol, hence the proposal's use of HTTP/3, as that adds delivery & ordering guarantees atop UDP.

**Comment by JamesNK** [comment]
A client can't easily connect to another client that's behind a firewall or NAT. There are ways around that, such as having both clients connect to a public server and have it be responsible for marshaling messages between the two clients, but that's kind of like having a message bus. One client puts messages on the message bus for the other client to read off the bus.

There is no reason you write a message bus yourself with gRPC and hide away the complexity in the middle, but there are probably existing solutions for this problem.

**Comment by JamesNK** [comment]
A .NET gRPC client can morph into a server by starting Kestrel in the process. There is nothing complex about that. The issue is whether a client can see another client behind a firewall or NAT.

The only solution I know of for client-to-client communication with gRPC, when the clients can't directly address each other, is what is described previously.
