### ISSUE TITLE
gRPC Retry and Connection Timeout

### ISSUE THREAD

**Issue by focus38** [grpc/grpc-dotnet#1899]
Hi.
@JamesNK, do retries and custom connection timeout work correctly together?

ENV: Linux (Ubuntu 20.04), .Net 6.0.9

If the client connects to the server that is running locally, then everything works.
If the client connects to the server through a network (LAN, Internet, VPN), then error occurs.

If I use retries with standard timeout, it works correctly. But the connection timeout is very long 130 seconds.
If I configure connection timeout setting for the handler, then TaskCanceledException is thrown and no retry occurs.
I tried to enable the ThrowOperationCanceledOnCancellation option, but it doesn't work.

Here is the repository with the code where I'm testing
https://github.com/focus38/grpc_test

**Comment by JamesNK** [comment]
When `ConnectTimeout` is set then SocketsHttpHandler throws a cancellation error. That makes sense because the handler is cancelling the call if it can't connect in the specified time.

To retry, add `StatusCode.Canceled` to the retry list:
```
RetryableStatusCodes = {StatusCode.Unavailable,StatusCode.Canceled}
```
