### ISSUE TITLE
Capture logging in unit testing

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#19]
Should capture log files during unit testing for local and CI debugging

**Comment by JunTaoLuo** [comment]
Something like https://github.com/aspnet/Extensions/blob/master/src/Logging/Logging.Testing/src/LoggedTest/ILoggedTest.cs?

**Comment by JamesNK** [comment]
Yes. I want to setup logging to be like SignalR's and capture each test run in its own text file.

**Comment by JunTaoLuo** [comment]
We'll need to investigate how this work in NUnit but this functionality is pretty useful.
