### ISSUE TITLE
Lifetime of a grpc channel of a client injected through a grpc factory

### ISSUE THREAD

**Issue by victorm1710** [grpc/grpc-dotnet#1902]
Assuming I used AddGrpcClient extension to register client and to be able to get grpc clients from DI, what would be the lifetime of an underlying grpc channels used by those grpc clients? It seems like in the past a single grpc channel was reused between clients, but by looking at current source code it seems like channel is created per client:

This is how clients are created:
https://github.com/grpc/grpc-dotnet/blob/master/src/Grpc.Net.ClientFactory/GrpcClientServiceExtensions.cs#L368
Here is the GrpcClientFactory factory registration:
https://github.com/grpc/grpc-dotnet/blob/master/src/Grpc.Net.ClientFactory/GrpcClientServiceExtensions.cs#L296
An invoker is created on each CreateClient call
https://github.com/grpc/grpc-dotnet/blob/master/src/Grpc.Net.ClientFactory/Internal/DefaultGrpcClientFactory.cs#L54
GrpcCallInvokerFactory creates a new channel per CreateInvoker call:
https://github.com/grpc/grpc-dotnet/blob/master/src/Grpc.Net.ClientFactory/Internal/GrpcCallInvokerFactory.cs#L118

**Comment by JamesNK** [comment]
A channel is created per-client type. The channel for a client type is then cached.

**Comment by victorm1710** [comment]
Thanks James, that was my assumption. I was just curious on where exactly is it cached, because I wasn't able to find that place in code 😅

**Comment by JamesNK** [comment]
Here: https://github.com/grpc/grpc-dotnet/blob/456098bcfeb9c796c19ea023b3ab3703181f1089/src/Grpc.Net.ClientFactory/Internal/GrpcCallInvokerFactory.cs#L66
