### ISSUE TITLE
Accessing reflection from client

### ISSUE THREAD

**Issue by ricsiLT** [grpc/grpc-dotnet#1903]
Hi,

Is there a way, directly or indirectly, of accessing reflection RPC via dotnet client? I would assume such method would just throw an exception when reflection is disabled but that's ok.

Use-case is that I want to see whether definitions used by server are the same as the ones used by client without any out-of-band tools and reflection *sounds* like it covers that.

**Comment by JamesNK** [comment]
https://github.com/grpc/grpc-dotnet/tree/master/examples#reflector

**Comment by ricsiLT** [comment]
Thank you! Maybe I'll create PR to add it to Microsoft docs in case someone will look for them there like me!

**Comment by JamesNK** [comment]
I don't know for sure, I haven't used the reflection API like this.

I think the bytes are a serialized form of the proto file. I think you load it into a protobuf descriptor from Google.Protobuf. e.g. `FileDescriptor`.

**Comment by JamesNK** [comment]
This project - https://github.com/xoofx/grpc-curl - uses payloads returned from reflection. I suggest you take a look at what it is doing.

**Comment by ricsiLT** [comment]
Thank you! Managed to get a working solution! Will leave code here if someone needs something like it but `FileDescriptor` hint was really useful!

Again, to summarize, this code is to detect when client is out of sync with the server and should update .proto:

```csharp
        using var channel = _channelFactory.GetChannel();
        var client = new ServerReflection.ServerReflectionClient(channel);
        
        using var call = client.ServerReflectionInfo();

        // To get all service names on the server, you can use this:
        // await call.RequestStream.WriteAsync(new ServerReflectionRequest{ ListServices = ""});
        // await call.ResponseStream.MoveNext(CancellationToken.None);
        // foreach (var serviceResponse in call.ResponseStream.Current.ListServicesResponse.Service)
        // {
        //     _logger.LogInformation("Service name on server: {ServiceName}", serviceResponse.Name);
        // }
        
        await call.RequestStream.WriteAsync(new ServerReflectionRequest{FileContainingSymbol = "name.space.service_name"});
        await call.ResponseStream.MoveNext(CancellationToken.None);
        var descriptorResponse = call.ResponseStream.Current;
        
        // This list has to be reversed. Check `.BuildFromByteStrings` docstring for more info.
        var fileDescriptors = FileDescriptor.BuildFromByteStrings(descriptorResponse.FileDescriptorResponse.FileDescriptorProto.Reverse());
        var localDescriptor = ServiceName.Descriptor.File;
        var relevantFileDescriptor = fileDescriptors.Single(descriptor => descriptor.Name == localDescriptor.Name);

        // this will have to be adjusted for your specific use-case.
        if (relevantFileDescriptor.SerializedData != localDescriptor.SerializedData)
        {
            _logger.LogWarning("Remote .proto differs from local copy. Please update.");
        }
        else
        {
            _logger.LogInformation(".proto definition matches between client and server.");
        }

        await call.RequestStream.CompleteAsync();
```
