### ISSUE TITLE
Reusing Channel for HealthChecks

### ISSUE THREAD

**Issue by bslbckr** [grpc/grpc-dotnet#1912]
We are working on a microservice backend that mainly uses gRPC for communication. For health-checking we rely on the gRPC HealthCheck protocol and thus many of our services implement two gRPC services: one for the business functions and one for the health-checks. 

Health-checking - in our setting - implies that also all consumed services are checked, too. I.e. service A consumes service B. So A's health-check requires to invoke service B's `Check` method. 

Before switching to AspNetCore and grpc-dotnet we reused the 'Channel' or 'CallInvoker' instance, respectively for the two clients of Service B and the HealthClient. In AspNetCore we, so far, failed to resemble this reuse behavior. Is there any way to re-use the channel used for one client within another client?

**Comment by JamesNK** [comment]
A GrpcChannel can be reused with different client types.

**Comment by bslbckr** [comment]
Could you give me a hint, where I should look at? I actually don't know how to do this. Is the channel selected on the given remote address?

**Comment by JamesNK** [comment]
You just create multiple clients from a channel. For example:

```cs
var channel = GrpcChannel.ForAddress("https://localhost:5001");
var client1 = new Greet.GreeterClient(channel);
var client2 = new Count.CounterClient(channel);
```

**Comment by bslbckr** [comment]
I think I haven't been clear, what exactly my problem is. I'm aware that I can do it the way you described it. But what I was looking for, is a way to achieve this using tlAspNetCor's DI mechanisms

**Comment by JamesNK** [comment]
No. Each client type has its own channel. If you need exact control, then don't use the gRPC client factory.

**Comment by bslbckr** [comment]
Thanks for the explanation. I'll close the issue
