### ISSUE TITLE
grpc-dotnet HoloLens 2 Support

### ISSUE THREAD

**Issue by HaiKonofanDesu** [grpc/grpc-dotnet#1915]
Hey there, 

I want to use grpc for a HoloLens app I'm currently developing. Sadly HoloLens 2 can't find/ use the .dll I get from NuGet as they are not compiled for UWP.

All tutorials like [this](https://github.com/grpc/grpc/issues/20344#issuecomment-561559557) or [this](https://github.com/grpc/grpc/issues/23488#issuecomment-690766560) say I need to build grpc_csharp_ext. which I can't find probably because of the split to grpc-dotnet. So I would like to ask if someone can let me know how I can actually recompile the dotnet Plugins (and maybe the grpc-core one as well) to work with the HoloLens 2.

Here are my currently used .dll:
- Google.Protobuf.3.21.5
- Grpc.Core.Api.2.49.0
- Grpc.Net.Client.2.49.0
- Grpc.Net.Client.Web.2.49.0
- Grpc.Net.Common.2.49.0
- Microsoft.Logging.Abstractions.3.0.3
- System.DiagnosticSource.4.5.1

I appreciate any help!

**Comment by JamesNK** [comment]
grpc-dotnet requires HTTP/2 support in SocketsHttpHandler, which HoloLens doesn't have. I think your only option would be to use gRPC-Web from UWP. That would allow for gRPC-Web unary and server streaming calls, but no client or bidirectional streaming. The documentation discusses how to setup gRPC-Web.

**Comment by HaiKonofanDesu** [comment]
@JamesNK Thanks for the fast reply. 

Could you explain a bit more how it's possible to implement gRPC-Web with Unity? As far as I saw gRPC-Web works with .js and .ts files but I use Unity aka C# as the programming language.
I also see some other people saying they got it running. Does that mean I would need to use the older version og grpc-core and grpc_csharp_ext to get it running on the HoloLens?

I also got this message from unity last week which now confuses me even more:
>  It suspect this is because there are no native plugin binaries of grpc_csharp_ext.dll that are compiled for UWP. I can only see ones compiled for Windows Desktop (under Assets/Plugins/Grpc.Core/runtimes/win/x64). To get around this, you need to recompile this DLL for UWP for all architectures you want to support. Since you're deploying to HoloLens 2, you'll need to compile it for ARM64. One gotcha is that if a DLL is compiled incorrectly or for the wrong architecture, it will not say that in the error message. The error message will merely say that it cannot find the DLL (even if it's there).

Is it just Unity not knowing that the HoloLens 2 does not support HTTP/2? Or does HoloLens 2 support HTTP/2 and just HoloLens 1 not?

Thanks in advance!

**Comment by JamesNK** [comment]
Grpc.Net.Client is a completely different implementation than Grpc.Core. gRPC for .NET documentation talks about gRPC-Web.

**Comment by HaiKonofanDesu** [comment]
So this means I need to switch back to Grpc.Core and try to rebuild it properly or use gRPC-Web. Thanks
