### ISSUE TITLE
Cancellation mechanism has negative impact on overall latency

### ISSUE THREAD

**Issue by ogxd** [grpc/grpc-dotnet#1917]
### What version of gRPC and what language are you using?
2.49.0 and 2.45.0

### What operating system (Linux, Windows,...) and version?
MacOS ARM64, but I believe it also happens on Linux x86 since I have spotted this issue on production servers (docker).

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
SDK is dotnet 6.0.401, runtime is dotnet 6.

### What did you do?
Compare Grpc.Core VS Grpc.Net.Client clients when using a timeout (cancellation token with duration)

### What did you expect to see?
I expect a timeout to have no effect on the duration of a call when the call duration is expected to be smaller than the timeout value. I know that there are some imprecisions with the clock, however this is a different problem here.    
For example, if 50% of calls take less than 2ms when I use no cancellation token (or a large duration), I expect to still have 50% of the calls take less than 2ms if I change this timeout to let's say 20ms.

### What did you see instead?
Given the example above, if I change the timeout to 20ms, then everything seems slowed down, up to a point that it no longer is able to perform a single call under 20ms.

### Repro

See [https://github.com/ogxd/grpc-net-client-migration-perf-repro](https://github.com/ogxd/grpc-net-client-migration-perf-repro). There is a test project that you can use to simulate client/server calls locally with both Grpc.Core and Grpc.Net.Client. You'll see that using different timeout values with Grpc.Core does not affect the overall response time, while it does with Grpc.Net.Client.    

<img width="312" alt="image" src="https://user-images.githubusercontent.com/12692438/196186394-435ed023-7d62-4d47-b505-f32400e307ca.png">
<img width="307" alt="image" src="https://user-images.githubusercontent.com/12692438/196186528-8f4b95bc-5422-4beb-8221-d3b87c6b8b74.png">
With Grpc.Core, the 50p (median) is the same if we use a 200ms timeout or a 10ms timeout value.     
     
<img width="361" alt="image" src="https://user-images.githubusercontent.com/12692438/196186749-15a102e0-609c-40d8-93d4-b8adb108c9ff.png">
<img width="350" alt="image" src="https://user-images.githubusercontent.com/12692438/196187510-b6bfb4fe-0ee7-4255-957a-92d5f7f991c3.png">
<img width="348" alt="image" src="https://user-images.githubusercontent.com/12692438/196186829-20b18e17-b619-48ea-8b84-e9d54f825875.png">
With Grpc.Net.Client, the 50p (median) drops to 75ms with a 30ms timeout, and is even unable to make a single successful call when the timeout is 10ms.     

Another weird thing is that it seems to work as expected when I run all Grpc.Net.Client tests at once? Maybe it's linked to something done at some kind of initialization stage, or just a weird side effect I don't know yet.

**Comment by JamesNK** [comment]
It's fine on my computer. I'm guessing I have a faster machine than you do.

![image](https://user-images.githubusercontent.com/303201/196193463-9533c891-2e70-47b8-9799-b1601ccedacb.png)

![image](https://user-images.githubusercontent.com/303201/196193513-c529e8c3-b8a8-4415-b372-faef48c010c8.png)

![image](https://user-images.githubusercontent.com/303201/196193573-5f64d11c-5ccd-4330-b06b-e185b7fadfc1.png)

![image](https://user-images.githubusercontent.com/303201/196193634-c2805081-4533-4480-833e-a7c8724f4f81.png)

Look at the slowest request times. They're bigger than 10ms for both frameworks. If you set the cancellation timer to 10ms, requests will start being aborted. Exceptions will be thrown, CPU usage will be wasted, and there will be garbage collections. That will slow down requests more, and cause more to be aborted, causing more slowdowns, causing more aborts, etc.

If something hurts you, don't do it.

**Comment by ogxd** [comment]
I think I know what the problem is: by adding a single call with no timeout before everything works as expected.    So I think that is because **this first call is establishing the connection**. Could it be that possibly with Grpc.Core cancellation management was different when establishing a connection?     
Do you know if I can specify a different timeout value for connections VS actual calls? I've already seen this in the past like for Aerospike.

**Comment by ogxd** [comment]
I have found a workaround:    
Instead of 
```csharp
new CallOptions().WithCancellationToken(new CancellationTokenSource(TimeSpan.FromMilliseconds(timeoutMs)).Token)
```
I tried 
```csharp
new CallOptions().WithDeadline(DateTime.UtcNow.AddMilliseconds(timeoutMs))
```
    
I am not sure was differs internally, but it seems to work as expected this way.     
<img width="344" alt="image" src="https://user-images.githubusercontent.com/12692438/196214438-d651a25b-92b2-4cdb-bacd-a849c6099e85.png">

**Comment by ogxd** [comment]
A timeout is not there to tell a function to take less an given duration. It is just a security mechanism to avoid doing unnecessary work whenever a call takes too much time. **We don't want to make it faster, we want to make it work when it's worth**.     
In practice, if I am building an API that must answer under 500ms, maybe I don't want my service to hang doing a grpc call to another service if it's not mandatory and it has other stuff to do afterward. This is why we use a timeout (or a deadline, call it how you want).

**Comment by JamesNK** [comment]
Deadlines are fine. 500 ms is probably ok.

10 ms deadline is a bomb waiting to explode. The moment it takes longer than 10 ms to establish the connection the app will DOS itself. Don’t do it.

**Comment by ogxd** [comment]
Here I am just reporting a bug, or a change in behavior compared to Grpc.Core. That is a fact, whether we should use timeout or not (on that it seems we simply don't agree, and that's fine).     
    
On my end I found out that deadline yields the expected behavior, unlike when using a cancellation token with a short timeout, and that is a valid workaround for me.     
I can invest some time trying to debug the underlying issue with the cancellation token, unless you don't see any issue (I don't want to waste my time).

**Comment by JamesNK** [comment]
Canceling a call via cancellation token:

https://github.com/grpc/grpc-dotnet/blob/456098bcfeb9c796c19ea023b3ab3703181f1089/src/Grpc.Net.Client/Internal/GrpcCall.cs#L398-L404

And canceling a call via a deadline:

https://github.com/grpc/grpc-dotnet/blob/456098bcfeb9c796c19ea023b3ab3703181f1089/src/Grpc.Net.Client/Internal/GrpcCall.cs#L1047-L1059

Both happen in the same way: calling `CancelCall`, which tells the underlying HTTP handler to abort.

The difference is there is extra code to ensure the deadline is canceled after the specified time. .NET timers aren't precise. There can be up to +14ms/-14ms precision in exactly when they run. I added extra code when a deadline is specified to keep a call going if the deadline hasn't passed:

https://github.com/grpc/grpc-dotnet/blob/456098bcfeb9c796c19ea023b3ab3703181f1089/src/Shared/CommonGrpcProtocolHelpers.cs#L28-L54

Probably the reason why a deadline is working better is it is forcing a longer timeout.

**Comment by ogxd** [comment]
Thanks a lot for the pointers and clarifications.
