### ISSUE TITLE
Kestrel-based gRPC/gRPC-web API gateway

### ISSUE THREAD

**Issue by stas-neverov** [grpc/grpc-dotnet#1918]
Hi,

How I could create a simple .NET reverse proxy running on Kestrel that redirects gRPC-web (or gRPC) requests to individual gRPC services available on diffenent URLs/ports?

Background - the idea is to design a plugin architecture like this:
- plugins are gRPC services developed as independent ASP.NET Core apps;
- main ASP.NET Core app launches all plugins from a plugin folder and passes each executable a service registry address;
- plugins self-register in the service registry;
- the main ASP.NET Core app proxies incoming gRPC-web/gRPC requests to relevant plugin gRPC services based on service registry metadata.

Thank you!

**Comment by JamesNK** [comment]
I'd build it using YARP - https://github.com/microsoft/reverse-proxy

**Comment by rafikiassumani-msft** [comment]
@stas-neverov Triage: YARP forward grpc calls to other grpc services. Will that be enough to satisfy your design? Please look at the following doc for forwarding requests: https://microsoft.github.io/reverse-proxy/articles/direct-forwarding.html

**Comment by stas-neverov** [comment]
@JamesNK, thanks for the tip and for the library - nice product!

@rafikiassumani-msft, yes, that's exactly what I was looking for. Thank you!
