### ISSUE TITLE
Failed to create a gRpc duplex stream when using MAUI Android

### ISSUE THREAD

**Issue by rodrigovaras** [grpc/grpc-dotnet#1923]
### What version of gRPC and what language are you using?
Using C# and version:
    <PackageReference Update="Grpc.Net.Client" Version="2.49.0" />

### What operating system (Linux, Windows,...) and version?
Running on Android 12

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET SDK:
 Version:   7.0.100-rc.2.22477.23
 Commit:    0a5360315a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-rc.2.22477.23\

Host:
  Version:      7.0.0-rc.2.22472.3
  Architecture: x64
  Commit:       550605cc93

### What did you do?
Connect to a GRPC Servce on the cloud

### What did you expect to see?
The await call succeed

### What did you see instead?
Call get stuck here:
        var responseMetadata = await enterMapDuplex.ResponseHeadersAsync;

here are the logs until it get stuck:
04:17:39.043 msg:Starting gRPC call. Method type: 'DuplexStreaming', URI: 'https://query.sa.uksouth.mixedreality.azure.com/com.azure.mixedreality.sa.locoptquery.MapQueryPlanner/EnterMap'. level:Debug name:Grpc.Net.Client.Internal.GrpcCall [GrpcMethodType=DuplexStreaming],[GrpcUri=/com.azure.mixedreality.sa.locoptquery.MapQueryPlanner/EnterMap]
04:17:39.124 msg:Subchannel id '1' created with addresses: query.sa.uksouth.mixedreality.azure.com:443 level:Debug name:Grpc.Net.Client.Balancer.Subchannel
04:17:39.203 msg:Channel picker updated. level:Debug name:Grpc.Net.Client.Balancer.Internal.ConnectionManager
04:17:39.329 msg:Subchannel id '1' state changed to Connecting. Detail: 'Connection requested.'. level:Debug name:Grpc.Net.Client.Balancer.Subchannel
04:17:39.374 msg:Channel state updated to Connecting. level:Debug name:Grpc.Net.Client.Balancer.Internal.ConnectionManager
04:17:39.417 msg:Subchannel id '1' state changed to Ready. Detail: 'Passively connected.'. level:Debug name:Grpc.Net.Client.Balancer.Subchannel
04:17:39.467 msg:Channel state updated to Ready. level:Debug name:Grpc.Net.Client.Balancer.Internal.ConnectionManager
04:17:39.506 msg:Channel picker updated. level:Debug name:Grpc.Net.Client.Balancer.Internal.ConnectionManager
04:17:39.553 msg:Successfully picked subchannel id '1' with address query.sa.uksouth.mixedreality.azure.com:443. level:Debug name:Grpc.Net.Client.Balancer.Internal.ConnectionManager

Here the logs of the desktop run ...(abbreviated)
04:20:36.021 msg:Starting gRPC call. Method type: 'DuplexStreaming', URI: 'https://query.sa.uksouth.mixedreality.azure.com/com.azure.mixedreality.sa.locoptquery.MapQueryPlanner/EnterMap'. level:Debug name:Grpc.Net.Client.Internal.GrpcCall [GrpcMethodType=DuplexStreaming],[GrpcUri=/com.azure.mixedreality.sa.locoptquery.MapQueryPlanner/EnterMap]
04:20:36.057 msg:Subchannel id '1' created with addresses: query.sa.uksouth.mixedreality.azure.com:443 level:Debug name:Grpc.Net.Client.Balancer.Subchannel 
04:20:36.091 msg:Channel picker updated. level:Debug name:Grpc.Net.Client.Balancer.Internal.ConnectionManager 
04:20:36.106 msg:Subchannel id '1' state changed to Connecting. Detail: 'Connection requested.'. level:Debug name:Grpc.Net.Client.Balancer.Subchannel 
04:20:36.124 msg:Channel state updated to Connecting. level:Debug name:Grpc.Net.Client.Balancer.Internal.ConnectionManager 
04:20:36.144 msg:Subchannel id '1' state changed to Ready. Detail: 'Passively connected.'. level:Debug name:Grpc.Net.Client.Balancer.Subchannel 
04:20:36.154 msg:Channel state updated to Ready. level:Debug name:Grpc.Net.Client.Balancer.Internal.ConnectionManager 
04:20:36.175 msg:Channel picker updated. level:Debug name:Grpc.Net.Client.Balancer.Internal.ConnectionManager 
04:20:36.187 msg:Successfully picked subchannel id '1' with address query.sa.uksouth.mixedreality.azure.com:443. level:Debug name:Grpc.Net.Client.Balancer.Internal.ConnectionManager 

04:20:37.401 msg:enter_map level:Debug name:LocOptMapContextSessionFactory [MapId=6895bbbd-08ea-4515-b8b7-dfe64068f465],[AccounId=829f0f39-0d64-40ec-9e99-063e97428248],[ms-cv=7YNL4Vn1bEqPZZoBfxd+Ng.0],[accept-encoding=identity,gzip]
04:20:37.414 msg:Sending message. level:Debug name:Grpc.Net.Client.Internal.GrpcCall [GrpcMethodType=DuplexStreaming],[GrpcUri=/com.azure.mixedreality.sa.locoptquery.MapQueryPlanner/EnterMap]
04:20:37.460 msg:Reading message. level:Debug name:Grpc.Net.Client.Internal.GrpcCall [GrpcMethodType=DuplexStreaming],[GrpcUri=/com.azure.mixedreality.sa.locoptquery.MapQueryPlanner/EnterMap]

### Anything else we should know about your project / environment?
The exact same project runs fine on the desktop box, no modifications just buuilding for Windows in MAUI make it to work i suspect the mono runtime behave differently than coreclr

**Comment by JamesNK** [comment]
How are you creating your gRPC channel? Could you add that code to the issue?

On Android, `SocketsHttpHandler` must be used to create the gRPC channel. It has full support for HTTP/2. If you're creating the channel with `HttpClientHandler` then it might cause this issue.

**Comment by rodrigovaras** [comment]
Thanks a lot, changing the message handler seems to fix the problem in Android.
