### ISSUE TITLE
SSL issue in Asp.Net.

### ISSUE THREAD

**Issue by YvonneArnoldus** [grpc/grpc-dotnet#1929]
I'm using gRPC with self-signed certifcates for root, client en server.

I can connect to my gRPC service from my Console app but I can't get it to work with Asp.net.

Server (created in .Net Framework 4.6.2):
```
     // read the certificate from the store
      var serverCertificate = CertifcateExtensions.GetCertifcateByThumbprint(gRPCServerThumbPrint);
      if (serverCertificate == null)
      {
        Logger.Warn("Could not find the correct GRPCSERVER Certificate. Please install the correct certificate");
        return;
      }

      // create sever credentials.
      var sslSerCred = new SslServerCredentials(new[] {
        new KeyCertificatePair(CertifcateExtensions.ExportPublicKeyToPEM(serverCertificate),
        CertifcateExtensions.ExtractKeyFromCertificate(serverCertificate))});

      // create gRpc server
      _gRPCServer = new Server
      {
        Services = { gRPC.BindService(new GRPCService(srv)) },
        Ports = { new ServerPort(_registeredHost, _registeredPort, sslSerCred) }
      };
```

Working client console client code (created with .Net 6):

```
var channelOptions = new List<ChannelOption> { new ChannelOption(ChannelOptions.SslTargetNameOverride, "GRPCSERVER") };
var channel = new Channel("169.254.80.80", 3157, sslClientCred1, channelOptions);
var client = new gRPC.gRPCClient(channel);
```

Not working client in Asp.Net code (created with .Net 6):

```
public void ConfigureServices(IServiceCollection services)
{
	services.AddGrpcClient<gRPC.gRPCClient>(tss.Name, options =>
	{
		// add url
		options.Address = new Uri(tss.Url);

		// logger
		options.ChannelOptionsActions.Add(a => a.LoggerFactory = loggerFactory);

		// add http handler for the certificate
		var handler = new HttpClientHandler();
		handler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;
		handler.ClientCertificates.Add(clientCert);
		options.ChannelOptionsActions.Add(a => a.HttpHandler = handler);

	})
	.ConfigurePrimaryHttpMessageHandler(() =>
	{
		// add handler.
		return new SocketsHttpHandler
		{
			// keeps connection alive
			PooledConnectionIdleTimeout = Timeout.InfiniteTimeSpan,
			KeepAlivePingDelay = TimeSpan.FromSeconds(60),
			KeepAlivePingTimeout = TimeSpan.FromSeconds(30),

			// allows channel to add additional HTTP/2 connections
			EnableMultipleHttp2Connections = true,

			// set the name of the target host
			SslOptions = new SslClientAuthenticationOptions
			{
				TargetHost = gRpcOptions.SslTargetNameOverride
			}
		};
	});
}
```

In the Asp.Net Core client I get the following error:

Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: The SSL connection could not be established, see inner exception. IOException: Cannot determine the frame size or a corrupted frame was received.", DebugException="System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

I tried to get the low level gRPC logging but it seems.

```
Environment.SetEnvironmentVariable("GRPC_VERBOSITY", "DEBUG");
Environment.SetEnvironmentVariable("GRPC_TRACE", "all");
GrpcEnvironment.SetLogger(new TextWriterLogger(TextWriter.Synchronized(File.CreateText("C:\\grpc.client.txt"))));
```

Also does not work in Asp.Net core.

Can anybody tell me how to add the low level logging in Asp.Net Core and how to make new ChannelOption(ChannelOptions.SslTargetNameOverride, "GRPCSERVER") work in Asp.Net Core?

**Comment by YvonneArnoldus** [comment]
Oke, I solved my issue why the ASP.Net Client didn't connect. I used different url's in the Asp.Net and the Console Client.

I still like to know how to do the low level gRPC logging through the GrpcEnvironment. Because that gives a better indication about the error than the Asp.Net log does.

**Comment by JamesNK** [comment]
You can add an event listener to HTTP logging from the client. Example of doing that: https://github.com/grpc/grpc-dotnet/blob/4c2e66ed85b4711cf7fdf062513771f5fd3a9fc7/test/Shared/HttpEventSourceListener.cs

And being used: https://github.com/grpc/grpc-dotnet/blob/456098bcfeb9c796c19ea023b3ab3703181f1089/test/FunctionalTests/Web/Client/AuthTests.cs#L50-L81

**Comment by YvonneArnoldus** [comment]
Thank you very much
