### ISSUE TITLE
Unicode control characters prefixed in some strings in latest packages

### ISSUE THREAD

**Issue by TXP-AlbertPucciani** [grpc/grpc-dotnet#1930]
### What version of gRPC and what language are you using?
Google.Protobuf 3.21.9
Grpc.AspNetCore 2.49.0
Grpc.AspNetCore.Web 2.49.0
Grpc.Net.Client 2.49.0

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET 6.0

### What did you do?
I upgraded from:
Google.Protobuf 3.21.1
Grpc.AspNetCore 2.47.0
Grpc.AspNetCore.Web 2.46.0
Grpc.Net.Client 2.47.0

In the latest version some of my strings are getting weird unicode control characters prefixed to them after returning to the client (testing using swagger and postman)

So far I have consistently seen: "\n\u0013", "\n\u0002", "\n\r" prefixed to some string fields

```
"region": "\n\u0002MI"
```
The proto looks like this:

```
string region = 7;
```

But I know for fact the value in the database has a length of 2 and equals "MI"

### What did you expect to see?

Those string fields without unicode control characters prefixed.

### Anything else we should know about your project / environment?
The protos are in a .NET Standard 2.0 project, referenced by a .NET 6 project. The solution is pretty big, I don't know enough how to reproduce this, but I'm hoping somebody sees this and has an "ah ha" moment because they know of some related code that was modified. Reverting back to the earlier packages resolves the issue, so this must be something introduced in a more recent update.

**Comment by JamesNK** [comment]
Nothing immediately springs to mind. There are many unit tests in gRPC and Protobuf, and I haven't seen this kind of regression in them. The regression is quite major, and I'd expect to have other people reporting it.

What package versions were you using originally? Can you figure out which package upgrade causes the error?
