### ISSUE TITLE
How to make generator mark code with ExcludeFromCoverage attribute?

### ISSUE THREAD

**Issue by voroninp** [grpc/grpc-dotnet#1933]
I'd like to automatically exclude generated code from code coverage analysis. As I can see, generated code is not marked with [`[ExcludeFromCodeCoverage]` attribute](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.excludefromcodecoverageattribute?view=net-6.0).

Is it possible to instruct generator to do it? Or is is a missing feature?

**Comment by rafikiassumani-msft** [comment]
Triage @voroninp Can your testing tool be configured to ignore the following attribute: `System.CodeDom.Compiler.GeneratedCode`

**Comment by voroninp** [comment]
@rafikiassumani-msft , yes, at least for [TeamCity](https://confluence.jetbrains.com/display/TCD7/JetBrains+dotCover).

**Comment by JamesNK** [comment]
You should do that. Adding a new attribute isn't possible.

**Comment by voroninp** [comment]
@JamesNK , but attribute is not applied to the classes, only methods and properties:

```
public sealed partial class DemoDesc : pb::IMessage<DemoDesc>
```

And it appears in coverage report anyway. ='(

**Comment by JamesNK** [comment]
I think those types don't have `GeneratedCode` attribute on them because it is possible to add new methods to them.

You could create matching partial types for them and add that attribute to them.

Or you could place all the generated code in its own project and exclude this project.
