### ISSUE TITLE
Update Grpc.Net.Client to use the latest version of Microsoft.Extensions.Logging.Abstractions given version 3.0.3 is deprecated 

### ISSUE THREAD

**Issue by Francisco-Gamino** [grpc/grpc-dotnet#1938]
### What version of gRPC and what language are you using?

Grpc.Net.Client, version 2.49.0

### What operating system (Linux, Windows,...) and version?

Windows

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)

```powershell
PS C:\> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.110
 Commit:    ce0a42998a

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.2.9200
 OS Platform: Windows
 RID:         win8-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.110\

global.json file:
  Not found

Host:
  Version:      6.0.10
  Architecture: x64
  Commit:       5a400c212a

.NET SDKs installed:
  3.1.424 [C:\Program Files\dotnet\sdk]
  6.0.110 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
PS C:\>
```

### What did you do?

Grpc.Net.Client, version 2.49.0 requires Microsoft.Extensions.Logging.Abstractions version 3.0.3. This version was release on 2/18/20 and it is deprecated. Could you please update this package to use the latest version of Microsoft.Extensions.Logging.Abstractions?

https://www.nuget.org/packages/Microsoft.Extensions.Logging.Abstractions#versions-body-tab
![image](https://user-images.githubusercontent.com/12720858/200041659-47c647d8-0335-45c6-b243-b043a4ae88c1.png)

### What did you expect to see?
N/A

### What did you see instead?
N/A

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc-dotnet/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by JamesNK** [comment]
gRPC currently still supports .NET Core 3.0. In a couple of months we'll look at removing out-of-date versions: 3.0, 3.1 (soon), 5.0

This package will be updated then.

However, there is nothing stopping your app from referencing a newer version of the package. It's backwards compatible.
