### ISSUE TITLE
The thrown exception's message is sooooooo unhelpful!!!

### ISSUE THREAD

**Issue by mobycorp** [grpc/grpc-dotnet#1939]
When an ASP.NET/gRPC application is first starting, it configures its http or https endpoints. If something is not configured correctly the application throws an error which is completely useless! The offending error is:

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.WaitForShutdownAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.WaitForShutdown(IHost host)
   at Program.<Main>$(String[] args) in D:\Development\Moby\Dev\MobyFileTransferServices\MobyFileTransferServices\Program.cs:line 206.
```

I have found that if any of the following occurs, this exception is thrown:

1. If the port is incorrect
2. If the TLS certificate is not found
3. If the TLS certificate's password is not correct
4. and there are others that I will add to this list when I can remember what they are

The internal code (either ASP.NET or gRPC - I am posting this in both forums) knows why it is throwing the exception so why not just say why the exception is being thrown! The `Object name: 'IServiceProvider'` message is a true red herring and completely useless. As I have come to have more experience on getting this to work, I grow more agitated in the lack of quality of that message. Look, getting SSL to work is hard enough to begin with. Help your developer community by throwing a better, more specific error!!!

For completeness' sage, I am including my Kestrel configuration.
appsettings:
```
	"Kestrel": {
		"EndpointDefaults": {
			"Protocols": "Http2",
			"SslProtocols": [ "Tls12" ]
		},
		"Endpoints": {
			"Https1": {
				"Certificate": {
					"Password": "123456",
					"Path": "localhost.pfx"
				},
				"Url": "https://*:30054"
			}
		}
	}
```
program.cs:
```
	// Add services to the container.
	_ = builder.Services.AddGrpc (grpcServiceOptions => {
		logger?.Debug ("Configuring presence intercepter...");
		grpcServiceOptions.Interceptors.Add<PresenceInterceptor> ();
		_ = grpcServiceOptions.EnableDetailedErrors = true;
	});
```

There is nothing special about this configuration. It's very simple. Please provide better messages as to why this initialization fails!!!

NOTE: I have downloaded both the gRPC and ASP.NET repositories and can't even find the string "Cannot access a disposed object" in the code... I have no idea where this message is being thrown from...

Regards,
Steve Miller

**Comment by JamesNK** [comment]
It looks like the error comes from this line: https://github.com/dotnet/runtime/blob/bd7e1cb81d763589b95f7bfbaa2a96dd364e9103/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/HostingAbstractionsHostExtensions.cs#L92

For some reason the service provider has been disposed before the app is shutdown.

I recommend you create an issue on dotnet/runtime repo and include a simple reproduction.

**Comment by mobycorp** [comment]
Thanks @JamesNK. I did also post the issue there...

**Comment by mobycorp** [comment]
@JamesNK - I was going to come back and update this after my list of issues regarding this error after some of them manifest themselves... I am once again listing this as a gRPC issue (but it may be a purely Kestrel issue).

I was installing an update of one of my services on an Ubuntu box and found this one again. When I use systemctl to stop a service, it does not always close the port that the app was using. If you try to start an app on a port that is locked, you will get this error. Again, the error displayed has NOTHING to do with the actual error!! I have run across at least three instances of this error being propagated and only found them by painstaking debugging. Seeing the ACTUAL cause would have saved me at least three days of development!!!
