### ISSUE TITLE
Use gRPC with both code-first and ClientFactory

### ISSUE THREAD

**Issue by minimalisticMe** [grpc/grpc-dotnet#1942]
Hi,

I have two ASP.NET 7.0 projects that I want to communicate via gRPC. One ASP.NET project will act as a `server`, the other ASP.NET 7 project will act as a `client`.
I don't want to care for creating `*.proto`-files, so I want to go code-first, creating an interface derived by `DataCrontract` following these docs: [Microsoft](https://learn.microsoft.com/de-de/aspnet/core/grpc/code-first?view=aspnetcore-7.0) and Github example [Coder](https://github.com/grpc/grpc-dotnet/tree/195e1c092265a464248e6ffa8e2c96796f74c606/examples/Coder).

For the Clientfactory I am now stuck, following [Microsoft](https://learn.microsoft.com/de-de/aspnet/core/grpc/clientfactory?view=aspnetcore-7.0) and Github example [Worker](https://github.com/grpc/grpc-dotnet/blob/master/examples/Worker) as I do not have an instance of the code-first generated class.

When calling `services.AddGrpcClient<Counter.CounterClient>(...)` I already need an `Counter`-instance that does not exist yet. In the code-first approach it will be generated by `channel.CreateGrpcService<ICounterService>()`, but then there already is assumed a `channel`-instance, which I don't have.

How can I use gRPC ClientFactory with the code-first approach?

**Comment by JamesNK** [comment]
https://protobuf-net.github.io/protobuf-net.Grpc/registerClientService

**Comment by minimalisticMe** [comment]
Thank you very much, this works like charm.
The only thing I can add: In order to use the proposed solution the `nuget` package `protobuf-net.Grpc.ClientFactory` needs to be installed. This was not clear to me upon first try.
