### ISSUE TITLE
macOS and iOS Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by ParkerRedford** [grpc/grpc-dotnet#1951]
### What version of gRPC and what language are you using?

Google.Protobuf 3.21.9
Grpc.Core 2.46.5
Grpc.Net.Client.Web
Grpc.Tools 2.50.0

### What operating system (Linux, Windows,...) and version?
macOS (Monterey 12.6) and iOS (any)
I can build project for Android successfully using macOS.

Running the project on Windows works just fine.

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.6
 OS Platform: Darwin
 RID:         osx.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  6.0.403 [/usr/local/share/dotnet/sdk]
  7.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

Build project for macOS and iOS

### What did you expect to see?
Run successfully

### What did you see instead?
`Undefined symbols for architecture x86_64
"_gprsharp_convert_clock_type", referenced from:
       -u command line option`
and about 50 more references

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc-dotnet/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by JamesNK** [comment]
I think this is a problem from the `Grpc.Tools` package. It executes `protoc`, a native compiler for protobuf messages. There might be compatibility issues with that OS.

`Grpc.Tools` code and issues are reported at https://github.com/grpc/grpc. If this issue is coming from `Grpc.Tools`, could you recreate this issue there?

**Comment by ParkerRedford** [comment]
I've recreated the issue at https://github.com/xamarin/xamarin-macios/issues/16842 because I've been seeing framework target sdk errors using dotnet build instead of the ide.

**Comment by JamesNK** [comment]
I'm closing this as there isn't work to be done in grpc-dotnet. If you want a fix in Grpc.Tools then you'll need to report an issue in https://github.com/grpc/grpc.
