### ISSUE TITLE
Throwing new RpcException indicated as 'Information' on ILogger

### ISSUE THREAD

**Issue by yoav-melamed** [grpc/grpc-dotnet#1952]
### What version of gRPC and what language are you using?
Grpc.AspNetCore 2.40.0
C#

### What operating system (Linux, Windows,...) and version?
Windows 11

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

### What did you expect to see?
I'm implementing a gRpc server in dotnet 6.0.
Everywhere I'm throwing (for example):
`throw new RpcException(new Status(StatusCode.Internal, "TEST"));`

I'm getting:
`info: Grpc.AspNetCore.Server.ServerCallHandler[7]
      Error status code 'Internal' with detail 'TEST' raised.`
In the console.
Please note the exception logged as an Info and not an Error.
Doing the same thing with a generic Exception object (for example):
`throw new Exception("TEST");`

Will results the logger to write:
`fail: Grpc.AspNetCore.Server.ServerCallHandler[6]
      Error when executing service method 'Register'.
      System.Exception: TEST
         at engine_broker.Services.OperationService.Register(RegisterRequest request, ServerCallContext context)
         at Grpc.Shared.Server.UnaryServerMethodInvoker`3.AwaitInvoker(Task`1 invokerTask, GrpcActivatorHandle`1 serviceHandle)
         at Grpc.Shared.Server.UnaryServerMethodInvoker`3.AwaitInvoker(Task`1 invokerTask, GrpcActivatorHandle`1 serviceHandle)
         at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
         at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)`

In the above you can see the exception has reported as 'fail' message and not an 'info'.
I'm using the default logger of asp.core 6

**Comment by JamesNK** [comment]
Yes, that's expected. An RpcException doesn't have to mean an unexpected error. For example, a method might throw RpcException with a status of InvalidArgument because the request wasn't completely validated.

I suggest creating an interceptor and logging all exceptions there if you want to log them at an error level.

**Comment by yoav-melamed** [comment]
Thank you @JamesNK !

> I suggest creating an interceptor and logging all exceptions there if you want to log them at an error level.

That's actually what I ended up doing. But it seems to be like killing a fly with a cannon :)
I don't know a lot of situations where someone throws an exception and expect it to be an informative message. Also in a case of InvalidArgument: It's more than a warning/error than an information (the method didn't get all the required inputs fully and correctly). Am I wrong?

**Comment by JamesNK** [comment]
The log message was changed from error to information because of customer feedback that a status like InvalidArgument logging as an error wasn't desired.

This is a case where everyone can't have exactly what they want.

**Comment by yoav-melamed** [comment]
I understand.
If that's the case, then the majority wins :)
I'll keep my interceptor in place.
Thank you very much @JamesNK  for taking the time to reply!
