### ISSUE TITLE
how to run server on console app (without  existing asp host)

### ISSUE THREAD

**Issue by setood** [grpc/grpc-dotnet#1953]
We have a big legacy server project, that uses own dependency injection, logging, `grpc.core` server, and no one asp.net hosting component. And now we meet a problem with `grpc.core` server, which haven't contain options to change `GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA` from `2` to any bigger. 
So we are decided to migrate to `grpc.dotnet`, because  as i know its have not any limit of amount pings without data.  
But i can't find any example how to use `grpc.dotnet` in non asp.net hosting apps.

**Comment by JamesNK** [comment]
You can add a `FrameworkReference` to a csproj to get access to APIs used to create a Grpc.AspNetCore server:

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-7.0&tabs=visual-studio#use-the-aspnet-core-shared-framework

Grpc.AspNetCore is hosted inside ASP.NET Core.
