### ISSUE TITLE
Can I generate messages as a separate project and then reuse these message types for server and client?

### ISSUE THREAD

**Issue by voroninp** [grpc/grpc-dotnet#1960]
I am thinking about the following project structure:

```
+-- Messages
  |
  +-- messages.proto (compiled)
  +-- service.proto (not compiled, imports `messages.proto`)'
+-- Server (references `Messages` project, so generaetd message could be reused, generates server)
  |
  +-- service.proto (added as a link from `Messages` project)
+-- Client (references `Messages` project, so generaetd message could be reused)
  |
  +-- service.proto (added as a link from `Messages` project, generates client.)
```

Is it possible to achieve? And if yes, how?

**Comment by voroninp** [comment]
Ok, I managed to achieve what I need by splitting proto file in two parts: with messages, and service. Service file imports messages proto, but is added just as a `<Content>`.

The only issue I have, I cannot reference both server and client assemblies because they both have static class with service name. One contains nested client, another - ServiceBase.

**Comment by chwarr** [comment]
I think the [Liber example](https://github.com/grpc/grpc-dotnet/tree/master/examples/Liber) is what you want to do:

* The [Common project only runs codegen and compiles the messages](https://github.com/grpc/grpc-dotnet/blob/80e2fabcf93b10cdf767a135cfafae40f35254bc/examples/Liber/Common/Common.csproj#L8).
* The [Client project only runs codegen on the service proto and only generates client stubs](https://github.com/grpc/grpc-dotnet/blob/80e2fabcf93b10cdf767a135cfafae40f35254bc/examples/Liber/Client/Client.csproj#L9).
* The [Server project is similar](https://github.com/grpc/grpc-dotnet/blob/80e2fabcf93b10cdf767a135cfafae40f35254bc/examples/Liber/Server/Server.csproj#L8).

The projects here use the [`GrpcServies` metadata](https://learn.microsoft.com/en-us/aspnet/core/grpc/basics?view=aspnetcore-6.0#add-a-proto-file-to-a-c-app) that [I mentioned before](https://github.com/grpc/grpc-dotnet/issues/1960#issuecomment-1323989320) to control what code is compiled into each project to avoid compiling anything twice.

**Comment by chwarr** [comment]
I don't remember the finer details here. Sorry.

**Comment by JamesNK** [comment]
Messages can be generated on there own. But a client or server is always generated with messages.

**Comment by voroninp** [comment]
@JamesNK , are not you mistaken? 

If all messages are defined in imported proto, and proto for which you set `GrpcServices="Server"` contains only definition of the service then only service is generated.

**Comment by JamesNK** [comment]
I was talking about everything in one file. Using multiple files can get around this, but some types could clash.

**Comment by OwnageIsMagic** [comment]
@JamesNK [the problem](https://github.com/grpc/grpc-dotnet/issues/1960#issuecomment-1324016189) is that you can't use separate Client and Server in one project due to name conflict on wrapper class.
