### ISSUE TITLE
ResourceExhaused exception does not log actual response size/maximum size setting

### ISSUE THREAD

**Issue by victormarante** [grpc/grpc-dotnet#1962]
Hi,

I recently integrated towards an external gRPC server, and started receiveing a lot of 
`Grpc.Core.RpcException: Status(StatusCode="ResourceExhausted", Detail="Received message exceeds the maximum configured message size.")`
Currently, I see no way to determine the actual response size, in order to determine the best course of action. Is there a way to enable this, or to log the response size prior to exception being thrown?

Package versions:
```
<ItemGroup>
   <PackageReference Include="Google.Protobuf" Version="3.21.9" />
   <PackageReference Include="Grpc.Net.Client" Version="2.49.0" />
   <PackageReference Include="Grpc.Net.ClientFactory" Version="2.49.0" />
</ItemGroup>
```

**Comment by doctorseus** [comment]
You should be able to set `https://github.com/grpc/grpc-dotnet/blob/master/src/Grpc.Net.Client/GrpcChannelOptions.cs#L69` to increase the size from the default. The actual length is not logged anywhere.

(If you really want to know the original size without debugging you could increase the size until it works, then serialize the object again to a protobuf. The result + some bytes is the original length.)

**Comment by victormarante** [comment]
Hi, I solved this in a different way, thanks for the help. We can close this issue for my sake.

**Comment by chenjing1294** [comment]
https://learn.microsoft.com/en-us/aspnet/core/grpc/configuration?view=aspnetcore-7.0#configure-client-options
