### ISSUE TITLE
Using Grpc on Azure with Visual Studio Template (VS 17.4.1, .net 7)

### ISSUE THREAD

**Issue by dgerding** [grpc/grpc-dotnet#1966]
Is there a demonstration of the correct way to configure and publish an Azure App Service, in VS2022 latest(17.4.1/.net 7), that:
•	Has a GRPC service (just using grpc project template) 
•	uses Linux Docker (also part of standard project template choices) for Azure App Service
•	uses an Azure SSL and hosted in an Azure Vault (yes, sni)

My understanding is GRPC requires https on http2. There is no need for http support. Only Http2 with https, again, for GRPC. 

The cert fetching code had worked in a prior build of this (on .net 6 project) but I'm just looking for a dial tone of grpc using the tools/targets (all MS stuff) referenced above since I haven't made it work yet with the new VS tooling and grpc project template.

Here's my current appsettings.json:

```
 "Kestrel": {
    "EndpointDefaults": {
      "Protocols": "Http2"
    }
  },
  "AllowedHosts": "*"
}
```
and here's the Kestrel config in my kestrel config:

```
...
webBuilder.UseStartup<Startup>();
                    webBuilder.UseUrls("http://localhost:80", "https://localhost:443")

                    
                    .UseKestrel(options =>
                     {
                         // configure Kestrel with our HTTPS certificate
                         options.ConfigureHttpsDefaults(options =>
                         {
                             try
                             {
                                 // When we get the certificate from Key Vault as a secret,
                                 // it provides the entire PFX file but without the password.
                                 // Since PFX is a binary format and a secret is a string,
                                 // it is base64 encoded. So we read in the text file and convert
                                 // it to the bytes to initialize the X509Certificate2.

                                 if (_appCertificate == null)
                                 {
                                     var certPath = Environment.GetEnvironmentVariable("HTTPS_CERTIFICATE_PATH");
                                     if (!string.IsNullOrEmpty(certPath))
                                     {
                                         var certString = System.IO.File.ReadAllText(certPath);
                                         var certBytes = Convert.FromBase64String(certString);
                                         _appCertificate = new X509Certificate2(certBytes);


                                         Console.WriteLine($"HTTPS cert Subject:    {_appCertificate.Subject}");
                                         Console.WriteLine($"HTTPS cert Thumbprint: {_appCertificate.Thumbprint}");

                                         // set the Kestrel HTTPS certificate
                                         options.ServerCertificate = _appCertificate;
                                     }
                                     else
                                     {
                                         throw new Exception("Missing HTTPS_CERTIFICATE_PATH");
                                     }
                                 }
                                 else
                                 {
                                     options.ServerCertificate = _appCertificate;
                                 }
                             }
                             catch (Exception ex)
                             {
                                 Console.Error.WriteLine($"unable to load https cert: {ex}");
                                 throw;
                             }
                         });
```

Here are a list of related links I've found, but no combination I try works. Thanks in advance.

Here are the resources I’ve looked at online.

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/http2?view=aspnetcore-6.0
https://learn.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-7.0
https://learn.microsoft.com/en-us/azure/key-vault/secrets/quick-create-net?tabs=azure-cli
https://thegreenerman.medium.com/set-up-https-on-local-with-net-core-and-docker-7a41f030fc76
https://andrewlock.net/5-ways-to-set-the-urls-for-an-aspnetcore-app/
https://dylanbeattie.net/2020/11/18/using-https-with-kestrel.html
https://learn.microsoft.com/en-us/azure/service-fabric/service-fabric-tutorial-dotnet-app-enable-https-endpoint (NOTE: for “fabric”)
https://devblogs.microsoft.com/dotnet/configuring-https-in-asp-net-core-across-different-platforms/
https://dev.to/425show/net-7-webapp-with-https-in-docker-secured-by-azure-ad-2nna
https://stackoverflow.com/questions/60090732/net-core-linux-kestrel-https-configuration
https://stackoverflow.com/questions/71170421/docker-errors-when-trying-to-publish-asp-net-project
https://stackoverflow.com/questions/55601949/application-gateway-502-error-when-configuring-it-for-azure-web-app
https://learn.microsoft.com/en-us/archive/blogs/waws/things-you-should-know-web-apps-and-linux#NoSCMDeploy

CLARIFYING: The above approach compiles and runs fine locally, but once published to Azure I get 502 errors from the outside, but on the azure side the service stands up and seems to be waiting for requests that never get there.

Thanks!
Dave G

**Comment by JamesNK** [comment]
I believe Azure App Service terminates TLS before it reaches your app. I'm unsure how using client certificates would work with Azure App Service. But I'm not an expert in this space.

**Comment by dgerding** [comment]
@JamesNK, thanks for the reply (and all your code !!!). I've got the certificate part handled, as this pattern _did_ work with as docker hosted linux azure app service until the upgrade to the newer vs project template and .net 7.

Since it is an official part of VS, and app services etc, it's surprising that someone else hasn't faced issue. I'll try posting over in ASP.NET etc... 

I'm going to leave the question open in hopes the some else has implemented the same combo successfully.

**Comment by JamesNK** [comment]
Closing. People can still read and comment.
