### ISSUE TITLE
How to find a specific client in the stream gRPC

### ISSUE THREAD

**Issue by gunhak01** [grpc/grpc-dotnet#1967]
I want to create Client and Server through gRPC Server Streaming or bi-streaming. 
I would like to distinguish each client at this time. 
I looked into it, and I think we can choose using unique ID to distinguish client or use peer to distinguish it.

What I am curious about is that when I want to send a response to only one specific client, I wonder if there is only a way to distinguish it through uid or peer after sending it to everyone. Can't the server send it to only one client from the beginning?

For example, suppose you created a server streaming grpc service called send(), request send() from multiple clients and wait for a response through stream. The server needs to respond to send() to a particular client, but I don't know how to generate only the send() service for this particular client.

I've already asked questions elsewhere, but the respondent said there would be a better way, 
so I'm asking again. 
[link](https://stackoverflow.com/questions/74597406/grpc-how-to-find-a-specific-client-in-the-stream-grpc)

Thank you.

@JamesNK

**Comment by JamesNK** [comment]
> The server needs to respond to send() to a particular client, but I don't know how to generate only the send() service for this particular client.

The client needs to specify an ID when it connects, the active requests need to be aggregated somewhere, and then the server picks the request to stream back a response based on its ID. This all becomes much more complicated as soon as you have multiple instances of a server.

It sounds like you're recreating SignalR. gRPC doesn't have built-in support for clients registering with the server and the server then broadcasting messages out. You have to build it yourself.

**Comment by gunhak01** [comment]
Thank you for your quick and accurate reply.
I'll make it based on what you told me!
