### ISSUE TITLE
Grpc verbosity

### ISSUE THREAD

**Issue by careless6666** [grpc/grpc-dotnet#1968]
If you set environment variables like this:

"GRPC_VERBOSITY": "DEBUG",
 "GRPC_TRACE": "api,cares_resolver,cares_address_sorting"

if you try call grpc client explicit created

`var channel = new Channel("dns:///any.servicename-scheduler.servicename.svc.dev1.k8s.company.net:82", ChannelCredentials.Insecure);`
`var client = new RoutingRulesService.RoutingRulesServiceClient(channel);`
`var rules = client.GetRoutingRules(new GetRoutingRulesRequest
          {
              TeamId = 1
          });
            `
  You will see normal trace, for example
  
  `1129 19:49:40.613659 Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library "/Users/alexander/Documents/ae/gitlab/sleepleseye/scheduler/src/Sleeplesseye.Scheduler.Service/bin/Debug/net6.0/runtimes/osx-arm64/native/libgrpc_csharp_ext.arm64.dylib"
D1129 19:49:40.657349 Grpc.Core.Internal.NativeExtension gRPC native library loaded successfully.
D1129 19:49:40.658727 6187429888 /Users/einari/Projects/grpc/grpc/src/core/lib/iomgr/ev_posix.cc:172: Using polling engine: poll
D1129 19:49:40.660090 6187429888 /Users/einari/Projects/grpc/grpc/src/core/ext/filters/client_channel/lb_policy_registry.cc:42: registering LB policy factory for "grpclb"
D1129 19:49:40.660135 6187429888 /Users/einari/Projects/grpc/grpc/src/core/ext/filters/client_channel/lb_policy_registry.cc:42: registering LB policy factory for "priority_experimental"
D1129 19:49:40.660160 6187429888 /Users/einari/Projects/grpc/grpc/src/core/ext/filters/client_channel/lb_policy_registry.cc:42: registering LB policy factory for "weighted_target_experimental"
D1129 19:49:40.660196 6187429888 /Users/einari/Projects/grpc/grpc/src/core/ext/filters/client_channel/lb_policy_registry.cc:42: registering LB policy factory for "pick_first"
D1129 19:49:40.660207 6187429888 /Users/einari/Projects/grpc/grpc/src/core/ext/filters/client_channel/lb_policy_registry.cc:42: registering LB policy factory for "round_robin"
D1129 19:49:40.660216 6187429888 /Users/einari/Projects/grpc/grpc/src/core/ext/filters/client_channel/lb_policy_registry.cc:42: registering LB policy factory for "ring_hash_experimental"
`
  but if i use client created from di i don't see anything trace information
  
  `services.AddGrpcClient<TClient>(configureClient)`
  
  How to view traces when registering via AddGrpcClient?
  
  We have dns resolution problem on our grpc clients, and we think it might be related

**Comment by JamesNK** [comment]
Channel, GRPC_VERBOSITY and GRPC_TRACE are from Grpc.Core. That's a different implementation for .NET.

See docs here for enabling logging with Grpc.Net.Client and Grpc.Net.ClientFactory: https://learn.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-6.0
