### ISSUE TITLE
State of support for Grpc.Net.Client.Web

### ISSUE THREAD

**Issue by ArthurHNL** [grpc/grpc-dotnet#2008]
Hi,

We are investigating the possibility of [using gRPC web on .NET Framework clients](https://learn.microsoft.com/en-us/aspnet/core/grpc/grpcweb?view=aspnetcore-7.0#configure-grpc-web-with-the-net-grpc-client) that we cannot migrate to .NET (Core) and that have to run on a Windows version that does not offer the HTTP/2 capabilities required for 'full' gRPC.

Looking at the [support offered by Microsoft for grpc-dotnet](https://github.com/grpc/grpc-dotnet/blob/master/microsoft-support.md), the server-side package of gRPC-Web (`Grpc.AspNetCore.Web`) is supported, but the client package for gRPC-Web on .NET is not present in this list (`Grpc.Net.Client.Web`).

Thus my question is, does Microsoft support the gRPC-Web client for .NET? And if not, why does Microsoft provide guidance on learn.microsoft.com on how to use the gRPC-Web client for .NET without supporting it?

I'm looking forward to your reply.

**Comment by JamesNK** [comment]
Grpc.Net.Client.Web is supported. It's a mistake that it's not in the list.

**Comment by ArthurHNL** [comment]
@JamesNK Thanks for your quick reply and change 👍
