### ISSUE TITLE
 grpc circuit breaker - .net core 6

### ISSUE THREAD

**Issue by vovapabyr** [grpc/grpc-dotnet#2011]
Hi everyone,
Following the [discussion](https://stackoverflow.com/questions/72126738/grpc-and-polly-net-core-6) it looks like we can't longer use polly `.AddPolicyHandler()` to build retry policy with grpc .net 6. The right way to build retry with grpc in .net 6 is described in this [post](https://learn.microsoft.com/en-us/aspnet/core/grpc/retries?view=aspnetcore-6.0). But, what is the right way to implement retry + circuit breaker with grpc in .net 6?

**Comment by JamesNK** [comment]
gRPC has retry functionality built in. There isn't built-in circuit breaker functionality, but you might be able to add something using a client interceptor.

**Comment by vovapabyr** [comment]
Thanks for the answer, @JamesNK. It still sounds easier to me to use polly `ExecuteAsync` method explicitly, than use built-in retry + client interceptor approach.

**Comment by JamesNK** [comment]
Ok!
