### ISSUE TITLE
OperationCanceledException thrown when canceling a CancelationToken does not reference the token canceled

### ISSUE THREAD

**Issue by hakenr** [grpc/grpc-dotnet#2014]
### What version of gRPC and what language are you using?
Grpc.Net.Client v2.51.0, .NET C#, Blazor WebAssembly

### What operating system (Linux, Windows,...) and version?
WebAssembly (browser) - .NET

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET SDK 7.0.2

### What did you do?
If you cancel a CancelationToken provided to the gRPC client, the OperationCanceledException thrown does not reference the token.

Context: Many implementations use this pattern to "catch" the cancelation:
```csharp
        catch (Exception e)
        {
            if (e is OperationCanceledException oce && oce.CancellationToken == cancellationToken)
            {
                // No-op; we canceled the operation, so it's fine to suppress this exception.
            }
```
e.g. Blazor's `Virtualize` component: https://github.com/dotnet/aspnetcore/blob/dfab67748084f120472e634a975b3c45150f608b/src/Components/Web/src/Virtualization/Virtualize.cs#L378-L383

### What did you expect to see?
1) The `OperationCanceledException.CancellationToken` (in `RpcException.DebugException`) should be the original `CancellationToken` canceled.
2) In case of cancellation, the `OperationFailedException` should not be wrapped by `RpcException`. It does not make sense as there is literally no use case where you would take advantage of having a `RpcException` instead of the very specific `OperationCanceledException` being caught by the caller expecting cancellation (such as `Virtualize` component in Blazor).

### What did you see instead?
`OperationCanceledException.CancellationToken` is `null`.
`OperationCanceledException` is masked by `RpcException` which implies need for "correcting" interceptor.

### Anything else we should know about your project / environment?
I created a simple repro with Blazor-Virtualize.
https://github.com/hakenr/VirtualizeGrpcRepro

The repro includes an active interceptor which "fixes" the error (for the `AsyncUnaryCall`):
https://github.com/hakenr/VirtualizeGrpcRepro/blob/master/BlazorGrpcWebCodeFirst/Client/CancellationWorkaroundGrpcClientInterceptor.cs

If you remove the registration of `CancellationWorkaroundGrpcClientInterceptor` from `BlazorGrpcWebCodeFirst.Client/Program.cs` (line 18) you immediately see the result - the `OperationFailedException` not being caught by `Virtualize`, which breaks the app.

cc @JamesNK, @mgravell

**Comment by hakenr** [comment]
Adjusted the title as the real goal is to be able to use gRPC client in use-cases such as `Virtualize` (where there is `OperationCanceledException` being caught) without need for any post-corrections with interceptors (such as unwrapping the `OperationFailedException` from `RpcException` or struggling with the `CancellationToken`).

**Comment by JamesNK** [comment]
There is a `ThrowOperationCanceledOnCancellation` option on the gRPC channel.

I agree btw, but we chose to it this way for backwards compact with gRPC.Core

**Comment by hakenr** [comment]
@JamesNK I didn't know about the `ThrowOperationCanceledOnCancellation` option. I will take a look and try to use it instead of the interceptor. I will let you know if it helps.

**Comment by hakenr** [comment]
@JamesNK Let me return to the original sub-issue. When I set `ThrowOperationCanceledOnCancellation = true`, the `OperationCancelledException` thrown does carry another `CancellationToken` than the `CancellationToken` provided to the client call and canceled by the `Virtualize`:
```csharp
public async ValueTask<ItemsProviderResult<CountryVM>> GetDataAsync(ItemsProviderRequest request)
{
	DataFragmentRequest<CountryVM> dataFragmentRequest = new()
		{
			StartIndex = request.StartIndex,
			Count = request.Count
		};

	try
	{
		var result = await CountryFacade.GetCountriesAsync(dataFragmentRequest, request.CancellationToken);
		return new ItemsProviderResult<CountryVM>(result.Data, result.TotalCount);
	}
	catch (OperationCanceledException ex)
	{
		Console.WriteLine("Exception: " + ex.ToString());
		Console.WriteLine("Token: " + ex.CancellationToken.GetHashCode());
		Console.WriteLine(ex.CancellationToken == request.CancellationToken ? "same" : "other"); // indicates OTHER
		throw;
	}
}
```

Usual logic (here represented by `Virtualize`) checks the `exception.CancellationToken` and the test fails:
```csharp
        catch (Exception e)
        {
            if (e is OperationCanceledException oce && oce.CancellationToken == cancellationToken)
            {
                // No-op; we canceled the operation, so it's fine to suppress this exception.
            }
```
https://github.com/dotnet/aspnetcore/blob/dfab67748084f120472e634a975b3c45150f608b/src/Components/Web/src/Virtualization/Virtualize.cs#L378-L383

As a confirmation, this fixes the issue:
```csharp
catch (OperationCanceledException ex)
{
	Console.WriteLine("Exception: " + ex.ToString());
	Console.WriteLine("Token: " + ex.CancellationToken.GetHashCode());
	Console.WriteLine(ex.CancellationToken == request.CancellationToken ? "same" : "other"); // indicates OTHER

	request.CancellationToken.ThrowIfCancellationRequested(); // fixes the isuue, throws correct exception with corresponding token
	
	throw;
}
```

**Comment by JamesNK** [comment]
Ok. There is an internal CancellationTokenSource for each gRPC call. I think there is a way to cancel it so that the reported token is the original one. Might be able to fix this in the gRPC client so your workaround isn't needed.
