### ISSUE TITLE
GrpcWeb support for .NET Framework

### ISSUE THREAD

**Issue by MustafaSuyi** [grpc/grpc-dotnet#2016]
Hello, will gRPC Web client and .NET Framework be supported in the future? I saw a lot of people having problems with this issue. If no work is planned for this, could you share an example project in which you use a .NET Framework gRPC server and Blazor WASM via proxies, or any other solutions if any? I believe it would be useful for many developers because there is no documentation or solution in the forums.

**Comment by JamesNK** [comment]
It's supported today.

**Comment by MustafaSuyi** [comment]
I tried to implement right away and got some Http exception because I couldn't find a mechanism for gRPC-Cors like MapGrpcService<SomeService>().RequireCors("SomeCors") in .NET Framework and that's probably an issue for another repository. Thank you!
