### ISSUE TITLE
Is there a way to output more diagnostic data at health check call?

### ISSUE THREAD

**Issue by thepra** [grpc/grpc-dotnet#2023]
I've setup a simple scenario with the usual configuration:
```
//Program.cs
    builder.Services.AddGrpc();
    builder.Services.AddGrpcHealthChecks()
        .AddCheck<MyCustomHealthCheck>("");
//...
    app.MapGrpcHealthChecksService();
```
And at `MyCustomHealthCheck : IHealthCheck` I provide on both kind of answers some data(`Dictionary<string,object>`) about the service checked like:
```
HealthCheckResult.Unhealthy("unhealthy", data: diagnostics);
HealthCheckResult.Healthy("healthy", data: diagnostics);
```
Now when I call from the client I get an answer like this:
```
{
  "status": 2
}
```
But I was expecting to get those extra data. 
Is there something that I miss to get those extra data?

**Comment by JamesNK** [comment]
There isn't a way to get more data from the gRPC health check service. By design it returns just a status. Here is the contract: https://github.com/grpc/grpc/blob/9378a7d2622cfd13b6f4fbc9aa979f931d6a8ca3/src/proto/grpc/health/v1/health.proto#L39
