### ISSUE TITLE
Globalization/Localization not working 

### ISSUE THREAD

**Issue by rizi** [grpc/grpc-dotnet#2024]
We have implemented a custom implementation of a localization provider like it's described here: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/localization#use-a-custom-provider

Complete guide:
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/localization

The provider is working fine with MVC/WebApi, but with gRPC(AsyncUnaryCall) it's not working correctly. Our custom provider is called and executed correctly, but as soon as the gRPC service(C#) is executed the default culture is used instead of the one returned by our Custom Provider.

The easiest way to check the current culture is to print the result of Thread.CurrentCulture and Thread.CurrentUICulture.

Is localization not supported in gRPC.net or do we have to configure something additional?

I can not find any details about that.

@JamesNK  Any help would be appreciated.

Fyi:
I also implemented a service interceptor that just does nothing but prints the result of Thread.CurrentCulture and Thread.CurrentUICulture and calls the continuation function --> and it seems that the correct culture is used here, but later (when the method of the service is executed) the wrong(default) culture is used, so it seems there must be something wrong in the last part of the gRPC execution chain.

Br

**Comment by JamesNK** [comment]
I added a test for this and found the server method had the correct culture set:

https://github.com/grpc/grpc-dotnet/pull/2039

**Comment by rizi** [comment]
> I added a test for this and found the server method had the correct culture set:
> 
> #2039

What does this mean, should it work out of the box?
Do you have any ideas why it's not working on our side?

B

**Comment by JamesNK** [comment]
I'm not familiar with the feature. I expect it works with gRPC, and it works in the test I wrote.

I don't know why it isn't working for you.

**Comment by rizi** [comment]
> I'm not familiar with the feature. I expect it works with gRPC, and it works in the test I wrote.
> 
> I don't know why it isn't working for you.

@JamesNK it's interesting that in the grcp interceptor the culture is still correct, can it be interceptor related? Do you know someone from the asp.net core team that could provide some information/help?

Br

**Comment by JamesNK** [comment]
I think you need to create a simple reproduction of the problem and put it in a github repo. Myself or someone from the ASP.NET Core team can take a look.

**Comment by rizi** [comment]
> I think you need to create a simple reproduction of the problem and put it in a github repo. Myself or someone from the ASP.NET Core team can take a look.

@JamesNK thx the unit tests you added helped me to figure out the problem.

Therefore I will close this issue/question.
