### ISSUE TITLE
Easiest way to change target host during call

### ISSUE THREAD

**Issue by Blackclaws** [grpc/grpc-dotnet#2028]
So this might be a bit of an edge case and I think I've found a potential way this is possible, however I'd like to ask whether there is an easier way.

Let me start with my problem statement. I have a gRPC service that is going to be hosted by different microservices, performing a similar function in each of them. It made sense to define this centrally as the concerns are really the same for each hosting service (think health check, general information, etc.).

In my specific case I can only determine the address/host for a request from the contents of the request message.

Since interceptors do not allow me to change the host property of the CallInterceptorContext that solution is out.

My current approach is to subclass the generated client and override the method call. This would allow me to create a CallInvoker and channel for each possible target. 

However accessing the method information isn't possible from a subclass as that is private to the generated client. I could of course now use reflection (which is probably what I'm going to do) but I wonder whether there is an easier way to go about this.

Manually building the Method seems excessively tedious especially since you also need to build the Marshallers and in the end it looks like I'd have to copy most of the generated code for that.

Is there any sort of interceptor/functionality that I might have missed? Or is there any easier access to the Method definitions so I can manually call the CallInvoker with it?

**Comment by Blackclaws** [comment]
So after working on this for a while:

Technically it works to just create a new CallInvoker each time. However, this isn't really that different from just creating a new channel in some manager class based on the message, and one has to duplicate a ton of functionality in order to get it to work.

There's a couple of red herings you can follow in the codebase though. For example the CallInvokers AsyncUnaryCall method takes a host string? argument. That argument is discarded by the ClientBaseConfigurationInterceptor:

https://github.com/grpc/grpc-dotnet/blob/4bf9312123f8a63caa408ca74d92040e5763beb4/src/Grpc.Core.Api/ClientBase.cs#L221

See that ```this.host``` is passed.

This is all moot to a degree however as this gets all passed down to the HttpClientCallInvoker that still has the Channel that the CallInvoker was originally created for and that doesn't allow any changes to the target host anyway.

Therefore I conclude that in order to switch the destination host based on the message I'll have to create a new channel for each of them.

This basically also means that the AddGrpcClient<T> methods are all out for me, because the GrpcClients that are configured there don't allow any sort of channel configuration while you get them out of the ServiceProvider.

I can't even use the GrpcClientFactory to specify the Channel because that is all baked in to the options object at the beginning and the GrpcCallInvokerFactory just takes a name to an already registered options object.

Maybe I'm missing something. But I'd like to use all the nice functionality in the GrpcClient Service Extensions, such as not creating extra channels and reusing MessageHandlers, but I just can't seem to get it to work. Any help would be appreciated.

**Comment by JamesNK** [comment]
I think you could try changing the "host" header in a DelegatingHandler, then configure the gRPC channel to use the delegating handler.

**Comment by Blackclaws** [comment]
> I think you could try changing the "host" header in a DelegatingHandler, then configure the gRPC channel to use the delegating handler.

You mean changing the RequestUri in a DelegatingHandler? That wouldn't work easily in this case because the same channel might be used by more than one request at the same time and I don't have access to the original message in the handler unless I pass it as metadata along which seems superfluous. Also I have a CallCredential handler which retrieves credentials depending on the target host, and this would get called before the correct target is set by the DelegatingHandler.

I think that what I wanted to do was simply a bit out of scope of what this library is supposed to do. What I ended up doing was write a Manager class around the Client which internally creates new instances of the service with channels set up for the right targets, with the call signatures being identical for the Manager class and the Client for easy passthrough.

Unless you want to continue the discussion around this, feel free to close the issue :)
