### ISSUE TITLE
Support for Compression Formats

### ISSUE THREAD

**Issue by Sen-Gupta** [grpc/grpc-dotnet#2030]
Hello @JamesN King ;-) 

Just wondering, **SignalR support MessagePack for serialization**.
https://learn.microsoft.com/en-us/aspnet/core/signalr/messagepackhubprotocol?view=aspnetcore-7.0

Not sure, but seems like this one:
https://github.com/neuecc/MessagePack-CSharp

From the same Developer, **We have now: MemoryPack**
https://github.com/Cysharp/MemoryPack
(Claims to be faster than anything else for now)

I have 2 folds question here:

First: 
**Do we have support for customizing compression/serialization formats like SignalR  in Grpc DotNet?**

Second: 
**What risks we run if we develop such compression/serialization ourselves?** 

For example:
The Author @neuecc  has Developed a client called **GrpcWebSocketBridge**. (We like it and probably you have already seen this)
https://github.com/Cysharp/GrpcWebSocketBridge with **MagicOnion** https://github.com/Cysharp/MagicOnion

( have tried it and it works with Message Pack and MemoryPack Both) **(I upgraded the GrpcWebSocketBridge for .Net 7 but not sure if it is right path to follow?)**

Background:
We have our blazor apps server/wasm/maui-blazor(windows)/maui-android/maui-ios built and developed using Code First Grpc.

We have noticed that it works well on server (less than a second), a little slow (grpc-web, 3 seconds) on wasm and terrible (30 seconds) on Android to pull data from server and populate the sqlite database on client side.
(We do 12 calls to server to populate our database with server side streaming, different endpoints)

We like the cleaner code first approach and hence looking for solutions(MagicOnion?)

We feel our problems are multifold here. 

(WASM is single threaded) - Until .Net 8!

On Android we should be leverating Multithreading as we should be able to run these calls in parallel?

But we also feel that compression is also a problem as we have around 20MB data for each client who logs in first time on the device to be pulled.

It would be great to hear your thought on this!

**Comment by JamesNK** [comment]
gRPC supports compression today: https://github.com/grpc/grpc-dotnet/tree/master/examples#compressor

**Comment by Sen-Gupta** [comment]
@JamesNK Thank you! Looking at it and will share my thought...

**Comment by Sen-Gupta** [comment]
@JamesNK for the lack of my knowledge in this area, It seems i have confused compression with serialization?

What would be the right approach to plug MemoryPack with grpc?

**Comment by JamesNK** [comment]
A different serializer can be plugged in, but it is more complicated. I haven't done that myself, but Code First gRPC is an example of using a custom serializer.

**Comment by Sen-Gupta** [comment]
As quoted above: 
I guess this serves as an example.
The Author @neuecc has Developed a client called GrpcWebSocketBridge. (We like it and probably you have already seen this)
https://github.com/Cysharp/GrpcWebSocketBridge with MagicOnion https://github.com/Cysharp/MagicOnion

I can potentially look at the implementation Code First Grpc. (Thank you for the clue)

By the way, just wondering apart from Gzip what other compressior are supported? Brotli?

**Comment by JamesNK** [comment]
Deflate. Or you can write your own compression provider.
