### ISSUE TITLE
gRPC Client Never Receives Response Headers

### ISSUE THREAD

**Issue by Morhpeuss** [grpc/grpc-dotnet#2037]
### What version of gRPC and what language are you using?
C#,  Grpc.AspNetCore.Web 2.51.0 (on server),  Grpc.Net.Client.Web 2.51.0 (Client. Blazor WebAssembly)

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET SDK 7

### What did you do?

I want to send information about the current client version from the server in all responses. I want to have this information in the HTTP header. 

I call the method WriteResponseHeaderAsyn in the server method or interceptor (tried both). I see (Fiddler) that the header is in the response header.

But, I cannot read this header on the client or interceptor on the client. I tried everything. 

My code:
 
`var result = AuthorizationClient.LoginAsync(loginRequest);                
var responseHeaders = await result.ResponseHeadersAsync;
`
ResponseHeaders is empty all time. I am able to use Trailers but the right place is HTTP header.

Is possible to read the response headers? Is possible to read the response headers in interceptors?

If yes, how?

Thanks.

**Comment by JamesNK** [comment]
Are you using CORS? You might need to specify the custom header the server is sending.

**Comment by Morhpeuss** [comment]
Perfect,  I exposed the header and now I am able to find him. 

But the second question. I need to verify this header for all responses. I am not sure if the interceptor is a good place.  

Is the good approach to do this in the custom httpmessagehandler.

For example:

`public class CustomHttpClientHandler
	 : DelegatingHandler
	{

		public CustomHttpClientHandler(HttpMessageHandler innerHandler)
		 : base(innerHandler)
		{

		}

		protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
		{
			var response = await base.SendAsync(request, cancellationToken);

			var versionHeader = response.Headers.FirstOrDefault(a =>  a.Key == "client-version");
			
			// check the version header
			return response;
		}
	}`

**Comment by JamesNK** [comment]
Either one works.

**Comment by Morhpeuss** [comment]
@JamesNK  Could you send me an example of how to do it in interceptor? Thx

**Comment by JamesNK** [comment]
There is documentation for writing an interceptor, and samples of writing interceptors that you can look at.
