### ISSUE TITLE
Client stream stops sending response mid-message

### ISSUE THREAD

**Issue by ThorstenReichert** [grpc/grpc-dotnet#2040]
### What version of gRPC and what language are you using?
Grpc.AspNetCore 2.51.0 / C#

### What operating system (Linux, Windows,...) and version?
Windows Server 2019 (17763.3887)

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
 Microsoft.AspNetCore.App 7.0.2
 Microsoft.NETCore.App 7.0.2
and some older versions installed (app is .NET 7)

### What did you do?
I have a Grpc service with a client-streaming method
```protobuf
syntax = "proto3";

service Service
{
	rpc Foo(stream Request) returns (Response);
}

message Request { bytes content = 1; }
message Response { bytes content = 1; }
```

For testing purposes, the server application is simply accepting any number of `Request`s, but ignores all of them (except some log message). Finally, it sends a response back to the client:
```csharp
await foreach (var request in requestStream.ReadAllAsync())
{
    _logger.Info($"Received message");
}

_logger.Info("Received all messages");

return new Response
{
    Content = RandomBytes(100 * 1024 * 1024)
};
```
The only non-standard part here is, that the messages are relatively large (0.5 - 5MB for requests, 100MB response) and there are lots of request messages (~150).

### What did you expect to see?
Response is received on the client side.

### What did you see instead?
Under certain circumstances (see below) the server stops sending the response mid-message. By this I mean it starts sending the response, but before it is fully transmitted, it just stops. Neither server nor client show any sign of errors. In the logfile, this looks like (just the ASP.NET Core and Grpc parts):
```
...
17:46:38.4591;Trace;Connection id "0HMO836T7LU0F" received DATA frame for stream ID 3 with length 16384 and flags NONE.;<Server>;21540;.NET ThreadPool Worker;7;Microsoft.AspNetCore.Server.Kestrel.Http2;
...
17:46:38.4671;Trace;Connection id "0HMO836T7LU0F" received DATA frame for stream ID 3 with length 16384 and flags NONE.;<Server>;21540;.NET ThreadPool Worker;18;Microsoft.AspNetCore.Server.Kestrel.Http2;
17:46:38.4671;Trace;Connection id "0HMO836T7LU0F" sending WINDOW_UPDATE frame for stream ID 3 with length 4 and flags 0x0.;<Server>;21540;.NET ThreadPool Worker;7;Microsoft.AspNetCore.Server.Kestrel.Http2;
17:46:38.4671;Trace;Connection id "0HMO836T7LU0F" received DATA frame for stream ID 3 with length 16384 and flags NONE.;<Server>;21540;.NET ThreadPool Worker;18;Microsoft.AspNetCore.Server.Kestrel.Http2;
...
17:46:38.4671;Trace;Connection id "0HMO836T7LU0F" received DATA frame for stream ID 3 with length 16384 and flags NONE.;<Server>;21540;.NET ThreadPool Worker;19;Microsoft.AspNetCore.Server.Kestrel.Http2;
17:46:38.4671;Trace;Connection id "0HMO836T7LU0F" sending WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0.;<Server>;21540;.NET ThreadPool Worker;21;Microsoft.AspNetCore.Server.Kestrel.Http2;
17:46:38.4671;Trace;Connection id "0HMO836T7LU0F" received DATA frame for stream ID 3 with length 16384 and flags NONE.;<Server>;21540;.NET ThreadPool Worker;19;Microsoft.AspNetCore.Server.Kestrel.Http2;
...
17:46:38.4817;Trace;Connection id "0HMO836T7LU0F" received DATA frame for stream ID 3 with length 16384 and flags NONE.;<Server>;21540;.NET ThreadPool Worker;23;Microsoft.AspNetCore.Server.Kestrel.Http2;
17:46:38.4817;Trace;Connection id "0HMO836T7LU0F" received DATA frame for stream ID 3 with length 7752 and flags END_STREAM.;<Server>;21540;.NET ThreadPool Worker;16;Microsoft.AspNetCore.Server.Kestrel.Http2;
17:46:38.4817;Debug;Connection id "0HMO836T7LU0F", Request id "0HMO836T7LU0F:00000003": done reading request body.;<Server>;21540;.NET ThreadPool Worker;16;Microsoft.AspNetCore.Server.Kestrel;
17:46:38.4817;Trace;Deserializing 528478 byte message to '<Request>'.;<Server>;21540;.NET ThreadPool Worker;16;Grpc.AspNetCore.Server.ServerCallHandler;
17:46:38.4817;Trace;Received message.;<Server>;21540;.NET ThreadPool Worker;16;Grpc.AspNetCore.Server.ServerCallHandler;
17:46:38.4817;Debug;Reading message.;<Server>;21540;.NET ThreadPool Worker;16;Grpc.AspNetCore.Server.ServerCallHandler;
17:46:38.4817;Trace;No message returned.;<Server>;21540;.NET ThreadPool Worker;16;Grpc.AspNetCore.Server.ServerCallHandler;
17:46:38.5631;Debug;Sending message.;<Server>;21540;.NET ThreadPool Worker;21;Grpc.AspNetCore.Server.ServerCallHandler;
17:46:38.6256;Trace;Serialized '<Response>' to 104857630 byte message.;<Server>;21540;.NET ThreadPool Worker;21;Grpc.AspNetCore.Server.ServerCallHandler;
17:46:38.6256;Trace;Message sent.;<Server>;21540;.NET ThreadPool Worker;21;Grpc.AspNetCore.Server.ServerCallHandler;
17:46:38.6256;Info;Executed endpoint 'gRPC - /Service/Foo';<Server>;21540;.NET ThreadPool Worker;21;Microsoft.AspNetCore.Routing.EndpointMiddleware;
17:46:38.6256;Info;Request finished HTTP/2 POST http://<Server>/Service/Foo application/grpc - - 200 - application/grpc 8257.3213ms;<Server>;21540;.NET ThreadPool Worker;21;Microsoft.AspNetCore.Hosting.Diagnostics;
17:46:38.6256;Trace;Connection id "0HMO836T7LU0F" sending HEADERS frame for stream ID 3 with length 59 and flags END_HEADERS.;<Server>;21540;.NET ThreadPool Worker;23;Microsoft.AspNetCore.Server.Kestrel.Http2;
17:46:38.6256;Trace;Connection id "0HMO836T7LU0F" sending DATA frame for stream ID 3 with length 16384 and flags NONE.;<Server>;21540;.NET ThreadPool Worker;23;Microsoft.AspNetCore.Server.Kestrel.Http2;
...
17:46:38.7707;Trace;Connection id "0HMO836T7LU0F" sending DATA frame for stream ID 3 with length 16384 and flags NONE.;<Server>;21540;.NET ThreadPool Worker;16;Microsoft.AspNetCore.Server.Kestrel.Http2;
17:46:38.7707;Trace;Connection id "0HMO836T7LU0F" sending DATA frame for stream ID 3 with length 16384 and flags NONE.;<Server>;21540;.NET ThreadPool Worker;16;Microsoft.AspNetCore.Server.Kestrel.Http2;
17:46:38.7707;Trace;Connection id "0HMO836T7LU0F" sending DATA frame for stream ID 3 with length 16384 and flags NONE.;<Server>;21540;.NET ThreadPool Worker;16;Microsoft.AspNetCore.Server.Kestrel.Http2;
17:46:38.7707;Trace;Connection id "0HMO836T7LU0F" sending DATA frame for stream ID 3 with length 16384 and flags NONE.;<Server>;21540;.NET ThreadPool Worker;16;Microsoft.AspNetCore.Server.Kestrel.Http2;
17:46:38.7707;Trace;Connection id "0HMO836T7LU0F" sending DATA frame for stream ID 3 with length 16384 and flags NONE.;<Server>;21540;.NET ThreadPool Worker;16;Microsoft.AspNetCore.Server.Kestrel.Http2;
17:48:30.6002;Debug;Connection id "0HMO836T7LU0F" received FIN.;<Server>;21540;.NET ThreadPool Worker;16;Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets;
17:48:30.6002;Debug;Connection id "0HMO836T7LU0F" is closed. The last processed stream ID was 3.;<Server>;21540;.NET ThreadPool Worker;16;Microsoft.AspNetCore.Server.Kestrel.Http2;
17:48:30.6002;Debug;Connection id "0HMO836T7LU0F" sending FIN because: "The client closed the connection.";<Server>;21540;.NET ThreadPool Worker;16;Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets;
17:48:30.6002;Debug;The connection queue processing loop for 0HMO836T7LU0F completed.;<Server>;21540;.NET ThreadPool Worker;16;Microsoft.AspNetCore.Server.Kestrel.Http2;
17:48:30.6002;Debug;Connection id "0HMO836T7LU0F" stopped.;<Server>;21540;.NET ThreadPool Worker;16;Microsoft.AspNetCore.Server.Kestrel.Connections;
```
As you can see, the server starts sending the response up until 17:46:38.7707, after that there is simply nothing. Finally, the client terminates the connection after a 2min timeout (but waiting longer also does not help).

Now, for the circumstances of _when_ this happens:
- The response message needs to be large (100MB in this case, for 1MB I could not repro the issue)
- The distance between client and server needs to be somewhat nontrivial (few 100km in my case), issue never occurred when client and server are on the same machine (or in the same building)
- Some `Request` messages are required. Without sending requests, the response is fully transmitted

What struck me as particularly odd is the reliance on `Request`s. So I monitored the Server app via ProcMon and had the transmitted bytes recorded this way (Receive Bytes is a measure for how many requests were sent):
```
#Success;   #Send Bytes;    #Receive Bytes; 
false;      1.053.396;      73.032.261;     
false;      1.053.936;      73.032.491;     
false;      1.053.383;      73.033.553;     
false;      1.051.862;      46.064.351;     
true;       104.916.816;    19.626.155;     
false;      2.624.138;      19.625.112;     
false;      3.148.697;      19.625.260;     
true;       104.916.153;    7.463.981;      
true;       104.916.127;    7.463.720;      
true;       104.916.140;    7.463.679;      
false;      1.053.383;      37.033.616;     
true;       104.915.775;    1.284;          
true;       104.915.707;    1.099;          
true;       104.915.707;    1.086;    
```

It seems to be that
- Fewer requests means higher probability of response being transmitted
- Fewer requests means more of the response is submitted
- For a given "mass" of requests, the response always stops being sent after a very similar number of bytes

If needed, I can upload the entire ProcMon or PerfView event collections, provide full logfiles, etc.
In general, I'd be happy to get even hints at what or how I could try to diagnose here, seems overall very odd.

### Anything else we should know about your project / environment?
The client is Java 17 based and used grpc-netty-shaded version 1.52.1. It is running inside a docker container.

**Comment by JamesNK** [comment]
Hi,

I've tried to recreate this but haven't been able to. My sample app is here - https://github.com/JamesNK/GrpcResponseHangs. I followed your description for incoming and outgoing messages, and ran [clumsy](http://jagt.github.io/clumsy/) to introduce 50ms of lag between the client and server on my computer.

gRPC calls always complete successfully.

**Comment by ThorstenReichert** [comment]
Hi, 

thanks a lot for your investigation (also did not know about clumsy, looks awesome).
After trying a few times with clumsy, I could not repro the issue on localhost either.

In the meanwhile, I modified my app to send exactly the same (protobuf) messages not over gRPC, but over an Http API. Never got the same issue there. In a few cases I observed that transmitting the response was stuck, however it recovered after ~1min (never saw this with gRPC).

Overall, after trying with clumsy, I am somewhat inclined to guess the issue is not with gRPC or ASP.NET Core, but with the network I'm working in.
Do you have any suggestions for what to try next? Otherwise thanks again and feel free to close.

**Comment by JamesNK** [comment]
No, I don't have any suggestions.
