### ISSUE TITLE
where is the google/protobuf/any.proto file located?

### ISSUE THREAD

**Issue by cysnet** [grpc/grpc-dotnet#2041]
where is the google/protobuf/any.proto file located?

**Comment by JamesNK** [comment]
It's not on disk. Protobuf has built-in support for importing that file.

If you want to see it then you can probably find it in the protobuf GitHub repository.

**Comment by cysnet** [comment]
> It's not on disk. Protobuf has built-in support for importing that file.
> 
> If you want to see it then you can probably find it in the protobuf GitHub repository.

so, the file is imported from the remoting server when compile the dotnet program?

**Comment by JamesNK** [comment]
No, it's built into protoc

**Comment by cysnet** [comment]
> No, it's built into protoc

thanks, got it
