### ISSUE TITLE
Is there a reason why interceptor's generic constraints specify only that TResponse is a class, and no new()?

### ISSUE THREAD

**Issue by voroninp** [grpc/grpc-dotnet#2043]
In some cases when `continuation` throws a very specific exception I'd like to set the status of the response and add some trailers. I don't want to rethrow an exception, but `ClientStreamingServerHandler` and `UnaryServerHandler` return `Task<TResponse>`, so I need to return an instance. If I do `return default!;` then status is overwritten to `Cancelled`.

Also, I've noticed that any status code different from `Ok` leads to exception on the client, so actual instance of `TResponse` should not matter.

I need to create a default value, but without `new()` constraint I have to use `Activator`.

Can we add this constraint to `Interceptor` interface?

**Comment by JamesNK** [comment]
> Can we add this constraint to Interceptor interface?

No, that is a breaking change. You'll need to use Activator or another mechanism to create the object.

**Comment by JamesNK** [comment]
There wouldn't be a parameterless constructor if someone overrides serialization and uses some form of immutable types as messages.

**Comment by goldenc** [comment]
What about an `IMessage` constraint, won't `TRequest` and `TResponse` always be of type `IMessage` ?

**Comment by JamesNK** [comment]
No. gRPC isn’t limited to protobuf. For example, some people use msgpack
