### ISSUE TITLE
How to correlate exception on the client and on the server?

### ISSUE THREAD

**Issue by voroninp** [grpc/grpc-dotnet#2044]
There's no `ActivityId` in `RpcException`, so when such exception is logged it's not easy to correlate it to traces of the request processing on the server.

Is there a way to retrieve some correlation value?

**Comment by cfox-dev** [comment]
Maybe one option could be to append Metadata in your RpcException.. 
Something like this:

```
var metadata = new Metadata();
metadata.Add(new Metadata.Entry("ActivityId", "MyActivity"));
return new RpcException(new Status(StatusCode.Internal, "Correlation exception"), metadata);
```

For consuming it, please refer to this example: https://learn.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/error-handling#catch-errors-in-grpc-clients

**Comment by voroninp** [comment]
@cfox-dev , yeah, but activity id of the request is to accessible when exception is caught.

Looks like I need to implement [client interceptor](https://learn.microsoft.com/en-us/aspnet/core/grpc/interceptors?view=aspnetcore-7.0#create-a-client-grpc-interceptor)

**Comment by cfox-dev** [comment]
If I got your question correctly, you can do that without interceptor. The metadata are serialized along with the RpcException so you can retrieve that when the exception is caught. Just push that value when you throw the exception at server side and then retrieve that value when you caught it at client side.

**Comment by voroninp** [comment]
@cfox-dev , Well, I put ActivityId into trailers in server interceptor. We do not throw `RpcException` ourselves, we just let handler to process regular exception.

**Comment by JamesNK** [comment]
A gRPC client on .NET 6+ supports sending trace headers to automatically correlate requests and responses.

See https://learn.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-7.0#tracing and https://jimmybogard.com/building-end-to-end-diagnostics-and-tracing-a-primer-trace-context/
