### ISSUE TITLE
Grpc error 'Request protocol 'HTTP/1.1' is not supported' in Android

### ISSUE THREAD

**Issue by gktval** [grpc/grpc-dotnet#2046]
I am receiving an error 'Request protocol 'HTTP/1.1' is not supported' when sending a request to the server. The method works in Windows 11, but in Android, the error occurs. I am using .Net 7 and Maui.

This is the specific error:
Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Request protocol 'HTTP/1.1' is not supported.")

My code to create the channel is below:

```
public GrpcChannel CreateChannel(string token)
{
   var credentials = CallCredentials.FromInterceptor((context, metadata) =>
      {
          metadata.Add("Authorization", $"Bearer {token}");
      }
      return Task.CompletedTask;
   });

   var handler = new SubdirectoryHandler(new HttpClientHandler(), "/MySubDirectory");
   var httpClient = new HttpClient(handler);
   httpClient.DefaultRequestVersion = new Version(2, 0);      

   var channel = GrpcChannel.ForAddress("https://mywebsite.com:443", new GrpcChannelOptions
     {
         Credentials = ChannelCredentials.Create(new SslCredentials(), credentials),
         HttpClient = httpClient
     });
   return channel;
}
```

I have also tried changing the HttpRequestMessage in the HttpClientHandler as described here [How to make the .net HttpClient use http 2.0?](https://stackoverflow.com/questions/32685151/how-to-make-the-net-httpclient-use-http-2-0)

```
protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
{
   request.Version = HttpVersion.Version20;
   return base.SendAsync(request, cancellationToken);
}
```

Any ideas what else I might be able to try or do to force it to not use 1.1?

**Comment by JamesNK** [comment]
Try using SocketsHttpHandler:

> var handler = new SubdirectoryHandler(new SocketsHttpHandler(), "/MySubDirectory");

**Comment by gktval** [comment]
Thanks for responding so quickly. That worked perfectly. Thank you for your help!
