### ISSUE TITLE
How set EnableDetailedErrors?

### ISSUE THREAD

**Issue by alexeygritsenko** [grpc/grpc-dotnet#2050]
Hi, I can't seem to find a way to enable detailed errors on the server. Here is my server code:
```
var cacert = File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "Certificates", "ca.crt"));
var servercert = File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "Certificates", "server.crt"));
var serverkey = File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "Certificates", "server.key"));
var keypair = new KeyCertificatePair(servercert, serverkey);
var ssl = new SslServerCredentials(new List<KeyCertificatePair>() { keypair }, cacert, false);

_server = new Server
{
	Services = { MyFileServer.BindService(new MyFileServerService())
	.Intercept(new GrpcServerInterceptor()) },
	Ports = {
	new ServerPort("0.0.0.0", 5001, ssl),
	new ServerPort("0.0.0.0", 5002, ssl)
	},
};

_server.Start();
```

**Comment by JamesNK** [comment]
You're using Grpc.Core, not Grpc.AspNetCore. EnableDetailedErrors doesn't apply to Grpc.Core.

**Comment by alexeygritsenko** [comment]
Thanks for the answer. Are there any plans to make such a feature for Grpc.Core? It seems to me that exception details are the same useful feature regardless of the platform. I use Windows Service and did not want to add unnecessary dependencies on AspNetCore

**Comment by JamesNK** [comment]
It's unlikely because Grpc.Core isn't getting new features.

Note: I don't work on Grpc.Core
