### ISSUE TITLE
Getting access to HttpContext from outside of gRPC Service method

### ISSUE THREAD

**Issue by jameswoodley** [grpc/grpc-dotnet#2053]
I am looking to create a class that can access the HttpContext in order to store the current logged in user. If this were Web Api, I'd just inject IHttpContextAccessor into that class, and access the user from there. Injecting this "LoggedInUser" class would then allow a call such as

`var email = _loggedInUser.Email` or `var isAdmin = _loggedInUser.Roles.Contains("Admin")`

I tried this approach within gRPC, but injecting IHttpContextAccessor just closes the grpc server with no error or messages. So reading it seems this is only available from within the `ServerCallContext` on the GRPC server method, this would mean I'd have to set it on every method, and pass down to handlers, and services, and anything else that may need the logged in user? Feels quite unwieldy

I'm sure I've missed something, so looking for advice as to how to get the current user (ClaimsPrincipal) outside of the gRPC server method.. i.e. somewhere I'm not given a `ServerCallContext` instance.

**Comment by JamesNK** [comment]
`IHttpContextAccessor` works. In fact, one of gRPC's features uses it: https://github.com/grpc/grpc-dotnet/blob/a456d47405c462ccfa9e1480ad7f38759f2c2127/src/Grpc.AspNetCore.Server.ClientFactory/ContextPropagationInterceptor.cs#L40

**Comment by jameswoodley** [comment]
I did think it was weird @JamesNK, thanks for confirming. Any idea why the app would just die if it's injected? I tried with all lifecycle types

**Comment by JamesNK** [comment]
No, I don't. Exiting the process without an error is strange. Perhaps try with a simple app and gradually introduce new logic until you find the point there is a problem.

**Comment by jameswoodley** [comment]
@JamesNK 

Sigh, yesterday was obviously one of those days..

I was missing `services.AddHttpContextAccessor()` ... 🤦🏻‍♂️ 

Thanks for the help though, your idea of starting simple made me go back to 1st principals and realise where I'd gone wrong
