### ISSUE TITLE
Can not build docker image net 7

### ISSUE THREAD

**Issue by barruka** [grpc/grpc-dotnet#2059]
First of all I want to apologize because I don't know if this is the project where I have to submit this issue. So, if this is not the project where you think I have to submit this issue, please point me to the right one! :)

### What version of gRPC and what language are you using?
.net 7.0.3
Google.Protobuf 3.22.0
Grpc.AspNetCore 2.51.0
Grpc.AspNetCore.Web 2.51.0
Grpc.Net.Client 2.51.0
Grpc.Tools 2.52.0-pre1

### What operating system (Linux, Windows,...) and version?
Develop on Windows 10 (the app runs ok)
Trying to create the image with 
mcr.microsoft.com/dotnet/aspnet:7.0-alpine AS base
mcr.microsoft.com/dotnet/sdk:7.0-alpine AS build

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.net sdk 7.0.200

### What did you expect to see?
Before adding the grpc packages to the project, the dockerfile works fine and creates the image, but after adding the packages and the code, the app works fine in development, but when trying to create the image it fails.
The dockerfile has:
`RUN dotnet restore "Shop.Store/Shop.Store.Infrastructure.Api/Shop.Store.Infrastructure.Api.csproj" -f --no-cache`

### What did you see instead?
#21 6.472 Build FAILED.
#21 6.472
#21 6.473 /usr/share/dotnet/sdk/7.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/google.protobuf/3.22.0/lib/net5.0/Google.Protobuf.xml' not found. Run a NuGet package restore to generate this file. [/src/Shop.Store/Shop.Store.Infrastructure.Api/Shop.Store.Infrastructure.Api.csproj]
#21 6.473 /usr/share/dotnet/sdk/7.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/grpc.aspnetcore.server/2.51.0/lib/net7.0/Grpc.AspNetCore.Server.xml' not found. Run a NuGet package restore to generate this file. [/src/Shop.Store/Shop.Store.Infrastructure.Api/Shop.Store.Infrastructure.Api.csproj]
#21 6.473 /usr/share/dotnet/sdk/7.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/grpc.aspnetcore.server.clientfactory/2.51.0/lib/net7.0/Grpc.AspNetCore.Server.ClientFactory.xml' not found. Run a NuGet package restore to generate this file. [/src/Shop.Store/Shop.Store.Infrastructure.Api/Shop.Store.Infrastructure.Api.csproj]
#21 6.473 /usr/share/dotnet/sdk/7.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/grpc.aspnetcore.web/2.51.0/lib/net7.0/Grpc.AspNetCore.Web.xml' not found. Run a NuGet package restore to generate this file. [/src/Shop.Store/Shop.Store.Infrastructure.Api/Shop.Store.Infrastructure.Api.csproj]
#21 6.473 /usr/share/dotnet/sdk/7.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/grpc.core.api/2.51.0/lib/netstandard2.1/Grpc.Core.Api.xml' not found. Run a NuGet package restore to generate this file. [/src/Shop.Store/Shop.Store.Infrastructure.Api/Shop.Store.Infrastructure.Api.csproj]
#21 6.473 /usr/share/dotnet/sdk/7.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/grpc.net.client/2.51.0/lib/net7.0/Grpc.Net.Client.xml' not found. Run a NuGet package restore to generate this file. [/src/Shop.Store/Shop.Store.Infrastructure.Api/Shop.Store.Infrastructure.Api.csproj]
#21 6.473 /usr/share/dotnet/sdk/7.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/grpc.net.clientfactory/2.51.0/lib/net7.0/Grpc.Net.ClientFactory.xml' not found. Run a NuGet package restore to generate this file. [/src/Shop.Store/Shop.Store.Infrastructure.Api/Shop.Store.Infrastructure.Api.csproj]
#21 6.473 /usr/share/dotnet/sdk/7.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/grpc.net.common/2.51.0/lib/net7.0/Grpc.Net.Common.xml' not found. Run a NuGet package restore to generate this file. [/src/Shop.Store/Shop.Store.Infrastructure.Api/Shop.Store.Infrastructure.Api.csproj]
#21 6.473 /usr/share/dotnet/sdk/7.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/microsoft.entityframeworkcore/7.0.3/lib/net6.0/Microsoft.EntityFrameworkCore.xml' not found. Run a NuGet package restore to generate this file. [/src/Shop.Store/Shop.Store.Infrastructure.Api/Shop.Store.Infrastructure.Api.csproj]
#21 6.473 /usr/share/dotnet/sdk/7.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/microsoft.entityframeworkcore.abstractions/7.0.3/lib/net6.0/Microsoft.EntityFrameworkCore.Abstractions.xml' not found. Run a NuGet package restore to generate this file. [/src/Shop.Store/Shop.Store.Infrastructure.Api/Shop.Store.Infrastructure.Api.csproj]
#21 6.473 /usr/share/dotnet/sdk/7.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/microsoft.entityframeworkcore.relational/7.0.2/lib/net6.0/Microsoft.EntityFrameworkCore.Relational.xml' not found. Run a NuGet package restore to generate this file. [/src/Shop.Store/Shop.Store.Infrastructure.Api/Shop.Store.Infrastructure.Api.csproj]
#21 6.473 /usr/share/dotnet/sdk/7.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/microsoft.extensions.caching.abstractions/7.0.0/lib/net7.0/Microsoft.Extensions.Caching.Abstractions.xml' not found. Run a NuGet package restore to generate this file. [/src/Shop.Store/Shop.Store.Infrastructure.Api/Shop.Store.Infrastructure.Api.csproj]
#21 6.473 /usr/share/dotnet/sdk/7.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/microsoft.extensions.caching.memory/7.0.0/lib/net7.0/Microsoft.Extensions.Caching.Memory.xml' not found. Run a NuGet package restore to generate this file. [/src/Shop.Store/Shop.Store.Infrastructure.Api/Shop.Store.Infrastructure.Api.csproj]
#21 6.473 /usr/share/dotnet/sdk/7.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/microsoft.extensions.configuration/2.0.0/lib/netstandard2.0/Microsoft.Extensions.Configuration.xml' not found. Run a NuGet package restore to generate this file. [/src/Shop.Store/Shop.Store.Infrastructure.Api/Shop.Store.Infrastructure.Api.csproj]
#21 6.473 /usr/share/dotnet/sdk/7.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/microsoft.extensions.configuration.abstractions/7.0.0/lib/net7.0/Microsoft.Extensions.Configuration.Abstractions.xml' not found. Run a NuGet package restore to generate this file. [/src/Shop.Store/Shop.Store.Infrastructure.Api/Shop.Store.Infrastructure.Api.csproj]
#21 6.473 /usr/share/dotnet/sdk/7.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/microsoft.extensions.configuration.binder/2.0.0/lib/netstandard2.0/Microsoft.Extensions.Configuration.Binder.xml' not found. Run a NuGet package restore to generate this file. [/src/Shop.Store/Shop.Store.Infrastructure.Api/Shop.Store.Infrastructure.Api.csproj]
#21 6.473 /usr/share/dotnet/sdk/7.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/microsoft.extensions.dependencyinjection/7.0.0/lib/net7.0/Microsoft.Extensions.DependencyInjection.xml' not found. Run a NuGet package restore to generate this file. [/src/Shop.Store/Shop.Store.Infrastructure.Api/Shop.Store.Infrastructure.Api.csproj]
#21 6.473 /usr/share/dotnet/sdk/7.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/microsoft.extensions.dependencyinjection.abstractions/7.0.0/lib/net7.0/Microsoft.Extensions.DependencyInjection.Abstractions.xml' not found. Run a NuGet package restore to generate this file. [/src/Shop.Store/Shop.Store.Infrastructure.Api/Shop.Store.Infrastructure.Api.csproj]
#21 6.473 /usr/share/dotnet/sdk/7.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/microsoft.extensions.dependencymodel/3.0.0/lib/netstandard2.0/Microsoft.Extensions.DependencyModel.xml' not found. Run a NuGet package restore to generate this file. [/src/Shop.Store/Shop.Store.Infrastructure.Api/Shop.Store.Infrastructure.Api.csproj]
#21 6.473 /usr/share/dotnet/sdk/7.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/microsoft.extensions.fileproviders.abstractions/3.1.8/lib/netcoreapp3.1/Microsoft.Extensions.FileProviders.Abstractions.xml' not found. Run a NuGet package restore to generate this file. [/src/Shop.Store/Shop.Store.Infrastructure.Api/Shop.Store.Infrastructure.Api.csproj]
#21 6.473 /usr/share/dotnet/sdk/7.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/microsoft.extensions.hosting.abstractions/3.1.8/lib/netcoreapp3.1/Microsoft.Extensions.Hosting.Abstractions.xml' not found. Run a NuGet package restore to generate this file. [/src/Shop.Store/Shop.Store.Infrastructure.Api/Shop.Store.Infrastructure.Api.csproj]
#21 6.473 /usr/share/dotnet/sdk/7.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/microsoft.extensions.http/3.0.3/lib/netcoreapp3.0/Microsoft.Extensions.Http.xml' not found. Run a NuGet package restore to generate this file. [/src/Shop.Store/Shop.Store.Infrastructure.Api/Shop.Store.Infrastructure.Api.csproj]
#21 6.473 /usr/share/dotnet/sdk/7.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/microsoft.extensions.logging/7.0.0/lib/net7.0/Microsoft.Extensions.Logging.xml' not found. Run a NuGet package restore to generate this file. [/src/Shop.Store/Shop.Store.Infrastructure.Api/Shop.Store.Infrastructure.Api.csproj]
#21 6.473 /usr/share/dotnet/sdk/7.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/microsoft.extensions.logging.abstractions/7.0.0/lib/net7.0/Microsoft.Extensions.Logging.Abstractions.xml' not found. Run a NuGet package restore to generate this file. [/src/Shop.Store/Shop.Store.Infrastructure.Api/Shop.Store.Infrastructure.Api.csproj]
#21 6.473 /usr/share/dotnet/sdk/7.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/microsoft.extensions.options/7.0.0/lib/net7.0/Microsoft.Extensions.Options.xml' not found. Run a NuGet package restore to generate this file. [/src/Shop.Store/Shop.Store.Infrastructure.Api/Shop.Store.Infrastructure.Api.csproj]
#21 6.473 /usr/share/dotnet/sdk/7.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/microsoft.extensions.options.configurationextensions/2.0.0/lib/netstandard2.0/Microsoft.Extensions.Options.ConfigurationExtensions.xml' not found. Run a NuGet package restore to generate this file. [/src/Shop.Store/Shop.Store.Infrastructure.Api/Shop.Store.Infrastructure.Api.csproj]
#21 6.473 /usr/share/dotnet/sdk/7.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/microsoft.extensions.primitives/7.0.0/lib/net7.0/Microsoft.Extensions.Primitives.xml' not found. Run a NuGet package restore to generate this file. [/src/Shop.Store/Shop.Store.Infrastructure.Api/Shop.Store.Infrastructure.Api.csproj]
#21 6.473 /usr/share/dotnet/sdk/7.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): warning NETSDK1004: Assets file '/root/.nuget/packages/microsoft.openapi/1.2.3/lib/netstandard2.0/Microsoft.OpenApi.xml' not found. Run a NuGet package restore to generate this file.

**Comment by adityamandaleeka** [comment]
Hmm... this doesn't look like it's a gRPC-specific issue (other packages are also hitting the same error).

**Comment by adityamandaleeka** [comment]
Perhaps this may be helpful: https://learn.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1004
