### ISSUE TITLE
Status(StatusCode="Internal", Detail="Failed to deserialize response message.")

### ISSUE THREAD

**Issue by khteh** [grpc/grpc-dotnet#2061]
### What version of gRPC and what language are you using?
C#
```
    <PackageReference Include="Google.Protobuf" Version="3.21.12" />
    <PackageReference Include="Grpc.Net.Client" Version="2.51.0" />
    <PackageReference Include="Grpc.Tools" Version="2.51.0">
```

### What operating system (Linux, Windows,...) and version?
Ubuntu 22.10

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

### What did you expect to see?
No error

### What did you see instead?
`Status(StatusCode="Internal", Detail="Failed to deserialize response message.")`

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc-dotnet/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by adityamandaleeka** [comment]
> If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
