### ISSUE TITLE
Exception information lost for GRPC server when running behind Citrixc ADC load balancer

### ISSUE THREAD

**Issue by leonardder** [grpc/grpc-dotnet#2062]
### What version of gRPC and what language are you using?
* Grpc.AspNetCore 2.51.0 on .NET 6 (C#)
* Citrix ADC 13.0-88.16 

### What operating system (Linux, Windows,...) and version?
GRPC Server running on Windows Server 2022 under IIS

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET SDK Version:   7.0.200                                                                                                     

### What did you do?
1. Create a server holding a service that raises an exception when a method is called, holding the message `Couldn't find relation for request`
2. Access the server from behind a Citrix ADC load balancer using the GRPC .NET Client

### What did you expect to see?
```
{StatusCode: 200, ReasonPhrase: 'OK', Version: 2.0, Headers:
{
  Server: Microsoft-IIS/10.0
  grpc-status: 5
  grpc-message: Couldn't find relation for request
  X-Powered-By: ASP.NET
  Date: Thu, 26 Jan 2023 14:32:50 GMT
  Content-Type: application/grpc
}}
```

### What did you see instead?
```{StatusCode: 200, ReasonPhrase: 'OK', Version: 2.0,
Headers:
{
  Date: Thu, 26 Jan 2023 14:22:48 GMT
  Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
  Content-Type: application/grpc
}, Trailing Headers:
{
  grpc-status: 0
}}
```

The GRPC client returns internal error "Failled to deserialize response"

### Anything else we should know about your project / environment?
At first sight, this looked like an issue with Citrixd ADC. I contacted Citrix about this case, and they reported the following:

> As per below RFC
> https://httpwg.org/specs/rfc9113.html#rfc.section.8.1
>> Trailer fields are carried in a field block that also terminates the stream. That is, trailer fields comprise a sequence starting with a HEADERS frame, followed by zero or more CONTINUATION frames, where the HEADERS frame bears an END_STREAM flag. Trailers MUST NOT include pseudo-header fields (Section 8.3). An endpoint that receives pseudo-header fields in trailers MUST treat the request or response as malformed (Section 8.1.1).
An endpoint that receives a HEADERS frame without the END_STREAM flag set after receiving the HEADERS frame that opens a request or after receiving a final (non-informational) status code MUST treat the corresponding request or response as malformed (Section 8.1.1).

> As in the RFC, during an error case (ie during trailer only) header should carry end stream flag in a frame, however in our case, after (trailer only header) HEADERS, empty DATA frame with end stream flag is sent- The flag should be there in frame 656801. This need to be fixed from the server side by sending end stream flag in(trailer only) header during error case.

**Comment by JamesNK** [comment]
I'm not sure if it is possible to have a headers-only response with ASP.NET Core + IIS, and the END_STREAM flag is on the HEADERS frame.

**Comment by JamesNK** [comment]
I've created an issue to investigate this - https://github.com/dotnet/aspnetcore/issues/47183

If changes are required to IIS in Windows then there is no chance we'll fix this. A workaround you could do is have middleware that always flushes headers before gRPC runs so that trailers are always used.

**Comment by leonardder** [comment]
Thanks for investigating this. I will certainly try the headers approach, but we might as well switch back to Kestrel.

**Comment by leonardder** [comment]
I'm actually not sure whether I'm getting the flushing the headers part correctly. Should I add middleware that calls context.Response.Body.FlushAsync() in certain situations?

**Comment by JamesNK** [comment]
An interceptor that calls [WriteResponseHeadersAsync](https://grpc.github.io/grpc/csharp/api/Grpc.Core.ServerCallContext.html#Grpc_Core_ServerCallContext_WriteResponseHeadersAsync_Grpc_Core_Metadata_) before executing the method is what I was thinking.

**Comment by leonardder** [comment]
i created the following interceptor:

```
public class WriteResponseHeadersInterceptor : Interceptor
{
    public override async Task<TResponse> UnaryServerHandler<TRequest, TResponse>(TRequest request, ServerCallContext context, UnaryServerMethod<TRequest, TResponse> continuation)
    {
        await context.WriteResponseHeadersAsync(new());
        return await base.UnaryServerHandler(request, context, continuation);
    }
}
```

Interesting enough, The GRPC Status still ends up in the headers, not in the trailers.

**Comment by JamesNK** [comment]
I tested your interceptor and the status is in the trailers for me:

![image](https://user-images.githubusercontent.com/303201/227874405-8c7d8a89-a28f-4bcb-b4a7-6630d01a1204.png)

```csharp
using Grpc.Core.Interceptors;
using Grpc.Core;
using GrpcService23.Services;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddGrpc(o => o.Interceptors.Add<WriteResponseHeadersInterceptor>());

var app = builder.Build();

// Configure the HTTP request pipeline.
app.MapGrpcService<GreeterService>();
app.MapGet("/", () => "Communication with gRPC endpoints must be made through a gRPC client. To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909");

app.Run();

public class WriteResponseHeadersInterceptor : Interceptor
{
    public override async Task<TResponse> UnaryServerHandler<TRequest, TResponse>(TRequest request, ServerCallContext context, UnaryServerMethod<TRequest, TResponse> continuation)
    {
        await context.WriteResponseHeadersAsync(new());
        return await base.UnaryServerHandler(request, context, continuation);
    }
}
```

**Comment by JamesNK** [comment]
It's a valid gRPC response. The problem is your proxy.
