### ISSUE TITLE
Custom options for http request message

### ISSUE THREAD

**Issue by careless6666** [grpc/grpc-dotnet#2064]
Now inside the library code we see a convenient way to transfer data between handlers and within the application through options

https://github.com/grpc/grpc-dotnet/blob/456098bcfeb9c796c19ea023b3ab3703181f1089/src/Grpc.Net.Client.Web/GrpcWebHandler.cs#L137

Of course, data can also be transmitted through headers, but then they will have to be cleaned before sending data, or even worse, they can leak out

Perhaps the simplest solution to this problem would be to allow registration AddHttpMessageHandler<>(), now it is not allowed

Or allow register list of ChannelOptionsActions

I try register of handler, but it is not work too

```
services.AddGrpcClient<TClient>(opt =>
opt.ChannelOptionsActions.Add(x=>
                {
                    x.HttpHandler = new CustomHttpMessageHandler();
                });

                options.ChannelOptionsActions.Add(x =>
                {
                    x.Credentials = ChannelCredentials.Insecure;
                    x.ServiceConfig = new ServiceConfig
                    {
                        LoadBalancingConfigs = { new RoundRobinConfig() }
                    };

                    x.HttpHandler = new SocketsHttpHandler()
                    );
```

Which of these is better?

**Comment by adityamandaleeka** [comment]
`AddHttpMessageHandler` can be used with the value returned from `AddGrpcClient`. That's the preferred approach.

**Comment by JamesNK** [comment]
There are examples of using AddHttpMessageHandler in tests: https://github.com/search?q=repo%3Agrpc%2Fgrpc-dotnet%20AddHttpMessageHandler&type=code

**Comment by careless6666** [comment]
I found a small nuance when the handler stops working, this is the case if you add ChannelOptionsActions

full example of test

```
[Fact]
	public async Task Test1()
	{
		var builder = WebApplication.CreateBuilder();

		builder.Services.AddGrpc();
		builder.Services.TryAddSingleton<TestHttpHandler>();
		builder.Services.TryAddSingleton<TestInterceptor>();
		builder.Services
			.AddGrpcClient<Greeter.GreeterClient>(x=>
			{
				x.Address = new Uri("http://localhost:8082");
				x.ChannelOptionsActions.Add(x =>
				{
					x.Credentials = ChannelCredentials.Insecure;
					x.ServiceConfig = new ServiceConfig
					{
						LoadBalancingConfigs = { new RoundRobinConfig() }
					};

					x.HttpHandler = new SocketsHttpHandler
					{
						EnableMultipleHttp2Connections = true,
						PooledConnectionIdleTimeout = TimeSpan.FromMinutes(1),
						PooledConnectionLifetime = TimeSpan.FromMinutes(1)
					};
				});
			})
			.AddHttpMessageHandler<TestHttpHandler>()
			.AddInterceptor<TestInterceptor>();


		builder.WebHost.ConfigureKestrel(kestrel =>
		{
			kestrel.ListenAnyIP(8082, options => options.Protocols = HttpProtocols.Http2); //grpc port
			kestrel.ListenAnyIP(5000, options => options.Protocols = HttpProtocols.Http1AndHttp2); //local http
		});
		
		var app = builder.Build();

		var client = app.Services.GetRequiredService<Greeter.GreeterClient>();
		
		app.UseRouting();
		app.UseEndpoints(s =>
		{
			s.MapGrpcService<GreetService>();
		});
		
		var appLifeTime = app.Services.GetRequiredService<IApplicationLifetime>();
		appLifeTime.ApplicationStarted.Register(async () =>
		{
			var response = await client.SayHelloFromAsync(new HelloRequestFrom() { From = "Me", Name = "MyName" });
			await app.StopAsync();
		});
		
		await app.RunAsync();
	}
```

if remove x.ChannelOptionsActions.Add(x => 
handler will be triggered, why is that?

**Comment by JamesNK** [comment]
Using ChannelOptionsActions like that overwrites `HttpHandler`, which is what is set with `AddHttpMessageHandler`.

Use [ConfigurePrimaryHttpMessageHandler](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.httpclientbuilderextensions.configureprimaryhttpmessagehandler?view=dotnet-plat-ext-8.0).

**Comment by careless6666** [comment]
Yes, that's what I need, thanks
