### ISSUE TITLE
Duplex Streaming Client's stream not delivered at the Server without Task.Run and Task.WaitAll

### ISSUE THREAD

**Issue by JinsPeter** [grpc/grpc-dotnet#2069]
I was using gRPC with Server streaming and is trying to change it to a DuplexStreaming to make use of [C# Clean Cancellation](https://github.com/grpc/grpc/issues/8277) in an effort to avoid unwanted errors logged.  
I converted to gRPC Duplex Streaming. But now I am experiencing a synchronization issue where I am **NOT** getting the second item in the request stream delivered.

 **Does Not work**
 
 ```csharp
public async Task MyDuplexStream(IAsyncStreamReader<MyRequest> requestStream, 
                                 IServerStreamWriter<MyResponse> responseStream, 
                                 ServerCallContext context)
{

     await foreach (var request in requestStream.ReadAllAsync())
    {
       // The second request in the requestStream is never delivered
        MyResponse respose = new MyResponse();
        await responseStream.WriteAsync(response);
     }
}

```
Wrapping the stream processing in a background thread solves it though.

**Works**
```csharp
public async Task MyDuplexStream(IAsyncStreamReader<MyRequest> requestStream, 
                                 IServerStreamWriter<MyResponse> responseStream, 
                                 ServerCallContext context)
{
    var taskList = new List<Task>();
    
    try
    {
        while (await requestStream.MoveNext())
        {
            var request = requestStream.Current;
            
            // Process the request asynchronously
            var task = Task.Run(async () =>
            {
                // ... process the request ...
                var response = new MyResponse();
                await responseStream.WriteAsync(response);
            });
            
            taskList.Add(task);
        }
    }
    finally
    {
        // Wait for all tasks to complete before terminating the stream
        await Task.WhenAll(taskList);
    }
}
```

Can you please explain this beahvior.
Caveat: We are using [Grpc.AspNetCore](https://www.nuget.org/packages/Grpc.AspNetCore) in a linux docker for server and Grpc.Core C#/.NET Client from windows as Grpc.Net.Client is not supported for windows fully.

**Comment by JinsPeter** [comment]
Do you mean multiple parallel call from different clients? How is the server supposed to know about that?

Also, The works example I tried is somewhat different. We are using a Channel based thread safe stream writer to write the a cached instance of the response stream. 

Now in that context, Can you please help me understand why I am needing this parallel threading?

**Comment by JamesNK** [comment]
> Do you mean multiple parallel call from different clients? How is the server supposed to know about that?

No. Multiple parallel calls to `WriteAsync` on the server aren't allowed in a streaming call.

**Comment by JinsPeter** [comment]
But that part is resolved by my ThreadSafeStreamWriter which will write one
by one.

**Comment by JinsPeter** [comment]
My bad, I am closing this question. The behavior I got was due to an await Task.Delay(-1, CancellationToken) running as part of my first received message.

@JamesNK  Thank you for the above information
