### ISSUE TITLE
gRPC-Web: How to handle 401 & 403 responses from AuthN/Z middlewares correctly?

### ISSUE THREAD

**Issue by gingters** [grpc/grpc-dotnet#2070]
Hello,

My question is: What is the correct / suggested way to handle HTTP 401 / 403 (or actually any other HTTP-response) from AuthN/Z (or any other) middleware correctly with gRPC-Web endpoints?

Background info:
I had to implement a way to secure a code-first gRPC-Web backend andd a Blazor WASM front end with cookie authentication. This would also be similar if not almost identical to an approach using gRPC-Web with BFF (Backend for frontend)-style mechanisms.

My first problem was, that the ASP.NET Core cookie authentication middleware by default issues HTTP redirects to a login page or a forbidden page. Of course a redirect as a response to a gRPC-Web call isn't going to work with the client. I worked around that by overriding the Cookie authentication events that do the redirect and instead return 401 / 403 responses, like other middlewares (i.e., JwtBearer) would do.

But then the gRPC-Web client in my Blazor WASM application threw errors as it did not expect the response to the gRPC-Web call to return with a 401/403 response. I did a lot of searching and the only way I came up with was to add a custom middleware that would translate the HTTP responses from the AuthN/AuthZ middlewares to gRPC status codes.
That also did not suffice, as the client then got an error, stating missing content-type headers. So I had to set these too, manually.

Now, when I look at my solution, I really find it ugly and I have a feeling that it can't or at least shouldn't be necessary to do that this way and that I am missing something important. So, what would be the suggested way of doing that, or is this crappy thing I came up with really a correct solution to my problem?

Thanks in advance for your time and help.

This is my full `Program.cs`, but the important part is the custom middleware between `.UseGrpcWeb` and `.UseAuthentication`:

```
using ProtoBuf.Grpc.Server;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Grpc.Core;
using Grpc.AspNetCore.Server;
using GrpcSample.Server.Grpc.Services;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(policy =>
    {
        policy
            .AllowAnyMethod()
            .AllowAnyHeader()
            .AllowCredentials()    // This is necessary to allow transfer of the cookie
            .WithOrigins("https://localhost:7214")
            .WithExposedHeaders("Grpc-Status", "Grpc-Message", "Grpc-Encoding", "Grpc-Accept-Encoding");
    });
});

builder.Services.AddCodeFirstGrpc();

builder.Services
    .AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
    .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme, options =>
    {
        // configure main cookie options
        options.Cookie.HttpOnly = true;
        options.Cookie.SecurePolicy = CookieSecurePolicy.Always;
        // We want the cookie to be sent always with all our API requests
        options.Cookie.SameSite = SameSiteMode.None;

        // Disable redirect events, as we only secure gRPC-Web and no website
        // and since we don't redirect, we need to set the correct status code
        options.Events.OnRedirectToLogin = (ctx) => { ctx.Response.StatusCode = StatusCodes.Status401Unauthorized; return Task.CompletedTask; };
        options.Events.OnRedirectToAccessDenied = (ctx) => { ctx.Response.StatusCode = StatusCodes.Status403Forbidden; return Task.CompletedTask; };
        options.Events.OnRedirectToLogout = _ => Task.CompletedTask;
        options.Events.OnRedirectToReturnUrl = _ => Task.CompletedTask;
    });

builder.Services.AddAuthorization(options =>
    {
        options.DefaultPolicy = new AuthorizationPolicyBuilder()
            .AddAuthenticationSchemes(CookieAuthenticationDefaults.AuthenticationScheme)
            .RequireAuthenticatedUser()
            .Build();
    });

var app = builder.Build();

// Configure the HTTP request pipeline.

app.UseHttpsRedirection();
app.UseCors();

app.UseRouting();

app.UseGrpcWeb(new GrpcWebOptions() { DefaultEnabled = true, });

// This Middleware translates the HTTP status codes to valid gRPC responses
app.Use(async (context, next) => {
    // let the following middlewares (especially AuthN/Z) do their jobs
    await next();

    if ((context.Response.StatusCode == StatusCodes.Status401Unauthorized
        || context.Response.StatusCode == StatusCodes.Status403Forbidden
        ) && context.GetEndpoint()?.Metadata.GetMetadata<GrpcMethodMetadata>() != null)
    {
        var grpcCode = (context.Response.StatusCode == StatusCodes.Status401Unauthorized)
            ? StatusCode.Unauthenticated
            : StatusCode.PermissionDenied;

        // for whatever reason, we need to set all of this manually:
        context.Response.ContentType = "application/grpc-web";
        context.Response.StatusCode = StatusCodes.Status200OK;
        context.Response.AppendTrailer("grpc-status", grpcCode.ToString("D"));
    }
});

app.UseAuthentication();
app.UseAuthorization();

app.MapGrpcService<SignInService>();
app.MapGrpcService<WeatherService>();
app.MapGrpcService<CounterService>();

app.Run();

```

**Comment by JamesNK** [comment]
You're using `Grpc.Net.Client` in Blazor WASM? It should convert 4xx status codes to a gRPC unauthorized status code in the client.

**Comment by gingters** [comment]
When I remove my middleware that translates the codes, I get the following:
`RpcException: Status(StatusCode="Unauthenticated", Detail="Bad gRPC response. HTTP status code: 401")`

With my middleware, it's at least not a "Bad gRPC response":
`RpcException: Status(StatusCode="Unauthenticated", Detail="")` 

So, without that code, I would still get roughly the same output, just with a misleading error message. I could live with that to make things easier.

But when I think about it more, an unauthenticated call should really never result in a "Bad gRPC response". It's a valid response, carrying the fact that the call was unauthenticated. Or, in case of the 403, that the call was forbidden. In both cases, a valid gRPC response should be returned from the server.

It's a nice add-on that the client can handle non-gRPC Web HTTP 401 and 403 responses, but the server should not send them in the first place. I think this is also important in order to be compatible with other gRPC Web clients.

**Comment by JamesNK** [comment]
All gRPC clients map HTTP status codes to gRPC status codes.

It’s working as expected.
