### ISSUE TITLE
Is it possible to have batching with streaming?

### ISSUE THREAD

**Issue by voroninp** [grpc/grpc-dotnet#2074]
We want to transfer a large amount of relatively small messages. If we use collections (repeated fields) then message payload becomes huge. If we write messages to stream one by one, we have a performance penalty.

Currently we are fixing this by having a stream of batch messages which contain a collection of items we want to transfer.
Can similar functionality be achieved with streaming without introducing additional message for batching?
I'd like to have an option to set stream's buffer size, so it gets flushed only after certain number of messages been written to it.

**Comment by JamesNK** [comment]
There is `WriteOptions.BufferHint` on `ServerCallContext` that you could set. However, I think you'd need to toggle it on and off when writing to send the next batch.

I'd have a message with a repeated field to represent the batch. It seems less error-prone and more obvious about what is going on.
