### ISSUE TITLE
Issue after update to 2.52.0

### ISSUE THREAD

**Issue by plombaer** [grpc/grpc-dotnet#2075]
Dear
Since the upgrade I'm getting the following error :
System.InvalidOperationException: 'Channel is configured with an HTTP transport doesn't support client-side load balancing or connectivity state tracking. The underlying HTTP transport must be a SocketsHttpHandler with no SocketsHttpHandler.ConnectCallback configured. The HTTP transport must be configured on the channel using GrpcChannelOptions.HttpHandler.'

My service is hosted in IIS using gRPC.Web with client load balancing.
All was working fine before the update.
Here is my client code:

```cs
            var credentials = CallCredentials.FromInterceptor((c, m) =>
            {
                m.Add("Authorization", "Bearer " + ...;
                return Task.CompletedTask;
            });
            var clientHandler = new SocketsHttpHandler();
            clientHandler.UseProxy = false;
            clientHandler.EnableMultipleHttp2Connections = false;
            clientHandler.SslOptions = new SslClientAuthenticationOptions
            {
                RemoteCertificateValidationCallback = ValidateServerCertificate,
            };
            var channel = GrpcChannel.ForAddress("dns:///...", new GrpcChannelOptions
            {
                HttpHandler = new GrpcWebHandler(new SubdirectoryHandler(clientHandler, "/...")),
                Credentials = ChannelCredentials.Create(ChannelCredentials.SecureSsl, credentials),

                //UnsafeUseInsecureChannelCallCredentials = true,
                ServiceConfig = new ServiceConfig
                {
                    LoadBalancingConfigs = { new RoundRobinConfig() }
                }
            });
```

**Comment by JamesNK** [comment]
That error should only happen if you're configuring SocketsHttpHandler.ConnectCallback, which you aren't doing in the sample in your issue.

Could you create a reproduction and put it in a GitHub repo? I'll take a look.

**Comment by plombaer** [comment]
[TestGrpcWeb.zip](https://github.com/grpc/grpc-dotnet/files/11008584/TestGrpcWeb.zip)
Here is my test project

**Comment by JamesNK** [comment]
I didn't get that error. It worked for me.

I tested with Kestrel, so I needed to modify the sample slightly not to use TLS, modify the path, and use a static load balancer instead of DNS, but that shouldn't impact the error.

![image](https://user-images.githubusercontent.com/303201/226151974-c3b4749c-d526-467c-8710-c8cb6a0afadc.png)

**Comment by plombaer** [comment]
If I give a dummy uri and comment ServiceConfig it doesn't crash anymore on GrpcChannel.ForAddress
I suppose the issue rises when there is a DNS.

**Comment by JasonSingleton** [comment]
I believe this issue is been caused by https://github.com/grpc/grpc-dotnet/commit/5a0b1eec01d24e49d9fe6d2a5ce77e20e29557fa

Even though the handler is configured to not use a proxy one is determined by  var proxy = socketsHttpHandler.Proxy ?? HttpClient.DefaultProxy;  Its ignoring the UseProxy property on the handler

This never returns false basically on my system when a load balancer is configured, I assume the same is happening for @plombaer so exiting it then sets the handler type to be Custom and then causing the error later in the code.

**Comment by JamesNK** [comment]
Yes, that would easily explain it. I think there are two options:

1. Improve the error message to say that load balancing isn't supported because there is a proxy.
2. Log a warning instead of preventing load balancing from working when there is a proxy.

**Comment by topsterde** [comment]
I also get the same error. Here is a very simple example. When will there be a solution to the error?
[GrpcInvalidOperationExceptionConstructor.zip](https://github.com/grpc/grpc-dotnet/files/11145400/GrpcInvalidOperationExceptionConstructor.zip)

**Comment by plombaer** [comment]
Hi
Just to be clear I had deactivated the proxy usage:
var clientHandler = new SocketsHttpHandler();
clientHandler.UseProxy = false;

**Comment by JamesNK** [comment]
2.53.0 will revert back to 2.51.0 behavior. Now a log message is written if a proxy is detected.

Use 2.51.0 until it's available.

**Comment by Dreamwalker666** [comment]
That does doesn't seem the same issue. This was the client ignoring proxy settings when UseProxy was false.  Which caused problems

**Comment by jbtc-dv** [comment]
Ok, thanks... I created [a new issue](https://github.com/grpc/grpc-dotnet/issues/2685)
