### ISSUE TITLE
gRPC Client Async Method Call Error

### ISSUE THREAD

**Issue by Cloud33** [grpc/grpc-dotnet#2077]
### What version of gRPC and what language are you using?
.net grpc

### What operating system (Linux, Windows,...) and version?
windows 10

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET SDK:
 Version:   7.0.202
 Commit:    6c74320bc3

 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.202\

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

I did a Hello example according to the tutorial, but there was a problem during the client call, and I was unable to successfully call the asynchronous method
code:
https://github.com/Cloud33/Hello.Grpc

### What did you expect to see?
The behavior is consistent with the synchronization method:
result:
```
GetHelloInfo Start
Greeting: Hello World!
GetHelloInfo End
GetHelloInfoAsync Start
Greeting: Hello World!
GetHelloInfoAsync End
```

### What did you see instead?
Operation:
Start Hello.Grpc.Server
Start Hello.Grpc.Client
result:
```
GetHelloInfo Start
Greeting: Hello World!
GetHelloInfo End
GetHelloInfoAsync Start
```
Unable to catch grpc error, program exited with code 0

**Comment by JamesNK** [comment]
GetHelloInfoAsync is an async void method. It needs to return Task and you need to await it.

**Comment by Cloud33** [comment]
oh my god! thank you
