### ISSUE TITLE
adding Json Transcoding causes .NET Maui gRPC client (which needs to use both HTTP/2 & HTTP/1) build to fail

### ISSUE THREAD

**Issue by exquirentibus** [grpc/grpc-dotnet#2084]
I'm having trouble adding  Json Transcoding to a gRPC .NET 7 Maui client app.  The app needs to be able to access a gRPC server that serves up normal gRPC HTTP/2 requests but also be able to call HTTP/1 REST Api created by Json Transcoding.

I created a .NET Maui app using VS2022 17.53.

I took the proto folder from: https://github.com/grpc/grpc-dotnet/tree/master/examples/Transcoder

and dropped it into the  outer level of the Maui solution.

I added the following to the Maui project:
```
  <ItemGroup>
    <Protobuf Include="..\Proto\greet.proto" Link="Protos\greet.proto" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.52.0" />
    <PackageReference Include="Microsoft.AspNetCore.Grpc.JsonTranscoding" Version="7.0.4" />
  </ItemGroup>
```

there will be two errors like:

Error    NETSDK1082    There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'iossimulator-x64'.

and if I try to build I end up with 6 total almost identical errors for the different mac and android platforms.

**Comment by JamesNK** [comment]
ASP.NET Core doesn't support iOS or Android.

**Comment by exquirentibus** [comment]
> ASP.NET Core doesn't support being hosted in iOS or Android. You can call ASP.NET Core apps from those devices, but you can't host a web app from them.

I'm Only interested in using Maui as a gRPC Client (for IOS and Android).  

I Can build a Maui gRPC client with HTTP/2 to access a 'normal' gRPC Server, but if I convert the Proto file to the format that Json Transcoding needs, I'm unable to figure a way to build so that the 'normal' gRPC Maui client can use this modified Proto file to accesss an HTTP/2 gRPC Server?

I want the IOS Maui client to be able to access Both HTTP/2 gRPC Server and Also the REST HTTP/1 gRPC Server, if that's possible?

I didn't have a problem with a Console CORE gRPC client or WPF CORE client using this modified proto file that imports the additional Google annotations.proto and http.proto?

btw - if there's a way to get HTTP/2 gRPC to work on Windows 2016 Server - I'd gladly just forget about JSON Transcoding and use HTTP/2 exclusively - but my understanding is that that even though it understands HTTP/2 somewhat gRPC won't work with HTTP/2 on 2016 Server (according to MS docs)?

Thanks!

**Comment by JamesNK** [comment]
The docs go into detail about platforms that are and aren't supported.

Grpc.AspNetCore and Microsoft.AspNetCore.Grpc.JsonTranscoding are server packages. That shouldn't be used in a client.

**Comment by exquirentibus** [comment]
So to use the JSON Transcoding modified proto file on a Maui client which packages do I need?  

I've tried various combination but I'm obviously missing something as I've not been able to successfully build after modifying the proto for the JSON Transcoding?

I'm sharing the same proto in a solution with a number of other projects so I'd like be able to use the same proto file for all .. but I may be totally missing something obvious?

**Comment by JamesNK** [comment]
You send a plain old HTTP request from the client.

**Comment by exquirentibus** [comment]
I realize that HTTP/1 is used to access a JSON Transcoding gRPC Server.

However .. I'd like my Maui IOS app to be able to access an HTTP/1 JSON Transcoding gRPC Server and Also an HTTP/2 gRPC Server (using different routines and different methods of course).

This means it would need to be able to link to the Transcoded modified proto file if I'm able to share the .. Same .. proto file among all my clients and the server in one solution .. even if the gRPC client is accessing an HTTP/2 gRPC Server.

If that's Not possible .. I'll need to make changes to the proto file .. Twice .. so I'd prefer to be able to use One proto file among the clients and the Server in the solution.

Is that possible or .. so I need to just have two different Maui and other client version that Only use HTTP/1 or .. Only .. use HTTP/2 depending on which version of the Server they are accessing?

As I'm stuck with Windows Server 2016 at the moment for my client (but will probably upgrade to 2022 or above at some point) I'd like to keep one version of each client that contained Both methods of accessing a gRPC server (which might be a JSON Transcoded gRPC server now but .. a 'normal' HTTP/2 gRPC Server later?

**Comment by JamesNK** [comment]
You can share a proto file.

**Comment by exquirentibus** [comment]
I'm actually using the proto from your wonderful example code - which paved the way for me to get JSON Transcoding working!

https://github.com/grpc/grpc-dotnet/tree/master/examples/Transcoder/Proto

**Comment by JamesNK** [comment]
I think this is resolved. Closing.
