### ISSUE TITLE
How could I add client certificate when I create the channel with SocketsHttpHandler?

### ISSUE THREAD

**Issue by ComptonAlvaro** [grpc/grpc-dotnet#2089]
I would like to require the client include the certificate to implement mTLS (mutual authentication).

I have read this documentation: https://learn.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/channel-credentials

And it explains how I could do it using HttpClientHandler. This is the code:

```
var handler = new HttpClientHandler();
handler.ClientCertificates.Add(cert);

var httpClient = new HttpClient(handler);

var callCredentials = CallCredentials.FromInterceptor(((context, metadata) =>
    {
        metadata.Add("Authorization", $"Bearer {_token}");
    }));

var channelCredentials = ChannelCredentials.Create(new SslCredentials(), callCredentials);

var channel = GrpcChannel.ForAddress("https://localhost:5001/", new GrpcChannelOptions
{
    HttpClient = httpClient,
    Credentials = channelCredentials
});

var grpc = new Portfolios.PortfoliosClient(channel);
```

However, in my case I need to use SocketsHttpHandler to create the channel, because it is needed to can use the client in a MAUI Android application. But it has not the CLientsCertificates collection to can add the certificate.

So how could add my certificate when I need to use the socket?

Thanks.

**Comment by JamesNK** [comment]
https://learn.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.ssloptions?view=net-7.0
