### ISSUE TITLE
How to setup custom channel option for grpc server?

### ISSUE THREAD

**Issue by Kiddinglife** [grpc/grpc-dotnet#2091]
document says clearly how to setup channel option for grpc client. But I need to setup channel option of groc.max-idle-connection-timeout for grpc server who is now cut off connection every 1min without activity, which is not right for steaming rpc. Pls Help. Thx.

**Comment by JamesNK** [comment]
Grpc.AspNetCore is built on ASP.NET Core. Look at the server options of whichever ASP.NET Core server you are using for timeout configuration.
