### ISSUE TITLE
We need way customise all grpc core channel option !

### ISSUE THREAD

**Issue by Kiddinglife** [grpc/grpc-dotnet#2092]
Hey, i cannot understand why the channel option grpc* are all hidden. I mean you should respect the end users’ needs. If you not understand those options, it’s fine. But why you hide all to the users? So weird. 

For example, the max idle connection timeout will cause stream remove error for steaming rpc. but I cannot set up using this library. Every option exist for some reasons for some specific cases. Pls show some respects. Thx.

**Comment by JamesNK** [comment]
`Grpc.Net.Client` is built on System.Net.Http (`SocketsHttpHandler`). `Grpc.AspNetCore` is built on ASP.NET Core. Settings are spread across the gRPC layer and the underlying HTTP layer.
