### ISSUE TITLE
Unexpected behaviour with FieldMask

### ISSUE THREAD

**Issue by PrinceEntree8** [grpc/grpc-dotnet#2097]
Hello,
I am new to gRPC and I am not sure if I am implementing the FieldMask in the correct way.

Here is my messages definitions
```protobuf
// Events messages
message Event {
  // optional string id = 1 [deprecated = true];
  reserved 1;
  optional string name = 2;
  optional string description = 3;
 // ...
  optional string locationId = 21;
}

message UpdateEventRequest {
  string id = 1;
  Event event = 2;
  google.protobuf.FieldMask updateMask = 3;
}
```

and here my csharp code

```csharp
    public override async Task<EventResponse> UpdateEvent(UpdateEventRequest request, ServerCallContext context)
    {
        // TODO: omit this check as it is a required field
        if (string.IsNullOrWhiteSpace(request.Id))
            throw new RpcException(new Status(StatusCode.InvalidArgument, "Invalid argument 'id'"));

        if (!_eventRepository.Exists(request.Id, out var evt) || evt is null)
        {
            throw new RpcException(new Status(StatusCode.NotFound, "Entity not found"));
        }
        
        var dto = evt.AdaptToDto();
    
        request.UpdateMask.Merge(request.Event, dto);

        await new EventValidator().ValidateAndThrowAsync(dto);

        evt = dto.AdaptToPoco(evt);
        var success = _eventRepository.UpdateEvent(evt);
        
        if (!success) throw new RpcException(new Status(StatusCode.NotFound, "Entity not updated."));

        return new EventResponse
        {
            Id = evt.Id,
            Event = dto
        };
    }
```

However when I try to update a field that has pascal-case  (like `locationId`) I face this wired error that occurs with some clients, when I send this request 

```
{
    "id": "fd416fa0-5794-4bdc-be9e-1feece4f7cac",
    "event": {
        "locationId": "e3362b3b-2b8d-42cd-8c63-a5d9d9d46597"
    },
    "updateMask": "locationId"
}
```
in the path `locationId` get translate to `location_id`, where the merge fails.

<img width="618" alt="image" src="https://user-images.githubusercontent.com/32601364/231830763-110ca103-5c92-48d4-a07e-3605559398ea.png">

but I send the following request
```
{
    "id": "fd416fa0-5794-4bdc-be9e-1feece4f7cac",
    "event": {
        "locationId": "e3362b3b-2b8d-42cd-8c63-a5d9d9d46597"
    },
    "updateMask": {
        "paths": [
            "locationId"
        ]
    }
}
```
the merge works but there is a warning inside the FieldMask
<img width="758" alt="image" src="https://user-images.githubusercontent.com/32601364/231834291-e6505c13-18db-434d-a38b-846782d6e3af.png">

Did I do something wrong?
Is this an expected behaviour, how can i fix?

**Comment by JamesNK** [comment]
I'm not familiar with using field mask. I think you should ask on StackOverflow. Someone there may know how to use it correctly.

**Comment by PrinceEntree8** [comment]
> I'm not familiar with using field mask. I think you should ask on StackOverflow. Someone there may know how to use it correctly.

I've made a question on StackOverflow, [here is the link](https://stackoverflow.com/questions/76013582/unexpected-behaviour-with-fieldmask-using-dotnet-core-grpc). I will update the issue once I got a reply.

**Comment by JamesNK** [comment]
https://stackoverflow.com/a/76024928/11829
