### ISSUE TITLE
Move types required for a managed gRPC HttpClient to Grpc.Core.Api

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#210]
Tracking issue for moving all the types required for the managed HttpClient powered gRPC client.

We want them in Grpc.Core.Api so that we don't need to download the large Grpc.Core package.

This is required for https://github.com/grpc/grpc-dotnet/issues/43

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/pull/18532 has been merged, https://github.com/grpc/grpc/pull/18705 is in progress.

**Comment by JunTaoLuo** [comment]
All required client types have been moved to Grpc.Core.Api. Only pending investigation is the Channel API which will be tracked separately in https://github.com/grpc/grpc-dotnet/issues/157
