### ISSUE TITLE
AsyncAuthInterceptor is not awaited....

### ISSUE THREAD

**Issue by AbstractionsAs** [grpc/grpc-dotnet#2105]
When configuring a channel with an `AsyncAuthInterceptor`, the interceptor is invoked, but it is not awaited, making the call complete before the interceptor.

The following code results in this problem.

```csharp
public MessageBusClient(ILog log, IOptionsMonitor<MessageBusClientOptions> options, IAuthenticationClient<MessageBusClient> authClient)
{
    this.log = log;
    this.options = options;
    this.authClient = authClient;

    async Task AsyncInterceptor(AuthInterceptorContext context, Metadata metadata)
    {
        var token = await authClient.GetTokenAsync();
        metadata.Add("Authorization", $"Bearer {token}");
    }

    channelOptions = new()
    {
        MaxReceiveMessageSize = MAX_RECEIVED_MESSAGE_SIZE,
        Credentials = ChannelCredentials.Create(new SslCredentials(), CallCredentials.FromInterceptor(AsyncInterceptor)),  
    };
   
}
```

**Comment by JamesNK** [comment]
That should work. Here is a unit test that verifies the auth interceptor is awaited:

https://github.com/grpc/grpc-dotnet/blob/6bf44820a2ef6af5845830728cd4b3d1a8053ed4/test/Grpc.Net.Client.Tests/CallCredentialTests.cs#L66-L93

**Comment by AbstractionsAs** [comment]
@JamesNK It should be noted that I use protobuf-net.Grpc to create the client, but this library is not involved in setting up the channel. Also, the library documentation says that authentication should not be affected.

Here's the code making the call:

```csharp
using var channel = GrpcChannel.ForAddress(options.CurrentValue.Endpoint, channelOptions);

var client = channel.CreateGrpcService<IMessageBusService>();
var request = new GetMessagesRequest {  MaxNumber = maxNumber };
var response = await client.GetMessagesAsync(request);

if (response.Result != OperationResult.OK)
  .....
```

And this is what happens when I'm stepping:


1. Breakpoint at `var response = await client.GetMessagesAsync(request)`
2. Breakpoint at `var token = await authClient.GetTokenAsync()` (in the interceptor)
3. Breakpoint at `if (response.Result != OperationResult.OK)` (the call has completed)
4. Breakpoint at  `metadata.Add("Authorization", $"Bearer {token}")` (back in the interceptor, after the call is complete...)

**Comment by JamesNK** [comment]
The code looks correct, and there is a unit test that verifies it works.

If you upload a simple repro then I could take a look to see if I could reproduce it.
