### ISSUE TITLE
Is it possible to use mutual authentication (mTLS) with gRPC and .NET with self signed certificates? How?

### ISSUE THREAD

**Issue by ComptonAlvaro** [grpc/grpc-dotnet#2112]
I would like to add a client certificate to my client application, send this certificate to the server and the server check if the client certificate is the expected certificate or not.

At first time, I am trying to create the gRPC channel in this way:

```
X509Certificate2 cert = X509Certificate2.CreateFromPem(paramStrCertificadoCliente, paramStrKeyCliente);
if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
{
    var originalCert = cert;
    cert = new X509Certificate2(cert.Export(X509ContentType.Pkcs12));
    originalCert.Dispose();
}


var handler = new HttpClientHandler();
handler.ClientCertificates.Add(cert);

var httpClient = new HttpClient(handler);


var callCredentials = CallCredentials.FromInterceptor(((context, metadata) =>
{
    metadata.Add("Authorization", $"Bearer {_tokenJwt}");
    return Task.CompletedTask;
}));

var channelCredentials = ChannelCredentials.Create(new SslCredentials(), callCredentials);

var channel = GrpcChannel.ForAddress("https://localhost:5002/", new GrpcChannelOptions
{
    HttpClient = httpClient,
    Credentials = channelCredentials
});



return channel;
```

But I get this error: "The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch, RemoteCertificateChainErrors".

Really it has sense because I have not added any certificate when I create the channel. So I try this way:

```
X509Certificate2 cert = X509Certificate2.CreateFromPem(paramStrCertificadoCliente, paramStrKeyCliente);
if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
{
    var originalCert = cert;
    cert = new X509Certificate2(cert.Export(X509ContentType.Pkcs12));
    originalCert.Dispose();
}

X509Certificate2 certCA = X509Certificate2.CreateFromPem(paramStrCA);
if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
{
    var originalCert = certCA;
    certCA = new X509Certificate2(certCA.Export(X509ContentType.Pkcs12));
    originalCert.Dispose();
}


var handler = new HttpClientHandler();
//handler.ClientCertificates.Add(certCA);
handler.ClientCertificates.Add(cert);

var httpClient = new HttpClient(handler);


var callCredentials = CallCredentials.FromInterceptor(((context, metadata) =>
{
    metadata.Add("Authorization", $"Bearer {_tokenJwt}");
    return Task.CompletedTask;
}));

KeyCertificatePair miParCertificado = new KeyCertificatePair(paramStrCertificadoCliente, paramStrKeyCliente);

var channelCredentials = ChannelCredentials.Create(new SslCredentials(paramStrCA, miParCertificado), callCredentials);

var channel = GrpcChannel.ForAddress("https://localhost:5002/", new GrpcChannelOptions
{
    HttpClient = httpClient,
    Credentials = channelCredentials
});
```

But I get this error: "SslCredentials with non-null arguments is not supported by GrpcChannel. GrpcChannel uses HttpClient to make gRPC calls and HttpClient automatically loads root certificates from the operating system certificate store. Client certificates should be configured on HttpClient. See https://aka.ms/aspnet/grpc/certauth for details."

It seems that when I create SslCredentials for gRPC, I can't use certificates, it takes them from the certificate store. But I would like to avoid to install the certificates in the certificate store, I want to distribute with the application.

I open this issue more than in ASP Core porject because the error tells about GrpcChannel.

So how could I set the client credentials when I create the channel?

Thanks.

**Comment by JamesNK** [comment]
@ComptonAlvaro I'm still not an expert when it comes to mTLS. mTLS is not configured in gRPC. It uses the underlying HTTP handler and server. Please stop asking mTLS questions here. The answer isn't going to change.
