### ISSUE TITLE
any way to get the state in GrpcChannel?

### ISSUE THREAD

**Issue by yasoob** [grpc/grpc-dotnet#2113]
Hi! This question was initially asked in 2021 over at this issue: #1275  It was told that this is available in a preview build. It has been almost 2 years since then. Is this feature available in stable now? How do I go about using it? We are upgrading from grpc.core to grpc.net and need access to Channel state.

**Comment by JamesNK** [comment]
It's available now but requires .NET 6 or later. If you're running on .NET Framework then you won't see it because the feature requires .NET 6.
