### ISSUE TITLE
Support for field visibility

### ISSUE THREAD

**Issue by poornimanayar** [grpc/grpc-dotnet#2114]
Hi,

Is there support for visibility based versioning as mentioned here? https://cloud.google.com/apis/design/versioning#visibility-based_versioning

I tried adding this to the out-of-the-box ASP.Net Core template as shown below with a copy of `visibility.proto` in my project but I cannot get it to compile

```
syntax = "proto3";

option csharp_namespace = "APIVersioning.gRPCService";

package greet;

import "google/api/visibility.proto";

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply); 
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings.
message HelloReply {
  string message = 1;
   
  string some_name = 3 [(google.api.field_visibility).restriction = "PREVIEW"];
}


```

I get an error `The type or namespace name 'Api' does not exist in the namespace 'Google' (are you missing an assembly reference?)`

Am I doing something wrong?

**Comment by JamesNK** [comment]
I'm not familiar with this feature.

You might be able to fix this by including a `<Protobuf>` element to the project file for visibility.proto.

Note that Grpc.AspNetCore.Server doesn't do anything with the visibility metadata. This looks like customization in Google's APIs.

**Comment by poornimanayar** [comment]
Yes, I got it working but yes without the server runtime handling it for me, it doesn't help :) 

Thanks for the clarification @JamesNK 

Poornima
