### ISSUE TITLE
Race condition when disposing of channels while cancelling calls.

### ISSUE THREAD

**Issue by amanda-tarafa** [grpc/grpc-dotnet#2119]
I think there might be a race condition if a channel is disposed at the same time that one of its active calls is cancelled separately. I think this happens only for server or bidi streaming calls. The original report (https://github.com/googleapis/google-cloud-dotnet/issues/10318) comes from a Google.Cloud.PubSub.V1 user who has provided a repro and logs. A couple of us on the Google side haven't been able to reproduce but I think my description below of the race conditions is accurate, and it's also supported by the user provided logs (ignoring the Google.Cloud.PubSub.V1 part of the logs.)

- [Grpc.Net.Client.GrpcChannel.Dispose](https://github.com/grpc/grpc-dotnet/blob/38738af700a3180e87054f922f953e67d9cdd82b/src/Grpc.Net.Client/GrpcChannel.cs#L741-L754) disposes of active calls **within a lock**.
https://github.com/grpc/grpc-dotnet/blob/38738af700a3180e87054f922f953e67d9cdd82b/src/Grpc.Net.Client/GrpcChannel.cs#L741-L754

- [Grpc.Net.Client.GrpcCall.Dispose](https://github.com/grpc/grpc-dotnet/blob/38738af700a3180e87054f922f953e67d9cdd82b/src/Grpc.Net.Client/Internal/GrpcCall.cs#L176-L188) basically calls [GrpcCall.Cleanup](https://github.com/grpc/grpc-dotnet/blob/38738af700a3180e87054f922f953e67d9cdd82b/src/Grpc.Net.Client/Internal/GrpcCall.cs#L196) with a status of cancel.
- GrpcCall.Cleanup then sets the call TaskCompletionSource to cancelled.
  https://github.com/grpc/grpc-dotnet/blob/38738af700a3180e87054f922f953e67d9cdd82b/src/Grpc.Net.Client/Internal/GrpcCall.cs#L211
- But, if this GrpcCall was already being cancelled elsewhere (i.e. in a different thread) setting the TaskCompletionSource to cancelled [blocks until the cancellation callbacks have completed elsewhere](https://github.com/dotnet/runtime/blob/0743c542a0aed2928d4f65653d54958b5e861d11/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenRegistration.cs#L38). Note that this **blocks holding the chanell lock**.

In the meantime the thread that first cancelled the GrpcCall has been able to:

- Execute [GrpcCall.CancelCallFromCancellationToken](https://github.com/grpc/grpc-dotnet/blob/38738af700a3180e87054f922f953e67d9cdd82b/src/Grpc.Net.Client/Internal/GrpcCall.cs#L412) which is the callback for the call cancellation token.
- CancelCallFromCancellationToken calls [CancelCall](https://github.com/grpc/grpc-dotnet/blob/38738af700a3180e87054f922f953e67d9cdd82b/src/Grpc.Net.Client/Internal/GrpcCall.cs#L420) which (same as Cleanup) sets the GrpcCall TaskCompletionSource to cancelled. The difference here is that this call doesn't block as it's being executed on the same thread (and as part of) the cancellation callback, so the GrpcCall.Task here is actually transtioned to cancelled.
- But note that a TaskCompletionSource is being used explicitly so that it's continuations are executed inmediately.
https://github.com/grpc/grpc-dotnet/blob/38738af700a3180e87054f922f953e67d9cdd82b/src/Grpc.Net.Client/Internal/GrpcCall.cs#L73-L74
- Which means that as soon as the GrpcCall.Task is transitioned to cancelled, and in the same context (thread) an OperationCancelledException is thrown and handled in GrpcCall.RunAsync because we are awaiting for the GrpcCall.Task to complete (in the case of server and bidi streaming).
  https://github.com/grpc/grpc-dotnet/blob/38738af700a3180e87054f922f953e67d9cdd82b/src/Grpc.Net.Client/Internal/GrpcCall.cs#L621
- Handling of that exception ultimately calls Cleanup
  https://github.com/grpc/grpc-dotnet/blob/38738af700a3180e87054f922f953e67d9cdd82b/src/Grpc.Net.Client/Internal/GrpcCall.cs#L639
  which in turn calls GrpcChannel.FinishActiveCall
  https://github.com/grpc/grpc-dotnet/blob/38738af700a3180e87054f922f953e67d9cdd82b/src/Grpc.Net.Client/Internal/GrpcCall.cs#L218
  which requires the channel lock that is being held by the channel disposing thread, which is waiting for this thread to finish executing the cancellation callback:
  https://github.com/grpc/grpc-dotnet/blob/38738af700a3180e87054f922f953e67d9cdd82b/src/Grpc.Net.Client/GrpcChannel.cs#L490-L501

Possible solution:

In [GrpcChannel.Dispose](https://github.com/grpc/grpc-dotnet/blob/38738af700a3180e87054f922f953e67d9cdd82b/src/Grpc.Net.Client/GrpcChannel.cs#L734), release the lock inmediately after getting the local copy of the active calls collection. This will avoid the race condition and as far as I can see will introduce no side effect.
- Note that new calls can currently be added to the channel active call collection right after the old calls have been disposed. By releasing the lock earlier we are just allowing that to possibly happen while we are disposing of the old calls. But this wouldn't affect old call disposal as we have a local copy of the active calls collection.
- The call that would otherwise be involved in the race condition will be removed from the channel active call collection twice, but that collection is a Hashset anyway which does nothing if the element being removed is not present.

**Comment by amanda-tarafa** [comment]
@JamesNK we were about to release a [patched beta](https://github.com/googleapis/google-cloud-dotnet/pull/10357) of Google.Cloud.PubSub.V1 . But if the release of this is more or less inminint, we'd probably want to wait. Do you have a rough idea on when this will be released? Thanks!

**Comment by JamesNK** [comment]
I'm going to start the 2.54.0 release process, but it will take a couple of weeks to have a preview release and then a final release.
