### ISSUE TITLE
Question: How to access grpc request message from aspnetcore AuthorizationHandler (HttpContext)

### ISSUE THREAD

**Issue by Place1** [grpc/grpc-dotnet#2124]
Hello I'm attempting to implement an aspnetcore `AuthorizationHandler<MyRequirement>` [docs](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authorization.authorizationhandler-1?view=aspnetcore-7.0) that authorizes gRPC requests but I need access to the gRPC request message object.

Is there a way to get the deserialzied (.NET) request message from the HttpContext?

It seems like aspnetcore's authorization framework is running above the gRPC world and so perhaps my use-case isn't possible? I'm trying to avoid using an Interceptor because they don't seem to integrate at all with aspnetcore authorization for [Authorize] attributes or other features like policy.

**Comment by JamesNK** [comment]
The gRPC request isn't deserialized until the middleware pipeline reaches the gRPC endpoint. I'm pretty sure authorization handler runs before then.

If you need information for authorization, then you probably should send it with the gRPC call as a HTTP header (aka gRPC request metadata)

**Comment by Place1** [comment]
Okay that's what I thought. 

The use case I'm implementing requires authorization against the request message itself. We have gRPC method options that are used to configure an authorization check statically based on properties in the message.

This was previously implemented using an Interceptor which worked well because we had access to the message and method descriptor for access to method extensions (grpc options) [using some code from the grpc reflection impl here](https://github.com/grpc/grpc-dotnet/blob/38738af700a3180e87054f922f953e67d9cdd82b/src/Grpc.AspNetCore.Server.Reflection/GrpcReflectionServiceExtensions.cs#L86).

We want to refactor this implementation to be part of aspnetcore's authorization framework as an AuthorizationHandler so that it can work alongside other authorization handlers and play nicely instead of being it's own thing inside an interceptor.

Seems like the interceptor is out only option.

**Comment by JamesNK** [comment]
Interceptors run when the gRPC endpoint is executed. That happens after authorization has run.

Data in HTTP headers is preferable, regardless of whether you're writing a RESTful or gRPC API because it's immediately available with the HTTP request.

**Comment by Place1** [comment]
> Data in HTTP headers is preferable

Headers would be preferable in general but we're using SpiceDB to authorize based on the request payload itself so that's why we're not using them.

> You could enable request buffering and manually deserialize a protobuf message earlier in the pipeline, then rewind the buffer, but there is a performance overhead.

We'd already given this a try understanding the perf impact but found that gRPC-Web encoding (I presume) caused issues and made it more complex than just de-serializing the body stream; and yeah, performance overhead isn't great either.

But thanks for the input! It's been very helpful. We'll just stick with Interceptors. Thanks for the help.
