### ISSUE TITLE
How to get C# interface from my proto services?

### ISSUE THREAD

**Issue by soroshsabz** [grpc/grpc-dotnet#2137]
ITNOA

Hi,

I follow the onion architecture, and I need interfaces for my services in service layer of all my microservices projects, I want to know, How to say this library to generate interface for all `proto services` and all implementation of services in C#, implement these interfaces?

How to use this interfaces in my C# project?

thanks

**Comment by soroshsabz** [comment]
if [Jon Skeet](https://stackoverflow.com/users/22656/jon-skeet) correct in https://stackoverflow.com/q/76283026/1539100 How to contribute this library, to generate interface in addition of class for `proto services`?

thanks

**Comment by JamesNK** [comment]
You can't generate interfaces.

The right repos for asking for code generation changes are https://github.com/protocolbuffers/protobuf and https://github.com/grpc/grpc
