### ISSUE TITLE
Grpc.Core.RpcException after upgrading to Grpc.Net.Client v2.52.0 in integration tests

### ISSUE THREAD

**Issue by rcdavid** [grpc/grpc-dotnet#2138]
### What version of gRPC and what language are you using?
Google.Protobuf 3.23.1 and C#

### What operating system (Linux, Windows,...) and version?
Edition	Windows 10 Pro
Version	22H2
Installed on	‎17.‎07.‎2020
OS build	19045.2965
Experience	Windows Feature Experience Pack 1000.19041.1000.0

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.Net6

### What did you do?
Using solution "sample004" from [https://github.com/Kralizek/unit-test-samples/tree/master]() 
1. Upgrade all nuget packages in solution EXCEPT Grpc.Net.Client (or upgrade to v2.51.0)
2. Run test GreeterShouldReturnMessageWithName() - works as expected
3. Upgrade Grpc.Net.Client to v2.52.0 (or v2.53.0)
4. Rerun test GreeterShouldReturnMessageWithName() - receive error

### What did you expect to see?
The test should be successful with latest versions of Grpc.Net.Client

### What did you see instead?
I get the following Grpc.Core.RpcException:
 
 GreeterShouldReturnMessageWithName
   Source: Tests.cs line 14
   Duration: 286 ms

  Message: 
Grpc.Core.RpcException : Status(StatusCode="Internal", Detail="Error starting gRPC call. ArgumentOutOfRangeException:  (Parameter 'count')
Actual value was 0.", DebugException="System.ArgumentOutOfRangeException:  (Parameter 'count')
Actual value was 0.")
  ----> System.ArgumentOutOfRangeException :  (Parameter 'count')
Actual value was 0.

  Stack Trace: 
Tests.GreeterShouldReturnMessageWithName() line 26
GenericAdapter`1.BlockUntilCompleted()
NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
AsyncToSyncAdapter.Await(Func`1 invoke)
TestMethodCommand.RunTestMethod(TestExecutionContext context)
TestMethodCommand.Execute(TestExecutionContext context)
<>c__DisplayClass4_0.<PerformWork>b__0()
<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
ContextUtils.DoIsolated(ContextCallback callback, Object state)
ContextUtils.DoIsolated[T](Func`1 func)
SimpleWorkItem.PerformWork()
--ArgumentOutOfRangeException
ResponseBodyReaderStream.VerifyBuffer(Byte[] buffer, Int32 offset, Int32 count)
ResponseBodyReaderStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
StreamExtensions.ReadMessageAsync[TResponse](Stream responseStream, GrpcCall call, Func`2 deserializer, String grpcEncoding, Boolean singleMessage, CancellationToken cancellationToken)
GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)

### Anything else we should know about your project / environment?
No

**Comment by JamesNK** [comment]
I think you need to update Microsoft.AspNetCore.Mvc.Testing to [6.0.16](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Testing/6.0.16)

This is related to zero-byte reads which were supported in 6.0.11 and later: https://github.com/dotnet/aspnetcore/issues/41692

**Comment by rcdavid** [comment]
Indeed, this resolves the problem. Thanks for the prompt response!
