### ISSUE TITLE
Feature set of .NET Core gRPC client

### ISSUE THREAD

**Issue by ronnylt** [grpc/grpc-dotnet#214]
According to the README:
> We plan to provide a managed .NET Core client as well (possibly with limited feature set at first)

Can you please provide more details about the feature set  of the client?

**Comment by JamesNK** [comment]
Hi

The client is now available in preview 6 - https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-6/

Two missing features: client compression of gRPC messages (compression of the overall HTTP/2 request is supported) and `Channel`. Client compression will come in the future, and we need to investigate what is required to support `Channel`. No timeline to share at the moment.

Let me know if you have any other questions.
