### ISSUE TITLE
How to share the generated types from a proto file ?

### ISSUE THREAD

**Issue by plombaer** [grpc/grpc-dotnet#2143]
Hi
I've a BrokenBusinessRule proto file who's generated type should be reused by multiple solutions.
```
message BrokenBusinessRule
{
  string parameter = 1;
  string code = 2;
  string message = 3;
}
```
Ideally the user of BrokenBusinessRule should reference (nuget) the assembly containing the type and use it in his own proto file.
I don't want to add BrokenBusinessRule.proto to each project. Only one BrokenBusinessRule class should exist.
It should work like Google.Protobuf works with Google.Protobuf.WellKnownTypes

Do you have guidelines or an example ?
Thanks in advance

**Comment by JamesNK** [comment]
You can share a NuGet package with the compiled messages in it.

**Comment by plombaer** [comment]
Sorry to reopen this one but I'd more details.
In case the compiled type and the proto are distributed. Will each consumer project generate its own class of BrokenBusinessRule ?
