### ISSUE TITLE
How to export the TLS master key of gRPC for WireShark

### ISSUE THREAD

**Issue by hannadeng** [grpc/grpc-dotnet#2144]
### Is your feature request related to a problem? 
According to [WireShark Wiki](https://wiki.wireshark.org/How-to-Export-TLS-Master-keys-of-gRPC) , currently C#/dotnet does not support TLS session secret key from either client or server side, so we are not able to analyze gRPC traffic encrypted in TLS using Wireshark. 

### Describe the solution you'd like
Is there any plan to support such feature of exporting the TLS Master key, so that we can analyze the HTTPS gRPC traffic using WireShark?

**Comment by JamesNK** [comment]
That change would have to happen in HttpClient. grpc-dotnet uses it to send HTTP requests.

You could ask on https://github.com/dotnet/runtime

**Comment by JamesNK** [comment]
https://github.com/dotnet/runtime/issues/37915

**Comment by hannadeng** [comment]
> That change would have to happen in HttpClient. grpc-dotnet uses it to send HTTP requests.
> 
> You could ask on https://github.com/dotnet/runtime

Thank you @JamesNK for the advice. Will check further on https://github.com/dotnet/runtime/issues/37915.

**Comment by JamesNK** [comment]
Thanks. Feel free to add a comment about why this is important to you. The more feedback on the issue, the more likely it happens.

**Comment by wfurt** [comment]
if anything we should show how to hook https://github.com/wfurt/PcapStream  to Kestrel @JamesNK. It would give people ability to decode and debug HTTP/2 & gRPC. Logging master key  is just one way and it will not work on macOS and Windows because we do not have access to it.
