### ISSUE TITLE
Document or sample of running gRPC in a non-ASP.NET Core app

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#2147]
FrameworkReference can be used to access ASP.NET Core functionality in non-ASP.NET Core apps (i.e. projects that don't use the `Microsoft.NET.Sdk.Web` SDK)

See https://learn.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-7.0&tabs=visual-studio#use-the-aspnet-core-shared-framework

Document on https://learn.microsoft.com/en-us/aspnet/core/grpc/migration?view=aspnetcore-7.0&viewFallbackFrom=aspnetcore-7.0%5C

Maybe add a sample.

**Comment by Jeevananthan-23** [comment]
Hi @JamesNK, I need to understand that non-ASP.NET CORE user can use Grpc.Core (http2c) which is currently not supported by grpcdotnet  because ASP.NET CORE is the only focus. But it could be great that grpcdotnet supports Kestrel/Dotnetty which that can be usefully by `Microsoft.NET.Sdk.Web` SDK.

**Comment by elbrandt** [comment]
Was a sample created for this?  I just posted a question that would benefit from this kind of sample.
see: https://learn.microsoft.com/en-us/answers/questions/2120880/example-of-a-c-standalone-exe-that-hosts-a-grpc-se
Thanks!
