### ISSUE TITLE
Questions about Grpc.AspNetCore.Server.Reflection

### ISSUE THREAD

**Issue by itbencn** [grpc/grpc-dotnet#2149]
When I use reflection to provide GRPC interface documentation
When encountering the same message name in different packages in the proto file
The project cannot be compiled, prompting xxx to repeatedly implement

I don't know if this is a bug or a normal phenomenon

**Comment by JamesNK** [comment]
I don't understand. Could you create a reproduction of the problem and add it to a github repo? I will take a look at it.

**Comment by JamesNK** [comment]
csharp_namespace is the same in both. Use different name spaces.
