### ISSUE TITLE
Add built-in proto files that support gRPC/REST

### ISSUE THREAD

**Issue by itbencn** [grpc/grpc-dotnet#2150]
### Is your feature request related to a problem? Please describe.
In NET7, the GRPC server can support both GRPC and `JSON Web API` requests based on `Microsoft.AspNetCore.Grpc.Swagger` packets
But it is necessary to
```
import "google/api/annotations.proto";
import "http.proto";
```
in each proto file
These two files are not built-in, which makes it very troublesome to connect them in the development environment

### Describe the solution you'd like
Build the aforementioned proto files into the protobuf project, just like `google/protobuf/descriptor.proto`

### Additional context
[annotations.proto](https://github.com/dotnet/aspnetcore/blob/main/src/Grpc/JsonTranscoding/test/testassets/Sandbox/google/api/annotations.proto)
[http.proto](https://github.com/dotnet/aspnetcore/blob/8b601c3a73ba66de4e6ca35530b5d32a48c76c5b/src/Grpc/JsonTranscoding/test/testassets/Sandbox/google/api/http.proto)
https://learn.microsoft.com/zh-cn/aspnet/core/grpc/json-transcoding?view=aspnetcore-7.0

<img width="795" alt="Snipaste_2023-06-03_00-22-50" src="https://github.com/protocolbuffers/protobuf/assets/42700064/09237583-afa6-48b1-ba42-96e4abce3ede">

https://github.com/dotnet/aspnetcore/issues/48589
https://github.com/protocolbuffers/protobuf/issues/12968

**Comment by JamesNK** [comment]
Discuss at https://github.com/dotnet/aspnetcore/issues/48589
