### ISSUE TITLE
Win 2012 server: Https connection to grpc service fails in TLS handshake. Same code works on win 2016 onwards machine.

### ISSUE THREAD

**Issue by shivkumarghatbale** [grpc/grpc-dotnet#2153]
I've grpc client & server running on the same machine. (client uses Grpc.Net.Client 2.51.0 package)
Server uses Grpc.AspNetCore 2.40 and protobuf-net.grpc.aspnetcore 1.0.179 package.

TLS handshake is failing on win 2012 machine but same code works on win 201 machine.

Grpc service has below error:

dbug: Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware[1]
      Failed to authenticate HTTPS connection.
      System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
       ---> System.ComponentModel.Win32Exception (0x80090367): No common application protocol exists between the client and the server. Application protocol negotiation failed.
         --- End of inner exception stack trace ---
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
         at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context)

Grpc client has below error:

Unhandled exception. Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: The SSL connection could not be established, see inner exception. AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'ProtocolVersion'. Win32Exception: The message received was unexpected or badly formatted.", DebugException="System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'ProtocolVersion'.

PS: grpc server has following info at the time of start up 

 HTTP/2 over TLS is not supported on Windows versions older than Windows 10 and Windows Server 2016 due to incompatible ciphers or missing ALPN support. Falling back to HTTP/1.1 instead.

@mgravell

**Comment by shivkumarghatbale** [comment]
@mgravell can you please check this?

**Comment by mgravell** [comment]
The message sort of says everything I could possibly say - it is a TLS incompatibility issue due to an old OS that lacks support for a required feature, telling you the minimum required server version. Presumably you want TLS, so... I'm not sure what I can beyond "consider updating the server OS"...

**Comment by JamesNK** [comment]
Kestrel requires Windows 10 or Windows Server 2016 or later. It says that both in the error message and in the docs: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/http2?view=aspnetcore-7.0
