### ISSUE TITLE
Where's the magic?

### ISSUE THREAD

**Issue by voroninp** [grpc/grpc-dotnet#2157]
I wanted to compare the performance of Grpc-Core (C-wrapper) (against .net 4.6.2 and .net 7.0) and Grpc.Client.Net (against .net 7.0)  libraries.

The benchmark is reading 500Mb of byte chunks (2Mb each) from locally running server. (No caching.)

I've discovered a very weird behavior of perf tests:

```
BenchmarkRunner.Run<Modern>();
Thread.Sleep(TimeSpan.FromSeconds(10));
BenchmarkRunner.Run<Legacy>();
```
If I wait slightly longer between benchmarks, `Grpc-Core` version (`Legacy`) works ~4x times slower. However, if the wait interval is small enough the performance of both libraries is more or less the same.

It looks like code from `Grpc.Client.Net` somehow affects http2 pipeline, so subsequent connections work fast. But that "switch" is reset after no connection is made.

If I change the order of benchmarks, `Grpc-Core` is always slower be it 4.6.2 or .net 7

@JamesNK , do you have any guess what it can be?

```CSharp
namespace ClientsBenchmarking
{
    [SimpleJob(RuntimeMoniker.Net70)]
    public class Modern
    {
#if NET7_0_OR_GREATER
        [Benchmark]
        public async Task FetchData()
        {
            using var channel = GrpcChannel.ForAddress("http://localhost:5068");
            var client = new BytesSender.BytesSenderClient(channel);
            var call = client.GetBytes(new Empty());

            while (await call.ResponseStream.MoveNext())
            {
            }
        }
#endif
    }

    [SimpleJob(RuntimeMoniker.Net462)]
    [SimpleJob(RuntimeMoniker.Net70)]
    public class Legacy
    {
        [Benchmark]
        public async Task FetchData()
        {
            var channel = new Channel("localhost:5068", ChannelCredentials.Insecure);
            var client = new BytesSender.BytesSenderClient(channel);
            var call = client.GetBytes(new Empty());

            while (await call.ResponseStream.MoveNext())
            {
            }
        }
    }
}
```

**Comment by JamesNK** [comment]
I don't know the internals for Grpc.Core. I can't comment why it is faster or slower in certain situations.
