### ISSUE TITLE
grpc message is not received by postman

### ISSUE THREAD

**Issue by khteh** [grpc/grpc-dotnet#2160]
```
syntax = "proto3";
option csharp_namespace = "Web.Api.Ping";
package Ping;
import "google/protobuf/empty.proto";
service SvcPing {
  rpc Ping (google.protobuf.Empty) returns (Pong);
}

message Pong {
  string message = 1;
}
```
```
public class PingService : SvcPing.SvcPingBase
{
    private readonly ILogger<PingService> _logger;
    public PingService(ILogger<PingService> logger) => _logger = logger;
    public override Task<Pong> Ping(Empty request, ServerCallContext context)
    {
        return Task.FromResult(new Pong
        {
            Message = "Hello!"
        });
    }
}
```
The message is NOT received by postman. What is seen in postman is only "Call completed".

### What version of gRPC and what language are you using?
2.53.0, C#

### What operating system (Linux, Windows,...) and version?
Ubuntu 23.04

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
```
.NET SDK:
 Version:   7.0.107
 Commit:    bf72c06963

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  23.04
 OS Platform: Linux
 RID:         ubuntu.23.04-x64
 Base Path:   /usr/lib/dotnet/sdk/7.0.107/

Host:
  Version:      7.0.7
  Architecture: x64
  Commit:       5b20af47d9

.NET SDKs installed:
  7.0.107 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.7 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.7 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/lib/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

### What did you expect to see?
```
{
    "Message": "Hello!"
}
```
on postman.

### What did you see instead?
"Call completed"

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc-dotnet/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by JamesNK** [comment]
Instructions for testing with postman are here - https://learn.microsoft.com/en-us/aspnet/core/grpc/test-tools

It is hard to know the cause based on the provided information. Please upload a repro of the issue to a GH repo and the steps you took to call it with postman.

**Comment by khteh** [comment]
https://github.com/khteh/AspNetCoreWebApi

**Comment by JamesNK** [comment]
I don't know why. You should ask Postman folks.

**Comment by JamesNK** [comment]
It works if `app.UseHttpLogging();` is removed.

**Comment by khteh** [comment]
Why does this cause an issue?

**Comment by JamesNK** [comment]
I'm guessing logging the response breaks it.

Please create an issue on https://github.com/dotnet/aspnetcore to say that HTTP logging + response body logging breaks gRPC.
