### ISSUE TITLE
Why is DebugException null on the client side?

### ISSUE THREAD

**Issue by bartosz-jarmuz** [grpc/grpc-dotnet#2163]
Hello,
I am using Grpc.AspNetCore v2.53.0 on a .NET core 6 project.

On the server side, I have an exception interceptor, which I want to use to set proper status code on the RpcException, based on the type of the business exception that happened.

I also want to preserve the stack trace and original exception details, so I wanted to include the original error in the DebugException property, like that:

```
catch (Exception ex)
        {
           //do stuff to get the proper status code
            throw new RpcException(new Status(properStatusCode, ex.Message, ex));
        }
```

Unfortunately, when the RpcException is caught on the client side, the Status.DebugException is always null...
All the other properties that I set (such as message, code) are preserved properly.
Am I doing something wrong?

Cheers

**Comment by JamesNK** [comment]
It's null because the exception isn't serialized on the server and deserialized on the client. Just the status code and message is sent from the server to the client.

You're not doing anything wrong. The debug exception is just for the environment it is thrown on.
