### ISSUE TITLE
M1 and M2 Processor Support for Mac

### ISSUE THREAD

**Issue by youngpe69** [grpc/grpc-dotnet#2168]
Apologies if this has been raised before. I am unable to use grpc-dotnet on an M2 based Mac using the dotnet template. It appears that grpc.tools does not have the specific processor support and the build attempts to use the x86 version of protoc. I’ve read that there are some CI build issues in adding support to the NuGet package? I’m just wondering if there is a workaround or if there are plans to enable in the near future? Thanks.

**Comment by JamesNK** [comment]
Grpc.Tools is maintained at https://github.com/grpc/grpc. Can you please create an issue there.

**Comment by youngpe69** [comment]
So Grpc.Tools does have support for M1 and M2 based out of that repo. Here's the difference, if I install using the brew package manager then I get a version of protoc that runs on M2. Now, if I create a Grpc service using dotnet new grpc and run that version of protoc on the example greet.proto the cs file that is created is not compatible with the container classes which leads me to believe that that protoc is targeting the old core c# version and not the later dotnet version. The NuGet Packages grpc.tools/2.5.4 definitely don't have support for M1/M2. So I'm not sure where the issue actually is?

**Comment by JamesNK** [comment]
I don't know. Please ask questions at https://github.com/grpc/grpc
