### ISSUE TITLE
Can I distinguish intended cancellation or cancellation because of timeout?

### ISSUE THREAD

**Issue by voroninp** [grpc/grpc-dotnet#2169]
I'd like to log `OperationCanceledException` in case of timeouts, but ignore exceptions which are caused by explicit cancelation from the client. 

Is there an option for this or is it seen just as a cancellation on the server side in both cases?

**Comment by JamesNK** [comment]
No.

gRPC writes what it knows (i.e. was the deadline exceeded on the server) to logging but isn't necessarily accurate.
