### ISSUE TITLE
Is the API documentation published somewhere?

### ISSUE THREAD

**Issue by leifurhauks** [grpc/grpc-dotnet#2172]
I'm having trouble finding the API docs for grpc-dotnet. I see that there are documentation comments, but are the API docs published somewhere to be more easily browsed and consulted? If not, is there a tool I should be using locally to browse the API docs?

I've found the overviews and tutorials on [Microsoft Learn](https://learn.microsoft.com/en-ca/aspnet/core/grpc/), and I see that there's an API reference for the legacy package [on grpc.io](https://grpc.io/docs/languages/csharp/).

**Comment by JamesNK** [comment]
Here: https://grpc.github.io/grpc/csharp-dotnet/api/Grpc.Core.html
