### ISSUE TITLE
Remove .NET Core 3 and .NET 5 targets

### ISSUE THREAD

**Issue by Varorbc** [grpc/grpc-dotnet#2180]
Why are unsupported target frameworks still supported? For example, netcoreapp3.0 and net5.0

**Comment by JamesNK** [comment]
Hasn't been a reason to yet. Might remove them when .NET 8 target is added.

**Comment by JamesNK** [comment]
Move to ActivitySource when old targets are dropped - https://github.com/open-telemetry/opentelemetry-dotnet/pull/4695#discussion_r1276720269

Add force yield in RetryCall and HedgeCall of GrpcCall.CallTask in .NET 8.

**Comment by JamesNK** [comment]
.NET standard 2.0 is important. Maybe for the others.
