### ISSUE TITLE
why not allowed  "GrpcChannel.forAddress("127.0.0.1:80")"

### ISSUE THREAD

**Issue by fengyeall111** [grpc/grpc-dotnet#2182]
I have investigated grpc in several languages: c++, go, php, js. When creating Channel, they use `grpc.dial("127.0.0.1:80")`, not `grpc.dial("http://127.0.0.1:80")`. Why dotnet-grpc do this? I can not understand this.Is Are there some more considerations about this?  how about add this support?

**Comment by luchunminglu** [comment]
use GrpcChannel.forAddress("http://127.0.0.1:80") or GrpcChannel.forAddress("https://127.0.0.1:80")  if ssl is enabled

**Comment by fengyeall111** [comment]
> use GrpcChannel.forAddress("http://127.0.0.1:80") or GrpcChannel.forAddress("https://127.0.0.1:80") if ssl is enabled

f that's the purpose, why not  just take `https` as the default value.In other langage,this section is passed by cerditial options

**Comment by JamesNK** [comment]
http:// and https:// prefixes were used to make it consistent with HttpClient, and allow people to configure the address and credentials with one string.

No plans to change.

**Comment by fengyeall111** [comment]
> http:// and https:// prefixes were used to make it consistent with HttpClient, and allow people to configure the address and credentials with one string.
> 
> No plans to change.

To make it consistent with HttpClient，The default address can automatically add the http or https prefix， Depending on the authentication options, decide whether it is http or https.
Consider the case:
using .net to interact with other languages, when you get the domain,  .net need address "http://127.0.0.1:80" to dial, however,
other language use "127.0.0.1:80" to dial.
```
// .net
var channel = GrpcChannel.ForAddress("http://127.0.0.1:80")
// go
var conn = grpc.dial("127.0.0.1:80")
// ... other language
```
This is ok if the project uses only c#. However, in the case of cross-language, the configured domain addresses need to be compatible.

**Comment by JamesNK** [comment]
It doesn't need to be consistent. This is fine:
```
var address = Environment.Variables["Server"]; // 127.0.0.1:80

// .net
var channel = GrpcChannel.ForAddress("http://" + address)
// go
var conn = grpc.dial(address)
// ... other language
```

**Comment by mgravell** [comment]
I propose we close this as "as-designed"; in particular, in .NET the `Uri` parsing means that `"localhost:8080"` parses as a valid uri, but for scheme `localhost`, path `8080`; at the moment (as implemented), we have flexibility to (at least hypothetically) support a range of schemas without ambiguity, so: "leave it alone". The current exception isn't *perfect*, but it is pretty clear what has happened:

``` c#
Unhandled exception. System.InvalidOperationException: No address resolver configured for the scheme 'localhost'.
```
