### ISSUE TITLE
Update implementation_comparison.md

### ISSUE THREAD

**Issue by Falco20019** [grpc/grpc-dotnet#2188]
Could you please consider updating https://github.com/grpc/grpc-dotnet/blob/master/doc/implementation_comparison.md since it's over 2 years old and some stuff has happened. We did some checking ourselves but it would be great to have an up2date list now that everyone needs to change. Would help with knowing what fields might break support and need workarounds when migrating.

/CC @jtattermusch @JamesNK

**Comment by Falco20019** [comment]
Friendly ping since it's close to a month without reaction yet.

**Comment by JamesNK** [comment]
PR: https://github.com/grpc/grpc-dotnet/pull/2240

Comment on the PR if there are changes you've seen that aren't mentioned.
