### ISSUE TITLE
Client certificate tutorial

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#219]
A tutorial showing the client using a client certificate and the server correctly validating it.

Tutorial should use ASP.NET Core's upcoming client cert validation middleware. See https://github.com/aspnet/AspNetCore/issues/4663

**Comment by andradf** [comment]
Will we be able to use a X509Certificate2 with a non-exportable private key for client authentication with this version of grpc? This is a giant roadblock for us with the current grpc native implementation.

**Comment by JamesNK** [comment]
I am not an expert when it comes to certs, so I'm not sure.

What I can tell you is the .NET server side and client side gRPC auth support will be similar to what is possible now with HttpClient + Kestrel. If you can do it today with HttpClient and ASP.NET Core MVC then you will be able to do it with managed gRPC client and gRPC ASP.NET Core.

**Comment by JamesNK** [comment]
I have added a example of sending a client certificate with gRPC calls and using them on the server. It is available here - https://github.com/grpc/grpc-dotnet/pull/306

This uses the new gRPC client that will be available in preview 6 very soon.
