### ISSUE TITLE
gRPC Failure after upgrading to .net 8 p6

### ISSUE THREAD

**Issue by e012345678** [grpc/grpc-dotnet#2191]
Hi,

After upgrading to .net 8 p6 our app fails on some devices showing this error:

`crit:
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer (100) 
Unhandled Exception rendering component: Typeinitialization_Type, Grpc.Net.Client.Internal.GrpcFrotocolConstants System.TypeInitializationException: Typeinitialization_Type, grpc.net.client.internal.GrpcProtocolconstants system.FormatException: net_http_headers_invalid_value, application/grpc Exception_EndOfInnerExceptionstack at Microsoft.Extensions.Dependencyinjection.ServiceLookup.CallSiteVisitor'2 Microsoft.Extensions.Dependencyinjection.ServiceLookup.RuntimeResolver Context, Microsoft.Extensions.Dependencyznjection, version=8.0.0.0, Culture-neutral, PublickeyToken=adb9793829ddae60],[System.Object, System.Private.corelib, version:8.0.0.0" culture-neutral, PublickeyToken=adb9793829ddae60].VisitCaliSiteMain(ServiceCaliSite, RuntimeResolverContext) at Microsort.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeRe solver.VisitRootCache(ServiceCaliSite, RuntimeResolverContext) at Microsort.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor'2 ((Microsort.Extensions.DependencyInjection.ServiceLookup.RuntimeResolver Context, Microsort.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, system.Private.corelib, Version-8.0.0.0, Culture=neutral, PublickeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument) 
`

Any idea what the problem is? Thanks a lot for the help!

**Comment by mgravell** [comment]
This *looks* like a `TypeInitializationException` when touching `GrpcProtocolConstants`, noting that the type initializer for that touches at least `HttpProtocol` and `HeaderNames`; both of those *look* pretty simple, and spinning up a local gRPC instance: it looks to work without issue. Any specific steps I might be able to use to try to repro this?

**Comment by Light407** [comment]
Was this issue ever resolved? Having the same issue @mgravell @e012345678

**Comment by JamesNK** [comment]
I don't think it is a bug in grpc-dotnet. The issue might be a bug in Blazor or .NET WebAssembly.
