### ISSUE TITLE
Update docs on .NET Framework support to match reality

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc-dotnet#2197]
https://learn.microsoft.com/en-us/aspnet/core/grpc/supported-platforms?view=aspnetcore-7.0#net-grpc-client-requirements

The doc currently mentions that Grpc.Net.Client over WinHttpHandler requires Win 11+ and doesn't say anything about Windows Server 20xx (which could be interpreted by many that Win Server 2022 has the same degree of support as Win 11).

According to my recent tests:
- Grpc.Net.Client on .NET Framework (using WinHttpHandler) will work fully (including bidi and client streaming) on Win 11
- Grpc.Net.Client on .NET Framework (using WinHttpHandler) will work partially on Win 2022 Server (bidi and client streaming call won't work, unary and server streaming will be fine).

Also the overview table mentions .NET Framework 4.6.1, for which support has already ended in 2022. Should we replace the row with ".NET Framework 4.6.2"?

**Comment by JamesNK** [comment]
@jtattermusch https://github.com/dotnet/AspNetCore.Docs/pull/30033
