### ISSUE TITLE
Server-side memory leaks

### ISSUE THREAD

**Issue by zeke202207** [grpc/grpc-dotnet#2203]
## What version of gRPC and what language are you using?

 - dotnet version 6

 - Grpc packages:
    > Google.Protobuf ==> Version="3.23.1" <br/>
    > Grpc.AspNetCore.Server.ClientFactory ==> Version="2.55.0" <br/>
    > Grpc.Net.Client ==> Version="2.55.0" <br/>
    > Grpc.Tools ==> Version="2.55.1" <br/>

## What operating system (Linux, Windows,...) and version?

Windows 10 [version 10.0.19045.3208]

## Scenario

Following the example from the official website, a simple demo was written. I found that grpc-service memory kept going up and not down, even when I closed the calling client, the memory still did not go down

> server code
```
    public static void Main(string[] args)
    {
        var builder = WebApplication.CreateBuilder(args);

        builder.WebHost.ConfigureKestrel(options =>
        {
            options.ListenAnyIP(4999, listenOptions => listenOptions.Protocols = HttpProtocols.Http2);
        });

        builder.Services.AddGrpc();

        var app = builder.Build();

        app.MapGrpcService<GreeterService>();
        
        app.MapGet("/", () => "Communication with gRPC endpoints must be made through a gRPC client. ");

        app.Run();
    }

    public class GreeterService : Greeter.GreeterBase
    {
        public GreeterService()
        {
        }

        public override Task<HelloReply> SayHello(HelloRequest request, ServerCallContext context)
        {
            Console.WriteLine($"Starting call. Request: {request}");
            return Task.FromResult(new HelloReply
            {
                Message = "Hello " + request.Name
            });
        }
    }
```

> client code 
 ```
    static void Main(string[] args)
    {
        using var channel = GrpcChannel.ForAddress("http://127.0.0.1:4999");
        var client = new Greeter.GreeterClient(channel);

        //Press Enter and call grpc service 100 times
        while (string.IsNullOrWhiteSpace(Console.ReadLine()))
        {
            for(int i = 0; i < 100; i++)
            {
                var reponse = client.SayHello(new HelloRequest() { Name =$"zeke-{i}" });
            }
        }

        Console.WriteLine("bye!");
        Console.ReadLine();
    }
 ```

 > protos
 ```
    syntax = "proto3";

    option csharp_namespace = "GrpcService1";

    package greet;

    // The greeting service definition.
    service Greeter {
    // Sends a greeting
    rpc SayHello (HelloRequest) returns (HelloReply);
    }

    // The request message containing the user's name.
    message HelloRequest {
    string name = 1;
    }

    // The response message containing the greetings.
    message HelloReply {
    string message = 1;
    }

 ```

  - After the service is started, the memory is monitored as follows

    | name      | memory |
    | --------- | ------ |
    | GrpcService1.exe      | 44,568 k       |

  - The client calls 500 times for the first time, the memory check is as follows

    | name      | memory |
    | --------- | ------ |
    | GrpcService1.exe      | 49,188 k       |

  - The client calls 500 times for the second time, the memory is checked as follows

    | name      | memory |
    | --------- | ------ |
    | GrpcService1.exe      | 49,316 k       |

  - After repeating the previous step N times, close the client and check for memory as follows

    | name      | memory |
    | --------- | ------ |
    | GrpcService1.exe      | 55,840 k       |   

## As you can see, the memory keeps growing and is not reclaimed

I want to be consulted. Is there a problem with my usage? or Is there a memory leak in grpc?.<br/>
Look forward to your reply,Thanks for helping!

**Comment by luchunminglu** [comment]
May be just console, it display more lines, use more memory.

**Comment by zeke202207** [comment]
Thanks for your  reply @luchunminglu <br/>
> May be just console, it display more lines, use more memory.


 I don't understand a little, even so, I have been calling the interface for a long time, and the server memory still only grows, not recycling, is this normal? Thank you

**Comment by zeke202207** [comment]
> don't understand a little, even so, I have been calling the interface for a long time, and the server memory still only grows, not recycling, is this normal? Thank you

I don't understand what you mean. Even so, when I call the service interface for a long time, I find that the memory is still growing, and there is no decline in reclaim. Is this a normal phenomenon? Thank you and look forward to your reply @luchunminglu

**Comment by zeke202207** [comment]
> May be just console, it display more lines, use more memory.

I don't understand what you mean. Even so, when I call the service interface for a long time, I find that the memory is still growing, and there is no decline in reclaim. Is this a normal phenomenon? Thank you and look forward to your reply @luchunminglu

**Comment by zeke202207** [comment]
I did a test today, the early memory growth rate is very large, after running for a period of time, the memory growth rate is reduced, but the memory is still growing, not always stable or decline.

**Comment by zeke202207** [comment]
Thank you so much @gfoidl
