### ISSUE TITLE
GrpcChannelOptions retry options are duplicated

### ISSUE THREAD

**Issue by setood** [grpc/grpc-dotnet#2212]
please help me figure out what the parameters with the value 5 will be used for and what with the value 6
```csharp
channel = GrpcChannel.ForAddress(node, new GrpcChannelOptions
{
    ServiceConfig = new ServiceConfig
    {
        MethodConfigs =
        {
            new MethodConfig
            {
                RetryPolicy = new RetryPolicy
                {
                    MaxAttempts = 5,
                    InitialBackoff = TimeSpan.FromSeconds(5),
                    MaxBackoff = TimeSpan.FromSeconds(5),
                    RetryableStatusCodes = { StatusCode.Unavailable }
                }
            }
        }
    },
    MaxRetryAttempts = 6,
    InitialReconnectBackoff = TimeSpan.FromSeconds(6),
    MaxReconnectBackoff = TimeSpan.FromSeconds(6),
});
```

**Comment by JamesNK** [comment]
A service config can be provided externally by a resolver. `MaxRetryAttempts` limits the value returned by the resolver.

**Comment by setood** [comment]
Do I understand correctly that the following statements can be made?:
- In the `GrpcChannelOptions` class, the properties `MaxReconnectBackoff` and `InitialReconnectBackoff` are responsible for the parameters of reconnections to each of the endpoints provided by the `resolver`.
- In the `GrpcChannelOptions` class, the `RetryPolicy` property (`InitialBackoff`, `MaxBackoff`) is responsible for retrying grpc calls. However, if there is currently no one available connection (they are all in `connection backoff`), the retry will be symbolic - the connection attempt and grpc call will not be made over network.
- The `ServiceConfig` obtained from the resolver will take precedence over the `ServiceConfig` in `GrpcChannelOptions`.

If I understood everything correctly, it's quite difficult to figure out how it work. Maybe there is documentation about it, that I couldn't find?

**Comment by JamesNK** [comment]
https://learn.microsoft.com/en-us/aspnet/core/grpc/retries?view=aspnetcore-7.0

**Comment by JamesNK** [comment]
If there is no connection, then a call can't be sent. The channel must wait until a connection is available before a call can be sent. That seems self-explanatory to me.

> If an HttpClient is passed to GrpcChannelOptions, the connection manager is not used, and the properties (GrpcChannelOptions) MaxReconnectBackoff and InitialReconnectBackoff are ignored. Grpc calls and retries start a new connection with each call.

Maybe the channel should throw an error or log a warning if options are configured on it that can't be used.
