### ISSUE TITLE
Error 12152 calling WinHttpWriteData, 'The server returned an invalid or unrecognized response' for duplex streaming.

### ISSUE THREAD

**Issue by voroninp** [grpc/grpc-dotnet#2214]
I am running `Grpc.Net.Client` library on .net 4.6.2
Connection is `TLS`.\
`WinHttpHandler` is used.\
 I run my app on Windows 11.

However, when I make parallel calls I get an error (which occurs 100% of the time but for various parallel calls.)

> `Error 12152 calling WinHttpWriteData, 'The server returned an invalid or unrecognized response'.

And on the server side I see all calls failing simultaneously with 'The request stream was aborted.' message.

Any ideas why it's happening?

**Comment by JamesNK** [comment]
I don't know why. WinHttpHandler is written by other people. You could ask on dotnet/runtime but you'll need to provide a lot more information. Ideally a repo containing a reproduction of the bug.
