### ISSUE TITLE
New attributes in BalancerAddress are ignored unless Endpoint has changed

### ISSUE THREAD

**Issue by kalduzov** [grpc/grpc-dotnet#2225]
@JamesNK , hi.

We encountered a very incomprehensible behavior for us in the balancing implementation.

In our implementation, which is inherited from `SubchannelsLoadBalancer`, we add attributes for `BalancerAddress `to the `Attributes `property for balancing by mesh versions.

Our pod address can change its mesh version while the grpc client is running. Then a new list of addresses arrives, in which the `Endpoint `has not actually changed, but the composition of the attributes for it has changed.

However, the implementation in `SubchannelsLoadBalancer `does not allow changing the current subchannel address, because if the subchannel matches the one that came in, then the "new" address with new attributes is ignored and the old subchannel is used.

We think that at least the presence of new attributes on the `BalancerAddress `should be reflected in the existing subchannel, because from the point of view of logic, `BalancerAddress `is not only an address, but also its additional properties, which are now ignored.

It seems that in general it will be enough to do in the method
`UpdateChannelState(ChannelState state) `call like
such `newOrCurrentSubchannel.Subchannel.UpdateAddresses(new[] { address });`

and correct the conditions in `UpdateAddresses `to update/add at least attributes to an existing address.

Or add a new mechanism to forward these attributes to an existing subchannel.

### What version of gRPC and what language are you using?

All versions with client side balancing

**Comment by JamesNK** [comment]
Why are changing the attributes useful for you? I'd like to understand what you're using them for.

What do you think should happen to a connection if its `BalancerAddress` has different attributes? Should it be recreated (socket closed, and reopened) or should it continue to be connected but with a different `BalancerAddress`?

**Comment by JamesNK** [comment]
A version with this change in it is available now - https://www.nuget.org/packages/Grpc.Net.Client/2.57.0-pre1

Please try it out. If you see anything wrong, it can be fixed in a the next week. Otherwise, you'll have to wait a few months for the next release.

**Comment by kalduzov** [comment]
We'll check it out soon.

**Comment by kalduzov** [comment]
We'll check it out soon.

**Comment by kalduzov** [comment]
Unfortunately, we were unable to test the solution this week. :(

**Comment by JamesNK** [comment]
Ok, no problem. If there are issues, then you'll need to wait for the next release.

2.57.0 is already out with the change. You can try that.
