### ISSUE TITLE
Validate Windows version when using WinHttpHandler

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#2226]
https://github.com/grpc/grpc-dotnet/pull/2220 adds a net462 target and automatically wires up WinHttpHandler.

WinHttpHandler has some Windows version requirements. Constructing a channel should throw an error if WinHttpHandler is used on unsupported versions of Windows.

Note: on Windows Server 2022 there is partial support for WinHttpHandler. Unary and server streaming calls succeed, client and bidi streaming calls fail. Channel shouldn't throw an error on Windows Server 2022 to not block people who only need unary on Win2022.

Related: https://github.com/grpc/grpc-dotnet/issues/2197

**Comment by jskeet** [comment]
For the "note": I understand the motivation here, and not throwing is probably the right call - but it would be really useful to have some way of detecting this without each user having to write the Windows Server 2022 detection code. (Perhaps something in GrpcChannelOptions to indicate which features are required, and throw if they're not all met? I'm not sure how feasible that is.)
