### ISSUE TITLE
Documentation Bug: Timeout.InfiniteTimeSpan is an invalid value for SocketsHttpHandler.PooledConnectionIdleTimeout

### ISSUE THREAD

**Issue by stephen-swensen** [grpc/grpc-dotnet#2230]
### What version of gRPC and what language are you using?

2.56.0-pre1 / C#

### What operating system (Linux, Windows,...) and version?

Linux / AKS / Docker

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)

Docker build: mcr.microsoft.com/dotnet/sdk:6.0
Docker runtime: mcr.microsoft.com/dotnet/aspnet:6.0 (.NET 6.0.20)

### What did you do?

Per documentation https://learn.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-7.0#keep-alive-pings I configured `SocketsHttpHandler` with `PooledConnectionIdleTimeout = Timeout.InfiniteTimeSpan` and I enabled Trace level logging.

### What did you expect to see?

Connections kept alive indefinitely.

### What did you see instead?

Connections constantly being closed due to be in Idle state:

`dbug: Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport[16] => GrpcMethodType:DuplexStreaming GrpcUri:/my.namespace/MyCall Subchannel id '2' socket 10.160.0.197:80 is being closed because it exceeds the idle timeout of -00:00:00.0010000.`

### Anything else we should know about your project / environment?

Setting `PooledConnectionIdleTimeout` to `TimeSpan.FromDays(30)` resolved the issue, but if I set it too much higher than 30 days then I get an error `Call failed with gRPC error status. Status code: 'Internal', Message: 'Error starting gRPC call. ArgumentOutOfRangeException: Time-out interval must be less than 2^32-2. (Parameter 'dueTime')'.`

Moreover, when I look at the documentation for `SocketsHttpHandler.PooledConnectionIdleTimeout` I see `Exceptions: ArgumentOutOfRangeException – The value specified is less than Zero or is equal to InfiniteTimeSpan.` So it appears the grpc-dotnet documentation should not be suggesting `Timeout.InfiniteTimeSpan` as a value for `PooledConnectionIdleTimeout` (i.e. it's a documentation bug).

Aside: the additional logging added to 2.56.0-pre1 helped me uncover this issue, thank you!!

**Comment by JamesNK** [comment]
This is a bug. Fix here: https://github.com/grpc/grpc-dotnet/pull/2231

Thanks for trying out the pre-release and reporting the issue.
