### ISSUE TITLE
<Protobuf>  OutputOptions attributed ignored in csproj integration for protoc compiler

### ISSUE THREAD

**Issue by clarkezone** [grpc/grpc-dotnet#2232]
### What version of gRPC and what language are you using?
8.0.100-preview.6.23330.14

### What operating system (Linux, Windows,...) and version?
Ubuntu 22.04

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)

.NET SDK:
 Version:   8.0.100-preview.6.23330.14
 Commit:    ba97796b8f

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /home/james/.dotnet/sdk/8.0.100-preview.6.23330.14/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-preview.6.23329.7
  Architecture: x64
  Commit:       5340be2ccc

.NET SDKs installed:
  6.0.412 [/home/james/.dotnet/sdk]
  8.0.100-preview.6.23330.14 [/home/james/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.20 [/home/james/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.6.23329.11 [/home/james/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.20 [/home/james/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.6.23329.7 [/home/james/.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/home/james/.dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

### What did you do?
Attempted to set file extension option to include .g.cs to avoid warnings as errors being triggered from the generated output.  This was done using OutputOptions attribute per the documentation here: https://chromium.googlesource.com/external/github.com/grpc/grpc/+/HEAD/src/csharp/BUILD-INTEGRATION.md and the compiler documentation here: https://protobuf.dev/reference/csharp/csharp-generated/

<Project Sdk="Microsoft.NET.Sdk.Web">
<ItemGroup>
<Protobuf Include="proto\geocacheservice.proto" GrpcServices="Client" OutputOptions="--csharp_opt=file_extension=.g.cs" />
<PackageReference Include="Google.Protobuf" Version="3.18.0" />
<PackageReference Include="Grpc.Net.Client" Version="2.39.0" />
<PackageReference Include="Grpc.Tools" Version="2.40.0">
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
  <PrivateAssets>all</PrivateAssets>
</PackageReference>
</ItemGroup>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>

### What did you expect to see?
The generated code should have used the .g.cs extension.  In reality the tooling should likely default to outputting .g.cs to avoid the warnings as errors trap since generated code typically generates warnings

### What did you see instead?
.cs extension indicating my custom

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc-dotnet/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by JamesNK** [comment]
Please recreate this issue at grpc/grpc repo. That's where Grpc.Tools is located: https://github.com/grpc/grpc/issues/new/choose
