### ISSUE TITLE
Grpc method attributes

### ISSUE THREAD

**Issue by careless6666** [grpc/grpc-dotnet#2238]
In controllers actions we can set attribute, and when check it in middleware like this

```
public async Task InvokeAsync(HttpContext context)
{
       var endpoint = context.GetEndpoint();
       var skipLogAttributes = endpoint?.Metadata.GetMetadata<SkipLogsAttribute>();
}
```

Do we have a similar mechanism for GRPC? Is there any suitable alternative?

**Comment by JamesNK** [comment]
See https://learn.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-7.0&tabs=visual-studio#resolve-httpcontext-in-grpc-methods

Then get the endpoint from the context like you usually would.
