### ISSUE TITLE
Remove System.Net.Http.SocketsHttpHandler.Http2Support appcontext switch

### ISSUE THREAD

**Issue by JunTaoLuo** [grpc/grpc-dotnet#226]
This has been set to true by default so we don't have to do it anymore. Will require an ingestion of new SDK when it's available.

**Comment by JamesNK** [comment]
Where/when was that change made? I tried removing the setting with a new SDK and it didn't work.

**Comment by JunTaoLuo** [comment]
This change is now in master https://github.com/dotnet/corefx/blob/d943b4d090dc8e88cbf02e6e24702543c59c49fb/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionSettings.cs#L126-L127 but it doesn't seem to be available yet.
