### ISSUE TITLE
Can Grpc for .NET be used to build a grpc server without an aspnetcore dependency and also with a totally custom transport layer?

### ISSUE THREAD

**Issue by ApolonTorq** [grpc/grpc-dotnet#2260]
All of the server side examples appear to have a Grpc.AspNetCore dependency.

Can this project be used to build the following types of grpc servers?

- grpc servers that listen on sockets without the aspnetcore dependency?
- grpc servers which rely on a totally custom transport layer? i.e. not sockets, unix sockets or named pipes.

**Comment by JamesNK** [comment]
> grpc servers that listen on sockets without the aspnetcore dependency?

No.

> grpc servers which rely on a totally custom transport layer? i.e. not sockets, unix sockets or named pipes.

Yes. Kestrel supports configuring custom transports. It's not documented but you can look at aspnetcore source code and see how the sockets and named pipes transports are written.
