### ISSUE TITLE
LoadLibrary failed with error 193

### ISSUE THREAD

**Issue by Taiizor** [grpc/grpc-dotnet#2292]
### What version of gRPC and what language are you using?
Grpc" "2.46.6"
Grpc.Core "2.46.6"
Grpc.Core.Api "2.57.0"
Google.Protobuf "3.24.4"

C#

### What operating system (Linux, Windows,...) and version?
Windows 11 ARM64

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET Framework 4.8

### What did you do?
I just run the application.

### What did you see instead?

`[16:14:34] ~ [SucroseWatchdog Thread-5386/Error] ~ [DISPATCHER UNHANDLED EXCEPTION START]
[16:14:34] ~ [SucroseWatchdog Thread-5386/Error] ~ [Application crashed: Error loading native library "C:\Users\user\AppData\Local\Sucrose\Sucrose.Launcher\grpc_csharp_ext.x64.dll". LoadLibrary failed with error 193.]
[16:14:34] ~ [SucroseWatchdog Thread-5386/Error] ~ [Inner exception: .]
[16:14:34] ~ [SucroseWatchdog Thread-5386/Error] ~ [Stack trace:    bei Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   bei Grpc.Core.Internal.NativeExtension.LoadNativeMethodsUsingExplicitLoad()
   bei Grpc.Core.Internal.NativeExtension..ctor()
   bei Grpc.Core.Internal.NativeExtension.Get()
   bei Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   bei Grpc.Core.GrpcEnvironment..ctor()
   bei Grpc.Core.GrpcEnvironment.AddRef()
   bei Grpc.Core.Server..ctor(IEnumerable'1 options)
   bei Sucrose.Grpc.Services.GeneralServerService.ServerCreate(ServerServiceDefinition Services)
   bei Sucrose.Launcher.App.Configure()
   bei Sucrose.Launcher.App.OnStartup(StartupEventArgs e)
   bei System.Windows.Application.<.ctor>b__1_0(Object unused)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler).]
[16:14:34] ~ [SucroseWatchdog Thread-5386/Error] ~ [DISPATCHER UNHANDLED EXCEPTION FINISH]`

### Anything else we should know about your project / environment?
No.

**Comment by JamesNK** [comment]
Please open issues relating to Grpc.Core in grpc/grpc.
