### ISSUE TITLE
Decide NuGet packages, package names and namespaces

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#23]
- [ ] Lock down what packages will make up .NET grpc
- [ ] NuGet package names
- [ ] Namespaces

**Comment by JamesNK** [comment]
## Packages!

Please correct any mistakes, I'm onboarding into csharp gRPC 😄 

### State today

* `Grpc.Core` - Contains .NET APIs, native components for Win, OSX, Linux, iOS, Xamarin. Used by server and client at runtime
* `Grpc.Tools` - Contains native components for Win, OSX, Linux, and MSBuild targets. Used to turn proto files into generated code. Used at dev time.
* `Grpc` - Depends on `Grpc.Core`. Not commonly used.
* `Google.Protobuf` - Contains .NET APIs. Used at runtime to process protocol buffer data. Referenced by end user projects.

### Proposal

* **`Grpc.Common` - Contains most .NET APIs from `Grpc.Core`. Used by `Grpc.Core` and `Grpc.AspNetCore`**
* **`Grpc.AspNetCore` - ASP.NET Core specific logic. Routing, logging, etc. Depends on `Microsoft.AspNetCore.*`. Used by server at runtime.**
* `Grpc.Core` - Contains **some .NET APIs**, **type forwards to `Grpc.Common`**, native components for Win, OSX, Linux, iOS, Xamarin. **Depends on `Grpc.Common`**. **Used by client at runtime**.

**Unchanged:**
* `Grpc.Tools` - Contains native components for Win, OSX, Linux, and MSBuild targets. Used to turn proto files into generated code. Used at dev time.
* `Grpc` - Depends on `Grpc.Core`. Not commonly used.
* `Google.Protobuf` - Contains .NET APIs. Used at runtime to process protocol buffer data. Referenced by end user projects.

**Comment by JamesNK** [comment]
On namespaces, the APIs in `Grpc.Common` will need to keep the same namespace for binary compatibility. `Grpc.AspNetCore` feels like a good base namespace for `Grpc.AspNetCore`.

Package: `Grpc.Core`
Namespace: `Grpc.Core`

Package: `Grpc.Common`
Namespace: `Grpc.Core` (required for binary compat)

Package: `Grpc.AspNetCore`
Namespace: `Grpc.AspNetCore`

**Comment by JamesNK** [comment]
@jtattermusch This is type forwarding: https://docs.microsoft.com/en-us/dotnet/framework/app-domains/type-forwarding-in-the-common-language-runtime

It isn't very complicated. It has a couple of constraints: when you move a type to a new assembly then you have to move all its dependencies, and the type has to keep the same name and namespace.

**Comment by JamesNK** [comment]
Context on why we would like to add netstandard2.0 targets - https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting#net-standard

> All platforms supporting .NET Standard 2.0 will use the netstandard2.0 target and benefit from having a smaller package graph while older platforms will still work and fall back to using the netstandard1.x target.

It should not be difficult to add netstandard2.0 support because Grpc.Core already has netstandard1.5.

**Comment by jtattermusch** [comment]
@JamesNK  I agree with most of the proposal in principle, but have a few comments:

- `Grpc.Core` currently targets `net45`, not `net451`. Therefore I assume the API package would also target net45 (besides supporting netstandard1.5 and netstandard2.0) and Grpc.Core would continue targetting `net45`

- I think `Grpc.Common` might be a too general name that doesn't really tell much what it is about. I'd be leaning towards something more like `Grpc.Common.Api`, `Grpc.Core.Api`, `Grpc.Core.Common` as that is more descriptive, and also doesn't use up a second-level name (IMHO second-level names should be reserved for packages that will be directly imported by users, not for "internals"). Almost no one would be using this package directly so a longer name is fine (and longer package name also subconsciously sends the signal "this is not the package you want").   As a remark, if the common package starts with prefix `Grpc.Core. ....` it is less surprising that it contains classes from `Grpc.Core` namespace (which is required for backward compatibility).

- The name `Grpc.AspNetCore` is fine if this is the package that the user is expected to add to their project most of the time (i.e. this contains all the grpc functionality most users would normally need). If this is meant more as a "core" package with barebone functionality and more add-on packages with additional support will exist, then I'd be leaning towards a more well-defined name (sth. like `Grpc.AspNetCore.Core`, `Grpc.AspNetCore.Middleware` or so). But ultimately this also depends on how the name fits into the ASP.NET core ecosystem. For comparison, if `Microsoft.AspNetCore` is also meant as the "barebone" ASP.NET core functionality than I guess this is fine. Out of curiosity, if we come up with an extension nuget package in the future (that user would add to their project separately), how would we call such package? For hypothetical feature "AdvancedRouting",  would we have a nuget package `Grpc.AspNetCore.AdvancedRouting`? Would it then be clear to users that is not by default contained in the `Grpc.AspNetCore` package?

- The name `Grpc.AspNetCore` also assumes that this would contain both client and server logic (which seem to be the plan, I just wanted to point it out explicitly).

- Adding `netstandard2.0` targets shouldn't be a problem. At the same time, this is basically nice to have, it doesn't really block the development of other components, right?

- (not really that important now, mostly implementation detail) I'm assuming that `Grpc.AspNetCore` will depending on multiple `Grpc.AspNetCore. ....` packages focused on specific areas. Or are we planning to build a monolithic package?

- I assume `netcoreapp3.0` target for Grpc.AspNetCore is because we want to benefit from the latest additions to .NET core, mostly for performance gains? That definitely makes sense, but at the same time, I can see that especially the client functionality would be very welcome by users on platforms like Xamarin and Unity. Can we possibly come up with a solution that would enable basic functionality (e.g at least the grpc client) on mobile platforms while not compromising the performance under asp.net core? (I think both Unity and Xamarin can currently support netstandard2.0).

**Comment by JamesNK** [comment]
> Grpc.Core currently targets net45, not net451

Targeting net45 is fine. I accidentally wrote net451 at some point 😄 

> Grpc.Core.Common

Sure, that's a fine option as well. It has the benefit that of making it more obvious that Grpc.Tools doesn't reference common.

> The name Grpc.AspNetCore is fine if this is the package that the user is expected to add to their project most of the time...

> I'm assuming that Grpc.AspNetCore will depending on multiple Grpc.AspNetCore. .... packages focused on specific areas. Or are we planning to build a monolithic package?

We might have more than one package under Grpc.AspNetCore. We can evaluate if and how to divide functionality up into packages as we build it.

> The name Grpc.AspNetCore also assumes that this would contain both client and server logic (which seem to be the plan, I just wanted to point it out explicitly).

Hmmm? Why do you think that. My understanding is Grpc.AspNetCore.* would only be for hosting gRPC in ASP.NET Core. Clients would continue to use Grpc.Core.

> Adding netstandard2.0 targets shouldn't be a problem. At the same time, this is basically nice to have, it doesn't really block the development of other components, right?

Yes it is a nice to have.

> I assume netcoreapp3.0 target for Grpc.AspNetCore is because we want to benefit from the latest additions to .NET core, mostly for performance gains?

Grpc.AspNetCore should be for server only. It needs to be netcoreapp3.0 because that is what ASP.NET Core 3.0 will be targeting (it no longer targets netstandard2.0)

**Comment by jtattermusch** [comment]
> > Grpc.Core currently targets net45, not net451
> 
> Targeting net45 is fine. I accidentally wrote net451 at some point 
> 
> > Grpc.Core.Common
> 
> Sure, that's a fine option as well. It has the benefit that of making it more obvious that Grpc.Tools doesn't reference common.
> 
> > The name Grpc.AspNetCore is fine if this is the package that the user is expected to add to their project most of the time...
> 
> > I'm assuming that Grpc.AspNetCore will depending on multiple Grpc.AspNetCore. .... packages focused on specific areas. Or are we planning to build a monolithic package?
> 
> We might have more than one package under Grpc.AspNetCore. We can evaluate if and how to divide functionality up into packages as we build it.
> 
> > The name Grpc.AspNetCore also assumes that this would contain both client and server logic (which seem to be the plan, I just wanted to point it out explicitly).
> 
> Hmmm? Why do you think that. My understanding is Grpc.AspNetCore.* would only be for hosting gRPC in ASP.NET Core. Clients would continue to use Grpc.Core.

That is based on a discussion with David. What we discussed:
- in the microservice world (our market), the server are often also clients as they call other backends.
- we will want a gRPC client using .NET Http/2 client at some point too as this makes the whole stack more unified (using Grpc.Core with native component is ok for the near future) - David mentioned that this should be possible in the future, possibly reusing some HTTP/2 code from asp.net core (I don't know the details).

Our primary focus for now is definitely building the asp.net core integration (server-side only). But planning for the future: What will be the nuget name for the pure C# client if we come up with one? Once we have a pure C# client, shouldn't there be an umbrella package for both the client and server functionality?

> 
> > Adding netstandard2.0 targets shouldn't be a problem. At the same time, this is basically nice to have, it doesn't really block the development of other components, right?
> 
> Yes it is a nice to have.
> 
> > I assume netcoreapp3.0 target for Grpc.AspNetCore is because we want to benefit from the latest additions to .NET core, mostly for performance gains?
> 
> Grpc.AspNetCore should be for server only. It needs to be netcoreapp3.0 because that is what ASP.NET Core 3.0 will be targeting (it no longer targets netstandard2.0)

**Comment by JamesNK** [comment]
ping @davidfowl

I'm not up to speed with future plans with .NET Http/2, but I can see your point that we should plan for it now. I don't think you would want `Grpc.AspNetCore.*` as the package name for the client. That is something we did for SignalR - `Microsoft.AspNetCore.SignalR.Client` - that I think we'd change give the opportunity. In people's minds, AspNetCore = server

@davidfowl could you comment on what HTTP/2 code would be used from asp.net in gRPC clients?

**Comment by jtattermusch** [comment]
@JamesNK  @JunTaoLuo are you more in favor of `Grpc.Core.Api` or  Grpc.Core.Common`?

**Comment by davidfowl** [comment]
I'm just getting up to date here.

> @davidfowl could you comment on what HTTP/2 code would be used from asp.net in gRPC clients?

This was a future hypothetical refactoring related to bedrock. Right now the client and server share code by source (the HPACK implementation) so there isn't much real here. 

It would be nice to understand if there's a meta package that will bring in both client and server side for writing ASP.NET Core microservices. It's fine to have them split for layering but will we have a meta package that brings in both by default?

> @JamesNK @JunTaoLuo are you more in favor of Grpc.Core.Api or Grpc.Core.Common?

Grpc.Core.Api seems more meaningful, I'm assuming this is the shared C# API surface without the native bits?

**Comment by jtattermusch** [comment]
> I'm just getting up to date here.
> 
> > @davidfowl could you comment on what HTTP/2 code would be used from asp.net in gRPC clients?
> 
> This was a future hypothetical refactoring related to bedrock. Right now the client and server share code by source (the HPACK implementation) so there isn't much real here.
> 
> It would be nice to understand if there's a meta package that will bring in both client and server side for writing ASP.NET Core microservices. It's fine to have them split for layering but will we have a meta package that brings in both by default?

I think it would make sense to have such meta package (users shouldn't need to think about if they will need client, server or both, they just want to use grpc). It would be good to have some idea about what could such package be named like.

> 
> > @JamesNK @JunTaoLuo are you more in favor of Grpc.Core.Api or Grpc.Core.Common?
> 
> Grpc.Core.Api seems more meaningful, I'm assuming this is the shared C# API surface without the native bits?

Yes, that is correct. `Grpc.Core.Common` would make more sense if the package actually contained some non-trivial logic (besides the API) that we wanted to share, but as of now, I don't thing there is much logic to share, it's really mostly about APIs (so Grpc.Core.Api is currently my favorite).
Another name that came into my mind is `Grpc.Core.Surface`, `Grpc.Core.CommonSurface`.

**Comment by JamesNK** [comment]
I don't have a strong preference for the new package name. Pick the one you like most and we can always change it later before shipping a stable package.

The future I think we're aiming towards:

`Grpc.AspNetCore` - fully .NET server. `netcoreapp3.0`
`Grpc.Client` - fully .NET client. `netstandard2.0`
`Grpc.Core` - legacy native implementation of client and server. `net45, netstandard1.5, netstandard2.0`

Supporting package(s):

`Grpc.Core.Api/Common` - type forwarded Types from Grpc.Core. `net45, netstandard1.5, netstandard2.0`. I think this could be used by both `AspNetCore` and `Client`. There will be some types in it that each don't use but that isn't a big deal.

What would a metapackage reference? If it is just `AspNetCore` and `Client` then I don't think it would add much value.

**Comment by jtattermusch** [comment]
> I don't have a strong preference for the new package name. Pick the one you like most and we can always change it later before shipping a stable package.
> 
> The future I think we're aiming towards:
> 
> `Grpc.AspNetCore` - fully .NET server. `netcoreapp3.0`
> `Grpc.Client` - fully .NET client. `netstandard2.0`

IMHO there are two problems with that name:
- it doesn't really make it clear that there are 2 implementations available - the "native" one and the "pure .NET" one.  With the Grpc.* nuget package names currently in existence, it's not really clear where this package fits into the ecosystem. (E.g. the relationship of Grpc.Core and Grpc.Client is not clear to a new user).
- it seems to imply that Grpc.Client supersedes Grpc.Core, which might well happen one day, but it's not a given. See my comment below.

> `Grpc.Core` - legacy native implementation of client and server. `net45, netstandard1.5, netstandard2.0`

Just a note: I wouldn't call `Grpc.Core` legacy - it might be that the pure .NET client is one day the go to version of gRPC for .NET, but to me it's definitely not a given (there will be differences in supported features etc.). The pure .NET client being a successful product with a lot of users and it becoming the official version of gRPC .NET are two very different things IMHO.

> 
> Supporting package(s):
> 
> `Grpc.Core.Api/Common` - type forwarded Types from Grpc.Core. `net45, netstandard1.5, netstandard2.0`. I think this could be used by both `AspNetCore` and `Client`. There will be some types in it that each don't use but that isn't a big deal.
> 
> What would a metapackage reference? If it is just `AspNetCore` and `Client` then I don't think it would add much value.

**Comment by JunTaoLuo** [comment]
Hey @jtattermusch, here's our latest thoughts on the package layout and naming. 
![grpc](https://user-images.githubusercontent.com/2030323/51108093-cf82a880-17a5-11e9-9f28-5125d71a453d.png)

1. We envision eventually shipping both a managed client and managed server. We want to distinguish these from the native clients and server so we should probably Grpc.AspNetCore/Grpc.NetCore in their name. We also don't think most users will be taking a direct dependency on these packages so we are proposing that we use a three-part name.
2. Most services call into other services so it’s likely they will use both the server and client. To simplify consumption, we should probably reserve the Grpc.AspNetCore metapackage to bring in both client and server functionalities.
3. In addition to server and client functionalities, an app will also need to reference Google.ProtoBuf and Grpc.Tools to actually function. The metapackage would be a good opportunity to bring in these dependencies and simplify the app’s package references.
4. We will also need a dependency on Microsoft.Extensions.ServiceDefinition.Design to bring in the ServiceReference functionalities, most likely. Ideally Grpc.Tools should bring this in but if we have strong push-back, the metapackage could bring this in as well.
5. HTTPClient may not be completed for the 3.0 milestone and it might make sense to create the metapackage once the managed client is available so these are currently marked as post 3.0. 
6. Grpc.Core will still be how users get their native clients and server
7. We're not keen on taking the top-level Grpc metapackage so we opted for Grpc.AspNetCore metapackage so it's clear that it is the metapackage that's related to the managed implementation offered on aspnetcore.

What do you think?

**Comment by jtattermusch** [comment]
This layout and naming is looking good! 

> Hey @jtattermusch, here's our latest thoughts on the package layout and naming.
> ![grpc](https://user-images.githubusercontent.com/2030323/51108093-cf82a880-17a5-11e9-9f28-5125d71a453d.png)
> 
> 1. We envision eventually shipping both a managed client and managed server. We want to distinguish these from the native clients and server so we should probably Grpc.AspNetCore/Grpc.NetCore in their name. We also don't think most users will be taking a direct dependency on these packages so we are proposing that we use a three-part name.
SG

> 2. Most services call into other services so it’s likely they will use both the server and client. To simplify consumption, we should probably reserve the Grpc.AspNetCore metapackage to bring in both client and server functionalities.

SG

> 3. In addition to server and client functionalities, an app will also need to reference Google.ProtoBuf and Grpc.Tools to actually function. The metapackage would be a good opportunity to bring in these dependencies and simplify the app’s package references.

SG for Grpc.AspNetCore metapackage to reference Google.Protobuf (users wanting to use alternative serialization formats can still use Grpc.NetCore.HTTPClient and Grpc.AspNetCore.Server packages individually and bring their own codegen).

I think Grpc.AspNetCore.Server should ideally not depend on Google.Protobuf and it should be fully serialization-format agnostic (that's discussed separately in https://github.com/grpc/grpc-dotnet/issues/30)

 Grpc.AspNetCore metapackage to reference Grpc.Tools is a good idea if we check out it actually works well in all the use cases (e.g. Grpc.Tools needs to be a build-only dependency).

> 4. We will also need a dependency on Microsoft.Extensions.ServiceDefinition.Design to bring in the ServiceReference functionalities, most likely. Ideally Grpc.Tools should bring this in but if we have strong push-back, the metapackage could bring this in as well

I'm happy to hear more here, but generally I don't have anything against it if this doesn't break any of the supported platforms (btw I haven't found the package name on nuget.org).

> 5. HTTPClient may not be completed for the 3.0 milestone and it might make sense to create the metapackage once the managed client is available so these are currently marked as post 3.0.

SG

> 6. Grpc.Core will still be how users get their native clients and server

SG

> 7. We're not keen on taking the top-level Grpc metapackage so we opted for Grpc.AspNetCore metapackage so it's clear that it is the metapackage that's related to the managed implementation offered on aspnetcore.

SG
> 
> What do you think?

Except the minor comments (that can be IMHO resolved separately later) I'm happy with the proposed layout. Thanks for taking the time to document it! (I think that pkg layout picture will be great for explaining how the gRPC .NET landscape looks like in documentation).

**Comment by JunTaoLuo** [comment]
>  (btw I haven't found the package name on nuget.org).

Because this is new in 3.0 and hasn't been released yet 😄

**Comment by JunTaoLuo** [comment]
I'm going to close this issue as the design is capture in the doc now. We'll open new issues if there needs to be any changes.
