### ISSUE TITLE
How can I reuse the same Channel instance for GRPC clients of different types?

### ISSUE THREAD

**Issue by ydie22** [grpc/grpc-dotnet#2306]
In the documentation, on the performance best practices, it is stated that channels should be long-lived and reused, which perfectly makes sense. Moreover, [https://learn.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-7.0#reuse-grpc-channels](url) also states that channels can be used to create clients of different types. However, I could not figure out how to achieve this. Can someone shed some light on the way to go to do that? Actually, I'd like to be able to call both normal service operations and health checks using the same channel, to ensure that any channel-level (connection) problem does not escape the health check. All our endpoints are implementing both their specific contract and the health check.

Our Grpc clients are managed using the Grpc client factory.

Thank you!

**Comment by JamesNK** [comment]
A client has a constructor that takes a channel. Just creates multiple clients of different types using the same channel.

**Comment by ydie22** [comment]
@JamesNK thanks for your answer. This would indeed be the way to go if we were explicitly instantiating clients and creating channels. However, we are using the `GrpcClientFactory`, to benefit from the automatic channel lifetime management and other things. I looked briefly at the code and it seems that `GrpcCallInvokerFactory` is caching channel instances using a combination of name and type. Therefore, I'm wondering how I could reuse channels across clients of different types when using `GrpcClientFactory`.

**Comment by JamesNK** [comment]
You can't do that with the factory. If you want greater control, you must manage the channel and clients yourself.
