### ISSUE TITLE
Support MAX_CONNECTION_AGE in dotnet server implementation

### ISSUE THREAD

**Issue by careless6666** [grpc/grpc-dotnet#2308]
if we look at the grpc documentation https://grpc.io/docs/guides/keepalive/
we see that there is a parameter called MAX_CONNECTION_AGE, we have a parameter in dotnet with similar behavior, but for the client, not for the server, example

```
new SocketsHttpHandler
        {
            EnableMultipleHttp2Connections = true,
            PooledConnectionIdleTimeout = TimeSpan.FromMinutes(1),
            PooledConnectionLifetime = TimeSpan.FromMinutes(1),
        }
```

if clients come to me in other languages via grpc, can I somehow set this setting on the server in dotnet?

This is an interesting point because Java supports closing the connection on the server side, but does not close it on the client side, it turns out that the dotnet can communicate with Java normally, but Java cannot, because it is create dns update problems

**Comment by careless6666** [comment]
This is an interesting point because Java supports closing the connection on the server side, but does not close it on the client side, it turns out that the dotnet can communicate with Java normally, but Java cannot, because it is create dns update problems

**Comment by JamesNK** [comment]
This is an ASP.NET Core feature. You should request this feature at https://github.com/dotnet/aspnetcore.

I think a way you could create a max lifetime is by writing [Kestrel connection middleware](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/connection-middleware?view=aspnetcore-7.0) and having a timer that aborts the connection context when triggered. If you do this, it's important the clean up the timer if the connection ends sooner to avoid unnecessary resource usage.

**Comment by careless6666** [comment]
thanks
