### ISSUE TITLE
Grpc Client ignores proxy configuration in GrpcChannelOptions.HttpHandler after update

### ISSUE THREAD

**Issue by ChristophSchemainda** [grpc/grpc-dotnet#2312]
### What version of gRPC and what language are you using?
Grpc.Net.Client 2.58

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
VisualStudio 2022, building for .NET6

### What did you do?
Updated the NuGet for Grpc.Net.Client from 2.39 to 2.58

### What did you expect to see?
Client can still connect to the server

### What did you see instead?
Proxy configuration is ignored and no connection is possible

### Anything else we should know about your project / environment?
The connection is essentially created by the following code:
        private void Connect()
        {
            var httpHandler = new SocketsHttpHandler()
            {
                PooledConnectionIdleTimeout = Timeout.InfiniteTimeSpan,
                EnableMultipleHttp2Connections = false,
                Proxy = new WebProxy("Proxy:3128", true),
                UseProxy = true
            };

            var op = new GrpcChannelOptions()
            {
                HttpHandler = httpHandler
            };

            GrpcChannel = GrpcChannel.ForAddress("https://Server:443", op);
        }

After this, a client is created and some grpc calls are made with
    var client = GrpcChannel.CreateGrpcService<ITestGrpcService>();
    var result = client.TestMethod();

After the NuGet update, the proxy configuration is ignored.
TCPView shows, that the client tries to open a connection to Server:443 instead of Proxy:3128

**Comment by JamesNK** [comment]
Newer versions have custom connectivity features which, unfortunately, don't currently take into account the proxy.

There are a couple of options to fix this issue:
1. Change SocketsHttpHandler to HttpClientHandler. I'm not sure if all of the settings you're setting on the sockets handler are available on HttpClientHandler.
2. Set a property on SocketsHttpHandler to not use the custom connectivity features:

```cs
httpHandler.Properties["__GrpcLoadBalancingDisabled"] = true;
```

**Comment by ChristophSchemainda** [comment]
Disabling the client load balancer features has worked in our case.
We are now able to update to the newest version.

**Comment by KirillKurdyukov** [comment]
https://github.com/grpc/grpc-dotnet/blob/1625f8942791c82d700802fc7278c543025f0fd3/src/Grpc.Net.Client/GrpcChannel.cs#L286


Used sockerHttpHandler

**Comment by Ksyusha7650** [comment]
> Newer versions have custom connectivity features which, unfortunately, don't currently take into account the proxy.
> 
> There are a couple of options to fix this issue:
> 
> 1. Change SocketsHttpHandler to HttpClientHandler. I'm not sure if all of the settings you're setting on the sockets handler are available on HttpClientHandler.
> 2. Set a property on SocketsHttpHandler to not use the custom connectivity features:
> 
> httpHandler.Properties["__GrpcLoadBalancingDisabled"] = true;


Hello @JamesNK!

Can you please tell me if the following statement is still the current decision: "httpHandler.Properties["__GrpcLoadBalancingEnabled"] = false;"
