### ISSUE TITLE
Performance benchmark between Grpc.Core and Grpc.NET?

### ISSUE THREAD

**Issue by msedi** [grpc/grpc-dotnet#2317]
We are still using the old Grpc.Core implementation and want to migrate soon. The question we have if there are performance benchmark/comparisons between the Grpc.Core and Grpc.NET?

**Comment by gfoidl** [comment]
I don't have links for comparing Grpc.NET and C-core version, but one that compares Grpc.NET with other languages.

[grpc_bench Results](https://github.com/LesnyRumcajs/grpc_bench/discussions)

In that repo (or your local clone) you could add a benchmark for the C-core version and run the benchmarks locally to have actual numbers on your hardware.
But when looking at the presented results it's very likely (super naive interpretation) that Grpc.NET will be superior to the C-core version (which is kind of deprecated anyway).

PS: please edit the title, as it contains two times Grpc.NET

**Comment by msedi** [comment]
@gfoidl. Thanks for the feedback. That helps a lot.
