### ISSUE TITLE
Video/Audio Streaming with GRPC

### ISSUE THREAD

**Issue by ctechid** [grpc/grpc-dotnet#2323]
I want to create a chat application with video/audio streams like jitsi-meet. Single server with thousands of clients.
Is video/audio streaming recommended with GRPC?

Thanks.

**Comment by JamesNK** [comment]
There are better ways to stream binary. See https://learn.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-8.0#binary-payloads for drawbacks to using gRPC

**Comment by ctechid** [comment]
> There are better ways to stream binary. See https://learn.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-8.0#grpc-services-and-large-binary-payloads for drawbacks to using gRPC

Thank you for the advice.
