### ISSUE TITLE
Make Interceptors to be async for pre-processing Metadata and using cancellation token

### ISSUE THREAD

**Issue by GoNextGroup** [grpc/grpc-dotnet#2325]
Hello.

I see the mechanism for post-processing data in Interceptor. For example (catch it on MS learn)

```
public class ErrorHandlerInterceptor : Interceptor
{
    public override AsyncUnaryCall<TResponse> AsyncUnaryCall<TRequest, TResponse>(
        TRequest request,
        ClientInterceptorContext<TRequest, TResponse> context,
        AsyncUnaryCallContinuation<TRequest, TResponse> continuation)
    {
        var call = continuation(request, context);

        return new AsyncUnaryCall<TResponse>(
            HandleResponse(call.ResponseAsync),
            call.ResponseHeadersAsync,
            call.GetStatus,
            call.GetTrailers,
            call.Dispose);
    }

    private async Task<TResponse> HandleResponse<TResponse>(Task<TResponse> inner)
    {
        try
        {
            return await inner;
        }
        catch (Exception ex)
        {
            throw new InvalidOperationException("Custom error", ex);
        }
    }
}
```

In this code I can use async methods in the HandleResponse method.

But there are no way to do "pre-processing" of a request. I cannot use async methods for Metadata changing.

The "use case": I want to transfer additional data about user between methods. I use EasyCaching library which provides me async methods GetAsync/SetAsync.
Before call I want to put some data with token in Distributed cache for calling service. And after call I want to get back additional data which called service put to caller service.

Through the interceptor I cannot use SetAsync on client side, just only Set.

This is a silly case, I know. Maybe you could show me another mechanism? I do not think that AsyncAuthInterceptor usage is a good approach here.

Also I want  to point out that AsyncUnaryCall has already realized GetAwaiter(), so, is it possible to add realization of `AsyncAsyncUnaryCallMethodBuilder` like `AsyncValueTaskMethodBuilder` for making the method allowing `async` keyword?

Thank you.

**Comment by JamesNK** [comment]
AsyncAuthInterceptor lets you do this.

**Comment by GoNextGroup** [comment]
James, I do disagree with this solution - I want to have just one interceptor for pre-processing and post-processing which I can register easily without any division. It's really strange - AsyncAuthInterceptor mostly connected with CallCredentials if I'm not mistaken. So, this division can greatly increase coupling of my code, because I do need keep in mind that pre-processing is located on AsyncAuthInterceptor, but post-processing - in just an ordinary interceptor. And It's really strange - I need to divide handler logic for client and server part, because  we have `Task<TResponse> UnaryServerHandler` which can be async.

**Comment by JamesNK** [comment]
> James, I do disagree with this solution

I didn't design the interceptors API but I'm guessing its present design occurred because interceptors were added later, by which point the methods to start a gRPC call were already created and they weren't async. It isn't possible to add async to interceptors at the start of a gRPC call without a large redesign and modification of proto code gen. This would be a big undertaking and breaking change.

> And It's really strange - I need to divide handler logic for client and server part, because we have Task<TResponse> UnaryServerHandler which can be async.

The design of client and server interceptors are very different (along with creating clients and servers in general). In a server, the server is calling gRPC with the request which then executes user code. In a client it's the other way around. User code calls gRPC. Unfortunately the methods weren't designed with async, which means all the wrapping of stream readers and writers, and setting of headers, can't have async.

**Comment by GoNextGroup** [comment]
James, but why don't you just add AsyncMethodBuilderAttribute and Async method builder realization for AsyncUnaryCall<TResponse> like ValueTask<TResponse>? Will it affect proto code gen?

**Comment by JamesNK** [comment]
`AsyncUnaryCall` is awaited by user code, not the internals of the gRPC client.

Call types that don't return one value (e.g. bidirectional streaming, server streaming) don't have GetAwaiter.

I don't think it can be done without large code changes and breaking changing, but you're welcome to clone the repo and try your idea.
