### ISSUE TITLE
Accessing headers/trailers of response in client Interceptor unary calls

### ISSUE THREAD

**Issue by tli2** [grpc/grpc-dotnet#2330]
I am trying to piggyback some custom tracking information to each gRPC request/response using the interceptor mechanism. The client interceptor, in this case, would append some information to a request header before sending it, and consumes the response header (populated by the server side interceptor) before exposing results up to the caller.

I am able to do so in `AsyncUnaryCall` and `AsyncClientStreamingCall` as documented [here](https://learn.microsoft.com/en-us/aspnet/core/grpc/interceptors?view=aspnetcore-8.0#awaiting-response-in-client-interceptor). However, there does not seem to be a way to get response headers in other variations. Specifically, I want to do the same thing for `BlockingUnaryCall`, accessing the response header after invoking continuation. Is a way to achieve this now/plans to support this in the future?

**Comment by JamesNK** [comment]
I don't think you can. A blocking call doesn't give access to response headers both from the caller's perspective and any interceptor's perspective.

**Comment by JamesNK** [comment]
You might be able to get around the limitation by having the `BlockingUnaryCall` method internally call `AsyncUnaryCall`, which makes the response headers available, and then do `ResponseAsync.Result` do get the response synchronously and return that. Don't worry about it blocking with `.Result`. That's literally what a blocking call does.
