### ISSUE TITLE
Is it posible implement Service mesh with grpc?

### ISSUE THREAD

**Issue by careless6666** [grpc/grpc-dotnet#2331]
If we want implement service mesh on http as example when we receive header 
```x-my-mesh: servicename:version```
we can make replace uri in http event like this
```
internal class HttpOutObserver : DiagnosticObserver
{
    [DiagnosticName("System.Net.Http.HttpRequestOut.Start")]
    public void OnHttpRequestOutStart(HttpRequestMessage request)
    {
            var serviceName = request.RequestUri!.Host.Split('.').First();
            var target = _meshContext.GetTargetVersionUri(serviceName);
                  
            request.RequestUri = new Uri(request.RequestUri.ToString().Replace(serviceName, target));
    }
}
```

we get service version from header and replace url, but if we try to do it in grpc
i try 
```request.RequestUri = new Uri(request.RequestUri.ToString().Replace(serviceName, target));```
 and this
```request.Options.Set(new HttpRequestOptionsKey<string>("CurrentAddress"), "10.41.145.191:82");```
 
 both of these approaches not working. Is this even it possible to do?

**Comment by JamesNK** [comment]
I haven't used gRPC with a service mesh. I don't know.
