### ISSUE TITLE
.NET 8.0 ChannelClosedException

### ISSUE THREAD

**Issue by rupreck** [grpc/grpc-dotnet#2333]
Under .NET 8.0, with version 2.59.0 of this project, if the connection is interrupted for any reason the Http2Connection FinalTeardown() method is called.  This hits the Complete() method in ChannelWriter, which then fails to complete, throwing a ChannelClosedException. This exception cannot be caught and so crashes the application. 

This is a huge problem because using this project on .NET 8.0 is therefore seriously problematic because a client can crash a server.

As you can imagine there are any number of reasons that the connection can be interrupted, from network issues, network changes or problems with either the server or the client.  Notably, if a client has an issue that triggers the Channel to close, this will immediately crash the server. 

### What version of gRPC and what language are you using?
2.59.0

### What operating system (Linux, Windows,...) and version?
Windows Server 2019, Windows 11 etc

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET 8.0.1

### What did you do?
GRPC call from client to server.  

### What did you expect to see?
No failure

### What did you see instead?
Server crashed.  

Application: SA.SQA.Provision.exe
CoreCLR Version: 8.0.23.53103
.NET Version: 8.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Threading.Channels.ChannelClosedException: The channel has been closed.
   at System.Net.Http.Http2Connection.FinalTeardown()
   at System.Net.Http.Http2Connection.Shutdown()
   at System.Net.Http.Http2Connection.Abort(Exception abortException)
   at System.Net.Http.Http2Connection.HeartBeat()
   at System.Net.Http.HttpConnectionPool.HeartBeat()
   at System.Net.Http.HttpConnectionPoolManager.HeartBeat()
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

### Anything else we should know about your project / environment?
No problem with this code on .NET 7.0

**Comment by JamesNK** [comment]
Hi

This looks like it is a problem with SocketsHttpHandler. Can you log this issue at https://github.com/dotnet/runtime and add link here? I'll make sure the right people see it.

**Comment by rupreck** [comment]
Thanks James,

I will do, but I'm wondering if grpc-dotnet can trap the exception.. our app can't - it ends up hitting our unhandled exception handler as the app is terminating...

       AppDomain.CurrentDomain.UnhandledException += new UnhandledExceptionEventHandler(CurrentDomain_UnhandledException);

At that point, there is nothing that can be done.

**Comment by JamesNK** [comment]
grpc-dotnet can't do anything. No grpc-dotnet code is involved in the call stack. It needs to be fixed in dotnet/runtime.

**Comment by gfoidl** [comment]
Issue got opened in runtime: https://github.com/dotnet/runtime/issues/95621
