### ISSUE TITLE
How to specify what data to return

### ISSUE THREAD

**Issue by NSV-dev** [grpc/grpc-dotnet#2341]
I'm writing gRPC service on C# and have a problem

Here is my objects
```proto
message GetReply {
  repeated PsychoPhysiologicalStateData states = 1;
}

message PsychoPhysiologicalStateData {
  string id = 1;
  string title = 2;
  string user_id = 3;
  repeated FullnessData fullness = 4;
  optional DatasetData dataset = 5;
  repeated PsychoPhysiologicalStateTimestampData timestamps = 6;
}
```

The problem is `DatasetData` is taking a lot of time to calculate, one of api's consumers needs it, other not. How can client specify what data he wants to be returned.

Of course I have 2 ways in mind:
1. Make `IncludeDatasetData` flag in request
2. Make separate request to get only `DatasetData` by `Id`

Both of them seems like a crutch for me
First one's problem is: I don't want to make a flag for every field of response object
Second one's problem is: I don't want clicent to make a lot of calls to api, it's better to have only one

So how do I do this "the right" way

**Comment by ricardSiliuk** [comment]
I think you're looking for `FieldMask`.

You can read about this more [here (example article about the concept)](https://netflixtechblog.com/practical-api-design-at-netflix-part-1-using-protobuf-fieldmask-35cfdc606518) and [here (docs)](https://protobuf.dev/reference/csharp/api-docs/class/google/protobuf/well-known-types/field-mask). Keep in mind that you need to be [specific](https://stackoverflow.com/questions/76013582/unexpected-behaviour-with-fieldmask-using-dotnet-core-grpc/76024928).

**Comment by JamesNK** [comment]
Yes, this is what FieldMask is for.

**Comment by NSV-dev** [comment]
Yes, it's exactly what i need. Thaks a lot.
