### ISSUE TITLE
How to let client side know that server side is shutting down

### ISSUE THREAD

**Issue by AidasSin** [grpc/grpc-dotnet#2342]
Hello, I would like to send a message to client side that the server is shutting down when service shuts down instead of client receiving a stack trace of exceptions. What I've tried to do is check if `IHostApplicationLifetime`  `ApplicationStopping.IsCancellationRequested` returns true and then throw an RpcException but that exception never reaches the client side.

I've attached an example Greeter project where I send hello every 10ms and  when I press Ctrl+C on Server side, `GreeterService` if condition triggers but exception does not get sent out to client side.

```
using Greet;
using Grpc.Net.Client;
using System;
using System.Threading;
using System.Threading.Tasks;

using var channel = GrpcChannel.ForAddress("https://localhost:5001");
var client = new Greeter.GreeterClient(channel);

while (true)
{
    try
    {
        var reply = await client.SayHelloAsync(new HelloRequest { Name = "GreeterClient" });
        Console.WriteLine("Greeting: " + reply.Message);
        await Task.Delay(10);
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex);
    }
}
```
```
namespace Server
{
    public class GreeterService : Greeter.GreeterBase
    {
        private readonly ILogger _logger;
        private readonly IHostApplicationLifetime _applicationLifetime;

        public GreeterService(ILoggerFactory loggerFactory, IHostApplicationLifetime applicationLifetime)
        {
            _logger = loggerFactory.CreateLogger<GreeterService>();
            _applicationLifetime = applicationLifetime;
        }

        public override Task<HelloReply> SayHello(HelloRequest request, ServerCallContext context)
        {
            _logger.LogInformation($"Sending hello to {request.Name}");

            if (_applicationLifetime.ApplicationStopping.IsCancellationRequested)
            {
                throw new RpcException(new Status(StatusCode.Internal, "Shutting down..."));
            }

            return Task.FromResult(new HelloReply { Message = "Hello " + request.Name });
        }
    }
}


```
I've also tried to use Interceptors but end up with the same result: exception does not get sent out.

Thank you for your help!

**Comment by JamesNK** [comment]
I believe this doesn't work because once an ASP.NET Core app starts shutting down, it no longer accepts new HTTP requests. One of the things an ASP.NET Core app does while shutting down is completing remain requests, and it can't do that if it keeps accepting new ones.

To achieve what you want I think you would need to add a type that sets its own flag that the server is shutting down soon, and then have a timer that stops the server after the time has elapsed.

**Comment by AidasSin** [comment]
Thank you for your response! :) 

To clarify, we had an issue with a Duplex connection (sorry for the provided unary connection example) and your response gave us an idea:

Create an `ApplicationStoppingService` where we register the `IHostApplicationLifetime` `ApplicationStopping` cancellation token and add a delay in order to send the `RpcException` when `ApplicationStopping` is true:
```
namespace Server.Services
{
    public class ApplicationStoppingService
    {
        public ApplicationStoppingService(IHostApplicationLifetime applicationLifetime)
        {
            applicationLifetime.ApplicationStopping.Register(async () => {
                await Task.Delay(2000);
            });
        }
    }
}
```
`GreeterService`:

```
public override async Task SayHello(HelloRequest request, IServerStreamWriter<HelloReply> responseStream, ServerCallContext context)
        {
            try
            {
                while (!_applicationLifetime.ApplicationStopping.IsCancellationRequested)
                {
                    await responseStream.WriteAsync(new HelloReply { Message = "Hello " + request.Name }, _applicationLifetime.ApplicationStopping);

                    await Task.Delay(1000, _applicationLifetime.ApplicationStopping);
                }
            }

            catch (RpcException ex) when (ex.InnerException is OperationCanceledException)
            {
                throw new RpcException(new Status(StatusCode.Unavailable, "Shutting down..."));
            }

            catch (OperationCanceledException)
            {
                throw new RpcException(new Status(StatusCode.Unavailable, "Shutting down..."));
            }
        }
```

Here is the full example repo for those interested :) https://github.com/AidasSin/graceful-shutdown-Greeter
