### ISSUE TITLE
Grpc Channel with Named Pipe

### ISSUE THREAD

**Issue by joergrossel** [grpc/grpc-dotnet#2350]
According to the documentation on [https://learn.microsoft.com/en-us/aspnet/core/grpc/interprocess-namedpipes?view=aspnetcore-8.0](https://learn.microsoft.com/en-us/aspnet/core/grpc/interprocess-namedpipes?view=aspnetcore-8.0)

It is required to create a SocketsHttpHandler with ConnectCallback provided from the NamedPipesConnectionFactory.

By following this example the application always runs into an InvalidOperationException "Channel is configured with an HTTP transport doesn't support client-side load balancing or connectivity state tracking." thrown in the GrpcChannel class method ValidateHttpHandlerSupportsConnectivity.

Is this specification outdated or how to setup the GrpcChannel correctly to work with Named Pipe on Windows?

**Comment by JamesNK** [comment]
Named pipes can't be combined with some other gRPC functionality (load balancing, calling connect, connection status)

**Comment by JamesNK** [comment]
Improvement to documentation: https://github.com/dotnet/AspNetCore.Docs/pull/31362
