### ISSUE TITLE
Date and times - time zones

### ISSUE THREAD

**Issue by rizi** [grpc/grpc-dotnet#2353]
Hi,
I'm wondering how time zones can be handled with grpc.net, the [documentation ](https://learn.microsoft.com/en-us/aspnet/core/grpc/protobuf?view=aspnetcore-8.0#dates-and-times) states the DateTimeOffset can be used but the offset will always be 0, how does this make sense?

And it seems that regarding grpc.net DateTime and DateTimeOffset  can be used interchangeably, am I right?

Do I have to create my own protobuf message to handle the offset correctly?

br

**Comment by JamesNK** [comment]
Yes, Timestamp is UTC. You'll need to store timezone somewhere else.
