### ISSUE TITLE
Support for DateOnly

### ISSUE THREAD

**Issue by rizi** [grpc/grpc-dotnet#2354]
Hi,

Since .Net 6 DateOnly is available, is there any plan to add support for it in grpc.net?

At the moment we have to use DateTime or DateTimeOffset, but sometimes we only need a date, so it would make the intention more obvious to use DateOnly.

Br

**Comment by JamesNK** [comment]
Do you want helper methods for converting between DateOnly and Timestamp? That code lives at https://github.com/protocolbuffers/protobuf. You should create an issue there.

**Comment by rizi** [comment]
> Do you want helper methods for converting between DateOnly and Timestamp? That code lives at https://github.com/protocolbuffers/protobuf. You should create an issue there.

Yes, helper methods would be helpful, thx for the info, I will create an issue there.
