### ISSUE TITLE
Support keyed services

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#2355]
.NET 8 added keyed services. Ensure DI on interceptors and services work with keyed services.

**Comment by vadimi-ep** [comment]
It looks like keyed services still don't work in gRPC services, is there a plan to support them?

**Comment by JamesNK** [comment]
How don’t they work?

**Comment by JamesNK** [comment]
Closing issue as tests were added here to verify this works - https://github.com/grpc/grpc-dotnet/pull/2356
