### ISSUE TITLE
Does the client-side proxy use Yield? (under what configuration)

### ISSUE THREAD

**Issue by leotohill** [grpc/grpc-dotnet#2360]
I want to use asnyc on the server side, but I cannot on the client side. 

If I define my grpc method as async Task<T>, then of course the interface must declare the method as returning Task<T>.  I'd guess that under this scenario, the client side proxy will use Yield().  But I don't think that I can support that on the client side, because it is .Net Framework 4.8 asp.net mvc. 

Is there any way that on the client side I can call the method with sync/blocking semantics, but on the server side, have async semantics?

**Comment by JamesNK** [comment]
A client that blocks has no impact on the server.

**Comment by leotohill** [comment]
> A client that blocks has no impact on the server.

Of course. But that's not my question.  I'm struggling with a different way to phrase it... it seems like a clear question to me, but apparently it isn't. 

Let me point that a asp.net mvc 4,8 application CANNOT safely call a method that uses Yield (i.e., an async method) and then block while waiting for the result.  In this environment, a reference to resultTask.Result is a blocking call that leads to deadlock.  This problem is described in various sources: references available upon request. :)

Thus my question: does the client side proxy use Yield?  If my method is not defined to return Task<T>, then I know that the proxy  CANNOT be using Yield.   Yield is only available in methods that return Task.  

But if my remote method (and interface) define the result type as Task<T>, then the proxy COULD be using Yield (why not?), providing all that greatness that async provides, on the client side,  All that greatness, except that for the asp.net problem. 

So: is the client side proxy doing a Yield?

**Comment by JamesNK** [comment]
The gRPC client is completely async. Making a gRPC call always involves calling async methods in the client.

There is the concept of blocking unary methods in generated code, but internally they just call an async method and then block.

**Comment by leotohill** [comment]
How can it be async if it doesn’t return a Task? I understand that it may have an asynchronous  implementation within, but it must be blocking my thread until the result is ready, right?Sent from my iPhoneOn Jan 16, 2024, at 10:57 PM, James Newton-King ***@***.***> wrote:﻿
The gRPC client is completely async. Making a gRPC call always involves calling async methods in the client.
There is the concept of blocking unary methods in generated code, but internally they just call an async method and then block.

**Comment by JamesNK** [comment]
https://github.com/grpc/grpc-dotnet/blob/0cad7497d0ad59693956591ebd9bf133eac3e0ee/src/Grpc.Net.Client/Internal/HttpClientCallInvoker.cs#L151-L155

**Comment by leotohill** [comment]
Another aspect of the question is this. Suppose I define my method to return Task<T>. On the client side, when I receive that task object result, do I have a guarantee that IsCompleted is already true? If you can say yes, I’m happy. If no, I will block the thread when accessing the result property, and potentially deadlock Sent from my iPhoneOn Jan 16, 2024, at 10:57 PM, James Newton-King ***@***.***> wrote:﻿
The gRPC client is completely async. Making a gRPC call always involves calling async methods in the client.
There is the concept of blocking unary methods in generated code, but internally they just call an async method and then block.

**Comment by JamesNK** [comment]
> do I have a guarantee that IsCompleted is already true?

No.

**Comment by leotohill** [comment]
Ok, so it DOES block my thread until the call completes. 

`return call.ResponseAsync.GetAwaiter().GetResult(); `

Do you know how this is not susceptible to the deadlock problem? Or... is it?

https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

**Comment by leotohill** [comment]
Yikes! I just realized that I wrote Yield where I meant to write “await”. You must think I’m clueless. Which I might still be, but not as bad as that. Anyway, with correction, my last question remains.. is the code susceptible to deadlock?Sent from my iPhoneOn Jan 16, 2024, at 11:32 PM, James Newton-King ***@***.***> wrote:﻿

do I have a guarantee that IsCompleted is already true?

No.

**Comment by JamesNK** [comment]
Yes it is.

I wouldn't have added that method, but it was a decision made before I was involved.

**Comment by leotohill** [comment]
This is really bad news. Very bad.  I’m learning this very late.Can you think of any workaround?  I’m open to forking the code, temporarily.Sent from my iPhoneOn Jan 17, 2024, at 6:58 PM, James Newton-King ***@***.***> wrote:﻿
Yes it is.
I wouldn't have added that method, but it was a decision made before I was involved.

**Comment by JamesNK** [comment]
No. I'm going to keep repeating this: async is ALWAYS involved when making a gRPC call.

**Comment by leotohill** [comment]
Alright, I think that I will have to workaround this, for the time being, by using background threads, e.g., 

return Task.Run(() => grpc.MyRemoteMethod(parm)).Result;

With worries about the performance impact. 

In case you are interested,  [my SO post](https://stackoverflow.com/questions/77813974/can-a-grpc-net-client-call-a-method-synchronously-but-the-server-handle-it-async/77837249#77837249)
