### ISSUE TITLE
How to handle connection's status in .net standard?

### ISSUE THREAD

**Issue by xandudex** [grpc/grpc-dotnet#2364]
I'm using unity with that package, I'have choosed .net standard. When creating an GrpcChannel there is no way to start a connection, handle it status like in .net 6+, is that a limitation of .net standard? if so, then what kind of trick is more good?
Currently in my connection service i'm creating a stream call to check the connection, that stream is endless until server or client will close it. I'm just not shure if that is correct way, so I will glad to discuss that topic)

**Comment by WeihanLi** [comment]
seemed not supported
https://github.com/grpc/grpc-dotnet/issues/2433#issuecomment-2100481651
