### ISSUE TITLE
Where is the Grpc.StatusProto Nuget Package

### ISSUE THREAD

**Issue by ncipollina** [grpc/grpc-dotnet#2368]
The documentation for Rich Error Handling for gRPC found [here](https://learn.microsoft.com/en-us/aspnet/core/grpc/error-handling?view=aspnetcore-8.0#rich-error-handling) states :

> gRPC on .NET supports a rich error model using the `Grpc.StatusProto` package.

Am I missing something because I cannot find this package on NuGet? This project still appears to be in this repo. Has it not yet been released?

**Comment by JamesNK** [comment]
The doc got merged early. The release with the package will be out soon.

It's accessable on the 3rd party NuGet feed: https://github.com/grpc/grpc-dotnet#grpc-nuget-feed

**Comment by JamesNK** [comment]
@apolcyn When do you expect the next release will be published?

**Comment by apolcyn** [comment]
We should be able to get this out in the next couple of days. Starting the branch cut process in https://github.com/grpc/grpc-dotnet/pull/2370

**Comment by tonydnewell** [comment]
Now released: https://www.nuget.org/packages/Grpc.StatusProto/

**Comment by JamesNK** [comment]
Updated doc: https://github.com/dotnet/AspNetCore.Docs/pull/31809

**Comment by AOne-T** [comment]
But forgot to update `Error` example
