### ISSUE TITLE
Dealing with unknown fields, server-side

### ISSUE THREAD

**Issue by ricsiLT** [grpc/grpc-dotnet#2387]
How does one gain access to unknown fields that were parsed on the server side of things? All docs I've seen only mention this from client side. Is it possible, or planned?

Our use-case is that we distribute our protos via nuget and we don't have visibility into when our clients will update, and sometimes server-side applications are a bit behind, leading to some fields being missed when sent from client and then stored by the server. It'd be nice to at least have a warning about that in the logs.

**Comment by JamesNK** [comment]
I don't know. Those are Protobuf specific questions. I suggest you ask on https://github.com/protocolbuffers/protobuf
