### ISSUE TITLE
Retrieve current resolved server when using pick_first load balancer

### ISSUE THREAD

**Issue by francotiveron** [grpc/grpc-dotnet#2391]
Once I have a working channel with load balancing and resolving multiple addresses with pick first policy, how can I determine which one of the server is currently being used by the load balancer?

Something similar to

```
var address = channel.GetCurrentResolvedAddress();
```

**Comment by JamesNK** [comment]
That feature isn't built into Grpc.Net.Client. You might be able to get this information by implementing a load balancer. You could copy and paste [the pick first balancer](https://github.com/grpc/grpc-dotnet/blob/933023b6f818ec54dfe84e7d31ec50dfe5044c13/src/Grpc.Net.Client/Balancer/PickFirstBalancer.cs) and set the field somewhere that is publicly accessible.
