### ISSUE TITLE
"Trailers-Only" support

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#241]
Consider returning status trailers in the header when there is no response content and headers have not been flushed. C Core does this.

For example:
* Unimplemented service/method
* Empty message
* Empty stream

// https://github.com/dotnet/corefx/issues/37511#issuecomment-491114368

**Comment by codymullins** [comment]
With the latest preview 8 of core and the nightly builds for gRPC (client+server), I'm still getting a "Trailers are not supported for this response" error in the API. It's likely I could be doing something wrong, but wanted to confirm that I'm not crazy since I've spent the last two nights looking at this.

**Comment by JamesNK** [comment]
That error is happening because the required `IHttpResponseTrailerFeature` is not registered with the request.

Kestrel doesn't support TLS on macOS - https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.0#unable-to-start-aspnet-core-grpc-app-on-macos. Have you disabled TLS? I would have expected Kestrel to throw an error if you attempted to start with a port that is HTTP/2 and uses TLS.

I've never seen your error before. If you want you can zip up your solution and drop it here. I can take a look at it.

**Comment by codymullins** [comment]
So - the service works fine in Windows. If I run it in MacOS and don't disable SSL, I get the trailers error response -- nothing regarding SSL support. If I disable https by adding the snippet on that page, there's no error on the server side but the client just indicates the response ended prematurely. 

My first iteration of testing out the normal gRPC library, which did indeed give the explicit SSL error you mentioned...part of why I've been confused.

Here's the code: https://github.com/codymullins/keyboardnavigator/tree/master/ChatServer

**Comment by codymullins** [comment]
Let me take a step back, the second issue I indicated, I've resolved. It was due to not setting the switch in the client library. So at the time, the only confusion is why there was no SSL error and instead the trailers error message on the first attempt when SSL was not disabled.

**Comment by JamesNK** [comment]
I used your code and found the problem. You are not configuring the port to use HTTP2. This should be in the appsettings.json:

```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "Kestrel": {
    "EndpointDefaults": {
      "Protocols": "Http2"
    }
  }
}
```

Or use Program.cs to configure the port to use HTTP2.

gRPC should validate the request is using HTTP/2 to make the problem more obvious. I created an issue - https://github.com/grpc/grpc-dotnet/issues/474

**Comment by 2821840032** [comment]
Thank you. The problem has been solved.
I think there should be a special label here.
To experience this, I need to change my system.
