### ISSUE TITLE
Memory Leak when using ContextPropagationInterceptor

### ISSUE THREAD

**Issue by aputlock** [grpc/grpc-dotnet#2419]
### What version of gRPC and what language are you using?
C#
gRPC codegen compiled with Grpc.Tools 2.40.0
Affected process importing Grpc.AspNetCore 2.50.0

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.net7

### What did you do?
My service implements a server streaming call, which as part of its implementation polls an rpc from another service. We also have ContextPropagationInterceptor added to the pipeline.

Simplified example:

```csharp
public override async Task Stream(StreamRequest request, IServerStreamWriter<StreamResponse> responseStream, ServerCallContext context)
{
    using CancellationTokenSource cts = new CancellationTokenSource();
    while (!context.CancellationToken.IsCancellationRequested)
    {
        // _otherService is a codegen'd grpc client
        var response = await _otherService.GetStateAsync(new GetStateRequest(), new Metadata(), cancellationToken: cts.Token);
        await responseStream.WriteAsync(response, context.CancellationToken);
    }
}
```

### What did you expect to see?
All resources cleaned up

### What did you see instead?
Process memory increases over time -- memory dump + ETW trace indicates there's a leak of Linked2CancellationTokenSource objects (+ associated CallbackRegistration, CallbackNode).

ContextPropagationInterceptor allocates a LinkedCancellationTokenSource and sets it up to be disposed when the containing GrpcCall is disposed. However, it doesn't seem like the call is ever implicitly disposed.

Using unary calls as an example:
https://github.com/grpc/grpc-dotnet/blob/c9c902c8daa54d2bd47a638df6a9d47fc5cae5d7/src/Grpc.AspNetCore.Server.ClientFactory/ContextPropagationInterceptor.cs#L153
https://github.com/grpc/grpc-dotnet/blob/c9c902c8daa54d2bd47a638df6a9d47fc5cae5d7/src/Grpc.AspNetCore.Server.ClientFactory/ContextPropagationInterceptor.cs#L115-L121
https://github.com/grpc/grpc-dotnet/blob/c9c902c8daa54d2bd47a638df6a9d47fc5cae5d7/src/Grpc.AspNetCore.Server.ClientFactory/ContextPropagationInterceptor.cs#L236
https://github.com/grpc/grpc-dotnet/blob/c9c902c8daa54d2bd47a638df6a9d47fc5cae5d7/src/Grpc.AspNetCore.Server.ClientFactory/ContextPropagationInterceptor.cs#L211-L215

I can work around this by adjusting my code, but it doesn't feel expected/ergonomic from a user's perspective:

```csharp
public override async Task Stream(StreamRequest request, IServerStreamWriter<StreamResponse> responseStream, ServerCallContext context)
{
    using CancellationTokenSource cts = new CancellationTokenSource();
    while (!context.CancellationToken.IsCancellationRequested)
    {
        using var unaryCall = _otherService.GetStateAsync(new GetStateRequest(), new Metadata(), cancellationToken: cts.Token);
        var response = await unaryCall;
        await responseStream.WriteAsync(response, context.CancellationToken);
    }
}
```

Particularly considering the comment on AsyncUnaryCall:Dispose:
https://github.com/grpc/grpc-dotnet/blob/c9c902c8daa54d2bd47a638df6a9d47fc5cae5d7/src/Grpc.Core.Api/AsyncUnaryCall.cs#L138-L147

It seems like either AsyncUnaryCall should be automatically disposing its AsyncCallState at some point, or ContextPropagationInterceptor has a faulty assumption that AsyncCallState will be disposed in normal control flow.

**Comment by JamesNK** [comment]
Thanks for the investigation. Fix here: https://github.com/grpc/grpc-dotnet/pull/2421
