### ISSUE TITLE
Question: Is there any event when connection state changed?

### ISSUE THREAD

**Issue by WeihanLi** [grpc/grpc-dotnet#2433]
I want to try to do something when the connection disconnected/reconnected,  is there any event I could use?

and seems the `State` of `GrpcChannel` is not available for `netstandard2.0`, is there some workaround for `netstandard2.0`

**Comment by JamesNK** [comment]
Detecting the connection state isn't supported on netstandard2.0. There isn't a workaround.

**Comment by WeihanLi** [comment]
@JamesNK thanks very much for the quick reply, and any event for the connection state changed? should I monitor the state to track the connection state changes?

**Comment by JamesNK** [comment]
There are no APIs for connection state in netstandard2.0. It's completely unsupported.

**Comment by WeihanLi** [comment]
thanks very much
