### ISSUE TITLE
Correct way to async await within Grpc Service (example needed)

### ISSUE THREAD

**Issue by ronMilne** [grpc/grpc-dotnet#244]
The RPC service is defined as
```csharp
async Task EventFeed(AMessageRequest request,
            IServerStreamWriter<Advisory> responseStream, ServerCallContext context)
```
AMessage is simply used to start the feed. Now within the EventFeed I start pumping messages down the wire. (WriteAsync) now the event feed is sourced from an Orleans Grain, which itself is async.

So my question is, What is the optimal way to await?, as I will never get a message from the client saying please stop so I can't await another message as it's not a client stream. Can you wait async on anything within the context? At present I'm using a manual reset event which is set when Orleans calls OnCompleteAsync which we all know is bad juju.
```csharp
 clientController.ClientTerminationEvent.WaitOne();
```
An example of a client calling a service with a single payload but expecting a stream response (forever or until client termination or server exhausted stream) is what I think I'm needing.

Hope it makes sense
Ron.

**Comment by JamesNK** [comment]
I don't follow.

So you're getting data from Orleans. In a loop wouldn't you wait on incoming data from it to be available, then write it once you have it? If you want the client to cancel then there is a cancellation token you can pass with your call.

Server:

https://github.com/grpc/grpc-dotnet/blob/e822af87b77a81496c531a3c747a18d58c6404b4/examples/Server/Services/Greeter.cs#L41-L57

Client:

https://github.com/grpc/grpc-dotnet/blob/e822af87b77a81496c531a3c747a18d58c6404b4/examples/Clients/Greeter/Program.cs#L54-L71

**Comment by ronMilne** [comment]
I'll try and post a simplified example, but given the above Server/Services/Greeter.cs above, would that simply keep the thread from reentering the pool whilst there is no data to send as it's in a while loop? I think that I need to wait for the OnCompletedAsync (Orleans stream) to be called then do something other than set the ManualResetEvent, all rather confusing lol.

**Comment by ronMilne** [comment]
Argh I think I should use a TaskCompletionSource and call SetResult within the OnAsyncComplete then I can await the task. Also allows for handling of onErrorAsync propagation to the outer task.

**Comment by JamesNK** [comment]
I'm going to close this. I don't think there is a new gRPC sample needed here.
