### ISSUE TITLE
Build fails due to non-latin symbols in windows user name

### ISSUE THREAD

**Issue by papka-Leo** [grpc/grpc-dotnet#2443]
### What version of gRPC and what language are you using?
2.63.0
C#

### What operating system (Linux, Windows,...) and version?
win 10 22H2

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
VS 2022
.NET SDKs installed:
  8.0.300 [C:\Program Files\dotnet\sdk]
Project is build for .net 6.

### What did you do?
After update package Grpc.AspNetCore from version 2.62.0 to 2.63.0 VS build is broken with next exception:
C:\Users\╦хюэшф\AppData\Local\Temp\tmp97132ea392f14706a31ed01c865c020b.rsp
Failed to open argument file	1
because of Cyrillic characters in user name, I think.

### What did you expect to see?
Build completes successfully.

### What did you see instead?
Build fails.

**Comment by papka-Leo** [comment]
Realted issue
https://github.com/grpc/grpc/issues/36518

**Comment by JamesNK** [comment]
The problem is in Grpc.Tools. Please add details to a grpc/grpc repo issue. Grpc.Tools is maintained there.
