### ISSUE TITLE
Support for protobuf version 3.15

### ISSUE THREAD

**Issue by plombaer** [grpc/grpc-dotnet#2450]
Hi,

Apparently protobuf 3.15 support [optional] field. Look helpful for nullable timestamp.
message MyMessage {
  google.protobuf.Timestamp date = 1 [optional];
}
I tried it in a .Net gRPC project but it doesn't compile.
Is it foreseen to be supported ?

**Comment by JamesNK** [comment]
This is a protobuf issue. Please create it here: https://github.com/protocolbuffers/protobuf
