### ISSUE TITLE
ChannelAllocationException: The connection cannot support any more channels. Consider creating a new connection

### ISSUE THREAD

**Issue by shenyang1007** [grpc/grpc-dotnet#2469]
What version of gRPC and what language are you using?
Grpc.AspNetCore.Server (2.62.0)
Grpc.Net.Client(2.62.0)

What operating system (Linux, Windows,...) and version?
windows2029

What runtime / compiler are you using (e.g. .NET Core SDK version dotnet --info)
Net8.0.6
Architecture: x64

Bug desc
This problem occurs when the program runs for about a month and the load becomes high。

Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="Exception was thrown by handler. ChannelAllocationException: The connection cannot support any more channels. Consider creating a new connection")

**Comment by JamesNK** [comment]
That's not a gRPC exception: https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/56b3ebf821dc612fb8fd8e7dfd824c9816170bc0/projects/RabbitMQ.Client/client/exceptions/ChannelAllocationException.cs#L40

**Comment by shenyang1007** [comment]
@JamesNK thanks
