### ISSUE TITLE
provide dotnet standard client

### ISSUE THREAD

**Issue by Groostav** [grpc/grpc-dotnet#248]
> As an amateur dotnet and grpc developer, I would like a small concise and highly portable dotnet client to compile my software against, so that I can build an app that is deployable on most .net instances

My understanding is that the flipside to dotnet core is dotnet standard, which is the common-factor of features between .net core and .net framework.

Can a GRPC-client-only library be created against dotnet standard that 

1. doesn't require me to deploy native libraries and 
2. provides more dotnet idiomatic APIs (read: less state machines, better exceptions, simpler async/await)

I figured that if you are doing a pure C# implementation of the server maybe you'd be willing to be on the hook for a pure C# implementation of a client.

**Comment by JamesNK** [comment]
We're working on one here - https://github.com/grpc/grpc-dotnet/tree/15b1ad163e07087829633961769b17295421c051/src/Grpc.NetCore.HttpClient

It will either target .NET Core 3.0 or netstandard2.1. It depends on whether HttpResponseMessage.TrailingHeaders makes it into .NET Standard - https://github.com/dotnet/standard/issues/1144

**Comment by JunTaoLuo** [comment]
This work is tracked in https://github.com/grpc/grpc-dotnet/issues/43
