### ISSUE TITLE
How to return an EMPTY grpc response using HttpContext only (no framework mapped)

### ISSUE THREAD

**Issue by smaktacular** [grpc/grpc-dotnet#2489]
I would like to construct a valid gRPC Response containing an Empty (from the Wellknown Namespace) message to mimic the behavior of another endpoint without having the gRPC server framework set up. Is there a way to achieve this by only referencing certain gRPC assemblies and putting it to the HttpContext?

For better understanding, I use yarp for forwarding gRPC requests to designated backends, but dependant on state I'd like to return just a response with Status 0 OK containing an empty message to tell the client that everything worked, without forwarding to it the backend.

I already tried the naive approach by just adding headers and serializing the body using CodedOutputStream. The client does not accept this response and Wireshark also shows differences in my faked response and the "original" response.

**Comment by JamesNK** [comment]
There is a gRPC header sent in the response. I suggest you look at the gRPC HTTP/2 spec.

**Comment by smaktacular** [comment]
Looking into the [https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md](spec) I couldn't find anything about a gRPC prefix. The code I've come up with is as follows:

```csharp
            HttpResponse response = httpContext.Response;
            response.ContentType = "application/grpc";
            //httpContext.Response.Headers["request-context"] = "appId=";

            response.StatusCode = 200;
            //data frame
            await response.BodyWriter.WriteAsync(Convert.FromHexString("0000050000000000010000000000"));

            // lacks dataframe
            //Stream bodyWriter = response.BodyWriter.AsStream();
            //new CodedOutputStream(bodyWriter, false).WriteMessage(new Empty());

            response.AppendTrailer("grpc-status", "0");

            return;
        }
``` 

Any hints on how to add the mentioned prefix?

**Comment by smaktacular** [comment]
There is no extension method or similar, like in Asp, like 

```csharp
return GrpcResult.Ok(new Empty())
```

that I have overlooked?

**Comment by JamesNK** [comment]
No
