### ISSUE TITLE
Fuzz testing Google.Protobuf serializer

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#249]

**Comment by JamesNK** [comment]
I started looking into this and discovered the author of SharpFuzz has already fuzz tested Google.Protobuf and linked to an issues he raised in his blog post - https://mijailovic.net/2019/01/03/sharpfuzz/

Issue - https://github.com/protocolbuffers/protobuf/issues/5513

**Comment by JunTaoLuo** [comment]
Fuzz testing has already been done by the community.
