### ISSUE TITLE
Can internal services be called through Http?

### ISSUE THREAD

**Issue by wangdaojun1985** [grpc/grpc-dotnet#2498]
Hi. I always get errors when using Http, but everything works fine when using Https.

For example:
![20240802103447](https://github.com/user-attachments/assets/b2f89829-20a8-4cef-8840-abce00803d6d)

Error info:
![9c1e7fe2-644d-4fcc-b783-9c4ace2b2e47](https://github.com/user-attachments/assets/6d5987ef-d14e-4f77-af58-2e9e7c78d8b0)

**Comment by JamesNK** [comment]
Probably this: https://learn.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-8.0&tabs=visual-studio#protocol-negotiation

**Comment by wangdaojun1985** [comment]
Thanks. It's useful.
I hope my approach can help others.
### First step 
Program.cs
```
builder.WebHost.ConfigureKestrel(options => {
    // Setup a HTTP/2 endpoint without TLS.
    options.ListenLocalhost(58532, o => o.Protocols = HttpProtocols.Http2);
});
```
### Second step 
YourGrpcClient.cs
```
//The client needs to set before creating the grpc call.
AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
var channel = GrpcChannel.ForAddress("http://localhost:58532");  
```
