### ISSUE TITLE
Setting up infrastructure to build and test

### ISSUE THREAD

**Issue by JunTaoLuo** [grpc/grpc-dotnet#25]
cc @jtattermusch can you help us set this up?

**Comment by JunTaoLuo** [comment]
FYI I misspoke about the timeline for the CLA process, we don't have a concrete timeline on when we will get that. In the mean time we'll start writing the code in a fork of this repo.

**Comment by jtattermusch** [comment]
It would help to have a project skeleton to test with (but I understand you can contribute that without a CLA). So should I take a look at the sandbox project and set up testing CI that would fit that project structure?

Also, what do we want at this point?
appveyor
travis
kokoro windows (kokoro is google internal CI)
kokoro mac
kokoro linux

Should we maybe start with kokoro linux and then add more stuff as needed? Or travis?

**Comment by JamesNK** [comment]
This was probably covered before I was involved in the project, but where will specific code live?

Today we have https://github.com/grpc/grpc/tree/master/src/csharp. Will that code move to this repo, or will this repo only be for `Grpc.AspNetCore`?

**Comment by JunTaoLuo** [comment]
I'll start structuring the code in GrpcSandbox to the expected package hierarchy so we can have something to build. As to Kokoro vs Travis, I'm okay with starting with either though I assume Travis would be more visible to us externally?

**Comment by jtattermusch** [comment]
I added the basic config for Travis linux https://github.com/grpc/grpc-dotnet/pull/26. Currently it only runs an empty shell script.

**Comment by jtattermusch** [comment]
What environment are we going to use to test this? I assume it's going to be some prerelease version of aspnetcore (as we want to target aspnetcore 3.x). What unit test framework are we going to use?
(just FYI, native Grpc and Google.Protobuf use NUnit)

**Comment by JamesNK** [comment]
We will need .NET Core 3.0 preview 1 for now - https://dotnet.microsoft.com/download/dotnet-core/3.0. We'll need to update to preview 2 when it comes out. After that we can probably stick with preview 2 until close to .NET Core RTM.

We use xunit in www.github.com/aspnet but since you use NUnit for other Grpc projects we can stick with it to be consistent.

**Comment by JunTaoLuo** [comment]
I think we have this mostly set up now and the changes are in.

**Comment by JunTaoLuo** [comment]
I don't think there's any action items left here. We have builds and tests running on Travis now.
