### ISSUE TITLE
Issues with client certificate

### ISSUE THREAD

**Issue by lean-bristleback** [grpc/grpc-dotnet#251]
Two issues:
1. When running an example project (/examples/Clients/Greeter/) on Windows and using a client certificate for authentication, the context.GetHttpContext().Connection.ClientCertificate property is still null. 
2. When setting HttpsConnectionAdapterOptions.ClientCertificateMode to ClientCertificateMode.RequireCertificate, the client fails to establish connection ("Error: HTTP/2 over TLS was not negotiated on an HTTP/2-only endpoint").

**Comment by JamesNK** [comment]
In preview 6 there is a new gRPC client that uses HttpClient internally.

I have added a example of sending a client certificate with gRPC calls and using them on the server. It is available here - https://github.com/grpc/grpc-dotnet/pull/306
