### ISSUE TITLE
Why gRPC-Web Support http and Documentation use https？

### ISSUE THREAD

**Issue by RainySeason673** [grpc/grpc-dotnet#2534]
Since gRPC-Web support HTTP/1.1, why Documentation demo use https for gRPC server address？Can the server's address use http？
reference : [here](https://learn.microsoft.com/en-us/aspnet/core/grpc/grpcweb?view=aspnetcore-8.0#configure-grpc-web-with-the-net-grpc-client)

![image](https://github.com/user-attachments/assets/38314d14-4de9-4fbe-b175-ae89043e593d)

**Comment by JamesNK** [comment]
YEs
