### ISSUE TITLE
HttpContextServerCallContext:RequestHeadersCore is not threadsafe

### ISSUE THREAD

**Issue by aputlock** [grpc/grpc-dotnet#2538]
### What version of gRPC and what language are you using?
C#

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.net6
Grpc.AspNetCore 2.50.0

### What did you do?

Simplified example:

```csharp
public override async Task<DoSomethingResponse> DoSomething(DoSomethingRequest request, ServerCallContext context)
{
   var tasks = new List<Task>();
   for (int i = 0; i < 10; i++)
      tasks.Add(_otherClient.DoSomethingElseAsync(new DoSomethingElseRequest(), headers: context.RequestHeaders).ResponseAsync);
   await Task.WhenAll(tasks);
   return new DoSomethingResponse();
}
```

### What did you expect to see?
RequestHeaders from the parent request are successfully passed along to the child requests.

### What did you see instead?

Headers are inconsistently forwarded to the child requests.

Looking at the source, it looks like HttpContextServerCallContext:RequestHeadersCore is not threadsafe:
https://github.com/grpc/grpc-dotnet/blob/b1df3e4c76792212a0401e1ae17114867fd6663b/src/Grpc.AspNetCore.Server/Internal/HttpContextServerCallContext.cs#L110-L138

I suspect what happened was:
1) Thread 1 looks for headers, sees it's null and executes line 116
2) Thread 2 looks for headers, sees it's not null and immediately returns
3) Thread 2 makes downstream request with unpopulated Metadata object
4) Thread 1 populates Metadata object, makes downstream request with populated object

I think this would be fixed by simply storing the metadata object in a local variable until it's fully populated and only assigning the instance variable once it's ready. This does mean that we may end up doing duplicate work to process the headers, but guarantees that no caller will move on with an incomplete object.

**Comment by JamesNK** [comment]
Hmm, generally I would say that `ServerCallContext` is like `HttpContext`: they're not designed to be thread safe.

But in this case, since you're only reading from the context, we should try to make that safer if it is low impact.

**Comment by aputlock** [comment]
Looking closer, I now see that `HttpContext` has exactly the [same](https://github.com/microsoft/referencesource/blob/51cf7850defa8a17d815b4700b67116e3fa283c2/System.Web/HttpRequest.cs#L2246) behavior when accessing the request headers, which would mean my suggested solution above would be subject to the same issue, just at a different layer.

It's easy enough to update our code to read request headers before spawning child tasks, so I'm happy enough if you'd like to close this without action. Sorry for the noise!
