### ISSUE TITLE
Where are all the Grpc.StatusProto versions?

### ISSUE THREAD

**Issue by leidegre** [grpc/grpc-dotnet#2549]
Getting warnings in my build that some Grpc.StatusProto versions cannot be found, looks like it only goes back to 2.61.0 what's going on?

https://www.nuget.org/packages/Grpc.StatusProto/

Getting warnings like these,

    warning NU1603: ... depends on Grpc.StatusProto (>= 2.59.0) but Grpc.StatusProto 2.59.0 was not found. An approximate best match of Grpc.StatusProto 2.61.0 was resolved.

**Comment by leidegre** [comment]
If I try to hack the NuGet URL I get this error and this page

![image](https://github.com/user-attachments/assets/d621cae3-1737-4be1-8158-edd4d0642b83)

**Comment by JamesNK** [comment]
What is referencing Grpc.StatusProto?

**Comment by leidegre** [comment]
Ah, okay. It's that recent. I reference all these packages with a common
config. So we use the same version of all grpc packages.

Hadn't seen this warning before. All good.
