### ISSUE TITLE
Health check and other ASP.NET core ecosystem integration

### ISSUE THREAD

**Issue by hacst** [grpc/grpc-dotnet#255]
The readme mentions
> Good integration with the rest of the ASP.NET Core ecosystem

As a goal of the project.

I was wondering how deep that integration will go. E.g. the ASP.NET core world has elaborate APIs for [health checking](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-3.0). Will those be somehow integrated with the [gRPC notion of those](https://github.com/grpc/grpc/blob/master/doc/health-checking.md) and just work?

Similarily there are things like the [application insights SDK/OpenCencus](https://docs.microsoft.com/bs-latn-ba/azure/azure-monitor/app/distributed-tracing?view=azure-cli-latest) that add distributed tracing to ASP.NET core applications. Is the goal to have those just interoperate with grpc-dotnet or will this require special work by the library and/or its users?

**Comment by JamesNK** [comment]
> Will those be somehow integrated with the gRPC notion of those  and just work?

You can use ASP.NET Core's healthchecks alongside a gRPC service. If you want you could copy that proto file into your app and have it call into ASP.NET's HealthCheckService.

**Comment by JamesNK** [comment]
We will likely have automatic propagation of tracing by integrating with HttpClientFactory. Tracing is something we want but isn't an area we have focused on yet.

**Comment by hacst** [comment]
I guess it should be easy enough to wire the health-checks up internally if that isn't shipped out of the box.

Great to hear tracing is in scope for the project and that the goal is for it to be automatic. With initiatives like https://opentelemetry.io/ this should hopefully make it very easy to make it work cross language and ecosystems.

Thanks for the information.
