### ISSUE TITLE
Any known issues regarding macOS+ gRPC Client?

### ISSUE THREAD

**Issue by alexandercarls** [grpc/grpc-dotnet#256]
With the latest preview5 codegen no longer works when adding the gRPC client manually as described in the docs. I couldn't pinpoint the exact errors and can't reliably reproduce them, as sometimes I can get the codegen for client working but not the server one or the other way around. Each project has the same proto file copied to the project (replicated the templates/docs)

It worked with preview3 where the client was created as part of the template, i.e. before the MSBuild design time compilation.

Occasionally I get the following error:

```
  Google.Protobuf.Tools.targets(355, 5): [MSB4062] The "Grpc.Tools.ProtoCompilerOutputs" task could not be loaded from the assembly /Users/alexandercarls/.nuget/packages/grpc.tools/1.20.0-pre3/build/_protobuf/netstandard1.3/Protobuf.MSBuild.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
```

**Comment by JamesNK** [comment]
Hi

`Grpc.Tools` is responsible for code generation and it is maintained at https://github.com/grpc/grpc. Please raise your issue there.
