### ISSUE TITLE
incompatible with 'all' frameworks in version 2.67.0

### ISSUE THREAD

**Issue by debuggedme** [grpc/grpc-dotnet#2577]
### What version of gRPC and what language are you using?

2.67.0

### What operating system (Linux, Windows,...) and version?

```
Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /root/.dotnet/sdk/9.0.100/
```

via dotnet --info 

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)

```
.NET SDK:
 Version:           9.0.100
 Commit:            59db016f11
 Workload version:  9.0.100-manifests.3068a692
 MSBuild version:   17.12.7+5b8665660
```

via dotnet --info 

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

```
rm -rf demo
dotnet new console -o demo 
dotnet add package Grpc.AspNetCore -v 2.67.0
```

### What did you expect to see?

```
info : PackageReference for package 'Grpc.AspNetCore' version '2.66.0' added to file '/root/demo/demo.csproj'.
```

### What did you see instead?

```
error: Package 'Grpc.AspNetCore' is incompatible with 'all' frameworks in project '/root/demo/demo.csproj'.
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc-dotnet/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by JamesNK** [comment]
It worked for me:

![image](https://github.com/user-attachments/assets/1ebf9bae-c5d2-42bc-b2f2-c7abe03534ff)

**Comment by debuggedme** [comment]
which dotnet version are you using?

**Comment by JamesNK** [comment]
A preview version of 9.0:
```
.NET SDK:
 Version:           9.0.200-preview.0.24529.19
 Commit:            3980fbc52d
 Workload version:  9.0.200-manifests.c6f19616
 MSBuild version:   17.13.0-preview-24529-12+ee511a938
```

**Comment by debuggedme** [comment]
deleting the nuget.config with private repositories and clearing the nuget local cache resolved the issue.
