### ISSUE TITLE
Callt to Channel.ConnectAsync() hangs

### ISSUE THREAD

**Issue by fatichar** [grpc/grpc-dotnet#277]
In my web service, I need to check whether a gRPC server (which runs on a device) is reachable. I am using the following code:
```
    private async Task<bool> IsUnresponsiveAsync(Device device)
    {
      try
      {
        Channel channel = new Channel(GetEndPoint(device), ChannelCredentials.Insecure);
        await channel.ConnectAsync(DateTime.Now.AddSeconds(2));

        var responsive = channel.State == ChannelState.Ready;
        await channel.ShutdownAsync();
        return !responsive;
      }
      catch (RpcException e)
      {
        Logger.LogError($"Failed to check reachability of device {device} with endpoint {GetEndPoint(device)}. Exception: {e}");
        return true;
      }
    }
```
The ConnectAsync() call does not return. There is no issue with the endpoint, as I am able to make rpc calls using the same channel. But rpc calls also hang when a deadline is specified.

**Comment by JamesNK** [comment]
Hi

Preview 6 has just been released - https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-6/. New in this release is a managed gRPC client: `Grpc.Net.Client`. It doesn't have a `Channel`, but you could consider using it.

If you want to use the `Grpc.Core` client you should raise issues related to it at https://github.com/grpc/grpc
