### ISSUE TITLE
determine code style to use for Grpc.AspNetCore

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc-dotnet#28]
Grpc.Core currently has code style that's different from AspNetCore code style. What code style do we use for Grpc.AspNetCore? 

Node: Grpc.Core currently doesn't have an automatic code style enforcement in place (we used to use StyleCop, but that's probably out of date now), so this might be an opportunity to adopt code style and enforcement tooling from AspNetCore.

**Comment by JunTaoLuo** [comment]
https://github.com/aspnet/AspNetCore/wiki/Engineering-guidelines#coding-guidelines is what we strive to follow. Along the same lines. I'm also curious if we should apply the same principles to the generated GRPC code. The style of the generated code looks unconventional and I think users who F12 on the base class may end up seeing that code so we might want to clean it up.

**Comment by chwarr** [comment]
> I'm also curious if we should apply the same principles to the generated GRPC code. The style of the generated code looks unconventional and I think users who F12 on the base class may end up seeing that code so we might want to clean it up.

Were I you, I'd only put a minimal amount of work into something like this. The amount of engineering work to make generated code look like something a human wrote is large, and the benefits fall off very quickly.

E.g., structuring generated code to have vacuous conditions makes generation easier:

```scheme
'(and true ,@(map pred->csharp conditions))
```

Style-enforcement tools have ways to ignore generated code. If they don't that's a feature to contribute.

On top of that, the amount of generated code that gets checked in should be minimal. F12 works on generated files already. Source embedding in PDBs solves makes the generated code available during debugging.

**Comment by JunTaoLuo** [comment]
Absolutely, generated code is a secondary concern, since it's not intended to be seen by humans. We are also looking into bypassing the generated code via the F12 experience which will take you directly to the proto file, but this is still up in the air.
