### ISSUE TITLE
Build failed on MacOS with C#

### ISSUE THREAD

**Issue by vinaychandra** [grpc/grpc-dotnet#295]
### What version of gRPC and what language are you using?

Language: `C#`

`Google.Protobuf`: 3.8.0
`Grpc.Tools`: 1.21.0
 
### What operating system (Linux, Windows,...) and version?
 `OSX 10.14.5`
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 `dotnet 3.0.100-preview5-011568`
 
### What did you do?
Built a proto file using the C# command
`<Protobuf Include="file.proto" Link="targetFile.proto" GrpcServices="Server" />`

Build the solution
 
### What did you expect to see?
 
Build succeeds.
 
### What did you see instead?
```
obj/Debug/netcoreapp3.0/ServiceGrpc.cs(42,12,42,29): error CS0234: The type or namespace name 'BindServiceMethodAttribute' does not exist in the namespace 'Grpc.Core' (are you missing an assembly reference?)
obj/Debug/netcoreapp3.0/ServiceGrpc.cs(42,12,42,29): error CS0234: The type or namespace name 'BindServiceMethod' does not exist in the namespace 'Grpc.Core' (are you missing an assembly reference?)
```

### Anything else we should know about your project / environment?

The same code builds if `Grpc.Tools` nuget version is `1.20.0`

**Comment by JunTaoLuo** [comment]
Yup this is because Grpc.AspNetCore.Server needed an update. I'll close this for now since the issue should be resolved. If it is not, please ping this issue again or create a new one.
