### ISSUE TITLE
Documentation for Grpc.Net.Client and associated ClientFactory APIs

### ISSUE THREAD

**Issue by JunTaoLuo** [grpc/grpc-dotnet#296]
Add more docs to docs.asp.net!

**Comment by JamesNK** [comment]
There are multiple examples that use the gRPC client factory. I'm going to close this as done.

We can look at adding tutorials with the client factory closer to 3.0.

**Comment by khteh** [comment]
Any update?

**Comment by JamesNK** [comment]
https://docs.microsoft.com/en-us/aspnet/core/grpc/client?view=aspnetcore-3.0

https://docs.microsoft.com/en-us/aspnet/core/grpc/clientfactory?view=aspnetcore-3.0

If you want docs then look on docs.microsoft.com
