### ISSUE TITLE
Client template

### ISSUE THREAD

**Issue by JunTaoLuo** [grpc/grpc-dotnet#302]
I think we should add a template for gRPC client that uses the new Grpc.Net.Client. Also, since https should just work, we can change the default url of the server template: https://github.com/aspnet/AspNetCore/blob/master/src/ProjectTemplates/Web.ProjectTemplates/content/GrpcService-CSharp/Properties/launchSettings.json#L6

cc @JamesNK @shirhatti.

**Comment by shirhatti** [comment]
We're screwed on OS X. Need to figure out what to do there.
No server-side ALPN implies no way to do HTTP/2 over TLS.
