### ISSUE TITLE
Allow use Grpc.AspNetCore.Server.ClientFactory in non-Grpc request

### ISSUE THREAD

**Issue by pengweiqhca** [grpc/grpc-dotnet#309]
Allow use Grpc.AspNetCore.Server.ClientFactory in background worker https://github.com/grpc/grpc-dotnet/blob/master/src/Grpc.AspNetCore.Server.ClientFactory/GrpcServerHttpClientBuilderExtensions.cs#L59
and allow use Grpc.AspNetCore.Server.ClientFactory in Asp.net core general reqeust https://github.com/grpc/grpc-dotnet/blob/master/src/Grpc.AspNetCore.Server.ClientFactory/GrpcServerHttpClientBuilderExtensions.cs#L65

**Comment by JunTaoLuo** [comment]
Marking this as done since https://github.com/grpc/grpc-dotnet/pull/308 is merged. Thanks!
