### ISSUE TITLE
Tracing

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#318]
Investigate tracing with gRPC, particularly OpenCensus.

**Comment by JamesNK** [comment]
SO!

Talking with @davidfowl and the tracing groundwork has been done for us in ASP.NET Core and HttpClient. By using those we get tracing for free.

I experimented hooking up OpenTelemetrySDK - https://github.com/open-telemetry/opentelemetry-dotnet - and exporting to Zipkin and got promising results:

![image](https://user-images.githubusercontent.com/303201/59488134-cae82a80-8ed2-11e9-9e0e-f60685941a6d.png)

![image](https://user-images.githubusercontent.com/303201/59488148-d6d3ec80-8ed2-11e9-9969-83b5ba696b73.png)

Source: https://github.com/JamesNK/grpc-dotnet/commit/9831bfb2d7a9b56be3c2c9e4361140b75790e926

**Comment by JamesNK** [comment]
I think perhaps the only remaining work here is potentially adding gRPC specific metadata to these events. For example, gRPC requests will always return 200 OK. Can we include grpc-status in these results?

**Comment by JamesNK** [comment]
I don't believe there are any product changes required here.

In the future we could add docs/examples for tracing.

**Comment by davidfowl** [comment]
If it is warranted, we could add more diagnostic listener events for GRPC invocations that may contain more information (like service name and method name and grpc status for the response).

**Comment by davidfowl** [comment]
I think there's some value in doing this for both GRPC and Signal
