### ISSUE TITLE
Test that basic interoperability tests are passing

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc-dotnet#32]
To ensure gRPC works well cross-language, we have a set of test cases that need to pass when ran against other gRPC implementations.

https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md

For "basic RPC support" (originally required for "alpha" version level of gRPC) these tests need to pass:
- [x] empty_unary
- [x] large_unary
- [x] client_streaming
- [x] server_streaming
- [x] ping_pong
- [x] empty_stream

A more "advanced RPC support" (still necessary for the library to be useful) - mostly things like timeouts, cancellation, RPC metadata...

- [x] custom_metadata
- [x] status_code_and_message
- [ ] special_status_message
- [x] unimplemented_method
- [x] unimplemented_service
- [x] cancel_after_begin
- [x] cancel_after_first_response
- [x] timeout_on_sleeping_server

The test need to also with both secure insecure connections.
on grpc/grpc repository we have a test framework that can run these interop tests cross-language once they are implemented.

There is also a bunch of "auth" tests, but those are client-side only (so not a requirement for server-side AspNetCore support).

**Comment by jtattermusch** [comment]
Some initial results are here:

Most test against aspnetcore server are actually passing:
https://source.cloud.google.com/results/invocations/89f6c1c8-4183-44c3-9dd9-5dba629d4d1e/targets/github%2Fgrpc%2Finterop_test/tests;query=aspnetcore;failed=false;passed=true;group=tests;test=cloud_to_cloud:node:aspnetcore_server:large_unary:tls;row=4

There are still a few failures:
https://source.cloud.google.com/results/invocations/89f6c1c8-4183-44c3-9dd9-5dba629d4d1e/targets/github%2Fgrpc%2Finterop_test/tests;query=aspnetcore;group=tests;test=cloud_to_cloud:node:aspnetcore_server:large_unary:tls;row=4
(filed https://github.com/grpc/grpc-dotnet/issues/101)

**Comment by jtattermusch** [comment]
As of https://github.com/grpc/grpc/pull/18070, interop tests are now running on grpc/grpc repo continuously.

**Comment by JamesNK** [comment]
Great. What is the link to view the test run history?

**Comment by jtattermusch** [comment]
The only remaining basic test is `special_status_message`, I created an issue to track separately:
https://github.com/grpc/grpc-dotnet/issues/161
