### ISSUE TITLE
Comparison to native grpc client

### ISSUE THREAD

**Issue by YairHalberstadt** [grpc/grpc-dotnet#323]
We currently use https://github.com/grpc/grpc in production, and are watching this project with interest.

In order to know whether we should look into moving our existing GRPC clients/servers to this implementation once it becomes production ready, we need to know more about how the two differ.

Would you be able to provide a comparison between the two implementations on your readme? When would you recommend one over the other?

Thank you very much!

**Comment by JamesNK** [comment]
The new client doesn't support compression of gRPC messages (it does support overall HTTP compression) and it doesn't have `Channel`. Other than that they are equivalent. This should change over the next couple of months.

This is the very first release of the client so keep in mind that it hasn't been tested nearly as much as the Grpc.Core client.

**Comment by YairHalberstadt** [comment]
Thanks

So at the moment, there's not much reason to use the new client over the old, but that may change?

**Comment by JamesNK** [comment]
HttpClient makes it easier to call gRPC over HTTPS. HttpClient supports a pipeline of HttpMessageHandlers. HttpClient is fully managed code, while Grpc.Core has native dependencies that only work on some platforms.
