### ISSUE TITLE
Consider removing the CRTP signature from GrpcClient

### ISSUE THREAD

**Issue by mgravell** [grpc/grpc-dotnet#325]
The current API on `GrpcClient` is:

``` c#
public static TClient Create<TClient>(HttpClient httpClient, ILoggerFactory? loggerFactory = null)
    where TClient : ClientBase<TClient>
```

It is true that the google-generated types implement the CRTP, but it is not actually required here, and it **significantly** complicates implementation of runtime-generated client types (code-first etc). All that is *actually required* here is `TClient : ClientBase`. I have prototyped with this constraint removed, and everything works fine, i.e.

``` c#
public static TClient Create<TClient>(HttpClient httpClient, ILoggerFactory? loggerFactory = null)
    where TClient : ClientBase
```

Removing this allows me to generate much simpler proxies, i.e.

``` c#
internal sealed class FooProxy : ClientBase, IFoo
```

instead of

``` c#
internal sealed class FooProxy : ClientBase<FooProxy>, IFoo
```

(with the other pieces that I need, obviously), and then with this CRTP constraint removed, I can just use the existing `GrpcClient.Create<FooProxy>(httpClient, loggerFactory);` to actually create instances. Tested, etc - it all works.

So: please consider removing this constraint; happy to submit a PR.

**Comment by JamesNK** [comment]
We're already planning to change it to "class". See https://github.com/grpc/grpc-dotnet/pull/311

**Comment by mgravell** [comment]
ah, even better - I'll be interested in looking into this "LiteClient" - it might be suitable for my scenario too, but I suspect I can make `ClientBase` work. I assume that either way, it'll need the same .ctor pattern?

Incidentally, I would recommend making the error more obvious and clear if someone *doesn't* meet the current requirements - IIRC, if you give it an incorrect type at the moment (even with the CRTP constraint), the error is obtuse.

**Comment by JamesNK** [comment]
The PR adds an error message at https://github.com/grpc/grpc-dotnet/pull/311/files#diff-de9fc0e19acbd6f64ed16718b2e7f3b9R56

Improvements to the message welcome.

**Comment by mgravell** [comment]
Well, it doesn't actually tell you the right thing IMO.

1. It isn't actually demanding either of those two base classes
2. Something could subclass either of those and still lack the constructor

Putting those together: you could follow the advice of the error message, and it wouldn't change the error / message. IMO it should:

1. Be explicit about the constructor it wants
2. Either actually assert those base classes, or soften the wording on mentioning those to be a suggestion

Perhaps:

> "... Is missing the required constructor taking a CallInvoker argument, typically by subclassing ClientBase or WhateverOtherBase"

?

**Comment by JamesNK** [comment]
https://github.com/grpc/grpc-dotnet/pull/311/files#r294019951

**Comment by JamesNK** [comment]
DONE

**Comment by mgravell** [comment]
Awesome. Just for my planning: is there an ETA on when the next drop is likely to be? (if you can't say, that's fine too - I'll just keep an eye on it)

**Comment by shirhatti** [comment]
Mid-July on NuGet. `https://grpc.jfrog.io/grpc/api/nuget/v3/grpc-nuget-dev` has drops everyday
