### ISSUE TITLE
Possibility of client factory provider api

### ISSUE THREAD

**Issue by mgravell** [grpc/grpc-dotnet#332]
There's a new factory provider API for server, which is great - but for client, the current API is pretty crude: "ask for a type that has the right constructor".

Is there scope to explore a similar factory provider API for clients, so that the existing `<T>` method could be used with abstract classes or interfaces **or** "types with the right constructor", and multiple providers get an opportunity to claim the type?

Not sure exactly what it would look like, although I suppose it is quite similar to the server simile. Mostly just asking the question here.

**Comment by JamesNK** [comment]
You really need DI to support injecting a factory. Fortunately we have something like that already: Grpc.Net.ClientFactory

Example of it being used: https://github.com/grpc/grpc-dotnet/tree/31f7a5f63f49821cf9d80ec1070d94809d158a30/examples/Clients/Worker

I think you will end up implementing https://github.com/grpc/grpc-dotnet/blob/31f7a5f63f49821cf9d80ec1070d94809d158a30/src/Grpc.Net.ClientFactory/GrpcClientFactory.cs

**Comment by mgravell** [comment]
Seems legit. I'll add to my list of things to investigate, thanks.

**Comment by JamesNK** [comment]
I'm going to close this until there is a more concrete feature request.
