### ISSUE TITLE
Please un-seal HttpClientCallInvoker

### ISSUE THREAD

**Issue by mgravell** [grpc/grpc-dotnet#337]
Reason: optimization

Use-case: I am generating proxies at runtime with full knowledge of the intended services. At the moment I need to use something very similar to `LiteClientBase`, with it doing the usual `this.CallInvoker` dance to invoke methods.

However, if `HttpClientBase` was un-sealed, I could use *it* as the base-class for my generated proxies (when using `HttpClient`), so I emit:

``` c#
class Foo : HttpClientCallInvoker, IMyService
{...}
```

And whenever I would have used `this.CallInvoker` I just emit `this`.

As a result, I only need half as many allocations per proxy instance.

**Comment by mgravell** [comment]
For comparison: `DefaultCallInvoker` (the `Channel` version) is not `sealed`

**Comment by JamesNK** [comment]
I think unsealing it would be a decision on if it makes sense from an API design perspective. One extra allocation isn't much in the grand scheme of things.

**Comment by mgravell** [comment]
(pouts)

k, I *guess* it isn't a biggie; it just seemed like a nice opportunity to dodge an alloc
