### ISSUE TITLE
Publish a version of Grpc.HealthCheck which is compatible with Grpc.AspnetCore

### ISSUE THREAD

**Issue by csteegz** [grpc/grpc-dotnet#338]
It would be nice to have a version of [Grpc.HealthCheck](https://www.nuget.org/packages/Grpc.HealthCheck/) which is compatible with Grpc.AspNetCore. 

Having the HealthCheck available as a nuget package makes it easier to consume.

**Comment by JamesNK** [comment]
How is it not compatible? If you register it as a singleton then it should work.

**Comment by csteegz** [comment]
Sure - but a version of the package that doesn't depend on Grpc.Core would be nice to have, especially with the HTTPClient based client.  

It seems like the code only depends on Grpc.Core.API (although I might be unclear on the Client/LiteClientBase split) and there could be meta-packages for it with Grpc.Core and Grpc.AspNetCore.

**Comment by JamesNK** [comment]
It contains a client so it depends on ClientBase and Grpc.Core.

Use can use the service with Grpc.AspNetCore.Server and the client with the HttpClient gRPC client without running any native code. The only downside is having a Grpc.Core dependency.

**Comment by JamesNK** [comment]
Version 2.23.0 and later of Grpc.HealthCheck no longer depends on Grpc.Core

https://www.nuget.org/packages/Grpc.HealthCheck/2.23.0-pre1
