### ISSUE TITLE
Question: How do you handle exceptions

### ISSUE THREAD

**Issue by buehler** [grpc/grpc-dotnet#340]
Hey @JamesNK 

I've got another question, that you might be able to enlighten me :-)

When using Grpc services, how is it intended to handle exceptions? How can I modify the returned status code?

When I throw any exception, the statuscode "internal" is used and the server closes the stream without sending trailers. This also happens when I throw an exception of the type RpcException (`throw new RpcException(new Status(StatusCode.InvalidArgument, exception.ToString()));`)

How can I react to those exceptions thrown by my business logic? I.E. change the statuscode to something else than Internal.

```csharp
/// <inheritdoc/>
public override async Task<Favorite> CreateFavorite(CreateFavoriteRequest request, ServerCallContext context)
{
    var (userId, tenantId) = context.GetAuthIds();
    return (await _favorites.CreateFavorite(userId, tenantId, request.TemplateId)).ToGrpcModel();
}
```

When I throw exceptions that are not catched, is it possible to register any "global" exception handler like with asp.net?

Cheers and thanks for your time
Chris

**Comment by JamesNK** [comment]
I get the status and message from the server in the exception thrown by the client.

```cs
public override Task<HelloReply> SayHello(HelloRequest request, ServerCallContext context)
{
    throw new RpcException(new Status(StatusCode.NotFound, "Not founsd!"));
}
```

Client:

```
Unhandled exception. Grpc.Core.RpcException: Status(StatusCode=NotFound, Detail="Not found")
   at Grpc.Net.Client.Internal.GrpcCall`2.FinishResponse() in C:\Development\Source\grpc-dotnet\src\Grpc.Net.Client\Internal\GrpcCall.cs:line 241
   at Grpc.Net.Client.Internal.GrpcCall`2.GetResponseAsync() in C:\Development\Source\grpc-dotnet\src\Grpc.Net.Client\Internal\GrpcCall.cs:line 301
   at Sample.Clients.Program.UnaryCallExample(GreeterClient client) in C:\Development\Source\grpc-dotnet\examples\Clients\Greeter\Program.cs:line 47
   at Sample.Clients.Program.Main(String[] args) in C:\Development\Source\grpc-dotnet\examples\Clients\Greeter\Program.cs:line 36
   at Sample.Clients.Program.<Main>(String[] args)
```

**Comment by buehler** [comment]
Well this works if you use the .net client. But what about general exceptions?
Since I updated to the newest preview, the correct status is returned.

Is there any chance for a global exception handler that can handle "unhandled exceptions"?

**Comment by JamesNK** [comment]
What do you mean by handle? Exceptions are already logged. What else do you want to do when an exception is thrown.

If you want to recover from an exception then writing a custom interceptor is probably the best option.

**Comment by buehler** [comment]
The recover part was what I was looking for. Thanks for the hint, I'm looking into it.
