### ISSUE TITLE
Add Integration tests

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#343]
Today all our testing is unit tests and functional tests (gRPC in TestServer).

I think we need functional tests that spin up Kestrel and are called via HttpClient. The interop tests do this but they don't cover many scenarios.

**Comment by mcalvinsf** [comment]
@JamesNK  Question - I am relatively new to grpc-dotnet and am looking for some good examples of how to use TestServer in my application development. They are hard to find. Can you point me to any examples or docs ? The MSFT stuff on integration testing seems really MVC focued still.

**Comment by ghstahl** [comment]
@mcalvinsf calling grpc services is exactly the same process as to how you would call an HTTP rest endpoint.  Pass in a **GrpcChannelOptions** to **GrpcChannel.ForAddress** where you tell the **grpcChannel** to use the HttpClient given to you by TestServer.

```
[Fact]
public async void success_SayHello()
{
    GrpcChannelOptions options = new GrpcChannelOptions()
    {
        HttpClient = _fixture.Client
    };
    var channel = GrpcChannel.ForAddress("http://localhost", options);
    var greeterClient = new Greeter.GreeterClient(channel);

    var reply = await greeterClient.SayHelloAsync(
                        new HelloRequest { Name = "GreeterClient" });
    reply.Message.Should().Equals("GreeterClient");
} 
```

This project has a working TestServer based XUnitTest
[gRPC-dotnetcore-play](https://github.com/P7CoreOrg/gRPC-dotnetcore-play)
