### ISSUE TITLE
API unification proposal : service on server-context

### ISSUE THREAD

**Issue by mgravell** [grpc/grpc-dotnet#345]
The base Grpc.Core.Api bindings are:

- `UnaryServerMethod<TRequest, TResponse>`,
- `ClientStreamingServerMethod<TRequest, TResponse>`
- `ServerStreamingServerMethod<TRequest, TResponse>`
- `DuplexStreamingServerMethod<TRequest, TResponse>`

which is based around the expectation of binding to (for example):

``` c#
(data, ctx) => someInstance.SomeMethod(data, ctx)
```

Presumably for reasons of service-instance lifetime management, the `Grpc.AspNetCore.Server` bindings work differently, demanding the `TServer` as the first parameter:

- `UnaryServerMethod<TService, TRequest, TResponse>`
- `ClientStreamingServerMethod<TService, TRequest, TResponse>`
- `ServerStreamingServerMethod<TService, TRequest, TResponse>`
- `DuplexStreamingServerMethod<TService, TRequest, TResponse>`

binding to (for example)

``` c#
(svc, data, ctx) => svc.SomeMethod(data, ctx)
```

This *works*, but the implementation demands lots of extra work and complexity (especially for folks like me!). But; I wonder if there's a better option.

That's the context, now the actual idea:

---

1. add the service to some interface - perhaps `IServerCallContextFeature`
2. pass the actual service instance to `HttpContextServerCallContext` (which *implements* the interface from 1)
3. perhaps add a helper extension method along the lines of:

``` c#
[MethodImpl(MethodImplOptions.AggressiveInlining)]
static TServer GetService<T>(this ServerCallContext context) where TServer : class
{
    return ((context as IServerCallContextFeature)?.Service) as T ?? ThrowInvalidService();
    static T ThrowInvalidService() => throw new SomethingException();
}
```

Then you can use the *regular* bindings, mapping to (since aspnetcore knows that the context will be an `IServerCallContextFeature`):

``` c#
(data, ctx) => ctx.GetService<TheKnownType>().SomeMethod(data, ctx)
```

---

I don't think this is a lot of work, and IMO unifying the delegate API (removing the 4 `TServer` variants) would make things significantly cleaner, with the only cost here being a single object cast per call. In the grand scheme of things, I think we can afford an object cast!

...

So: thoughts?

(note: I don't care about *which* interface; maybe `IServerCallContextFeature` is the wrong thing; maybe it is a new `IServiceBoundCallContext` ?)

(note note: I'd be happy to try a PR if you are intrigued but lacking in time)

**Comment by mgravell** [comment]
The more I think about it, the more I think "3" is overkill; I'd just emit (whether il or expression) "load ctx", "cast to the interface", "call-virt the getter", "cast to the service" {load the other arguments} "call-virt the method", "ret"

**Comment by JamesNK** [comment]
I don't think it will work. The current design is strongly typed end-to-end. The MethodInfo on a class is converted to a strongly typed delegate here:

https://github.com/grpc/grpc-dotnet/blob/ef1749b2e54f625f267d0e7369703d5cfa0b67f0/src/Grpc.AspNetCore.Server/Model/Internal/ProviderServiceBinder.cs#L66

It needs the service parameter because it is an open delegate:

https://blog.slaks.net/2011/06/open-delegates-vs-closed-delegates.html

**Comment by mgravell** [comment]
Yes, I understand the open/closed issue. I'm simply saying it is irrelevant here. It is entirely possible to switch to a closed delegate (essentially a static method). The `CreateDelegate` call would obviously become about 3 lines of `Expression` code, the `TDelegate` being used would change to the one from `Grpc.Core.Api`, and all that would change is that (pseudo code)

``` c#
var result = handler(svc, ctx, arg);
```

becomes:

``` c#
ctx.Service = svc;
var result = handler(ctx, arg);
```

(Presumably in 4 places, one per signature type)

To me it seems entirely workable.

**Comment by JamesNK** [comment]
It isn't irrelevant. I know it can be done, but it involves more moving parts. Originally we invoked the method via a compiled expression.

Removing 4 delegates used at startup that basically no one will care about, to introduce extra complexity, delegate invocations and allocations every gRPC call doesn't feel like a good trade.

**Comment by mgravell** [comment]
Fair enough. I've also just realized that this would also significantly complicate something I'm doing to snag the server instance via ldarg_0, which works identically for your open delegate and the native closed delegate, so... yeah, don't change it! Thanks for the discussion.
