### ISSUE TITLE
Easy way to break up services (handlers)? 

### ISSUE THREAD

**Issue by JamesCrann** [grpc/grpc-dotnet#351]
Is there an easy way to implement each call of a proto defined service in its own class? I don't wish to create multiple micro proto files to allow separation but at the same time I don't wish to implement a single service class which implements all calls, with each method potentially forcing its own dependencies to be injected into the class. 

Can you think of a way, or might their be a way in future to implement service calls in their own classes (handlers?) and somehow group them together to fulfill the proto contract? 

The the work done so far is awesome and a welcome alternative to REST in the .Net stack.

**Comment by cwe1ss** [comment]
You could forward the calls into your own classes with something like MediatR. In that case, each of your methods in the service implementation type would basically just hold a "_mediator.SendAsync()" call.
* https://github.com/jbogard/MediatR
* https://github.com/jbogard/MediatR.Extensions.Microsoft.DependencyInjection
* https://ardalis.com/using-mediatr-in-aspnet-core-apps

**Comment by JamesCrann** [comment]
Thanks for the suggestion, I had considered that, but wanted to avoid having to create the (minimal) extra boilerplate manually for each call, seeing as generation is being used elsewhere. 
Should the stream implementations work combined with MetdiatR?

**Comment by cwe1ss** [comment]
I’ve not used streams so far and don’t know much about it. Hopefully, someone else can answer that.

**Comment by JamesNK** [comment]
You can't customize the code generation to put each call in a separate service.

What you could do is have partial classes, with each call in its own partial class.

**Comment by jtattermusch** [comment]
We don't plan to add an option to put individual handlers into separate classes via the codegen.
Not sure how many methods has your service definition, but the gRPC ecosystem gravitates towards using the microservices model - which means that individual services should have a rather small footprint and the methods will together provide a solution to a single problem (so they presumably won't need lots of different dependencies as you're describing).
