### ISSUE TITLE
ASP.NET/.NET Framework 4.6.1 MoveNext() blocked?

### ISSUE THREAD

**Issue by hueidou** [grpc/grpc-dotnet#355]
I create a ASP.NET/.NET Framework 4.6.1 project, references RouteGuide project of the example [RouteGuide](https://github.com/grpc/grpc/tree/master/examples/csharp/RouteGuide/RouteGuide).

When run to IAsyncStreamReader<TResponse>.MoveNext(), it blocked.

```
while (await responseStream.MoveNext()) // block first while
 {
  Feature feature = responseStream.Current;
  responseLog.Append(feature.ToString());
}
```

```
Google.Protobuf 3.8.0
Grpc 1.21.0
Grpc.Tools 1.21.0
```

I also create a Console/.NET Framework 4.6.1 project which also references RouteGuide project, works normal.

ASP.NET Core/.NET Framework 4.6.1 project works normal too.

Is this related to IIS/IIS Express？

**Comment by JamesNK** [comment]
This repository is for Grpc.AspNetCore.Server. You should ask your question at https://github.com/grpc/grpc
