### ISSUE TITLE
Custom tcp stream encryption available ?

### ISSUE THREAD

**Issue by gronlund013** [grpc/grpc-dotnet#361]
I am trying to communicate with a microcontroller that uses a very custom encryption where each byte is obscured.

Can't find where to access the underlying tcpip stream.

Basically I want to overwrite the following
Write(byte[] inputBuffer, byte[]outputBuffer)
Read(byte[] inputBuffer, byte[]outputBuffer)

Is that possible ?

**Comment by davidfowl** [comment]
The microcontroller is doing http/2? You can do this at Kestrel's transport layer but I'd like to understand the end to end here.

**Comment by gronlund013** [comment]
The microcontroller is doing proto3 syntax using a custom tcp/ip stream where it basically does this

foreach (byte in bytesToRead) {
    byte = byte ^ 'c'
}

That happens before the bytestream is sent to the protobuf library (protobuf-c).

Im using latest netcore release btw (Grpc 1.22.0-pre1)

**Comment by jtattermusch** [comment]
The problem with these "custom" encryption protocols is that they tend to have a lot of security flaws. If you're already running aspnetcore on your controller, why don't you just use standard security layer?

What do you mean by "custom tcp/ip stream"? Are you actually using grpc protocol or not?
It's also not clear if you're "encrypting" the entire tcp stream or the individual messages ("... before the bytestream is sent to the protobuf library..."

**Comment by gronlund013** [comment]
We havent used grpc before.

Our last version we used protobuf-c and protobuf-net .
We are now migrating to protobuf 3 syntax and grpc seemed like a nice alternative for the dotnet side since we're migrating to dotnet core.

The encryption is for the individual messages, if theres a better way of encrypting the traffic which can be accomplished on the c side, we could try it.

**Comment by jtattermusch** [comment]
if you're encrypting individual messages, you can set custom serializer/deserializer for method handlers.
But if you want real security, I'd suggest just using https (secure gRPC connection) rather than trying to reinvent the wheel.

**Comment by gronlund013** [comment]
thank you, will try

**Comment by JamesNK** [comment]
Closing this as answered. Comment if you run into any issues with using HTTPS and gRPC.
