### ISSUE TITLE
parallel request sayhello example error

### ISSUE THREAD

**Issue by codeex** [grpc/grpc-dotnet#365]
When I try it parallel performance , I found the error.
my test environment:
  .net core 3.0 preview 6
client pacakge reference:
`<PackageReference Include="Google.Protobuf" Version="3.8.0" />
        <PackageReference Include="Grpc.Core" Version="1.21.0" />
        <PackageReference Include="Grpc.Net.Client" Version="0.1.22-pre1" />
        <PackageReference Include="Grpc.Net.ClientFactory" Version="0.1.22-pre1" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.0.0-preview6.19304.6" /> `

service package reference:
`<PackageReference Include="Grpc.AspNetCore.Server" Version="0.1.22-pre1" />
<PackageReference Include="Google.Protobuf" Version="3.8.0" />`

**proto file is isolation solution, generate the dll,then other project reference it.**

not debug version, in Release version.
sayHello service ,dont change code.
sayHello Client code:
```
 AppContext.SetSwitch( "System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport",        true);
            // Include port of the gRPC server as an application argument
            var port = args.Length > 0 ? args[0] : "50051";
            var sc = new ServiceCollection();
            sc.AddGrpcClient<CfgService.CfgServiceClient>("first", opts =>
             {
                 opts.BaseAddress = new Uri("http://localhost:" + port);
             });
            sc.AddGrpcClient<CfgService.CfgServiceClient>("two", opts =>
             {
                 opts.BaseAddress = new Uri("http://localhost:" + port);
             });

            var sp = sc.BuildServiceProvider();
            var clientFactory = sp.GetRequiredService<GrpcClientFactory>();
            var client = clientFactory.CreateClient<Greeter.GreeterClient>("two");
            //var channel = new Channel("localhost:" + port, ChannelCredentials.Insecure);
            //var client = new CfgService.CfgServiceClient(channel);

            int[] test = new int[5000];
            Stopwatch sw = new Stopwatch();

            for (int j = 0; j < 10; j++)
            {
                sw.Reset();
                sw.Start();

                var rst = Parallel.ForEach(test, async i =>
                {
                    try
                    {
                        var reply = await client.SayHelloAsync(new HelloRequest { Name = "GreeterClient" });
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine(ex.Message);
                    }
                });

                sw.Stop();
                Console.WriteLine($"{j} parallel for Elapsed time :{rst.IsCompleted}, {sw.ElapsedMilliseconds} ms");

                //sw.Reset();
                //sw.Start();
                //for (int i = 0; i < 1000; i++)
                //{
                //    var reply = await client.SayHelloAsync(new HelloRequest { Name = "GreeterClient" });
                //    //Console.WriteLine("Greeting: " + reply.Message);
                //}
                //sw.Stop();
                //Console.WriteLine($"{j} for loop 1000 Elapsed time : {sw.ElapsedMilliseconds} ms");
            }
            Console.WriteLine("Press any key to exit...");
            Console.ReadKey();
```
client application error info: 
An error occurred while sending the request.
An error occurred while sending the request.
An error occurred while sending the request.
An error occurred while sending the request.
An error occurred while sending the request.
Process is terminating due to StackOverflowException.
Process is terminating due to StackOverflowException.
Process is terminating due to StackOverflowException.
Process is terminating due to StackOverflowException.
Process is terminating due to StackOverflowException.
Process is terminating due to StackOverflowException.
unknown error! CrashDumper not found!
service applation 's error info:
 _TestService.GreeterService[3]
      Error when executing service method 'SayHello'.
System.IO.IOException: The request stream was aborted. ---> Microsoft.AspNetCore.Connections.ConnectionAbortedException: The HTTP/2 connection faulted. ---> Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2ConnectionErrorException: HTTP/2 connection error (STREAM_CLOSED): The client sent a DATA frame to closed stream ID 3619.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessDataFrameAsync(ReadOnlySequence`1 payload)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessFrameAsync[TContext](IHttpApplication`1 application, ReadOnlySequence`1 payload)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2MessageBody.ReadAsync(CancellationToken cancellationToken)
   at Grpc.AspNetCore.Server.Internal.PipeExtensions.ReadSingleMessageAsync(PipeReader input, HttpContextServerCallContext context)
   at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext)_

**Comment by codeex** [comment]
when I try below code ,It occurs error too.
```
var rst = Parallel.ForEach(test, async i =>
                {
                    try
                    {
                        client = clientFactory.CreateClient<CfgService.CfgServiceClient>("first");
                        var reply = await client.SayHelloAsync(new HelloRequest { Name = "GreeterClient" });
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine(ex.Message);
                    }
                });
```
error info:
An error occurred while sending the request.
An error occurred while sending the request.
An error occurred while sending the request.
An error occurred while sending the request.
An error occurred while sending the request.
An error occurred while sending the request.
An error occurred while sending the request.
Error while copying content to a stream.
An error occurred while sending the request.
An error occurred while sending the request.
An error occurred while sending the request.
An error occurred while sending the request.

But I change iterators to 200 ,then no error.

**Comment by JamesNK** [comment]
Hi

It looks like you're making 5000 calls in parallel, correct? I setup a console app to make 5000 calls in parallel and didn't see that error. I suspect that is because a number of HTTP/2 stress issues have been fixed in the server.

What you could do is wait until preview 7, which should come soon, and retry. If you're feeling really experimental you could also download the latest nightly .NET Core SDK and use a nightly grpc-dotnet package from the grpc NuGet feed. If you want to do that let me know and I'll add some instructions.

Feel free to comment on this issue if this error still happens in preview 7.

**Comment by codeex** [comment]
very ok in preview 7
