### ISSUE TITLE
gRPC Client invoked from AzureFunction throws error - Could not load type 'Grpc.Core.CallOptions' from assembly Grpc.Core.Api 

### ISSUE THREAD

**Issue by abhijeet-gandhi** [grpc/grpc-dotnet#373]
When gRPCClient invoked from AzureFunction (TimerTrigger) it throws - 
Could not load type 'Grpc.Core.CallOptions' from assembly 'Grpc.Core.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad'.

AzureFunction - .Net Core 2.2
nuget - Grpc.Core v1.22

**Comment by JamesNK** [comment]
This repo is for `Grpc.AspNetCore.Server`. For `Grpc.Core` issues you should re-post at https://github.com/grpc/grpc
