### ISSUE TITLE
Throw error if no test projects run on build

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#389]
Follow up to https://github.com/grpc/grpc-dotnet/pull/380

Throw an error if `test_projects` contains no items. It means we'll be notified if the tests move, the script isn't updated and tests stop running.

**Comment by JunTaoLuo** [comment]
Hmm actually it turns out ls already helps us with this: 
```
ls: test/**/*NotTests.csproj: No such file or directory
```
