### ISSUE TITLE
HTTP/2 over TLS was not negotiated on an HTTP/2-only endpoint.

### ISSUE THREAD

**Issue by MishaVernik** [grpc/grpc-dotnet#405]
**Problem:** 
On the server side 
```
Microsoft.AspNetCore.Server.Kestrel[0]
      HTTP/2 over TLS was not negotiated on an HTTP/2-only endpoint.
```
![Screenshot 7_21_2019 12_46_53 PM (2)](https://user-images.githubusercontent.com/41151124/61590218-b247f000-abb5-11e9-84b5-27ea5d26b518.png)

**Attempts to solve:**
1. With .cshtml
```
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<h1>Hello, gRPC!</h1>
@using Tasly.Service
@using Grpc.Core

<button class="btn btn-primary" onclick="@SayHello()">RUN</button>

<hr />

<p>@Greeting</p>

@functions {

    private string Greeting;

    async Task SayHello()
    {
        var channel = new Channel("localhost:5001", ChannelCredentials.Insecure);
        var client = new Greeter.GreeterClient(channel);

        var reply = await client.SayHelloAsync(new HelloRequest { Name = "Blazor gRPC Client" });
        Greeting = reply.Message;

        await channel.ShutdownAsync();
    }

}
```
2. The same with .razor (but it doesn't work) or I used it incorrectly. 
-----
**If you have any suggestions about how to fix, or if you need more information, please let me know.**

**Comment by JamesNK** [comment]
`ChannelCredentials.Insecure` means HTTPS is not used. Grpc.Net.Client package contains a gRPC client that uses HttpClient internally, which makes HTTPS much easier. If you want to use Grpc.Core client then you should ask on grpc/grpc for help.

**Comment by kmudayakumar** [comment]
This issue occurred for me even though I have used Grpc.Net.Client package. In fact the sample downloaded from https://github.com/aspnet/AspNetCore.Docs also have the same problem.

**Comment by StingyJack** [comment]
I had this same error message happen and thought it was gRPC related but it was due to an http 1.0 client connecting to the gRPC service to hit a healthcheck endpoint to make sure the service was available prior to contacting the specific gRPC service using the generated client.  Switching that HttpClient to use http2 fixed it.

**Comment by AbdoDabbas** [comment]
Hi @StingyJack,
How did you switch it, using this?:
```
AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2Support", true);
```

**Comment by StingyJack** [comment]
@AbdoDabbas  On the service I had this in the appSettings.json

``` json
{ ...
  "Kestrel": {
    "EndpointDefaults": {
      "Protocols": "Http2"
    }
  }
```

The c# client had to be changed to use http2 messages like this...
``` csharp
var req = new HttpRequestMessage(HttpMethod.Get, _myEndpoint) { Version = new Version(2, 0) };
var response = await _httpClient.SendAsync(req).ConfigureAwait(false);
```
