### ISSUE TITLE
Windows/Kerberos/Negotiate authentication

### ISSUE THREAD

**Issue by markrendle** [grpc/grpc-dotnet#409]
In the [Authentication and authorization in gRPC for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/authn-and-authz?view=aspnetcore-3.0#other-authentication-mechanisms) docs it says:

> In addition to bearer token and client certificate authentication, all ASP.NET Core supported authentication mechanisms such as OAuth, OpenID and Negotiate should work with gRPC.

But in the [Configure Windows Authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-3.0&tabs=visual-studio) docs, there is a Note:

> Windows Authentication isn't supported with HTTP/2. Authentication challenges can be sent on HTTP/2 responses, but the client must downgrade to HTTP/1.1 before authenticating.

Since gRPC runs over HTTP/2, these two statements would seem to be at odds.

I had a go at creating a simple service (with Preview6 and the latest Grpc.Net.* preview packages), adding `.Negotiate()` on authn and an `Authorize` attribute on the gRPC method, and using `HttpClientHandler.UseDefaultCredentials = true` on the client, and the service (running in plain Kestrel on Windows 10 1903) returns a 401.

Should it be possible to use `Negotiate` on a gRPC service, whether using Windows auth on Windows or Kerberos on Linux?

**Comment by JamesNK** [comment]
I looked into this and Windows authentication isn't part of the HTTP/2 spec and so can't be used with gRPC. I'll correct the documentation.

**Comment by markrendle** [comment]
👍 for correcting the documentation.
👎 for Windows auth not working over HTTP/2 (which is not your fault).

**Comment by ebekker** [comment]
Can anyone clarify if this is the kind of thing that can be addressed _simply_ with enough engineering resources, or is this something that has to be taken back to a _standards body_ like IETF?

I was just thinking that since Negotiate is implemented via HTTP headers and a few round-trip HTTP interactions, that it could be adapted to HTTP/2 pretty easily, is this not the case?

**Comment by JamesNK** [comment]
I don't know. I've never looked at how Windows auth works on the wire.

**Comment by IamJignesh** [comment]
@JamesNK is this possible?
https://learn.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-8.0&viewFallbackFrom=aspnetcore-3.0&tabs=visual-studio
![image](https://github.com/user-attachments/assets/6a243d14-02d2-47a6-a1a0-6e14d4a744b3)
