### ISSUE TITLE
when multi grpc server using same port, no error

### ISSUE THREAD

**Issue by spiderpoison** [grpc/grpc-dotnet#414]
I run HelloWorld on linux, when run mutli server with same port, only last server can receive msg.
If I want the second server output error instead of grabbing port, how should I do?

By the way, if i want to start grpc server with the Socket which has already bind and listen to a port,  how should I do?

**Comment by JamesNK** [comment]
Kestrel doesn't support multiple instances listening to the same port: https://stackoverflow.com/a/37869426/11829

**Comment by spiderpoison** [comment]
@JamesNK thanks for your replay.
I don't need multiple instances listening to the same port
I just want the second listening throw error and failed. But now, the second listening successfully while the first fail in silence.

**Comment by JamesNK** [comment]
I have never experienced that. The first Kestrel instance will use the port and the second instance will throw an error saying that the port is already in use.

**Comment by spiderpoison** [comment]
I run socket bind and listen of dotnet core, It's ok, the second instance will throw.
But When I run the example https://github.com/grpc/grpc/tree/master/examples/csharp/Helloworld/GreeterServer, will be wrong.

**Comment by JamesNK** [comment]
You're running C-Core grpc. This repo is for gRPC on Kestrel.

Ask at https://github.com/grpc/grpc

**Comment by jtattermusch** [comment]
You should be able to configure with `grpc.so_reuseport` what the behavior should be (set a `ChannelOption` for the server)
https://github.com/grpc/grpc/blob/b8b6df08ae6d9f60e1b282a659d26b8c340de5c9/include/grpc/impl/codegen/grpc_types.h#L278

**Comment by MuhammadNoman-SE** [comment]
Is there any way to run service and client on the same machine without using the port?
