### ISSUE TITLE
Support WriteFlags.BufferHint?

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#42]
@jtattermusch Should WriteFlags.BufferHint be supported? There is no use of it in grpc/grpc

**Comment by jtattermusch** [comment]
context:
In Grpc.Core the buffer hint gets propagated to C-core (the native layer) which AFAIK does have some special handling https://github.com/grpc/grpc/blob/618a3f561d4a93f263cca23abad086ed8f4d5e86/src/csharp/Grpc.Core/Internal/CallSafeHandle.cs#L81

That said, this is only a hint, so just ignoring it is a fully compliant solution (which I suggest we do initially unless ASP.NET core has support for corking/uncorking that maps well to this concept).

The main reason for this flag to exist is to give a performance-oriented hint that other chunk of data is coming very soon (so it might make sense to delay the write syscall and write everything at once),
so this flag will only become interesting once trying to squeeze the implementation for maximum performance.

**Comment by JamesNK** [comment]
Done in https://github.com/grpc/grpc-dotnet/pull/69
