### ISSUE TITLE
Managed client using HttpClient

### ISSUE THREAD

**Issue by JunTaoLuo** [grpc/grpc-dotnet#43]
This issue tracks the work required to provide a complete managed end to end experience. This is going to be blocked on Core support for trailing response header support. cc @shirhatti for an expected timeframe.

Also, I'm not certain we need to change the code gen to implement this feature. I think we can pass in an HttpClient based [call invoker](https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/CallInvoker.cs) to the [constructor](https://github.com/grpc/grpc/blob/afc5b0b5d4d36aedf94a70b50d7c40062590abb1/src/csharp/Grpc.Core/ClientBase.cs#L62) of the client. I don't have a client I can prototype this with yet so I'm not 100% certain but is there any reason this wouldn't work @jtattermusch @JamesNK ?

**Comment by jtattermusch** [comment]
> This issue tracks the work required to provide a complete managed end to end experience. This is going to be blocked on Core support for trailing response header support. cc @shirhatti for an expected timeframe.
> 
> Also, I'm not certain we need to change the code gen to implement this feature. I think we can pass in an HttpClient based [call invoker](https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/CallInvoker.cs) to the [constructor](https://github.com/grpc/grpc/blob/afc5b0b5d4d36aedf94a70b50d7c40062590abb1/src/csharp/Grpc.Core/ClientBase.cs#L62) of the client. I don't have a client I can prototype this with yet so I'm not 100% certain but is there any reason this wouldn't work @jtattermusch @JamesNK ?

Good point, using HttpClient-based CallInvoker to create an instance of client stub should work. That should be sufficient for basic client functionality.

**Comment by JamesNK** [comment]
Initial release in preview 6. Additional features can be tracked in there own issues.

**Comment by mikebm** [comment]
Sorry to resurrect this, but I am not seeing a .net standard version of the Grpc.Net.Client available in Nuget. It only targets .net core 3 which is incompatible with projects such as Xamarin Forms. Am I missing something or is this not actually available as part of preview 6.

**Comment by JamesNK** [comment]
https://www.nuget.org/packages/Grpc.Net.Client/0.1.22-pre1 - this version supports netstandard2.1

netstandard2.1 is required because the client needs to access trailers from the HTTP/2 response.
