### ISSUE TITLE
Support interceptors in AspNetCore.Server

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#44]
https://github.com/grpc/proposal/blob/master/L12-csharp-interceptors.md

https://grpc.io/grpc/csharp/api/Grpc.Core.Interceptors.html

**Comment by JunTaoLuo** [comment]
This might impact #1

**Comment by JamesNK** [comment]
@jtattermusch Do you think this is important to implement in gRPC ASP.NET Server? In ASP.NET we will have middleware that will fulfill the same purpose.

**Comment by jtattermusch** [comment]
I think it's fine to not have this in the first version and we can revisit later. It would be useful to do a quick check though to see if this is possible from the API perspective (i.e. what types we would need to move to Grpc.Core.Api and see if they are easily movable).

**Comment by JamesNK** [comment]
ok! thanks

**Comment by Kadajski** [comment]
Middleware fulfills a _similar_ purpose, though how would you get access to the actual request or response objects in your middleware? Seems like the deserialization/serialization all happens inside of e.g. `UnaryServerCallHandler` so on either end you'd only have access to bytes

**Comment by Kadajski** [comment]
> I think it's fine to not have this in the first version and we can revisit later. It would be useful to do a quick check though to see if this is possible from the API perspective (i.e. what types we would need to move to Grpc.Core.Api and see if they are easily movable).

I am pretty sure the only things required that were mentioned to have not been moved over are:

| Types |
|---------------------------------------------------------------------------|
| Grpc.Core.Interceptors.Interceptor |
| Grpc.Core.Interceptors.Interceptor+AsyncClientStreamingCallContinuation`2 |
| Grpc.Core.Interceptors.Interceptor+AsyncDuplexStreamingCallContinuation`2 |
| Grpc.Core.Interceptors.Interceptor+AsyncServerStreamingCallContinuation`2 |
| Grpc.Core.Interceptors.Interceptor+AsyncUnaryCallContinuation`2 |
| Grpc.Core.Interceptors.Interceptor+BlockingUnaryCallContinuation`2 |

The interceptor is pretty stand-alone. The only thing referencing anything else are the extension methods which would need to be rewritten to match this new repo as the old `ServerServiceDefinition` doesn't seem to be used anymore.

I did some investigations into how this _could_ work and came up with some sample code for a unary call. https://github.com/Kadajski/grpc-dotnet/commit/68a398bb7f4ce7ba2c6052a579276ca6bacbc0b9

**Comment by aloisdeniel** [comment]
Hi, I'm currently trying to use ASP.net middlewares in combination with gRPC service behind. I struggle because you can't throw an `RpcException` from that middleware (I suppose that we aren't in the gRPC world yet, and the client continues wait for a response).

Any suggestion for doing that today ? Interceptors might be a solution, but middlewares are interesting since they can be shared more easily.

**Comment by gezhl** [comment]
Any news on this?

For my project I need to handle authentication via username and password contained in gRPC metadata, but cannot find any way to access this data during the AuthenticationHandler's HandleAuthenticateAsync() method. Is this possible (even using a hacky workaround or extension methods) in release v0.1.19-pre1?

**Comment by JunTaoLuo** [comment]
Based on the feedback we have received, we are prioritizing this feature.

**Comment by zejji** [comment]
Just to mention some use case examples which are not currently possible when using Grpc.AspNetCore.Server (and which will hopefully be solved by interceptor support). I have run into all 3 of these in trying to implement a real-world project:

- logging of the full content of all incoming requests (including message bodies);
- handling of exceptions thrown within the gRPC service implementation (these are currently swallowed by a catch block in the guts of the Grpc.AspNetCore.Server code);
- returning of gRPC status codes/metadata on a failed call (e.g. following an authentication failure).

**Comment by JunTaoLuo** [comment]
We have added interceptor support in Grpc.AspNetCore.Server. Example usage can be found in the server sample: https://github.com/grpc/grpc-dotnet/blob/master/examples/Server/Startup.cs.

**Comment by pascx64** [comment]
> We have added interceptor support in Grpc.AspNetCore.Server. Example usage can be found in the server sample: https://github.com/grpc/grpc-dotnet/blob/master/examples/Server/Startup.cs.

It seems like the link is broken. I think the example is now located here : 
[https://github.com/grpc/grpc-dotnet/blob/master/examples/Logger/Server/Startup.cs](https://github.com/grpc/grpc-dotnet/blob/master/examples/Logger/Server/Startup.cs)

**Comment by AnthonyGiretti** [comment]
> Just to mention some use case examples which are not currently possible when using Grpc.AspNetCore.Server (and which will hopefully be solved by interceptor support). I have run into all 3 of these in trying to implement a real-world project:
> 
> * global logging of the full content of all incoming requests (including message bodies);
> * global handling of exceptions thrown within the gRPC service implementation (these are currently swallowed by a catch block in the guts of the Grpc.AspNetCore.Server code);
> * returning of gRPC status codes/metadata on a failed call (e.g. following an authentication failure).

Hi Folks, any update on this?

**Comment by JamesNK** [comment]
Interceptors have been implemented for a while now.

**Comment by AnthonyGiretti** [comment]
I have seen, In fact I was unable to handle globally exceptions with an
interceptor, maybe I haven't used it in the proper way.
Do you have a code sample that shows global error handling (like a
middleware in a webapi) I would like to catch the exception and  the the
proper grpc status to the client?


<http://anthonygiretti.com/>   *Anthony Giretti*
MVP, MCSD
Developer, Blogger, Speaker
[image: email] anthony.giretti@gmail.com
[image: mobile] + 1 514 557 1380 <+1+514+557+1380>
[image: Twitter]
<https://twitter.com/https://twitter.com/anthonygiretti> [image:
LinkedIn]
<https://linkedin.com/https://www.linkedin.com/in/anthony-g-98670426/>
http://anthonygiretti.com


Le sam. 7 déc. 2019 à 23:32, James Newton-King <notifications@github.com> a
écrit :
