### ISSUE TITLE
Grpc healthcheck is failing in kubernetes once every few days

### ISSUE THREAD

**Issue by mustakimali** [grpc/grpc-dotnet#452]
A grpc service recently upgraded to .NET Core Preview 7 fails the kubernetes healthcheck intermittently. When I remove kubernetes healthcheck - the application works fine. This issue appeared twice, first in 1 day mark and the next is 4.5 days mark.

here is the error message
```
Status(StatusCode=Unavailable, Detail=\"failed to connect to all addresses\")
```

```
[Route("liveness")]
public async Task<IActionResult> LivenessCheck()
{
    var channel = await GetSecuredChannel();
    var client = new Health.HealthClient(channel);

    var response = await client.CheckAsync(new HealthCheckRequest
    {
        Service = "ServiceName"
    });
   // the status is hard-coded in the service to be Serving
    if (response.Status != HealthCheckResponse.Types.ServingStatus.Serving)
    {
        _logger.LogWarning("Healthcheck Failed! {healthCheckResponse}", response);

        return StatusCode(500, "Healthcheck Failed");
    }

    return Ok("healthy");
}

private async Task<Channel> GetSecuredChannel()
{
    var target = $"my-app.default.svc.cluster.local:443";
    var rootCertificates = await System.IO.File.ReadAllTextAsync("/usr/share/ca-certificates/company-ca.crt");

    var channel = new Channel(target, new SslCredentials(rootCertificates));
    return channel;
}
```

here is the relevant code from `Startup`

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers();
    services.AddGrpc();
    
    /* code removed for brevity */

    services.AddTransient<IProviderService, ProviderService>();
    services.AddSingleton<Grpc.HealthCheck.HealthServiceImpl>();
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env, IServiceProvider sp)
{
    var hc = sp.GetRequiredService<Grpc.HealthCheck.HealthServiceImpl>();
    hc.SetStatus("ServiceName", HealthCheckResponse.Types.ServingStatus.Serving);

    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
    }

    app.UseRouting();

    app.UseEndpoints(endpoints =>
    {
        endpoints.MapGrpcService<ProvidersImpl>();                        // this is application code
        endpoints.MapGrpcService<Grpc.HealthCheck.HealthServiceImpl>();   // this comes from NuGet Grpc.HealthCheck v1.22.0
        endpoints.MapControllers();
    });
}
```

I'm using [Grpc.HealthCheck v1.22.0](https://www.nuget.org/packages/Grpc.HealthCheck/) here is all the relavant packages

```
    <PackageReference Include="Grpc.AspNetCore.Server" Version="0.1.22-pre2" />
    <PackageReference Include="Grpc.HealthCheck" Version="1.22.0" />
```

Does anyone know about any issues with kubernetes healthcheck for Grpc that affects services running for some time?

**Comment by JamesNK** [comment]
I don't know what the issue could be.

It is unlikely to be in the health check service itself. It is very very simple:

https://github.com/grpc/grpc/blob/13fb5066390b51bf457725a91fe3a93daed40940/src/csharp/Grpc.HealthCheck/HealthServiceImpl.cs#L87-L100

Are any warnings or errors being logged on the server?

You're using the Grpc.Core client which is where the status code is being raised. Perhaps the issue is with it.

**Comment by mustakimali** [comment]
Thanks @JamesNK, there is no warning at or around the exact moment, but surprisingly Kestrel generated warnings like this around ~4 hours before each of the incidents.

```
Heartbeat took longer than "00:00:01" at "08/06/2019 06:25:55 +00:00". This could be caused by thread pool starvation.
```
I am confused by that warning, as I don't see anything that could cause threadpool starvation. 😕 .

To identify whether the issue is with the _Client_ - I have pushed an update that uses [`grpc_health_probe` binary](https://github.com/grpc-ecosystem/grpc-health-probe) to perform the healthcheck. Just keeping an eye on it now.

If it turns out there is an issue with the `Grpc.Core` client - then I'd have to be careful before upgrading other services that uses an older version og Grpc.Core.

**Comment by mustakimali** [comment]
It appears there was indeed some issue with the `Grpc.Core` client package. There was no issue since I started using the `grpc_health_probe` binary for the health-check. So I will close this issue.
