### ISSUE TITLE
Server not working when not using https and ListenOptions set to Http1AndHttp2

### ISSUE THREAD

**Issue by hanabi1224** [grpc/grpc-dotnet#460]
Grpc service works for Http2 only when not using https, however, I need it listen to a single port and work for both http1(webapi/web site) and http2(grpc),  is there any workaround? Thanks in advance

**Comment by JamesNK** [comment]
What happens when you use HTTPS? What are the errors on the client and/or server?

A port can be configured to support HTTP1 and 2 in Kestrel - https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.2#listenoptionsprotocols

**Comment by hanabi1224** [comment]
@JamesNK Sry for the confusion, everything works fine with https, my problem is that, when I use http, I could not make it work for both http1(web api) and http2(grpc) with a single port.

**Comment by JamesNK** [comment]
Ah ok.

A port that supports both HTTP1 and 2 needs HTTPS enabled: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.2#listenoptionsprotocols

**Comment by JamesNK** [comment]
Will improve documentation of this limitation: https://github.com/aspnet/AspNetCore.Docs/pull/13891

**Comment by hanabi1224** [comment]
@JamesNK Thanks!
