### ISSUE TITLE
Run GRPC and WebApi along each other

### ISSUE THREAD

**Issue by buehler** [grpc/grpc-dotnet#464]
Dear Developers :-)

I'm using (and testing) this package quite a lot and I found a special case that I just can't figure out a solution:

Is it possible to use GRPC with WebApi in the same application? And maybe on the same port?

Or do I need to use multiple ports, one for grpc and one for webapi?

Or is it depending on `HTTP2`, respectively `Http1AndHttp2`?

Right now, the backend does use http2 but without tls configured since the loadbalancer of the app does terminate TLS.

But I need the application to response to rest calls as well as grpc calls since a third party app does not have grpc.

Best
Christoph

**Comment by JamesNK** [comment]
You can reuse the same port in Kestrel. The port needs to be Http2 or Http1AndHttp2.

However, if you are using Http1AndHttp2 then you have to use TLS. See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.0#listenoptionsprotocols

**Comment by buehler** [comment]
Alright, thank you very much!

Have a nice day :-)
