### ISSUE TITLE
client concurrency settings?

### ISSUE THREAD

**Issue by IKende** [grpc/grpc-dotnet#483]
I using grpc-dotnet for performance testing
## create client code
```
var client = new Channel($"{Setting.SERVER_HOST}:50051", ChannelCredentials.Insecure);
var greeter=new Greeter.GreeterClient(client)
```
## concurrent test code
```
        public async Task Execute()
        {
            var result = await Greeter.SayHelloAsync(new HelloRequest { Name = "you" });
        }
```
## Environment
－ Client: E31230v2 16g
－ Server: E52670v2 32g
－ Network: [10Gb]
－ System: Windows server
concurrent testing with 256 instances result rps is 37k. but using [orleans](https://github.com/dotnet/orleans) concurrent testing with 256 instances result rps is 142k.
[Test code](https://github.com/IKende/dotnet-rpc-benchmark/blob/master/RPCBenchmark/Examples/GRPCHelloWorld.cs)

**Comment by JamesNK** [comment]
Your benchmark appears to use Grpc.Core, which can be found at https://github.com/grpc/grpc

This repo is for the new gRPC client for .NET Core 3.

Getting started tutorial: https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.0&tabs=visual-studio

**Comment by IKende** [comment]
Thanks
