### ISSUE TITLE
Runtime test and document host and OS requirements

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#492]
We need to provide documentation and/or an app check on startup that gRPC service is used in a compatible host and OS.

Example of user trying and failing to use gRPC on Win Server 2012:
https://github.com/protobuf-net/protobuf-net.Grpc/issues/16#issuecomment-528546112

**Comment by GoNextGroup** [comment]
Unfortunatelly, the problem won't be solved by updating OS. The tests gonna fails on the fully updated OS, but in a "magic" way (it's described in the some last messages by the link above). I'll try to test on the Windows 10 (Build 1903) today. Possible, it's not an OS problem, but the problem of the llibrary itself.

**Comment by GoNextGroup** [comment]
I've found the source of the problem.  It was connected with the Fiddler Configuration. By default, Fiddler uses proxy and changes Windows proxy configuration for localhost. I removed proxy setting for not to use proxy everywhere in Fiddler configuration and all gonna great!
I think, this problem could be marked as solved.

**Comment by JamesNK** [comment]
@shirhatti

**Comment by shirhatti** [comment]
|                                            | gRPC support over TLS | gRPC support using prior knowledge HTTP/2 (h2c) |
|--------------------------------------------|-----------------------|-------------------------------------------------|
| Windows <= 8 Windows Server <= Server 2012 | No                    | Yes                                             |
| Window >= 8.1 Windows Server >= 2012 R2    | Yes                   | Yes                                             |
| macOS                                      | No                    | Yes                                             |
| Linux with OpenSSL <= 1.0.2g               | No                    | Yes                                             |
| Linux with OpenSSL >= 1.0.2h               | Yes                   | Yes                                             |

**Comment by jtattermusch** [comment]
@shirhatti  thanks for the summary. It might be useful to make it clear the the "h2c" column corresponds to an "insecure channel / plain text connection", while the first column is "secure channel". Currently it's not fully obvious from the table, but it's a very important distinction.

**Comment by JamesNK** [comment]
People are still being bitten by this - https://github.com/aspnet/AspNetCore/issues/14139#issuecomment-535211129

**Comment by JamesNK** [comment]
Fixed with https://github.com/aspnet/AspNetCore.Docs/pull/14730
