### ISSUE TITLE
Consider using grpc certs for interop testing

### ISSUE THREAD

**Issue by JunTaoLuo** [grpc/grpc-dotnet#50]
We may need to change our certs to those at https://github.com/grpc/grpc/tree/master/src/core/tsi/test_creds and https://github.com/grpc/grpc/tree/master/src/csharp/Grpc.IntegrationTesting/data in the future for interop testing scenarios.

**Comment by ayed44** [comment]
هنا يطلب مني الرقم سري كيف احصله

**Comment by JamesNK** [comment]
@JunTaoLuo Is this needed? Interop tests appear to be running without any issues.

**Comment by JamesNK** [comment]
Interop tests seem to be fine as is. Closing.
