### ISSUE TITLE
HTTP/2 performance of Kestrel and HttpClient

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#502]
gRPC on .NET Core can only be fast if HTTP/2 is fast. This is a tracking issue for helping the Kestrel team and HttpClient teams improve performance.

**Comment by JamesNK** [comment]
Kestrel HTTP/2 issue: https://github.com/aspnet/AspNetCore/issues/13750

**Comment by RenaudGelai** [comment]
Hello,

I have some performances issues with grpc/kestrel.

If i write this : 

![image](https://user-images.githubusercontent.com/998330/78409847-0cd19100-760b-11ea-9312-161f3ce8bd5c.png)

The first call is very slow (between one and three seconds).

But if i write this :

![image](https://user-images.githubusercontent.com/998330/78409815-f592a380-760a-11ea-9674-68dccaacfd47.png)


I don't have the problem.

Is it related to this issue ?

**Comment by JamesNK** [comment]
No. The slowness is probably related to resolving the IP address.

**Comment by JamesNK** [comment]
I think this can be called fixed in .NET 5
