### ISSUE TITLE
Send message from one client to another

### ISSUE THREAD

**Issue by PwGiza** [grpc/grpc-dotnet#504]
Is There any option to send message from client  one (stream) to server and then from server send this message to another client also stream?

**Comment by JamesNK** [comment]
Not using gRPC. Point-to-point realtime communication is supported (i.e. a client and server pushing messages to each other).

If you want to broadcast messages out to multiple clients then you'll need to implement that manually, or use technology like SignalR.

**Comment by PwGiza** [comment]
Ok thanks James.
 but it is possible to keep open two streams from onw client in the same time?

**Comment by JamesNK** [comment]
Yes

**Comment by PwGiza** [comment]
Using only grpc? Or I need signalr?

**Comment by PwGiza** [comment]
Because i try with grpc and when I try open another stream the one is closed.

**Comment by JamesNK** [comment]
You can make two streaming gRPC calls at the same time from one client.

**Comment by MdLejTeCole** [comment]
It is what i am looking for last days it is very good news Grpc let me send more streams. But i dont know from where do you take DefaultTimeout() and how look like AddDuplexStreamingMethod().

I use servicesProvaider to create client like this
```
            var servicesProvider = new Provider();
            servicesProvider.SetServiceConnection(typeof(EkService.EkClient), "localhost", 5000, ChannelCredentials.Insecure);
            servicesProvider.CreateServiceAndCache<EkService.EkClient>();

            var client = servicesProvider.GetService<EkService.EkClient>();
```

Is it possible for me to do it with my client?
