### ISSUE TITLE
Multiple streams

### ISSUE THREAD

**Issue by MdLejTeCole** [grpc/grpc-dotnet#519]
Can I have 2 stream open at the same time? Or call one method in another?

`await Task.WhenAll(GetData(client), SendData(client));

private static async Task GetData(ServiceClient client)
{
using (var call = client.GetDataStream(new Protos.Model() { Id = 3 }))
{
await foreach (var item in call.ResponseStream.ReadAllAsync())
{
//do something with data and then send
SendData(item);

}
}
}

public static async Task SendData(ServiceClient client, Protos.Model item)
{
using (var call = client.SendDataToServer())
{
await call.RequestStream.WriteAsync(item));
}
}`

**Comment by JamesNK** [comment]
Yes. Unit test verifying that it works: https://github.com/grpc/grpc-dotnet/pull/525
