### ISSUE TITLE
Bad gRPC response. Expected HTTP status code 200. Got status code: 426

### ISSUE THREAD

**Issue by pablofrommars** [grpc/grpc-dotnet#526]
### What version of gRPC and what language are you using?
- C#
- Grpc.AspNetCore (0.2.23-pre2)

### What operating system ?
Windows 10

### What runtime are you using?
 .NET Core 3.0 (.NET Core 3.0.100-rc1)

### What did you do?

I am trying to embed a Grpc server within a Blazor server side application.

My solution contains 4 projects:

- BlazorGrpc.Shared defines the grpc service and generates the server and client.

greet.proto

```proto
syntax = "proto3";

option csharp_namespace = "GreeterRpc";

package Greet;

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply);
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings.
message HelloReply {
  string message = 1;
}
```
Service.cs

``` C#
 public class GreeterService : Greeter.GreeterBase
{
   public override Task<HelloReply> SayHello(HelloRequest request, ServerCallContext context)
   {
      return Task.FromResult(new HelloReply
      {
         Message = "Hello " + request.Name
      });
   }
}
```

- BlazorGrpc is the blazor server side app  and embeds a Greeter service mapped in Startup.cs
``` C#
app.UseEndpoints(endpoints =>
{
   endpoints.MapGrpcService<Shared.GreeterService>();
   endpoints.MapBlazorHub();
   endpoints.MapFallbackToPage("/_Host");
});
```
- BlazorGrpc.GrpcService also embeds a Greeter service mapped in Startup.cs
``` C#
app.UseEndpoints(endpoints =>
{
   endpoints.MapGrpcService<Shared.GreeterService>();
});
```

- BlazorGrpc.Worker is a background service and contacts both BlazorGrpc and BlazorGrpc.GrpService

``` C#
protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            await Task.Delay(5 * 1000).ConfigureAwait(false);

            /// Request to BlazorGrpc
            var task1 = Task.Run(async () =>
            {
                try
                {
                    using var channel = GrpcChannel.ForAddress("https://localhost:44345");
                    var client = new GreeterRpc.Greeter.GreeterClient(channel);
                    var reply = await client.SayHelloAsync(new GreeterRpc.HelloRequest { Name = "BlazorGrpc" });
                    _logger.LogInformation($"reply: {reply.Message}");
                }
                catch (Exception e)
                {
                    _logger.LogError(e, $"HelloRequest to BlazorGrpc");
                }
            });
            /// Request to BlazorGrpc.GrpcService
            var task2 = Task.Run(async () =>
            {
                try
                {
                    using var channel = GrpcChannel.ForAddress("https://localhost:5001");
                    var client = new GreeterRpc.Greeter.GreeterClient(channel);
                    var reply = await client.SayHelloAsync(new GreeterRpc.HelloRequest { Name = "BlazorGrpc.GrpcService" });
                    _logger.LogInformation($"reply: {reply.Message}");
                }
                catch (Exception e)
                {
                    _logger.LogError(e, $"HelloRequest to BlazorGrpc.GrpcService");
                }
            });

            await Task.WhenAll(task1, task2);
        }
```

### What did you expect to see?

The request to BlazorGrpc (task1) succeed like the request to BlazorGrpc.GrpcService (task2) does.

### What did you see instead?

An expection is raised in task1:
```
Grpc.Core.RpcException: Status(StatusCode=Cancelled, Detail="Bad gRPC response. Expected HTTP status code 200. Got status code: 426")
   at Grpc.Net.Client.Internal.GrpcCall`2.GetResponseAsync()
   at BlazorGrpc.Worker.Worker.<ExecuteAsync>b__2_0() in C:\Users\pablo\source\repos\BlazorGrpc\BlazorGrpc.Worker\Worker.cs:line 31
```
BlazorGrpc does not complain at all:

```
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/2.0 POST https://localhost:44345/Greet.Greeter/SayHello application/grpc 
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executing endpoint 'gRPC - /Greet.Greeter/SayHello'
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint 'gRPC - /Greet.Greeter/SayHello'
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 35.4341ms 426
```

For comparison, BlazorGrpc.GrpcService logs:
```
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/2 POST https://localhost:5001/Greet.Greeter/SayHello application/grpc 
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executing endpoint 'gRPC - /Greet.Greeter/SayHello'
BlazorGrpc.Shared.GreeterService: Debug: Reading message.
BlazorGrpc.Shared.GreeterService: Debug: Sending message.
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint 'gRPC - /Greet.Greeter/SayHello'  
```

In addition, GreeterService.SayHello is never invoked in BlazorGrpc (debug breakpoint). If I add a constructor to GreeterService, it doesn't seem to be invoked either (debug breakpoint). It's like BlazorGrpc doesn't even create an instance of GreeterService which I find very suspicious and probably the cause of the problem.

### Anything else we should know about your project / environment?

See reproduction solution:
https://github.com/pablofrommars/BlazorGrpc

Many thanks to everybody involved!

**Comment by JamesNK** [comment]
I think you are hitting this logic:

https://github.com/grpc/grpc-dotnet/blob/01081bc26898a10cc8c3b473990bccc5e8035e84/src/Grpc.AspNetCore.Server/Internal/CallHandlers/ServerCallHandlerBase.cs#L64-L70

Your request to BlazorGrpc is not HTTP/2. When the request is using the correct protocol then it will succeed.

Also Grpc.AspNetCore could should be writing this message to server logs so it is more obvious what is going on to people like you have this problem.

**Comment by JamesNK** [comment]
You get this error because you're starting BlazorGrpc from Visual Studio, and it is IIS Express as configured in your launchSettings.json. If you update it to remove IIS Express and use port 5051 in your worker then it completes succcessfully.

```json
{
  "profiles": {
    "BlazorGrpc": {
      "commandName": "Project",
      "launchBrowser": true,
      "applicationUrl": "https://localhost:5051;http://localhost:5050",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

If you start the we

**Comment by pablofrommars** [comment]
Brilliant! Not in a million years I could have thought about launchSettings.json.

I suspected a configuration mistake regarding protocol use but discarded it as the logs stated HTTP/2.0, #529 should help remove confusion.

```
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/2.0 POST https://localhost:44345/Greet.Greeter/SayHello application/grpc
```
Thanks!

**Comment by JamesNK** [comment]
Ah, there is an extra problem here. IIS is getting HTTP/2, but it has an odd protocol.

https://github.com/aspnet/AspNetCore/issues/14139
