### ISSUE TITLE
Security review

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#53]
Lets review security prior to the first preview

// @blowdart

**Comment by JamesNK** [comment]
Serialization with protobuf
Maximum message sizes
HttpClient with HTTP/2
Compression security considerations
Min request body rate limiting for streaming

**Comment by blowdart** [comment]
Resource use
Authentication
Authorization? 
Error handling
Input validation

**Comment by JunTaoLuo** [comment]
@shirhatti can you upload the notes please?

**Comment by shirhatti** [comment]
https://github.com/aspnet/specs/blob/master/notes/grpc/security-review.md

**Comment by JamesNK** [comment]
Handed off to security people. Follow up tasks can be new issues
