### ISSUE TITLE
Grpc.Net.Client good to go for production?

### ISSUE THREAD

**Issue by bvandre** [grpc/grpc-dotnet#532]
The `README.md` for `Grpc.Net.Client` contains this warning

```
WARNING - The client is not ready for production usage. It does not support reading status and trailers, and because of this the client can't recognize when the server reports a failure.
```
Is this still true? I can see from all of your outward documentation that this is being promoted. I just wanted to ensure that the client is good to go for production.

**Comment by JamesNK** [comment]
You can use it in production. I'll remove that warning.

**Comment by JamesNK** [comment]
Done https://github.com/grpc/grpc-dotnet/pull/533
