### ISSUE TITLE
--grpc_out: protoc-gen-grpc: The system cannot find the file specified.

### ISSUE THREAD

**Issue by stulzq** [grpc/grpc-dotnet#541]
I created a gRPC Service project using Visual Studio 2019（.NET Core 3.0 Release）, but I can't compile it.
![image](https://user-images.githubusercontent.com/13200155/65476030-28b5e680-deb4-11e9-833d-918b124eedf7.png)

The "系统找不到指定的路径" means "The system cannot find the file specified." 

When I send this project to my colleagues, he can compile successfully. How can I solve this problem?

**Comment by stulzq** [comment]
Visual Studio 16.3.0
.NET Core 3.0.100
Windows 10

**Comment by jtattermusch** [comment]
@stulzq  feel free to share what the problem was

**Comment by stulzq** [comment]
https://github.com/aspnet/AspNetCore/issues/14351
