### ISSUE TITLE
Generate client interface

### ISSUE THREAD

**Issue by bluetentacle** [grpc/grpc-dotnet#545]
Currently, the grpc tool chain generates a client class but not an interface, such as:

```csharp
public partial class GreeterClient : grpc::ClientBase<GreeterClient>
```

This makes the generated code very unfriendly to dependency injection and mocking. In a typical application that makes good use of dependency injection, you'd expect to be able to inject an `IGreeterClient` into a class that needs to make the RPC call:

```csharp
public class MyClass
{
  public MyClass(IGreeterClient greeterClient)
  {
      ...
  }
}
```

...so that in unit tests, IGreeterClient can easily be replaced with a mock.

I'd like to see grpc-dotnet generate the interface which is implemented my the class. To carry on the GreeterClient example:

```csharp
public interface IGreeterClient
{
  virtual grpc::AsyncServerStreamingCall<global::server.HelloReply> SayHello(global::server.HelloRequest request, grpc::CallOptions options);
}

public partial class GreeterClient : grpc::ClientBase<GreeterClient>, IGreeterClient
{
  ...
}
```

Is such a feature already available, or does it need to be implemented?

**Comment by JamesNK** [comment]
You can raise this issue at https://github.com/grpc/grpc

You don't need an interface to unit test a client. Client's have a constructor that takes a `CallInvoker`. You can give it a test implementation.

**Comment by jtattermusch** [comment]
Answered in https://github.com/grpc/grpc/issues/20373
