### ISSUE TITLE
Custom object message field type and serialization

### ISSUE THREAD

**Issue by khteh** [grpc/grpc-dotnet#552]
How to represent an entity object in GRPC message which is sent as a response from the Service? I know I can redefine every single field in the entity object with a `message` type but it doesn't make sense to do that for an entity object retrieved from the DB. Same for the data types defined / provided by the framework.
Any advice and insight is appreciated.

**Comment by kkadir** [comment]
Hello @khteh, it is not clear what you are asking for as gRPC depends on the protocol buffer to interchange data. That is one of the key points of using gRPC:  serializing structured data to enable data exchange across polyglot service(s) and client(s) in a language-agnostic way.

What I understand from your question is that it seems unusual to send a whole entity with all its fields as-is, and you assume that maybe using custom or wrapper types would be better. But;
1. There is nothing wrong with having many fields in a message.
2. Using any language-specific, or context-specific is against the very foundation of gRPC.

Finally, IMHO if you constantly require to send thick messages between autonomous services (i.e. microservices) or clients (i.e. mobile clients), maybe you should consider rethinking over your design.

**Comment by JamesNK** [comment]
> I can redefine every single field in the entity object with a message type but it doesn't make sense to do that for an entity object retrieved from the DB. Same for the data types defined / provided by the framework.

You need to define messages so there is a contract. gRPC isn't like JSON/REST where you can receive some JSON on the client and then get some properties out of it by name. The client and server need to share the same contract which is the proto file.

**Comment by khteh** [comment]
Let me give you an example. A client authenticates with an auth sever using grpc. How to send across framework object types like `ClaimsPrincipal`, `Claims`, etc?

**Comment by JamesNK** [comment]
Authentication and authorization documentation - https://docs.microsoft.com/en-us/aspnet/core/grpc/authn-and-authz?view=aspnetcore-3.0

**Comment by khteh** [comment]
What if the client and server needs to share the contract which includes framework defined types like `Claims` and `ClaimsPrincipal`? Which grpc type should I use to define the message field?

**Comment by JamesNK** [comment]
You turn a `Claims`/`ClaimsPrincipal` into a message on the client and you turn the message into a `Claims`/`ClaimsPrincipal` on the server.

**Comment by khteh** [comment]
I was thinking of using `bytes` type. But then it needs binary serializer and grpc / protobuf is using binary protocol. `BinaryFormatter` is a cjoice but not a good one. Is there a way to assign the opaque object and let grpc/protobuf does the binary serialization and send across?

**Comment by JamesNK** [comment]
There is nothing built into gRPC. How you serialize objects to bytes is up to you.

Keep in mind that `BinaryFormatter` has security problems.

**Comment by khteh** [comment]
That's why I mentioned "not a good one". Whihc binary serializer do you recommened? Does .net core 3 have a better binary serializer? Can we use the grpc/protobuf serializer?

**Comment by JamesNK** [comment]
Yes you can use the gRPC serializer, but like I already said **you must define a contract**. There is no automatic serialization.
