### ISSUE TITLE
I created a grpc project on vs that was not available

### ISSUE THREAD

**Issue by miaoyukai** [grpc/grpc-dotnet#557]
![7aa426f8ac25b6faceb232a63b78c5b](https://user-images.githubusercontent.com/38027640/65751371-f8cd4400-e13c-11e9-94e2-df7a28afe869.png)
As above, this is a new project.

**Comment by JamesNK** [comment]
The NuGet package didn't resolve (as indicated by the yellow warning on the icon)

If the problem continues then you should ask on https://github.com/NuGet/Home with more detail about why it didn't resolve.

**Comment by miaoyukai** [comment]
> The NuGet package didn't resolve (as indicated by the yellow warning on the icon)
> 
> If the problem continues then you should ask on https://github.com/NuGet/Home with more detail about why it didn't resolve.

I know the nuget package is not loaded, but this is a newly created project. Is this package fully compatible with 3.0?

**Comment by JamesNK** [comment]
Yes

**Comment by miaoyukai** [comment]
> Yes

Thank you.
