### ISSUE TITLE
ClassLibrary netstandard2.0 doesn't build .proto files

### ISSUE THREAD

**Issue by khteh** [grpc/grpc-dotnet#558]
I am using .Net Core 2.2. I have Protos/*.proto in a class library project:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Protobuf Include="Protos/*.proto" GrpcServices="Server"/>
    <PackageReference Include="Grpc.AspNetCore" Version="2.23.2"/>
    <PackageReference Include="Google.Protobuf" Version="3.9.2"/>
  </ItemGroup>
```
It doesn't build the .proto files. No .cs code is generated in the output folder. What do I miss? Thanks.

**Comment by khteh** [comment]
.Net Core 2.2 ClassLibrary needs to reference Grpc.Tools. This is not needed in .Net Core 3.0

**Comment by khteh** [comment]
Now I get the following error with the generated .cs files:
```
error CS0400: The type or namespace name 'Grpc' could not be found in the global namespace (are you missing an assembly reference?) 
```

**Comment by JamesNK** [comment]
Grpc.AspNetCore requires netcoreapp3.0.

You should reference Grpc.Core.Api in netstandard projects.

**Comment by diogonborges** [comment]
I know this is closed by I'm also failing to produce a simple scenario with Grpc.Core.Api.
gRPC.Protos as a netStandard2.1 project with the proto files.
gRPC.Server as a netcoreapp3.1 project referencing the gRPC.Protos project.
The gRPC.Server project can't see the gRPC.Protos namespaces.
