### ISSUE TITLE
Cannot compile and run gRPC Greeter template

### ISSUE THREAD

**Issue by joaoportela** [grpc/grpc-dotnet#559]
### Steps to reproduce

Follow the quickstart tutorial:
```bash
dotnet new grpc -o GrpcGreeter
cd GrpcGreeter
dotnet run
```

### Expected Result

Program builds and runs.

### Actual Result

Build fails with this output:

```txt
--grpc_out : error : protoc-gen-grpc: The system cannot find the path specified. [D:\dev\GrpcGreeter\GrpcGreeter.csproj]

The build failed. Fix the build errors and run again.
```

Tried using the Grpc.Core afterwards and ran into the same issue.

This makes me believe that this is the same issue as this one: [**Accented characters in nuget path breaks c# grpc tool compiler**](https://github.com/grpc/grpc/issues/17995)

**Comment by joaoportela** [comment]
### Workaround
While this isn't fixed, I'll post my workaround here:

1. (Optional) Create a junction link pointing to the a new directory (that doesn't have special characters)
    1.  For me it was `mklink /j "D:\.nuget" "C:\Users\João\.nuget"`
2. Change environment variable to the new directory "NUGET_PACKAGES=D:\.nuget\packages"

The junction link helps ease the transition: 

- packages still in old directory for instances that haven't seen yet the new env var
- avoids copying the directory contents to the new location

**Comment by JamesNK** [comment]
https://github.com/grpc/grpc/issues/17995 is where you should discuss Grpc.Tools issues.

This repository is for Grpc.AspNetCore and Grpc.Net.Client issues.

**Comment by joaoportela** [comment]
@JamesNK got it.

On that thread they're saying that is actually the tools fault. Do you happen to know the issue tracker for that?

**Comment by jtattermusch** [comment]
@joaoportela as mentioned in grpc/grpc#17995 the underlying issue might be in protoc. Protobuf (which protoc is part of) lives here: https://github.com/protocolbuffers/protobuf
