### ISSUE TITLE
Authentication failed - wrong status code client side

### ISSUE THREAD

**Issue by AnthonyGiretti** [grpc/grpc-dotnet#571]
Hi!

I experienced an issue with grpc-dotnet client side (app console)

When the server side (grpc-dotnet too) authentication fails, I receive (with the HttpClient client side) the wrong grpc status code: CANCELLED. According to gRPC spec I should receive instead UNAUTHENTICATED.

Thanks

**Comment by JamesNK** [comment]
You get a CANCELLED status code because the server returns a 400 (unauthorized) status code header. That is quite different from returning a 200 status code with an UNAUTHENTICATED grpc-status in the response trailer.

**Comment by JamesNK** [comment]
@jtattermusch Do you know of any clients or servers that have any built in support for mapping 401 to a gRPC status?

**Comment by AnthonyGiretti** [comment]
Thank you for the answer.
But allow me to disagree

The server returns 401 then it should be mapped to UNAUTHENTICATED, (Unauthenticated doesn't exist in http then it should be considered as Unauthorized).
In grpc specs UNAUTHENTICATED means: _The request does not have valid authentication credentials for the operation._

Then we cannot expect neither 200 (you are right) nor CANCELLED because in grpc world CANCELLED means: _The operation was cancelled, typically by the caller._

Here are GRPC statuses code: https://grpc.github.io/grpc/core/md_doc_statuscodes.html

Does it make sense or I'm totally wrong? 

Thanks!

**Comment by JamesNK** [comment]
My interpretation is the server should return 200 OK with a status of UNAUTHENTICATED. A way to get the behavior you want is to have middleware on the server that changes 401 status responses to 200 with an UNAUTHENTICATED trailer status for gRPC endpoints.

**Comment by JamesNK** [comment]
I found this. There maybe a mapping: https://grpc.github.io/grpc/cpp/md_doc_http-grpc-status-mapping.html

@jtattermusch Should the client map the gRPC status from these HTTP status codes?

**Comment by AnthonyGiretti** [comment]
Yes!
That's what I was fighting for :)



401 Unauthorized | UNAUTHENTICATED
-- | --



401 Unauthorized | UNAUTHENTICATED
-- | --



401 Unauthorized | UNAUTHENTICATED
-- | --

**Comment by chwarr** [comment]
The gRPC status is distinct from the underlying HTTP2 status. That being said, the [gRPC HTTP2 protocol spec suggests that clients synthesize gRPC statuses](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#responses) in cases when the underlying HTTP2 status "violates" the gRPC spec:

> Implementations should expect broken deployments to send non-200 HTTP status codes in responses as well as a variety of non-GRPC content-types and to omit **Status** & **Status-Message**. Implementations must synthesize a **Status** & **Status-Message** to propagate to the application layer when this occurs.

The C Core library maps from non-200 HTTP2 status codes to gRPC status values. A useful starting place is the `grpc_error_get_status` function, which [calls the `grpc_http2_error_to_grpc_status`
conversion function](https://github.com/grpc/grpc/blob/master/src/core/lib/transport/error_utils.cc#L93-L94). `grpc_error_get_status` is used, in turn, by [call's `set_final_status`](https://github.com/grpc/grpc/blob/a358d48f123cca42c47aaf37978f3c640cf823c3/src/core/lib/surface/call.cc#L737).

grpc-java [does something similar](https://github.com/grpc/grpc-java/blob/fa8f89a1a6302088f640c5592db258db5b4f83c2/core/src/main/java/io/grpc/internal/GrpcUtil.java#L268-L297) as [does grpc-go](https://github.com/grpc/grpc-go/blob/40ed2eb467471df2bd3c59e66cc5357159062d48/internal/transport/http_util.go#L303-L308).

**Comment by JamesNK** [comment]
Ok. grpc-dotnet should do this to.

**Comment by AnthonyGiretti** [comment]
Thank you!

**Comment by mcalvinsf** [comment]
Well I have upgraded to latest release and I still get the Status=Cancelled RpcException.

**Comment by SmRiley** [comment]
As of now, unauthorized access still returns operation cancel, is this by design or is it a bug?
Grpc.Core.RpcException:“Status(StatusCode="Cancelled", Detail="Bad gRPC response. Response did not have a content-type header.")”
