### ISSUE TITLE
Client stop receiving message

### ISSUE THREAD

**Issue by PwGiza** [grpc/grpc-dotnet#572]
I streaming message in Task from grpc service to client and after 99 package of data client stop receiving message. Im writing on server streamwriter from client to dictionary and on client side when I get data I try to send it to the server in another method. 

`var call = client.GetDataFromServer(new Empty())
{
  await foreach(var item in call.ResponseStream.ReadAllAsync())
{ 
await Task.Run(async () =>
{ 
await SendDataToServer(item, client)
});`

SendDataToServer
`var call2 = client.SendData()
await call2.RrequestStream.WriteAsync(item);`

Server still writing message(GetDataFromServer) but client don't do anything after 99 package. This only happen when I run SendDataToServer.

**Comment by JamesNK** [comment]
What is the logging output from the client and server? It is unlikely messages stopped without an error, and without knowing that error it is difficult to say what is wrong.

**Comment by JamesNK** [comment]
Closing for now. Can reopen in future if you still have this problem.
