### ISSUE TITLE
HTTP2 KeepAlive/PING control support

### ISSUE THREAD

**Issue by chrisdot** [grpc/grpc-dotnet#577]
Hi
Is there a way to control the HTTP2 keepalive? I need to know if my client is still there on the server side (in a long lived client streaming scenario).
I mean something like [there is in grpc core](https://github.com/grpc/grpc/blob/master/doc/keepalive.md)?
Thanks 
Christophe

BTW: Really nice to have a full grpc stack in .net core!!!

**Comment by JamesNK** [comment]
There is this setting in Kestrel:

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.0#keep-alive-timeout

Does that do what you want?

**Comment by JamesNK** [comment]
@Tratcher @halter73 Does the keep alive setting apply to HTTP/2 as well? The documentation links to an HTTP/1.1 spec.

**Comment by Tratcher** [comment]
All of those limits apply to HTTP/1.1 and HTTP/2. Http/2 has a series of additional limits under `Limits.Http2`. The KeepAliveTimeout value measures how long a completely idle connection will be kept.
Http/2 doesn't have a different Keep-Alive concept, right?

**Comment by chrisdot** [comment]
@JamesNK 
The feature you're making reference to is [HTTP/1.1 related](https://tools.ietf.org/html/rfc7230#section-6.5). As I undestand it, it is just a way for the server to know when a zombie HTTP can be closed.
Here I'm talking about [the pure HTTP/2 ping frame feature](https://http2.github.io/http2-spec/#PING) due to the multiplexed nature of a HTTP/2 connection, to detect if the idle (no current payload being tarnsmitted at the moment) is still up. 
So, @Tratcher  yes there is a different concept in HTTP/2 but I shouldn't have named it keepalive but PING. But I did that because of the naming in given the grpc-core [reference](https://github.com/grpc/grpc/blob/master/doc/keepalive.md).

**Comment by Tratcher** [comment]
Ah. Kestrel will acknowledge a Ping but it will not send any on its own, nor does it have an API to allow you to send one.

**Comment by chrisdot** [comment]
OK, I created a feature request for [kestrel](https://github.com/aspnet/AspNetCore/issues/15104) and [HttpClient](https://github.com/dotnet/corefx/issues/41852).

**Comment by JamesNK** [comment]
Thanks! The work for this is in other repos so closing.
