### ISSUE TITLE
grpc service gives error "Bad gRPC response. Expected HTTP status code 200. Got status code: 426"  when deployed on Azure where works fine locally when run on IIS Express

### ISSUE THREAD

**Issue by rupeshtech** [grpc/grpc-dotnet#578]
I have created a gRPC service.. 
Using gRPC service by using Client, which has gRPC Service reference.

Created a console app to test the service. When service is running locally (https://localhost:5001)  and **called from console app, works fine**.

**When service is deploy on Azure as Appservice, gives error: Bad gRPC response**. Expected HTTP status code 200. Got status code: 426 when being called from console app

**ErrorMessage: Bad gRPC response. Expected HTTP status code 200. Got status code: 426**

### What version of gRPC and what language are you using?
Grpc.AspNetCore Version="2.23.1"

### What operating system (Linux, Windows,...) and version?
Azure Appservice for windows
<PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UserSecretsId>xxxxxxxxxxxxxxxxxxxxxxxxx</UserSecretsId>
  </PropertyGroup>

###  .NET Core SDK
.NET core 3.0

### What did you do?
Create a sample gRPC .NET Core 3.0 application using visual studio.
create a client to consume the service. 
Deploy gRPC service to Azure as Appservice (windows).
Consume the service from a console app.

### How gRPC is being called?
Using service via client
` var channel = GrpcChannel.ForAddress("https://xxxx.azurewebsites.net");
            var client = new RequestorClient(channel);
            var response = SubmitRequest(client,request)`

in above code , it works fine  when url  is https://localhost:5001

### Publish setting
![image](https://user-images.githubusercontent.com/24852402/66132226-024f2400-e5f5-11e9-9d7e-ed5905dcc31c.png)

### What did you expect to see?
Successfull call to service, HTTP status code 200

### ErrorMessage
Bad gRPC response. Expected HTTP status code 200. Got status code: 426

### Stacktrace
"   at Grpc.Net.Client.Internal.GrpcCall`2.<GetResponseAsync>d__63.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n"

**Comment by rupeshtech** [comment]
saw this comment from other github issue on same topic


Can't host gRPC in IIS/Azure App Service.The HTTP/2 implementation of Http.Sys does not support HTTP response trailing headers which gRPC relies on.
--
Comment link: https://github.com/aspnet/AspNetCore/issues/9020#issuecomment-479600486

Issue link : https://github.com/aspnet/AspNetCore/issues/9020


So the conclusion is, Azure Appservice  (Linux or windows) doesnt hosting of support gRPC service. (reason can be found in the link of other issue)
And solution is to deploy it on Kubernetes.

Some Open Qs still remain: **Will it work on Web Apps for Container?**

**Comment by JamesNK** [comment]
Hi

Please keep discussion about gRPC + Azure at https://github.com/aspnet/AspNetCore/issues/9020. Repost your questions there.

Multiple issues discussing this will create confusion.

**Comment by rupeshtech** [comment]
I have created step by step guide to create test and deploy grpc service using .NET Core 3.0
https://github.com/rupeshtech/k8s-grpc-dotntecore
