### ISSUE TITLE
In examples the proto package names should be all lowercase

### ISSUE THREAD

**Issue by Ciantic** [grpc/grpc-dotnet#580]
This is very minor thing, but package names in the protobuf example files such as:

https://github.com/grpc/grpc-dotnet/blob/master/examples/Greeter/Proto/greet.proto

Should be in lowercase like `package greet;` right now they are PascalCased e.g. `package Greet;` as if it's some .NET namespace. Same applies to all examples, the package names should be in lowercase.

**Comment by JamesNK** [comment]
Is that a convention? Do you know if it is documented anywhere or is it sort of a general consensus?

**Comment by Ciantic** [comment]
It comes from this:

https://developers.google.com/protocol-buffers/docs/style

> Files should be named lower_snake_case.pro
> Package name should be in lowercase, and should correspond to the directory hierarchy. e.g., if a file is in my/package/, then the package name should be my.package.

But generally all text is lower_snake_case in protobufs.

**Comment by JamesNK** [comment]
Ok, I'll update samples, documentation and template.

**Comment by JamesNK** [comment]
Done
