### ISSUE TITLE
Bump version of Google.Protobuf to 3.10.0

### ISSUE THREAD

**Issue by nagytech** [grpc/grpc-dotnet#582]
### Is your feature request related to a problem? Please describe.
The current version of `grpc-dotnet` references an older version of `Google.Protobuf` (3.9.1).  In 3.9.1, classes like `Google.Protobuf.Reflection.DescriptorReflection.Descriptor` protected which means they cannot be referenced from a compiled proto that uses "google/protobuf/descriptor.proto".  This issue also occurs when attempting to reflect on other object like `MethodOptions`.  

In Google.Protobuf 3.10.0, these methods are now public.

https://github.com/protocolbuffers/protobuf/blob/master/csharp/src/Google.Protobuf/Reflection/Descriptor.cs#L15

(See, also https://github.com/protocolbuffers/protobuf/commit/5caa44e0564bae42e00900c73c20e0ec2c76b058#diff-0cbedbafd7e1b4826bfd9c967656a2a7)

### Describe the solution you'd like
Bump GoogleProtobufPackageVersion to 3.10.0:

-    <GoogleProtobufPackageVersion>3.9.1</GoogleProtobufPackageVersion>
+    <GoogleProtobufPackageVersion>3.10.0</GoogleProtobufPackageVersion>

### Describe alternatives you've considered
None.

### Additional context
Will submit a PR shortly.

**Comment by JamesNK** [comment]
Fixed
