### ISSUE TITLE
Please set names for all gRPC threads

### ISSUE THREAD

**Issue by daveyostcom** [grpc/grpc-dotnet#599]
It can be bewildering when there is trouble deep in a gRPC thread. Sometimes it might be nice to know a little more about what's going on.

It would be nice if every thread created by gRPC would have a name that starts with "gRPC" plus any other useful information that can be added, for example, the name of the service being worked on.

Example:
    Worker 2: BidiHello receive @1960820

<img width="431" alt="image" src="https://user-images.githubusercontent.com/8748/66548513-3bf0c500-eaf6-11e9-99a0-7b5719f2fc82.png">

**Comment by JamesNK** [comment]
Is this for Grpc.Core or grpc-dotnet?

grpc-dotnet doesn't create any threads. Work is done on threads in the threadpool via tasks but I'm not sure if you can name those.

**Comment by davidfowl** [comment]
GRPC doesn't use create any threads so this can't really be a thing. What you really want to look at is "activities/requests" and the tool you're using above doesn't support for that it seems.

**Comment by JamesNK** [comment]
We can't improve the thread names: https://stackoverflow.com/questions/13762286/how-can-i-assign-a-name-to-a-task-in-tpl

If you have future ideas to improve debugging then we're happy to hear them.
