### ISSUE TITLE
Set up benchmark scenarios

### ISSUE THREAD

**Issue by JunTaoLuo** [grpc/grpc-dotnet#6]
This issue will track the work needed to set up benchmarking scenarios on our side for grpc-dotnet. More details to follow. This will help us compare performance metrics against existing implementation as well as track improvements when we optimize the implementation.

cc @shirhatti @JamesNK

**Comment by JamesNK** [comment]
Would be ideal to setup on aspnet/benchmarks to track changes over time

**Comment by JunTaoLuo** [comment]
@shirhatti, can you link the current benchmarks?

Benchmarks we would still like to add:
- Raw Unary call with HTTP message instead of c core client
- comparison JSON HTTP2

**Comment by JamesNK** [comment]
https://aka.ms/aspnet/benchmarks

Custom benchmarks

**Comment by JamesNK** [comment]
todo: The benchmarks are running on Linux and failing on Windows. Find out why

**Comment by JamesNK** [comment]
DONE
