### ISSUE TITLE
Investigate gRPC compression performance

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#602]
I think we might be able to optimize compression to avoid additional array allocations.

**Comment by zsybupt** [comment]
```c#

                if (output.TryGetBuffer(out ArraySegment<byte> buffer))
                {
                    if (buffer.Offset == 0 && buffer.Count == buffer.Array?.Length)
                    {
                        result = buffer.Array;
                        return true;
                    }
                }

                result = output.ToArray();
                return true;
```

**Comment by zsybupt** [comment]
if (output.TryGetBuffer(out ArraySegment<byte> buffer))
                {
                    if (buffer.Offset == 0 && buffer.Count == buffer.Array?.Length)
                    {
                        result = buffer.Array;
                        return true;
                    }
                }

                result = output.ToArray();
                return true;
