### ISSUE TITLE
Docs on gRPC versioning

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#604]
How to version gRPC calls. What works, what doesn't, tools, etc

**Comment by beefo** [comment]
@JamesNK is there any information about this for gRPC in general?

A related question: my instinct is to want to give our gRPC and REST APIs dissimilar and non-default base routes (running in tandem on the server). Though this may be in contradiction to gRPC design in some way. Something similar to:
`var channel = GrpcChannel.ForAddress("https://127.0.0.1/grpc/");`

**Comment by chwarr** [comment]
@beefo, for the base route question, you may want to look at https://github.com/grpc/grpc-dotnet/issues/110. That looks to my like what you're asking. (TL;DR: not supported, may need to go through the [gRPC RFC](https://github.com/grpc/proposal#grpc-rfcs) process for cross-implementation compat.)

**Comment by chwarr** [comment]
@beefo, for the versioning question, a resource is the [Proto3 Updating A Message Type][ver] documentation. This talks about what changes are safe to make to a message.

I've not found good documentation about changes that can be made to a service. (E.g., call cardinality changes)

[ver]: https://developers.google.com/protocol-buffers/docs/proto3#updating

**Comment by beefo** [comment]
Thanks @chwarr, very helpful.

**Comment by dragonly** [comment]
This is really a problem for day-to-day development works. We have flexible url patterns to play with in restful world like `api.domain.com/v2/`, but little (seems) in the grpc world.
For now I only come up with a solution that change .proto package name from `PackageName` to `PackageName_v2` and rewrite a new version of .proto file, then serve v2 side by side with v1 on the same domain, and config proxy server (nginx/envoy/istio virtualservice) to distinguish http2 paths of `/PackageName` and `/PackageName_v2`

**Comment by jtattermusch** [comment]
@dragonly   if you want to differentiate between multiple versions (mutually incompatible) of the same API, add the version number of that API  to the proto namespace - it's a best practice to do that anyway (adding `.v1`, `.v2` suffix).
FTR, see https://github.com/googleapis/googleapis/tree/master/google/datastore/v1
