### ISSUE TITLE
how to Bulid grpc Service and CLient in One project and one exe

### ISSUE THREAD

**Issue by heartacker** [grpc/grpc-dotnet#605]
hi I am using vs 2019 to creat gRPC service and Client within one project in c#, 
```
    <Protobuf Include="Protos\greet.proto" GrpcServices="Server" />
    <Protobuf Include="Protos\greet.proto" GrpcServices="Client" /> 
```
it seems not work and  either-or; 
but i just wanna to build my service and client to one  EXE file. and how to do that?thx a lot

**Comment by JamesNK** [comment]
Just have it once and set GrpcServices to Both:

```xml
    <Protobuf Include="Protos\greet.proto" GrpcServices="Both" /> 
```

**Comment by TopSwagCode** [comment]
Hi. Awesome. Fixed my issue. But where is the documentation for this ❓

**Comment by JamesNK** [comment]
Them is some on troubleshooting page. Will move it to the Protobuf on C# page - https://github.com/dotnet/AspNetCore.Docs/pull/19152
