### ISSUE TITLE
Add container example

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#607]
Example of a gRPC project that runs server in a container.

**Comment by gitting** [comment]
I tried to containerize a grpc service sample but it doesn't appear I can call it via http. My scenario is to put all services in containers behind nginx which would handle TLS.

I tried to configure the service like [this](https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-5.0#unable-to-start-aspnet-core-grpc-app-on-macos) but it wouldn't work even before dockerizing.

**Comment by JamesNK** [comment]
Added: https://github.com/grpc/grpc-dotnet/tree/master/examples/Container

TODO: Add description to examples README.md
