### ISSUE TITLE
launchSettings.json isn't considered when server is launched directly

### ISSUE THREAD

**Issue by gsantopaolo** [grpc/grpc-dotnet#616]
HI all, totally new to gRPC here.
I'm looking at [all the samples](https://github.com/grpc/grpc-dotnet/tree/master/examples).
If you try to change the launchSettings.json - applicationUrl port in nomething different than "https://localhost:5001" (eg. https://localhost:5002), it seems that if you run the server outside the VS IDE (eg, browse the correct bin folder and double click on the server executable) the server does not read the new parameter and starts on "https://localhost:5001".
If you try to launch the server for debug from the VS IDE the launchSettings.json are then used and the server starts on the modified url port (eg  https://localhost:5002).
Am I missing something here?

**Comment by JamesNK** [comment]
I believe launchSettings.json is only for use at development. Launching via VS uses it, and launching via `dotnet run` uses it.

If you publish an executable then you need to customize Kestrel endpoints via appsettings.json or Program.cs.

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.0#development

**Comment by LevanJ** [comment]
I was trying the same thing. Running directly the .exe file for testing the server. The server was running with the default ports:  `"http://localhost:5000;https://localhost:5001"`.  Finally, I changed it from `appsettings.json` for the .exe file.

`  "AllowedHosts": "*",
  "Kestrel": {
    "Endpoints": {
      "Http": {
        "Url": "https://localhost:7005",
        "Protocols": "Http1AndHttp2"
      },
      "gRPC": {
        "Url": "http://localhost:5005",
        "Protocols": "Http2"
      }
    }`
