### ISSUE TITLE
Add support for Google.Api Namespace in protoc

### ISSUE THREAD

**Issue by whiteworker** [grpc/grpc-dotnet#619]
<b>Thanks for all the work you put into this library!</b>
<b>Is there any plans to support Google.Api ?</b>
I want to use protoc tool to generate swagger json doc,so i need import google/api/annotations.proto in proto files.
Protoc tool generate swagger json doc is well,but Grpc.Tools auto-generated files can't be complie.
It showed global::Google.Api can't find in any namespace
There is my protoc
```proto
syntax = "proto3";

option csharp_namespace = "gRPCService";

import "google/api/annotations.proto";

package AI;

service AIServer {
  rpc MachineAnswer (MachineAnswerRequest) returns (MachineAnswerResponse){
    option (google.api.http) = {
      post: "/ask"
      body: "*"
  };
  };
}

message MachineAnswerRequest {
  string Question = 1;
}

message MachineAnswerResponse {
  string Answer = 1;
}
```
Thanks for help!

**Comment by JamesNK** [comment]
My guess is there is a package that you need to reference that contains Google.Api.

Otherwise you should add this issue to https://github.com/grpc/grpc. Code generation is in Grpc.Tools. grpc-dotnet just references it. Someone who knows more about Grpc.Tools should be able to help you there.

**Comment by aamirbutt** [comment]
Hi @JamesNK . Do you have any solution for this, or do you know of any issue where this is being tracked? I am running into the same problem, and can't seem to find the appropriate package.

**Comment by aamirbutt** [comment]
Never mind, found it. 
Putting it here for somebody like me in the future.
You need to add `Google.Api.CommonProtos`
