### ISSUE TITLE
Consider package that integrates Grpc.HealthCheck with ASP.NET Core health checks

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#622]
There might be value in writing a package that automatically integrates Grpc.HealthChecks with ASP.NET Core health checks

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks

Related: https://github.com/grpc/grpc-dotnet/issues/603

**Comment by JamesNK** [comment]
Done with https://github.com/grpc/grpc-dotnet/pull/657

Currently package is not published. Will consider publishing if there is interest.

**Comment by bourquep** [comment]
@JamesNK I'd love to have access to a published package for this!

**Comment by 7amou3** [comment]
@JamesNK any news on the grpc healthcheck nuget package?

**Comment by mathieu-benoit** [comment]
Just curious, could https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks be a good place to have it?

**Comment by Eagle3386** [comment]
@JamesNK Sorry for interrupting you, but when does the package leave its pre-release state, i. e. when is 2.42.0 released?
