### ISSUE TITLE
Will .netframework 4.5+ be supported for Grpc.Net.Client 

### ISSUE THREAD

**Issue by speed2048** [grpc/grpc-dotnet#625]
I have .netframework 4.7.2 applications and would like to use Grpc.net.client for this framework but when I use nuget to install I cannot because the framework is not supported.

I know there is a legacy grpc package but configuration / setup ( IE https support ) is a lot more work.

Thanks in advance.

**Comment by JamesNK** [comment]
No plans. It requires HTTP2 and that’s not supported there

**Comment by Gopichandar** [comment]
Is there a workaround to Connect .Net Framwork 4.5+ clients to .NetCore grpc?  Please suggest

**Comment by JamesNK** [comment]
Use Grpc.Core package

**Comment by Gopichandar** [comment]
Thanks for the reply. I'm trying to get some samples on this.  Do we have any sample on how to connect using Grpc.core on .Net Framework client to connect to the Grpc Server?

**Comment by icnocop** [comment]
@Gopichandar https://github.com/grpc/grpc/tree/master/src/csharp/Grpc.Examples.MathClient

**Comment by Gopichandar** [comment]
Thanks alot @icnocop , the link really helps.

**Comment by mujgancihan** [comment]
Hi @Gopichandar , did you find a sample in Net Framework?

**Comment by sabyabr** [comment]
Dumb question, why is Grpc.Net.Client produces .net standard and not .net core if it doesn't support .net framework.

**Comment by JinsPeter** [comment]
@sabyabr Haha.. Is it really a dump question? It is not.
Grpc.Net.Client targets NetStandard 2.1 where the only available implementation is .NET Core 3.1. 
Microsoft has informed it has no plans to alter .NET full framework to target .NetStandard 2.1 due to a lot of breaking Api.
Who is dump now?

**Comment by IcyEagle** [comment]
@JinsPeter hi there!

Indeed, Grpc.Net.Client requires NetStandard 2.1, but what about Grpc.Net.Client.Web which (as far as I know) is used for gRPC-Web implementation? I spent a day, looking for a way how to run gRPC-over-web with .NET 4.x (damned Unity3D!) and didn't succeed. It's ridiculous since actually, grpc-web channel doesn't need HTTP/2 features to communicate with the server (its HTTP 1.1 proxy actually) but it depends on Grpc.Net.Client which in its turn requires .NET 5

**Comment by Gopichandar** [comment]
> Hi @Gopichandar , did you find a sample in Net Framework?

 refer https://github.com/grpc/grpc/tree/master/src/csharp/Grpc.Examples.MathClient

**Comment by karuguvel** [comment]
> > Hi @Gopichandar , did you find a sample in Net Framework?
> 
> refer https://github.com/grpc/grpc/tree/master/src/csharp/Grpc.Examples.MathClient

Not available this repository.
can you please share the repos if you have
