### ISSUE TITLE
Using multiple clients of the same Grpc service

### ISSUE THREAD

**Issue by ahaeber** [grpc/grpc-dotnet#627]
We have a broker service that receives gRPC messages and relays them to various services depending on the message.

For the Broker we have defined a gRPC service (say "BrokerService"). The services it depends on all implement another gRPC service (say "AnotherService"). Is it possible using ASP.NET Core dependency injection to  handle this scenario? It appears that the best we can get is a IEnumerable<AnotherService> and we would have to loop through that list to find the target service. (And that is assuming we know the services during startup, although we desire to use Kubernetes Client API to watch for them).

[GrpcClientFactory](https://github.com/grpc/grpc-dotnet/tree/master/src/Grpc.Net.ClientFactory) seems to be helpful for this scenario (i.e., to cache clients), however it appears that it is only supposed to be used from dependency injection. Are there any plans to make it non-internal? Or is there a better approach to implement this scenario?

**Comment by JamesNK** [comment]
You can have multiple clients of the same type but calling different servers:

```csharp
services.AddGrpcClient<Greet.GreeterClient>("BrokerService", o => o.Address = address);
services.AddGrpcClient<Greet.GreeterClient>("AnotherService", o => o.Address = address);
```

```csharp
public class YourType(GrpcClientFactory clientFactory)
{
    var brokerServiceGreeter = clientFactory.CreateClient<Greet.GreeterClient>("BrokerService");
    var anotherServiceServiceGreeter = clientFactory.CreateClient<Greet.GreeterClient>("AnotherService");
}
```

**Comment by ahaeber** [comment]
Thanks for the help!
