### ISSUE TITLE
Grpc tool in VS2019 do not build classes when the asp.net project is a service fabric service.

### ISSUE THREAD

**Issue by Dolphinsimon** [grpc/grpc-dotnet#630]
### What version of gRPC and what language are you using?
Grpc.AspNetCore/Grps.Tools 2.24.0 
C# 
### What operating system (Linux, Windows,...) and version?
Windows 10 18362.418

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET SDK 3.1.100-preview1-014459

### What did you do?
Just add a new asp.netcore mvc project as a stateless service in Service Fabric services.
When build the project, the *.proto files will not generate classes as expected.

### What did you expect to see?
The Grpc classes will be generate when build the project.

### What did you see instead?
Can not find any classes in the build output directory.

### Anything else we should know about your project / environment?
VS2019 16.4.0 Preview 2.0

**Comment by JamesNK** [comment]
I couldn't reproduce this. I created a new service fabric app and added an ASP.NET Core website. I added Grpc.AspNetCore and a proto reference and it appears to work:

![image](https://user-images.githubusercontent.com/303201/68080318-cd392a00-fe5d-11e9-8c2e-6887d0ed0f53.png)

**Comment by Dolphinsimon** [comment]
> I couldn't reproduce this. I created a new service fabric app and added an ASP.NET Core website. I added Grpc.AspNetCore and a proto reference and it appears to work:
> 
> ![image](https://user-images.githubusercontent.com/303201/68080318-cd392a00-fe5d-11e9-8c2e-6887d0ed0f53.png)

Thanks for your reply. I have put more details for my project.
Here is my project file:
![QQ截图20191103215022](https://user-images.githubusercontent.com/4425053/68086204-f967a180-fe83-11e9-84c4-53c44b73964b.png)

Here is my proto file:
![QQ截图20191103215216](https://user-images.githubusercontent.com/4425053/68086224-3a5fb600-fe84-11e9-934f-97ad11f41e4f.png)

Here is all files in the output folder:
![QQ截图20191103215346](https://user-images.githubusercontent.com/4425053/68086236-814dab80-fe84-11e9-9bee-b9f548119f6a.png)

None of any classes were there.

**Comment by JamesNK** [comment]
The gRPC types are compiled into the DLL that references the proto file. They aren't in their own DLL.

If you wanted you could make a netstandard2.0 project that is just for the proto file, and then reference that from other projects.

**Comment by Dolphinsimon** [comment]
> The gRPC types are compiled into the DLL that references the proto file. They aren't in their own DLL.
> 
> If you wanted you could make a netstandard2.0 project that is just for the proto file, and then reference that from other projects.

Sorry, I don't understand. I think we are talking about why the grpc tool doesn't generate the classes for .proto files in my project. 

You can see all files start with Authorization* in my last comment. None of the grpc service classes were found.

**Comment by JunTaoLuo** [comment]
What exactly are you not finding? I see that your project is rather typical so I think it might just be a misunderstanding in how gRPC projects are built.

When you build your project, the Grpc.Tools contains targets that compile your proto files into C# files. In your case these files should appear as obj/{Debug/Release}/netcoreapp3.0/{Authorization.cs/AuthorizationGrpc.cs}. Are these the files you are looking for? FYI, you don't need to reference Grpc.Tools if you already reference Grpc.AspNetCore since it's brought in as a transitive reference.

The tool also automatically include these generated C# files in the project build so the generated types will be compiled into the assembly Authorization.dll which you are examining. The gRPC types should be contained in that assembly under the namespace Authorization.Protos which you specified in your proto file. 

Let me know if you are still missing files and we can look in the binary logs for why it might not be working for you.

**Comment by Dolphinsimon** [comment]
> What exactly are you not finding? I see that your project is rather typical so I think it might just be a misunderstanding in how gRPC projects are built.
> 
> When you build your project, the Grpc.Tools contains targets that compile your proto files into C# files. In your case these files should appear as obj/{Debug/Release}/netcoreapp3.0/{Authorization.cs/AuthorizationGrpc.cs}. Are these the files you are looking for? FYI, you don't need to reference Grpc.Tools if you already reference Grpc.AspNetCore since it's brought in as a transitive reference.
> 
> The tool also automatically include these generated C# files in the project build so the generated types will be compiled into the assembly Authorization.dll which you are examining. The gRPC types should be contained in that assembly under the namespace Authorization.Protos which you specified in your proto file.
> 
> Let me know if you are still missing files and we can look in the binary logs for why it might not be working for you.
Yes, I am looking for the C# *.cs files that generated by Grpc.Tools.

**Comment by JunTaoLuo** [comment]
Is there any issues with finding the files? If so, please mark this issue as closed.

**Comment by Dolphinsimon** [comment]
> Is there any issues with finding the files? If so, please mark this issue as closed.

In my project, I cannot find any *.cs files generated by Grpc.Tools in the following path obj/{Debug/Release}/netcoreapp3.0/{Authorization.cs/AuthorizationGrpc.cs}.

**Comment by Dolphinsimon** [comment]
I have tested my project in another PC with newer VS 2019 Preview.  I can't find the generated cs files in the output folder yet.

**Comment by JamesNK** [comment]
You're going to need to upload a repo of your app because I'm not able to reproduce this.

Generated cs files:
![image](https://user-images.githubusercontent.com/303201/70112648-e0d4ec00-16ba-11ea-92a0-82cad29b4126.png)

Output directory containing compiled web app dll:
![image](https://user-images.githubusercontent.com/303201/70112782-63f64200-16bb-11ea-9200-8a64224086d3.png)

Types in compiled dll:
![image](https://user-images.githubusercontent.com/303201/70112788-6c4e7d00-16bb-11ea-8087-247783482c4c.png)

**Comment by Dolphinsimon** [comment]
> You're going to need to upload a reproduction of your app because I'm not able to reproduce this.
> 
> Generated cs files:
> ![image](https://user-images.githubusercontent.com/303201/70112648-e0d4ec00-16ba-11ea-92a0-82cad29b4126.png)
> 
> Output directory containing compiled web app dll:
> ![image](https://user-images.githubusercontent.com/303201/70112782-63f64200-16bb-11ea-9200-8a64224086d3.png)
> 
> Types in compiled dll:
> ![image](https://user-images.githubusercontent.com/303201/70112810-80927a00-16bb-11ea-9805-aa0d8e8e666b.png)

I have uploaded my project to OneDrive [here](https://1drv.ms/u/s!Ak8xZo_dxVop0cE1AlP5Zm0L19uplA?e=SPgI59)

**Comment by JamesNK** [comment]
Types are generated in VS:

![image](https://user-images.githubusercontent.com/303201/71537639-befe1a80-2983-11ea-9603-a45afe55aa97.png)

And I can see them in the assembly:

![image](https://user-images.githubusercontent.com/303201/71537643-ccb3a000-2983-11ea-9678-82dbcd8c52c1.png)

**Comment by Dolphinsimon** [comment]
> Types are generated in VS:
> 
> ![image](https://user-images.githubusercontent.com/303201/71537639-befe1a80-2983-11ea-9603-a45afe55aa97.png)
> 
> And I can see them in the assembly:
> 
> ![image](https://user-images.githubusercontent.com/303201/71537643-ccb3a000-2983-11ea-9678-82dbcd8c52c1.png)

Thanks for your testing. I've checked the \obj\Debug\netcoreapp3.0\win7-x64 directory, I can find the
AuthorizationGrpc.cs file now.
I was tried to find the file in \bin instead of \obj. This was my mistake.
Apologize for that.
