### ISSUE TITLE
use of PEM files, WPF grpc server and IIS usage

### ISSUE THREAD

**Issue by lonewolfnsp** [grpc/grpc-dotnet#631]
I'm sorry if I might have missed any articles on my queries.. but I've fumbled around and couldn't find any useful info, so I have no choice but to ask here. Please bear with me.. 

1. I understand that the new grpc-dotnet does not support pem files on server side which is the way grpc-C core behaved for .net. I've used openssl to generate the pem files and pfx file like this:
openssl req -x509 -newkey rsa:4096 -keyout private.pem -out public.pem -days 365 -nodes -subj /CN=localhost 
and use 
openssl pkcs12 -export -in public.pem -inkey private.pem -out mycert.pfx

the pfx is set up in the grpc service under kestrel segment in the appsettings.json file. 
BUT 
I can't find any useful info on how to load the public.pem into the client's GrpcChannelOptions, though I've used SslCredentials to load the file's content. So my question is, is this even possible? if so, how?

2. Is it possible to have a WPF app (.net core 3) host a grpc server (.net core 3)? I was able to do this easily using the original grpc for C# but can't find any way to config kestrel since WPF does not have kestrel.. 

3. Using the grpc-C core, I was able to have an ASP.NET core web API hosted in IIS, using the developer SSL cert or any CA cert, and GRPC server in the same app, listening on a different port, using a different TLS cert.. is this even possible for this grpc implementation? it seems to me once kestrel is configured, it applies to both ASP.NET web app and grpc.. can they use different ports and differnt certs? the web app would still use whatever http/https ports and cert IIS is set to, independent of kestrel, as usual, while GRPC would use the http2 port defined in kestrel.. is this possible? if so, how?

**Comment by davidfowl** [comment]
> Is it possible to have a WPF app (.net core 3) host a grpc server (.net core 3)? I was able to do this easily using the original grpc for C# but can't find any way to config kestrel since WPF does not have kestrel..

AFAIK it should just work if you add the package. It should add a “FrameworkReference” to Microsoft.AspNetCore.App. Which you can do from any .NET Core project.

> Using the grpc-C core, I was able to have an ASP.NET core web API hosted in IIS, using the developer SSL cert or any CA cert, and GRPC server in the same app, listening on a different port, using a different TLS cert.. is this even possible for this grpc implementation? it seems to me once kestrel is configured, it applies to both ASP.NET web app and grpc.. can they use different ports and differnt certs? the web app would still use whatever http/https ports and cert IIS is set to, independent of kestrel, as usual, while GRPC would use the http2 port defined in kestrel.. is this possible? if so, how?

Spin up a new host with kestrel in the same application and it’ll work. If you need a sample I can provide one later but it’s basically just making a separate universe in the same app (which is doable)

**Comment by lonewolfnsp** [comment]
@davidfowl, thanks for advise but I don't think for WPF to use groc-dotnet is that straight as the http2 server is provided by kestrel, which is only available in web server apps like web API, web MVC etc. WPF isn't that kind of web server app, so there's no kestrel in the appsettings.json that I can configure. Using the C-core grpc, this is indeed easy as it's the same regardless of whether it's web server app, console or WPF/Winform since the Server class is a grpc type, not kestrel. 

As for ASP.NET core web server app having grpc server using different ports and TLS cert, seriously, I don't know what you meant by having a differnt host. There is only 1 appsettings.json, and in this file, there is only 1 kestrel setting. I know setting kestrel protocol to http1And2 will enable the web app and grpc to work in the same app, but this would share the same listening port for kestrel. And anyway, would be "masked" by IIS once hosted in it. So if the original kestrel says port 5001, and IIS https port is set to say 445, then external apps have to connect to port 445 and not 5001. So my assessment is it's not so straightforward.. The C-core grpc is totally independent of ASP.NET, thus I know it can handle such scenario.. but this new grpc-dotnet uses asp.net and kestrel, so I'm really confused..  another way to look at it is like having web API and websocket on the same app, but each uses a different port..  you can't isn't it? IIS http/https port setting is per app pool, not per feature. 

Can someone in MS please confirm if this is a limitation of the new grpc-dotnet?

Also, anyone has any insights on the pem file being used by client? 

And is it true that a grpc service can't be hosted in IIS?

**Comment by davidfowl** [comment]
> @davidfowl, thanks for advise but I don't think for WPF to use groc-dotnet is that straight as the http2 server is provided by kestrel, which is only available in web server apps like web API, web MVC etc. WPF isn't that kind of web server app, so there's no kestrel in the appsettings.json that I can configure. Using the C-core grpc, this is indeed easy as it's the same regardless of whether it's web server app, console or WPF/Winform since the Server class is a grpc type, not kestrel.

I don't know what you mean. Can you clarify? WPF isn't special, it's just .NET Code. Kestrel is the webserver handling the HTTP/2 protocol. You can just add a reference to ASP.NET in your WPF project and it'll work like magic.

> As for ASP.NET core web server app having grpc server using different ports and TLS cert, seriously, I don't know what you meant by having a differnt host. There is only 1 appsettings.json, and in this file, there is only 1 kestrel setting. I know setting kestrel protocol to http1And2 will enable the web app and grpc to work in the same app, but this would share the same listening port for kestrel. And anyway, would be "masked" by IIS once hosted in it. So if the original kestrel says port 5001, and IIS https port is set to say 445, then external apps have to connect to port 445 and not 5001. So my assessment is it's not so straightforward.. The C-core grpc is totally independent of ASP.NET, thus I know it can handle such scenario.. but this new grpc-dotnet uses asp.net and kestrel, so I'm really confused.. another way to look at it is like having web API and websocket on the same app, but each uses a different port.. you can't isn't it? IIS http/https port setting is per app pool, not per feature.

Might be easier if I just give you a sample. You can write code to spin up another server in the same process.

> And is it true that a grpc service can't be hosted in IIS?

Yes that's true. The features aren't yet available (like response trailers) to make grpc work natively in IIS.

Here are the samples https://github.com/davidfowl/gRPCSamples.

> Also, anyone has any insights on the pem file being used by client?

@bartonjs? Do you know if x509Certificate supports PEM files

**Comment by bartonjs** [comment]
> Do you know if x509Certificate supports PEM files[?]

It supports a single-PEM (just "-----BEGIN CERTIFICATE-----(\r)\nbase64(\r)\n-----END CERTIFICATE-----"), but not a multi-PEM (either multiple certs or a cert and a key).

The only single-file representation that can load a private key along with a cert is PFX/PKCS12.

**Comment by lonewolfnsp** [comment]
@bartonjs , yes, I only need to load the cert in the client.. as I mentioned, I combined the private key file and cert file into a single pfx loaded into the server. So the client side only needs to load the cert pem file to authenticate with the server. Could you please show me how to load this on the client side? Last time using grpc.Core, I was able to do it using Channel(<address of server>, <pem file content>).. but now with the new GrpcChannel,.FraomAddress, I can't do it that way,  I tried passing the SslCredential in the Credential property of ChannelOptions, but it generated exception at runtime..  could you please show me how to do it?

**Comment by bartonjs** [comment]
@lonewolfnsp No idea how to do it in the context GRPC (I've never looked at what is in this project, I own certs at the lower level).  

From `X509Certificate2`'s perspective, it's either `new X509Certificate2(pathToFile)` or `new X509Certificate2(asciiBytesFromPemText)`.

**Comment by JamesNK** [comment]
gRPC uses `HttpClient` internally. I don't know the details of how it resolves certificate when making a https request. As far as I can tell the only time you need to specify a certificate to it is when you're using client certificate authentication.

https://docs.microsoft.com/en-us/aspnet/core/grpc/authn-and-authz?view=aspnetcore-3.0#client-certificate-authentication

**Comment by lonewolfnsp** [comment]
@davidfowl , I created a WPF (.net core) app in VS2019.. added Grpc.Tools, Grpc.aspnetcore and protobuf nuget packages.. and NO.. there is no kestrel, no appsettings.json in WPF.. so basically, no way to even add kestrel in.. online examples all show WPF being used as a grpc client talking to a grpc service.. WPF as a client is easy.. but as a grpc server, at least for the new grpc-dotnet, isn't so straightforward..  I was able to easily do it using the grpc.Core though.. just instantiate a Server object and configure it.. but how do I instantiate a kestrel object? 

As for pem certificate being used in grpc client, it was very easy with grpc.Core.. but seems no one has any idea how to even do it in grpc-dotnet..  wonderful.. so much for grpc being "first class" support in .net core.. 

grpc.Core is way easier to use..  :'(

**Comment by JamesNK** [comment]
David create a sample of WPF + Kestrel right here, just for you: https://github.com/davidfowl/gRPCSamples/tree/master/WpfAppWithGrpcServer

**Comment by lonewolfnsp** [comment]
@JamesNK, thank you for your kind help.. I've looked through it.. man! very different from the way the samples are written, like Greeter, Certifier etc..  that's why I said, grpc.Core is way easier to use, because no matter what type of app, it's the same way of instantiating Server..  

case in point, the WPF app's kestrel can't use appsettings.json to config.. 

as for cert pem loading on client, basically i've existing java and asp.net web api grpc clients connecting to the server. The existing server is based on .net core 2.2 and grpc.Core.. so it's using 2 pem files (private key pem+certificate pem). I'm investigating upgrading to .net core 3 and along the way upgrade the grpc to use the new grpc-dotnet.. without affecting the clients.. so basically client would still be using the certificate pem to connect in.. to ensure clients are not affected, I have to first test it out.. thus the need to find out how to load the cert pem in the client..  no doubt I can still use grpc.Core's client to do it.. but I would like to find out how different is the grpc-dotnet's way of doing that.. 

the samples provided with the grpc-dotnet repo is really lacking.. a sample showing how to have a grpc server in a plain console, with a grpc client in another plain console would have gone a long way to clear things up, rather than keep pushing for grpc service or asp.net app.. from the plain console app, at least I could "extrapolate" into how WPF can use it.. 

That said, the IHost way still looks like a hack to me.. as if forcing it into WPF.. but still, thanks David for spending the time to write that sample.. I'll try it out. :) 

thank you guys for helping me. merci beaucoup :)

**Comment by JamesNK** [comment]
> the samples provided with the grpc-dotnet repo is really lacking.. a sample showing how to have a grpc server in a plain console, with a grpc client in another plain console would have gone a long way to clear things up, rather than keep pushing for grpc service or asp.net app.. from the plain console app, at least I could "extrapolate" into how WPF can use it..

There is one, right here: https://github.com/grpc/grpc-dotnet/tree/master/examples/Worker

**Comment by lonewolfnsp** [comment]
@davidfowl , sorry to trouble you again.. now that I've a little more experience with grpc-dotnet, I created a new WPF (.net core) app, and used your codes for the grpc server in WPF and I got error.. the error: Error	CS1061	'IServiceCollection' does not contain a definition for 'AddStandaloneGrpcServer' and no accessible extension method 'AddStandaloneGrpcServer' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)	WPFGrpcSvr	D:\VS Projects\ChatterGrp		Active
 

I've added the packages as seen in your example's csproj, reproduced ehre:

<PackageReference Include="Grpc.AspNetCore.Server" Version="2.25.0" />

do I need some other nuget packages?

**Comment by chwarr** [comment]
`AddStandaloneGrpcServer` is a helper method that David wrote. You can find it in [GrpcServerExtensions.cs](https://github.com/davidfowl/gRPCSamples/blob/master/gRPCLibrary/GrpcServerExtensions.cs) in his sample repository.
