### ISSUE TITLE
the request for the GET method is rejected

### ISSUE THREAD

**Issue by tinylit** [grpc/grpc-dotnet#632]
When GRPC is used with NETCore MVC, the request for the GET method is rejected.

**Comment by JamesNK** [comment]
gRPC shouldn't interfere with MVC if they are used together.

Please post a simple reproduction of the issue.

**Comment by tinylit** [comment]
Ok, just a moment, please.

**Comment by tinylit** [comment]
I'm sorry, I tried it and it worked fine with GRPC and NETCORE MVC alone. There are problems when working with frameworks like SwaggerUI.
