### ISSUE TITLE
Detect if network firewall is blocking request with "Connect Failed" error 

### ISSUE THREAD

**Issue by amkoehler** [grpc/grpc-dotnet#636]
Hello, 

A user of our app is having trouble with certain grpc requests in our .NET app. This is the error message they receive in the logs:

```
Status(StatusCode=Unavailable, Detail="Connect Failed")
Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="Connect Failed")
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  ...
```

Some investigation of this error message shows it _may_ be an issue with the user's network firewall (see [here](https://github.com/googleapis/google-cloud-dotnet/issues/3112) and [here](https://stackoverflow.com/a/52468627/1569757)). Certain requests work fine, but this error comes up for any request that uses our firestore client with grpc. The client is instantiated as follows:

```csharp
// Uses OAuth2 to initalize our Firestore Client
var creds = GoogleCredential.FromAccessToken(userContext.Token);
var channel = new Channel("firestore.googleapis.com", 443, GoogleGrpcCredentials.ToChannelCredentials(creds));
return FirestoreClient.Create(channel);
```

What we've tried so far:
- Turning on  [`TextWriterLogger`](https://grpc.github.io/grpc/csharp/api/Grpc.Core.Logging.TextWriterLogger.html) doesn't seem to give us additional logs so that we can get more info about the connection issue
- The user can make requests to `firestore.googleapis.com` on port 443 from a browser without an issue

-----

1. Is there any sort of additional logging we can turn on to get more info about the "Connect Failed" error? Our theory is that it's a network firewall issue since it works for most of our users, but we don't have proof of this yet.
2. We have a few requests that use the [Firestore REST API](https://cloud.google.com/firestore/docs/reference/rest/), and those work just fine. The only requests that are failing use the [Firestore RPC API](https://cloud.google.com/firestore/docs/reference/rpc/). Are there any known differences in these requests that could be blocked on a network firewall? As far as I can tell, both are requests to firestore.googleapis.com on port 443

**Comment by JamesNK** [comment]
Instructions for setting up logging are available here: https://docs.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-3.0

**Comment by JamesNK** [comment]
Closing because there is no response. If this is still a problem add a comment here and this issue can be reopened.
