### ISSUE TITLE
Correct way to log exception in interceptor?

### ISSUE THREAD

**Issue by kle622** [grpc/grpc-dotnet#645]
Hey all. How should a catch-all exception logger look like? The code below does what I want, but I'm not sure if returning `null` is the best idea. I've checked the sample here, but there is no exception handling https://github.com/grpc/grpc-dotnet/blob/1f67ee2d00e60281dfc78a072b41fc575e0d1ce3/examples/Logger/Server/ServerLoggerInterceptor.cs. 

I'm using .NET Framework and including gRPC and Microsoft.Extensions.Hosting packages so I don't get the nice stuff that .NET Core has by default. Thanks!

        public override Task<TResponse> UnaryServerHandler<TRequest, TResponse>(TRequest request, ServerCallContext context, UnaryServerMethod<TRequest, TResponse> continuation)
        {
            try
            {
                return base.UnaryServerHandler(request, context, continuation);
            }
            catch (Exception exception)
            {
                _logger.LogError(exception.ToString());
                return null;
            }
        }

**Comment by chwarr** [comment]
If you configure logging in your host, can you get access [to the gRPC logs](https://docs.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-3.0)? If so, you could add your logger as a logging provider if one doesn't already exist. Much of the logging is based on the [Microsoft.Extensions.Logging package](https://www.nuget.org/packages/Microsoft.Extensions.Logging) that targets .NET Standard 2.0.

There's already a top-level [exception handler](https://github.com/grpc/grpc-dotnet/blob/542066a4cce1d6581d7c6592560a8edd00994a3f/src/Grpc.AspNetCore.Server/Internal/HttpContextServerCallContext.cs#L151-L186), so you can just rethrow the exception after logging. This will get you the default behavior of terminating the call with a status code of `Unknown`.

```
catch (Exception exception)
{
    _logger.LogError(exception.ToString());
    throw;
}
```

If you want to customize this behavior, throw an `RpcException` with the `Status` and `Trailers` set as you need.

Interceptors are written in terms of the generic `TResponse`; in almost all cases, there's no object it can sensibly return on its own, so it needs to either return what the continuation returned or throw. In this case, the continuation didn't return anything, so we have to throw.

**Comment by kle622** [comment]
Tried to add `"Grpc": "Debug"`to my appsettings.json, but no luck. I'm not using `.AddGrpc()` as I'm on .NET Framework, is that a requirement to do gRPC logging via the host?

**Comment by JamesNK** [comment]
If you're on .NET Framework then you're using Grpc.Core and not Grpc.AspNetCore.

I have tried error logging in an interceptor. You could ask about it at [grpc/grpc](https://github.com/grpc/grpc). A change I'd make is to continue to throw the exception:

```cs
    public override Task<TResponse> UnaryServerHandler<TRequest, TResponse>(TRequest request, ServerCallContext context, UnaryServerMethod<TRequest, TResponse> continuation)
    {
        try
        {
            return base.UnaryServerHandler(request, context, continuation);
        }
        catch (Exception exception)
        {
            _logger.LogError(exception.ToString());
            throw;
        }
    }
```

**Comment by kle622** [comment]
Got it. Thanks guys! Closing.

**Comment by thdotnet** [comment]
@kle622 were you able to log the error using this approach? I'm trying this way, but it never reaches the catch block. Is there any special way to register this interceptor?

**Comment by kle622** [comment]
@thdotnet yup. If you are using .net core, it is as simple as 

```
services.AddGrpc(options = 
{
    options.Interceptors.Add<TInterceptor>();
});
```

If you are using .net framework, it is a bit more involved
```
_server = new Server
{
    Services = 
    {
        Proto.Service.BindService(ServiceInstance).Intercept(InterceptorInstance);
    }
    Ports = ...
}
```

**Comment by thdotnet** [comment]
I was able to register the interceptor. But when debugging, it never reaches the catch statement in the UnaryServerHandler method.

**Comment by kle622** [comment]
Which method are you using to register? (core or framework?

**Comment by thdotnet** [comment]
core...and the implementation is pretty much the same as yours:

```
public override Task<TResponse> UnaryServerHandler<TRequest, TResponse>(TRequest request, ServerCallContext context, UnaryServerMethod<TRequest, TResponse> continuation)
    {
        try
        {
            return base.UnaryServerHandler(request, context, continuation);
        }
        catch (Exception exception)
        {
            _logger.LogError(exception.ToString());
            throw;
        }
    }
```

**Comment by kle622** [comment]
Are you debugging locally? Are you able to hit the statement in the `try` (perhaps no exception is being thrown? James has a great tutorial sample that I followed here https://github.com/grpc/grpc-dotnet/tree/master/examples/Logger/Server

**Comment by thdotnet** [comment]
yes, the base.UnaryServerHandler works, I'm forcing an exception in the implementation but it's not being catched in the catch statement UnaryServerHandler

**Comment by kle622** [comment]
Can you place a break point in the catch block and try again? I'm wondering if your visual studio exception settings are not breaking. Make sure `Common Language Runtime Exceptions` has a check next to it

![image](https://user-images.githubusercontent.com/7141342/77950443-56be1e00-727d-11ea-9314-c4fb2a2a28ed.png)

**Comment by wyepez** [comment]
> core...and the implementation is pretty much the same as yours:
> 
> ```
> public override Task<TResponse> UnaryServerHandler<TRequest, TResponse>(TRequest request, ServerCallContext context, UnaryServerMethod<TRequest, TResponse> continuation)
>     {
>         try
>         {
>             return base.UnaryServerHandler(request, context, continuation);
>         }
>         catch (Exception exception)
>         {
>             _logger.LogError(exception.ToString());
>             throw;
>         }
>     }
> ```

Adding async/await do the trick
