### ISSUE TITLE
Support for gRPC on arm

### ISSUE THREAD

**Issue by dnutiu** [grpc/grpc-dotnet#650]
**Is your feature request related to a problem? Please describe.**

Could you please add gRPC support for arm processors?

**Describe the ideal solution**

Someone has already worked on this :
https://dev.to/erikest/grpc-on-dotnet-core-preview3-on-raspberrypi-3-4nf4
https://github.com/erikest/libgrpc_csharp_ext

**Comment by JamesNK** [comment]
Your sample is using Grpc.Core to support ARM. You should post issues about that library at github.com/grpc/grpc

This repository's client is built on .NET Core's HttpClient. If HttpClient+HTTP/2 runs on a platform then this gRPC clinet will.
