### ISSUE TITLE
Handshake failed

### ISSUE THREAD

**Issue by moodya** [grpc/grpc-dotnet#653]
D1112 11:55:39.416952 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\security\transport\security_handshaker.cc:176: Security handshake failed: {"created":"@1573559739.416000000","description":"Handshake read failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\security\transport\security_handshaker.cc","file_line":358,"referenced_errors":[{"created":"@1573559739.416000000","description":"End of TCP stream","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\iomgr\tcp_windows.cc","file_line":229}]}

We have hosted a .net grpc sevrer in an azure container and have set it up to use ssl. In terms of being able to connect to the server everything works fine, and a third party has confirmed this. However when I switch on DEBUG logging we our repeatedly getting the above. What does this mean?

**Comment by moodya** [comment]
D1112 12:26:06.109187 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\security\transport\security_handshaker.cc:176: Security handshake failed: {"created":"@1573561566.109000000","description":"Handshake read failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\security\transport\security_handshaker.cc","file_line":358,"referenced_errors":[{"created":"@1573561566.109000000","description":"End of TCP stream","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\iomgr\tcp_windows.cc","file_line":229}]}
D1112 12:26:06.110134 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\ext\transport\chttp2\server\chttp2_server.cc:123: Handshaking failed: {"created":"@1573561566.109000000","description":"Handshake read failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\security\transport\security_handshaker.cc","file_line":358,"referenced_errors":[{"created":"@1573561566.109000000","description":"End of TCP stream","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\iomgr\tcp_windows.cc","file_line":229}]}

**Comment by moodya** [comment]
<PackageReference Include="Google.Api.Gax.Grpc" Version="2.7.0" />
    <PackageReference Include="Google.Protobuf" Version="3.8.0" />
    <PackageReference Include="Grpc" Version="1.22.0" />
    <PackageReference Include="Grpc.Core" Version="1.22.0" />
    <PackageReference Include="Grpc.Tools" Version="1.22.0" PrivateAssets="All" />

**Comment by JunTaoLuo** [comment]
This is a Grpc.Core issue. Please file the issue here: https://github.com/grpc/grpc.
