### ISSUE TITLE
BlockingUnaryCall fails with Bad gRPC response if no TLS/SSL is used

### ISSUE THREAD

**Issue by maxreb** [grpc/grpc-dotnet#654]
### What version of gRPC and what language are you using?
gRPC.Net.Client 2.25.0,c#

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
 .Net Core 3.0,  Razor Components (Blazor server side)

### What did you do?
Connecting to an non TLS/SSL gRPC Server

### What did you expect to see?
Even though I don't use `https` but `http` it should use HTTP/2

### What did you see instead?
The `POST` sent from the Client (BlockingUnaryCall) downgrades to `HTTP/1.1` so the response will be `HTTP/1.1`, too and this leads to the following exception:
`Grpc.Core.RpcException: 'Status(StatusCode=Internal, Detail="Bad gRPC response. Response protocol downgraded to HTTP/1.1.")'`
The one who downgrades the protocol isn't the gRPC server, but the client it self.
![image](https://user-images.githubusercontent.com/39700092/68782592-f0bc5b80-0639-11ea-869c-b71fc66987e4.png)

### How to fix it?
Put the following line of code in your Startup class:
```
//This will force the gRPC.Client to use HTTP/2 even though it's unencrypted
AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
```

**Comment by JamesNK** [comment]
Using the switch is required at the moment. We'll improve it with 5.0.

Is that a problem for you?

**Comment by maxreb** [comment]
.net 5.0? Sure, thanks for the news. I just opened that issue for people struggling with the same error!

**Comment by JamesNK** [comment]
Will be improved with https://github.com/dotnet/corefx/issues/41621

**Comment by yshteinm** [comment]
I am connecting to HTTPS server and still get the same error
