### ISSUE TITLE
Adding TLS to GRPC endpoint causes it to fail

### ISSUE THREAD

**Issue by evolvedlight** [grpc/grpc-dotnet#655]
### What version of gRPC and what language are you using?
Grpc.AspNetCore.Server 2.25.0, c#

### What operating system (Linux, Windows,...) and version?
Windows (but tested Linux too)

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
3.0.100

### What did you do?
We have a working GRPC endpoint (using plaintext). We want to get the TLS version running, so for now have generated a self signed cert (with trusted CA) and added it to the project with UseHttps("thefile.pfx"). Now, we can go to the local (and deployed) version of the website with a browser and see the certificate correctly being used.

```
options.ConfigureHttpsDefaults((c) =>
{
    c.ServerCertificate = new X509Certificate2("cert.pfx");
});

options.ConfigureEndpointDefaults((c) =>
{
    c.Protocols = HttpProtocols.Http2;
});
```

I now try to use this with the grpcurl tool, and the http version still works, but the https version does not. I get the error "Message: stream terminated by RST_STREAM with error code: PROTOCOL_ERROR". 

### What did you expect to see?
I expected to see the same output as for the non-ssl version

### What did you see instead?
The protocol error

```
grpcurl.exe -plaintext -v -import-path <snipped>\Protos -proto grpc_service.proto localhost:5000 GrpcService/Healthcheck

Resolved method descriptor:
rpc Healthcheck ( .HealthcheckRequest ) returns ( .HealthcheckResponse );

Request metadata to send:
(empty)

Response headers received:
content-type: application/grpc
date: Wed, 13 Nov 2019 15:11:53 GMT
server: Kestrel

Response contents:
{
  "healthCheckString": "Ok"
}

Response trailers received:
(empty)
Sent 0 requests and received 1 response
grpcurl.exe -insecure -v -import-path <snipped>\Protos -proto grpc_service.proto localhost:5001 GrpcService/Healthcheck

Resolved method descriptor:
rpc Healthcheck ( .HealthcheckRequest ) returns ( .HealthcheckResponse );

Request metadata to send:
(empty)

Response headers received:
(empty)

Response trailers received:
(empty)
Sent 0 requests and received 0 responses
ERROR:
  Code: Internal
  Message: stream terminated by RST_STREAM with error code: PROTOCOL_ERROR
```

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc-dotnet/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
This was done in a corporate environment so I can't give the source code, if the above is insufficient I will make a clear reproduction outside the corporate environment. Just let me know.

**Comment by JamesNK** [comment]
It looks like your client is configured to use plaintext/unsecured

> grpcurl.exe -plaintext -v -import-path <snipped>\Protos -proto grpc_service.proto localhost:5000 GrpcService/Healthcheck

> grpcurl.exe -insecure -v -import-path <snipped>\Protos -proto grpc_service.proto localhost:5001 GrpcService/Healthcheck

**Comment by evolvedlight** [comment]
Hi @JamesNK 

Thanks very much for looking (and I loved your NDC talk!).
I've realised that my problem is actually far simpler.
The service _does_ work with TLS, no problem there at all. What doesn't work is using GRPC Bloom or Grpccurl to access the service - I was assuming that Bloom would work after seeing it on your talk.

To reproduce:
Follow the guide on https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.0&tabs=visual-studio-code#create-a-grpc-service to create the service only.

Start it
Try to connect to it with Bloom.

I now realise that this wasn't using TLS as expected. I assume as you say, that it's the same problem with grpcurl.
I know this probably isn't your top priority right now, but it'd be great to have a small section on how to use some third party testing tools like Bloom with the API.

Thanks,
Steve
