### ISSUE TITLE
Document using BloomGrpc/grpcurl with grpc-dotnet

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#656]
See https://github.com/grpc/grpc-dotnet/issues/655#issuecomment-553558919

Specifically discuss TLS issues.

**Comment by Hellevar** [comment]
If someone wants to interact with their gRPC services through handy UI - please check my library [BlazorFly.Grpc](https://github.com/Hellevar/BlazorFly.Grpc).
For now it provides basic 'swagger'-like experience via Blazor-based UI, fully '.net way'.

**Comment by rizi** [comment]
@Hellevar is your project still under development?

**Comment by rizi** [comment]
@JamesNK would be great if you could point us in the right direction. When requesting a service using BloomGrpc, the C# server always fails with some security/certificates exceptions, using the same certificate but using a C# grpc client everything is working finde.
