### ISSUE TITLE
Explore supporting other .NET languages

### ISSUE THREAD

**Issue by JunTaoLuo** [grpc/grpc-dotnet#66]
F#? VB? Let's make sure we don't paint ourselves into a corner in terms of supporting these languages while we work on the C# support.

**Comment by JunTaoLuo** [comment]
cc @shirhatti

**Comment by shirhatti** [comment]
FYI @KathleenDollard @cartermp

I'll follow up with more details.

**Comment by KathleenDollard** [comment]
Looking forward to it.

**Comment by JamesNK** [comment]
I don't think there is anything in `Grpc.AspNetCore.Server` that would tie the framework to C#. And producing templates shouldn't be difficult. `Grpc.Tools` only codegenning C# is the main blocker.

**Comment by JamesNK** [comment]
We support other languages vs protobuf-net.Grpc. You can use C#, VB.NET, F# with that library.
