### ISSUE TITLE
can't import proto files in VS2019 grpc service

### ISSUE THREAD

**Issue by lonewolfnsp** [grpc/grpc-dotnet#666]
I've 2 proto files, chatdata.proto and chatter.proto. 

chatdata.proto
syntax="proto3";

message emptyMsg{}

message Chatmsg
{
	string message=1;
}

message stepMsg
{
	int32 	stepPos=1;
}

enum ErrorCode
{
	UNKNOWN=0;
	INVALID_VALUE=1;
	UNAUTHORIZED=2;
	NOT_ALLOWED=3;	
}

message ErrorReq
{
	ErrorCode code=1;
}

chatsvc.proto
syntax = "proto3";
import "chatdata.proto"; //VS2019 keeps complaining can't find this file. why??

service ChatSvc 
{
	rpc getResponse(Chatmsg) returns (Chatmsg){}
	rpc generateServerError(ErrorReq) returns (emptyMsg){}
	rpc stepSvrProgress(stream stepMsg) returns (emptyMsg){}
	rpc stepClientProgress(emptyMsg) returns (stream stepMsg){}
	rpc Chatting(stream Chatmsg) returns (stream Chatmsg){}	
}

I created a grpc service project in VS2019, put these 2 files in protos folder, specified to use protobuf to compile them, but only generate server codes for chatter.proto. for chatdata.proto, I specified do not generate. 

when I try to compile to generate the proxy class, it FAILED. it claimed it's not able to find chatdata.proto. why? the same files using grpc tools, I could generate the proxy class just fine.. 

this is really driving me mad.. can someone please enlighten me on what's wrong?

**Comment by JamesNK** [comment]
Is chatdata.proto in a folder? You may need to add that to the import path, e.g. import "MyFolder/chatdata.proto"

**Comment by lonewolfnsp** [comment]
it's in the same place as chatsvc.proto. Basically both are in the protos folder. so it should work isn;t it? I used grpc tools to generate the proxy class myself and used it directly in the project. then I got hit by another issue, when trying to compile, "no grpc methods discovered". WTF??? can't work properly in VS2019, now don't even let me use the pne I generated.. seriously.. is this a joke??

**Comment by JamesNK** [comment]
Did you try what I suggested?

**Comment by lonewolfnsp** [comment]
yep.. your method does work. but my concern is, when using the grpc tools to generate the proxy class for another language, would this folder name cause issues? seriously MS should allow specifying of linked proto files, instead of treating them as distinct separate files. can you advice me on this?

**Comment by lonewolfnsp** [comment]
OK, think  I figured out why.. in VS, I created a folder call protos for project ChatSvr (grpc service). This requires me to specify protos/chatdata.proto for import in the chatsvc.proto file. I added in another console project, this time I did not add a folder, but just added the 2 proto files as link since I don't want to have copies of the same files flying around.. but now, when I compile, I will get the file not found error for the console project as it's now not in a folder within the project. I think this is a bug with VS or the protobuf compiler. the folder in VS is sort of a "logical folder" to organize the file types, but here it's considered a physical folder path. what do you think?

**Comment by JamesNK** [comment]
The compiler and MS build integration is written at grpc/grpc. If you have an issue with how it works you should bring it up there.
