### ISSUE TITLE
MapGrpcService<TService> mapped service custom lifetime

### ISSUE THREAD

**Issue by GoNextGroup** [grpc/grpc-dotnet#667]
Hello.

If I'm not mistaken, current realization of `MapGrpcService<TService>` realize only scoped lifetime. Is it possible to add an ability to select custom service lifetime? I want to use services as singletones, but have no ability.

Thank you.

**Comment by JamesNK** [comment]
Service instances are resolved from DI. Just register the service instance as a singleton in Startup.cs:

```cs
services.AddSingleton<YourServiceType>();
```
