### ISSUE TITLE
getting access to grpc listening port at runtime

### ISSUE THREAD

**Issue by lonewolfnsp** [grpc/grpc-dotnet#675]
Hi all, I'm trying to gain access to the port that grpc is listening on at runtime. As the settings are all in appsettings.json. How and where can I access the actual https port?

This is my appsettings.json:
{
  "Kestrel": {
    "Endpoints": {      
      "Https": {
        "Url": "https://*:25000",
        "Protocols": "Http1AndHttp2",
        "Certificate": {
          "Path": "chat.pfx",
          "Password": "123456"
        }
      }
    }
  }
}

**Comment by JamesNK** [comment]
You want to access the TCP port on the server? I don't know. Kestrel abstracts away the transport and HTTP/2 protocol. You could look at the Kestrel source code to find out whether there are any hooks you could use.

**Comment by lonewolfnsp** [comment]
Actually the scenario is like this, I've two different apps, each has its own grpc server, one is manager the other is like client. Server has to connect to the client's grpc server to control client which in this case is on another machine, thus client port is not known beforehand. On client startup, once its grpc server is up and running, it will connect to the server and tell server what its grpc port is, so server can connect to it. 

Now as grpc-dotnet's kestrel is configured via appsettings.json (I don't want to hardcode it as client machine may not have the port available), I intend to let client tell server the details. Thus the need to be able to get the runtime http2 port on client side.

but if there's a better way, I'm open to it too..

**Comment by JamesNK** [comment]
I don't know. I googled this: https://stackoverflow.com/questions/49871318/determine-port-kestrel-binded-to

**Comment by JamesNK** [comment]
I believe this is answered. Closing.
