### ISSUE TITLE
Rename Grpc.AspNetCore.Server.ClientFactory and Grpc.AspNetCore.Server.Reflection packages

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#678]
These package names are pretty long. I don't think we need to put "Server" in every server-side package. "AspNetCore" already indicates that it is designed to run on the server in ASP.NET Core.

I think we can shorten them:
* Grpc.AspNetCore.Server.ClientFactory -> Grpc.AspNetCore.ClientFactory
* Grpc.AspNetCore.Server.Reflection -> Grpc.AspNetCore.Reflection

Fortunately neither of these packages uses the full namespace in any public types. All the public types are in other common namespaces (Microsoft.Extensions.DependencyInjection, Microsoft.AspNetCore.Builder) to make their extension methods easily discoverable.

We could:
1. Introduce new packages with the shortened names, with the logic moved to them
2. Publish versions of the existing packages, with dependencies on the new packages and type forwarding to them
3. After the next release remove the old packages from source (i.e. stop publishing them).

**Comment by jtattermusch** [comment]
I'm fine with the plan (but not sure if it's worth the work).
