### ISSUE TITLE
Misleading error message "Supplied channel credentials do not allow composition"

### ISSUE THREAD

**Issue by christopheblin** [grpc/grpc-dotnet#679]
### What version of gRPC and what language are you using?
Irrelevant but I use C# via Nuget Grpc.AspNetCore.Server 2.23.2

### What operating system (Linux, Windows,...) and version?
Irrelevant, but I use windows and docker

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
Irrelevant but .NET Core SDK 3

### What did you do?
ChannelCredentials.Create(ChannelCredentials.Insecure, credentials)

### What did you expect to see?
In the first place, I expect it to work.
Now that I understand that it is not secure to provide credentials over an insecure channel, I expect to see a better error message than "Supplied channel credentials do not allow composition" like "You cannot provide credentials over insecure channel"

### What did you see instead?

Error message "Supplied channel credentials do not allow composition" thrown at https://github.com/grpc/grpc/blob/1d5a5af8134c71a1b48809c2d88f10763ab2a9bb/src/csharp/Grpc.Core.Api/ChannelCredentials.cs#L104

### Anything else we should know about your project / environment?
I do not htink so

**Comment by JamesNK** [comment]
PR to improve the error message - https://github.com/grpc/grpc/pull/21383
