### ISSUE TITLE
Status(StatusCode=Internal, Detail="Bad gRPC response. Response protocol downgraded to HTTP/1.1."

### ISSUE THREAD

**Issue by ceremony** [grpc/grpc-dotnet#682]
### What version of gRPC and what language are you using?
gRPC.Net.Client 2.25.0, C#

### What operating system (Linux, Windows,...) and version?
Linux RHEL 7

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET Core 3.1

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

I'm setting up gRPC pipes between one server and multiple clients, each with a different port (for various reasons).  

I have everything using insecure ports, this is a totally controlled environment.

I do _not_ use ASP.NET, just straight C#, System.Net.Http, etc.

### What did you expect to see?
Successful transmission request/response.

### What did you see instead?
Status(StatusCode=Internal, Detail="Bad gRPC response. Response protocol downgraded to HTTP/1.1.") =>    at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
...

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
A previous bug report #654 mentioned a very similar issue, and mentioned a possible fix:
//This will force the gRPC.Client to use HTTP/2 even though it's unencrypted
AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);

But this does not work in my environment;  at least not with .NET Core 3.1, and without using ASP.NET etc.

**Comment by JamesNK** [comment]
Is your client connecting with TLS? (if it has an https address then it is). In that case your server port doesn't support HTTP/2.

If you're connecting without TLS (http address) then `AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);` is required.

**Comment by ceremony** [comment]
Hi James,

Here is the code I use for the client.  It's kind of paranoid, but I'm trying to force HTTP/2:
...
            AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2Support", true);
            AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);            
            Channel = GrpcChannel.ForAddress("http://localhost:9000", new GrpcChannelOptions() {
                HttpClient = new System.Net.Http.HttpClient() {
                    DefaultRequestVersion = new Version(2, 0)
                }
            });
            Client = new ComposerRPC.ComposerRPCClient(Channel);
...

Here is the code for the server (also paranoid):
....
                // Launch
                Transit(States.Compose);
                Log.Info("launching composer rpc service", 1);
                var hs = new HostBuilder().ConfigureServices((ctx, svc) => {
                    var h = Config.RPCBaseHost;
                    var p = Config.RPCBasePort + Program.Identity;
                    Log.Info("starting composer rpc service @ " + h + " : " + p, 1);
                    var o = new Composer(DbCxnString, h, p);
                    var srv = new Server() {   
                        Services = { ComposerRPC.BindService(o) },
                        Ports = { new ServerPort(h, p, ServerCredentials.Insecure) },                        
                    };         
                    svc.AddSingleton<Server>(srv);
                    svc.AddSingleton<IHostedService, HostedServiceRPC>();
                    o.Shutdown = (() => srv.ShutdownAsync());
                    Log.Info("composer rpc service @ " + h + " : " + p + " ready", 1);
                });
...

Any insight would be *greatly* appreciated.

I've literally tried everything - using Credential.Insecure on everything, using Channel=new Channel, and a whole number of other permutations.

**Comment by ceremony** [comment]
Wow I just looked in the mirror and realized that I have no hair left - I've pulled it all out the past two days.

I am *so* excited about using gRPC w/ .NET 3.1 - what a blessing, but I think there is something that just isn't right with .NET Core 3.1, Visual Studio 16.4, and gRPC xxx.25.

I ended up switching back to TCP/sockets;  maybe not so convenient, but the codebases and methodology are extremely mature and well understood.

Anyways, I definitely hope to revisit gRPC at a future time when the kinks have been worked out - it's a critical project for work so I can't take chances.

Thanks,
Ceremony

**Comment by JamesNK** [comment]
You're using Grpc.Core as the server, and not Grpc.AspNetCore for ASP.NET Core. Why?

Did you try one of the samples? Or following the [tutorial](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.1&tabs=visual-studio)?

If you still can't get it working then you'll need to attach a simple repro of your source code.

**Comment by ceremony** [comment]
Hi James,

Thanks, I was not even aware of the Grpc.AspNETCore.  

In several of the examples that I've seen for dotnet core, I've observed:
Grpc.Channel instead of Grpc.Net.Client.Channel, etc.
So from the available documentation, there was confusion on my part between Grpc.Core and Grpc.Net.XXX or Grpc.AspNETCore.XXXX.

What I'm going to do is download the sample app straight from that link you indicated and try getting it to run.

Thanks.

**Comment by brmdbr** [comment]
@ceremony Did you get it working? I'm runing into the same problem.

**Comment by yshteinm** [comment]
Having the same problem in .NET Core 3 console app. Anybody can help?

**Comment by atresnjo** [comment]
> 
> 
> Having the same problem in .NET Core 3 console app. Anybody can help?

[what worked for me](https://stackoverflow.com/a/59631915/11989452)

and 

`AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);`

on the client

**Comment by yshteinm** [comment]
What if it is not hosted in Kestrel? I need it to work from Xamarin app. Any solution?

**Comment by HarrySpyrou** [comment]
I'm running into the same problem here. Nothing seems to be working. Running NGINX in front of Kestrel. @atresnjo 's solution didn't work for me.

**Comment by jwu-dharmo** [comment]
Same here...using straight from the config file...I am running .Net Core 3.1

I tried the Grpc.Net.Client.Channel solution, but didn't work.  This is a real problem.

**Comment by yshteinm** [comment]
Here is what you can do: Use memory stream to put your data object. Then use REST call and put the data in it. You probably will het HTTP1.1 instead of HTTP2 but this is what we want to make it working, don't we? And at least you get binary small data which works with protobuf on server.

**Comment by jwu-dharmo** [comment]
I just figured out my problem...just to be 100% clear on my approach:

**appsettings.Test.json**:
```
"Kestrel": {
    "Endpoints": {
      "Https": {
        "Url": "https://my.domain.com:1111",
        "Certificate": {
          "Subject": "CN_value_only",
          "Store": "My",
          "Location": "LocalMachine",
          "AllowInvalid": "true"
        }
      }
    }
  }
```
**program.cs**

```
.ConfigureServices((context, services) =>
              {
                services.Configure<KestrelServerOptions>(
                  context.Configuration.GetSection("Kestrel"));
              })
```

The cause to my "Bad gRPC response" was the domain name in the appsetting.json was NOT correct.
