### ISSUE TITLE
Grpc repeatedfield .net core web api binding

### ISSUE THREAD

**Issue by mokoker** [grpc/grpc-dotnet#685]
Hi, I hava a complex object that contains RepeatedField<int> type, proto file looks something like
message QuestionRequest{
	string Name = 1;
	repeated int32 Topics = 2;
}
and I am having trouble binding to it in the web api controller. Because its sealed i can't write a wrapper class and because its readonly I am also having trouble setting it in a custom complex type binder.
Also checked the samples and benchmark client but they don't have repeated fields.
Why RepeatedField and not just  basic List it should make everyting easier.

Thanks.

**Comment by JamesNK** [comment]
RepeatedField is a Protobuf type - https://developers.google.com/protocol-buffers/docs/reference/csharp/class/google/protobuf/collections/repeated-field-t-

These types are deserialized to be serialized by other serializers. If you want that ability you can request it at https://www.github.com/protobuf/protobuf
