### ISSUE TITLE
grpc.reflection not in nuget packages for dotnet core 3+?

### ISSUE THREAD

**Issue by jrvjrv** [grpc/grpc-dotnet#693]
I wanted to add reflection to the grpc greeter example, working with dotnet core 3.1 using VS code on ubuntu. I added the nuget package for Grpc.Reflection version 2.26.0-pre1 (and also tried v 2.25). Both intellisense and compilation were unable to find the Grpc.Reflection methods. I suspect (but do not have sufficient understanding of nuget packages to know) that the nuget package does not include a library suitable for dotnet core 3.1. Is that correct?

**Comment by jrvjrv** [comment]
I think I have answered my own question. I was assuming, based on the example, that the Grpc.Reflection nuget package included the two extension methods shown in the sample, services.AddGrpcReflection() and endpoints.MapGrpcReflectionService(). It took me a while to realize that the two methods came from a *project* reference to Grpc.AspNetCore.Server.Reflection. I created a similar project, built it, and was able to reference that csproj into the simple example.

My revised question: is it true that the Grpc.AspNetCore.Server.Reflection project is not currently available through nuget?

**Comment by JamesNK** [comment]
What happened when you searched for it on NuGet?

**Comment by jrvjrv** [comment]
The problem is that I have misunderstood nuget package manager in visual studio code. Its search seems to be case-sensitive, but only sometimes. If I search for "grpc.aspnetcore" then Grpc.AspNetCore.Server.Reflection shows up. But if I search for "grpc.aspnentcore.server" or "grpc.aspnetcore.server.reflection" I get nothing. If I search for "Grpc.AspNetCore.Server.Reflection" (matching capitalization) then the package is found. As I have become accustomed to package manager working as case-insensitive I couldn't find the package. Sorry for the confusion.
