### ISSUE TITLE
Convert protobuf to json format

### ISSUE THREAD

**Issue by Edward-Zhou** [grpc/grpc-dotnet#708]
For Java, there is a [JsonFormat](https://github.com/protocolbuffers/protobuf/blob/master/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java) which could be used to convert from/to json format.

Is there any similiar feature for .net core?

**Comment by JamesNK** [comment]
Convert a message to JSON: https://developers.google.com/protocol-buffers/docs/reference/csharp/class/google/protobuf/json-formatter

Convert a message from JSON: https://developers.google.com/protocol-buffers/docs/reference/csharp/class/google/protobuf/json-parser
