### ISSUE TITLE
NU1202 Package is compatible and NU1212	Invalid project-package combination

### ISSUE THREAD

**Issue by Que8549** [grpc/grpc-dotnet#709]
### What version of gRPC and what language are you using?
 C#, Grpc.AspNetCore v2.26.0, Google.Protobuf.Tools v3.11.2, Google.Protobuf v3.11.2. I am trying to install dotnet-grpc v2.26.0 from NuGet

### What operating system (Linux, Windows,...) and version?
Windows and Visual Studio 2019 v16.3.10

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET Core 3.1 also tried .NET Core 3.0

### What did you do?
I tried install dotnet-grpc v2.26.0 from NuGet using VS2019 into my project.

### What did you expect to see?
I expected to see a successful package install. I want to use dotnet-grpc 2.26.0 to compile my *.proto files into C# classes when I build the project. I do not want to setup a pre-build event to call protoc directly.

### What did you see instead?
Error NU1202	Package dotnet-grpc 2.26.0 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0). Package dotnet-grpc 2.26.0 supports: netcoreapp3.0 (.NETCoreApp,Version=v3.0) / any	BiosensingApparel	C:\Projects\myProject.csproj	
Error NU1212 Invalid project-package combination for dotnet-grpc 2.26.0. DotnetToolReference project style can only contain references of the DotnetTool type 

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
Package  dotnet-grpc v2.26.0  was not installed into the project

### Anything else we should know about your project / environment?
I am not using the ASP.NET Core project template because of project restrictions. However, I am using the same ASP.NET Core modules in the project. 

I can setup the gRPC services in my Startup.cs file.
        public void ConfigureServices(IServiceCollection services)
        {
           services.AddResponseCompression(); 
           services.AddGrpc();
        }

        public void Configure(IApplicationBuilder app)
        {
            app.UseResponseCompression();

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                // Communication with gRPC endpoints must be made through a gRPC client.
                // To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909
                //endpoints.MapGrpcService<GreeterService>();
            });
        }`

**Comment by JamesNK** [comment]
Why are you trying to add that package to a website? It is a command line tool.

**Comment by Que8549** [comment]
The project is a Windows form project that hosts a Chromium browser (CefSharp). I'm using Kestrel as the web server. I need the command line tool in order to create the c# classes from the proto files.

**Comment by JamesNK** [comment]
dotnet-grpc doesn't contain a runtime target. It is only usable as a command line tool. There are no plans to change that.

You could copy the source code into your own app.

**Comment by Que8549** [comment]
Thanks, I'll probably do that. Thanks again.
