### ISSUE TITLE
Handle binary header and trailer values

### ISSUE THREAD

**Issue by JunTaoLuo** [grpc/grpc-dotnet#71]
Currently Kestrel will reject headers it cannot parse as ASCII or UTF-8 with a 400 response. We also do not support sending binary trailers. We need to discuss how to support this feature and what changes are required in ASP.NET.

**Comment by JunTaoLuo** [comment]
https://github.com/grpc/grpc-dotnet/pull/69#pullrequestreview-200446456 Actually just noticed that binary headers and trailers are always assumed to be base64 encoded as mentioned in https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#requests. This makes it easier to handle.

**Comment by jtattermusch** [comment]
Yes this, shouldn't be a problem. There's no such thing as "binary headers" in HTTP/2 AFAIK. gRPC only makes it appear so. One of the popular use cases is let one of the trailers carry a serialized protobuf with e.g. structured error details (example here: https://github.com/googleapis/googleapis/blob/master/google/rpc/status.proto#L80).
