### ISSUE TITLE
Custom IOC-Container / Child Container/Scope per RPC-Method Call

### ISSUE THREAD

**Issue by rizi** [grpc/grpc-dotnet#715]
Hi,
We need to use a custom IOC-Container (like Unity, Autofac), is there a way to archive that with rpc (we are using .net core 3.1)? If it's possible please guide me in the right direction, I wasn't able to find a solution.

We would also need to create a new scope (child container) for each RPC-method call and resolve the rpc service from the child container, after the method call has finished we need to dispose the child container. 
Is there a way to archive that, maybe with some kind of interceptors?

E.q: 
1.) Client calls rpc-method 
2.) Server creates a new scope (child container), resolves the rpc service from this child container (and all dependencies of the rpc service that may be used by the constructor)
3.) The called rpc-method gets executed, after the method call has finished the newly created child container needs to be diposed?

Br
Renè

**Comment by JamesNK** [comment]
You can implement `IGrpcServiceActivator<T>` that uses your custom DI container. Then register it with asp.net core's DI

**Comment by rizi** [comment]
> You can implement `IGrpcServiceActivator<T>` that uses your custom DI container. Then register it with asp.net core's DI

Thx for the fast reply, how to I hook into grpc so I can create a new child container (scope) before the method is called?
And I need a hook to dispose the child container after the method call, is there also a way to archive this? maybe with an interceptor or something?

**Comment by rizi** [comment]
That's exactly what I was looking for, so I close the issue, I hope that's OK for you.

**Comment by rizi** [comment]
@JamesNK sorry for re-opening the issue, but I'm a little bit confused.
Today I created a new GrpcService (using the asp.net core 3.1 template) and there is no dependency to your package dotnet-grpc, so the interface IGrpcServiceActivator<T> is marked as internal and I can not create my custom service activator.
Please have a look at the screenshot, can you tell me what I did wrong, or why the template for asp.net core grpc 3.1 does not use your package. 
thx
![IgrpcServiceActivator](https://user-images.githubusercontent.com/796258/72234707-935b7100-35ce-11ea-8f25-60158184ccae.png)
