### ISSUE TITLE
GRPC server and console applications.

### ISSUE THREAD

**Issue by Code-Codex** [grpc/grpc-dotnet#719]
All the examples shown here and on Microsoft docs show creating a GRPC server for asp.net core. Is there an equivalent way to do this in console apps? 
If there is then can you point me to the resource? If not then are there any plans?

I have  been using GRPC.Core libraries but i would prefer using grpc-dotnet.
Any information/help would be appreciated.

**Comment by JamesNK** [comment]
An asp.net core server app is a console app, it just happens to start a web server in Program.Main.

What else are you looking for?

**Comment by Code-Codex** [comment]
Hello James.. Our application is composed or various micro-services running on the same machine and we use gRPC for IPC between those micro-services. I don't know what the overhead of starting up an entire asp.net core pipeline/web server in each process would be.

**Comment by JamesNK** [comment]
Right now you can't. grpc-dotnet only supports HTTP/2 via TCP sockets.

In 5.0 we want to add support for other transports (e.g. HTTP/2 via named pipes or unix domain sockets) but work on that hasn't started yet.

**Comment by Code-Codex** [comment]
Thats good to know that named pipes are on the list.. Thanks for the information.
