### ISSUE TITLE
Populate AuthContext on ServerCallContext

### ISSUE THREAD

**Issue by JunTaoLuo** [grpc/grpc-dotnet#72]
The last item that's not tracked by issues or pending PRs from the list of properties on ServerCallContext.

**Comment by JamesNK** [comment]
@jtattermusch The `AuthContext` constructor is internal

https://github.com/grpc/grpc/blob/906c12568e9bdf1d8306a2f2ab45efe8beb43f74/src/csharp/Grpc.Core.Api/AuthContext.cs#L42

Should it be made public?

**Comment by JamesNK** [comment]
We'll have to leave it out in the first preview.
