### ISSUE TITLE
When having multiple clients with their own stream requests invoking a server grpc method, after one client is invoked, the other fails with an exception

### ISSUE THREAD

**Issue by Dmdv** [grpc/grpc-dotnet#722]
### What version of gRPC and what language are you using?
C#. NET CORE 3.1, Grpc.AspNetCore 2.26.0

### What operating system (Linux, Windows,...) and version?
Server is in Docker (ALPINE)
Client is in Window 10

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET Core SDK 3.1

### What did you do?

I create 2 client to invoke 2 different servers with stream requests.

```
// First client call

using var httpClient1 = new HttpClient(httpClientHandler);
using var channel1 = GrpcChannel.ForAddress("https://127.0.0.1:4555", new GrpcChannelOptions {HttpClient = httpClient1});
var grpcClient1 = new MyGrpc.GrpcClient(channel1);

// Invoked grpcClient1 method

// Second client call

using var httpClient2 = new HttpClient(httpClientHandler);
using var channel2 = GrpcChannel.ForAddress("https://127.0.0.1:5555", new GrpcChannelOptions {HttpClient = httpClient2});
var grpcClient2 = new MyGrpc.GrpcClient(channel2);

// Invoked grpcClient2 method

```

### What did you expect to see?

Results from 2 clients.

### What did you see instead?

> Status(StatusCode=Internal, Detail="")

the first one is invoked successfully.
The second one fails with an exception "Error starting gRPC call: The SSL connection couldn't be established"

If I comment the first call, invocation of the second call is performed successfully.
If I uncomment the first call, invocation of the second call fails.

Troubleshooting didn't help, none of debug parameters showed up during debugging.

**Comment by JamesNK** [comment]
Your requests are on different ports. The second port might not have a valid TLS certificate.

Client logging will provide more detail about the error: https://docs.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-3.1#grpc-client-logging

**Comment by JunTaoLuo** [comment]
@Dmdv have you been able to capture logs and confirm the second port was set up with the correct TLS certificate?

**Comment by JunTaoLuo** [comment]
Since there hasn't been any responses, we'll be closing the issue in 3 days if there are no further updates.
