### ISSUE TITLE
Unity (netstandard2.0 / net4.X )Support ?

### ISSUE THREAD

**Issue by Stvchm9703** [grpc/grpc-dotnet#726]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
---
#### What version of gRPC and what language are you using?
Client side : gRPC csharp unity : 1.27.0

#### What operating system (Linux, Windows,...) and version?
Window

#### What runtime / compiler are you using (e.g. python version or version of gcc)
csharp : netstandard2.0

#### What did you do?
So I try to make a connection with credentials

and client-side , unity
``` csharp
// init 
var crt = new SslCredentials (File.ReadAllText ( "key.pem"));
var channel = new Channel ( "0.0.0.0", 11000, crt);
this.client = new RoomStatus.RoomStatusClient (this.channel);
/// ......
// skip to create-process
var t = await this.client.CreateRoomAsync (new RoomCreateReq {
        UserId = this.HostId
});
Debug.Log(t.RoomInfo);
```

#### What did you expect to see?
client-side can execute the code, and show the data received from server

and client-side , unity
``` csharp
// init 
var channel = new Channel ( "0.0.0.0", 11000, SslCredentials.Insecure);
this.client = new RoomStatus.RoomStatusClient (this.channel);
/// ......
// skip to create-process
var t = await this.client.CreateRoomAsync (new RoomCreateReq {
        UserId = this.HostId
});
Debug.Log(t.RoomInfo);
```

#### What did you see instead?
Fail Log with `Status(StatusCode=Unavailable, Detail="Empty update")`

---

I know similar case of csharp had been occurred in [StackOverflow](https://stackoverflow.com/questions/57451709/grcp-server-throws-exception-when-using-sslservercredentials-in-c-sharp) , said that this project may solve the problem about SslCredentials failure. 
However, the released version are only supporting netstandard2.1, which is not able to implement to Unity (netstandard2.0/ .net4.x ), even I clone the project and try to build the netstandard2.0 by myself, it cannot solve all the issue between the different version. 

### Describe the solution you'd like
project build target may add the netstandard2.0 or .net4.x , since the Unity official are not going to upgrade the compatibility level

I know that it is hard to make it with Unity, but it is no way to solve the SSL issue,

**Comment by JamesNK** [comment]
This is the wrong repository. Ask Grpc.Core questions at https://github.com/grpc/grpc
