### ISSUE TITLE
Update Blazor sample when 3.2.0 preview is out

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#732]
3.2.0 preview fixes `HttpClientHandler`. The sample can be simplified to remove reflection creating the underlying handler.

Should be out on Jan 28.

https://www.nuget.org/packages/Microsoft.AspNetCore.Blazor

**Comment by anurse** [comment]
Blazor 3.2.0 Preview 1 is out now! We can do this!
