### ISSUE TITLE
Why generated code throw exception on null values(.e.g string) instead of just setting default value?

### ISSUE THREAD

**Issue by zeinali0** [grpc/grpc-dotnet#734]
Why generated code throw exception on null value assignment?
I know in new version of protobuf(v3) they decide to remove optional feature and all field most have value.
But why just don't set default value for some primitive type like string instead of throwing ArgumantNullException? this behavior has conflict with some tools like AutoMapper.
I mean this behavior would affect other part of a program.
if in grpc-area all null value most be replaced with default value so just keep this constraint in grpc-area. throwing a exception for setting null value would cause this constraint flow in other part of program which i think it is not a good practice and it is against cross-cutting concern.

**Comment by JamesNK** [comment]
We use Google.Protobuf for code generation. You should ask this question at https://github.com/google/protobuf.

Include "C#" in the title.
