### ISSUE TITLE
Enabling javascript debugging

### ISSUE THREAD

**Issue by albertly** [grpc/grpc-dotnet#742]
I was not able to debug client side JavaScript in examples\Browser\Server\wwwroot\Scripts\index.js
Why not to enable source-map ? **--devtool inline-source-map**

### Describe the solution you'd like
In Server.csproj 
```
 <Target Name="DebugEnsureNodeEnv" BeforeTargets="Build" Condition=" '$(Configuration)' == 'Debug' And !Exists('$(SpaRoot)node_modules') ">
 ...
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npx webpack --debug --devtool inline-source-map scripts/index.js" />
  </Target>
```

After I did it, I was able to debug.

**Comment by JunTaoLuo** [comment]
Sounds reasonable, care to send a PR?

**Comment by albertly** [comment]
Sure, I can do it.  But I have a question. How do you generate .csproj file ? Do you edit it manually or via some kind of "project template" ? If it is possible I would like to make it more generic than just put a few lines in specific Server.csproj file.

**Comment by JunTaoLuo** [comment]
Please edit the .csproj manually in this case. The npm and npx commands are custom to this project.

**Comment by JunTaoLuo** [comment]
Addressed by https://github.com/grpc/grpc-dotnet/pull/750
