### ISSUE TITLE
JavaScript Bundle does not regenerated after Rebuild Project

### ISSUE THREAD

**Issue by albertly** [grpc/grpc-dotnet#743]
### What version of gRPC and what language are you using?
Latest, up to date. From this repo.

### What operating system (Linux, Windows,...) and version?
Windows 10 Pro 1909

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\albertly\Downloads\tmp\grpc\.dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.1.100 [C:\Users\albertly\Downloads\tmp\grpc\.dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [C:\Users\albertly\Downloads\tmp\grpc\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Users\albertly\Downloads\tmp\grpc\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Users\albertly\Downloads\tmp\grpc\.dotnet\shared\Microsoft.WindowsD

### What did you do?
Project : examples\Browser
I've deleted 
examples\Browser\Server\wwwroot\dist\main.js 
This is a bundle generated by webpack.
### What did you expect to see?
After rebuild project I expected to see new file generated.

### What did you see instead?
No file generated. Only after deleting node_modules folder and rebuilding - node_modules was restored and main.js regenerating.

### Anything else we should know about your project / environment?
Microsoft VS Enterprise 2019 16.3.0

**Comment by JunTaoLuo** [comment]
HOw did you trigger the rebuild? My suspicion is that the `Build` target wasn't triggered and therefore our custom targets did not run: https://github.com/grpc/grpc-dotnet/blob/master/examples/Browser/Server/Server.csproj#L19.

**Comment by albertly** [comment]
I've just pressed rebuild solution from the menu.

**Comment by JamesNK** [comment]
JavaScript build only runs if node_modules does not exist:

https://github.com/grpc/grpc-dotnet/blob/b2845043e8993c974f2735c4059fdf94f56056ab/examples/Browser/Server/Server.csproj#L19

I copied this from the SPA template. If there is a better way of integrating node+.NET then I'm open to improvements.

**Comment by JunTaoLuo** [comment]
Looks like this is by design

**Comment by albertly** [comment]
No it is very bad behavior.
The solution is rather simple: to check "Date modified" of bundle file. 
If it is less of any of wwwroot\Scripts\*.js files then regeneration is needed. That's all
