### ISSUE TITLE
Send/Receive binary data from/to browser? 

### ISSUE THREAD

**Issue by albertly** [grpc/grpc-dotnet#744]
Project examples\Browser

For test purposes I've changed greet.proto to
```
message HelloReply {
  bytes message = 1;
}

```
And class GreeterService.cs to
```
        public override Task<HelloReply> SayHello(HelloRequest request, ServerCallContext context)
        {
            byte[] b = new byte[20];
            new Random().NextBytes(b);
            
            return Task.FromResult(new HelloReply { Message = Google.Protobuf.ByteString.CopyFrom(b) });
        }
```

I hoped to receive binary data.

Unfortunately, I don't think that transfer was truly binary 

`proto.greet.HelloReply {wrappers_: null, messageId_: undefined, arrayIndexOffset_: -1, array: Array(1), pivot_: 1.7976931348623157e+308, …}wrappers_: nullmessageId_: undefinedarrayIndexOffset_: -1array: Array(1)0: "`N˭!H(zNݕ"length: 1__proto__: Array(0)pivot_: 1.7976931348623157e+308convertedPrimitiveFields_: {}__proto__: jspb.Message
`
I've got something in base64
AAAAABYKFKty+cj41eqWOYIcCZXF2Vu01pv8gAAAABBncnBjLXN0YXR1czogMA0K

Is it possible at all ?

I want to increase speed when uploading/downloading files  with gRPC.

**Comment by JunTaoLuo** [comment]
We send bytes or base64 encoded based on the [request content type](https://github.com/grpc/grpc-dotnet/blob/bee59db0bec2956d0b2e1941066950b2650f0e48/src/Grpc.AspNetCore.Web/Internal/GrpcWebMiddleware.cs#L120-L127). It seems like the js client in our browser sample is opting for the GrpcWebText content type (i.e. "application/grpc-web-text"). In our C# client, we specify the mode when creating the client: https://github.com/grpc/grpc-dotnet/blob/bee59db0bec2956d0b2e1941066950b2650f0e48/src/Grpc.AspNetCore.Web/README.md#grpcnetclientweb, I suppose you'll need to do something similar for the js client.

**Comment by albertly** [comment]
It's work. **Thank you**.
I've just changed the mode to grpcweb.

The full command is 
`./protoc greet.proto --js_out=import_style=commonjs:./ --grpc-web_out=import_style=commonjs,mode=grpcweb:./ --plugin=protoc-gen-grpc-web=./protoc-gen-grpc-web.exe`

P.S.  grpc\examples\Browser\Server\wwwroot\Scripts\README.md file was very usefull.
