### ISSUE TITLE
Add support for gRPC Swagger

### ISSUE THREAD

**Issue by profnimrod** [grpc/grpc-dotnet#745]
### Is your feature request related to a problem? Please describe.
I wonder if support for a project like gRPC Swagger (https://github.com/grpc-swagger/grpc-swagger) could be added.  Or perhaps better, support for gRPC Gateway (https://github.com/grpc-ecosystem/grpc-gateway) where if the appropriate REST options are included in the proto, a REST API controller is automatically created, which can then be readily documented using Swagger/OpenAPI.

### Describe the solution you'd like
If the appropriate REST option is added to the proto service definition, e.g., 

service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply){
    option (google.api.http) = {
      post: "/api/controller/sayhello"
      body: "*"
    };
}

then a Web API controller is automatically created with the appropriate name and methods.  The startup file is updated to include the controller and endpoints.  To this Swagger could be manually added.

**Comment by JunTaoLuo** [comment]
Have you taken a look at https://github.com/aspnet/AspLabs/tree/master/src/GrpcHttpApi?

**Comment by profnimrod** [comment]
Ah, I hadn't.  Looks interesting.  I've cloned the repository but having trouble compile the relevant projects :-(

**Comment by JunTaoLuo** [comment]
Can you add more details on what issues you're running into?

**Comment by profnimrod** [comment]
Sure thing - after making sure I had the last .Net Core 3.0 SDK and runtime installed I still get:

> Severity	Code	Description	Project	File	Line	Suppression State

Error		Unable to find package Microsoft.DotNet.Arcade.Sdk. No packages exist with this id in source(s): gRPC, NuGet.org (v3)	Microsoft.AspNetCore.Grpc.HttpApi		5	

> Severity	Code	Description	Project	File	Line	Suppression State

Error		C:\Program Files\dotnet\sdk\3.0.102\Sdks\Microsoft.DotNet.Arcade.Sdk\Sdk not found. Check that a recent enough .NET Core SDK is installed and/or increase the version specified in global.json.	Microsoft.AspNetCore.Grpc.HttpApi		5

**Comment by JunTaoLuo** [comment]
The Microsoft.AspNetCore.Grpc.HttpApi package is not published anywhere. You need to build and pack the project https://github.com/aspnet/AspLabs/tree/master/src/GrpcHttpApi/src/Microsoft.AspNetCore.Grpc.HttpApi and consume the package.

**Comment by profnimrod** [comment]
Thanks - yes I get that and that is what I was trying to do, but it failed to build because it couldn't find Microsoft.DotNet.Arcade.Sdk which I'd never heard of.  Fixed it by adding "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json" to my NuGet package source. Have successfully built now and can hopefully do some testing.

**Comment by profnimrod** [comment]
When I try to run a test (using exactly the same proto as in the Sample) I get a compilation error:

> The type or namespace name 'Api' does not exist in the namespace 'Google' (are you missing an assembly reference?)

This is in the Greet.cs that is generated from the proto:

`syntax = "proto3";

import "google/api/annotations.proto";

package greet;

service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply) {
    option (google.api.http) = {
      get: "v1/greeter/{name}"
    };
  }
  rpc SayHellos (HelloRequest) returns (stream HelloReply);
}

message HelloRequest {
  string name = 1;
  string test_name = 2;
}

message HelloReply {
  string message = 1;
}`

Any ideas?  Has this anything to do with Known Issue #1 on https://github.com/aspnet/AspLabs/tree/master/src/GrpcHttpApi?  I have Google.Protobuf 3.11.2 installed as opposed to 3.8, but I can't downgrade as Grpc.AspNetCore 2.27.0 requires it to be >= 3.10.0.

**Comment by profnimrod** [comment]
OK - got it working... sweet!  This is certainly moving in the right direction for what I'd like to do.  The reason I'd like to have this work with Swagger is that I can then publish the API design and documentation to something like Swagger Hub to support multi user collaboration.  It would also be very cool to be able to roundtrip between proto and OpenAPI yaml... At this point I'd definitely settle for being able to go from proto to OpenApi - this project nearly gets there.

I got a test gRPC server with REST endpoints up and running.  I add the relevant additions needed to add Swagger to my startup, which now looks like:

`public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddGrpcHttpApi();
            services.AddMvc();

            // Register the Swagger generator, defining 1 or more Swagger documents
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Version = "v1" });
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            // Enable middleware to serve generated Swagger as a JSON endpoint.
            app.UseSwagger();

            // Enable middleware to serve swagger-ui (HTML, JS, CSS, etc.),
            // specifying the Swagger JSON endpoint.
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
            });

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapGrpcService<GreeterService>();
            });
        }
    }`

It all compiles and runs OK, but when I go to the Swagger UI endpoint, the UI loads OK, but states that "No operations defined in spec!".  Any ideas on how I can get Swagger to recognize the endpoints created by Microsoft.AspNetCore.Grpc.HttpApi ? Or could Swagger compatibility be added some time?

**Comment by JunTaoLuo** [comment]
We haven't tried GrpcHttpApi with Swagger so I'm not surprised it doesn't work right out of the box. It's something that we can investigate in the future though.

**Comment by profnimrod** [comment]
Yes, thanks... I wasn't surprised either and know it is not necessarily trivial to do that.  There is a nice gRPC-swagger JAVA project that you might find of relevance... having the ability to insert optional Swagger annotations in the proto messages and services would be very helpful indeed.

**Comment by JamesNK** [comment]
That .NET swagger library integrates into MVC. They would need to add custom support for gRPC+REST.

**Comment by JamesNK** [comment]
Sample that shows how to use gRPC HTTP API + Swagger

https://github.com/aspnet/AspLabs/tree/master/src/GrpcHttpApi/sample

**Comment by arttobe** [comment]
I followed this, but it is not working in dotnet 5
Has something changed?
The project compiles without error

**Comment by MichaelPeter** [comment]
Is it still planned to put this into Production? 

Would look really forward in a way to write an documentation in GRPC without having to setup a golang grpc-gateway.
