### ISSUE TITLE
Does hosting GRPC services automatically preclude me from also hosting REST endpoints

### ISSUE THREAD

**Issue by ronnyek** [grpc/grpc-dotnet#746]
I've got a API with rest endpoints, and was attempting to additionally expose some grpc services.

I was able to get GRPC services running, however only by setting Kestrel ListenOptions to allow protocol Http2 only.

If I set to Http1AndHttp2, the grpc client would immediately return an exception saying "cancelled".

If I set it to Http2 explicitly, grpc services work, but rest endpoints would return ERR_INVALID_HTTP_RESPONSE

So my question is.. is there a limitation that can be worked around to host GRPC services along side rest services? (I'm not suggesting this should be automatic, or anything like that... just serving rest endpoints as well as additionally listening for GRPC clients.

(question originates from: https://github.com/protobuf-net/protobuf-net.Grpc/issues/55)

**Comment by JamesNK** [comment]
Are you using TLS? Http1AndHttp2 requires TLS for the ALPN handshake - https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1#listenoptionsprotocols

**Comment by JunTaoLuo** [comment]
@ronnyek since there hasn't been any responses, I'm closing this issue. Please reopen if you have more details to share.
