### ISSUE TITLE
Resolve gRPC Clients by name

### ISSUE THREAD

**Issue by thereapman** [grpc/grpc-dotnet#747]
We want to use the same proto service implementation for different endpoints while using the client factory. Registering with:
```
services.AddGrpcClient<TClient>("service-1", options => (...))
services.AddGrpcClient<TClient>("service-2", options => (...))
```

and resolving using 

```
public class SomeClass {
   SomeClass(TClient client) {}
}
```

Is it possible to instead of injecting the client directly to inject some kind of an `IGrpcClientFactory` (same approach as `IHttpClientFactory`) and call an `.CreateClient("service-1")`?

**Comment by JamesNK** [comment]
Yes. Inject GrpcClientFactory.

https://github.com/grpc/grpc-dotnet/blob/master/src/Grpc.Net.ClientFactory/GrpcClientFactory.cs
