### ISSUE TITLE
Document using gRPC-Web with Grpc.Net.ClientFactory

### ISSUE THREAD

**Issue by AnthonyGiretti** [grpc/grpc-dotnet#749]
Hi!

Based on the following example (a .NET gRPC client configured for gRPC-web)

```
var handler = new GrpcWebHandler(GrpcWebMode.GrpcWebText, new HttpClientHandler());
var channel = GrpcChannel.ForAddress("https://localhost:5001", new GrpcChannelOptions
{
        HttpClient = new HttpClient(handler)
});
```

Is it possible to have an extension method that registers in DI a .NET gRPC client configured for gRPC-web like this (finally like _**AddGrpcClient**_)?

```
services.AddGrpcWebClient<GreeterClient>(o =>
{
     o.Mode = GrpcWebMode.GrpcWebText,
     o.HttpVersion = HttpVersion.Version10, // optional (or HttpVersion.Version20)
     o.InnerHandler = new HttpMessageHandler(), // optional , custom handler else default: new HttpMessageHandler()
     o.GrpcChannelOptions.Address = new Uri("https://localhost:5001");
 });

**Comment by JamesNK** [comment]
It would require a NuGet package that depends on both Grpc.Net.Client.Web and Grpc.Net.ClientFactory. Certainly possible but probably not worth it from a maintainability perspective.

 I think it would be better to show how to configure grpcweb with a factory in docs

**Comment by AnthonyGiretti** [comment]
I understand, I tried to do it myself, by creating a project named _Grpc.Net.ClientFactory.Web_ in the solution, and I realized I needed a lot of stuff from Grpc.Net.ClientFactory, so big refactor is required 
as you mentionned.
I'd like to try that refactor, if I succeed and if it's relevant I'll PR you that refactor.

For the Factory that's a good idea.
Thanks

**Comment by JamesNK** [comment]
I don’t think it will be used enough to warrant a new package. Showing how to use the existing client factory with grpcweb in docs is the right level of investment here. If it becomes really popular then we could publish a new package in the future.

You’re welcome to publish your own package if you want.

**Comment by AnthonyGiretti** [comment]
Thank you!
-- 
*Anthony Giretti*
*Blogger, Speaker | MVP, MCSD*
*m:*  +1 514 557 1380 <+1+514+557+1380>
*s:  *anthonygiretti.com
*e:  *anthony.giretti@gmail.com

**Comment by paburgos** [comment]
Hi, wondering if any updates on this? or, can you provide an example here?
