### ISSUE TITLE
Grpc.Web - Hosting issues under IIS or Application Service Plan

### ISSUE THREAD

**Issue by Harkole** [grpc/grpc-dotnet#759]
We’ve already got some gRPC clients (Dotnet Core Worker Service) running using reverse proxies and Kestrel and this works fine. But we are keen to switch to App Service Plans (or even a VM and IIS) as this is the business standard approach. As such, this post was a great bit of news and so we quickly set about converting the start up in both client and server to support it.

Having deployed to both VM running IIS and then an Application Service plan we keep getting met with the same error message, I’m fairly sure it’s to do with IIS configuration but I can’t find anything that helps with the issue.

A static page on the application can be displayed and proves the system is running and accepting requests, so it is a purely gRPC issue as far as I can tell.

The VM is running Server 2016 and Dotnet Core 3.1.1 Hosting Bundle and has the latest Windows updates installed, the application was deployed as an In-Process set up. The application service plan we tried was the standard Azure Application Service Plan (Windows based), it returned the same client error as the VM.

gRPC in Visual Studio Debug gives:

Status(StatusCode=Internal, Detail=”Content-Type ‘application/grpc-web-text’ is not supported.”)

The logs from the IIS server show the following:

warn: Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository[50]
Using an in-memory repository. Keys will not be persisted to storage.

warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[59]
Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.

warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
No XML encryptor configured. Key {d496f657-222b-4e28-8648-a2619138201f} may be persisted to storage in unencrypted form.

info: Microsoft.Hosting.Lifetime[0]
Application started. Press Ctrl+C to shut down.

info: Microsoft.Hosting.Lifetime[0]
Hosting environment: Production

info: Microsoft.Hosting.Lifetime[0]
Content root path:

fail: Grpc.AspNetCore.Server.ServerCallHandler[6]
Error when executing service method ‘AuthenticateApp’.

System.InvalidOperationException: Trailers are not supported for this response. The server may not support gRPC.
at Grpc.AspNetCore.Server.Internal.GrpcProtocolHelpers.GetTrailersDestination(HttpResponse response)
at Grpc.AspNetCore.Server.Internal.HttpResponseExtensions.ConsolidateTrailers(HttpResponse httpResponse, HttpContextServerCallContext context)
at Grpc.AspNetCore.Server.Internal.HttpContextServerCallContext.EndCallCore()
at Grpc.AspNetCore.Server.Internal.HttpContextServerCallContext.EndCallAsync()
at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase<code>3.&lt;HandleCallAsync&gt;g__AwaitHandleCall|17_0(HttpContextServerCallContext serverCallContext, Method</code>2 method, Task handleCall)

fail: Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer[2]
Connection ID “7566047384183026471”, Request ID “8000b328-0002-6900-b63f-84710c7967bb”: An unhandled exception was thrown by the application.

System.InvalidOperationException: Trailers are not supported for this response. The server may not support gRPC.
at Grpc.AspNetCore.Server.Internal.GrpcProtocolHelpers.GetTrailersDestination(HttpResponse response)
at Grpc.AspNetCore.Server.Internal.HttpResponseExtensions.ConsolidateTrailers(HttpResponse httpResponse, HttpContextServerCallContext context)
at Grpc.AspNetCore.Server.Internal.HttpContextServerCallContext.ProcessHandlerError(Exception ex, String method)
at Grpc.AspNetCore.Server.Internal.HttpContextServerCallContext.ProcessHandlerErrorAsync(Exception ex, String method)
at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase<code>3.&lt;HandleCallAsync&gt;g__AwaitHandleCall|17_0(HttpContextServerCallContext serverCallContext, Method</code>2 method, Task handleCall)
at Microsoft.AspNetCore.Routing.EndpointMiddleware.g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.g__AwaitMatcher|8_0(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task<code>1 matcherTask)
at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT</code>1.ProcessRequestAsync()

fail: Grpc.AspNetCore.Server.ServerCallHandler[6]
Error when executing service method ‘AuthenticateApp’.

System.InvalidOperationException: Trailers are not supported for this response. The server may not support gRPC.
at Grpc.AspNetCore.Server.Internal.GrpcProtocolHelpers.GetTrailersDestination(HttpResponse response)
at Grpc.AspNetCore.Server.Internal.HttpResponseExtensions.ConsolidateTrailers(HttpResponse httpResponse, HttpContextServerCallContext context)
at Grpc.AspNetCore.Server.Internal.HttpContextServerCallContext.EndCallCore()
at Grpc.AspNetCore.Server.Internal.HttpContextServerCallContext.EndCallAsync()
at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.g__AwaitHandleCall|17_0(HttpContextServerCallContext serverCallCon

**Comment by JamesNK** [comment]
IIS and Azure App Service can't host gRPC with HTTP/2. These servers don't have support for HTTP/2 trailers which is required for gRPC to function correctly.

To run gRPC in these environments you need to use gRPC-Web. Docs: https://docs.microsoft.com/aspnet/core/grpc/browser

Example of gRPC-Web in Azure App Service: https://grpcweb.azurewebsites.net/

**Comment by Harkole** [comment]
@JamesNK apologies for not making it clear, the above error is occurring having followed your blog and converted the service to Grpc.Web

**Comment by JamesNK** [comment]
Are you sure it is setup correctly on the server?
1. `UseGrpcWeb` middleware is in the correct location
2. `MapGrpcService` has `EnableGrpcWeb`, or you have `services.AddGrpcWeb(o => o.GrpcWebEnabled = true);` in `ConfigureServices`

**Comment by Will-Blackburn** [comment]
I believe so, I won't be able to generate debug until Monday but this is the config/service settings:

Configure section
`// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();
            app.UseDefaultFiles();
            app.UseStaticFiles();

            app.UseGrpcWeb();

            app.UseRouting();
            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                // Map HTTP API Controllers
                endpoints.MapControllers();

                // Map GRPC services
                endpoints.MapGrpcService<AuthenticationGrpcService>().EnableGrpcWeb();
                endpoints.MapGrpcService<AuditGrpcService>().EnableGrpcWeb();
                endpoints.MapGrpcService<FileEndpointConfigurationGrpcService>().EnableGrpcWeb();

                endpoints.MapGet("/", async context =>
                {
                    await context.Response.WriteAsync("Communication with gRPC endpoints must be made through a gRPC client. To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909");
                });
            });
        }`

And the top section of Services

` // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddOptions();

            services.Configure<IISServerOptions>(options =>
            {
                options.AutomaticAuthentication = false;
                options.AllowSynchronousIO = true;
            });`

**Comment by JamesNK** [comment]
Your problem is UseGrpcWeb needs to be between UseRouting and UseEndpoints.

**Comment by Will-Blackburn** [comment]
Thanks James, I'll confirm everything on Monday when I can access the code/servers again

**Comment by AnthonyGiretti** [comment]
Hi,

I also have an issue with grpc-web in Azure app service.
My angular app works fine if grpc web app is hosted locally, once deployed, neither the local angular app nor the  app hosted in azure work. I always have CORS issue, I have enabled `.AllowAnyOrigin()` .
So I don't understand what's going on.

This is works fine
![grpcweblocal](https://user-images.githubusercontent.com/21200167/74108720-209cd180-4b4b-11ea-916a-bbe08b035c3a.png)

Once deployed:
![grpcweb1](https://user-images.githubusercontent.com/21200167/74108788-aa4c9f00-4b4b-11ea-9a69-91df31bc6494.png)

In the meantime when I use grpc-web from a .NET client, it doesn't work neither if my grpc-web app is hosted in azure like my angular app, I get "Cancelled" with no errors details, I use HTTP version 1.1:

![grpcwebnet](https://user-images.githubusercontent.com/21200167/74108819-da943d80-4b4b-11ea-8542-8801075ee238.png)

Conclusion:
Whatever the client, Since grpc-web is hosted in Azure it doesn't work

**Comment by AnthonyGiretti** [comment]
By the way,

here is my startup config:

`namespace DemoAspNetCore3
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        public void ConfigureServices(IServiceCollection services)
        {
            
            services.AddDbContext<DemoDbContext>(options => options.UseSqlServer("connectionstring"));

            services.AddCors(options =>
            {
                options.AddPolicy("MyPolicy",
                builder =>
                {
                    builder.AllowAnyOrigin()
                    .AllowAnyHeader()
                    .AllowAnyMethod();
                });
            });

            services.AddGrpc(options =>
            {
                options.EnableMessageValidation();
                options.Interceptors.Add<LoggerInterceptor>();
            });

            services.AddValidator<CountryCreateRequestValidator>();

            services.AddGrpcValidation();

            services.AddAutoMapper(Assembly.Load("DemoGrpc.Web"));

            services.AddScoped<ICountryService, CountryService>();
            services.AddScoped<ICountryRepository, EFCountryRepository>();

            services.AddApplicationInsightsTelemetry();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();

            app.UseCors("MyPolicy");

            app.UseGrpcWeb();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapGrpcService<MyOwnGRpcService>();
                endpoints.MapGrpcService<CountryGrpcService>().EnableGrpcWeb();

                endpoints.MapGet("/", async context =>
                {
                    await context.Response.WriteAsync("Communication with gRPC endpoints must be made through a gRPC client. To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909");
                });
            });
        }
    }
}
`

**Comment by JamesNK** [comment]
It definitely works... https://grpcweb.azurewebsites.net/

**Comment by JamesNK** [comment]
> So I don't understand what's going on.

I tested CORS working here - https://github.com/grpc/grpc-dotnet/blob/a1bb10d4a96c8eeb1ee13959a8b4426d29b2557b/testassets/InteropTestsWebsite/Startup.cs

Try adding `builder.WithExposedHeaders("Grpc-Status", "Grpc-Message");`

**Comment by JamesNK** [comment]
> I get "Cancelled" with no errors details

Did you try enable logging in the client to see what is going on?

https://docs.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-3.1#grpc-client-logging

**Comment by AnthonyGiretti** [comment]
I believe you.
I saw your tweet last december. 
Since grpc-web has been released I'm unable to make it work in Azure, locally everything work fine, I'm so confused

Let me try solution you gave me.

For the .NET client, I haven't checked yet, I get "CANCELLED" error after 1 min since the request has been sent

**Comment by AnthonyGiretti** [comment]
It doesn't work better with `builder.WithExposedHeaders("Grpc-Status", "Grpc-Message");`

But I have a different behavior now, the call remains peding during 1 min before sending me CORS errors

![grpc-angular](https://user-images.githubusercontent.com/21200167/74110562-9872f800-4b5b-11ea-8a74-ed8ac7f33ad8.png)

By the way in your code, the policy name is missing in UseCors:

`app.UseCors(app.UseCors("MyPolicy"););`

**Comment by JamesNK** [comment]
CORS metadata with the name is on the gRPC service endpoint.

**Comment by AnthonyGiretti** [comment]
I still have the same issue. I really don't understand.

Maybe it's related to my appservice instance?

**Comment by AnthonyGiretti** [comment]
I could not find the solution for CORS issue.

So I tried with a console app these scenarii:

1-
My appservice has HTTP 2 enabled 
![image](https://user-images.githubusercontent.com/21200167/74115153-b7818200-4b7b-11ea-93ee-2648addc9106.png)

I get this response:

![image](https://user-images.githubusercontent.com/21200167/74115176-d8e26e00-4b7b-11ea-8984-74deba1aa39f.png)

2- 
My appservice has HTTP 1.1 enabled 
![image](https://user-images.githubusercontent.com/21200167/74115214-07604900-4b7c-11ea-8e93-102beeb1e555.png)

I get this answer (the response takes 1 min to come)

![image](https://user-images.githubusercontent.com/21200167/74115270-73db4800-4b7c-11ea-9af6-72128cbfcb0e.png)

3-
In localhost with HTTP 2

![image](https://user-images.githubusercontent.com/21200167/74115332-c1f04b80-4b7c-11ea-8937-9d8bfac901d1.png)

 It works fine:

![image](https://user-images.githubusercontent.com/21200167/74115372-f3691700-4b7c-11ea-8a01-75f066b216c3.png)


I really think there is an issue in my App service.

Here are my setting, do you see something wrong, I don't think so but at that point....

![image](https://user-images.githubusercontent.com/21200167/74115504-83a75c00-4b7d-11ea-970e-3a5c2d92ba30.png)

**Comment by JamesNK** [comment]
https://medium.com/@abhijeetg/cross-origin-resource-sharing-cors-azure-app-service-bec8d9747426

?

I don't know, I'm just linking what I found on Google.

**Comment by AnthonyGiretti** [comment]
I have enabled detailed logging in my console app:

Scenario 1: grpc-web using http 1.1 client side and in appservice:

![image](https://user-images.githubusercontent.com/21200167/74120535-b4918c00-4b91-11ea-9203-55edcc5bdebf.png)

 I get this:

![image](https://user-images.githubusercontent.com/21200167/74120563-cd9a3d00-4b91-11ea-956b-c9296066892e.png)

Scenario 2: grpc-web using http 2 client side and in appservice:

![image](https://user-images.githubusercontent.com/21200167/74120607-ed316580-4b91-11ea-8780-6813741abd03.png)

I get this:

![image](https://user-images.githubusercontent.com/21200167/74120895-3a620700-4b93-11ea-8be0-f701cf2ea7dc.png)


Scenario 3: grpc-web using http 2 client side and grpc-wweb server in localhost (works fine):

![image](https://user-images.githubusercontent.com/21200167/74120718-7ea0d780-4b92-11ea-80ca-b8d7a8898778.png)

![image](https://user-images.githubusercontent.com/21200167/74120706-6a5cda80-4b92-11ea-9ec7-6e0a267dfe81.png)


I tried  with Linux AppService and Windows AppService

I think I tried everything...

**Comment by AnthonyGiretti** [comment]
Thanks for the link.

I suspect that CORS issue is not the real error. I suspect the app crashes before cors checks.
With SPA like Angular and React that kind of "fake CORS issue" occurs.

I have to go further and diagnose the AppService with Azure Tools

**Comment by JamesNK** [comment]
This works for me:

```csharp
static async Task Main(string[] args)
{
    var handler = new GrpcWebHandler(GrpcWebMode.GrpcWebText, new HttpClientHandler());
    var channel = GrpcChannel.ForAddress("https://grpcweb.azurewebsites.net/", new GrpcChannelOptions
    {
        HttpClient = new HttpClient(handler)
    });

    var client = new Greeter.GreeterClient(channel);
    var response = await client.SayHelloAsync(new HelloRequest { Name = ".NET" });

    Console.WriteLine(response.Message);
}
```

![image](https://user-images.githubusercontent.com/303201/74121330-01c23c00-4c2c-11ea-96c9-6e5b220c4cfe.png)

**Comment by AnthonyGiretti** [comment]
OK,

I'll consume your proto file here https://github.com/grpc/grpc-dotnet/blob/a1bb10d4a96c8eeb1ee13959a8b4426d29b2557b/testassets/Proto/greet.proto

and call your hosted service. 

with my angular app and my console app.

Let's see....

Thanks again for your help

**Comment by AnthonyGiretti** [comment]
Interesting

![image](https://user-images.githubusercontent.com/21200167/74121900-5c5d8880-4b97-11ea-981a-c5e8b8b6e77e.png)

![image](https://user-images.githubusercontent.com/21200167/74121827-1e606480-4b97-11ea-8666-a190ed5beba6.png)

**Comment by AnthonyGiretti** [comment]
By the way my assemblies are up to date (2.27)

**Comment by Harkole** [comment]
Morning @JamesNK we've updated the middle ware order and we're still not seeing success, the client is returning an exception stating

`Error starting gRPC call: Buffer is not large enough for header`

The server logs from the VM show:

```fail: Grpc.AspNetCore.Server.ServerCallHandler[6]
      Error when executing service method 'AuthenticateApp'.
System.InvalidOperationException: Trailers are not supported for this response. The server may not support gRPC.
   at Grpc.AspNetCore.Server.Internal.GrpcProtocolHelpers.GetTrailersDestination(HttpResponse response)
   at Grpc.AspNetCore.Server.Internal.HttpResponseExtensions.ConsolidateTrailers(HttpResponse httpResponse, HttpContextServerCallContext context)
   at Grpc.AspNetCore.Server.Internal.HttpContextServerCallContext.EndCallCore()
   at Grpc.AspNetCore.Server.Internal.HttpContextServerCallContext.EndCallAsync()
   at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase'3.<HandleCallAsync>g__AwaitHandleCall|17_0(HttpContextServerCallContext serverCallContext, Method'2 method, Task handleCall)
fail: Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer[2]
      Connection ID "11673330257229787912", Request ID "80003309-0005-a200-b63f-84710c7967bb": An unhandled exception was thrown by the application.
System.InvalidOperationException: Trailers are not supported for this response. The server may not support gRPC.
   at Grpc.AspNetCore.Server.Internal.GrpcProtocolHelpers.GetTrailersDestination(HttpResponse response)
   at Grpc.AspNetCore.Server.Internal.HttpResponseExtensions.ConsolidateTrailers(HttpResponse httpResponse, HttpContextServerCallContext context)
   at Grpc.AspNetCore.Server.Internal.HttpContextServerCallContext.ProcessHandlerError(Exception ex, String method)
   at Grpc.AspNetCore.Server.Internal.HttpContextServerCallContext.ProcessHandlerErrorAsync(Exception ex, String method)
   at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase'3.<HandleCallAsync>g__AwaitHandleCall|17_0(HttpContextServerCallContext serverCallContext, Method'2 method, Task handleCall)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT``1.ProcessRequestAsync()
fail: Grpc.AspNetCore.Server.ServerCallHandler[6]
      Error when executing service method 'AuthenticateApp'.
System.InvalidOperationException: Trailers are not supported for this response. The server may not support gRPC.
   at Grpc.AspNetCore.Server.Internal.GrpcProtocolHelpers.GetTrailersDestination(HttpResponse response)
   at Grpc.AspNetCore.Server.Internal.HttpResponseExtensions.ConsolidateTrailers(HttpResponse httpResponse, HttpContextServerCallContext context)
   at Grpc.AspNetCore.Server.Internal.HttpContextServerCallContext.EndCallCore()
   at Grpc.AspNetCore.Server.Internal.HttpContextServerCallContext.EndCallAsync()
   at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase'3.<HandleCallAsync>g__AwaitHandleCall|17_0(HttpContextServerCallContext serverCallContext, Method'2 method, Task handleCall)```

The Azure Applciation Service Plan results in the same Client error

**Comment by JamesNK** [comment]
The error message alone isn’t enough to understand what is going on. Include debug level logs and post the logs for a complete request on the server.

**Comment by AnthonyGiretti** [comment]
Hi all

Can somebody try ton consume my appservice on his side if I give him the proto file? Errors I have don’t have any sense. I can even not making work @JamesNK AppService

Thanks

**Comment by Harkole** [comment]
@JamesNK those are the logs from `stdout` on the server, what other debug information can we generate? I've got 

```csharp
services.AddGrpc(options =>
{
    options.EnableDetailedErrors = true;
});
```

**Comment by AnthonyGiretti** [comment]
OK

It's related to my machine, I tried on another machine and I could make your Appservice working.
I need to investigate why my machine has a that behaviour.

![image](https://user-images.githubusercontent.com/21200167/74159149-42e52c80-4be9-11ea-933f-2b36476a4fcb.png)

One fixed I'll retry with my AppService.

Thanks for your help

**Comment by JamesNK** [comment]
@Harkole https://docs.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-3.1#logging

**Comment by JamesNK** [comment]
> `Error starting gRPC call: Buffer is not large enough for header`

Make sure you're using version 2.27.0 of gRPC packages on the client and server.

**Comment by Will-Blackburn** [comment]
@JamesNK the client application wasn't running the latest gRPC packages (2.26.0 instead of 2.27.0).

I'm sorry, should of checked sooner but I would of expected the GrpcWeb to have a depenancy of 2.27.0 and forced the update when we installed the 2.27.0-pre1 packages. Having done this I'm now able to communicate with the Server running as an In-Process IIS application!

Haven't been able to test the Azure Application Plan from home but expect it'll be working there too as it's mirrored the errors so far

**Comment by JamesNK** [comment]
There is no dependency between the two packages which is why 2.27.0 of the client isn't automatically selected. It is an easy mistake. Docs should probably talk about it.

**Comment by AnthonyGiretti** [comment]
I finally made it work.
My app was running with .NET Core 3.1 runtime which is only compatible with Linux AppService.

![portal3](https://user-images.githubusercontent.com/21200167/74206307-cd10ad80-4c48-11ea-9df9-8689734c43bf.png)

With a Linux AppService the app just doesn't start:

![unnamed](https://user-images.githubusercontent.com/21200167/74206371-1cef7480-4c49-11ea-96ae-6d307cf041cb.png)

So I downgraded to .NET Core 3.0 and deployed on a Windows AppService and it works fine now.

It was not a CORS issue.

Demo here: https://anthonygiretti.blob.core.windows.net/grpcwebdemo/index.html
(The Angular 8 app is deployed in static website.)

About my HttpClient which failed to call your AppService I never found the solution, I just started a new project from scratch and it works fine now.

Thanks for your support and I hope this will help other people

**Comment by JamesNK** [comment]
I set it up to run in Linux here: http://grpcweblinux.azurewebsites.net/

**Comment by Schuttrim** [comment]
When Using Grpc-Web with a .Net Framework Application, we had the issue that HTTP/2 wasn't supported.

We fixed it by using the `System.Net.Http.WinHttpHandler` package.

We would then inject this custom HttpHandler into the HttpClient that's used by the GrpcChannel.

    public class Http2CustomHandler : WinHttpHandler
    {
        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, System.Threading.CancellationToken cancellationToken)
        {
            request.Version = new Version("2.0");
            return base.SendAsync(request, cancellationToken);
        }
    }
