### ISSUE TITLE
Update Grpc.Core.Api with way to create AuthContext

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#76]
re: https://github.com/grpc/grpc-dotnet/issues/72#issuecomment-461243827

The `AuthContext` constructor is internal and `Grpc.AspNetCore.Server` has no way to create it.

**Comment by jtattermusch** [comment]
I'd like to give the AuthContext a bit more thought. 
If we don't manage to do this before the 1.19.0-pre1 release, would it help if we gave Grpc.AspNetCore.Server  access to internals of Grpc.Core.Api?

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/blob/ff51441a29403c50495dc6ee3708e04ff088871d/src/csharp/Grpc.Core.Api/Properties/AssemblyInfo.cs#L58

**Comment by jtattermusch** [comment]
Or we could use this https://www.strathweb.com/2018/10/no-internalvisibleto-no-problem-bypassing-c-visibility-rules-with-roslyn/

**Comment by JamesNK** [comment]
I'm not a fan of InternalsVisibleTo outside of testing. It is easy for a developer to modify internal code without realizing it is part of the public API.

> Or we could use this [strathweb.com/2018/10/no-internalvisibleto-no-problem-bypassing-c-visibility-rules-with-roslyn](https://www.strathweb.com/2018/10/no-internalvisibleto-no-problem-bypassing-c-visibility-rules-with-roslyn/)

That's even scarier 😋
