### ISSUE TITLE
grpc-status missing when it should be 0 (OK)

### ISSUE THREAD

**Issue by AnthonyGiretti** [grpc/grpc-dotnet#761]
Hi!

Some weeks ago I created a Polly rule that allow call retry in some cases. It was working fine.
Here is the code as a reminder:

![image](https://user-images.githubusercontent.com/21200167/74109806-aa9d6800-4b54-11ea-97ee-746c5dcd0dab.png)

Retry calls works fine (because grpc-status is well set) 👍 , in fact when I raise an RpcException whatever the status I set into.

However,

My client crashes when the call succeed, because grpc-status is missing.
According to the gRPC spec (if I understand well), when a call succeed it should return grpc-status: 0 in headers.

Is it a bug in grpc-dotnet?

If not, then I just need to prevent crash when grpc-status is missing.

Thank you!

Failing call:
![failing code](https://user-images.githubusercontent.com/21200167/74109781-5e522800-4b54-11ea-8910-246d806c9957.png)

Successful call:
![succeed call](https://user-images.githubusercontent.com/21200167/74109784-64e09f80-4b54-11ea-83b9-492ea36cd0a0.png)

**Comment by AnthonyGiretti** [comment]
OH!

I don't know if it's normal, but I found grpc-status in the response body instead of in the headers

![grpc-status-body](https://user-images.githubusercontent.com/21200167/74110232-bdb23700-4b58-11ea-8fee-290acbee5bb9.png)

**Comment by JamesNK** [comment]
grpc-status is written as a message with gRPC-Web. That is how gRPC-Web is able to work in HTTP/1.1. You don't see it in the trailing headers collection because gRPC-Web doesn't use them.

**Comment by AnthonyGiretti** [comment]
and what about grpc ? the status is missing (grpc-web is disabled)

**Comment by JamesNK** [comment]
> and what about grpc ? the status is missing (grpc-web is disabled)

You're looking in the headers. grpc-status is written to trailers when there is a message. A failing call writes grpc-status to the headers because there is no message.

**Comment by AnthonyGiretti** [comment]
OK.

Thank you
