### ISSUE TITLE
non-asycn gRPC call hangs browser

### ISSUE THREAD

**Issue by ThatRickGuy** [grpc/grpc-dotnet#764]
### What version of gRPC and what language are you using?
Client - netstandard2.1, Grpc.Net.Client.Web Version 2.27.0-pre1
Server - netcoreapp3.1, Grpc.AspNetCore Version 2.27.0, Grpc.AspNetCore.Web Version 2.27.0-pre1
Shared - netstandard2.1, Google.Protobuf Version 3.11.3, Grpc.Net.Client Version 2.27.0, Grpc.Tools Version 2.27.0

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
Core 3.1.100
Blazor 3.2
 
### What did you do?
Calling gRPC non-async causes the browser (both Edge and Chrome) to hang. Edge will sometimes pop a 'long running script' error. Browsers have to be closed via task manager. Sample available here - https://github.com/ThatRickGuy/WASM-Blazor-gRPC-Sample in the FetchData.razor file, comment/uncomment the "This works" and "This doesn't" blocks. In the non-async call, the server receives and processes the request, but the client doesn't get the response. 

### What did you expect to see?
A successful non-async call to the gRPC service

### What did you see instead?
Browser hangs

**Comment by JamesNK** [comment]
That is a limitation of Blazor. Not awaiting HTTP requests causes the app to hang - https://github.com/dotnet/aspnetcore/issues/16217

You should use the async method calls on the client.

**Comment by ThatRickGuy** [comment]
Is Grpc.Net.Client.Web anticipated to be used outside of Blazor? If not, should the non-async methods be exposed? If so, can the intellisense usage have a recommendation of not using them in blazor clients?

Is it possible to get a warning on calling the non-async method at build time? 

Is it possible to get an error at run time?

**Comment by JamesNK** [comment]
> Is Grpc.Net.Client.Web anticipated to be used outside of Blazor? If not, should the non-async methods be exposed? If so, can the intellisense usage have a recommendation of not using them in blazor clients?

Yes it is used outside of Blazor. The code generated client is a separate thing. We can't remove the sync method just in Blazor.

> Is it possible to get a warning on calling the non-async method at build time?

Hmm, maybe a code analysis plugin that is built into Blazor? That's outside of the scope of gRPC.

> Is it possible to get an error at run time?

I don't think so. We can't really know

**Comment by JamesNK** [comment]
I think the right thing to do here is document this - https://docs.microsoft.com/en-us/aspnet/core/grpc/browser?view=aspnetcore-3.1#configure-grpc-web-with-the-net-grpc-client

**Comment by JamesNK** [comment]
Docs updated

**Comment by ThatRickGuy** [comment]
Excellent! That will hopefully help others from making the same mistake I made! :)
