### ISSUE TITLE
How can I get detailed information about "'System.InvalidOperationException' in System.Private.CoreLib.dll"

### ISSUE THREAD

**Issue by TihomirBl** [grpc/grpc-dotnet#768]
Hello!
I get the fallowing exception when trying to make a call on my gRPC client side:

An exception of type 'System.InvalidOperationException' occurred in System.Private.CoreLib.dll but was not handled in user code
Can't write the message because the call is complete.

I'm using .net core 3.1 and latest versions of Grpc libraries.

My question is how can I get more detailed information about what is happening?

**Comment by JamesNK** [comment]
Where did you get those error details? There isn't much information there.

You can setup logging to get more information - https://docs.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-3.1#logging

**Comment by anurse** [comment]
Closing as we haven't heard from you and close inactive issues after a short period. If you're able to get the information we requested, please comment and we can reactivate and continue investigating!

**Comment by DAerov** [comment]
> Closing as we haven't heard from you and close inactive issues after a short period. If you're able to get the information we requested, please comment and we can reactivate and continue investigating!

сука, допоможи БУДЬ ЛАСКА НАХУЙ ЦЯ ОШИБКА ЗАІБАЛА
