### ISSUE TITLE
Add cors code sample to browser sample project

### ISSUE THREAD

**Issue by hanabi1224** [grpc/grpc-dotnet#771]
It will be awesome to have cors code sample to demonstrate the case that frontend and backend does not share host or port

**Comment by AnthonyGiretti** [comment]
Hi!

I have an example here :

https://github.com/AnthonyGiretti/aspnetcore3-grpc-samples/blob/master/DemoAspNetCore3/Startup.cs

**Comment by anurse** [comment]
Thanks for the PR! We'll take a look!
