### ISSUE TITLE
Making proto from C# code

### ISSUE THREAD

**Issue by MatthewDavidCampbell** [grpc/grpc-dotnet#778]
With protobuf-net using attributes or the model a **proto** description can be made from existing C# code.  Any support for this within grpc-dotnet coming or present?  We have a bunch of legacy contracts.  Either we write proto then re-generate the C# or find a way to make proto from existing C#.

Another option might be to not use Protobuf has the serialized language.  Our solution uses CSharp with all backend services.  Assuming that csharp could be serialized | deserialized with the Grpc Microsoft extensions.

A third option which I would love feedback on is what if our model (contracts) in csharp got translated to a proto description.  Then that proro file is included in the Grpc.Tools pipeline generating Google Protobuf classes.  But instead of using the Google Protobuf classes when making client | server calls the model (contracts) are referenced then mapped "automagically" by client | server grpc pipelines | interceptors to Google Protobuf before serializing over the wire.

**Comment by JamesNK** [comment]
You can use protobuf-net with gRPC using https://protobuf-net.github.io/protobuf-net.Grpc/. It doesn't require a proto file.

We currently don't have plans to generate proto files from C# files.

**Comment by MatthewDavidCampbell** [comment]
Thanks @JamesNK.  Ended up using Protobuf-net and weaving into similar extensions that are part of Grpc Server.
