### ISSUE TITLE
Grpc.Tools should hook CoreCompile instead of BeforeCompile for WPF compatibility

### ISSUE THREAD

**Issue by uecasm** [grpc/grpc-dotnet#780]
Using Grpc.Tools 2.27.

Protobuf file generation does not work correctly in WPF; this is listed as a [known issue for .NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.0#wpf-projects-unable-to-generate-grpc-c-assets-from-proto-files) but does also affect .NET Framework as well.

The problem is that Grpc.Tools is hooking into the wrong part of the build process -- in particular a part that does not get executed for a particular compilation step used by WPF.

See https://github.com/dotnet/wpf/issues/810#issuecomment-587982956 for more info.

The suggested fix is to change `_Protobuf_Compile_BeforeCsCompile` to hook `CoreCompile` instead of `BeforeCompile`.

I have not checked if this resolves the issue with .NET Core as well, although I would assume so.  Defining the extra property (as shown in the comment above) definitely does resolve it for .NET Framework, and changing the `BeforeTargets` should have the same effect, but I have not explicitly tested that either.

**Comment by uecasm** [comment]
And now I **have** tested a patched nuget package which does just change the `BeforeTargets` from `BeforeCompile` to `CoreCompile`, and confirmed that this works for .NET Framework.

**Comment by JamesNK** [comment]
Please recreate this issue in https://github.com/grpc/grpc - Grpc.Tools is part of that repository.

**Comment by uecasm** [comment]
Ok, done.
