### ISSUE TITLE
Grpc method returning Status(StatusCode=Cancelled, Detail="Cancelled")

### ISSUE THREAD

**Issue by pranavi-cm** [grpc/grpc-dotnet#781]
### What version of gRPC and what language are you using?
GrpcCore 2.27.0, C#

### What operating system (Linux, Windows,...) and version?
Windows server 2012 R2

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
C# .NET 4.8

### What did you do?
We upgraded Grpc core and API library to 2.27.0. Since the upgrade, all the **async** calls are returned with 
Status(StatusCode=Cancelled, Detail="Cancelled")
The grpc server received the call and handled it successfully but the client returned Cancelled.
The sync calls return the result successfully.

### What did you expect to see?
Our previous version was 1.20.1 and both async and sync calls returned the result successfully.
Expected the same result with the latest version 2.27.0

**Comment by JamesNK** [comment]
Please recreate this issue on https://github.com/grpc/grpc

grpc-dotnet is for the `Grpc.AspNetCore` package, not `Grpc.Core`.
