### ISSUE TITLE
Grpc.AspNetCore.Web support on .net core 3.1

### ISSUE THREAD

**Issue by c-arnab** [grpc/grpc-dotnet#785]
I created a simple grpc dotnet service and client and then tried updating the service to support grpc web.
When I try to add package  Grpc.AspNetCore.Web, it tells me error: Package 'Grpc.AspNetCore.Web' is incompatible
I checked https://www.nuget.org/packages/Grpc.AspNetCore.Web and found that it shows under dependencies .NETCoreApp 3.0

Does this mean that this package will not support 3.1 and if so when can I expect a new nuget package supporting .net core 3.1

Thanks

**Comment by halter73** [comment]
@c-arnab Can you share your csproj? The package is supported on .NET Core 3.1.

**Comment by JamesNK** [comment]
`netcoreapp30` packages are compatible with `netcoreapp31`.

There is a sample of that package being used with netcoreapp31 here - https://github.com/grpc/grpc-dotnet/blob/1159126138d752f21c8a02b74002d83aec5f2c88/examples/Browser/Server/Server.csproj#L4
