### ISSUE TITLE
ServerCallContext.Peer format is unconventional/not as documented

### ISSUE THREAD

**Issue by tg73** [grpc/grpc-dotnet#789]
The `Grpc.Core.ServerCallContext.Peer` property is documented as:

> Address of the remote endpoint in URI format.

However, the string does not seem to be in conventional URI format. For example, `ipv6:::1:49178`. This is not parsed well by `System.Uri`, which cannot determine the host and port:
```
PS> new-object system.uri "ipv6:::1:49178"
AbsolutePath   : ::1:49178
AbsoluteUri    : ipv6:::1:49178
LocalPath      : ::1:49178
Authority      :
HostNameType   : Unknown
IsDefaultPort  : True
IsFile         : False
IsLoopback     : False
PathAndQuery   : ::1:49178
Segments       : {::1:49178}
IsUnc          : False
Host           :
Port           : -1
Query          :
Fragment       :
Scheme         : ipv6
OriginalString : ipv6:::1:49178
DnsSafeHost    :
IdnHost        :
IsAbsoluteUri  : True
UserEscaped    : False
UserInfo       :
```
This does not seem to meet the expectations given by the documentation.

The `Peer` string is built [here](https://github.com/grpc/grpc-dotnet/blob/1159126138d752f21c8a02b74002d83aec5f2c88/src/Grpc.AspNetCore.Server/Internal/HttpContextServerCallContext.cs#L87), which clearly seeks to provide the host address and port.

Is this a bug? If not, what is the intended means of parsing the `Peer` string so that the host and port can be accessed?

**Comment by JamesNK** [comment]
This value replicates what Grpc.Core returns for the Peer. @jtattermusch can you comment on the purpose of Peer and why it is formatted this way?

@tg73 You could get the underlying HttpContext and get information about the client from it.

**Comment by jtattermusch** [comment]
The underlying call in Grpc.Core is:
https://github.com/grpc/grpc/blob/057f2b6139769dc66ad32ac341546b1f223133b6/include/grpc/grpc.h#L270
The format is https://github.com/grpc/grpc/blob/master/doc/naming.md

@JamesNK  are you sure that Grpc.Core returns e.g. `ipv6:::1:49178` and not `ipv6:[::1]:49178` in case of ipv6 being used?

**Comment by JamesNK** [comment]
There is a bug in our IPv6 addresses. Will fix.
