### ISSUE TITLE
grpc-web middleware does not handle request when client hostname has tailing '/'

### ISSUE THREAD

**Issue by hanabi1224** [grpc/grpc-dotnet#790]
### What version of gRPC and what language are you using?
grpc-web as client and Grpc.AspNetCore.Web as server

### What operating system (Linux, Windows,...) and version?
win10

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
3.1.102

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

```javascript
const goodClient = new GreeterClient('http://localhost', null, null);
const badClient = new GreeterClient('http://localhost/', null, null);
```

### What did you expect to see?
both should be working fine

### What did you see instead?
request from badClient is not handled properly by grpc web middleware

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc-dotnet/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by JamesNK** [comment]
I tested `const badClient = new GreeterClient('http://localhost/', null, null);`. It that address is used then requests are sent with double forward slashes. On the server these don't match to a gRPC endpoint.

e.g. `http://localhost//service/method` fails. Needs to be `http://localhost/service/method`

Please raise this issue at https://github.com/grpc/grpc-web. That is where the JavaScript client logic is hosted.
