### ISSUE TITLE
How to benchmark performance changes

### ISSUE THREAD

**Issue by vaughanr** [grpc/grpc-dotnet#793]
Hi,

I've made a small change in my fork to use a local function to avoid an allocation in the GrpcChannel class. 

https://github.com/vaughanr/grpc-dotnet/commit/920978283f1409ebbd1c651c6cc5f1c515f74672

I think it would but would like to supply hard evidence in the same way that @JamesNK often does in his PRs eg: https://github.com/grpc/grpc-dotnet/pull/775

1. Would you be open to these sorts of PRs with evidence?

2. I assume I should use the Grpc.AspNetCore.Microbenchmarks project. Is there a run option that you always use?

**Comment by JamesNK** [comment]
The dictionary needs a func so one must be allocated at some point. The current code ensures the func is only allocated once, rather than one per call to `GetCachedGrpcMethodInfo`.

Measuring is definitely required whenever making changes for perf.

**Comment by vaughanr** [comment]
Yes I see that now, thank you for having a look. I saved an allocation on creating a channel but cost one every time it was used! If I attempt one again I will get some evidence before I ask the question.
