### ISSUE TITLE
Create grpc templates

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#8]
- [x] Identify what templates. Initial proposal: client, client/server, server
- [x] Decide on languages supported. C# only or add F#
- [x] Create new templates (in aspnet/templates?)
- [x] Decide on default proto file location
- [x] How are proto files referenced by client project (e.g. service reference?)

**Comment by RainingNight** [comment]
From C# interface and POCO class generate proto file?

**Comment by JunTaoLuo** [comment]
For the first preview we are looking to ship a server and client multi-project template which will reference the .proto file explicitly for c# only. F#, service reference and POCO class support will be tracked separately.
