### ISSUE TITLE
Improve functional test readability

### ISSUE THREAD

**Issue by JunTaoLuo** [grpc/grpc-dotnet#80]
Comment: https://github.com/grpc/grpc-dotnet/pull/79#discussion_r255013018.

This looks like a worthwhile suggestion but we'll need to add a bit of infrastructure to support.

**Comment by dhhoang** [comment]
I think this can be done by setting up a `TestServer` that maps grpc methods to lambda function as the arrange phase in the test method rather than having one static server. 
This is probably less efficient but that shouldn't matter too much?
Is this up-for-grabs? I'd like to send a PR.

**Comment by jtattermusch** [comment]
Looks like #105 has established a nice way to define the handlers used in testing directly in the test case method, but we haven't really converted the existing tests to use this approach.
(we have a bunch of "overloads" of SayHello defined here: https://github.com/grpc/grpc-dotnet/blob/2c2f93ac6773085466baef79e8f8dde0e8536c48/testassets/Proto/greet.proto#L24 and most of them seem to be only used once). Are we planning to do some test refactoring to make the tests more readable?
