### ISSUE TITLE
Feedback: Blazor Wasm/gRPC example: upgrading to v2.28.0.pre1 results in 'Bad gRPC response' client side.

### ISSUE THREAD

**Issue by JeepNL** [grpc/grpc-dotnet#805]
When I updated the Blazor WASM/gRPC example (https://github.com/grpc/grpc-dotnet/tree/master/examples/Blazor) with the v2.28.0.pre1 Nuget packages I'm getting client side errors in dev tools. Server side seems to work okay. No errors there.

I used the source code without any modification (_except launchSettings.json_) as a reference project. I'm running it on localhost with Kestrel. I'm using Microsoft Visual Studio Community 2019 Preview Version 16.5.0 Preview 5.0

When I downgrade the Nuget packages to the latest previous versions, everything works again.

![Annotation 2020-03-04 105024](https://user-images.githubusercontent.com/39458532/75867643-35494e00-5e07-11ea-8043-90699d246a8d.jpg)

Nuget packages for project (client & server)

![Annotation 2020-03-04 105253](https://user-images.githubusercontent.com/39458532/75868311-28792a00-5e08-11ea-8b7c-93bd73199dae.jpg)

_Client launchSettings.json_
```
{
  "profiles": {
    "Client": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "https://localhost;http://localhost"
    }
  }
}
```
_Server launchSettings.json_
```
{
  "profiles": {
    "Server": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "https://localhost:5001;http://localhost:5000"
    }
  }
}
```

**Comment by JamesNK** [comment]
Thanks for reporting this. I found what the problem was and have a fix.

Until it is fixed and released you can workaround this issue by specifying a version when you create `GrpcWebHandler`.

```cs
new GrpcWebHandler(GrpcWebMode.GrpcWebText, new Version(1, 1), new HttpClientHandler())
```

The actual version number doesn't matter, the browser ignores it, but it should fix your problem.

**Comment by JamesNK** [comment]
Will leave this open for a couple of days until a fixed version is available.

**Comment by JeepNL** [comment]
@JamesNK (FYI) After upgrading to v2.28.0.**pre2** I can use 
`new GrpcWebHandler(GrpcWebMode.GrpcWebText, new HttpClientHandler());`
again.
