### ISSUE TITLE
nuget package version

### ISSUE THREAD

**Issue by miseri** [grpc/grpc-dotnet#806]
I was just updating a gRPC client and noticed that the version number made a jump from 1.22.x to 2.23.x. Is there a specific reason for this? 

And if this is an error is there no way to fix it to keep it inline with the versioning of the rest of gRPC?

Personally I found it very confusing, especially in terms of establishing version compatibility with other gRPC based software written in other languages.

**Comment by JamesNK** [comment]
There was a breaking change forced on .NET gRPC implementations. Because of that the major version number was increased - https://github.com/grpc/grpc/pull/19059

**Comment by miseri** [comment]
Ah, that explains it. Thanks for the quick reply James.
