### ISSUE TITLE
Getting error while using Grpc.Net.Client.Web in Blazor with Mobile Bindings running on Android emulator

### ISSUE THREAD

**Issue by ogauthier** [grpc/grpc-dotnet#823]
### What version of gRPC and what language are you using?
Using package Grpc.Net.Client.Web version 2.28.0-pre2
C#

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
.Net Core SDK 3.1.102

### What did you do?
I'm trying to create a HelloWorld sample application with Blazor Mobile Bindings that communicates with gRPC server. I was able to create a console application that works with same gRPC server.

### What did you expect to see?
A proper Hello response

### What did you see instead?
A RpcException on the client:
Error starting gRPC call: An error occured while sending the request

On the server console, we see this error:
HTTP/2 over TLS was not negotiated on an HTTP/2-only endpoint

**Comment by jtattermusch** [comment]
This belongs under the grpc/grpc-dotnet repository.

**Comment by JamesNK** [comment]
Your problem is a mismatch between the server and the client over TLS.

Your server requires TLS (it is using HTTPS) but your client is sending a request without TLS (it is using HTTP).

**Comment by ogauthier** [comment]
I was getting a SSL trust exception, which was expected. But after ignoring certificates errors, I still get the HTTP/2 over TLS was not negotiated on an HTTP/2-only endpoint message on the server.
Is there something else I need to do on the client side?
I'm running the service on localhost with the dev certificate and Android doesn't accept self-signed certificates, so I need to bypass SSL trust errors.

**Comment by JamesNK** [comment]
Android might not support HTTP/2.

gRPC-Web doesn't require HTTP/2 so what you could do is make the Kestrel endpoint support Http1AndHttp2, and then specify HTTP/1.1 in the GrpcWebHandler constructor.

**Comment by ogauthier** [comment]
Ok I got it to work, the only thing that I was missing is the Http1AndHttp2 setting for my Kestrel enpoint.
Thank you!
