### ISSUE TITLE
Does Grpc.Net.Client support UWP?

### ISSUE THREAD

**Issue by manupstairs** [grpc/grpc-dotnet#828]
Hi, I saw Grpc.Net.Client depend on .NET Standard 2.1.
Does it mean Grpc.Net.Client will support UWP in future?

Currently, is there a way to use Grpc in UWP client?

Thanks.

**Comment by JamesNK** [comment]
If UWP supports netstandard2.1 and HttpClient on UWP supports HTTP/2 then it will work.

If HttpClient doesn't support HTTP/2 then you could still use gRPC-Web with Grpc.Net.Client.

**Comment by manupstairs** [comment]
Thanks for your reply. Very clear and quickly.
