### ISSUE TITLE
Grpc Server streaming with Callback

### ISSUE THREAD

**Issue by MhdAna** [grpc/grpc-dotnet#832]
I need to know if it is possible on Grpc Framework to have a callback action on the Server Side during streaming from Server --> Client,  which make me able to release resources.

Thanks for any Advice or Suggestion.

**Comment by JunTaoLuo** [comment]
Can you give a specific example? 

You should be able to handle the creation and release of resources in your service implementation. Lifecycle of services and resources resolved from DI will be created/released based on their specified lifecycle.

**Comment by JamesNK** [comment]
Your last issue you said you're using Grpc.Core? https://github.com/grpc/grpc-dotnet/issues/829#issuecomment-601376447

Is that still the case? Reminder that this repo is for grpc-dotnet, not Grpc.Core.

**Comment by JamesNK** [comment]
I see you've created the same issue in both repos - https://github.com/grpc/grpc/issues/22445

Please don't do this. We're different teams, and you're wasting time by making two teams look at your issue. I'm closing this one.

If you begin using grpc-dotnet then you should create issues here.

**Comment by MhdAna** [comment]
Please let the issue open here, because i do't get 
any response from the other team.

**Comment by MhdAna** [comment]
Kindly i think you have to ask me before you close the issue.

**Comment by JamesNK** [comment]
This is the wrong place for Grpc.Core issues. Some code is similar but they are completely different implementations. We move all Grpc.Core issues to the https://github.com/grpc/grpc repository.

You posted your issue less than a day ago. Don't expect immediate replies.

And please use the correct repo in future.

**Comment by MhdAna** [comment]
Thank you for your answer, but as you said sometimes it is not easy to choose the right repository.
I will do my best.
