### ISSUE TITLE
Omnisharp complains it can't find "Server" as a namespace or type

### ISSUE THREAD

**Issue by piperun** [grpc/grpc-dotnet#833]
I'm trying to setup the server part of grpc, but Omnisharp keeps on complaining that `Grpc.Core` does not contain a type/namespace called "Server", even though in the API the `Grpc.Core.Server` class does exist.

I've setup my own class that is inherited from the abstract class generated by vscode I've imported:
```
using Grpc.Core;
using GeneratedProtoNameSpace;
```
My csproj file looks as follows:
```
    <PackageReference Include="Google.Protobuf" Version="3.11.4" />
    <PackageReference Include="Grpc.Tools" Version="2.27.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    <Protobuf Include="Protos\ssh.proto" GrpcServices="Server" />
    </PackageReference>
```

I'm struggling to understand what the issue here might be.

**Comment by JunTaoLuo** [comment]
I think you're using the Grpc.Core package. This repo is for Grpc.AspNetCore.Server so please redirect your questions to https://github.com/grpc/grpc instead. 

Sidenote: it looks like your csproj isn't correct, the `Protobuf` element should be added under an `ItemGroup` and should not be a metadata under the `Grpc.Tools` package reference.

**Comment by piperun** [comment]
My apologizes, the csproj is just a snippet from the file, it's under a `<itemGroup>`.
