### ISSUE TITLE
Request compression

### ISSUE THREAD

**Issue by prj** [grpc/grpc-dotnet#836]
Hello,

After doing some reading, I am unable to figure out how to do request compression.
My use case is in some cases submitting very much compressable binaries over the wire, and I was wondering if there is a way to compress the request.

I found how to turn on compression for responses by setting the ResponseCompressionAlgorithm, but I would like to do the same on the client.
I searched through open issues, but it seemed to me like everything is more directed towards response compression.

Thank you.

**Comment by JamesNK** [comment]
I've created an example of request and response compression. Code is here: https://github.com/grpc/grpc-dotnet/pull/840

**Comment by prj** [comment]
Thank you. This is exactly what I was needed.
I must say though that passing a magic string constant into a field not really meant for it seems kinda hacky though.
Perhaps there could be a better way? This is currently done per-request, what about doing it per-channel and adding it to GrpcOptions as a configurable value?

**Comment by anurse** [comment]
The main reason for the magic string is that the gRPC c-core-based .NET client and the pure .NET client share the same API and the metadata dictionary is the only way to pass custom options like this through.

We've had discussions about looking at ways to improve this, but it's not been a high priority given the cost of changes to both public APIs.
