### ISSUE TITLE
GRPC Interceptor - error handling

### ISSUE THREAD

**Issue by thdotnet** [grpc/grpc-dotnet#843]
I'm trying to intercept and catch Exceptions before they get sent to clients.

I've created on Interceptor class, and intentionally raised an exception on my GRPC method. The problem is that the catch line is never reached. Is there any way to implement an interceptor to catch exceptions?

  ```
  public class GlobalGrpcExceptionHandler : Grpc.Core.Interceptors.Interceptor
    {
             public override Task<TResponse> UnaryServerHandler<TRequest, TResponse>(TRequest request, ServerCallContext context, UnaryServerMethod<TRequest, TResponse> continuation)
        {
            try
            {
                return base.UnaryServerHandler(request, context, continuation);
            }
            catch (Exception ex)
            {
                throw;
            }
            
        }

    }
```

**Comment by JamesNK** [comment]
A sample shows how to make an interceptor catch errors:

https://github.com/grpc/grpc-dotnet/blob/afc2b217619e9f96e3de3be2dfce650a9468939c/examples/Logger/Client/ClientLoggerInterceptor.cs#L28-L61

This is in the client, but the same concept applies for server methods.

**Comment by thdotnet** [comment]
Hi James,

yes I know it's possible and I've found samples for the client. My requirement is to do that in the server. I've tried using the same approach (with changes such as continuation), but I can't make it to work. Could you please provide a sample for it? I've noticed it's a common problem that many people is trying to achieve in the community .

**Comment by JamesNK** [comment]
Does the same concept not work with UnaryServerHandler?

**Comment by thdotnet** [comment]
not really, there's no equivalent to get the response and pass to the continuation delegate.

**Comment by JamesNK** [comment]
You need to await the continuation call to catch the exception on the server

https://github.com/grpc/grpc-dotnet/pull/847/files

**Comment by thdotnet** [comment]
Thank you James!
