### ISSUE TITLE
Vigor.sln example does not compile out of the box

### ISSUE THREAD

**Issue by endrton** [grpc/grpc-dotnet#844]
### What version of gRPC and what language are you using?
I fetched latest source from grpc-dotnet master branch.

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
I had to change the global.json to 3.1.200 as i don't have 3.1.100 installed but i don't think it matters in this case.

### What did you do?
I opened directly the Vigor solution (examples/Vigor/Vigor.sln) in VS2019 and compile.

### What did you expect to see?
I expected a successful build.

### What did you see instead?
Grpc.AspnetCore project failed with _NU1105 Unable to find project information for '...\Grpc.AspNetCore.Server.ClientFactory.csproj'_. 
Everything was fine after i've added Grpc.AspNetCore.Server.ClientFactory, Grpc.Net.ClientFactory and Grpc.Net.Client. So those should be part of the solution.
If you confirm, i can provide a pull request for this small issue.

### Anything else we should know about your project / environment?
No

**Comment by JamesNK** [comment]
Fixed. Thanks for the heads up!

**Comment by endrton** [comment]
That was quick. :)
Thanks for fixing!
