### ISSUE TITLE
C# gRPC client doesn't work with golang gRPC server for mTLS

### ISSUE THREAD

**Issue by pooneh-m** [grpc/grpc-dotnet#845]
### What version of gRPC and what language are you using?
Using Golang gRPC server and C# gRPC client.
Golang gRPC v1.20.0
C# gRPC 2.23

### What operating system (Linux, Windows,...) and version?
Linux 5.2.17-1rodete3-amd64

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200
 Commit:    c5123d973b

Runtime Environment:
 OS Name:     debian
 OS Version:  rodete
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   [REDACTED]/dotnet/sdk/3.1.200/

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.200 [[REDACTED]/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [[REDACTED]dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [[REDACTED]/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

### What did you do?
The details of the issue is documented in the [stackoverflow](https://stackoverflow.com/questions/60823164/grpc-client-in-c-sharp-does-not-work-with-grpc-server-in-go-with-mtls-support).

There is a gRPC service written in golang that works perfectly with gRPC client in golang. However, when using C# gRPC client, after mTLS handshake the client fails.

### What did you expect to see?
Success

### What did you see instead?
```
dbug: Grpc.Net.Client.Internal.GrpcCall[1]
      Starting gRPC call. Method type: 'Unary', URI: 'https://x.x.x.x/v1alpha1.AllocationService/PostAllocate'.
dbug: Grpc.Net.Client.Internal.GrpcCall[18]
      Sending message.
trce: Grpc.Net.Client.Internal.GrpcCall[21]
      Serialized 'V1Alpha1.AllocationRequest' to 9 byte message.
trce: Grpc.Net.Client.Internal.GrpcCall[19]
      Message sent.
fail: Grpc.Net.Client.Internal.GrpcCall[6]
      Error starting gRPC call.
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request)
dbug: Grpc.Net.Client.Internal.GrpcCall[8]
      gRPC call canceled.
fail: Grpc.Net.Client.Internal.GrpcCall[3]
      Call failed with gRPC error status. Status code: 'Internal', Message: 'Error starting gRPC call: An error occurred while sending the request.'.
dbug: Grpc.Net.Client.Internal.GrpcCall[4]
      Finished gRPC call.
gRPC error: Error starting gRPC call: An error occurred while sending the request.
```
And there is no server log on receiving the request.

**Comment by JamesNK** [comment]
I don't know what the cause of your problem is. The client is reporting the server is closing the connection. You would need to find out on the server side why it is doing that.

**Comment by pooneh-m** [comment]
On the server log there is nothing indicating the request was received. So the request gets dropped after the TLS handshake and before reaching the application level.

**Comment by JamesNK** [comment]
I don't know without extra information. That is happening inside the golang server, and I don't have knowledge of its implementation or what would cause that behavior.

**Comment by pooneh-m** [comment]
Thanks @JamesNK. Do you have suggestions on what extra info I should provide or how? Has there been any example of a gRPC golang **mTLS** server the works with C# gRPC client?

**Comment by JamesNK** [comment]
I haven't setup mutual TLS with golang but there is a sample of it working with ASP.NET Core here - https://github.com/grpc/grpc-dotnet/tree/master/examples#certifier

**Comment by pooneh-m** [comment]
Thanks. I've gone through those samples, but could not get mTLS working cross languages.

**Comment by anurse** [comment]
@pooneh-m Can you provide a runnable sample that reproduces the mTLS issues you're seeing? We're not seeing it in our tests, so we need clarity on exactly what you're doing and why it might be different from what we're testing.

**Comment by markmandel** [comment]
Come back around to this, just because we're getting some more users getting blocked by this.

If it helps at all, the Go gRPC server code is all hosted here:
https://github.com/googleforgames/agones/blob/master/cmd/allocator/main.go

The go client that works (I've also confirmed this), can also be found here:
https://github.com/googleforgames/agones/tree/master/examples/allocator-client

The go client and server are all using gRPC v1.20.1 as sstated earlier.

Does that help?

**Comment by Davidnovarro** [comment]
@anurse Here is the sample project that fails to call gRPC. The certificates and the endpoint is already set-up, all you need to do to reproduce the issue is to run the .cproj in visual studio.

The server and certificates are for testing, don't worry about privacy.

**Comment by pooneh-m** [comment]
I also added samples in https://github.com/pooneh-m/grpc-sample to repro server in go and client in C# to run locally. Without tls enabled, the request from client in C# to golang server succeeds, but with tls enabled, request fails with error:
```
~/go/src/grpc-sample/hellotls/client$ dotnet run
dbug: Grpc.Net.Client.Internal.GrpcCall[1]
      Starting gRPC call. Method type: 'Unary', URI: 'https://127.0.0.1:12342/sample.HelloWorldService/Test'.
fail: Grpc.Net.Client.Internal.GrpcCall[6]
      Error starting gRPC call.
System.Net.Http.HttpRequestException: Connection refused
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)
info: Grpc.Net.Client.Internal.GrpcCall[3]
      Call failed with gRPC error status. Status code: 'Internal', Message: 'Error starting gRPC call: Connection refused'.
dbug: Grpc.Net.Client.Internal.GrpcCall[4]
      Finished gRPC call.
gRPC error: Error starting gRPC call: Connection refused
dbug: Grpc.Net.Client.Internal.GrpcCall[8]
      gRPC call canceled.
Grpc.Core.RpcException: Status(StatusCode=Internal, Detail="Error starting gRPC call: Connection refused")
   at HelloWorldClient.Program.Main(String[] args) in /usr/local/google/home/pooneh/go/src/grpc-sample/hellotls/client/Program.cs:line 24
Press any key to exit...
```

**Comment by JamesNK** [comment]
@pooneh-m Your instructions are unclear to me. I ran the apps in hellotls\server and hellotls\client. hellotls\server is hosted on port 12341, and hellotls\client is calling port 12342. When I changed the client to call port 12341 then it appears to run successfully.

Client:
```
C:\Development\Temp\grpc-sample\hellotls\server [master ≡]> go run main.go
go: finding github.com/golang/protobuf v1.4.0
go: finding google.golang.org/grpc v1.29.1
go: finding google.golang.org/protobuf v1.21.0
go: finding github.com/golang/protobuf v1.4.0-rc.4.0.20200313231945-b860323f09d0
go: finding google.golang.org/protobuf v1.20.1-0.20200309200217-e05f789c0967
go: finding github.com/golang/protobuf v1.4.0-rc.2
go: finding google.golang.org/protobuf v0.0.0-20200228230310-ab0ca4ff8a60
go: finding github.com/golang/protobuf v1.4.0-rc.1.0.20200221234624-67d41d38c208
go: finding google.golang.org/protobuf v0.0.0-20200221191635-4d8936d0db64
go: finding github.com/golang/protobuf v1.4.0-rc.1
go: finding google.golang.org/protobuf v0.0.0-20200109180630-ec00e32a8dfd
go: downloading google.golang.org/grpc v1.29.1
go: downloading github.com/golang/protobuf v1.4.0
go: extracting github.com/golang/protobuf v1.4.0
go: extracting google.golang.org/grpc v1.29.1
go: downloading google.golang.org/protobuf v1.21.0
go: extracting google.golang.org/protobuf v1.21.0
2020/04/27 10:03:15 Received: random
```

Server:
```
C:\Development\Temp\grpc-sample\hellotls\client [master ≡ +0 ~2 -0 !]> dotnet run
dbug: Grpc.Net.Client.Internal.GrpcCall[1]
      Starting gRPC call. Method type: 'Unary', URI: 'https://127.0.0.1:12341/sample.HelloWorldService/Test'.
dbug: Grpc.Net.Client.Internal.GrpcCall[18]
      Sending message.
trce: Grpc.Net.Client.Internal.GrpcCall[21]
      Serialized 'Sample.TestRequest' to 8 byte message.
trce: Grpc.Net.Client.Internal.GrpcCall[19]
      Message sent.
trce: Grpc.Net.Client.Internal.GrpcCall[2]
      Response headers received.
dbug: Grpc.Net.Client.Internal.GrpcCall[13]
      Reading message.
trce: Grpc.Net.Client.Internal.GrpcCall[15]
      Deserializing 24 byte message to 'Sample.TestResponse'.
trce: Grpc.Net.Client.Internal.GrpcCall[16]
      Received message.
dbug: Grpc.Net.Client.Internal.GrpcCall[4]
      Finished gRPC call.
Got your query: random
Press any key to exit...
```

**Comment by JamesNK** [comment]
> @anurse Here is the sample project that fails to call gRPC. The certificates and the endpoint is already set-up, all you need to do to reproduce the issue is to run the .cproj in visual studio.
> 
> The server and certificates are for testing, don't worry about privacy.
> Take a look at AllocatorClient.zip
> [drive.google.com/open?id=1OTYti9bc6-wWDa6xzJnlgtne1-8tOK3L](https://drive.google.com/open?id=1OTYti9bc6-wWDa6xzJnlgtne1-8tOK3L)

I ran your app and couldn't get it to work with either Grpc.Core or Grpc.Net.Client.

Grpc.Core:
```
Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="failed to connect to all addresses")
```

Grpc.Net.Client:
```
fail: Grpc.Net.Client.Internal.GrpcCall[6]
      Error starting gRPC call.
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
```

**Comment by pooneh-m** [comment]
Sorry for my earlier error. I could get a sample working with mtls with golang server and C# client: https://github.com/pooneh-m/grpc-sample/tree/master/hellomtls
However it fails when the server is loading certificates dynamically as in the server example from @Davidnovarro:

```
GetConfigForClient: func(*tls.ClientHelloInfo) (*tls.Config, error) {
    return &tls.Config{
        Certificates: []tls.Certificate{tlsCer},
        ClientAuth:   tls.RequireAndVerifyClientCert,
        ClientCAs:    certPool,
    }, nil
},
```

**Comment by JamesNK** [comment]
It succeeds for me:

```
C:\Development\Temp\grpc-sample\hellomtls\server [master ≡]> go run main.go
2020/04/27 11:32:52 Received: mTLS random
```

```
C:\Development\Temp\grpc-sample\hellomtls\client [master ≡ +0 ~1 -0 !]> dotnet run
Got your query: mTLS random
Press any key to exit...
```

I see your client is Grpc.Core. Reminder to everyone here: this isn't the repo for Grpc.Core. That is here - https://github.com/grpc/grpc/tree/master/src/csharp.

grpc-dotnet is for Grpc.Net.Client.

**Comment by JamesNK** [comment]
Is there anymore feedback here? Can this be closed?

**Comment by pooneh-m** [comment]
Thanks for your help. We can close it. The root cause is when using GetConfigForClient in golang server, the requests from C# client fails. One solution in the golang server is to replace GetConfigForClient with VerifyPeerCertificate as explained in [stackoverflow](https://stackoverflow.com/questions/60823164/grpc-client-in-c-sharp-does-not-work-with-grpc-server-in-go-with-mtls-support).
