### ISSUE TITLE
Global error handling server side

### ISSUE THREAD

**Issue by AnthonyGiretti** [grpc/grpc-dotnet#848]
This is could be interesting? from a specific Exception type handling the right grpc status
No need to await the continuation Task, Exceptions are available before its completed

`namespace DemoGrpc.Web.Logging
{
    public class LoggerInterceptor : Interceptor
    {
        private readonly ILogger<LoggerInterceptor> _logger;

        public LoggerInterceptor(ILogger<LoggerInterceptor> logger)
        {
            _logger = logger;
        }

        public override Task<TResponse> UnaryServerHandler<TRequest, TResponse>(
            TRequest request,
            ServerCallContext context,
            UnaryServerMethod<TRequest, TResponse> continuation)
        {
            LogCall(context);
            try
            {
                var call = continuation(request, context);
                var exceptions = call.Exception;

                if (exceptions != null)
                {
                    var exception = exceptions.GetBaseException();
                    throw exception;
                }
                return call;
            }
            catch (SqlException e)
            {
                _logger.LogError(e, $"An SQL error occured when calling {context.Method}");
                Status status;

                if (e.Number == -2) // Sql Timeout
                {
                    status = new Status(StatusCode.DeadlineExceeded, "SQL timeout");
                }
                else
                {
                    status = new Status(StatusCode.Internal, "SQL error");
                }
                throw new RpcException(status);
            }
            catch (Exception e)
            {
                _logger.LogError(e, $"An error occured when calling {context.Method}");
                throw new RpcException(Status.DefaultCancelled, e.Message);
            }
            
        }

        private void LogCall(ServerCallContext context)
        {
            var httpContext = context.GetHttpContext();
            _logger.LogDebug($"Starting call. Request: {httpContext.Request.Path}");
        }
    }
}`

**Comment by JamesNK** [comment]
That doesn't work as soon as the unary method must wait on IO. The exception will always be null. Awaiting the task is required.

**Comment by JamesNK** [comment]
Put `await Task.Delay(1000)` in the unary method before throwing the error.

**Comment by AnthonyGiretti** [comment]
Good catch! Exception is null.

It was not the right way.

Thank you
