### ISSUE TITLE
Using appsettings.{environment}.json in Program.cs (Blazor gRPC example)

### ISSUE THREAD

**Issue by JeepNL** [grpc/grpc-dotnet#849]
I'm using Blazor WebAssembly 3.2.0 Preview 3

 - Blazor .gRPC example: https://github.com/grpc/grpc-dotnet/tree/master/examples/Blazor
 - Microsoft Docs page: https://docs.microsoft.com/en-us/aspnet/core/blazor/dependency-injection?view=aspnetcore-3.1#blazor-webassembly

I'm now using `#if DEBUG #else #endif` for the string variable "`backendUrl`". I'd like to load that setting from appsettings.{environment}.json. I can get that after `var host = builder.Build();` (_info from Microsoft Docs, see sample code below, and link here above_) but the gRPC service is called before that.

My question: is it possible or should I keep using `#if DEBUG` etc. 
(_I'd like to use appsettings whenever it is possible anywhere in my code._)

**Part of my Program.cs**
```
	string backendUrl = string.Empty;
#if DEBUG
	backendUrl = "https://localhost:5001"; // Local debug URL
#else
	backendUrl = "https://<example>.com:5001"; // Production URL
#endif
	builder.Services.AddSingleton(services =>
	{
		// Create a gRPC-Web channel pointing to the backend server.
		// GrpcWebText is used because server streaming requires it. If server streaming is not used in your app
		// then GrpcWeb is recommended because it produces smaller messages.
		var httpClient = new HttpClient(new GrpcWebHandler(GrpcWebMode.GrpcWebText, new HttpClientHandler()));
		var channel = GrpcChannel.ForAddress(backendUrl, new GrpcChannelOptions { HttpClient = httpClient });
		return channel;
	});

	// load settings from appsettings.{environment}.json
	// see: https://docs.microsoft.com/en-us/aspnet/core/blazor/dependency-injection?view=aspnetcore-3.1#add-services-to-an-app
	var host = builder.Build();

	var backendDomain = host.Configuration["Settings:BackEndDomain"];
	Console.WriteLine($"Backend Domain: {backendDomain}");

	await host.RunAsync();

	// original
	// await builder.Build().RunAsync();
```

**Comment by JamesNK** [comment]
I don't know. Your question is about how Blazor works, and I haven't used it much.

You should ask at https://github.com/dotnet/aspnetcore/issues

**Comment by JeepNL** [comment]
Oops. Again.
