### ISSUE TITLE
Reporting Failures in Application Insights

### ISSUE THREAD

**Issue by generatives** [grpc/grpc-dotnet#856]
When an exception is thrown in one of my GRPC services the request is always reported as successful in Application Insights. Neither PostgresExceptions from npgsql or RpcExceptions thrown by my own code cause the request to be reported as failed. I have seen that the GRPC standard is to always report a 200, does that interfere with Application Insight's detection of failed requests?

**Comment by generatives** [comment]
Note that Application Insights does report the Exception, it just doesn't report the request as failed.

**Comment by JamesNK** [comment]
gRPC always returns a 200 status code. App Insights will be using that status code to determine request success and failure. In gRPC a failure is reported in the grpc-status code header/trailer.

Recognizing a gRPC failure is a change that would need to happen in App Insights. You should create an issue with them.

**Comment by generatives** [comment]
Okay, thank you James
