### ISSUE TITLE
gRPC .Net Web Client additional Options Request without Auth Header

### ISSUE THREAD

**Issue by lolsharp** [grpc/grpc-dotnet#857]
### What version of gRPC and what language are you using?
C# both on Client (Blazor) and Server

Grpc.AspNetCore: 2.28.0-pre2
Grpc.Net.Client: 2.28.0-pre2
Google.Protobuf: 3.11.4

### What operating system (Linux, Windows,...) and version?
Windows 10 
Version	10.0.17763 Build 17763

Visual Studio 2019 Preview 
Version 16.6.0 Preview 2.1

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET Core SDK 3.1.300-preview-015048

### What did you do?
While playing around with the current Blazor webassembly version and the gRPC web client, i discovered a bug when using the gRPC on an extra server  with authorization.

I created a sample project based on the blazor webassembly template and the gRPC template.
https://github.com/lolsharp/gRPC-.Net-Web-Client-Bug

In the sample project only authentication is active, as soon as authorization is added, the options call fails since it doesn't contain the authentication header, and the whole gRPC call fails.

### What did you expect to see?
Either no options call or the required auth parameters on the options call.

### What did you see instead?
No auth paramaters on options call.

Options:
![noauth](https://user-images.githubusercontent.com/9304417/78782934-1e1bf400-79a3-11ea-9478-92b26ca884ad.jpg)

Post:
![auth](https://user-images.githubusercontent.com/9304417/78782952-25db9880-79a3-11ea-9d67-200bff7aafcf.jpg)

### Anything else we should know about your project / environment?
If the gRPC service and the blazor server host are the same, no additional options call is made.

**Comment by JamesNK** [comment]
I took a look at your sample I think the likely problem is the UseCors is after UseAuthentication/UseAuthorization. Move it before those in Startup.cs and see whether it works.

**Comment by lolsharp** [comment]
Thanks James, 
that was it. 
I wasn't able to correctly identify the source of the options call. 
CORS Preflighted Request should not contain credentials -> no Auth for it ether.
