### ISSUE TITLE
Document release process and inclusion in ASP.NET Core templates

### ISSUE THREAD

**Issue by anurse** [grpc/grpc-dotnet#858]
These came up during our triage, so I'm filing an issue to track the possible work here.

1. We should document the process to release gRPC packages (even if that just involves notifying some folks).
1. As part of that process, we should consider (for each release):
	* Whether to update the ASP.NET Core templates (and document how to do so)
	* Whether to update the version used by VS's Add Service Reference (and document how to do so)

cc @shirhatti @JamesNK @JunTaoLuo

**Comment by shirhatti** [comment]
3. Update API docs 😄
