### ISSUE TITLE
gRPC + CORS

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#86]
Is gRPC + CORS a thing in the real world? Do we need to test for it and support it?

Ideally we should be able to reuse existing ASP.NET Core CORS logic in routing and middleware.

**Comment by jtattermusch** [comment]
This is the first time I'm hearing about it in the context of gRPC, so I'm assuming we don't need it.

**Comment by davidfowl** [comment]
This would only matter for something like grpc-Web I would imagine...

**Comment by JamesNK** [comment]
Yeah

**Comment by plaisted** [comment]
Out of curiosity, has there been any planning regarding aspcore and gRPC-web? Seems like a middleware or similar could be added for gRPC-Web support.

**Comment by davidfowl** [comment]
Not yet, we're trying to get the basics working end to end first.

**Comment by JamesNK** [comment]
Closing because we don't support gRPC-Web. If that changes then this can be reopened/recreated
