### ISSUE TITLE
Is it possible to use GRPC with Normal c# Project ()

### ISSUE THREAD

**Issue by MhdAna** [grpc/grpc-dotnet#860]
I did some GRPC example only with using .NET Core Project, for some reason i could not use the GRPC with a normal (or we can say not .Net Core) c# Project.
Is it correct? or not?

Thanks in advanced

**Comment by chwarr** [comment]
If you're asking about running atop .NET Framework, see https://github.com/grpc/grpc-dotnet/issues/710

**Comment by MhdAna** [comment]
To get the GRPC running on .Net Framework then i have to use ASP.NET project for both side (Client/Server), because ASP.NET supports the protocol communication HTTP/2.
Please confirm it if it is correct.

**Comment by JamesNK** [comment]
No.

Use Grpc.Core - https://github.com/grpc/grpc-dotnet/issues/710#issuecomment-570318436
