### ISSUE TITLE
Is it possible to wait for requests to complete before shutting down the service?

### ISSUE THREAD

**Issue by danjonwilliams** [grpc/grpc-dotnet#861]
I have an ASP.Net core gRPC service that has a streaming method which is cancellable (so that if a client chooses to stop streaming the server side will stop writing to the stream). This uses the cancellation token on the ServerCallContext.

However, if a client is reading from the stream when the service is shut down (e.g. by pressing Ctrl+C in the console window when debugging in Visual Studio), the request is cancelled and the client receives an error. 

Once shutdown is triggered I would like to allow any requests that are being processed to complete, rather than cancelling them. Is that possible?

**Comment by JamesNK** [comment]
ASP.NET Core has IApplicationLifetime

https://www.thinktecture.com/en/asp-net/aspnet-core-in-production-graceful-shutdown-and-reacting-to-aborted-requests/

**Comment by JunTaoLuo** [comment]
@danjonwilliams this question seems to be answered so I'm closing the issue. Please let us know if you have additional concerns.
