### ISSUE TITLE
IServiceProvider/IServiceScopeFactory dependency injection in GRPC Interceptors

### ISSUE THREAD

**Issue by GoNextGroup** [grpc/grpc-dotnet#866]
Hello, guys.

I use Interceptors on Client's and Server's side which are needed to use IServiceScopeFactory for dependency resolving (for example, for Mapper resolving).
But currently there is no way to realize this without intermediate ServiceProvider building (via services.BuildServiceProvider()) or another container usage (like SimpleInject) for resolving this provider in the third-party container and pass it everywhere it needs.
Is it possible to avoid this "overhead" (because services.BuildServiceProvider() create an additional "copy" of DI container, and usage third-party container just for ISErviceProvider storage isn't a good code)?

Thank you.

**Comment by JamesNK** [comment]
Are you running into this problem on the client or the server? The implementations to create and run interceptors is different.

Currently the client factory doesn't support transient interceptors.

The server should support per-request and transient interceptors.

**Comment by anurse** [comment]
Closing as we haven't heard from you and close inactive issues after a short period. If you're able to get the information we requested, please comment and we can reactivate and continue investigating!

**Comment by Alex69rus** [comment]
I have the same issue.
I'm trying to get IServiceCollection inside grps server handler.
But this IServiceCollection has different scope from scope which was used for activating server handler itself.
IServiceCollection that I got has doesn't started scope I guess.
