### ISSUE TITLE
Greeter tutorial broken in Grpc.AspNetCore 2.28

### ISSUE THREAD

**Issue by niederee** [grpc/grpc-dotnet#868]
When following the [Microsoft Grpc Docs](https://docs.microsoft.com/en-us/aspnet/core/grpc/basics?view=aspnetcore-3.1).  

- Windows 10
- Visual Studio Professional 16.5.3
- .net core 3.1.201

 `Greeter.GreeterBase` is not generated.  Downgrading to Grpc.AspNetCore 2.27.0 allowed me to successfully follow the tutorial.

**Comment by JunTaoLuo** [comment]
I am able to use 2.28.0 and the sample seems to work for me. Can you share your project file so we can try to reproduce the issue?

**Comment by niederee** [comment]
When trying to create a clean project to share I was unable to repro.  Unfortunately can't share the project that produces issue.  Closed
