### ISSUE TITLE
I get an error when using GrpcChannel with a server that is not secure

### ISSUE THREAD

**Issue by aaron-dsouza** [grpc/grpc-dotnet#870]
### What version of gRPC and what language are you using?
"Grpc.Net.Client" Version="2.28.0"

### What operating system (Linux, Windows,...) and version?
Mac OS 10.15.4

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
.NET Core 3.1

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
All details with code snippets are captured here
[https://stackoverflow.com/questions/61208080/transport-failed-error-when-using-a-java-based-grpc-server-with-a-c-sharp-based]

### What did you expect to see?
No error at the server end

### What did you see instead?
INFO: Transport failed
io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception: HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 16030100b6010000b203035e95b0402c6320969d3d5fba04

**Comment by shirhatti** [comment]
There is additional configuration required when calling insecure (non-TLS) services with the .NET Core client. See https://docs.microsoft.com/aspnet/core/grpc/troubleshoot#call-insecure-grpc-services-with-net-core-client
