### ISSUE TITLE
Visual studio reports errors for generated classes based on .proto files

### ISSUE THREAD

**Issue by aaron-dsouza** [grpc/grpc-dotnet#875]
When I generated C# classes from .proto files errors are shown in the Visual Studio editor even though the code builds just fine.
For example I see this error highlighted in the editor
![image](https://user-images.githubusercontent.com/35029697/79893511-d0cb6800-8421-11ea-9256-bb274f1e727c.png)

My proto file has the service defined as so
service Simple {
    rpc GetData (Empty) returns (Data) {
    }
}

What settings must I set in Visual studio to avoid this error?

**Comment by JunTaoLuo** [comment]
The type is generated on build, so before you run build for the first time, the editor will not be able to resolve the type. Does the error go away after you run a build?

**Comment by aaron-dsouza** [comment]
No. The error doesn’t go away after doing a build   
  
  
  
  
Regards
  
Aaron   
  
  
  
  
  

  
  
>

**Comment by shirhatti** [comment]
Can you share a repro?
