### ISSUE TITLE
Import "google/api/annotations.proto" was not found or had errors

### ISSUE THREAD

**Issue by rabejens** [grpc/grpc-dotnet#879]
I followed the three steps [in your blog](http://james.newtonking.com/archive/2020/03/31/introducing-grpc-http-api) but I am getting above error.

What else do I have to do to make the dependencies available?

**Comment by JamesNK** [comment]
You need to have a copies of a copy of files in your project. I've updated the instructions: http://james.newtonking.com/archive/2020/03/31/introducing-grpc-http-api

**Comment by mfc19** [comment]
@JamesNK I followed the instructions and in my .Net project I still have build errors:

Error		Import "google/api/annotations.proto" was not found or had errors.

I have the google files in a google\api directory in my project

**Comment by dennisroche** [comment]
I found in VS 2019 Preview and in the gRPC HTTP API sample that I needed to include the google `*.proto` files into the project. 

```
    <Protobuf Include="..\Proto\google\api\*.proto">
      <Link>Protos\google\api\%(Filename)%(Extension)</Link>
    </Protobuf>
```

**Comment by Pao-lino** [comment]
@mfc19 I've have the same issue, did you find a solution ?

**Comment by sailingKieler** [comment]
Hi, I just wanna add my two cents in here, it might help others in future.

I'm new to building a gRPC client within an ASP.NET backend app (using `net8.0`), and I got the Protobuf definitions supplied by another party, requiring `google/api/annotations.proto` and others beyond the [Protobuf Well-known Types](https://protobuf.dev/reference/protobuf/google.protobuf/). Here's how I solved it:

* There's the NuGet package [Google.Api.CommonProtos](https://www.nuget.org/packages/Google.Api.CommonProtos) that contains `annotations.proto` and many more, and which I imported as follows. Note the setting of `GeneratePathProperty="true"`.
```xml
<PackageReference Include="Google.Api.CommonProtos" Version="2.15.0" GeneratePathProperty="true" />
<PackageReference Include="Google.Protobuf" Version="3.27.3" />
<PackageReference Include="Grpc.Tools" Version="2.65.0" PrivateAssets="All" />
```
* After `dotnet restore` you will find the `google/**/*.proto`s in `<userHome>/.nuget/packages/google.api.commonprotos/2.15.0/content/protos/`
* I then registered my proto files including an additional setting of `AdditionalImportDirs` like this
```xml
<Protobuf ProtoRoot="Proto" Include="Proto/**/*.proto" GrpcServices="Client" AdditionalImportDirs="$(PkgGoogle_Api_CommonProtos)/content/protos"/>
```
* run `dotnet build`

Et voilà! 🎉
