### ISSUE TITLE
Can't Invoke ASP.NET Core 3.1 gRpc in Docker

### ISSUE THREAD

**Issue by JarrodJ83** [grpc/grpc-dotnet#883]
I've followed every guide I can find on this with no success. I have created a grpc from the built in grpc template with Docker support enabled and cannot invoke the service successfully.

**Steps to Reproduce:**

1. Create new project in Visual Studio 2019 using "gRPC Service" template
2. Select "ASP.NET Core 3.1"
3. Check "Enable Docker Support" for Linux
4. Start Debugger using Docker

> Microsoft.Hosting.Lifetime: Information: Now listening on: http://[::]:80
> [40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
>       Now listening on: http://[::]:80
> [40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
>       Application started. Press Ctrl+C to shut down.
> [40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
>       Hosting environment: Development

![image](https://user-images.githubusercontent.com/248166/80229649-bdd1b700-861e-11ea-96ec-5b09df591b4e.png)

5. Try to invoke service using the following code:

```
var httpClientHandler = new HttpClientHandler();
httpClientHandler.ServerCertificateCustomValidationCallback =
	HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;;
var httpClient = new HttpClient(httpClientHandler);

Log.Logger = new LoggerConfiguration().WriteTo.Console().MinimumLevel.Verbose().CreateLogger();

var channel = GrpcChannel.ForAddress("https://localhost",
	new GrpcChannelOptions { 
	HttpClient = httpClient 
	,LoggerFactory= new Serilog.Extensions.Logging.SerilogLoggerFactory(Log.Logger)
	});

var greeter = new GrpcService1.Greeter.GreeterClient(channel);
greeter.SayHello(new HelloRequest {Name = "Test" });
```

**Expected Behavior:**
Successful invocation of gRpc service

**Actual Behavior:**
No connection could be made because the target machine actively refused it

I've also followed these guides with no success:
https://docs.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-3.1
https://docs.microsoft.com/en-us/aspnet/core/security/docker-compose-https?view=aspnetcore-3.1

If someone could please point me in the direction of what I am doing wrong it would be greatly appreciated. I've wasted a full day trying to get a trivial gRPC working in docker with no success.

**Comment by davidfowl** [comment]
When you running in docker you can't use localhost, that won't let you talk to the other container. I'm not even sure if VS creates containers in the same docker network by default (is there a docker compose file?). If you're not launching the client in a container then you need to access the server using localhost and the host port.

**Comment by JarrodJ83** [comment]
Clearly I have been staring at this stuff too long! I see I should have been using port 32786. Thanks for the quick reply and sorry for stupidity in my question!

**Comment by pathfinderanalysis** [comment]
Hi , Can you please share the sample. I am trying the same ,i am containerizing the grpc server service in docker and calling that service in local (asp.net core) using grpc client with AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true); i am getting some error.

**Comment by explorer855** [comment]
> 
> 
> Clearly I have been staring at this stuff too long! I see I should have been using port 32786. Thanks for the quick reply and sorry for stupidity in my question!

That's a random port. Is there a way to make it work for Docker?
