### ISSUE TITLE
How to check if server is running

### ISSUE THREAD

**Issue by mikart143** [grpc/grpc-dotnet#892]
Hello !
I would like to ask you how to check if server is running.
I can create GrpcChannel and then pass to client and then wait for some execption but is there any more elegant way ? Is Channel Conectivity implemented like in core ?

Regards Mikart

**Comment by JamesNK** [comment]
There isn't a way to do that at the moment. Issue tracking support here: https://github.com/grpc/grpc-dotnet/issues/874
