### ISSUE TITLE
Should a cancelled streaming call throw an RpcException or a System.IO.IOException?

### ISSUE THREAD

**Issue by orcnz** [grpc/grpc-dotnet#894]
I have been experimenting with the examples in this repository (commit 54add4f70f9154024573c1bb99c8450f5ee2a132). When running the Aggregator I notice that after the 3.5 second delay the client cancels the server streaming call and an `System.IO.IOException` is thrown. However, the example looks as though it is expecting the exception to be a `RpcException` with the status code of `Cancelled`.

Is this behaviour of throwing a `System.IO.IOException` on a cancelled call expected or a bug?

**Comment by JamesNK** [comment]
It is a bug. It was introduced in 2.28.0 and has already been fixed. I'm not sure what the cause is but I've added a test to prevent it being reintroduced.

Use an older version, or the [latest nightly](https://github.com/grpc/grpc-dotnet#grpc-nuget-feed).
