### ISSUE TITLE
Exception Handling with Additional DelegatedHandlers

### ISSUE THREAD

**Issue by moudis** [grpc/grpc-dotnet#895]
For context, I came across this issue while testing a Blazor WASM application with `Grpc.Net.Client.Web`.

While debugging issues integrating the current MSAL implementation, I came across an issue dealing with exception handling and the additional `DelegatedHandler` that I was adding to the HTTP request pipeline in my Blazor client. I eventually discovered that the `AuthorizationMessageHandler` I was adding was throwing an exception, but was being consumed and rethrown by the gRPC client as a `Grpc.Core.RpcException`, with the exception's Message set to "Error starting gRPC call. [other exception message]"

The relevant exception translation is happening in: https://github.com/grpc/grpc-dotnet/blob/54add4f70f9154024573c1bb99c8450f5ee2a132/src/Grpc.Net.Client/Internal/GrpcCall.cs#L575-L594

Judging from that function and its callers / callees, exceptions other than OperationCanceledException and RpcException have their Message and InnerExceptions turned into a single String message and put in a RpcException.

My questions: is this the expected behavior for the library when using it with multiple handlers in the HttpClient request chain? If not, would it be possible to keep exception information (source/type) from other handlers instead of losing that information along the way?

**Comment by JamesNK** [comment]
Yes this is expected. Issue about it here - https://github.com/grpc/grpc-dotnet/issues/798. Throwing the original exception wouldn't be consistent with what Grpc.Core does, and we're trying to maintain compatibility where possible.

The next version will include inner exception message in the RpcException message - https://github.com/grpc/grpc-dotnet/pull/804
