### ISSUE TITLE
Syntax support in VS and VS Code

### ISSUE THREAD

**Issue by JunTaoLuo** [grpc/grpc-dotnet#9]
Determine if we want to add official grammar and syntax support for VS and VS Code in addition to the third party extensions currently available.

**Comment by jtattermusch** [comment]
I assume you mean syntax support for `.proto` files?
It would be good to list the existing third-party extensions you had in mind here.
Also, I'm not sure if there are any grpc-specific features that would be useful or if .proto syntax support would be sufficient.

**Comment by JunTaoLuo** [comment]
Correct I'm referring to the .proto file syntax and grammar. Currently I'm using https://github.com/zxh0/vscode-proto3 for vscode and https://github.com/mreu/ProtobufLanguageService for full vs. They provide syntax support but I haven't seen any autocomplete or intellisense like capabilities.

**Comment by AlgorithmsAreCool** [comment]
Please don't forget about imported .proto files.

We break up our protos into multiple files and import them into a root file to keep things organized. But it makes it hard on the tooling which mostly assumes that all the messages are defined in a single file.

I can provide examples if this is confusing.

**Comment by JunTaoLuo** [comment]
VS is shipping support for proto grammar in VS 2019 Update 16.1.

**Comment by ndobryanskyy** [comment]
@JunTaoLuo, can you please explain here or point somewhere on how to enable intellisense support for `.proto` files in Visual Studio 2019? 

I am currently using `VS 2019 16.3.0 Preview 4.0` and the highlighting seems fine (except for `rpc` within services - no colors there), but no auto-completion pops up :(
