### ISSUE TITLE
Multitarget .Net standard 2

### ISSUE THREAD

**Issue by Pinox** [grpc/grpc-dotnet#905]
Hi Guys,

Any chance you can add a multitarget of .net standard version 2 on this project.

I think currently this is possible : 

var client = new HttpClient()
{
BaseAddress = new Uri("https://localhost:5001"),
DefaultRequestVersion = new Version(2, 0)
};

As you know UWP apps don't support .net standard 2.1 so adding support for  .net standard 2 will be of great help to use this in a cross platform solution. Currently can't upgrade my solution to gRPC because of UWP cross platform code. This is the only library preventing .net standard 2.0 gRPC to work.

protobuf-net.Grpc and Grpc.Core all supports .net standard 2.0

**Comment by JamesNK** [comment]
The client doesn't support UWP because netstandard2.0 doesn't have `HttpResponseMessage.ResponseTrailers`
