### ISSUE TITLE
.NET 5 breaking changes for Base64 reminder

### ISSUE THREAD

**Issue by gfoidl** [grpc/grpc-dotnet#908]
Regarding `System.Buffers.Text.Base64` there will be a breaking change in .NET 5 on the status `Done` vs. `NeedMoreData` introduced by https://github.com/dotnet/runtime/pull/281.

This issue is meant as a remainder to adapt to the change.
(Feel free to assign this issue to me.)

Places affected here:
https://github.com/grpc/grpc-dotnet/blob/5de614014db934edc8445050ccda645639d19ad8/src/Grpc.Net.Client.Web/Internal/Base64RequestStream.cs#L85-L87

Right now the relevant projects target .NET Standard 2.1.
So if consumed by a .NET 5 project it should crash?! while .NET Core 3.1 is fine.

---

Possible fixes:

* introduce a target for `net5.0`, so that conditional compilation can be used to take the proper state into account
* leave the target by `netstandard2.1`, and use the framework description to pick the correct value of status at runtime (in a static initialization)

I'd prefer the former option.

---

Other places to double check (not affected right now):
https://github.com/grpc/grpc-dotnet/blob/5de614014db934edc8445050ccda645639d19ad8/src/Grpc.Net.Client.Web/Internal/Base64ResponseStream.cs#L29
https://github.com/grpc/grpc-dotnet/blob/5de614014db934edc8445050ccda645639d19ad8/src/Grpc.AspNetCore.Web/Internal/Base64PipeReader.cs#L33
https://github.com/grpc/grpc-dotnet/blob/5de614014db934edc8445050ccda645639d19ad8/src/Grpc.AspNetCore.Web/Internal/Base64PipeWriter.cs#L31

**Comment by JamesNK** [comment]
Already fixed

**Comment by gfoidl** [comment]
Perfect 👍
