### ISSUE TITLE
HTTP/2 - SHA256RSA - Windows Server 2012

### ISSUE THREAD

**Issue by fischer-ti** [grpc/grpc-dotnet#910]
Hy there, I'm so happy today because I've started to deploy my application with Server AspNetcore +Client .NetCore (Worker)+ gRPC (watched tons of videos, etc.) and working for the past 2 months to migrate my application from .NetFrameWork (testing purposes only) with WCF to this point (A lot of testing, and improving from FrameWork to .Net Core, hoping to get some results  at any time).
Anyway, all going good, using the first app to install the brand new app with a lot of open source...
THEN =D

Crash at Windows 2012 with few messages from client, but:

Grpc.Core.RpcException: Status(StatusCode=Internal, Detail="Error starting gRPC call: An error occurred while sending the request.")   at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,
TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[T
Request,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterc
eptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorC
ontext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,
TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at MY METHOD =D

An a single msg at the server:
fail: Microsoft.AspNetCore.Server.Kestrel[0]
      HTTP/2 over TLS was not negotiated on an HTTP/2-only endpoint.

Dig a little here and there and found out that Windows Server 2012 won't work with some certs:
https://stackoverflow.com/questions/58188842/asp-net-core-3-0-app-not-working-on-windows-server-2012-r2-due-to-err-http2-inad

But not really an answer found!

Can anyone help me out? =D
Thanks a lot! GREAT DAY! Very excited about it all!

**Comment by JamesNK** [comment]
Documentation here: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1#http2-support

You either need to upgrade to a new version of Windows or use a supported certificate type that the documentation mentions.

**Comment by fischer-ti** [comment]
Thanks man! Reading that!
