### ISSUE TITLE
IAsyncStreamReader and MemoryStream

### ISSUE THREAD

**Issue by VasilSirakov** [grpc/grpc-dotnet#913]
I made a simple client-side streaming file upload RPC. Server-side I read the file chunk by chunk using the `IAsyncStreamReader`. What I need to do next is stream the file to an AWS S3 bucket, however, making the HTTP call to AWS requires supplying an instance of a `Stream`.

My question is if it is possible to somehow obtain a `MemoryStream` from the `IAsyncStreamReader`? 

My only idea was to iterate the `IAsyncEnumerable` and flush the byte chunks to a memory stream but then the problem is that I'd be reading the entire file in-memory before sending the actual request.

```  C#   
var request = new PutObjectRequest()
{
      Key = fileName,
      InputStream = new MemoryStream()
};
     
await foreach (var message in requestStream.ReadAllAsync())
{
      await request.InputStream.WriteAsync(message.Chunk.ToByteArray());
}

// Send request
await s3Client.PutObjectAsync(request);
```

I could completely be misunderstanding this so feel free to close if it is irrelevant.

**Comment by JamesNK** [comment]
I think to do what you want you will need to create your own `Stream` implementation that overrides ReadAsync and reads from the underlying `IAsyncStreamReader`.

Implementing your own stream will be complex, be should avoid the overhead of buffering the incoming object to memory.

**Comment by luigisaggese** [comment]
@VasilSirakov I have same use case, how did you solved at the end? I was thinking also to use UploadObjectFromStreamAsync method of s3Client that accept Stream. It will be helpful to hear your feedback

**Comment by VasilSirakov** [comment]
@luigisaggese If I remember correctly, in the end we just rewrote the file upload from gRPC to REST because it was much more performant and didn't have this issue.

If you insist on using gRPC for this, I would say the only option is to write your own custom class that inherits from `Stream`, and implement the function that reads a buffer of bytes from the stream to use the `IAsyncStreamReader` from your gRPC request.

This was 4 years ago, though, so I don't know if the APIs have changed much since then.

**Comment by luigisaggese** [comment]
> If you insist on using gRPC for this, I would say one option is to write your own custom class that inherits from `Stream`, and implement the function that reads a buffer of bytes from the stream to use the `IAsyncStreamReader` from your gRPC request.

@VasilSirakov yes this I am trying to do and to try to chunk messages as proposed [here](https://github.com/grpc/grpc-dotnet/blob/master/examples/Uploader/Client/Program.cs) from client side, and to read them from server side with custom class

```
public override async ValueTask < int > ReadAsync(Memory < byte > buffer, CancellationToken cancellationToken) {
  var bytesRead = 0;
  while (bytesRead < buffer.Length && _streamPosition < _streamLength) {
    if (_request == null || _requestPos == _request.File.Content.Length) {
      // Read the next request object
      if (!await _reader.MoveNext()) {
        throw new EndOfStreamException("Unexpected end of stream while reading artifact");
      }

      _request = _reader.Current;
      _requestPos = 0;
    } else {
      // Copy data from the current request object
      var numBytesToCopy = Math.Min(buffer.Length - bytesRead, _request.File.Content.Length - _requestPos);
      _request.File.Content.Span.Slice(_requestPos, numBytesToCopy).CopyTo(buffer.Slice(bytesRead, numBytesToCopy).Span);
      _requestPos += numBytesToCopy;
      bytesRead += numBytesToCopy;
      _streamPosition += numBytesToCopy;
    }
  }
  return bytesRead;
}
```
