### ISSUE TITLE
Client: server-streaming does not collect duplicated (fault+ctx) trailers during an RpcException

### ISSUE THREAD

**Issue by mgravell** [grpc/grpc-dotnet#915]
Scenario: the server (native in this case) deliberately faults with an `RpcException` including some trailers in the middle of a server-streaming operation, and that trailer has also been added to the server context, i.e.

``` c#
var faultTrailers = new Metadata();
faultTrailers.Add("sum", sum);
// **and** importantly
serverContext.ResponseTrailers.Add("sum", sum);
throw new RpcException(new Status(StatusCode.Internal, "oops"), faultTrailers);
```

## Expectation

as observed with the native Google client:

The client-side call `await streamReader.MoveNext(cancellationToken)` will surface an `RpcException` with the correct `StatusCode`, `Detail` and `Trailers` i.e. one of `"sum", sum`

## Actual

as observed with Grpc-Dotnet

The client-side call `await streamReader.MoveNext(cancellationToken)` surfaces an `RpcException` with the correct `StatusCode`, `Detail` - but:

- sometimes the `Trailers` collection is empty
- sometimes the `Trailers` collection has it *twice*, i.e. `"sum", "10,10"`

I haven't figured out the rules for when it is empty and when it is duplicated; when I run *just* the one test, it tends to be empty; when I run a bunch of tests it tends to be duplicated. Possibly a thread race condition.

## Repro

See the `ServerStreaming(true)` test case [here](https://github.com/protobuf-net/protobuf-net.Grpc/blob/master/tests/protobuf-net.Grpc.Test.Integration/StreamTests.cs) - comparing `NativeStreamTests` to `ManagedStreamTests`.

A good place to put a breakpoint is in [`Reshape.cs`](https://github.com/protobuf-net/protobuf-net.Grpc/blob/master/src/protobuf-net.Grpc/Internal/Reshape.cs), `ServerStreamingAsyncImpl`, on the line:

``` c#
metadata?.SetTrailers(fault);
```

(which is where the exception is surfaced)

Note that this is the exact same (native) server in both tests, so presumably this is a client bug.

Note: I have added `IsManagedClient` that changes the test's expectation to reflect what I am observing (so my tests acknowledge reality for now)

**Comment by JamesNK** [comment]
@mgravell 2.30.0 is on NuGet with this fix. You can update your package reference and remove any related hacks.
