### ISSUE TITLE
Use messages with dynamic objects

### ISSUE THREAD

**Issue by imaramos** [grpc/grpc-dotnet#917]
I wanted to pass some message through grpc with dynamic data, something like this:
```
public class Message
{
    // some other properties
   ...
   public object Payload { get; set; }
}
```
If I understood right (not sure), in protobuf it could be done with "Any", something like this:
```
import "google/protobuf/any.proto";

message Message {
   google.protobuf.Any payload = 1;
}
```

How can I pack/unpack some object to this "Any" type and vice-versa?
For some reason Protobuf c# documentation only shows examples with java and c++
https://developers.google.com/protocol-buffers/docs/reference/csharp/class/google/protobuf/well-known-types/any
As a workaround I could just pass some json in this payload, but then I would lose performance by performing two different serializations.
Thank you for the help.

**Comment by JamesNK** [comment]
Example of a service using any - https://github.com/grpc/grpc-dotnet/blob/19d081e820960c271b544d56cc02568fd2cc6641/testassets/FunctionalTestsWebsite/Services/AnyService.cs#L29

Example working with any on a client - https://github.com/grpc/grpc-dotnet/blob/9390e16e8d82c4e5685522d0c7cab1584b691c08/test/FunctionalTests/Server/UnaryMethodTests.cs#L490

**Comment by imaramos** [comment]
Hi @JamesNK thanks for your response.
I have realized that Any does not fit my case because it requires for the server to know the proto contract upfront (since it requires that the class implements IMessage)
I guess that with protobuf I cannot do this type of dynamic object deserialization.
Probably my best chance is to go with something like a string or "google/protobuf/struct.proto" holding some json payload.

**Comment by JamesNK** [comment]
Yes. Or just a string field with JSON. Or a bytes field if the dynamic payload is binary.

**Comment by imaramos** [comment]
Thanks for the help.

**Comment by sanjeloo** [comment]
> Yes. Or just a string field with JSON. Or a bytes field if the dynamic payload is binary.

I have the same issue that I want to try this out but I think this has serialize and deserialize overhead . 
is this can become the main issue for my business cause I have used it for caching, I need  to send and receive data as quick as possible

**Comment by JamesNK** [comment]
I don't know your system or your performance requirements. Measure and find out.

btw, there are now docs about how to work with unstructured data - https://docs.microsoft.com/en-us/aspnet/core/grpc/protobuf?view=aspnetcore-6.0#unstructured-and-conditional-messages
