### ISSUE TITLE
Kestrel Http1AndHttp2 without TLS

### ISSUE THREAD

**Issue by imaramos** [grpc/grpc-dotnet#919]
We want to add GRPC to our existing API, so we need to enable HTTP2 as well as maintaining our existing HTTP1.1 controllers.
Is it possible to use this kestrel option without TLS?
```
	"Kestrel": {
		"EndpointDefaults": {
			"Protocols": "Http1AndHttp2"
		}
	}
```
We don't need encryption since the publicly exposed communications are behind a reverse-proxy.
I would like to avoid to use different ports for Http1.1 and Http2.
Thank you.

**Comment by JamesNK** [comment]
TLS is required for [ALPN negotiation](https://en.wikipedia.org/wiki/Application-Layer_Protocol_Negotiation). Without TLS there is no negotiation and Kestrel defaults to HTTP/1.1.

**Comment by herman1vdb** [comment]
realted issue #802
