### ISSUE TITLE
Version scheme for Grpc.AspNetCore.Server

### ISSUE THREAD

**Issue by JunTaoLuo** [grpc/grpc-dotnet#92]
To capture our discussion on how to version the grpc-dotnet packages.

For the time being, we will be moving forward with something like 0.1.19. However, in the future we expect divergence due to breaking changes in either gRPC or ASP.NET libraries. A few of the considerations:

1. Reacting to breaking changes in gRPC (e.g. 2.x.x version of Grpc.Core.Api)
2. Reacting to breaking changes in ASP.NET Core (e.g. 4.0)
3. Follow semantic versioning with scheme of Major.Minor.Patch
4. Building for multiple versions of ASP.NET Core simultaneously. For example, currently we have 1.0/1.1, 2.1, 2.2 and 3.0 with various level of support. In the future there should be fewer versions under support but we expect to service at least two releases at the same time. How does support for Grpc package work? For example, if 2.0.0 is released will 1.x.x be out of support?
5. Allow for ease of ingestion by users. How to determine which version to use given version A of GRPC and version B of ASP.NET Core 

That being said, how are other language support versioned? I'm thinking thinking Java, Node, and Go implementations may have some of these similar concerns?

**Comment by JamesNK** [comment]
See https://github.com/grpc/grpc-dotnet/blob/master/doc/versioning.md
