### ISSUE TITLE
Detecting back pressure when streaming

### ISSUE THREAD

**Issue by JuliusSweetland** [grpc/grpc-dotnet#924]
Is it possible to detect back pressure on the streaming server or receiving client? I'm looking for a way of figuring out when the client is receiving messages more quickly than it can process so that I can apply conflation on the server stream automatically. I'm currently struggling to even understand how the server decides when it can send more data to the client - is there a shared buffer size which is updated as the client reads items during enumeration of responses in the client's code base, or does the server send messages without restriction?

I am imagining a way of monitoring the client's receive buffer and/or server's send buffer and detect growth which implies the client is falling behind.

Any info would be greatly received.

**Comment by BrennanConroy** [comment]
cc @JamesNK

**Comment by JamesNK** [comment]
There is no API that tells you back pressure is occurring. An indication that you have back pressure is reads and writes are not completed synchronously. They reason they aren't completed synchronously is because they're waiting on back pressure to be relieved. However there are other reasons why reads and writes are sync vs async.

**Comment by JuliusSweetland** [comment]
@JamesNK Possibly a noob question, but how can you detect whether reads/writes are sync or async? Thanks for the steer - appreciate your input.

**Comment by JamesNK** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.iscompleted?view=netcore-3.1

**Comment by JuliusSweetland** [comment]
@JamesNK Just to clarify, you don't mean whether the read/write operation is performed synchronously/asynchronously, but instead that I can check whether the Task completes at a point immediately/soon after the call, when Task.IsCompleted is tested, and from that determine if there is a delay which would indicate buffered reads/writes?

https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.system-iasyncresult-completedsynchronously?redirectedfrom=MSDN&view=netcore-3.1#System_Threading_Tasks_Task_System_IAsyncResult_CompletedSynchronously

Following your original suggestion on face value: Task.CompletedSynchronously looks like a good way to check what you suggested, but as far as I can see this is always false on a Task: https://github.com/microsoft/referencesource/blob/master/mscorlib/system/threading/Tasks/Task.cs#L1623

**Comment by JamesNK** [comment]
Anything that could be asynchronous returns a `Task`.

Use what I said: `IsCompleted`. Don't use `CompletedSynchronously`. It is out of date.

**Comment by JamesNK** [comment]
I think this has been answered. Closing.
