### ISSUE TITLE
Concurrent problems of grpc client？

### ISSUE THREAD

**Issue by 893949088** [grpc/grpc-dotnet#925]
GrpcService：(use gRPCService project templete)

![image](https://user-images.githubusercontent.com/4034377/82737671-48fcb480-9d65-11ea-8257-d3cc8b5767f8.png)

AspNetCore API:

![image](https://user-images.githubusercontent.com/4034377/82737874-7138e300-9d66-11ea-8740-602f80cb7a05.png)

![image](https://user-images.githubusercontent.com/4034377/82737698-6fbaeb00-9d65-11ea-89ba-a62f252b8556.png)

Jmeter Test :

![image](https://user-images.githubusercontent.com/4034377/82737831-4a7aac80-9d66-11ea-8a8e-d73bb3328740.png)

![image](https://user-images.githubusercontent.com/4034377/82737823-4058ae00-9d66-11ea-9cdf-8785cdcf3814.png)

ElasticAPM：

![image](https://user-images.githubusercontent.com/4034377/82737927-caa11200-9d66-11ea-876d-7caa26207dbe.png)

WHY？

**Comment by JamesNK** [comment]
You're making a lot of parallel requests? You might be running into the limit of 100 maximum concurrent streams on one connection in HTTP/2.

You can set this to a higher limit and see whether that makes a difference to your results - https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.http2limits.maxstreamsperconnection?view=aspnetcore-3.1#Microsoft_AspNetCore_Server_Kestrel_Core_Http2Limits_MaxStreamsPerConnection

**Comment by 893949088** [comment]
This seems to be a problem caused by a synchronous call.

**Comment by JamesNK** [comment]
I see.

Why are you using `SayHello` and not `SayHelloAsync`?

**Comment by 893949088** [comment]
I probably didn't notice that, why synchronization and asynchronous are so different.

**Comment by JamesNK** [comment]
It is documented here - https://docs.microsoft.com/en-us/aspnet/core/grpc/client?view=aspnetcore-3.1#unary-call

**Comment by 893949088** [comment]
ok, thx.
