### ISSUE TITLE
Is there a new workaround for streaming with Blazor wasm?

### ISSUE THREAD

**Issue by jeremy-sigma** [grpc/grpc-dotnet#928]
I recently updated to Blazor Webassembly 3.2 release and my grpc streams no longer work because the assembly file WebAssembly.Net.Http no longer exists. Is there a new workaround to replace the old one referenced below?

![image](https://user-images.githubusercontent.com/40273160/83185008-2bba4400-a0df-11ea-9937-45fe0734d84c.png)

I also noticed that in the ASP.NET blog release for preview 5 that they added this to enable streaming per request. My question is how would I enable streaming globally or per request with my grpc calls? 
Do I need to wrap my grpc messages into an HttpRequestMessage or something else?

![image](https://user-images.githubusercontent.com/40273160/83185478-e9ddcd80-a0df-11ea-8266-da9870be4d70.png)

Blazor Webassembly version - 3.2
Grpc.Net.Client 2.29.0
Grpc.Net.Client.Web 2.29.0

**Comment by JamesNK** [comment]
Streaming is already automatically enabled with 2.29.0.

https://github.com/grpc/grpc-dotnet/blob/1344beb663fe05abf53a6c71ea349d0c5f267bce/src/Grpc.Net.Client.Web/GrpcWebHandler.cs#L127

I just verified that it works again with the Blazor example - https://github.com/grpc/grpc-dotnet/tree/master/examples#blazor

Have you configured the handler to use GrpcWebMode.GrpcWebText?

**Comment by jeremy-sigma** [comment]
This is the channel that I am currently injecting right into my razor page to call my rpc's

     var httpClientHandler = new HttpClientHandler();
     var handler = new GrpcWebHandler(GrpcWebMode.GrpcWebText, httpClientHandler);
     var httpClient = new HttpClient(handler, false);
                
                
     var channel = GrpcChannel.ForAddress("https://" + IP + ":" + PORT, new GrpcChannelOptions
     {
          HttpClient = httpClient
      });

Maybe I am just looking on the wrong side of things. I am catching an exception on my grpc server side that says "Cannot write message after request is complete." So my assumption was the stream wasnt working properly. On the Server side I am using these dependencies.

![image](https://user-images.githubusercontent.com/40273160/83194712-ee10e780-a0ed-11ea-8a57-e97afd6756af.png)


And this is the call that results in the above error message
`await responseStream.WriteAsync(message);`

**Comment by JamesNK** [comment]
That isn't related. When `WebAssemblyEnableStreamingResponse` is not set (or you use `GrpcWebMode.GrpcWeb`), then no messages are received until the stream is complete.

Are you able to upload a reproduction of your issue?

**Comment by jeremy-sigma** [comment]
Its not necessary, I was able to figure out that the issue was being caused by something else after you let me know that I didnt need a workaround to enable streaming any long. Much appreciated.

**Comment by achmstein** [comment]
I'm facing the same issue. I cannot make stream works with blazor wasm. I'm using version 2.29.0 and configured handler to use GrpcWebText.

**Comment by achmstein** [comment]
I noticed that the stream not work if Fiddler is running
