### ISSUE TITLE
Example/Support For VB

### ISSUE THREAD

**Issue by paul1956** [grpc/grpc-dotnet#934]
### Is your feature request related to a problem? Please describe.
Trying to use gPRC from VB and I get error that generator is only supported by C# Project

### Describe the solution you'd like
I want to use gRPC from Visual Basic even of the Proto code needs to be generated in a separate C# project. I would be willing to update code generator to also product VB with some guidance.

### Describe alternatives you've considered
Create a C# project, put Proto folder there and link to it.

**Comment by JamesNK** [comment]
VB is not supported. Grpc.Tools only supports generating C#.

What you could try is have a separate project that is C#, and reference Grpc.Tools + proto files in it. VB projects can then reference the C# project.

**Comment by paul1956** [comment]
@JamesNK I figured that but an example would be fantastic.

**Comment by paul1956** [comment]
@JamesNK  I think this works following your idea, I will close.

**Comment by InteXX** [comment]
@JamesNK 

@paul1956 offered of his valuable time to build a VB.NET generator. Are you able to provide guidance for this?

**Comment by JamesNK** [comment]
What? He didn't do that.

**Comment by InteXX** [comment]
Maybe I've misunderstood:

`I would be willing to update code generator to also product VB with some guidance`

**Comment by paul1956** [comment]
@JamesNK I currently have a workaround that does what you suggested, splits the project then reference it from VB. In 2020 I did offer to create a VB Generator with guidance but have since then I mostly retired. If there is sufficient guidance and people are not in a hurry I would attempt it for VB.

**Comment by InteXX** [comment]
@JamesNK 

Perhaps a new branch could be created and some documentation published for the VB.NET community to assist? I'd like to give it a go myself, at least a little bit.

**Comment by JamesNK** [comment]
Oh, I see now the offer was in the original issue.

Adding VB would be very complicated. Generation is run by protoc, a C++ tool in the protobuf repository. It does the code gen for serializing protobuf types. Then there is addition code generation in the gRPC repo for the gRPC specific code. Then there is msbuild integration in the gRPC repo.

As well as this being difficult, I doubt the protobuf or gRPC projects would accept the changes. It is a lot more to maintain, and there is already a simple workaround which is just to have a csproj project, do code gen there, and then reference types from VB projects.

**Comment by InteXX** [comment]
I think that pretty well seals our fate.

**Comment by paul1956** [comment]
@InteXX I actually agree that the code generation is not needed. An example showing what needs to be done would be useful.

**Comment by InteXX** [comment]
@paul1956 

I imagine it'd be pretty much the same as referencing any project from a VB.NET project: add it, import the namespaces.

Am I misunderstanding you?

**Comment by paul1956** [comment]
@InteXX You need to know what to split up. I took me a while to get everything working and others should not have to go through that. An example would help everyone. The original issue had two alternatives, support VB OR provide example with Proto in separate project.

**Comment by InteXX** [comment]
I haven't looked at gRPC yet (planning to next week), so I'm having difficulty imagining what you're referring to.

Could a stripped-down version of your working project serve as a good community sample, submitted as a PR?

**Comment by paul1956** [comment]
@InteXX After getting gRPC to work I found out the data I needed was not available using that protocol. But my converter recognizes gRPC projects and will do all the work for you to create an example from a small C# sample. It does the split, creates the extra project and then converts all the C# code that uses gRPC to VB.

**Comment by InteXX** [comment]
@paul1956 

Ah. That's probably a little more complex than I'm going to get. I plan to just reference the C# project from my VB project. That's on the client side. Not sure what's involved on the server side.

I'll know more by the end of the week.

**Comment by InteXX** [comment]
p.s. We should probably stop hijacking this thread.

**Comment by peteringemann** [comment]
@paul1956 
Hi,
I am in the exact same position and I would very much like to see your example so I don't have to spend hours on this. As for now it seems like something the easily could be pain to figure out how to do. So if you have a working split-implementation using C# and VB.NET ready for download I would really like to have a look.

In general I am a but frustrated about closing the WCF door without offering an alternative. Which is basically what is happening to VB.NET users.

- peter

**Comment by InteXX** [comment]
@peteringemann 

Did you see [CoreWCF](https://github.com/CoreWCF/CoreWCF)? Would that help solve your dilemma?

**Comment by paul1956** [comment]
@peteringemann my converter converts the grpc by creating separate C# projects (client and server) with just the necessary parts left in C# and then that project is referenced by VB. I have stopped maintaining to converter except for thing that directly affect me or to respond to pull requests, as one retired person I can't keep up with all the changes to C# language, but it currently works for the vast majority of C# code out there.

**Comment by InteXX** [comment]
@paul1956 

Is this it? https://github.com/paul1956/grpc-dotnet

**Comment by paul1956** [comment]
No, I don't think I ever got that to work. It's part of CSharpToVB.

**Comment by InteXX** [comment]
Oh, OK.

I see you've got a ModVB/JSON project up there. I might have a look at that, as time allows (awfully stacked up these days).

I'm long lamenting the loss of Razor in VB.NET; I'm hoping ModVB will present us a path toward things like Blazor, etc.

**Comment by paul1956** [comment]
@InteXX My CareLink App does a lot more with JSON and has lots of functions to handle it then anything else. Also, some example of use WebView2.

**Comment by peteringemann** [comment]
Hi @InteXX - yeah! I've seen the CoreWCF. And I've also noted that the project is third party and it seems like it's made in protest :) (which is great) to help those left with WCF. Because of that I tried to migrate to gRPC but it seems to be an impossible thing to do. But maybe I should give it a try.

@paul1956, do you have a link to your converter that creates a minimized C# project to be referenced in the VB-solution? I would very much like to have a look at it.

**Comment by InteXX** [comment]
@peteringemann 

> maybe I should give it a try

FWIW it seems to be well-maintained.

**Comment by paul1956** [comment]
> Hi @InteXX - yeah! I've seen the CoreWCF. And I've also noted that the project is third party and it seems like it's made in protest :) (which is great) to help those left with WCF. Because of that I tried to migrate to gRPC but it seems to be an impossible thing to do. But maybe I should give it a try.
> 
> @paul1956, do you have a link to your converter that creates a minimized C# project to be referenced in the VB-solution? I would very much like to have a look at it.

@InteXX 
https://github.com/paul1956/CSharpToVB
