### ISSUE TITLE
TSI_PROTOCOL_FAILURE started happening on 01.06.2020 while certificate is still valid and has been working for more than a year

### ISSUE THREAD

**Issue by hypdeb** [grpc/grpc-dotnet#942]
### What version of gRPC and what language are you using?
gRPC.Core 2.29 in C#

### What operating system (Linux, Windows,...) and version?
Windows Server 2016 AND Windows 10 

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
both .NET Framework 4.7.2 and .NET Core 3.1

### What did you do?
Call a remote procedure on a gRPC server running in a docker container behind an nginx reverse proxy doing tls termination.
This has been working fine for more than a year, only started failing on the first of June this year for some unknown reason. Certificate is valid until next year.

### What did you expect to see?
I don't expect valid certificates (Chrome is perfectly happy with them) to not be valid according to gRPC.

### What did you see instead?
```
I0609 11:09:00.550686 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\tsi\ssl_transport_security.cc:222:      HANDSHAKE START -       TLS client start_connect  - !!!!!!
I0609 11:09:00.550851 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\tsi\ssl_transport_security.cc:222:                 LOOP -    TLS client enter_early_data  - !!!!!!
I0609 11:09:00.551203 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\tsi\ssl_transport_security.cc:222:                 LOOP -   TLS client read_server_hello  - !!!!!!
I0609 11:09:00.573569 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\tsi\ssl_transport_security.cc:222:                 LOOP - TLS client read_server_certifi  - !!!!!!
I0609 11:09:00.574256 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\tsi\ssl_transport_security.cc:222:                 LOOP - TLS client read_certificate_st  - !!!!!!
I0609 11:09:00.574483 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\tsi\ssl_transport_security.cc:222:                 LOOP - TLS client verify_server_certi  - !!!!!!
E0609 11:09:00.574937 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\tsi\ssl_transport_security.cc:1379: Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
D0609 11:09:00.575301 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\transport\security_handshaker.cc:184: Security handshake failed: {"created":"@1591693740.575000000","description":"Handshake failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\transport\security_handshaker.cc","file_line":307,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
I0609 11:09:00.575714 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\subchannel.cc:1003: Connect failed: {"created":"@1591693740.575000000","description":"Handshake failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\transport\security_handshaker.cc","file_line":307,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
```

### Anything else we should know about your project / environment?
Certificate is issued by COMODO CA and is valid until 22.01.2021. It is used by a variety of other applications that all verify it as valid.

**Comment by JamesNK** [comment]
Grpc.Core issues should be created at https://github.com/grpc/grpc/issues. Please recreate your issue there.

**Comment by hypdeb** [comment]
Actually, I figured it out in the meantime.
This was caused by: some intermediate certificate having expired and gRPC C# not using the OSs root store. A "solution" is to do this https://github.com/grpc/grpc/issues/8978#issuecomment-283469676.
I will rather try to go with configurable path to some root certificates file to make it OS independent.
