### ISSUE TITLE
make it easier to spawn multiple grpc server instances (i.e. kestrel)

### ISSUE THREAD

**Issue by schmitch** [grpc/grpc-dotnet#943]
### Is your feature request related to a problem? Please describe.
currently all our services follow the same design pattern:
- web api
- grpc api

we host both on a different port, i.e. we have a "front" channel that is web accessible and a "back" channel that is online available inside our network.
it's quite possible to build that, however it's not a breeze.
currently migrating from grpc-c servers to grpc-aspnet core reduces our application size by 75% so it's something we deeply look into.

### Describe the solution you'd like
register a service that spawns a full blown kestrel "back" channel server.

### Describe alternatives you've considered
better request pipeline branching features, however that would be tricky if hosted inside iis.

### Additional context
Grpc Native is really awesome!

btw. my idea would also make it possible to easier embed kestrel (inspired from playframework: https://www.playframework.com/documentation/2.8.x/ScalaEmbeddingPlayAkkaHttp)
it makes it really easy to have a small backend api on different ip's/ports that do not share the same authorization, etc.

**Comment by JamesNK** [comment]
> register a service that spawns a full blown kestrel "back" channel server.

I don't understand what you're asking. Please provide more information.

> better request pipeline branching features, however that would be tricky if hosted inside iis.

The middleware pipeline can be branched - https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.1#branch-the-middleware-pipeline

**Comment by schmitch** [comment]
@JamesNK here is some example:
https://github.com/schmitch/grpc-custom-kestrel

does not work yet, but I'm bringing it to work.

unfortunatly it would be better if multiple instances could be registered, but I think the DI limits that a little bit.

**Comment by JamesNK** [comment]
If you want multiple servers inside an app why not create two hosts?

This seems like such an esoteric feature that it is unlikely changes would be made to this gRPC library to support it.

**Comment by schmitch** [comment]
two hosts means, that any service that I called, need to be registered by the new host aswell, so I need to have double registration of multiple stuff.

I do not think that it is that esoteric, since it will allow a smoother transition between grpc-c and grpc-csharp. in grpc-c most people probably worked with `new Server` and did the same thing than we did. I'm pretty sure that people do not migrate because of that mismatch.

**Comment by davidfowl** [comment]
I think the goal is good but I don't think it makes sense to try and fork the API at this level to aid in migration. This grpc library was made to integrate deeply with the ASP.NET Core application model, if there needs to be an easier way to host ASP.NET Core then that seems unrelated to gRPC.

Shameless plug: 

https://github.com/featherhttp/framework

This may be interesting to you:

https://github.com/featherhttp/framework/blob/69b43bed727b74245f4061f5dbb8eaf384c475d7/samples/GRPC/Program.cs#L29

**Comment by JunTaoLuo** [comment]
We haven't heard back in 7 days. Closing the issue for now.

**Comment by schmitch** [comment]
@davidfowl your project looks cool, unfortunatly what I'm looking at, is have a single DI provider that can serve multiple http servers, so that Singleton's will only live once, etc.

sad that this might not come. I mean when looking at asp.net core alone, there is no need to spawn multiple http servers. however combined with grpc, there is a need for multiple servers.

**Comment by davidfowl** [comment]
I dunno why you think there’s a need for multiple severs, can you elaborate?

**Comment by schmitch** [comment]
frontend and backchannel.
i.e. using grpc-web and also have a second non public facing grpc-server for communication

**Comment by davidfowl** [comment]
You can host 2 endpoints on the same server and make the internal service be bound to the internal port only.
