### ISSUE TITLE
Continue server side processing after disconnect

### ISSUE THREAD

**Issue by Nvious1** [grpc/grpc-dotnet#944]
A hopefully quick question for you all.  
I have created a modified version of the Greeter example using the Server Streaming call in net-core 3.1.  In my code, the rpc call will execute a potentially long running process such as a server side executable.  I am trying to prepare for possible network disconnects. In just general testing so far when I close out the client (ctrl+c or just close window in windows),  while my server side process is running I see that the server side process just dies (gracefully at least) even though I am trying to deal with the server --> client stream disconnect with exception handling.  

Q) _Is this is the expected behavior or is it possible allow the client to disconnect and let the server side process complete?  I was thinking I could try the aggregator model to allow the server to call itself to avoid the issue as well._

Now I figured it would be difficult / impossible to have the client reattach to the original stream which is fine, so was going to build additional rpc calls to that the client could get status on process that it originally kicked off and just keep monitoring its status until it completes.

**Comment by Nvious1** [comment]
Ok, thanks.   After I commented out all of the return session streams messages, I confirmed I could close the client out and the server process would continue.  Thanks for the answer to the question.  Just a follow up but is there a way to detect the half-closed connection state on the connection context?

**Comment by JamesNK** [comment]
ServerCallContext.CancellationToken should tell you

**Comment by JunTaoLuo** [comment]
There hasn't been any responses, Please let us know if you have more updates.
