### ISSUE TITLE
How to use Cookies between multiple Clients with Dependency Injection?

### ISSUE THREAD

**Issue by catSIXe** [grpc/grpc-dotnet#950]
If i create a Channel and use multiple Clients on it, the Cookies (Auth) are shared
`using var channel = GrpcChannel.ForAddress($"https://{ o.Host }:{ o.Port }", channelOptions);
var nodeRegistryClient = new NodeRegistry.NodeRegistryClient(channel);
var fileRegistryClient = new FileRegistry.FileRegistryClient(channel);`
[Complete File](https://github.com/catSIXe/datahoarderfs/blob/730ca654ce272472b06f95e624c25074738674da/monolith/ManagedNode.cs#L30)

if i use Dependency Injection with an `ServiceCollection `and do `services.AddGrpcClient`, they dont share the Cookies amongst them. [Example](https://github.com/catSIXe/datahoarderfs/blob/master/monolith/ManagedNode.cs#L33)

How do i solve this issue? As it would be better to ues DependencyInjection but on the other Hand it prevents Cookie Auth Sharing

**Comment by JamesNK** [comment]
Separate HttpClient+channel instances are created for each client when using `AddGrpcClient`. You should create your clients manually with a shared channel.
