### ISSUE TITLE
gRPC with .net framework

### ISSUE THREAD

**Issue by rajcool1239** [grpc/grpc-dotnet#951]
While we want to move to .net core in the future, we would like to use grpc with .net framework. However this needs PEM file during service start, is there any workaround/solution that doesn't need PEM file? Also, why does gRPC with .Net core (using kestrel) not require the PEM file and why is PEM file only needed when using gRPC with .Net framework?

**grpc with .net framework** 

            SslServerCredentials sslServerCredentials = new SslServerCredentials(new List<KeyCertificatePair>() { new KeyCertificatePair(certificatePem, certificateKey) }, null, false); >>> need private key/PEM for this cert
            Grpc.Core.Server server = new Grpc.Core.Server
            {
                Services = { service.BindService(new Server()) },
                Ports = { new ServerPort(server.Host, server.Port, sslServerCredentials) }
            };
            server.Start();

**gRPC with .NET core using kestrel**
webBuilder.ConfigureKestrel(options =>
                    {
                        options.Listen(
                            IPAddress.Any,
                            configuredPort,
                            listenOptions =>
                            {
                                listenOptions.Protocols = HttpProtocols.Http2;
                                if (certificate != null)
                                {
                                    listenOptions.UseHttps(certificate); **>> this cert doesn't need to have private key**
                                }
                            });
                    })

**Comment by JamesNK** [comment]
Please ask Grpc.Core questions at https://github.com/grpc/grpc
