### ISSUE TITLE
Grpc Client with Asp.Net Core API

### ISSUE THREAD

**Issue by lijun727** [grpc/grpc-dotnet#952]
hi,
I'm afraid I've got a problem,
When I use ASP.NET  CORE API as the Grpc client, I cycle ten times, found that every time the average time for 2 s, and I use. NET CORE console as the client, the cycle of ten times, only the first time in a second, the back nine times the average time was 100 ms, using the same Grpc Service  (ASP.NET CORE API), I checked the Grpc Service log, and shows each access for an average of 70 ms, and my client code are all the same.I don't understand what's going on.Is ASP.NET CORE API not recommended as a Grpc client? Or is there something wrong with my code?

**Comment by lijun727** [comment]
the client code:
`

            AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);var startTime = DateTime.Now;
            var channel = GrpcChannel.ForAddress("http://localhost:9120");
            var client = new IUserGrpcService.IUserGrpcServiceClient(channel);
            var reply = await client.SayHelloAsync(new UserGrpc.HelloRequest { Name = "GrpcClient" });
            Console.WriteLine($"GrpcTime:{DateTime.Now - startTime}");
`

**Comment by JamesNK** [comment]
Our benchmarks are available here - https://aka.ms/aspnet/benchmarks. These compare the clients and servers of multiple implementations together:

* Grpc.Core
* gRPC for .NET Core
* gRPC for Go

Go to page 15.

**Comment by JunTaoLuo** [comment]
We haven't heard back in 7 days. Closing the issue for now.
