### ISSUE TITLE
How to run NET Core gRPC Server  in Docker?

### ISSUE THREAD

**Issue by win32nipuh** [grpc/grpc-dotnet#954]
I build in VS the cross-platform  NET Core +gRPC Server.
In Windows it works, then I have added the Dockerfile and build the Docker image.
Run the Server in Docker, and run gRPC.net client, receive:
```
PS D:\_Docker> docker run -it --rm -p 5000:80 -p 5001:443 --name cams02 myserver:latest
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:80
...
"Error starting gRPC call. HttpRequestException: The SSL connection could not be established, see inner exception. IOException: The handshake failed due to an unexpected packet format.

```

What are step by step instruction how to build a NET Core  gRPC Server and Docker image?
How to expose https enpoint?

**Comment by BrennanConroy** [comment]
This looks like an HTTP/HTTPS mismatch. Verify what ports the server is listening on and that you're exposing.

Show your full server startup logs and the URL you were using on the gRPC client.

**Comment by JunTaoLuo** [comment]
There hasn't been any response in 7 days, we're closing the issue for now.
