### ISSUE TITLE
Grpc client throws exceptions for non 200 statuses

### ISSUE THREAD

**Issue by Alex69rus** [grpc/grpc-dotnet#958]
### Is your feature request related to a problem? Please describe.
I'm always frustrated when I use non 200 status code in grpc responses. 
For example: I wrote method on server side
```csharp
public async Task<User> GetUser(GetUserByIdRequest request, ServerCallContext context)
{
    var user = await _userRepo.GetById(request.UserId);
    if (user == null)
        throw new RpcException(new Status(StatusCode.NotFound,"User not found"));
    return user;
}
```
Then on client side for handling StatusCode I have to write:
```csharp
try
{
    var user = _userGrpcClient.GetUser(new GetUserByIdRequest()
    {
        UserId = 1
    };
    // do smth
}
catch (RpcException ex) when (ex.StatusCode == StatusCode.NotFound)
{
    // handle 404 err
}
```
It is so terrible. Huge constructions, throwing and handling Exceptions decrease performance.
Why grpc client throws Exceptions for non 200 status codes?

### Describe the solution you'd like
Something like handling http responses.
Grpc call must return `GrpcResponse`, and no `Task<T>`.
There I'll can get StatusCode, Trailings or Result(maybe ResponseStream).
For example:
```csharp
public void Foo()
{
    var resp = _userGrpcClient.GetUser(new GetUserByIdRequest()
    {
        UserId = 1
    };
    if (resp.StatusCode == StatusCode.NotFound)
    {
        // handle 404 err
    }
    var user = resp.Result;
}
```

**Comment by JamesNK** [comment]
Expections for non-OK status codes are how our public API behaves and we don't plan to change that. A single exception has a tiny impact compared to the work involved in a gRPC request.

To get the solution you want, in your app you could create a helper method. It would catch StatusCode related exceptions and return that in a result with the status.

**Comment by Alex69rus** [comment]
But this approach has a great impact to quality and readability of code.
It's a pity.
Thanks for response.
