### ISSUE TITLE
DNS resolution failed / Failed to pick subchannel

### ISSUE THREAD

**Issue by ComptonAlvaro** [grpc/grpc-dotnet#959]
No matter if the service is running or not, when I run the client and try to send a request to the service, I get the error DNS resolution failed / failed to pick subchannel.

The code of the service is this:
```

            const int port = yyyy;
            var keypair = new KeyCertificatePair(_clientCertificate, _clientPrivateKey);
            var sslCreds = new SslCredentials(_caCertificate, keypair);

            var channel = new Channel("https://x.x.x.x", port, sslCreds);


            var client = new Gestor.GestorClient(channel);
            return client;
```

The complete error that I have is:
`{"Status(StatusCode=\"Unavailable\", Detail=\"DNS resolution failed\", DebugException=\"Grpc.Core.Internal.CoreErrorDetailException: {\"created\":\"@1592666370.497000000\",\"description\":\"Failed to pick subchannel\",\"file\":\"T:\\src\\github\\grpc\\workspace_csharp_ext_windows_x64\\src\\core\\ext\\filters\\client_channel\\client_channel.cc\",\"file_line\":3948,\"referenced_errors\":[{\"created\":\"@1592666370.497000000\",\"description\":\"Resolver transient failure\",\"file\":\"T:\\src\\github\\grpc\\workspace_csharp_ext_windows_x64\\src\\core\\ext\\filters\\client_channel\\resolving_lb_policy.cc\",\"file_line\":216,\"referenced_errors\":[{\"created\":\"@1592666370.497000000\",\"description\":\"DNS resolution failed\",\"file\":\"T:\\src\\github\\grpc\\workspace_csharp_ext_windows_x64\\src\\core\\ext\\filters\\client_channel\\resolver\\dns\\c_ares\\dns_resolver_ares.cc\",\"file_line\":375,\"grpc_status\":14,\"referenced_errors\":[{\"created\":\"@1592666370.497000000\",\"description\":\"C-ares status is not ARES_SUCCESS qtype=A name=https://x.x.x.x:yyyy is_balancer=0: Domain name not found\",\"file\":\"T:\\src\\github\\grpc\\workspace_csharp_ext_windows_x64\\src\\core\\ext\\filters\\client_channel\\resolver\\dns\\c_ares\\grpc_ares_wrapper.cc\",\"file_line\":287,\"referenced_errors\":[{\"created\":\"@1592666370.497000000\",\"description\":\"C-ares status is not ARES_SUCCESS qtype=AAAA name=https://x.x.x.x:yyyy is_balancer=0: Domain name not found\",\"file\":\"T:\\src\\github\\grpc\\workspace_csharp_ext_windows_x64\\src\\core\\ext\\filters\\client_channel\\resolver\\dns\\c_ares\\grpc_ares_wrapper.cc\",\"file_line\":287}]}]}]}]}\")"}`

This is with the new version 2.30.0. preview1. But I get the same error with the version 2.29.x, but I get more details in the preview version.

Thanks.

**Comment by JunTaoLuo** [comment]
This looks like an issue that should be transferred to https://github.com/grpc/grpc

**Comment by apolcyn** [comment]
> This looks like an issue that should be transferred to https://github.com/grpc/grpc

+1, please open this there, it looks like a potential issue in the DNS resolution code on windows specifically.

@ComptonAlvaro do you happen to see this log message: https://github.com/grpc/grpc/blob/9ec31c795ed695905cf4a11bc6ebe430103e6bf0/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L581

or this one: https://github.com/grpc/grpc/blob/9ec31c795ed695905cf4a11bc6ebe430103e6bf0/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc#L589

You <i>might</i> need to run under GRPC_VERBOSITY=DEBUG to be able to see those logs.
