### ISSUE TITLE
gRPC-Web service for .NET hosted in Azure as App Service does not support bi-directional streaming

### ISSUE THREAD

**Issue by ievdokdm** [grpc/grpc-dotnet#963]
Using Grpc.AspNetCore 2.29.0 and configured gRPC server as gRPC-Web and Grpc.Net.Client 2.29.0 on a client-side I am able to stream data back and forth using bi-directional streaming on localhost from client to server. 
But once server deployed on Azure App Service client only able to stream messages to the server but not receive messages from the server.
According to service logs, messages are sent from server to client.

**Comment by JamesNK** [comment]
I believe the Azure proxy doesn't support bi-directional streaming. Server streaming works, and client streaming probably works, but it doesn't support data being sent in both directions at the same time.

**Comment by ievdokdm** [comment]
Could this be added to official documentation? And are there any plans to add support of bi-directional streaming to App Service?

**Comment by JamesNK** [comment]
Sure. I think the best recommendation is to say to only use unary and server streaming calls with gRPC-Web.

gRPC-Web can very often use HTTP/1.1, and HTTP/1.1 servers don't consistently have support for bi-directional communication.

**Comment by JamesNK** [comment]
Docs updated - https://github.com/dotnet/AspNetCore.Docs/pull/19012
