### ISSUE TITLE
Blazor WASM & gRPC-Web: RpcException vs. AccessTokenNotAvailableException (want to provide full sample for community)

### ISSUE THREAD

**Issue by ChristianWeyer** [grpc/grpc-dotnet#965]
Hi all,

I am planning to provide a Blazor WASM with gRPC-Web sample, with JWT authentication.
For now, everything looks quite OK.

But...
In Blazor WASM, we are supposed to catch an `AccessTokenNotAvailableException` (see https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-3.1#attach-tokens-to-outgoing-requests) and then e.g. call `.Redirect` to get redirected to the IdP.
However, when using a gRPC/gRPC-Web channel in Blazor, we only get a `RpcException`, with no inner exception to act upon.

Is there anything I am missing here? :-)

Thanks!

**Comment by JamesNK** [comment]
I think the exception will be accessible on `Status.DebugException`. That is a new property in 2.30.0-pre1

See https://github.com/grpc/grpc-dotnet/pull/947

**Comment by ChristianWeyer** [comment]
Perfect, this works @JamesNK - thanks a lot.
