### ISSUE TITLE
Exception was thrown by handler.

### ISSUE THREAD

**Issue by jfalameda** [grpc/grpc-dotnet#968]
Hi,

I have implemented GRPC as described on the tutorials and I cannot get it to work. I get the following error:

`Exception was thrown by handler.`

I added an interceptor and I can see the call is received but the server, but it seems it is failing in the internal processing. I do not know what else to do or how to proceed to identify the error. Any tips?

Kind regards,
José.

**Comment by JamesNK** [comment]
The error will be logged. See instructions for setting up logging here - https://docs.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-3.1

**Comment by jfalameda** [comment]
Thanks
