### ISSUE TITLE
C# ValueTask based service API to reduce allocations

### ISSUE THREAD

**Issue by MaximGurschi** [grpc/grpc-dotnet#970]
Hello,

I am working on a grpc service in dot.net. It is built with high throughput in mind. I have attempted to remove all allocations from requests, and managed to do that for the most part.

The final allocations i have are:
1.Task
2.TaskCompletionSource
3.The async machinery instance
4.The response proto message

I was thinking that maybe i can get rid of the first 3 by using the ValueTask API backed by IValueTaskSource. However this would require the grpc service base class overrides to return ValueTask to properly avoid allocations.
Is there any initiatives to introduce ValueTask returning service methods? Perhaps i am not the first person to propose this.

As for the allocated proto message, i was thinking to reuse the instances as well, but for that i would require a callback to know that the request is written to the response. Is there a way to achieve such a notification, so that i can reuse the object for another request?

**Comment by JamesNK** [comment]
> Is there any initiatives to introduce ValueTask returning service methods? Perhaps i am not the first person to propose this.

Which specific Task, TaskCompletionSource, async machinery? If you're talking about the `Task` returned from unary methods, then there isn't a plan to update that. It comes from generated code. Any change like that needs to be made in Grpc.Tools in the grpc/grpc repo.

If async state is being allocated then at some point execution is awaiting a Task, and a Task and async state will get allocated regardless of whether you're using Task or ValueTask.

> As for the allocated proto message, i was thinking to reuse the instances as well, but for that i would require a callback to know that the request is written to the response. Is there a way to achieve such a notification, so that i can reuse the object for another request?

No there isn't. I think it is unlikely that sort of feature would ever be added to generated deserialization code.

**Comment by MaximGurschi** [comment]
@JamesNK 
Thank you for the speedy response.

Interestingly i posted on grpc/grpc repo initially. Then i discovered that there are 2 .net implementations (that and this repo) and closed that one and posted the same question here :)

My code allocates a TaskCompletionSource so that i can produce a Task for the Unary call. That ends up allocating the Task. The Task machinery gets allocated as i do an await inside my Unary method.

My Unary method is roughly this:

'
async Task<**AllocatedResult**> ServiceCall(Input) 
{
       var precondition = await Precondition();

       //1.2. Allocates TaskCompletionSource + Task.
       var tcs = new TaskCompletionSource<**AllocatedResult**>();

       //3.Allocates **AllocatedResult**.
       DoWork(tcs);

      //4.Allocates async machinery.
      return await tcs.Task.
}
'

Suppose the precondition makes use of ValueTask and amortized zero allocation through IValueTaskSource. It is my understanding that then i am left with the 4 allocations i mentioned above.

Please correct me if i am wrong, but if the Unary method prototype where to support async ValueTask<**AllocatedResult**>, AND if i were to no longer use TaskCompletionSource and have the ValueTask complete by using IValuerTaskSource (and pooling) then the only allocations would be for the **AllocatedResult** instance only?

If that is the case, then is it possible to rid off the final **AllocatedResult** by using a streaming server? I'm thinking using the IServerStreamWriter. The server can write the proto and then reuse it?
But then i read online that Unary endpoints are faster than streaming ones and generally recommended for small responses. Lets say my response is ~1KB. Would you expect the benefit of pooling the response proto by using a unary stream endpoint be outweighed by the stream overhead?

Thank you again, and i will post on the grpc/grpc repo again :)

**Comment by JamesNK** [comment]
If you want to cache and reuse `AllocatedResult` then there is nothing stopping you today. You could even cache a a completed `Task<AllocatedResult>` around it and use that if nothing awaits.

If you want to avoid the async state machine then you can test whether the task returned from DoWork is already complete, e.g. https://github.com/grpc/grpc-dotnet/blob/08a0a558c739d29cff3b209d67d75f8598bb8091/src/Grpc.AspNetCore.Server/Internal/CallHandlers/ServerCallHandlerBase.cs#L87-L118. If it is complete then you don't need async on a fast path.

These task allocations are very small and only happen once per-request. There are many per-request allocations made by the gRPC framework that you don't see.

**Comment by MaximGurschi** [comment]
My AllocatedResult wraps data that can be compared to an atomic counter. So 3 requests will get response counters 100, 101, 102 for example. AllocatedResult is a reference type generated from the protobuf DSL. How can i reuse this allocated AllocatedResult reference? It seems to me that is unsafe as there is a risk of returning the same counter 102 to all three requests?

It seems to me that the only way to reuse it is to know that the previous response was already written to the network.

Unfortunately the Work in DoWork will never be done immediately. That is an async IO operation.

I also appreciate that there might be other allocations going on, but i am trying to eliminate those coming from the code i wrote.
I will of course benchmark myself, but what do you think of the Unary stream idea? Here is what i was thinking:

'
async Task ServiceCall(Input, IServerStreamWriter<AllocatedResult> stream)
{
var result = PoolOfAllocatedResults.Rent();
try
{
    result.Counter = (int)Counter.Next();

   await stream.WriteAsync(result);
}
finally
{
    PoolOfAllocatedResults.Return(result);
}
'

This seems to achieve safe pooling of AllocatedResult, but i am wondering if this will be slower than the original Unary Unary method even if the amount of data written to the response stream is less than 1KB.

**Comment by JamesNK** [comment]
I doubt it will be any faster or slower. You're micro-optimizing things that are unlikely to have any impact.

Measure.

**Comment by MaximGurschi** [comment]
Thanks, yes how i've started on this path was observing my service RAM usage hovering at 1GB. After removing as many allocations as i could i reduced it to 400MB. The VS profiler was showing those 3 objects as the main allocations. I was trying to see if i can remove them.

**Comment by MaximGurschi** [comment]
For completeness, in the end to achieve the reuse of the allocated response objects, i made my grpc API return stream so that once i am done calling responseStream.WriteAsync i can then reuse the response object.

**Comment by MaximGurschi** [comment]
I can say that in my experience pooling objects greatly improved throughput and helped keep GC at zero for steady message processing.

I used Roslyn to generate additional partial classes for messages (based on the original C# messages) so that i can control 3 aspects:
1. Object allocation
2. Object Deep resetting
3. Object pool returning

Special casing of repeated fields is done. For string type i use a custom Utf8 message proto wrapping of repeated int32. The way repeated is reset is by calling RemoveAt (at the tail so that the internal array is not lost).

The pooling is applied to both input DTOs and any objects that i use internally.

**Comment by ziaulhasanhamim** [comment]
I agree with this idea. Because we don't about the RPC service nature(Will it be synchronous or asynchronous). That's the literal reason why the value task was created like a path can be sync or async without the allocation for sync path

**Comment by VAllens** [comment]
> I can say that in my experience pooling objects greatly improved throughput and helped keep GC at zero for steady message processing.
> 
> I used Roslyn to generate additional partial classes for messages (based on the original C# messages) so that i can control 3 aspects:
> 
> 1. Object allocation
> 2. Object Deep resetting
> 3. Object pool returning
> 
> Special casing of repeated fields is done. For string type i use a custom Utf8 message proto wrapping of repeated int32. The way repeated is reset is by calling RemoveAt (at the tail so that the internal array is not lost).
> 
> The pooling is applied to both input DTOs and any objects that i use internally.

`use a custom Utf8 message proto wrapping of repeated int32`
That's a really great idea, I'm also pooling grpc messages.
