### ISSUE TITLE
Dynamic gRPC service?

### ISSUE THREAD

**Issue by jonathanmarston** [grpc/grpc-dotnet#972]
I would like to build a proxy that allows clients to call an existing, proprietary, socket-based RPC interface via gRPC. The interface for these calls can change over time, which is currently handled by giving clients the ability to query for the metadata of the RPC method format. 

Is it possible to define a dynamic gRPC service with methods and structures defined at runtime, and a single handler that could translate the calls to the existing backend interface?

**Comment by JamesNK** [comment]
You can't dynamically accept gRPC calls for endpoints at runtime.

What you could do is have an endpoint that accepts an identifier of what you want to do, e.g. a method name arg, and then a string or bytes payload for message. You would use those args to invoke the backend interface.

**Comment by JamesNK** [comment]
Closing as answered
