### ISSUE TITLE
Keeping streams alive in grpc-web over http/1

### ISSUE THREAD

**Issue by giuliano-barberi-tf** [grpc/grpc-dotnet#976]
I'm wondering if it's necessary to implement an application level ping when doing a long lived stream that may have long periods of idleness. Under http/2 it seems that in .NET 5 kestrel will be able to do proper pings with its own timer but I'm wondering if it's using http/1 for grpc-web then does that mean we're potentially at the mercy of whatever the load balancer decides to do and it could close the connection on us?

**Comment by BrennanConroy** [comment]
> I'm wondering if it's necessary to implement an application level ping when doing a long lived stream that may have long periods of idleness

Yes, grpc-web doesn't have pings built into it so you would need to manage that yourself.

**Comment by JunTaoLuo** [comment]
There hasn't been any response in the past 7 days so we are closing this issue. Please reopen or open a new issue if you you would like to discuss further.
