### ISSUE TITLE
Sharing and reusing of protos in large projects next to impossible, help!

### ISSUE THREAD

**Issue by ChiefInnovator** [grpc/grpc-dotnet#988]
### Sharing and reusing of protos in large projects next to impossible, help!

We are in the midst of a large microservice implementation with gRPC.  We want to share common protos across several services.  Examples include address, GPS coordinates, phone number, version, person, and more.  Basically any data that can be common across a service we do not want to be redefined in the service.

For example, say we had an Address proto and did not define an addressline3 field.  We do not want to go to every service project and have to add addressline3 to that proto.

So we came up with three approaches to share protos.  Unfortunately, none solves the problem completely.  Translation, they do not solve the problem.

**Option 1 - Have a library protos project where all our protos live.**
We stick the protos in a shared library and use NuGet package Kungfu to copy the protos into the consuming project.  This worked great for sharing the packages, but failed to deliver due to assembly conflicts.

Service A and Service B consume the protos. Our clients for these services are defined in separate assemblies.  The challenge is that a consuming application may using clients from both Service A and Service B.  In that case, .NET does not know which types to use and blows up at us.

This also had the following complexity:
- Oversharing of protos that are not needed in Service B, but needed in Service A, and vice-versa.
- Cannot distinguish between protos from private services (i.e. backend) and public services (public APIs).
- Client and service projects would get all protos and you would have to go through each one and select whether they would be compiled and whether you wanted Client, Server, or Both classes generated.

**Option 2 - We share our protos using GitHub Submodules**
This is really no different that Option #1, just a different mechanism for sharing the protos.  It has all the same challenges as well as the added complexity of doing this in source control.

Developer - "Architect! Architect! It hurts when I do this!
Architect - "Don't do it"

**Option 3 - Define a common protos in shared NuGet library, define service specific protos in services**
The idea is that we would have a shared assembly just for our common types. The thinking is that we would have a shared NuGet package which had our compiled common protos. Then we would have services define those types specific to their services.  We got this idea from how the gRPC tooling sharing the Google Wellknown Protos. Unfortunately this is a challenge too. In our attempts, the service protos need access to the common proto files, not just the compiled protos.

### Summary
We are going to try a fourth option which is a common repo with multiple projects to mirror all our services and clients.

**Protos Repo**
protos\common\address.proto
protos\common\person.proto
protos\product\productspecific.proto
protos\serviceA\serviceAspecific.proto
protos\serviceB\serviceBspecific.proto
CommonProtos\CommonProtos.csproj <= Publish to internal NuGet repository
BaseServiceAClient\BaseServiceAClient.csproj <= Publish to internal NuGet repository
BaseServiceAService\BaseServiceAService.csproj <= Publish to internal NuGet repository
BaseServiceBClient\BaseServiceBClient.csproj <= Publish to internal NuGet repository
BaseServiceBService\BaseServiceBService.csproj <= Publish to internal NuGet repository

NOTE: Yes we know that we can collapse client and service and use both. In practice, we never do this because we have taken a rule that we never share anything server-side with the client unless we have to do so.

Service A = Internal backend service
Service B = Public service

**ServiceA Repo**
ServiceAClient\ServiceAClient.csproject <- References CommonProto and BaseServiceAClient
ServiceAService\ServiceAService.csproject <- References CommonProto and BaseServiceAService
Publish ServiceAClient to our internal NuGet repository

**ServiceB Repo**
ServiceBClient\ServiceBClient.csproject <- References CommonProto and BaseServiceBClient
ServiceBService\ServiceBService.csproject <- References CommonProto and BaseServiceBService
Publish ServiceBClient to public NuGet repository

This should fix our internal sharing issue.  We still don't know how to solve publishing our protos so that customers and partners can consume those protos for our public services.

**Comment by JohnGalt1717** [comment]
We have this same issue. Even if you use a shared directory it generates the same thing over and over again instead of truly sharing it.

I wish the team would consider code first gRPC using DTOs that are annotated along with annotations on services and would generate the protos for clients automatically from the URL structure.  This would massively simplify the structure. I know there is a private project for this, but we'd feel a lot better if it was integrated into the full solution.

And as a fringe benefit this would allow really great integration of REST with the grpc clients as well.

**Comment by JamesNK** [comment]
We're not going to support code first in grpc-dotnet, but making code first successful via https://protobuf-net.github.io/protobuf-net.Grpc is a goal. Changes were made to grpc-dotnet specifically to make protobuf-net.Grpc integrate well.

**Comment by JamesNK** [comment]
> NOTE: Yes we know that we can collapse client and service and use both. In practice, we never do this because we have taken a rule that we never share anything server-side with the client unless we have to do so.

The service base class and clients are very lightweight. Separating them into different assemblies doesn't add any value, but it is up to you if you want the extra complexity.

> This should fix our internal sharing issue. We still don't know how to solve publishing our protos so that customers and partners can consume those protos for our public services.

Complex proto sharing scenarios like you are talking about isn't something I have much experience with. I'm going to play around with it, and see whether I can create an example.

**Comment by JamesNK** [comment]
@ChiefInnovator Example https://github.com/grpc/grpc-dotnet/pull/992

> Unfortunately this is a challenge too. In our attempts, the service protos need access to the common proto files, not just the compiled protos.

I think you were on the right track with option 3, what you need to change to get it working is to not reference the common proto files with `<Protobuf>`.

The compiler still needs to access to common proto files when generating the service (this is via `import common.proto` in the proto files), but you don't want the common types generated with `<Protobuf  Include="common.proto" />`.
