### ISSUE TITLE
Unit testing that a client can be built

### ISSUE THREAD

**Issue by christopheblin** [grpc/grpc-dotnet#991]
In my project, there are classes with ServiceContract attribute as well as classes with DataContract+DataMember.

We are exposing these classes both with gRPC and with HTTP, everything is fine and everyone is happy. 

The problem we have is that, sometimes, there are only HTTP clients (and no gRPC client).
And so, in the impl, we sometimes forget "details" like the fact that you can not have more than one parameter in the method.
However, at some point, there is someone that wants to use the gRPC endpoint and he takes a really harsh error.

Is there a way to test that the gRPC definitions are correct upfront ?

At the moment, we have tried :

        [Fact]
        public void TestContracts()
        {
            var f = new CodeFirstGrpcClientFactory(new HttpClient());
            f.BuildClient<IMyService>("https", "dummy", 80);            
        }

However, this is working even if we miss the ServiceContract or a DataMember attribute...

Is there a way to be more proactive here ?

**Comment by JamesNK** [comment]
Because you're using a code first client you should ask here - https://github.com/protobuf-net/protobuf-net.Grpc
