### ISSUE TITLE
Singleton Grpc channel or create it per request?

### ISSUE THREAD

**Issue by MasiumDev** [grpc/grpc-dotnet#994]
in 1000 concurrent request:
When I use one Grpc channel for all requests, it seems I get high latency for most requests up to 1.5 sec.
But, when I create a Grpc channel per request, this latency decrease to 150 ms.

what's the reason?

**Comment by JunTaoLuo** [comment]
The likely reason is that you are running into the maximum streams per connection limit: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.http2limits.maxstreamsperconnection?view=aspnetcore-3.1#Microsoft_AspNetCore_Server_Kestrel_Core_Http2Limits_MaxStreamsPerConnection.

You can either set the limit higher or create additional channels (i.e. connections).

**Comment by JamesNK** [comment]
Don't create a channel per request. There is a lot of overhead when creating a channel so you want to reuse them.

I recommend you create an array of 10 channels, and then pick one at random for each request to spread requests across them. In .NET 5 this situation will be improved. A channel will automatically create more requests for you.

**Comment by JunTaoLuo** [comment]
Given that the root question has been answered, we're closing this issue.
