### ISSUE TITLE
The sample "Browser" application works fine on the local dev machine but the client fails to communicate when it's promoted to Azure after promoting

### ISSUE THREAD

**Issue by Arash-Sabet** [grpc/grpc-dotnet#995]
@JamesNK The question posted in this ticket may be related to [this closed issue](https://github.com/grpc/grpc-dotnet/issues/759). 

Could you please share your Azure Configuration of the sample ["Browser" server app](https://github.com/grpc/grpc-dotnet/tree/master/examples#browser)? 

The "Browser" app runs successfully on the local machine and the client receives reply fine but the client fails to communicate with the hosted Browser app on Azure. I had the Browser server app deployed to Azure and without making any changes in its code nor the configuration. Also, I did not add any CORS policies to the deployed code. The only difference is that I used my own proto file in both server and client which should not impact the overall outcome.

The client's error messages read as below:

> dbug: Grpc.Net.Client.Internal.GrpcCall[18]
>       Sending message.
> fail: Grpc.Net.Client.Internal.GrpcCall[6]
>       Error starting gRPC call.
> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
>  ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
>  ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
>    --- End of inner exception stack trace ---
>    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
>    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
>    at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
>    at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
>    at System.Net.Http.HttpConnection.FillAsync()
>    at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
>    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
>    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at Grpc.Net.Client.Web.GrpcWebHandler.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
>    at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)
> info: Grpc.Net.Client.Internal.GrpcCall[3]
>       Call failed with gRPC error status. Status code: 'Cancelled', Message: ''.
> dbug: Grpc.Net.Client.Internal.GrpcCall[4]
>       Finished gRPC call.

The following packages are used in the C# client application:

```xml
  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.12.3" />
    <PackageReference Include="Grpc.Net.Client" Version="2.30.0" />
    <PackageReference Include="Grpc.Net.Client.Web" Version="2.30.0" />
    <PackageReference Include="Grpc.Tools" Version="2.30.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
```

The following code snippet exhibits how the communication happens with the server which works fine with localhost:

```csharp
public static async Task SendSomethingAsync(string payload, ILoggerFactory loggerFactory)
        {
            const string url = "https://MASKED.azurewebsites.net/";
            //const string url = "https://localhost:44308";
            AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
            var handler = new GrpcWebHandler(GrpcWebMode.GrpcWebText, new HttpClientHandler());
            using var channel = GrpcChannel.ForAddress(url, new GrpcChannelOptions
            {
                HttpClient = new HttpClient(handler),
                LoggerFactory = loggerFactory
            });

            var client = new TestgRPC.gRPC.PayloadSubmission.PayloadSubmissionClient(channel);
            var submitted = await client.SubmitAsync(new SubmissionRequest
            {
                ClientKey = "678",
                ConnectionId = "abcdef",
                UserId = "3",
                MyObjectPayload= payload,
            });

            Console.WriteLine($"Submitted: {submitted}");
        }
```

**Comment by Arash-Sabet** [comment]
Just wondering @Will-Blackburn and @AnthonyGiretti , what could be missing from a gRpc-web configuration that I cannot make mine work on Azure app services? I saw your names on ticket #759 and thought to reach out to you for further inputs should there are any.

**Comment by AnthonyGiretti** [comment]
Hi, check my blog article and see if you missed something. I had pain with Linux App Service. 
https://anthonygiretti.com/2020/03/29/grpc-asp-net-core-3-1-whats-grpc-web-how-to-create-a-grpc-web-service/

If it doesn't solve your issue you can send me an email and we will see 

Good luck :)

**Comment by Arash-Sabet** [comment]
Thanks @AnthonyGiretti , In fact I followed your blog too yesterday but no luck. Is there a configuration tweak required to be done on Azure app service (Windows) that I may be missing?!

**Comment by Arash-Sabet** [comment]
The issue is that we needed to deploy the application as a self-contained application. Apparently the default .net core 3.1 installed on Azure app services cannot accommodate a gRPC-web app.
