### ISSUE TITLE
"No 'Access-Control-Allow-Origin'" call from custom domain with Blazor.NET WASM

### ISSUE THREAD

**Issue by bidipeppercrap** [grpc/grpc-dotnet#998]
### What version of gRPC and what language are you using?
gRPC v3
C#

### What operating system (Linux, Windows,...) and version?
Linux Ubuntu 18.04 LTS Server hosted on Azure VM

### What runtime / compiler are you using
Compiler on Local Machine: .NET Core SDK 3.1.302
Runtime on Server: AspNetCore 3.1.6

##### Blazor.NET WASM
Google.Protobuf v3.12.3
Grpc.Net.Client.Web v2.30.0
Grpc.Net.ClientFactory v2.30.0
Grpc.Tools v2.30.0

##### gRPC Service
Grpc.AspNetCore v2.30.0
Grpc.AspNetCore.Web v2.30.0

### What did you do?
My Blazor.NET WebAssembly works fine calling grpc in my local machine (https://localhost:5001)

But when I call it from my domain (https://grpc.domain.com) it said:  
> Access to fetch at 'https://grpc.blazor.hometemp.bidipeppercrap.com/character.Character/SearchCharacter' from origin 'https://localhost:44395' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

When I call with curl, the result is the same for localhost:5000 and http

I use Nginx to proxy pass localhost:5000 to my https domain (ssl configured with certbot)

#### When I use cURL
![curl](https://imgur.com/J5Ers33.png "Curl")

#### Response header from the server (gRPC Service)
![response header](https://imgur.com/YI2ead7.png "Response Header")

---

### Blazor.NET Configuration
```
        public static async Task Main(string[] args)
        {
            var builder = WebAssemblyHostBuilder.CreateDefault(args);
            builder.RootComponents.Add<App>("app");

            builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });

            builder.Services.AddSingleton(services =>
            {
                var httpHandler = new GrpcWebHandler(GrpcWebMode.GrpcWeb, new HttpClientHandler());

                return GrpcChannel.ForAddress("https://grpc.blazor.hometemp.bidipeppercrap.com", new GrpcChannelOptions { HttpHandler = httpHandler });
            });

            await builder.Build().RunAsync();
        }
```

---

### gRPC Service Configuration
```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContextPool<SpellTestContext>(options => options
                .UseMySql(Configuration.GetConnectionString("SpellTestConnection")));

            services.AddGrpc();

            services.AddCors(o => o.AddPolicy("AllowAll", builder =>
            {
                builder.AllowAnyOrigin()
                    .AllowAnyMethod()
                    .AllowAnyHeader()
                    .WithExposedHeaders("Grpc-Status", "Grpc-Message", "Grpc-Encoding", "Grpc-Accept-Encoding");
            }));
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();

            app.UseGrpcWeb();

            app.UseCors();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapGrpcService<CharacterService>().EnableGrpcWeb().RequireCors("AllowAll");

                endpoints.MapGet("/", async context =>
                {
                    await context.Response.WriteAsync("Communication with gRPC endpoints must be made through a gRPC client. To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909");
                });
            });
        }
```

**Comment by JamesNK** [comment]
I tested deploying the Blazor sample to http://grpcblazor.azurewebsites.net/ with CORS enabled in ASP.NET Core, and I was able to combine Blazor + gRPC-Web + CORS successfully.

https://github.com/JamesNK/grpc-dotnet/commit/c74b746e41a08985c1d8c7c21d5e425d159011e6

Do you have CORS configured on the App Service? If the App Service has CORS configured then it overrides what happens in ASP.NET Core.

**Comment by bidipeppercrap** [comment]
> I tested deploying the Blazor sample to http://grpcblazor.azurewebsites.net/ with CORS enabled in ASP.NET Core, and I was able to combine Blazor + gRPC-Web + CORS successfully.
> 
> https://github.com/JamesNK/grpc-dotnet/commit/c74b746e41a08985c1d8c7c21d5e425d159011e6
> 
> Do you have CORS configured on the App Service? If the App Service has CORS configured then it overrides what happens in ASP.NET Core.

I don't use App Service
I use VM

**Comment by JamesNK** [comment]
Ok. Sorry I don't know what the issue is. Blazor + gRPC-Web + CORS works successfully, so I don't believe it is an issue in the gRPC or gRPC-Web implementations. Perhaps there is configuration in the VM that is blocking preflight requests? I don't know.

**Comment by bidipeppercrap** [comment]
@JamesNK 
I use Nginx to proxy pass localhost:5000 to https

**Comment by bidipeppercrap** [comment]
RESOLVED!

I need to specify the http2 and grpc_pass to my nginx server block config!

I change my nginx server block config to this:

```
upstream mylovely_service {
    server localhost:5000;
}

server {
    listen 443 ssl http2;
    # cert and stuffs

    location / {
        grpc_pass grpcs://mylovely_service;
    }
}
````

**Comment by drodic** [comment]
Hi @bidipeppercrap, 
I also struggle for a long time with same thing, but I can't get apps to run.
Could you be so nice and send complete example of your nginx.config file and Dockerfile of both apps, and description of how your grpc service and Blazor wasm app are configured and deployed.
Thank you in advance.

**Comment by bidipeppercrap** [comment]
> Hi @bidipeppercrap, 
> I also struggle for a long time with same thing, but I can't get apps to run.
> Could you be so nice and send complete example of your nginx.config file and Dockerfile of both apps, and description of how your grpc service and Blazor wasm app are configured and deployed.
> Thank you in advance.
> 

I already gave my nginx config in my comment

**Comment by drodic** [comment]
I thought it was just part of the nginx.conf file 🙂. And what is localhost: 5000, is that grpc uri server or uri application from which you call grpc service?

**Comment by wrosenuance** [comment]
I had this error and found that I had to add "X-Grpc-Web" and "User-Agent" to the headers exposed to the application by the CORS policy.

```csharp
services.AddCors(o => o.AddPolicy("AllowAll", builder =>
{
    builder.AllowAnyOrigin()
        .AllowAnyMethod()
        .AllowAnyHeader()
        .WithExposedHeaders("Grpc-Status", "Grpc-Message", "Grpc-Encoding", "Grpc-Accept-Encoding", "X-Grpc-Web", "User-Agent");
}));
```

I had started with the original poster's code so I also had the `RequireCors("AllowAll")` call referencing the above policy after `EnableGrpcWeb()`.

```csharp
app.UseRouting();
app.UseGrpcWeb();
app.UseCors();

app.UseEndpoints(endpoints =>
{
  endpoints.MapGrpcService<CharacterService>().EnableGrpcWeb().RequireCors("AllowAll");

  // ...snip... 
});

```

This seemed to fix things for me! I hope it helps anyone else who winds up here when searching for this error.

**Comment by stasberkov** [comment]
Official docs how to use grpc-web with CORS https://learn.microsoft.com/en-us/aspnet/core/grpc/grpcweb?view=aspnetcore-8.0
